nidas: nidas::dynld::isff::PacketInputStream Class Reference
nidas::dynld::isff::PacketInputStream Class Reference
#include <PacketInputStream.h>
Public Types
typedef nidas::core::dsm_time_t dsm_time_t
Public Member Functions
PacketInputStream (nidas::core::IOChannel *iochannel=0) throw (nidas::util::InvalidParameterException)
Constructor.
PacketInputStream (const PacketInputStream &x, nidas::core::IOChannel *iochannel)
Copy constructor, with a new, connected IOChannel.
virtual PacketInputStream * clone (nidas::core::IOChannel *iochannel)
Create a clone, with a new, connected IOChannel.
virtual ~PacketInputStream ()
std::string getName () const
std::list< const nidas::core::SampleTag * > getSampleTags () const
What SampleTags am I a SampleSource for?
void init () throw ()
nidas::core::Sample * readSample () throw (nidas::util::IOException)
Read the next sample from the InputStream.
bool readSamples () throw (nidas::util::IOException)
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients and DSMSensors.
void close () throw (nidas::util::IOException)
void flush () throw ()
Implementation of SampleSource::flush().
int getFd () const
virtual void setIOChannel (nidas::core::IOChannel *val)
Set the IOChannel for this SampleInputStream.h.
void readInputHeader ()
Read archive information at beginning of input stream or file.
bool parseInputHeader ()
const nidas::core::SampleInputHeader & getInputHeader () const
void requestConnection (nidas::core::DSMService *)
virtual nidas::core::SampleInput * getOriginal () const
nidas::core::SampleInput * connected (nidas::core::IOChannel *iochan) throw ()
Implementation of IOChannelRequester::connected.
void setNonBlocking (bool val)
bool isNonBlocking () const
const nidas::core::DSMConfig * getDSMConfig () const
What DSM am I connnected to? May be NULL if it cannot be determined.
void setKeepStats (bool val)
void addSampleTag (const nidas::core::SampleTag *tag) throw ()
Implementation of SampleInput::addSampleTag().
void removeSampleTag (const nidas::core::SampleTag *tag) throw ()
nidas::core::SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
nidas::core::SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
nidas::core::SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (nidas::core::SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (nidas::core::SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (nidas::core::SampleClient *client, const nidas::core::SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (nidas::core::SampleClient *client, const nidas::core::SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const nidas::core::SampleStats & getSampleStats () const
void search (const nidas::util::UTime &tt)
Search forward until a sample header is read whose time is greater than or equal to tt.
void distribute (const nidas::core::Sample *s) throw ()
Distribute a sample to my clients.
size_t getBadSamples () const
void setBadSampleFilter (const nidas::core::BadSampleFilter &bsf)
Replace the bad sample filter rules for this stream with bsf.
void setFilterBadSamples (bool val)
See BadSampleFilter.
void setMinDsmId (int val)
See BadSampleFilter.
void setMaxDsmId (int val)
See BadSampleFilter.
void setMinSampleLength (unsigned int val)
See BadSampleFilter.
void setMaxSampleLength (unsigned int val)
See BadSampleFilter.
void setMinSampleTime (const nidas::util::UTime &val)
See BadSampleFilter.
void setMaxSampleTime (const nidas::util::UTime &val)
See BadSampleFilter.
void fromDOMElement (const xercesc::DOMElement *node)
void setExpectHeader (bool val)
bool getExpectHeader () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Attributes
nidas::core::SampleSourceSupport _source
Private Member Functions
const nidas::core::SampleTag * findSampleTag (int configId, int goesId, int sampleId) throw (nidas::util::InvalidParameterException)
const GOESProject * getGOESProject (int configid) const throw (nidas::util::InvalidParameterException)
PacketInputStream (const PacketInputStream &)
No copy.
PacketInputStream & operator= (const PacketInputStream &)
No assignment.
nidas::core::Sample * nextSample ()
Unpack the next sample from the InputStream.
nidas::core::Sample * nextSample (bool keepreading, bool searching=false, dsm_time_t search_time=LONG_LONG_MIN)
Unpack the next sample from the InputStream buffer or by reading more data if keepreading is true.
void checkUnexpectedEOF ()
ReadResult readBlock (bool keepreading, char *&ptr, size_t &lentoread)
Read a block into memory, updating the given block pointer and length counter accordingly.
ReadResult read (bool keepreading, char *ptr, size_t lentoread)
All reads of the iostream go through here.
void handleNewInput ()
Whenever we are at the start of a new input, we need to start over with parsing the input header.
nidas::core::Sample * handleEOF (bool keepreading)
When EOF has been caught, then either we need to return the last pending sample, or else we need to throw the exception.
void closeBlocks ()
nidas::core::Sample * sampleFromHeader () throw ()
Check the current header for validity and generate a sample for it.
Private Attributes
nidas::core::IOChannel * _iochan
nidas::core::IOStream * _iostream
PacketParser * _packetParser
std::map< int, GOESProject * > _projectsByConfigId
nidas::core::DSMService * _service
Service that has requested my input.
const nidas::core::DSMConfig * _dsm
bool _expectHeader
bool _inputHeaderParsed
nidas::core::SampleHeader _sheader
size_t _headerToRead
char * _hptr
nidas::core::Sample * _samp
Will be non-null if we have previously read part of a sample from the stream.
nidas::core::Sample * _sampPending
The currently pending sample.
size_t _dataToRead
How many bytes left to read from the stream into the data portion of samp.
char * _dptr
Pointer into the data portion of samp where we will read next.
bool _skipSample
This is set if the data for the current sample header should be read but skipped, because the sample is the first after a block of bad samples and thus the time at the front of the sample might still be corrupt.
BlockStats _block
Information about the current block of samples, good or bad.
size_t _badSamples
Number of bad samples in the stream so far, which is to say number of bytes checked which did not contain a reasonable sample header.
size_t _goodSamples
Number of good samples in the stream so far.
nidas::core::SampleInputHeader _inputHeader
nidas::core::BadSampleFilter _bsf
SampleInputStream * _original
bool _raw
std::string _last_name
Keep the current name of the input stream so it can be
referenced even after the input stream has advanced to a new input name.
nidas::util::EOFException _eofx
bool _ateof
Static Private Attributes
static XMLCh * namespaceURI = 0
Member Typedef Documentation
dsm_time_t
typedef nidas::core::dsm_time_t nidas::dynld::SampleInputStream::dsm_time_t inherited
Constructor & Destructor Documentation
PacketInputStream() [1/3]
PacketInputStream::PacketInputStream (nidas::core::IOChannel * iochannel = 0) throw (nidas::util::InvalidParameterException)
Constructor.
Parameters
iochannel The IOChannel that we use for data input. SampleInputStream will own the pointer to the IOChannel, and will delete it in ~SampleInputStream(). If it is a null pointer, then it must be set within the fromDOMElement method.
Referenced by clone().
PacketInputStream() [2/3]
PacketInputStream::PacketInputStream (const PacketInputStream & x, nidas::core::IOChannel * iochannel)
Copy constructor, with a new, connected IOChannel.
References _iochan, _iostream, and nidas::core::IOChannel::getBufferSize().
~PacketInputStream()
PacketInputStream::~PacketInputStream () virtual
References _iochan, _iostream, _packetParser, and _projectsByConfigId.
PacketInputStream() [3/3]
nidas::dynld::isff::PacketInputStream::PacketInputStream (const PacketInputStream &) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::dynld::SampleInputStream::addSampleClient (nidas::core::SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by DataDump::run(), and DataStats::run().
addSampleClientForTag()
void nidas::dynld::SampleInputStream::addSampleClientForTag (nidas::core::SampleClient * client, const nidas::core::SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
addSampleTag()
void nidas::dynld::SampleInputStream::addSampleTag (const nidas::core::SampleTag * tag) throw () inline virtual inherited
Implementation of SampleInput::addSampleTag().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleTag().
Referenced by nidas::dynld::raf::SyncServer::initSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
checkUnexpectedEOF()
void SampleInputStream::checkUnexpectedEOF () private inherited
References nidas::dynld::SampleInputStream::_dataToRead, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_last_name, nidas::dynld::SampleInputStream::_samp, nidas::dynld::SampleInputStream::_sheader, CNAME, nidas::core::Sample::getDataByteLength(), nidas::core::SampleHeader::getSizeOf(), and WLOG.
Referenced by nidas::dynld::SampleInputStream::read().
clone()
PacketInputStream * PacketInputStream::clone (nidas::core::IOChannel * iochannel) virtual
Create a clone, with a new, connected IOChannel.
Reimplemented from nidas::dynld::SampleInputStream.
References PacketInputStream().
close()
void PacketInputStream::close () throw (nidas::util::IOException) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::SampleInput.
References _iochan, _iostream, _packetParser, and nidas::core::IOChannel::close().
Referenced by PacketDecode::run().
closeBlocks()
void SampleInputStream::closeBlocks () private inherited
References nidas::dynld::SampleInputStream::_badSamples, nidas::dynld::SampleInputStream::_block, nidas::dynld::SampleInputStream::_bsf, nidas::dynld::SampleInputStream::_goodSamples, nidas::dynld::SampleInputStream::_last_name, nidas::dynld::BlockStats::block_start, CNAME, DLOG, nidas::core::BadSampleFilter::filterBadSamples(), nidas::util::LogContext::log(), LOG_DEBUG, LOG_WARNING, and nidas::dynld::BlockStats::nbytes.
Referenced by nidas::dynld::SampleInputStream::close(), and nidas::dynld::SampleInputStream::handleNewInput().
connected()
SampleInput * SampleInputStream::connected (nidas::core::IOChannel * iochan) throw () virtual inherited
Implementation of IOChannelRequester::connected.
One can use this method to notify SampleInputStream that the IOChannel is connected, which will cause SampleInputStream to open the IOStream.
Implements nidas::core::IOChannelRequester.
distribute()
void nidas::dynld::SampleInputStream::distribute (const nidas::core::Sample * s) throw () inline inherited
Distribute a sample to my clients.
One could use this to insert a sample into the stream.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::distribute().
Referenced by nidas::dynld::raf::SyncServer::handleSample().
findSampleTag()
const SampleTag * PacketInputStream::findSampleTag (int configId, int goesId, int sampleId) throw (nidas::util::InvalidParameterException) private
References DLOG, nidas::dynld::isff::GOESProject::getSampleTag(), and nidas::dynld::isff::GOESProject::getStationNumber().
Referenced by readSamples().
flush()
void nidas::dynld::isff::PacketInputStream::flush () throw () inline virtual
Implementation of SampleSource::flush().
Implements nidas::core::SampleSource.
fromDOMElement()
void SampleInputStream::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::dynld::SampleInputStream::_iochan, nidas::core::IOChannel::createIOChannel(), nidas::core::DOMable::fromDOMElement(), nidas::core::XDOMAttr::getName(), nidas::dynld::SampleInputStream::setIOChannel(), and WLOG.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getBadSamples()
size_t nidas::dynld::SampleInputStream::getBadSamples () const inline inherited
References nidas::dynld::SampleInputStream::_badSamples.
getClientCount()
int nidas::dynld::SampleInputStream::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getClientCount().
getDSMConfig()
const DSMConfig * SampleInputStream::getDSMConfig () const virtual inherited
What DSM am I connnected to? May be NULL if it cannot be determined.
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_dsm.
getExpectHeader()
bool nidas::dynld::SampleInputStream::getExpectHeader () const inline inherited
References nidas::dynld::SampleInputStream::_expectHeader.
getFd()
int SampleInputStream::getFd () const virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::getFd().
getGOESProject()
const GOESProject * PacketInputStream::getGOESProject (int configid) const throw (nidas::util::InvalidParameterException) private
References nidas::core::Project::getInstance(), nidas::core::ParameterT< T >::getLength(), nidas::core::Project::getName(), nidas::core::Project::getParameter(), nidas::core::Parameter::getType(), nidas::core::ParameterT< T >::getValue(), and nidas::core::Parameter::INT_PARAM.
Referenced by getSampleTags(), and readSamples().
getInputHeader()
const nidas::core::SampleInputHeader& nidas::dynld::SampleInputStream::getInputHeader () const inline inherited
References nidas::dynld::SampleInputStream::_inputHeader.
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::raf::SyncServer::openStream(), DataDump::run(), DataStats::run(), DataPrep::run(), MergeVerifier::run(), NidsMerge::run(), ExtractFast2D::run(), ExtractDMT::run(), SensorExtract::run(), and StatsProcess::run().
getName()
string PacketInputStream::getName () const virtual
Implements nidas::core::SampleInput.
References _iochan, and nidas::core::IOChannel::getName().
Referenced by readSample(), and readSamples().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getOriginal()
virtual nidas::core::SampleInput* nidas::dynld::SampleInputStream::getOriginal () const inline virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_original.
getProcessedSampleSource()
nidas::core::SampleSource* nidas::dynld::SampleInputStream::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getProcessedSampleSource().
getRawSampleSource()
nidas::core::SampleSource* nidas::dynld::SampleInputStream::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getRawSampleSource().
getSampleStats()
const nidas::core::SampleStats& nidas::dynld::SampleInputStream::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
nidas::core::SampleTagIterator nidas::dynld::SampleInputStream::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
list< const SampleTag * > PacketInputStream::getSampleTags () const virtual
What SampleTags am I a SampleSource for?
Implements nidas::core::SampleSource.
References getGOESProject(), and nidas::dynld::isff::GOESProject::getSampleTags().
Referenced by PacketDecode::run().
handleEOF()
Sample * SampleInputStream::handleEOF (bool keepreading) private inherited
When EOF has been caught, then either we need to return the last pending sample, or else we need to throw the exception.
HOWEVER, because nextSample() is not allowed to throw an IOException when keepreading is false, since in general it does not make sense to trigger EOF when nothing is being read, this handler only throws the exception when keepreading is true.
References nidas::dynld::SampleInputStream::_eofx, nidas::dynld::SampleInputStream::_sampPending, CNAME, and DLOG.
Referenced by nidas::dynld::SampleInputStream::nextSample(), and nidas::dynld::SampleInputStream::readSamples().
handleNewInput()
void SampleInputStream::handleNewInput () private inherited
Whenever we are at the start of a new input, we need to start over with parsing the input header.
This method sets up the right state to start over on a new file.
References nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_iostream, nidas::core::IOStream::backup(), nidas::dynld::SampleInputStream::closeBlocks(), CNAME, DLOG, nidas::core::IOStream::getNumInputBytes(), and VLOG.
Referenced by nidas::dynld::SampleInputStream::read().
init()
void PacketInputStream::init () throw ()
References _iochan, _iostream, _packetParser, nidas::core::IOChannel::getBufferSize(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
Referenced by PacketDecode::run().
isNonBlocking()
bool SampleInputStream::isNonBlocking () const virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::isNonBlocking().
nextSample() [1/2]
Sample * SampleInputStream::nextSample () private inherited
Unpack the next sample from the InputStream.
This method does not perform any physical reads, so it should not throw EOFException or IOException.
Returns
pointer to a sample if there is one available in the buffer, else NULL.
Referenced by nidas::dynld::SampleInputStream::flush(), nidas::dynld::SampleInputStream::readSample(), nidas::dynld::SampleInputStream::readSamples(), and nidas::dynld::SampleInputStream::search().
nextSample() [2/2]
Sample * SampleInputStream::nextSample (bool keepreading, bool searching = false, dsm_time_t search_time = LONG_LONG_MIN) private inherited
Unpack the next sample from the InputStream buffer or by reading more data if keepreading is true.
If searching is set, then reading stops after the first sample header found whose time tag is after search_time, as described in the search() method.
Exceptions
nidas::util::IOException
References nidas::dynld::SampleInputStream::_ateof, nidas::dynld::SampleInputStream::_bsf, nidas::dynld::SampleInputStream::_dataToRead, nidas::dynld::SampleInputStream::_dptr, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_hptr, nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_samp, nidas::dynld::SampleInputStream::_sampPending, nidas::dynld::SampleInputStream::_sheader, nidas::dynld::SampleInputStream::_skipSample, CNAME, DLOG, nidas::dynld::SampleInputStream::ReadResult::eof, nidas::core::BadSampleFilter::filterBadSamples(), nidas::util::UTime::format(), nidas::core::Sample::freeReference(), nidas::core::SampleHeader::getDataByteLength(), nidas::core::Sample::getDataByteLength(), nidas::core::SampleHeader::getRawId(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleHeader::getTimeTag(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::getVoidDataPtr(), nidas::dynld::SampleInputStream::handleEOF(), nidas::dynld::SampleInputStream::ReadResult::newinput, nidas::dynld::SampleInputStream::readBlock(), nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::sampleFromHeader(), nidas::core::SampleHeader::setDataByteLength(), nidas::core::SampleHeader::setRawId(), nidas::core::SampleHeader::setTimeTag(), VLOG, and WLOG.
operator=()
PacketInputStream& nidas::dynld::isff::PacketInputStream::operator= (const PacketInputStream &) private
No assignment.
parseInputHeader()
bool SampleInputStream::parseInputHeader () inherited
Exceptions
nidas::util::IOException
References nidas::dynld::SampleInputStream::_bsf, nidas::dynld::SampleInputStream::_dataToRead, nidas::dynld::SampleInputStream::_expectHeader, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_hptr, nidas::dynld::SampleInputStream::_inputHeader, nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_iostream, nidas::dynld::SampleInputStream::_samp, nidas::dynld::SampleInputStream::_sheader, nidas::core::IOStream::backup(), CNAME, DLOG, nidas::core::Sample::freeReference(), nidas::dynld::SampleInputStream::getName(), nidas::core::IOStream::getNumInputBytes(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleInputHeader::parse(), PLOG, nidas::core::BadSampleFilter::skipNidasHeader(), and nidas::util::Exception::what().
Referenced by nidas::dynld::SampleInputStream::readInputHeader().
read()
SampleInputStream::ReadResult SampleInputStream::read (bool keepreading, char * ptr, size_t lentoread) private inherited
All reads of the iostream go through here.
There are three kinds of reads needed:
Read to fill the iostream buffer but not a local block. (ptr==0 and keepreading=true)
Read from the iostream buffer into a local block (keepreading==false).
Read from the iostream to fill a local block, filling the buffer as needed (keepreading=true)
In all these cases, we need to catch if we hit the end of a file to know if the file ended unexpectedly. Also, if we hit the end of a file and a sample is still pending (because filtering is enabled and a sample is not good until it passes the filter and is succeeded by eof or another good sample), then we also need to return that sample. This method records the eof exception but does not pass it on, waiting instead for it to be thrown after any pending sample has been returned by nextSample(). Callers can test ReadResult members for which cases have occurred.
References nidas::dynld::SampleInputStream::_ateof, nidas::dynld::SampleInputStream::_eofx, nidas::dynld::SampleInputStream::_iostream, nidas::core::IOStream::available(), nidas::dynld::SampleInputStream::checkUnexpectedEOF(), CNAME, DLOG, nidas::dynld::SampleInputStream::ReadResult::eof, nidas::dynld::SampleInputStream::handleNewInput(), nidas::core::IOStream::isNewInput(), nidas::dynld::SampleInputStream::ReadResult::len, nidas::dynld::SampleInputStream::ReadResult::newinput, nidas::core::IOStream::read(), nidas::core::IOStream::readBuf(), and VLOG.
Referenced by nidas::dynld::SampleInputStream::readBlock(), and nidas::dynld::SampleInputStream::readSamples().
readBlock()
SampleInputStream::ReadResult SampleInputStream::readBlock (bool keepreading, char *& ptr, size_t & lentoread) private inherited
Read a block into memory, updating the given block pointer and length counter accordingly.
If keepreading is false, only read into the block what is available from the iostream buffer. Return the ReadResult of the last read. Always return if the current input ends or eof is reached.
References nidas::dynld::SampleInputStream::ReadResult::eof, nidas::dynld::SampleInputStream::ReadResult::len, nidas::dynld::SampleInputStream::ReadResult::newinput, and nidas::dynld::SampleInputStream::read().
Referenced by nidas::dynld::SampleInputStream::nextSample().
readInputHeader()
void SampleInputStream::readInputHeader () inherited
Read archive information at beginning of input stream or file.
Exceptions
nidas::util::IOException
References nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_iostream, nidas::dynld::SampleInputStream::_last_name, CNAME, DLOG, nidas::dynld::SampleInputStream::getName(), nidas::core::IOStream::getNumInputBytes(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::core::IOStream::read().
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::raf::SyncServer::openStream(), DataStats::readHeader(), DataDump::run(), DataPrep::run(), MergeVerifier::run(), NidsMerge::run(), ExtractFast2D::run(), ExtractDMT::run(), SensorExtract::run(), and StatsProcess::run().
readSample()
nidas::core::Sample* nidas::dynld::isff::PacketInputStream::readSample () throw (nidas::util::IOException) inline virtual
Read the next sample from the InputStream.
The caller must call freeReference on the sample when they're done with it. This method may perform zero or more reads of the IOChannel.
Implements nidas::core::SampleInput.
References getName().
readSamples()
bool PacketInputStream::readSamples () throw (nidas::util::IOException) virtual
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients and DSMSensors.
This will perform only one physical read of the underlying IOChannel and so is appropriate to use when a select() has determined that there is data available on our file descriptor.
Implements nidas::core::SampleInput.
References _iostream, _packetParser, nidas::dynld::SampleInputStream::_source, nidas::core::SampleSourceSupport::distribute(), DLOG, findSampleTag(), nidas::util::UTime::format(), nidas::dynld::isff::PacketInfo::getChannel(), nidas::dynld::isff::PacketParser::getConfigId(), nidas::core::SampleT< DataT >::getDataLength(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::dynld::isff::PacketInfo::getFreqOffset(), getGOESProject(), nidas::dynld::isff::GOESProject::getGOESSampleTag(), nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), getName(), nidas::dynld::isff::PacketParser::getPacketInfo(), nidas::dynld::isff::PacketParser::getPacketTime(), nidas::dynld::isff::PacketParser::getSampleId(), nidas::dynld::isff::PacketInfo::getSignalStrength(), nidas::dynld::isff::PacketParser::getStationId(), nidas::dynld::isff::GOESProject::getStationNumber(), nidas::dynld::isff::PacketInfo::getStatusInt(), nidas::core::SampleTag::getVariables(), nidas::dynld::isff::GOESProject::getXmitInterval(), nidas::dynld::isff::GOESProject::getXmitOffset(), len, nidas::util::Logger::log(), LOG_WARNING, nidas::dynld::isff::PacketParser::NESDIS_PT, nidas::dynld::isff::PacketParser::parse(), nidas::dynld::isff::PacketParser::parseData(), nidas::core::IOStream::readUntil(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), nidas::util::UTime::toUsecs(), USECS_PER_SEC, and nidas::util::Exception::what().
Referenced by PacketDecode::run().
removeSampleClient()
void nidas::dynld::SampleInputStream::removeSampleClient (nidas::core::SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by DataDump::run(), and DataStats::run().
removeSampleClientForTag()
void nidas::dynld::SampleInputStream::removeSampleClientForTag (nidas::core::SampleClient * c, const nidas::core::SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
removeSampleTag()
void nidas::dynld::SampleInputStream::removeSampleTag (const nidas::core::SampleTag *) throw () inline virtual inherited
Exceptions
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleTag().
requestConnection()
void SampleInputStream::requestConnection (nidas::core::DSMService * requester) virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, nidas::dynld::SampleInputStream::_service, and nidas::core::IOChannel::requestConnection().
sampleFromHeader()
Sample * SampleInputStream::sampleFromHeader () throw () private inherited
Check the current header for validity and generate a sample for it.
References nidas::dynld::SampleInputStream::_badSamples, nidas::dynld::SampleInputStream::_block, nidas::dynld::SampleInputStream::_bsf, nidas::dynld::SampleInputStream::_goodSamples, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_hptr, nidas::dynld::SampleInputStream::_iostream, nidas::dynld::SampleInputStream::_sheader, nidas::dynld::SampleInputStream::_skipSample, nidas::util::LogContext::active(), nidas::dynld::BlockStats::addGoodSample(), CNAME, nidas::dynld::BlockStats::endBadBlock(), nidas::core::BadSampleFilter::filterBadSamples(), ftime(), nidas::core::SampleHeader::getDataByteLength(), nidas::core::SampleHeader::getId(), nidas::dynld::SampleInputStream::getName(), nidas::core::IOStream::getNumInputBytes(), nidas::core::getSample(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleHeader::getTimeTag(), nidas::core::SampleHeader::getType(), nidas::dynld::BlockStats::good, nidas::core::BadSampleFilter::invalidSampleHeader(), nidas::util::LogContext::log(), LOG_DEBUG, LOG_WARNING, nidas::dynld::BlockStats::nbytes, nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), nidas::dynld::BlockStats::start_time, nidas::dynld::BlockStats::startBadBlock(), and WLOG.
Referenced by nidas::dynld::SampleInputStream::nextSample().
search()
void SampleInputStream::search (const nidas::util::UTime & tt) inherited
Search forward until a sample header is read whose time is greater than or equal to tt.
Leaves the InputStream positioned so that the next call to readSample() or readSamples() will read the rest of the sample.
Exceptions
nidas::util::IOException
References CNAME, DLOG, nidas::util::UTime::format(), nidas::dynld::SampleInputStream::nextSample(), and nidas::util::UTime::toUsecs().
Referenced by DataPrep::run(), and StatsProcess::run().
setBadSampleFilter()
void nidas::dynld::SampleInputStream::setBadSampleFilter (const nidas::core::BadSampleFilter & bsf) inline inherited
Replace the bad sample filter rules for this stream with bsf.
References nidas::dynld::SampleInputStream::_bsf.
Referenced by DataDump::run(), DataStats::run(), DataPrep::run(), NidsMerge::run(), and StatsProcess::run().
setExpectHeader()
void nidas::dynld::SampleInputStream::setExpectHeader (bool val) inline inherited
References nidas::dynld::SampleInputStream::_expectHeader.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
setFilterBadSamples()
void nidas::dynld::SampleInputStream::setFilterBadSamples (bool val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setFilterBadSamples().
setIOChannel()
void SampleInputStream::setIOChannel (nidas::core::IOChannel * val) virtual inherited
Set the IOChannel for this SampleInputStream.h.
References nidas::dynld::SampleInputStream::_dsm, nidas::dynld::SampleInputStream::_iochan, nidas::core::IOChannel::close(), nidas::core::Project::findDSM(), nidas::core::IOChannel::getConnectionInfo(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::core::Project::getInstance(), nidas::core::ConnectionInfo::getRemoteSocketAddress(), nidas::dynld::SampleInputStream::setExpectHeader(), and nidas::core::IOChannel::writeNidasHeader().
Referenced by nidas::dynld::SampleInputStream::fromDOMElement(), and nidas::dynld::SampleInputStream::SampleInputStream().
setKeepStats()
void nidas::dynld::SampleInputStream::setKeepStats (bool val) inline virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::setKeepStats().
setMaxDsmId()
void nidas::dynld::SampleInputStream::setMaxDsmId (int val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMaxDsmId().
Referenced by nidas::dynld::raf::SyncServer::openStream().
setMaxSampleLength()
void nidas::dynld::SampleInputStream::setMaxSampleLength (unsigned int val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMaxSampleLength().
Referenced by nidas::dynld::raf::SyncServer::openStream(), MergeVerifier::run(), and SensorExtract::run().
setMaxSampleTime()
void nidas::dynld::SampleInputStream::setMaxSampleTime (const nidas::util::UTime & val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMaxSampleTime().
Referenced by nidas::dynld::raf::SyncServer::openStream(), and MergeVerifier::run().
setMinDsmId()
void nidas::dynld::SampleInputStream::setMinDsmId (int val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMinDsmId().
setMinSampleLength()
void nidas::dynld::SampleInputStream::setMinSampleLength (unsigned int val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMinSampleLength().
setMinSampleTime()
void nidas::dynld::SampleInputStream::setMinSampleTime (const nidas::util::UTime & val) inline inherited
See BadSampleFilter.
References nidas::dynld::SampleInputStream::_bsf, and nidas::core::BadSampleFilter::setMinSampleTime().
Referenced by nidas::dynld::raf::SyncServer::openStream(), and MergeVerifier::run().
setNonBlocking()
void SampleInputStream::setNonBlocking (bool val) virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::setNonBlocking().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_ateof
bool nidas::dynld::SampleInputStream::_ateof private inherited
Referenced by nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::read(), and nidas::dynld::SampleInputStream::readSamples().
_badSamples
size_t nidas::dynld::SampleInputStream::_badSamples private inherited
Number of bad samples in the stream so far, which is to say number of bytes checked which did not contain a reasonable sample header.
Referenced by nidas::dynld::SampleInputStream::closeBlocks(), nidas::dynld::SampleInputStream::getBadSamples(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_block
BlockStats nidas::dynld::SampleInputStream::_block private inherited
Information about the current block of samples, good or bad.
Referenced by nidas::dynld::SampleInputStream::closeBlocks(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_bsf
nidas::core::BadSampleFilter nidas::dynld::SampleInputStream::_bsf private inherited
Referenced by nidas::dynld::SampleInputStream::closeBlocks(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), nidas::dynld::SampleInputStream::sampleFromHeader(), nidas::dynld::SampleInputStream::setBadSampleFilter(), nidas::dynld::SampleInputStream::setFilterBadSamples(), nidas::dynld::SampleInputStream::setMaxDsmId(), nidas::dynld::SampleInputStream::setMaxSampleLength(), nidas::dynld::SampleInputStream::setMaxSampleTime(), nidas::dynld::SampleInputStream::setMinDsmId(), nidas::dynld::SampleInputStream::setMinSampleLength(), and nidas::dynld::SampleInputStream::setMinSampleTime().
_dataToRead
size_t nidas::dynld::SampleInputStream::_dataToRead private inherited
How many bytes left to read from the stream into the data portion of samp.
Referenced by nidas::dynld::SampleInputStream::checkUnexpectedEOF(), nidas::dynld::SampleInputStream::nextSample(), and nidas::dynld::SampleInputStream::parseInputHeader().
_dptr
char* nidas::dynld::SampleInputStream::_dptr private inherited
Pointer into the data portion of samp where we will read next.
Referenced by nidas::dynld::SampleInputStream::nextSample().
_dsm
const nidas::core::DSMConfig* nidas::dynld::SampleInputStream::_dsm private inherited
Referenced by nidas::dynld::SampleInputStream::getDSMConfig(), and nidas::dynld::SampleInputStream::setIOChannel().
_eofx
nidas::util::EOFException nidas::dynld::SampleInputStream::_eofx private inherited
Referenced by nidas::dynld::SampleInputStream::handleEOF(), and nidas::dynld::SampleInputStream::read().
_expectHeader
bool nidas::dynld::SampleInputStream::_expectHeader private inherited
Referenced by nidas::dynld::SampleInputStream::getExpectHeader(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::setExpectHeader().
_goodSamples
size_t nidas::dynld::SampleInputStream::_goodSamples private inherited
Number of good samples in the stream so far.
Referenced by nidas::dynld::SampleInputStream::closeBlocks(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_headerToRead
size_t nidas::dynld::SampleInputStream::_headerToRead private inherited
Referenced by nidas::dynld::SampleInputStream::checkUnexpectedEOF(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_hptr
char* nidas::dynld::SampleInputStream::_hptr private inherited
Referenced by nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_inputHeader
nidas::core::SampleInputHeader nidas::dynld::SampleInputStream::_inputHeader private inherited
Referenced by nidas::dynld::SampleInputStream::getInputHeader(), and nidas::dynld::SampleInputStream::parseInputHeader().
_inputHeaderParsed
bool nidas::dynld::SampleInputStream::_inputHeaderParsed private inherited
Referenced by nidas::dynld::SampleInputStream::handleNewInput(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::readInputHeader().
_iochan
nidas::core::IOChannel* nidas::dynld::isff::PacketInputStream::_iochan private
Referenced by close(), getName(), init(), PacketInputStream(), and ~PacketInputStream().
_iostream
nidas::core::IOStream* nidas::dynld::isff::PacketInputStream::_iostream private
Referenced by close(), init(), PacketInputStream(), readSamples(), and ~PacketInputStream().
_last_name
std::string nidas::dynld::SampleInputStream::_last_name private inherited
Keep the current name of the input stream so it can be
referenced even after the input stream has advanced to a new input name.
Referenced by nidas::dynld::SampleInputStream::checkUnexpectedEOF(), nidas::dynld::SampleInputStream::closeBlocks(), and nidas::dynld::SampleInputStream::readInputHeader().
_original
SampleInputStream* nidas::dynld::SampleInputStream::_original private inherited
Referenced by nidas::dynld::SampleInputStream::getOriginal().
_packetParser
PacketParser* nidas::dynld::isff::PacketInputStream::_packetParser private
Referenced by close(), init(), readSamples(), and ~PacketInputStream().
_projectsByConfigId
std::map<int,GOESProject*> nidas::dynld::isff::PacketInputStream::_projectsByConfigId mutable private
Referenced by ~PacketInputStream().
_raw
bool nidas::dynld::SampleInputStream::_raw private inherited
_samp
nidas::core::Sample* nidas::dynld::SampleInputStream::_samp private inherited
Will be non-null if we have previously read part of a sample from the stream.
Referenced by nidas::dynld::SampleInputStream::checkUnexpectedEOF(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::~SampleInputStream().
_sampPending
nidas::core::Sample* nidas::dynld::SampleInputStream::_sampPending private inherited
The currently pending sample.
When filtering is active, the pending sample is held until the succeeding sample header is confirmed to be good.
Referenced by nidas::dynld::SampleInputStream::handleEOF(), nidas::dynld::SampleInputStream::nextSample(), and nidas::dynld::SampleInputStream::~SampleInputStream().
_service
nidas::core::DSMService* nidas::dynld::SampleInputStream::_service private inherited
Service that has requested my input.
Referenced by nidas::dynld::SampleInputStream::requestConnection().
_sheader
nidas::core::SampleHeader nidas::dynld::SampleInputStream::_sheader private inherited
Referenced by nidas::dynld::SampleInputStream::checkUnexpectedEOF(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::SampleInputStream::parseInputHeader(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_skipSample
bool nidas::dynld::SampleInputStream::_skipSample private inherited
This is set if the data for the current sample header should be read but skipped, because the sample is the first after a block of bad samples and thus the time at the front of the sample might still be corrupt.
Referenced by nidas::dynld::SampleInputStream::nextSample(), and nidas::dynld::SampleInputStream::sampleFromHeader().
_source
nidas::core::SampleSourceSupport nidas::dynld::SampleInputStream::_source protected inherited
Referenced by nidas::dynld::SampleInputStream::addSampleClient(), nidas::dynld::SampleInputStream::addSampleClientForTag(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::dynld::SampleInputStream::distribute(), nidas::dynld::SampleInputStream::flush(), nidas::dynld::SampleInputStream::getClientCount(), nidas::dynld::SampleInputStream::getProcessedSampleSource(), nidas::dynld::SampleInputStream::getRawSampleSource(), nidas::dynld::SampleInputStream::getSampleStats(), nidas::dynld::SampleInputStream::getSampleTagIterator(), nidas::dynld::SampleInputStream::getSampleTags(), readSamples(), nidas::dynld::SampleInputStream::readSamples(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::dynld::SampleInputStream::removeSampleClientForTag(), nidas::dynld::SampleInputStream::removeSampleTag(), and nidas::dynld::SampleInputStream::setKeepStats().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/isff/PacketInputStream.h
nidas/dynld/isff/PacketInputStream.cc