nidas: SampleToDatabase Class Reference
SampleToDatabase Class Reference
Public Member Functions
SampleToDatabase (InfluxDB *db=0, dsm_sample_id_t sid=0, const std::string &sname="", const SampleTag *stag=0)
A default constructor is required to use objects as a map element.
void setSiteAndMeasurement (const SampleTag *stag)
void defaultMeasurementName (const SampleTag *stag)
Generate a default measurement name for SampleTag stag.
bool receive (const Sample *samp) throw ()
void accumulate (const Sample *samp)
SampleToDatabase & operator= (const SampleToDatabase &rhs)
SampleToDatabase (const SampleToDatabase &rhs)
Public Attributes
InfluxDB * _db
string name
dsm_sample_id_t id
string sitename
string measurementName
string spsid
string dsmid
string sampid
string info
vector< string > varunits
vector< string > varnames
Constructor & Destructor Documentation
SampleToDatabase() [1/2]
SampleToDatabase::SampleToDatabase (InfluxDB * db = 0, dsm_sample_id_t sid = 0, const std::string & sname = "", const SampleTag * stag = 0) inline
A default constructor is required to use objects as a map element.
References backslash(), nidas::core::NidasApp::formatId(), nidas::core::NidasApp::getApplicationInstance(), nidas::core::DSMSensor::getHeightString(), nidas::core::VariableConverter::getUnits(), id_to_string(), and WLOG.
SampleToDatabase() [2/2]
SampleToDatabase::SampleToDatabase (const SampleToDatabase & rhs) inline
Member Function Documentation
accumulate()
void SampleToDatabase::accumulate (const Sample * samp)
References nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::core::NidasApp::getApplicationInstance(), nidas::core::Sample::getDataValue(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::getType(), and nidas::core::NidasApp::setException().
defaultMeasurementName()
void SampleToDatabase::defaultMeasurementName (const SampleTag * stag) inline
Generate a default measurement name for SampleTag stag.
References nidas::core::DSMSensor::getCatalogName(), nidas::core::SampleTag::getDSMSensor(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSensorId(), and string_to_lower().
operator=()
SampleToDatabase& SampleToDatabase::operator= (const SampleToDatabase & rhs) inline
References _db, dsmid, id, info, measurementName, name, sampid, sitename, spsid, varnames, and varunits.
receive()
bool SampleToDatabase::receive (const Sample * samp) throw ()
References nidas::core::DOUBLE_ST, and nidas::core::FLOAT_ST.
setSiteAndMeasurement()
void SampleToDatabase::setSiteAndMeasurement (const SampleTag * stag) inline
References nidas::core::Site::getName(), nidas::core::SampleTag::getSite(), and nidas::core::SampleTag::getSuffix().
Member Data Documentation
_db
InfluxDB* SampleToDatabase::_db
Referenced by operator=().
dsmid
string SampleToDatabase::dsmid
Referenced by operator=().
id
dsm_sample_id_t SampleToDatabase::id
Referenced by operator=(), and SampleDispatcher::SampleDispatcher().
info
string SampleToDatabase::info
Referenced by operator=().
measurementName
string SampleToDatabase::measurementName
Referenced by operator=().
name
string SampleToDatabase::name
Referenced by operator=().
sampid
string SampleToDatabase::sampid
Referenced by operator=().
sitename
string SampleToDatabase::sitename
Referenced by operator=().
spsid
string SampleToDatabase::spsid
Referenced by operator=().
varnames
vector<string> SampleToDatabase::varnames
Referenced by operator=().
varunits
vector<string> SampleToDatabase::varunits
Referenced by operator=().
The documentation for this class was generated from the following file:
nidas/apps/data_influxdb.cc