nidas: nidas::util::BitArray Class Reference
nidas::util::BitArray Class Reference
A class for holding bits.
#include <BitArray.h>
Public Member Functions
BitArray (int lenbits)
Constructor, all bits will be initialized to 0.
BitArray (const BitArray &ba)
Copy constructor.
BitArray & operator= (const BitArray &ba)
Assignment operator.
~BitArray ()
void setBits (bool value)
Set all bits to 1 if value is true, otherwise set all to 0.
void setBit (int num, bool value)
Set a bit, in range 0:(length()-1) to 1 if value is true, otherwise false.
void setBits (int begin, int end, unsigned int bitmask)
Set all bits from begin, up to, but not including, end, to the corresponding bits in bitmask.
void setBits64 (int begin, int end, unsigned long long bitmask)
bool getBit (int num) const
Get value of a bit.
unsigned int getBits (int begin, int end)
Return a integer of bits.
long long getBits64 (int begin, int end)
Return a long long of bits.
unsigned char * getPtr ()
Return pointer to first byte of BitArray.
const unsigned char * getConstPtr () const
Return const pointer to first byte of BitArray.
bool any () const
bool all () const
bool any (int begin, int end) const
bool all (int begin, int end) const
int getLength () const
Length of array, in bits.
int getLengthInBytes () const
Length of array, in bytes.
std::string toString () const
BitArray & operator|= (const BitArray &x)
BitArray operator| (const BitArray &x)
BitArray & operator&= (const BitArray &x)
BitArray operator& (const BitArray &x)
BitArray & operator^= (const BitArray &x)
BitArray operator^ (const BitArray &x)
Protected Attributes
unsigned char * bits
To make things portable across different machine endiannesses we represent the bits in an array of chars, rather than in integers.
int lenBits
int lenBytes
Detailed Description
A class for holding bits.
Supports setting/getting individual bits in an array. Could be used by an object that is setting/getting relays, for example.
Constructor & Destructor Documentation
BitArray() [1/2]
BitArray::BitArray (int lenbits)
Constructor, all bits will be initialized to 0.
References bits, lenBytes, and setBits().
BitArray() [2/2]
BitArray::BitArray (const BitArray & ba)
Copy constructor.
References bits, and lenBytes.
~BitArray()
BitArray::~BitArray ()
References bits.
Member Function Documentation
all() [1/2]
bool nidas::util::BitArray::all () const inline
References getBit(), and getLength().
all() [2/2]
bool nidas::util::BitArray::all (int begin, int end) const inline
References getBit(), and getLength().
any() [1/2]
bool nidas::util::BitArray::any () const inline
References getBit(), and getLength().
Referenced by nidas::dynld::raf::CVIProcessor::receive().
any() [2/2]
bool nidas::util::BitArray::any (int begin, int end) const inline
References getBit(), and getLength().
getBit()
bool nidas::util::BitArray::getBit (int num) const inline
Get value of a bit.
Parameters
num Index of bit, in range 0:(getLength()-1). Does not check for indices outside of range.
References bits, and getLength().
Referenced by all(), any(), getBits(), getBits64(), main(), and toString().
getBits()
unsigned int BitArray::getBits (int begin, int end)
Return a integer of bits.
Low order bits in the results will contain the low bits.
References bits, getBit(), and getLength().
Referenced by main().
getBits64()
long long BitArray::getBits64 (int begin, int end)
Return a long long of bits.
Low order bits in the results will contain the low bits.
References bits, getBit(), and getLength().
getConstPtr()
const unsigned char* nidas::util::BitArray::getConstPtr () const inline
Return const pointer to first byte of BitArray.
This will contain bits 0-7.
References bits.
Referenced by nidas::dynld::IR104_Relays::clearOutputs(), nidas::dynld::ViperDIO::clearOutputs(), operator&(), nidas::util::operator&(), operator&=(), nidas::util::operator==(), operator^(), nidas::util::operator^(), operator^=(), operator|(), nidas::util::operator|(), operator|=(), nidas::dynld::IR104_Relays::setOutputs(), and nidas::dynld::ViperDIO::setOutputs().
getLength()
int nidas::util::BitArray::getLength () const inline
Length of array, in bits.
References lenBits.
Referenced by all(), any(), nidas::dynld::IR104_Relays::clearOutputs(), nidas::dynld::ViperDIO::clearOutputs(), getBit(), getBits(), getBits64(), operator&(), nidas::util::operator&(), operator&=(), nidas::util::operator==(), operator^(), nidas::util::operator^(), operator^=(), operator|(), nidas::util::operator|(), operator|=(), setBits(), setBits64(), nidas::dynld::IR104_Relays::setOutputs(), nidas::dynld::ViperDIO::setOutputs(), and toString().
getLengthInBytes()
int nidas::util::BitArray::getLengthInBytes () const inline
Length of array, in bytes.
References lenBytes.
Referenced by operator&(), nidas::util::operator&(), operator&=(), nidas::util::operator==(), operator^(), nidas::util::operator^(), operator^=(), operator|(), nidas::util::operator|(), operator|=(), setBit(), and setBits().
getPtr()
unsigned char* nidas::util::BitArray::getPtr () inline
Return pointer to first byte of BitArray.
This will contain bits 0-7.
References bits.
Referenced by operator&(), nidas::util::operator&(), operator&=(), operator^(), nidas::util::operator^(), operator^=(), operator|(), nidas::util::operator|(), and operator|=().
operator&()
BitArray BitArray::operator& (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
operator&=()
BitArray & BitArray::operator&= (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
operator=()
BitArray & BitArray::operator= (const BitArray & ba)
Assignment operator.
References bits, lenBits, and lenBytes.
operator^()
BitArray BitArray::operator^ (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
operator^=()
BitArray & BitArray::operator^= (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
operator|()
BitArray BitArray::operator| (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
operator|=()
BitArray & BitArray::operator|= (const BitArray & x)
References getConstPtr(), getLength(), getLengthInBytes(), and getPtr().
setBit()
void nidas::util::BitArray::setBit (int num, bool value) inline
Set a bit, in range 0:(length()-1) to 1 if value is true, otherwise false.
Silently ignores requests out of range.
References bits, and getLengthInBytes().
Referenced by main(), nidas::dynld::raf::CVIProcessor::receive(), setBits(), and setBits64().
setBits() [1/2]
void BitArray::setBits (bool value)
Set all bits to 1 if value is true, otherwise set all to 0.
References bits, getLength(), getLengthInBytes(), and setBit().
Referenced by BitArray(), nidas::dynld::IR104_Relays::getInputs(), nidas::dynld::ViperDIO::getInputs(), nidas::dynld::IR104_Relays::getOutputs(), nidas::dynld::ViperDIO::getOutputs(), and main().
setBits() [2/2]
void BitArray::setBits (int begin, int end, unsigned int bitmask)
Set all bits from begin, up to, but not including, end, to the corresponding bits in bitmask.
Bit 0 from bitmask is copied to begin, bit 1 to begin+1, etc.
Parameters
begin Index of first bit, from 0, up to getLength()-1.
end Index of last bit, from begin, up to getLength()-1.
bitmask integer containing source bits to be copied, with bit 0 in the least significant byte. If (end - begin) is greater than 32, then end is silently adjusted to begin+32.
References getLength(), and setBit().
setBits64()
void BitArray::setBits64 (int begin, int end, unsigned long long bitmask)
References getLength(), and setBit().
toString()
std::string BitArray::toString () const
References getBit(), and getLength().
Member Data Documentation
bits
unsigned char* nidas::util::BitArray::bits protected
To make things portable across different machine endiannesses we represent the bits in an array of chars, rather than in integers.
Bits 0-7 are in bits[0], 8-15 in bits[1], etc.
Referenced by BitArray(), getBit(), getBits(), getBits64(), getConstPtr(), getPtr(), operator=(), setBit(), setBits(), and ~BitArray().
lenBits
int nidas::util::BitArray::lenBits protected
Referenced by getLength(), and operator=().
lenBytes
int nidas::util::BitArray::lenBytes protected
Referenced by BitArray(), getLengthInBytes(), and operator=().
The documentation for this class was generated from the following files:
nidas/util/BitArray.h
nidas/util/BitArray.cc