nidas: nidas::core::SampleTracer Class Reference
nidas::core::SampleTracer Class Reference
SampleTracer uses a Logger to log messages about samples as they are encountered in the code.
#include <SampleTracer.h>
Public Member Functions
SampleTracer (int level, const char *file, const char *function, int line)
bool active (const Sample *samp)
bool active (dsm_sample_id_t id)
nidas::util::LogMessage & msg (const Sample *samp=0, const std::string &text="")
Format a basic log message tracing the given the sample, using text as a prefix, then return a reference to this instance's LogMessage so more information can be streamed to it.
nidas::util::LogMessage & msg (dsm_time_t tt, dsm_sample_id_t sid, const std::string &text="")
Static Public Member Functions
static std::string format_time (dsm_time_t tt)
static std::string format_time (dsm_time_t tt, const std::string &format)
Private Attributes
nidas::util::LogContext _context
nidas::util::LogMessage _msg
nidas::core::SampleMatcher _matcher
Detailed Description
SampleTracer uses a Logger to log messages about samples as they are encountered in the code.
The samples are selected by ID using a SampleMatcher, whose criteria are specified in the 'trace_samples' log parameter.
Constructor & Destructor Documentation
SampleTracer()
SampleTracer::SampleTracer (int level, const char * file, const char * function, int line)
References _matcher, nidas::core::SampleMatcher::addCriteria(), nidas::util::Logger::getInstance(), nidas::util::LogScheme::getParameter(), and nidas::util::Logger::getScheme().
Member Function Documentation
active() [1/2]
bool nidas::core::SampleTracer::active (const Sample * samp) inline
References _context, _matcher, nidas::util::LogContext::active(), and nidas::core::SampleMatcher::match().
Referenced by nidas::core::SampleSorter::run(), and nidas::dynld::raf::SyncRecordSource::slog().
active() [2/2]
bool nidas::core::SampleTracer::active (dsm_sample_id_t id) inline
References _context, _matcher, nidas::util::LogContext::active(), and nidas::core::SampleMatcher::match().
format_time() [1/2]
static std::string nidas::core::SampleTracer::format_time (dsm_time_t tt) inline static
References nidas::util::UTime::format().
Referenced by msg(), nidas::core::SampleSorter::receive(), and nidas::core::SampleSorter::run().
format_time() [2/2]
static std::string nidas::core::SampleTracer::format_time (dsm_time_t tt, const std::string & format) inline static
References nidas::util::UTime::format().
msg() [1/2]
nidas::util::LogMessage& nidas::core::SampleTracer::msg (const Sample * samp = 0, const std::string & text = "") inline
Format a basic log message tracing the given the sample, using text as a prefix, then return a reference to this instance's LogMessage so more information can be streamed to it.
The 'endlog' manipulator must be streamed to the return value to actually log the message. For example:
static SampleTracer st;
...
if (st.active(samp))
   st.msg(samp, "received") << endlog;
With no arguments, no message is added, just the LogMessage reference is returned, allowing more information to be streamed to an existing message.
References _msg, format_time(), GET_DSM_ID, and GET_SPS_ID.
Referenced by nidas::core::SampleSorter::run(), and nidas::dynld::raf::SyncRecordSource::slog().
msg() [2/2]
nidas::util::LogMessage& nidas::core::SampleTracer::msg (dsm_time_t tt, dsm_sample_id_t sid, const std::string & text = "") inline
References _msg, format_time(), GET_DSM_ID, and GET_SPS_ID.
Member Data Documentation
_context
nidas::util::LogContext nidas::core::SampleTracer::_context private
Referenced by active().
_matcher
nidas::core::SampleMatcher nidas::core::SampleTracer::_matcher private
Referenced by active(), and SampleTracer().
_msg
nidas::util::LogMessage nidas::core::SampleTracer::_msg private
Referenced by msg().
The documentation for this class was generated from the following files:
nidas/core/SampleTracer.h
nidas/core/SampleTracer.cc