nidas: PacketDecode Class Reference
PacketDecode Class Reference
Public Member Functions
PacketDecode ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
Static Public Member Functions
static void sigAction (int sig, siginfo_t *siginfo, void *vptr)
static void setupSignals ()
static int main (int argc, char **argv) throw ()
static int usage (const char *argv0)
Private Attributes
list< string > packetFileNames
string xmlFileName
string netcdfServer
bool doAscii
Constructor & Destructor Documentation
PacketDecode()
PacketDecode::PacketDecode ()
Member Function Documentation
main()
int PacketDecode::main (int argc, char ** argv) throw () static
References parseRunstring(), and run().
Referenced by main().
parseRunstring()
int PacketDecode::parseRunstring (int argc, char ** argv) throw ()
References nidas::util::Logger::getInstance(), nidas::util::LogConfig::level, nidas::util::Logger::setScheme(), and usage().
Referenced by main().
run()
int PacketDecode::run () throw ()
References nidas::core::FileSet::addFileName(), nidas::dynld::isff::PacketInputStream::close(), nidas::core::SampleArchiver::connect(), nidas::core::SampleArchiver::disconnect(), doAscii, nidas::util::Process::expandEnvVars(), nidas::dynld::isff::PacketInputStream::getSampleTags(), nidas::dynld::isff::PacketInputStream::init(), netcdfServer, packetFileNames, nidas::core::XMLParser::parse(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::util::Exception::what(), and xmlFileName.
Referenced by main().
setupSignals()
static void PacketDecode::setupSignals () static
sigAction()
static void PacketDecode::sigAction (int sig, siginfo_t * siginfo, void * vptr) static
usage()
int PacketDecode::usage (const char * argv0) static
Member Data Documentation
doAscii
bool PacketDecode::doAscii private
Referenced by run().
netcdfServer
string PacketDecode::netcdfServer private
Referenced by run().
packetFileNames
list<string> PacketDecode::packetFileNames private
Referenced by run().
xmlFileName
string PacketDecode::xmlFileName private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/isff/pdecode.cc