nidas: nidas::dynld::psql::PSQLChannel Class Reference
nidas::dynld::psql::PSQLChannel Class Reference abstract
#include <PSQLChannel.h>
Public Member Functions
PSQLChannel ()
PSQLChannel (const PSQLChannel &)
Copy constructor.
virtual ~PSQLChannel ()
PSQLChannel * clone () const
Clone method.
void setName (const std::string &val)
const std::string & getName () const
void requestConnection (ConnectionRequester *) throw (nidas::util::IOException)
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Read method (not used).
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Write method.
void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
void close () throw (nidas::util::IOException)
int getFd () const
void setHost (const std::string &val)
const std::string & getHost () const
void setDBName (const std::string &val)
const std::string & getDBName () const
void setUser (const std::string &val)
const std::string & getUser () const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual void requestConnection (IOChannelRequester *)=0
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
virtual int getReconnectDelaySecs () const
virtual void setNonBlocking (bool val)=0
virtual bool isNonBlocking () const =0
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual size_t write (const struct iovec *iov, int iovcnt)=0
Physical write method which must be implemented in derived classes.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void connectDatabase ()
Protected Attributes
std::string name
std::string host
std::string dbname
std::string user
PGconn * _conn
Database connection pointer.
char * lastCommand
size_t lastNchars
Private Attributes
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
PSQLChannel() [1/2]
PSQLChannel::PSQLChannel ()
Referenced by clone().
PSQLChannel() [2/2]
PSQLChannel::PSQLChannel (const PSQLChannel & x)
Copy constructor.
~PSQLChannel()
PSQLChannel::~PSQLChannel () virtual
References _conn, and lastCommand.
Member Function Documentation
clone()
PSQLChannel * PSQLChannel::clone () const virtual
Clone method.
Implements nidas::core::IOChannel.
References PSQLChannel().
Referenced by connect().
close()
void PSQLChannel::close () throw (nidas::util::IOException) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _conn, and flush().
Referenced by nidas::dynld::psql::PSQLSampleOutput::close().
connect()
IOChannel * PSQLChannel::connect () throw (nidas::util::IOException) virtual
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Exceptions
nidas::util::IOException
nidas::util::UnknownHostException
Implements nidas::core::IOChannel.
References clone(), connectDatabase(), and DLOG.
Referenced by nidas::dynld::psql::PSQLSampleOutput::connect().
connectDatabase()
void PSQLChannel::connectDatabase () protected
References _conn, getDBName(), getHost(), getName(), and getUser().
Referenced by connect().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
void PSQLChannel::flush () throw (nidas::util::IOException) virtual
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::IOChannel.
References _conn, getName(), and lastCommand.
Referenced by close(), and nidas::dynld::psql::PSQLSampleOutput::flush().
fromDOMElement()
void PSQLChannel::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), nidas::util::Logger::log(), and LOG_INFO.
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDBName()
const std::string& nidas::dynld::psql::PSQLChannel::getDBName () const inline
Referenced by connectDatabase().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::dynld::psql::PSQLChannel::getFd () const inline virtual
Implements nidas::core::IOChannel.
getHost()
const std::string& nidas::dynld::psql::PSQLChannel::getHost () const inline
Referenced by connectDatabase().
getName()
const std::string& nidas::dynld::psql::PSQLChannel::getName () const inline virtual
Implements nidas::core::IOChannel.
Referenced by connectDatabase(), and flush().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getUser()
const std::string& nidas::dynld::psql::PSQLChannel::getUser () const inline
Referenced by connectDatabase().
isNewInput()
virtual bool nidas::core::IOChannel::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented in nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::core::IOStream::read(), and nidas::core::IOStream::readUntil().
isNonBlocking()
virtual bool nidas::core::IOChannel::isNonBlocking () const pure virtual inherited
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::isff::GOESXmtr, nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::isNonBlocking().
read()
size_t nidas::dynld::psql::PSQLChannel::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual
Read method (not used).
Implements nidas::core::IOChannel.
requestConnection() [1/2]
void PSQLChannel::requestConnection (ConnectionRequester * requester) throw (nidas::util::IOException)
References DLOG.
requestConnection() [2/2]
virtual void nidas::core::IOChannel::requestConnection (IOChannelRequester *) pure virtual inherited
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
It is like opening a device, but in the case of server sockets, it just starts a thread to wait on connections. Only when the IOChannelRequester::connected() method is called back is the channel actually open and ready for IO. The IOChannel* returned by IOChannelRequester::connected may be another instance of an IOChannel.
Exceptions
nidas::util::IOException
Implemented in nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::DatagramSocket, nidas::dynld::isff::GOESXmtr, nidas::core::UnixIOChannel, and nidas::core::FileSet.
Referenced by nidas::dynld::SampleInputStream::requestConnection(), nidas::core::SampleOutputBase::requestConnection(), and nidas::dynld::XMLConfigService::schedule().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDBName()
void PSQLChannel::setDBName (const std::string & val)
References dbname, host, setName(), and user.
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setHost()
void PSQLChannel::setHost (const std::string & val)
References dbname, host, setName(), and user.
setName()
void nidas::dynld::psql::PSQLChannel::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
Referenced by setDBName(), setHost(), and setUser().
setNonBlocking()
virtual void nidas::core::IOChannel::setNonBlocking (bool val) pure virtual inherited
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setNonBlocking().
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setUser()
void PSQLChannel::setUser (const std::string & val)
References dbname, host, setName(), and user.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
virtual size_t nidas::core::IOChannel::write (const struct iovec * iov, int iovcnt) pure virtual inherited
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::isff::SE_GOESXmtr, nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::MultipleUDPSockets, nidas::core::FileSet, nidas::core::DatagramSocket, nidas::dynld::isff::SimGOESXmtr, nidas::core::ServerSocket, nidas::core::McSocketUDP, and nidas::core::McSocket.
write() [2/2]
size_t PSQLChannel::write (const void * buf, size_t len) throw (nidas::util::IOException) virtual
Write method.
Sends SQL command to DB.
Implements nidas::core::IOChannel.
References len.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_conn
PGconn* nidas::dynld::psql::PSQLChannel::_conn protected
Database connection pointer.
Referenced by close(), connectDatabase(), flush(), and ~PSQLChannel().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
dbname
std::string nidas::dynld::psql::PSQLChannel::dbname protected
Referenced by setDBName(), setHost(), and setUser().
host
std::string nidas::dynld::psql::PSQLChannel::host protected
Referenced by setDBName(), setHost(), and setUser().
lastCommand
char* nidas::dynld::psql::PSQLChannel::lastCommand protected
Referenced by flush(), and ~PSQLChannel().
lastNchars
size_t nidas::dynld::psql::PSQLChannel::lastNchars protected
name
std::string nidas::dynld::psql::PSQLChannel::name protected
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
user
std::string nidas::dynld::psql::PSQLChannel::user protected
Referenced by setDBName(), setHost(), and setUser().
The documentation for this class was generated from the following files:
nidas/dynld/psql/PSQLChannel.h
nidas/dynld/psql/PSQLChannel.cc