nidas: SensorSimulator Class Reference
SensorSimulator Class Reference abstract
Base class for sensor simulators.
Public Member Functions
SensorSimulator (n_u::SerialPort *p, bool prompted, string prompt, float rate, int nmessages)
virtual void sendMessage ()=0
Implement this to send a message from the simulated sensor.
virtual void writeMessage (const std::string &msg)
Subclasses generate the message to send, then call writeMessage() to send it out.
virtual void writeMessage (const char *buf, std::streamsize l)
overloaded function useful for writing binary data
virtual void run ()
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
void interrupt ()
Stop the simulation.
bool isInterrupted () const
n_u::SerialPort * port ()
Protected Member Functions
Looper * getLooper ()
void looperNotify () override
Method called by Looper.
void readPrompts ()
SensorSimulator (const SensorSimulator &)
SensorSimulator & operator= (const SensorSimulator &)
Protected Attributes
n_u::SerialPort * _port
bool _prompted
string _prompt
float _rate
int _nmessages
bool _interrupted
Static Protected Attributes
static Looper * _looper = 0
Detailed Description
Base class for sensor simulators.
Constructor & Destructor Documentation
SensorSimulator() [1/2]
SensorSimulator::SensorSimulator (n_u::SerialPort * p, bool prompted, string prompt, float rate, int nmessages) inline
SensorSimulator() [2/2]
SensorSimulator::SensorSimulator (const SensorSimulator &) protected
Member Function Documentation
getLooper()
Looper * SensorSimulator::getLooper () protected
interrupt()
void SensorSimulator::interrupt () inline
Stop the simulation.
Referenced by FileSim::sendASCIIMessage(), and FileSim::sendBinaryMessage().
isInterrupted()
bool SensorSimulator::isInterrupted () const inline
looperNotify()
void SensorSimulator::looperNotify () override protected virtual
Method called by Looper.
This method should not be a heavy user of resources, since the notification of other clients is delayed until this method finishes. If much work is to be done, this method should post a semaphore for another worker thread to proceed.
Implements nidas::core::LooperClient.
References nidas::util::Exception::what().
operator=()
SensorSimulator& SensorSimulator::operator= (const SensorSimulator &) protected
port()
n_u::SerialPort* SensorSimulator::port () inline
readPrompts()
void SensorSimulator::readPrompts () protected
run()
void SensorSimulator::run () virtual
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
run() will return when isInterrupted() is true.
Reimplemented in Csat3Sim.
References MSECS_PER_SEC.
sendMessage()
virtual void SensorSimulator::sendMessage () pure virtual
Implement this to send a message from the simulated sensor.
Exceptions
nidas::util::IOException
Implemented in Csat3Sim, FileSim, and FixedSim.
writeMessage() [1/2]
virtual void SensorSimulator::writeMessage (const char * buf, std::streamsize l) inline virtual
overloaded function useful for writing binary data
writeMessage() [2/2]
virtual void SensorSimulator::writeMessage (const std::string & msg) inline virtual
Subclasses generate the message to send, then call writeMessage() to send it out.
Referenced by FileSim::sendASCIIMessage(), FileSim::sendBinaryMessage(), and FixedSim::sendMessage().
Member Data Documentation
_interrupted
bool SensorSimulator::_interrupted protected
_looper
Looper * SensorSimulator::_looper = 0 static protected
_nmessages
int SensorSimulator::_nmessages protected
Referenced by Csat3Sim::run().
_port
n_u::SerialPort* SensorSimulator::_port protected
Referenced by Csat3Sim::run(), and Csat3Sim::sendMessage().
_prompt
string SensorSimulator::_prompt protected
_prompted
bool SensorSimulator::_prompted protected
_rate
float SensorSimulator::_rate protected
Referenced by Csat3Sim::run().
The documentation for this class was generated from the following file:
nidas/apps/sensor_sim.cc