nidas: nidas::core::DSMConfig::MyDictionary Class Reference
nidas::core::DSMConfig::MyDictionary Class Reference
Public Member Functions
MyDictionary (DSMConfig *dsm)
MyDictionary (const MyDictionary &x)
MyDictionary & operator= (const MyDictionary &rhs)
bool getTokenValue (const std::string &token, std::string &value) const
std::string expandString (const std::string &input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Private Attributes
DSMConfig * _dsm
Constructor & Destructor Documentation
MyDictionary() [1/2]
nidas::core::DSMConfig::MyDictionary::MyDictionary (DSMConfig * dsm) inline
MyDictionary() [2/2]
nidas::core::DSMConfig::MyDictionary::MyDictionary (const MyDictionary & x) inline
Member Function Documentation
expandString()
string Dictionary::expandString (const std::string & input) const inherited
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Referenced by nidas::core::DSMConfig::expandString(), nidas::core::DSMSensor::expandString(), nidas::core::Project::expandString(), nidas::core::Site::expandString(), and nidas::core::ParameterT< T >::fromDOMElement().
getTokenValue()
bool DSMConfig::MyDictionary::getTokenValue (const std::string & token, std::string & value) const virtual
Implements nidas::core::Dictionary.
References _dsm, nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getLocation(), nidas::core::DSMConfig::getName(), nidas::core::DSMConfig::getSite(), and nidas::core::Site::getTokenValue().
Referenced by nidas::core::DSMConfig::getTokenValue().
operator=()
MyDictionary& nidas::core::DSMConfig::MyDictionary::operator= (const MyDictionary & rhs) inline
References _dsm.
Member Data Documentation
_dsm
DSMConfig* nidas::core::DSMConfig::MyDictionary::_dsm private
Referenced by getTokenValue(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/DSMConfig.h
nidas/core/DSMConfig.cc