nidas: nidas::core::XDOMElement Class Reference
nidas::core::XDOMElement Class Reference
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
#include <XDOM.h>
Public Member Functions
XDOMElement (const xercesc::DOMElement *e)
XDOMElement (xercesc::DOMElement *e)
const std::string & getAttributeValue (const std::string &aname)
void setAttributeValue (const std::string &name, const std::string &val)
const std::string & getNodeName () const
const std::string & getNodeType () const
const xercesc::DOMElement * getElement () const
Private Member Functions
XDOMElement (const XDOMElement &)
No copying.
XDOMElement & operator= (const XDOMElement &)
No assignment.
Private Attributes
const xercesc::DOMElement * _elemConst
xercesc::DOMElement * _elemNonConst
std::map< std::string, std::string > _attrs
std::string _nodename
std::string _nodetype
Detailed Description
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
Constructor & Destructor Documentation
XDOMElement() [1/3]
nidas::core::XDOMElement::XDOMElement (const xercesc::DOMElement * e) inline
XDOMElement() [2/3]
nidas::core::XDOMElement::XDOMElement (xercesc::DOMElement * e) inline
XDOMElement() [3/3]
nidas::core::XDOMElement::XDOMElement (const XDOMElement &) private
No copying.
Member Function Documentation
getAttributeValue()
const std::string& nidas::core::XDOMElement::getAttributeValue (const std::string & aname) inline
Returns
an empty string if attribute does not have a specified or default value.
References _attrs, and _elemConst.
Referenced by nidas::core::XMLConfigWriterFilter::acceptDSMNode(), nidas::core::IOChannel::createIOChannel(), nidas::core::Socket::createSocket(), nidas::core::VariableConverter::createVariableConverter(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DSMCatalog::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::SensorCatalog::fromDOMElement(), nidas::core::ServiceCatalog::fromDOMElement(), nidas::core::ParameterT< T >::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::DSMService::getClassName(), nidas::core::DSMSensor::getClassName(), LogSchemeFromDOMElement(), nidas::core::Project::removeAutoConfig(), and nidas::core::DSMConfig::sensorFromDOMElement().
getElement()
const xercesc::DOMElement* nidas::core::XDOMElement::getElement () const inline
References _elemConst.
Referenced by nidas::core::Project::removeAutoConfig().
getNodeName()
const std::string& nidas::core::XDOMElement::getNodeName () const inline
References _nodename.
Referenced by nidas::core::XMLConfigWriterFilter::acceptDSMNode(), nidas::core::XMLConfigWriterFilter::acceptNode(), nidas::core::IOChannel::createIOChannel(), nidas::core::VariableConverter::createVariableConverter(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::Dataset::fromDOMElement(), nidas::core::Datasets::fromDOMElement(), nidas::core::DSMCatalog::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::ProjectConfigs::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::SensorCatalog::fromDOMElement(), nidas::core::ServiceCatalog::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::FileSet::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), LogSchemeFromDOMElement(), nidas::core::Project::removeAutoConfig(), and nidas::core::DSMConfig::sensorFromDOMElement().
getNodeType()
const std::string& nidas::core::XDOMElement::getNodeType () const inline
References _nodetype.
operator=()
XDOMElement& nidas::core::XDOMElement::operator= (const XDOMElement &) private
No assignment.
setAttributeValue()
void nidas::core::XDOMElement::setAttributeValue (const std::string & name, const std::string & val) inline
References _attrs, and _elemNonConst.
Referenced by nidas::core::Project::removeAutoConfig(), nidas::dynld::XMLConfigService::Worker::run(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::DSMConfig::toDOMElement(), nidas::core::Project::toDOMElement(), nidas::core::SampleTag::toDOMElement(), nidas::core::Site::toDOMElement(), and nidas::core::Variable::toDOMElement().
Member Data Documentation
_attrs
std::map<std::string,std::string> nidas::core::XDOMElement::_attrs private
Referenced by getAttributeValue(), and setAttributeValue().
_elemConst
const xercesc::DOMElement* nidas::core::XDOMElement::_elemConst private
Referenced by getAttributeValue(), and getElement().
_elemNonConst
xercesc::DOMElement* nidas::core::XDOMElement::_elemNonConst private
Referenced by setAttributeValue().
_nodename
std::string nidas::core::XDOMElement::_nodename private
Referenced by getNodeName().
_nodetype
std::string nidas::core::XDOMElement::_nodetype private
Referenced by getNodeType().
The documentation for this class was generated from the following file:
nidas/core/XDOM.h