nidas: nidas/apps/raf/ck_arinc.cc File Reference
ck_arinc.cc File Reference
#include <iostream>
#include <iomanip>
#include <sys/select.h>
#include <nidas/dynld/raf/IRS_HW_HG2001GD.h>
Classes
struct dbl_arcfg_t
Functions
int main ()
Variables
static dbl_arcfg_t IRS_labels []
static int nIRS_labels = sizeof(IRS_labels) / sizeof(dbl_arcfg_t)
Function Documentation
main()
int main ()
References nidas::dynld::raf::DSMArincSensor::close(), nidas::dynld::raf::DSMArincSensor::open(), nidas::core::DSMSensor::setDeviceName(), and nidas::util::Exception::what().
Variable Documentation
IRS_labels
dbl_arcfg_t IRS_labels[] static
nIRS_labels
int nIRS_labels = sizeof(IRS_labels) / sizeof(dbl_arcfg_t) static