nidas: nidas::core::SensorHandler Class Reference
nidas::core::SensorHandler Class Reference
SensorHandler implements a DSMSensor event loop.
#include <SensorHandler.h>
Classes
class NotifyPipe
class PolledDSMSensor
Public Types
enum runStatus { RUN_CANCELED = -1 , RUN_OK = 0 , NOT_RUNNING = 1 , RUN_EXCEPTION = 2 }
Values that can be returned by run method.
enum SchedPolicy { NU_THREAD_OTHER =SCHED_OTHER , NU_THREAD_FIFO =SCHED_FIFO , NU_THREAD_RR =SCHED_RR }
Public Member Functions
SensorHandler (unsigned short rserialPort=0)
Constructor.
~SensorHandler ()
Close any remaining sensors.
void signalHandler (int sig, siginfo_t *)
Override default implementation of Thread::signalHandler().
void addSensor (DSMSensor *sensor)
Add an unopened sensor to the SensorHandler.
void closeSensor (DSMSensor *sensor)
Request that SensorHandler close the sensor.
void sensorIsOpen (DSMSensor *sensor) throw ()
After SensorOpener has opened the sensor, it will notify SensorHandler via this method that the sensor is open.
void checkSensors (dsm_time_t)
Check on each sensor.
void setSensorStatsInterval (int val)
Set the sensor statistics calculation period.
int getSensorStatsInterval () const
Get the sensor check period.
void handleRemoteSerial (int fd, DSMSensor *sensor)
int run ()
Thread function.
std::list< DSMSensor * > getAllSensors () const
std::list< DSMSensor * > getOpenedSensors () const
void interrupt ()
Interrupt polling.
int join ()
Join this thread and join the SensorOpener.
int getEpollFd () const
void incrementFullBufferReads (const DSMSensor *sensor)
Called by a DSMSensor to indicate that a read did not consume all available data.
void updateTimeouts ()
Tell the SensorHandler that one or more sensor timeouts have changed.
virtual void start ()
Start the thread running, meaning execute the run method in a separate thread.
virtual void kill (int sig)
Send a signal to this thread.
virtual void cancel ()
Cancel this thread.
virtual bool isInterrupted () const
Return true when this thread has been interrupted.
virtual bool isRunning () const
Is this thread running?
virtual bool isJoined () const
Has this thread been joined?
virtual bool isDetached () const
Is this a detached thread.
bool isCancelEnabled () const
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
bool isCancelDeferred () const
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
const std::string & getName () const throw ()
Return the name of this thread.
const std::string & getFullName () throw ()
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
bool setRealTimeRoundRobinPriority (int val)
bool setRealTimeFIFOPriority (int val)
bool setNonRealTimePriority ()
void setThreadScheduler (enum SchedPolicy policy, int priority)
void blockSignal (int)
Block a signal in this thread.
void unblockSignal (int)
Install a signal handler and unblock the signal.
Static Public Member Functions
static Thread * currentThread ()
Return the thread object for the current thread.
static pthread_t currentThreadId ()
static Thread * lookupThread (pthread_t id)
static const std::string & currentName ()
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
static std::string getPolicyString (int policy)
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
static int test (int argc, char **argv)
a test method.
Protected Member Functions
void setCancelEnabled (bool val)
Set the cancel state for this thread - false means cancel requests are ignored.
void setCancelDeferred (bool val)
Set the cancel type for this thread.
pthread_t getId () const
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Private Member Functions
void add (DSMSensor *sensor) throw ()
Internal private method to create a PolledDSMSensor from a DSMSensor and add it to the list of currently active sensors.
void remove (PolledDSMSensor *sensor) throw ()
Internal private method to close the PolledDSMSensor.
void scheduleClose (PolledDSMSensor *) throw ()
Schedule this PolledDSMSensor to be closed when convenient.
void scheduleReopen (PolledDSMSensor *) throw ()
Schedule this PolledDSMSensor to be closed and reopened.
void add (RemoteSerialConnection *) throw ()
Internal private method to add a remote serial connection to a sensor.
void remove (RemoteSerialConnection *) throw ()
void scheduleAdd (RemoteSerialConnection *) throw ()
Schedule this remote serial connection to be closed when convenient.
void scheduleClose (RemoteSerialConnection *) throw ()
void handlePollingChange ()
Called when something has changed in our collection of sensors.
void calcStatistics (dsm_time_t)
void setupTimeouts (int sensorCheckIntervalMsecs)
void checkTimeouts (dsm_time_t)
SensorHandler (const SensorHandler &)
No copy.
SensorHandler & operator= (const SensorHandler &)
No assignment.
virtual int pRun ()
void setThreadSchedulerNolock (enum SchedPolicy policy, int priority)
void makeFullName ()
void registerThread ()
Register this current thread with a static registry of threads by id.
void unregisterThread ()
void unsetId ()
Static Private Member Functions
static void * thr_run (void *me)
static void * thr_run_detached (void *me)
static void thr_cleanup (void *me)
static void thr_cleanup_delete (void *me)
static void thr_add_sig (int sig)
static void sigAction (int sig, siginfo_t *si, void *vptr)
Private Attributes
std::list< DSMSensor * > _allSensors
The collection of DSMSensors to be handled.
nidas::util::Mutex _pollingMutex
bool _pollingChanged
A change in the polling file descriptors needs to be handled.
std::list< DSMSensor * > _openedSensors
Collection of DSMSensors which have been opened.
std::list< PolledDSMSensor * > _polledSensors
Those DSMSensors currently being polled.
std::list< DSMSensor * > _newOpenedSensors
Newly opened DSMSensors, which are to be added to the list of file descriptors to be polled.
std::set< PolledDSMSensor * > _pendingSensorClosures
Sensors to be closed, probably due to a read error or a timeout.
std::set< PolledDSMSensor * > _pendingSensorReopens
Sensors to be closed and then reopened.
unsigned short _remoteSerialSocketPort
RemoteSerialListener * _rserial
std::list< RemoteSerialConnection * > _newRserials
Newly opened RemoteSerialConnections, which are to be added to the list of file descriptors to be polled.
std::set< RemoteSerialConnection * > _pendingRserialClosures
RemoteSerialConnections to be closed, probably because the socket connection closed.
std::list< RemoteSerialConnection * > _activeRserialConns
int _epollfd
epoll file descriptor.
struct epoll_event * _events
int _nevents
NotifyPipe * _notifyPipe
dsm_time_t _sensorCheckTime
dsm_time_t _sensorStatsTime
int _sensorCheckIntervalMsecs
Interval for checking for timeouts on each sensor, in milliseconds.
unsigned int _sensorCheckIntervalUsecs
Same as _sensorCheckIntervalMsecs, but in microseconds.
unsigned int _sensorStatsInterval
Interval for calculcating through-put statistics on each sensor, in microseconds.
SensorOpener _opener
std::map< const DSMSensor *, unsigned int > _fullBufferReads
For each sensor, number of times that the input buffer was filled in a read, i.e.
bool _acceptingOpens
Mutex _mutex
Mutex for accessing _id.
std::string _name
std::string _fullname
pthread_t _id
bool _running
bool _interrupted
bool _cancel_enabled
bool _cancel_deferred
pthread_attr_t _thread_attr
Exception * _exception
Exception thrown by run method.
bool _detached
sigset_t _blockedSignals
sigset_t _unblockedSignals
Static Private Attributes
static std::string unknownName = std::string("unknown")
Friends
class RemoteSerialConnection
class RemoteSerialListener
Detailed Description
SensorHandler implements a DSMSensor event loop.
It uses one of the available system calls, depending on the value of POLLING_METHOD, to check for events on the file descriptors of one or more PolledDSMSensors and RemoteSerial sockets.
The handlePollEvents() method is called on each active file descriptor. The polling loop is implemented in the Thread::run method of the SensorHandler.
This code has supported legacy systems which did not have the epoll() API, and used select/pselect or poll/ppoll instead. So, this code supports all the polling APIs, and one is selected using POLLING_METHOD. As of 2017 all known systems support epoll(), so the old select/poll code could be removed.
When an incoming socket connection is accepted on RemoteSerialListener, a RemoteSerialConnection is established, which first requests the name of a DSMSensor on the connected socket. If that sensor is found then data are then passed back and forth between the socket and the DSMSensor. This data path is separate from the normal Sample data path. It allows remote, direct control of serial sensors.
Member Enumeration Documentation
runStatus
enum nidas::util::Thread::runStatus inherited
Values that can be returned by run method.
User can define other values greater than RUN_EXCEPTION. These values are then returned by int join(). Note that PTHREAD_CANCELLED is -1
Enumerator
RUN_CANCELED
RUN_OK
NOT_RUNNING
RUN_EXCEPTION
SchedPolicy
enum nidas::util::Thread::SchedPolicy inherited
Enumerator
NU_THREAD_OTHER
NU_THREAD_FIFO
NU_THREAD_RR
Constructor & Destructor Documentation
SensorHandler() [1/2]
SensorHandler::SensorHandler (unsigned short rserialPort = 0)
Constructor.
Parameters
rserialPort TCP socket port to listen for incoming requests to the rserial service. 0=don't listen.
References _sensorStatsInterval, _sensorStatsTime, nidas::util::Thread::blockSignal(), nidas::util::getSystemTime(), MSECS_PER_SEC, N_POLLERR, N_POLLHUP, N_POLLIN, N_POLLRDHUP, setSensorStatsInterval(), and nidas::util::timeCeiling().
~SensorHandler()
SensorHandler::~SensorHandler ()
Close any remaining sensors.
Before this is called the run method should be finished.
References _allSensors, _epollfd, _events, _notifyPipe, _polledSensors, _rserial, nidas::core::SensorHandler::PolledDSMSensor::close(), and nidas::core::DSMSensor::setDSMConfig().
SensorHandler() [2/2]
nidas::core::SensorHandler::SensorHandler (const SensorHandler &) private
No copy.
Member Function Documentation
add() [1/2]
void SensorHandler::add (DSMSensor * sensor) throw () private
Internal private method to create a PolledDSMSensor from a DSMSensor and add it to the list of currently active sensors.
References _openedSensors, _polledSensors, _pollingMutex, nidas::util::Mutex::lock(), PLOG, nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
Referenced by handlePollingChange().
add() [2/2]
void SensorHandler::add (RemoteSerialConnection * conn) throw () private
Internal private method to add a remote serial connection to a sensor.
References _activeRserialConns, _allSensors, _pollingMutex, nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getName(), ILOG, nidas::util::Mutex::lock(), NLOG, PLOG, nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
addSensor()
void SensorHandler::addSensor (DSMSensor * sensor)
Add an unopened sensor to the SensorHandler.
SensorHandler will then own the DSMSensor.
References _allSensors, _opener, _pollingMutex, nidas::util::Mutex::lock(), nidas::core::SensorOpener::openSensor(), and nidas::util::Mutex::unlock().
Referenced by nidas::core::DSMConfig::openSensors().
amInterrupted()
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::Looper::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
blockSignal()
void Thread::blockSignal (int sig) inherited
Block a signal in this thread.
This method is usually called before this Thread has started. If this Thread is currently running, then this method is only effective if called from this Thread, i.e. from its own run() method.
Because SIGINT, SIGTERM and SIGHUP are typically caught in the main thread, they are blocked by default in a Thread. Call unblockSignal(sig) if you want to catch them in a Thread.
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::ConnectionMonitor(), nidas::core::ServerSocket::ConnectionThread::ConnectionThread(), nidas::core::DerivedDataReader::DerivedDataReader(), nidas::util::McSocketListener::McSocketListener(), nidas::util::McSocketMulticaster< SocketTT >::McSocketMulticaster(), SensorHandler(), nidas::core::SensorOpener::SensorOpener(), nidas::util::Thread::test(), nidas::dynld::RawSampleService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
calcStatistics()
void SensorHandler::calcStatistics (dsm_time_t tnow) private
References _sensorStatsInterval, _sensorStatsTime, nidas::core::DSMSensor::calcStatistics(), getAllSensors(), and nidas::util::timeCeiling().
Referenced by run().
cancel()
void Thread::cancel () virtual inherited
Cancel this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::DSMService::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DerivedDataReader::deleteInstance(), and nidas::core::DSMEngine::joinDataThreads().
checkSensors()
void nidas::core::SensorHandler::checkSensors (dsm_time_t)
Check on each sensor.
Currently this means checking whether a timeout has occured and calculating statistics on the data received from the sensor.
checkTimeouts()
void SensorHandler::checkTimeouts (dsm_time_t tnow) private
References _polledSensors, _sensorCheckIntervalUsecs, _sensorCheckTime, nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), scheduleReopen(), and nidas::util::timeCeiling().
Referenced by run().
closeSensor()
void nidas::core::SensorHandler::closeSensor (DSMSensor * sensor)
Request that SensorHandler close the sensor.
currentName()
static const std::string& nidas::util::Thread::currentName () inline static inherited
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
References nidas::util::Thread::currentThread(), nidas::util::Thread::getName(), and nidas::util::Thread::unknownName.
Referenced by nidas::util::Logger::msg_locked().
currentThread()
Thread * Thread::currentThread () static inherited
Return the thread object for the current thread.
Returns null if not found.
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::currentName(), and nidas::util::Thread::unblockSignal().
currentThreadId()
pthread_t Thread::currentThreadId () static inherited
Referenced by nidas::core::Looper::removeClient().
getAllSensors()
list< DSMSensor * > SensorHandler::getAllSensors () const
References _allSensors, and _pollingMutex.
Referenced by calcStatistics(), and nidas::core::DSMEngineStat::run().
getEpollFd()
int nidas::core::SensorHandler::getEpollFd () const inline
References _epollfd.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::RemoteSerialListener::close(), nidas::core::SensorHandler::NotifyPipe::NotifyPipe(), nidas::core::SensorHandler::PolledDSMSensor::PolledDSMSensor(), nidas::core::RemoteSerialListener::RemoteSerialListener(), and nidas::core::RemoteSerialConnection::setSensor().
getFullName()
const std::string & Thread::getFullName () throw () inherited
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
References nidas::util::Thread::_fullname.
Referenced by nidas::util::Thread::pRun(), nidas::util::Thread::test(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
getId()
pthread_t nidas::util::Thread::getId () const inline protected inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Referenced by nidas::util::Thread::isJoined(), nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::core::Looper::removeClient().
getName()
const std::string & Thread::getName () const throw () inherited
Return the name of this thread.
References nidas::util::Thread::_name.
Referenced by nidas::core::DSMService::cancel(), nidas::util::Thread::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), nidas::core::SensorHandler::PolledDSMSensor::close(), nidas::util::Thread::currentName(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SampleSorter::heapDecrement(), nidas::core::DSMService::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleSorter::run(), nidas::util::ThreadJoiner::run(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::sigAction(), nidas::util::Thread::start(), nidas::util::Thread::test(), nidas::util::LogContext::threadName(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
getOpenedSensors()
list< DSMSensor * > SensorHandler::getOpenedSensors () const
References _openedSensors, and _pollingMutex.
getPolicyString()
string Thread::getPolicyString (int policy) static inherited
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
References nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::NU_THREAD_RR.
Referenced by nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::makeFullName().
getSensorStatsInterval()
int nidas::core::SensorHandler::getSensorStatsInterval () const inline
Get the sensor check period.
Returns
Period, in milliseconds.
References _sensorStatsInterval, and USECS_PER_MSEC.
handlePollingChange()
void SensorHandler::handlePollingChange () private
Called when something has changed in our collection of sensors.
Mainly this maintains the set of file descriptors used by the epoll() system functions.
References _acceptingOpens, _activeRserialConns, _events, _nevents, _newOpenedSensors, _newRserials, _notifyPipe, _opener, _pendingRserialClosures, _pendingSensorClosures, _pendingSensorReopens, _polledSensors, _pollingChanged, _pollingMutex, _rserial, _sensorCheckIntervalMsecs, _sensorCheckIntervalUsecs, _sensorCheckTime, add(), fd, nidas::core::SensorHandler::PolledDSMSensor::getDSMSensor(), nidas::core::RemoteSerialConnection::getFd(), nidas::core::RemoteSerialListener::getFd(), nidas::core::SensorHandler::PolledDSMSensor::getFd(), nidas::core::SensorHandler::NotifyPipe::getFd(), nidas::util::getSystemTime(), nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs(), ILOG, nidas::util::Mutex::lock(), MSECS_PER_SEC, remove(), nidas::core::SensorOpener::reopenSensor(), setupTimeouts(), nidas::util::timeCeiling(), nidas::util::Mutex::unlock(), and USECS_PER_MSEC.
Referenced by run().
handleRemoteSerial()
void nidas::core::SensorHandler::handleRemoteSerial (int fd, DSMSensor * sensor)
Exceptions
nidas::util::IOException
incrementFullBufferReads()
void SensorHandler::incrementFullBufferReads (const DSMSensor * sensor)
Called by a DSMSensor to indicate that a read did not consume all available data.
References _fullBufferReads, nidas::core::DSMSensor::getName(), and ILOG.
interrupt()
void SensorHandler::interrupt () virtual
Interrupt polling.
Reimplemented from nidas::util::Thread.
References _notifyPipe, nidas::util::Thread::kill(), and nidas::core::SensorHandler::NotifyPipe::notify().
Referenced by nidas::core::DSMEngine::interrupt().
isCancelDeferred()
bool Thread::isCancelDeferred () const inherited
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
References nidas::util::Thread::_cancel_deferred.
isCancelEnabled()
bool Thread::isCancelEnabled () const inherited
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
References nidas::util::Thread::_cancel_enabled.
isDetached()
virtual bool nidas::util::Thread::isDetached () const inline virtual inherited
Is this a detached thread.
References nidas::util::Thread::_detached.
isInterrupted()
virtual bool nidas::util::Thread::isInterrupted () const inline virtual inherited
Return true when this thread has been interrupted.
Implements nidas::util::Runnable.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::core::SampleSorter::flush(), nidas::dynld::raf::SyncServer::read(), ServerThread::run(), Sender::run(), ModemLineSetter::run(), ModemLineMonitor::run(), nidas::core::DerivedDataReader::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleBuffer::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::SampleSorter::run(), run(), nidas::core::SensorOpener::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::util::McSocketListener::run(), and nidas::dynld::raf::SyncServer::stop().
isJoined()
virtual bool nidas::util::Thread::isJoined () const inline virtual inherited
Has this thread been joined?
References nidas::util::Thread::getId().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::deleteInstance(), join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::util::Thread::test(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
isRunning()
virtual bool nidas::util::Thread::isRunning () const inline virtual inherited
Is this thread running?
References nidas::util::Thread::_mutex, and nidas::util::Thread::_running.
Referenced by nidas::util::Thread::blockSignal(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::DSMService::interrupt(), nidas::core::SamplePipeline::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::Looper::removeClient(), nidas::core::ServerSocket::requestConnection(), run(), nidas::core::Looper::setupClientMaps(), nidas::util::Thread::test(), nidas::util::Thread::unblockSignal(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::util::Thread::~Thread(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
join()
int SensorHandler::join () virtual
Join this thread and join the SensorOpener.
Exceptions
nidas::util::Exception
Reimplemented from nidas::util::Thread.
References _opener, nidas::util::Thread::isJoined(), and nidas::util::Thread::join().
Referenced by nidas::core::DSMEngine::joinDataThreads().
kill()
void Thread::kill (int sig) virtual inherited
Send a signal to this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::interrupt(), interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::XmlRpcThread::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), main(), scheduleAdd(), scheduleClose(), scheduleReopen(), and sensorIsOpen().
lookupThread()
Thread * Thread::lookupThread (pthread_t id) static inherited
Referenced by nidas::util::LogContext::threadName().
makeFullName()
void Thread::makeFullName () private inherited
References nidas::util::Thread::_cancel_deferred, nidas::util::Thread::_cancel_enabled, nidas::util::Thread::_detached, nidas::util::Thread::_fullname, nidas::util::Thread::_id, nidas::util::Thread::_name, and nidas::util::Thread::getPolicyString().
Referenced by nidas::util::Thread::start().
operator=()
SensorHandler& nidas::core::SensorHandler::operator= (const SensorHandler &) private
No assignment.
pRun()
int Thread::pRun () private virtual inherited
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_exception, nidas::util::Thread::_mutex, nidas::util::Thread::_unblockedSignals, nidas::util::Exception::clone(), nidas::util::Thread::getFullName(), nidas::util::Thread::getId(), ILOG, nidas::util::Mutex::lock(), nidas::util::Mutex::ptr(), nidas::util::Runnable::run(), and nidas::util::Thread::RUN_EXCEPTION.
Referenced by nidas::util::Thread::thr_run(), and nidas::util::Thread::thr_run_detached().
registerThread()
void Thread::registerThread () private inherited
Register this current thread with a static registry of threads by id.
Thread::registerThread (new Thread ("Main"));
Referenced by nidas::util::Thread::start().
remove() [1/2]
void SensorHandler::remove (PolledDSMSensor * sensor) throw () private
Internal private method to close the PolledDSMSensor.
Remove it from the polling list, then delete it. The associated DSMSensor will be removed from _openedSensors.
References _openedSensors, _polledSensors, _pollingMutex, nidas::util::Mutex::lock(), PLOG, nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
Referenced by handlePollingChange().
remove() [2/2]
void SensorHandler::remove (RemoteSerialConnection * conn) throw () private
References _activeRserialConns, _pollingMutex, nidas::util::Mutex::lock(), PLOG, nidas::util::Mutex::unlock(), nidas::util::Exception::what(), and WLOG.
run()
int SensorHandler::run () virtual
Thread function.
Thread function, epoll loop.
Exceptions
nidas::util::Exception
Implements nidas::util::Runnable.
References _acceptingOpens, _activeRserialConns, _epollfd, _events, _nevents, _newOpenedSensors, _notifyPipe, _opener, _pendingRserialClosures, _pendingSensorClosures, _polledSensors, _pollingChanged, _pollingMutex, _remoteSerialSocketPort, _rserial, _sensorCheckIntervalMsecs, _sensorCheckTime, _sensorStatsTime, calcStatistics(), checkTimeouts(), nidas::core::DSMSensor::close(), nidas::core::RemoteSerialListener::close(), nidas::core::SensorHandler::NotifyPipe::close(), fd, nidas::core::SamplePools::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SamplePoolInterface::getNSamplesAlloc(), nidas::core::SamplePoolInterface::getNSamplesOut(), nidas::core::SamplePools::getPools(), nidas::util::getSystemTime(), nidas::core::Polled::handlePollEvents(), handlePollingChange(), if(), nidas::core::SensorOpener::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::isRunning(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_INFO, LOG_WARNING, N_POLLERR, N_POLLIN, PLOG, POLL_EPOLL_ET, POLLING_METHOD, RemoteSerialListener, nidas::util::Thread::RUN_OK, nidas::util::Thread::start(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
scheduleAdd()
void SensorHandler::scheduleAdd (RemoteSerialConnection * conn) throw () private
Schedule this remote serial connection to be closed when convenient.
References _newRserials, _notifyPipe, _pollingChanged, _pollingMutex, nidas::util::Thread::kill(), nidas::util::Mutex::lock(), nidas::core::SensorHandler::NotifyPipe::notify(), and nidas::util::Mutex::unlock().
scheduleClose() [1/2]
void SensorHandler::scheduleClose (PolledDSMSensor * psensor) throw () private
Schedule this PolledDSMSensor to be closed when convenient.
References _notifyPipe, _pendingSensorClosures, _pollingChanged, _pollingMutex, nidas::util::Thread::kill(), nidas::util::Mutex::lock(), nidas::core::SensorHandler::NotifyPipe::notify(), and nidas::util::Mutex::unlock().
scheduleClose() [2/2]
void SensorHandler::scheduleClose (RemoteSerialConnection * conn) throw () private
References _notifyPipe, _pendingRserialClosures, _pollingChanged, _pollingMutex, nidas::util::Thread::kill(), nidas::util::Mutex::lock(), nidas::core::SensorHandler::NotifyPipe::notify(), and nidas::util::Mutex::unlock().
scheduleReopen()
void SensorHandler::scheduleReopen (PolledDSMSensor * psensor) throw () private
Schedule this PolledDSMSensor to be closed and reopened.
References _notifyPipe, _pendingSensorReopens, _pollingChanged, _pollingMutex, nidas::util::Thread::kill(), nidas::util::Mutex::lock(), nidas::core::SensorHandler::NotifyPipe::notify(), and nidas::util::Mutex::unlock().
Referenced by checkTimeouts().
sensorIsOpen()
void SensorHandler::sensorIsOpen (DSMSensor * sensor) throw ()
After SensorOpener has opened the sensor, it will notify SensorHandler via this method that the sensor is open.
References _acceptingOpens, _newOpenedSensors, _notifyPipe, _pollingChanged, _pollingMutex, nidas::util::Thread::kill(), nidas::util::Mutex::lock(), nidas::core::SensorHandler::NotifyPipe::notify(), and nidas::util::Mutex::unlock().
Referenced by nidas::core::SensorOpener::run().
setCancelDeferred()
void Thread::setCancelDeferred (bool val) protected inherited
Set the cancel type for this thread.
true means cancel requests are deferred until the next cancellation point. false means they occur instantly. This is protected, it should be called only from a thread's own run method. See the pthreads(7) man page for a list of the cancellation points.
Note: non-deferred canceling is difficult to get right. It has not been tested with this class, and is not recommended.
References nidas::util::Thread::_cancel_deferred.
setCancelEnabled()
void Thread::setCancelEnabled (bool val) protected inherited
Set the cancel state for this thread - false means cancel requests are ignored.
See pthread_setcancelstate. This is protected, it should be called only from a thread's own run method.
References nidas::util::Thread::_cancel_enabled.
setNonRealTimePriority()
bool Thread::setNonRealTimePriority () inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::setThreadScheduler().
setRealTimeFIFOPriority()
bool Thread::setRealTimeFIFOPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_FIFO, and nidas::util::Thread::setThreadScheduler().
Referenced by nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setRealTimeRoundRobinPriority()
bool Thread::setRealTimeRoundRobinPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_RR, and nidas::util::Thread::setThreadScheduler().
setSensorStatsInterval()
void nidas::core::SensorHandler::setSensorStatsInterval (int val) inline
Set the sensor statistics calculation period.
Parameters
val Period, in milliseconds.
References _sensorStatsInterval, and USECS_PER_MSEC.
Referenced by SensorHandler().
setThreadScheduler()
void Thread::setThreadScheduler (enum SchedPolicy policy, int priority) inherited
Exceptions
Exception
References nidas::util::Thread::_mutex, and nidas::util::Thread::setThreadSchedulerNolock().
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::getLooper(), nidas::util::Thread::setNonRealTimePriority(), nidas::util::Thread::setRealTimeFIFOPriority(), and nidas::util::Thread::setRealTimeRoundRobinPriority().
setThreadSchedulerNolock()
void Thread::setThreadSchedulerNolock (enum SchedPolicy policy, int priority) private inherited
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::util::Thread::setThreadScheduler(), and nidas::util::Thread::start().
setupTimeouts()
void SensorHandler::setupTimeouts (int sensorCheckIntervalMsecs) private
References _polledSensors, MSECS_PER_SEC, NSECS_PER_MSEC, and nidas::core::SensorHandler::PolledDSMSensor::setupTimeouts().
Referenced by handlePollingChange().
sigAction()
void Thread::sigAction (int sig, siginfo_t * si, void * vptr) static private inherited
References DLOG, nidas::util::Thread::getName(), and nidas::util::Thread::signalHandler().
Referenced by nidas::util::Thread::thr_add_sig().
signalHandler()
void SensorHandler::signalHandler (int sig, siginfo_t *) virtual
Override default implementation of Thread::signalHandler().
The default implementation sets the interrupted flag, which we don't want.
Reimplemented from nidas::util::Thread.
start()
void Thread::start () virtual inherited
Start the thread running, meaning execute the run method in a separate thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_interrupted, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), nidas::util::Thread::getName(), nidas::util::Thread::makeFullName(), nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::registerThread(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::thr_run(), nidas::util::Thread::thr_run_detached(), and WLOG.
Referenced by nidas::util::McSocketListener::accept(), nidas::dynld::RawSampleService::connect(), nidas::dynld::XMLConfigAllService::connected(), nidas::dynld::XMLConfigService::connected(), nidas::core::DerivedDataReader::createInstance(), nidas::dynld::raf::SyncServer::getTimeWindow(), nidas::util::McSocket< SocketT >::joinMulticaster(), main(), nidas::core::FsMount::mount(), nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), nidas::core::SamplePipeline::rawinit(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), ServerThread::run(), PSI::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), nidas::core::FsMountWorkerThread::run(), run(), nidas::core::Socket::ConnectionThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::dynld::raf::SyncServer::setTimeWindow(), nidas::core::Looper::setupClientMaps(), nidas::core::DSMServerApp::startStatusThread(), nidas::core::DSMEngine::startXmlRpcThread(), and nidas::core::DSMServerApp::startXmlRpcThread().
test()
int Thread::test (int argc, char ** argv) static inherited
a test method.
References nidas::util::Runnable::amInterrupted(), nidas::util::Thread::blockSignal(), nidas::util::Thread::getFullName(), nidas::util::Thread::getName(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Runnable::run(), nidas::util::Thread::Thread(), and nidas::util::Exception::what().
testCancel()
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
thr_add_sig()
void Thread::thr_add_sig (int sig) static private inherited
References nidas::util::Thread::sigAction().
Referenced by nidas::util::Thread::blockSignal(), and nidas::util::Thread::unblockSignal().
thr_cleanup()
void Thread::thr_cleanup (void * me) static private inherited
References nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), ILOG, and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run().
thr_cleanup_delete()
void Thread::thr_cleanup_delete (void * me) static private inherited
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), nidas::util::Mutex::lock(), nidas::util::Mutex::unlock(), and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run_detached().
thr_run()
void * Thread::thr_run (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup().
Referenced by nidas::util::Thread::start().
thr_run_detached()
void * Thread::thr_run_detached (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup_delete().
Referenced by nidas::util::Thread::start().
unblockSignal()
void Thread::unblockSignal (int sig) inherited
Install a signal handler and unblock the signal.
The signal handler will log a message about the receipt of the signal at severity LOG_INFO using the nidas::util::Logger. Then, if the signal handler is being invoked from a registered Thread, the virtual method signalHandler() for that Thread will be called.
The signal handler is installed with the sigaction() system call, and will be the action for the given signal in all threads, including the main() thread. If other threads do not wish to take action on a given signal, they should call blockSignal(sig). Or they can define their own signalHandler() method.
After installing the signal handler, the signal is added to those that are unblocked for the thread, or if the Thread is not yet running, the signal will be unblocked in the thread once it runs.
As with blockSignal(), this method is typically called on this Thread before it has started. If this Thread has started, then the signal will only be unblocked if the method is called from this Thread, i.e. from its own run() method.
To install a signal handler, and then block the signal so that it is held as pending until it is later unblocked, typically with pselect(), or sigwaitinfo(), do:
void Thread::run()
{
    // get the existing signal mask
    sigset_t sigmask;
    pthread_sigmask(SIG_BLOCK,NULL,&sigmask);
    // remove SIGUSR1 from the mask passed to pselect
    sigdelset(&sigmask,SIGUSR1);
    for (;;) {
        pselect(nfd,&readfds,0,0,0,&sigmask);
        ...
    }
}
...
thread.unblockSignal(SIGUSR1);
thread.blockSignal(SIGUSR1);
thread.start();
...
try {
    if (thread.isRunning()) {
        thread.kill(SIGUSR1);
        thread.join()
    }
}
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::core::DerivedDataReader::DerivedDataReader(), nidas::core::FsMountWorkerThread::FsMountWorkerThread(), nidas::core::StatusListener::StatusListener(), nidas::core::StatusThread::StatusThread(), nidas::dynld::XMLConfigService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
unregisterThread()
void Thread::unregisterThread () private inherited
Referenced by nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
unsetId()
void nidas::util::Thread::unsetId () inline private inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
updateTimeouts()
void nidas::core::SensorHandler::updateTimeouts () inline
Tell the SensorHandler that one or more sensor timeouts have changed.
References _pollingChanged.
Referenced by nidas::core::RemoteSerialConnection::close(), and nidas::core::RemoteSerialConnection::doEscCmds().
Friends And Related Function Documentation
RemoteSerialConnection
friend class RemoteSerialConnection friend
RemoteSerialListener
friend class RemoteSerialListener friend
Referenced by run().
Member Data Documentation
_acceptingOpens
bool nidas::core::SensorHandler::_acceptingOpens private
Referenced by handlePollingChange(), run(), and sensorIsOpen().
_activeRserialConns
std::list<RemoteSerialConnection*> nidas::core::SensorHandler::_activeRserialConns private
Referenced by add(), handlePollingChange(), remove(), and run().
_allSensors
std::list<DSMSensor*> nidas::core::SensorHandler::_allSensors private
The collection of DSMSensors to be handled.
Referenced by add(), addSensor(), getAllSensors(), and ~SensorHandler().
_blockedSignals
sigset_t nidas::util::Thread::_blockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
_cancel_deferred
bool nidas::util::Thread::_cancel_deferred private inherited
Referenced by nidas::util::Thread::isCancelDeferred(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelDeferred().
_cancel_enabled
bool nidas::util::Thread::_cancel_enabled private inherited
Referenced by nidas::util::Thread::isCancelEnabled(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelEnabled().
_detached
bool nidas::util::Thread::_detached private inherited
Referenced by nidas::util::Thread::isDetached(), nidas::util::Thread::makeFullName(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_epollfd
int nidas::core::SensorHandler::_epollfd private
epoll file descriptor.
Referenced by getEpollFd(), run(), and ~SensorHandler().
_events
struct epoll_event* nidas::core::SensorHandler::_events private
Referenced by handlePollingChange(), run(), and ~SensorHandler().
_exception
Exception* nidas::util::Thread::_exception private inherited
Exception thrown by run method.
Referenced by nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::util::Thread::~Thread().
_fullBufferReads
std::map<const DSMSensor*,unsigned int> nidas::core::SensorHandler::_fullBufferReads private
For each sensor, number of times that the input buffer was filled in a read, i.e.
the read did not consume all the data available.
Referenced by incrementFullBufferReads().
_fullname
std::string nidas::util::Thread::_fullname private inherited
Referenced by nidas::util::Thread::getFullName(), and nidas::util::Thread::makeFullName().
_id
pthread_t nidas::util::Thread::_id private inherited
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::makeFullName(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_interrupted
bool nidas::util::Thread::_interrupted private inherited
Referenced by nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::signalHandler(), and nidas::util::Thread::start().
_mutex
Mutex nidas::util::Thread::_mutex mutable private inherited
Mutex for accessing _id.
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::pRun(), nidas::util::Thread::setThreadScheduler(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_name
std::string nidas::util::Thread::_name private inherited
Referenced by nidas::util::Thread::getName(), and nidas::util::Thread::makeFullName().
_nevents
int nidas::core::SensorHandler::_nevents private
Referenced by handlePollingChange(), and run().
_newOpenedSensors
std::list<DSMSensor*> nidas::core::SensorHandler::_newOpenedSensors private
Newly opened DSMSensors, which are to be added to the list of file descriptors to be polled.
Referenced by handlePollingChange(), run(), and sensorIsOpen().
_newRserials
std::list<RemoteSerialConnection*> nidas::core::SensorHandler::_newRserials private
Newly opened RemoteSerialConnections, which are to be added to the list of file descriptors to be polled.
Referenced by handlePollingChange(), and scheduleAdd().
_notifyPipe
NotifyPipe* nidas::core::SensorHandler::_notifyPipe private
Referenced by handlePollingChange(), interrupt(), run(), scheduleAdd(), scheduleClose(), scheduleReopen(), sensorIsOpen(), and ~SensorHandler().
_openedSensors
std::list<DSMSensor*> nidas::core::SensorHandler::_openedSensors private
Collection of DSMSensors which have been opened.
Referenced by add(), getOpenedSensors(), and remove().
_opener
SensorOpener nidas::core::SensorHandler::_opener private
Referenced by addSensor(), handlePollingChange(), join(), and run().
_pendingRserialClosures
std::set<RemoteSerialConnection*> nidas::core::SensorHandler::_pendingRserialClosures private
RemoteSerialConnections to be closed, probably because the socket connection closed.
Referenced by handlePollingChange(), run(), and scheduleClose().
_pendingSensorClosures
std::set<PolledDSMSensor*> nidas::core::SensorHandler::_pendingSensorClosures private
Sensors to be closed, probably due to a read error or a timeout.
Defined as a set to avoid bugs where a sensor might be added twice.
Referenced by handlePollingChange(), run(), and scheduleClose().
_pendingSensorReopens
std::set<PolledDSMSensor*> nidas::core::SensorHandler::_pendingSensorReopens private
Sensors to be closed and then reopened.
Also probably due to a read error or a timeout.
Referenced by handlePollingChange(), and scheduleReopen().
_polledSensors
std::list<PolledDSMSensor*> nidas::core::SensorHandler::_polledSensors private
Those DSMSensors currently being polled.
Referenced by add(), checkTimeouts(), handlePollingChange(), remove(), run(), setupTimeouts(), and ~SensorHandler().
_pollingChanged
bool nidas::core::SensorHandler::_pollingChanged private
A change in the polling file descriptors needs to be handled.
Referenced by handlePollingChange(), run(), scheduleAdd(), scheduleClose(), scheduleReopen(), sensorIsOpen(), and updateTimeouts().
_pollingMutex
nidas::util::Mutex nidas::core::SensorHandler::_pollingMutex mutable private
Referenced by add(), addSensor(), getAllSensors(), getOpenedSensors(), handlePollingChange(), remove(), run(), scheduleAdd(), scheduleClose(), scheduleReopen(), and sensorIsOpen().
_remoteSerialSocketPort
unsigned short nidas::core::SensorHandler::_remoteSerialSocketPort private
Referenced by run().
_rserial
RemoteSerialListener* nidas::core::SensorHandler::_rserial private
Referenced by handlePollingChange(), run(), and ~SensorHandler().
_running
bool nidas::util::Thread::_running private inherited
Referenced by nidas::util::Thread::isRunning(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
_sensorCheckIntervalMsecs
int nidas::core::SensorHandler::_sensorCheckIntervalMsecs private
Interval for checking for timeouts on each sensor, in milliseconds.
Will be -1 if no sensors have a timeout.
Referenced by handlePollingChange(), and run().
_sensorCheckIntervalUsecs
unsigned int nidas::core::SensorHandler::_sensorCheckIntervalUsecs private
Same as _sensorCheckIntervalMsecs, but in microseconds.
Referenced by checkTimeouts(), and handlePollingChange().
_sensorCheckTime
dsm_time_t nidas::core::SensorHandler::_sensorCheckTime private
Referenced by checkTimeouts(), handlePollingChange(), and run().
_sensorStatsInterval
unsigned int nidas::core::SensorHandler::_sensorStatsInterval private
Interval for calculcating through-put statistics on each sensor, in microseconds.
Referenced by calcStatistics(), getSensorStatsInterval(), SensorHandler(), and setSensorStatsInterval().
_sensorStatsTime
dsm_time_t nidas::core::SensorHandler::_sensorStatsTime private
Referenced by calcStatistics(), run(), and SensorHandler().
_thread_attr
pthread_attr_t nidas::util::Thread::_thread_attr private inherited
Referenced by nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_unblockedSignals
sigset_t nidas::util::Thread::_unblockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
unknownName
std::string Thread::unknownName = std::string("unknown") static private inherited
Referenced by nidas::util::Thread::currentName().
The documentation for this class was generated from the following files:
nidas/core/SensorHandler.h
nidas/core/SensorHandler.cc