nidas: nidas::core::FullSampleComparator Class Reference
nidas::core::FullSampleComparator Class Reference
Comparator of pointers to Samples, does the same checks as SampleHeaderComparator, but in addition, if two samples compare as equal, then compares their data.
#include <SortedSampleSet.h>
Public Member Functions
bool operator() (const Sample *x, const Sample *y) const
Return true if x is less than y.
Detailed Description
Comparator of pointers to Samples, does the same checks as SampleHeaderComparator, but in addition, if two samples compare as equal, then compares their data.
Member Function Documentation
operator()()
bool nidas::core::FullSampleComparator::operator() (const Sample * x, const Sample * y) const inline
Return true if x is less than y.
References nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataLength(), nidas::core::Sample::getId(), and nidas::core::Sample::getTimeTag().
The documentation for this class was generated from the following file:
nidas/core/SortedSampleSet.h