nidas: nidas::core::DSMSensor::MyDictionary Class Reference
nidas::core::DSMSensor::MyDictionary Class Reference
Public Member Functions
MyDictionary (DSMSensor *sensor)
MyDictionary (const MyDictionary &x)
MyDictionary & operator= (const MyDictionary &rhs)
bool getTokenValue (const std::string &token, std::string &value) const
std::string expandString (const std::string &input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Private Attributes
DSMSensor * _sensor
Constructor & Destructor Documentation
MyDictionary() [1/2]
nidas::core::DSMSensor::MyDictionary::MyDictionary (DSMSensor * sensor) inline
MyDictionary() [2/2]
nidas::core::DSMSensor::MyDictionary::MyDictionary (const MyDictionary & x) inline
Member Function Documentation
expandString()
string Dictionary::expandString (const std::string & input) const inherited
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Referenced by nidas::core::DSMConfig::expandString(), nidas::core::DSMSensor::expandString(), nidas::core::Project::expandString(), nidas::core::Site::expandString(), and nidas::core::ParameterT< T >::fromDOMElement().
getTokenValue()
bool DSMSensor::MyDictionary::getTokenValue (const std::string & token, std::string & value) const virtual
Implements nidas::core::Dictionary.
References _sensor, nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getHeightString(), nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMConfig::getTokenValue().
Referenced by nidas::core::DSMSensor::getTokenValue().
operator=()
MyDictionary& nidas::core::DSMSensor::MyDictionary::operator= (const MyDictionary & rhs) inline
References _sensor.
Member Data Documentation
_sensor
DSMSensor* nidas::core::DSMSensor::MyDictionary::_sensor private
Referenced by getTokenValue(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/DSMSensor.h
nidas/core/DSMSensor.cc