nidas: nidas/apps/dmd_mmat_vin_limit_test.cc File Reference
dmd_mmat_vin_limit_test.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <assert.h>
#include <nidas/linux/diamond/dmd_mmat.h>
#include <fcntl.h>
#include <sys/ioctl.h>
Macros
#define NUM_ADC_TEST_CHANNELS_DEFAULT 16
#define ADC_SAMPLE_RATE_DEFAULT 10
#define ADC_GAIN_DEFAULT 2
#define V_LIMIT_HIGH_DEFAULT 2.510
#define V_LIMIT_LOW_DEFAULT 2.490
Functions
void print_app_usage (void)
float ctov (int code, int gain)
int main (int argc, char **argv)
Macro Definition Documentation
ADC_GAIN_DEFAULT
#define ADC_GAIN_DEFAULT 2
ADC_SAMPLE_RATE_DEFAULT
#define ADC_SAMPLE_RATE_DEFAULT 10
NUM_ADC_TEST_CHANNELS_DEFAULT
#define NUM_ADC_TEST_CHANNELS_DEFAULT 16
V_LIMIT_HIGH_DEFAULT
#define V_LIMIT_HIGH_DEFAULT 2.510
V_LIMIT_LOW_DEFAULT
#define V_LIMIT_LOW_DEFAULT 2.490
Function Documentation
ctov()
float ctov (int code, int gain)
Referenced by main().
main()
int main (int argc, char ** argv)
References ADC_GAIN_DEFAULT, ADC_SAMPLE_RATE_DEFAULT, nidas_a2d_sample_config::bipolar, nidas_a2d_sample_config::channels, ctov(), dsm_sample::data, DMMAT_A2D_GET_STATUS, DMMAT_START, DMMAT_STOP, fd, DMMAT_A2D_Status::fifoEmpty, DMMAT_A2D_Status::fifoOverflows, DMMAT_A2D_Status::fifoUnderflows, nidas_a2d_sample_config::filterType, nidas_a2d_sample_config::gain, nidas_a2d_config::latencyUsecs, dsm_sample::length, MAX_A2D_CHANNELS, DMMAT_A2D_Status::missedSamples, nidas_a2d_sample_config::nFilterData, NIDAS_A2D_CONFIG_SAMPLE, NIDAS_A2D_GET_NCHAN, NIDAS_A2D_SET_CONFIG, NIDAS_FILTER_PICKOFF, NUM_ADC_TEST_CHANNELS_DEFAULT, nidas_a2d_sample_config::nvars, print_app_usage(), printf(), nidas_a2d_sample_config::rate, nidas_a2d_config::scanRate, nidas_a2d_sample_config::sindex, SIZEOF_DSM_SAMPLE_HEADER, dsm_sample::timetag, USECS_PER_SEC, V_LIMIT_HIGH_DEFAULT, and V_LIMIT_LOW_DEFAULT.
print_app_usage()
void print_app_usage (void)
References ADC_SAMPLE_RATE_DEFAULT, NUM_ADC_TEST_CHANNELS_DEFAULT, printf(), V_LIMIT_HIGH_DEFAULT, and V_LIMIT_LOW_DEFAULT.
Referenced by main().