nidas: PacketReader Class Reference
PacketReader Class Reference
Public Member Functions
PacketReader ()
~PacketReader ()
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
const deque< n_u::DatagramPacket * > & getPackets () const
nidas::util::Cond & dataReady ()
void loop () throw ()
const string & getHeader () const
int getTCPPort () const
int getMaxPacketSize () const
void checkPacket (n_u::DatagramPacket &)
void logBadPacket (const n_u::DatagramPacket &pkt, const string &msg)
Private Attributes
int _udpport
int _tcpport
int _packetsize
string _header
deque< n_u::DatagramPacket * > _packets
nidas::util::Cond _dataReady
size_t _rejectedPackets
long long _minSampleTime
long long _maxSampleTime
int _maxDsmId
unsigned int _maxSampleLength
int _rejectPacketInterval
int _packetReadInterval
NidasApp _app
Static Private Attributes
static const int DEFAULT_PACKET_SIZE = 16384
Constructor & Destructor Documentation
PacketReader()
PacketReader::PacketReader ()
References _app, and nidas::core::NidasApp::setApplicationInstance().
~PacketReader()
PacketReader::~PacketReader ()
References _dataReady, _packets, CLOG, nidas::util::DatagramPacketT< DataT >::getData(), nidas::util::Cond::lock(), nidas::util::Cond::unlock(), and nidas::util::Exception::what().
Member Function Documentation
checkPacket()
void PacketReader::checkPacket (n_u::DatagramPacket & pkt)
References _maxDsmId, _maxSampleLength, _maxSampleTime, _minSampleTime, _rejectedPackets, _rejectPacketInterval, nidas::core::CHAR_ST, nidas::util::UTime::format(), GET_DSM_ID, GET_SPS_ID, nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr(), nidas::core::SampleHeader::getDataByteLength(), nidas::core::SampleHeader::getId(), nidas::util::DatagramPacketBase::getLength(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleHeader::getTimeTag(), nidas::core::SampleHeader::getType(), logBadPacket(), and nidas::util::DatagramPacketBase::setLength().
Referenced by loop().
dataReady()
nidas::util::Cond& PacketReader::dataReady () inline
Referenced by WriterThread::run().
getHeader()
const string& PacketReader::getHeader () const inline
getMaxPacketSize()
int PacketReader::getMaxPacketSize () const inline
Referenced by WriterThread::run().
getPackets()
const deque<n_u::DatagramPacket*>& PacketReader::getPackets () const inline
Referenced by WriterThread::run().
getTCPPort()
int PacketReader::getTCPPort () const inline
logBadPacket()
void PacketReader::logBadPacket (const n_u::DatagramPacket & pkt, const string & msg)
References _rejectedPackets, nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::getSocketAddress(), nidas::util::SocketAddress::toString(), and WLOG.
Referenced by checkPacket().
loop()
void PacketReader::loop () throw ()
References _dataReady, _packetReadInterval, _packets, _packetsize, _udpport, nidas::util::Cond::broadcast(), checkPacket(), nidas::util::DatagramSocket::close(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::DatagramPacketBase::getSocketAddress(), interrupted, nidas::util::Cond::lock(), PLOG, nidas::util::DatagramSocket::receive(), nidas::util::SocketAddress::toString(), nidas::util::Cond::unlock(), VLOG, and nidas::util::Exception::what().
Referenced by main().
parseRunstring()
int PacketReader::parseRunstring (int argc, char ** argv)
References _app, _header, _packetReadInterval, _packetsize, _rejectPacketInterval, _tcpport, _udpport, nidas::core::NidasAppArg::acceptShortFlag(), nidas::core::NidasApp::allowUnrecognized(), nidas::core::NidasAppArgv::argc, nidas::core::NidasAppArgv::argv, nidas::core::NidasApp::DebugDaemon, nidas::core::NidasApp::enableArguments(), fclose(), fp, nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::loggingArgs(), nidas::core::NidasApp::parseArgs(), usage(), nidas::core::NidasApp::Version, and nidas::util::Exception::what().
Referenced by main().
usage()
int PacketReader::usage (const char * argv0)
References _app, DEFAULT_PACKET_SIZE, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
_app
NidasApp PacketReader::_app private
Referenced by PacketReader(), parseRunstring(), and usage().
_dataReady
nidas::util::Cond PacketReader::_dataReady private
Referenced by loop(), and ~PacketReader().
_header
string PacketReader::_header private
Referenced by parseRunstring().
_maxDsmId
int PacketReader::_maxDsmId private
Referenced by checkPacket().
_maxSampleLength
unsigned int PacketReader::_maxSampleLength private
Referenced by checkPacket().
_maxSampleTime
long long PacketReader::_maxSampleTime private
Referenced by checkPacket().
_minSampleTime
long long PacketReader::_minSampleTime private
Referenced by checkPacket().
_packetReadInterval
int PacketReader::_packetReadInterval private
Referenced by loop(), and parseRunstring().
_packets
deque<n_u::DatagramPacket*> PacketReader::_packets private
Referenced by loop(), and ~PacketReader().
_packetsize
int PacketReader::_packetsize private
Referenced by loop(), and parseRunstring().
_rejectedPackets
size_t PacketReader::_rejectedPackets private
Referenced by checkPacket(), and logBadPacket().
_rejectPacketInterval
int PacketReader::_rejectPacketInterval private
Referenced by checkPacket(), and parseRunstring().
_tcpport
int PacketReader::_tcpport private
Referenced by parseRunstring().
_udpport
int PacketReader::_udpport private
Referenced by loop(), and parseRunstring().
DEFAULT_PACKET_SIZE
const int PacketReader::DEFAULT_PACKET_SIZE = 16384 static private
Referenced by usage().
The documentation for this class was generated from the following file:
nidas/apps/nidas_udp_relay.cc