nidas: nidas::core::SampleT< DataT > Class Template Reference
nidas::core::SampleT< DataT > Class Template Reference
A typed Sample, with data of type DataT.
#include <Sample.h>
Public Member Functions
SampleT ()
~SampleT ()
sampleType getType () const
Get the type of the sample.
unsigned int getDataLength () const
Get number of elements of type DataT in data.
void setDataLength (unsigned int val)
Set the number of elements of type DataT in data.
void * getVoidDataPtr ()
Get a void* pointer to the data portion of the sample.
const void * getConstVoidDataPtr () const
Get a const void* pointer to the data portion of the sample.
DataT * getDataPtr ()
const DataT * getConstDataPtr () const
double getDataValue (unsigned int i) const
Implementation of virtual method.
void setDataValue (unsigned int i, double val)
Implementation of virtual method.
void setDataValue (unsigned int i, float val)
Implementation of virtual method.
unsigned int getAllocLength () const
Get number of elements allocated in data portion of sample.
unsigned int getAllocByteLength () const
Get number of bytes allocated in data portion of sample.
void allocateData (unsigned int val)
Allocate data.
void reallocateData (unsigned int val)
Re-allocate data, space, keeping contents.
void freeReference () const
Decrement the reference count for this sample.
void setTimeTag (dsm_time_t val)
dsm_time_t getTimeTag () const
Time-tag in non-leap microseconds since Jan 1, 1970 00:00 GMT.
void setId (dsm_sample_id_t val)
Set the id portion of the sample header.
dsm_sample_id_t getId () const
Get the id portion of the sample header.
void setRawId (dsm_sample_id_t val)
Set the full, raw id portion of the sample header.
dsm_sample_id_t getRawId () const
void setSpSId (unsigned int val)
Set the short id portion of the sample header, containing the sensor + sample ids.
unsigned int getSpSId () const
Get the short id portion of the sample header.
void setDSMId (unsigned int val)
Set the DSM (data system) id portion of the sample header.
unsigned int getDSMId () const
Get the DSM (data system) id portion of the sample header.
unsigned int getDataByteLength () const
Get the number of bytes in data portion of sample.
unsigned int getHeaderLength () const
Number of bytes in header.
const void * getHeaderPtr () const
Get a pointer to the header portion of the sample.
void holdReference () const
Increment the reference count for this sample.
Static Public Member Functions
static unsigned int getMaxDataLength ()
Maximum number of elements in data.
static int sizeofDataType ()
Protected Member Functions
SampleT (const SampleT &)
No copy.
SampleT & operator= (const SampleT &)
No assignment.
Protected Attributes
DataT * _data
Pointer to the actual data.
unsigned int _allocLen
Number of bytes allocated in data.
SampleHeader _header
int _refCount
The reference count.
nidas::util::Mutex _refLock
Static Protected Attributes
static int _nsamps
Global count of the number of samples in use by a process.
Detailed Description
template<class DataT>
class nidas::core::SampleT< DataT >
A typed Sample, with data of type DataT.
Constructor & Destructor Documentation
SampleT() [1/2]
template<class DataT > nidas::core::SampleT< DataT >::SampleT () inline
~SampleT()
template<class DataT > nidas::core::SampleT< DataT >::~SampleT () inline
References nidas::core::SampleT< DataT >::_data.
SampleT() [2/2]
template<class DataT > nidas::core::SampleT< DataT >::SampleT (const SampleT< DataT > &) protected
No copy.
Member Function Documentation
allocateData()
template<class DataT > void nidas::core::SampleT< DataT >::allocateData (unsigned int val) inline virtual
Allocate data.
Parameters
val number of DataT's to allocated.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_allocLen, nidas::core::SampleT< DataT >::_data, nidas::core::SampleT< DataT >::getMaxDataLength(), and nidas::core::SampleT< DataT >::setDataLength().
freeReference()
template<class DataT > void nidas::core::SampleT< DataT >::freeReference virtual
Decrement the reference count for this sample.
Free a reference to a sample.
If the reference count is zero, then put the Sample into the SamplePool. freeReference() can be performed on a const Sample. However if at any moment a user of a const Sample has called freeReference more times than they have called holdReference, then they have violated the contract of a const Sample. Once the sample goes back into the sample pool it may be altered.
Samples can be used like normal variables without reference counting: { SampleT< samp; // automatic variable samp.setTimeTag(99); ... } // automatic variable destroyed
Or the reference count capability can be used. Here one saves samples into a buffer, and then later pops them off.
void pushSample(const Sample* samp) { samp->holdReference(); buffer.push_back(samp); } const Sample* popSample() { const Sample* samp = buffer.back(); buffer.pop_back(); samp->freeReference(); return samp; }
// Get sample from SamplePool. // The reference count will be one after the sample // is fetched from the pool - holdReference is // called for you by SamplePool. Sample* samp = SamplePool::getInstance()->getSample(100); ... pushSample(samp); ... samp = popSample(); ... // When you're completely done with it, call freeReference(). samp->freeReference();
Return it to its pool if no-one is using it.
Implements nidas::core::Sample.
References nidas::core::SamplePool< SampleType >::putSample().
Referenced by nidas::core::SampleAverager::flush(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::TSI_CPC3772::process(), TestSource::run(), nidas::dynld::isff::GOESOutput::run(), nidas::core::CharacterSensor::searchSampleScanners(), nidas::core::NearestResamplerAtRate::~NearestResamplerAtRate(), and nidas::dynld::raf::SyncRecordSource::~SyncRecordSource().
getAllocByteLength()
template<class DataT > unsigned int nidas::core::SampleT< DataT >::getAllocByteLength () const inline virtual
Get number of bytes allocated in data portion of sample.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_allocLen.
getAllocLength()
template<class DataT > unsigned int nidas::core::SampleT< DataT >::getAllocLength () const inline virtual
Get number of elements allocated in data portion of sample.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_allocLen.
Referenced by nidas::core::SampleT< DataT >::setDataLength().
getConstDataPtr()
template<class DataT > const DataT* nidas::core::SampleT< DataT >::getConstDataPtr () const inline
References nidas::core::SampleT< DataT >::_data.
Referenced by nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::isff::GOESOutput::receive(), nidas::dynld::psql::PSQLSampleOutput::receive(), nidas::dynld::raf::CVIProcessor::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::isff::SE_GOESXmtr::transmitDataSE110(), and nidas::dynld::isff::SE_GOESXmtr::transmitDataSE120().
getConstVoidDataPtr()
template<class DataT > const void* nidas::core::SampleT< DataT >::getConstVoidDataPtr () const inline virtual
Get a const void* pointer to the data portion of the sample.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data.
Referenced by nidas::dynld::iss::WICORSensor::process(), nidas::dynld::TSI_CPC3772::process(), and nidas::core::CharacterSensor::searchSampleScanners().
getDataByteLength()
unsigned int nidas::core::Sample::getDataByteLength () const inline inherited
Get the number of bytes in data portion of sample.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getDataByteLength().
Referenced by SampleCounter::accumulateData(), SampleCounter::accumulateSample(), nidas::dynld::BlockStats::addGoodSample(), nidas::dynld::raf::PIP_Serial::appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), nidas::dynld::DSC_FreqCounter::calculatePeriodUsec(), nidas::dynld::SampleInputStream::checkUnexpectedEOF(), DumpClient::dumpNaked(), nidas::dynld::raf::IRIGSensor::get100HzBacklog(), nidas::core::SampleT< DataT >::getDataLength(), nidas::dynld::raf::IRIGSensor::getIRIGTime(), nidas::dynld::raf::IRIGSensor::getStatusPtr(), nidas::dynld::raf::IRIGSensor::getUnixTime(), nidas::dynld::raf::A2D_Serial::nextSample(), nidas::dynld::raf::UDPArincSensor::nextSample(), nidas::dynld::SampleInputStream::nextSample(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::dynld::IR104_Relays::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::dynld::DSC_PulseCounter::process(), nidas::dynld::raf::A2DBoardTempSensor::process(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::PHIPS_UDP::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::raf::TwoD64_USB::processSOR(), nidas::dynld::AsciiOutput::receive(), MergeVerifier::reportBackward(), MergeVerifier::reportDuplicate(), MergeVerifier::reportMissing(), ExtractFast2D::run(), ExtractDMT::run(), nidas::core::SampleBuffer::run(), nidas::core::SampleSorter::run(), and nidas::dynld::SampleOutputStream::write().
getDataLength()
template<class DataT > unsigned int nidas::core::SampleT< DataT >::getDataLength () const inline virtual
Get number of elements of type DataT in data.
Implements nidas::core::Sample.
References nidas::core::Sample::getDataByteLength().
Referenced by nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::isff::GOESOutput::receive(), nidas::dynld::psql::PSQLSampleOutput::receive(), nidas::core::NearestResampler::receive(), nidas::dynld::raf::CVIProcessor::receive(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::isff::SE_GOESXmtr::transmitDataSE110(), nidas::dynld::isff::SE_GOESXmtr::transmitDataSE120(), nidas::dynld::isff::WisardMote::unpack100thSec(), nidas::dynld::isff::WisardMote::unpack10thSec(), nidas::dynld::isff::WisardMote::unpackAccumSec(), nidas::dynld::isff::WisardMote::unpackCNR2(), nidas::dynld::isff::WisardMote::unpackGsoil(), nidas::dynld::isff::WisardMote::unpackInt16(), nidas::dynld::isff::WisardMote::unpackInt32(), nidas::dynld::isff::WisardMote::unpackNR01(), nidas::dynld::isff::WisardMote::unpackPicTime(), nidas::dynld::isff::WisardMote::unpackPicTimeFields(), nidas::dynld::isff::WisardMote::unpackPower(), nidas::dynld::isff::WisardMote::unpackQsoil(), nidas::dynld::isff::WisardMote::unpackRlw(), nidas::dynld::isff::WisardMote::unpackRlwKZ(), nidas::dynld::isff::WisardMote::unpackRnet(), nidas::dynld::isff::WisardMote::unpackRsw(), nidas::dynld::isff::WisardMote::unpackRsw2(), nidas::dynld::isff::WisardMote::unpackStatus(), nidas::dynld::isff::WisardMote::unpackTP01(), nidas::dynld::isff::WisardMote::unpackTRH(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::WisardMote::unpackUint16(), nidas::dynld::isff::WisardMote::unpackUint32(), and nidas::dynld::isff::WisardMote::unpackXbee().
getDataPtr()
template<class DataT > DataT* nidas::core::SampleT< DataT >::getDataPtr () inline
References nidas::core::SampleT< DataT >::_data.
Referenced by nidas::core::DSMSensor::applyConversions(), nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::isff::NCAR_TRH::convertVariable(), nidas::dynld::ParoSci_202BG_P::createPressureSample(), nidas::dynld::raf::SidsNetSensor::createSamples(), nidas::dynld::raf::TwoD_USB::createSamples(), nidas::core::NearestResampler::flush(), nidas::core::SampleAverager::flush(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::dynld::IR104_Relays::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::NCAR_TRH::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::dynld::DSC_Event::process(), nidas::dynld::DSC_FreqCounter::process(), nidas::dynld::DSC_PulseCounter::process(), nidas::dynld::ParoSci_202BG_T::process(), nidas::dynld::raf::A2DBoardTempSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::IRIGSensor::process(), nidas::dynld::GPS_NMEA_Serial::process(), nidas::dynld::GPS_Novatel_Serial::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::BCPD_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::PHIPS_UDP::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::PSI9116_Sensor::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::TwoD_House::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::Watlow::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::WxtSensor::process(), nidas::dynld::raf::DSMArincSensor::processAlta(), nidas::dynld::raf::TwoD64_USB::processSOR(), nidas::dynld::raf::TwoD64_USB_v3::processSOR(), nidas::dynld::raf::DSMAnalogSensor::processTemperature(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::isff::GOESOutput::receive(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::dynld::isff::GOESOutput::run(), nidas::core::CharacterSensor::searchSampleScanners(), nidas::dynld::raf::SyncRecordSource::sendSyncHeader(), nidas::core::DSMSensor::trimUnparsed(), nidas::dynld::isff::WisardMote::unpack100thSec(), nidas::dynld::isff::WisardMote::unpack10thSec(), nidas::dynld::isff::WisardMote::unpackAccumSec(), nidas::dynld::isff::WisardMote::unpackCNR2(), nidas::dynld::isff::WisardMote::unpackGsoil(), nidas::dynld::isff::WisardMote::unpackInt16(), nidas::dynld::isff::WisardMote::unpackInt32(), nidas::dynld::isff::WisardMote::unpackNR01(), nidas::dynld::isff::WisardMote::unpackPicTime(), nidas::dynld::isff::WisardMote::unpackPicTimeFields(), nidas::dynld::isff::WisardMote::unpackPower(), nidas::dynld::isff::WisardMote::unpackQsoil(), nidas::dynld::isff::WisardMote::unpackRlw(), nidas::dynld::isff::WisardMote::unpackRlwKZ(), nidas::dynld::isff::WisardMote::unpackRnet(), nidas::dynld::isff::WisardMote::unpackRsw(), nidas::dynld::isff::WisardMote::unpackRsw2(), nidas::dynld::isff::WisardMote::unpackStatus(), nidas::dynld::isff::WisardMote::unpackTP01(), nidas::dynld::isff::WisardMote::unpackTRH(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::WisardMote::unpackUint16(), nidas::dynld::isff::WisardMote::unpackUint32(), nidas::dynld::isff::WisardMote::unpackXbee(), and ARLIngest::writeLine().
getDataValue()
template<class DataT > double nidas::core::SampleT< DataT >::getDataValue (unsigned int i) const inline virtual
Implementation of virtual method.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data.
getDSMId()
unsigned int nidas::core::Sample::getDSMId () const inline inherited
Get the DSM (data system) id portion of the sample header.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getDSMId().
Referenced by NidsMerge::receiveAllowedDsm(), and NidsMerge::run().
getHeaderLength()
unsigned int nidas::core::Sample::getHeaderLength () const inline inherited
Number of bytes in header.
References nidas::core::SampleHeader::getSizeOf().
Referenced by nidas::dynld::BlockStats::addGoodSample(), nidas::core::SampleBuffer::run(), nidas::core::SampleSorter::run(), and nidas::dynld::SampleOutputStream::write().
getHeaderPtr()
const void* nidas::core::Sample::getHeaderPtr () const inline inherited
Get a pointer to the header portion of the sample.
References nidas::core::Sample::_header.
Referenced by nidas::core::operator<<(), and nidas::dynld::SampleOutputStream::write().
getId()
dsm_sample_id_t nidas::core::Sample::getId () const inline inherited
Get the id portion of the sample header.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getId().
Referenced by nidas::core::SampleClock::addSampleDate(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::dynld::raf::SyncRecordReader::init(), nidas::core::SampleMatcher::match(), nidas::core::SampleHeaderComparator::operator()(), nidas::core::FullSampleComparator::operator()(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::VCSEL_Serial::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::WxtSensor::process(), nidas::dynld::raf::SyncRecordReader::read(), nidas::dynld::raf::SyncRecordSource::receive(), SampleCounter::receive(), nidas::dynld::AsciiOutput::receive(), MergeVerifier::reportBackward(), MergeVerifier::reportDuplicate(), MergeVerifier::reportMissing(), nidas::core::MessageStreamScanner::requestBiggerSample(), DataStats::restartStats(), ExtractFast2D::run(), ExtractDMT::run(), SensorExtract::run(), and nidas::core::SampleSorter::run().
getMaxDataLength()
template<class DataT > static unsigned int nidas::core::SampleT< DataT >::getMaxDataLength () inline static
Maximum number of elements in data.
References nidas::core::SampleHeader::getMaxDataLength().
Referenced by nidas::core::SampleT< DataT >::allocateData(), and nidas::core::SampleT< DataT >::reallocateData().
getRawId()
dsm_sample_id_t nidas::core::Sample::getRawId () const inline inherited
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getRawId().
Referenced by nidas::dynld::SampleOutputStream::write().
getSpSId()
unsigned int nidas::core::Sample::getSpSId () const inline inherited
Get the short id portion of the sample header.
This is the portion of the id without the DSM id.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getSpSId().
Referenced by NidsMerge::run().
getTimeTag()
dsm_time_t nidas::core::Sample::getTimeTag () const inline inherited
Time-tag in non-leap microseconds since Jan 1, 1970 00:00 GMT.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::getTimeTag().
Referenced by SampleToDatabase::accumulate(), SampleCounter::accumulateData(), SampleCounter::accumulateSample(), nidas::dynld::BlockStats::addGoodSample(), nidas::core::SampleClock::addSampleDate(), nidas::core::CharacterSensor::adjustTimeTag(), nidas::core::DSMSensor::applyConversions(), nidas::dynld::raf::A2D_Serial::checkCkSum(), nidas::dynld::raf::SyncRecordSource::checkTime(), nidas::dynld::raf::SyncRecordSource::computeSlotIndex(), nidas::dynld::isff::NCAR_TRH::convertVariable(), nidas::dynld::BlockStats::endBadBlock(), nidas::dynld::raf::SyncServer::handleSample(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::core::SampleMatcher::match(), nidas::dynld::SampleInputStream::nextSample(), nidas::dynld::raf::SyncServer::openStream(), nidas::core::SampleTimetagComparator::operator()(), nidas::core::SampleHeaderComparator::operator()(), nidas::core::FullSampleComparator::operator()(), nidas::dynld::IR104_Relays::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::dynld::DSC_PulseCounter::process(), nidas::dynld::raf::A2DBoardTempSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::PHIPS_UDP::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::PSI9116_Sensor::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::UDPArincSensor::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::VCSEL_Serial::process(), nidas::dynld::raf::Watlow::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::WxtSensor::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::raf::TwoD64_USB::processSOR(), nidas::dynld::raf::SyncRecordReader::read(), nidas::dynld::isff::GOESOutput::receive(), nidas::dynld::raf::SyncRecordSource::receive(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), MergeVerifier::reportBackward(), MergeVerifier::reportDuplicate(), MergeVerifier::reportMissing(), nidas::core::MessageStreamScanner::requestBiggerSample(), DataStats::restartStats(), DmdA2dCk::run(), MergeVerifier::run(), NidsMerge::run(), SensorExtract::run(), nidas::core::SampleSorter::run(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::raf::SyncRecordReader::scanHeader(), nidas::dynld::raf::SyncRecordSource::sendSyncHeader(), nidas::dynld::raf::SyncRecordSource::sendSyncRecord(), nidas::dynld::raf::Extract2D::setTimeStamp(), nidas::dynld::isff::WisardMote::unpack10thSec(), nidas::dynld::isff::WisardMote::unpackAccumSec(), nidas::dynld::isff::WisardMote::unpackTsoil(), and nidas::dynld::SampleOutputStream::write().
getType()
template<class DataT > sampleType nidas::core::SampleT< DataT >::getType () const inline virtual
Get the type of the sample.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data, and nidas::core::getSampleType().
getVoidDataPtr()
template<class DataT > void* nidas::core::SampleT< DataT >::getVoidDataPtr () inline virtual
Get a void* pointer to the data portion of the sample.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data.
Referenced by nidas::dynld::isff::Wind3D::process(), and nidas::core::MessageStreamScanner::requestBiggerSample().
holdReference()
void nidas::core::Sample::holdReference () const inline inherited
Increment the reference count for this sample.
Sample supports a form of reference counting. See freeReference. We have to use a hack-like cast of the this pointer to a const so that holdReference can be used on a const Sample. The SamplePool class supports Sample reference counting.
References nidas::core::Sample::_refCount, nidas::core::Sample::_refLock, nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
operator=()
template<class DataT > SampleT& nidas::core::SampleT< DataT >::operator= (const SampleT< DataT > &) protected
No assignment.
reallocateData()
template<class DataT > void nidas::core::SampleT< DataT >::reallocateData (unsigned int val) inline virtual
Re-allocate data, space, keeping contents.
Parameters
val number of DataT's to allocated.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_allocLen, nidas::core::SampleT< DataT >::_data, and nidas::core::SampleT< DataT >::getMaxDataLength().
setDataLength()
template<class DataT > void nidas::core::SampleT< DataT >::setDataLength (unsigned int val) inline virtual
Set the number of elements of type DataT in data.
Parameters
val number of elements.
Implements nidas::core::Sample.
References nidas::core::Sample::_header, nidas::core::SampleT< DataT >::getAllocLength(), and nidas::core::SampleHeader::setDataByteLength().
Referenced by nidas::core::SampleT< DataT >::allocateData(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::TSI_CPC3772::process(), and nidas::core::DSMSensor::trimUnparsed().
setDataValue() [1/2]
template<class DataT > void nidas::core::SampleT< DataT >::setDataValue (unsigned int i, double val) inline virtual
Implementation of virtual method.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data.
setDataValue() [2/2]
template<class DataT > void nidas::core::SampleT< DataT >::setDataValue (unsigned int i, float val) inline virtual
Implementation of virtual method.
Implements nidas::core::Sample.
References nidas::core::SampleT< DataT >::_data.
setDSMId()
void nidas::core::Sample::setDSMId (unsigned int val) inline inherited
Set the DSM (data system) id portion of the sample header.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::setDSMId().
Referenced by ARLIngest::writeLine().
setId()
void nidas::core::Sample::setId (dsm_sample_id_t val) inline inherited
Set the id portion of the sample header.
The id typically identifies the data system and sensor of origin of the sample.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::setId().
Referenced by nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::ParoSci_202BG_P::createPressureSample(), nidas::dynld::raf::SidsNetSensor::createSamples(), nidas::dynld::raf::TwoD_USB::createSamples(), nidas::core::NearestResampler::flush(), nidas::core::SampleAverager::flush(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::dynld::IR104_Relays::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::dynld::DSC_Event::process(), nidas::dynld::DSC_FreqCounter::process(), nidas::dynld::DSC_PulseCounter::process(), nidas::dynld::ParoSci_202BG_T::process(), nidas::dynld::raf::A2DBoardTempSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::IRIGSensor::process(), nidas::dynld::GPS_NMEA_Serial::process(), nidas::dynld::GPS_Novatel_Serial::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::BCPD_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::PHIPS_UDP::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::PSI9116_Sensor::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::TwoD_House::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::Watlow::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::WxtSensor::process(), nidas::dynld::raf::DSMArincSensor::processAlta(), nidas::dynld::raf::TwoD64_USB::processSOR(), nidas::dynld::raf::TwoD64_USB_v3::processSOR(), nidas::dynld::raf::DSMAnalogSensor::processTemperature(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::core::MessageStreamScanner::requestBiggerSample(), TestSource::run(), SensorExtract::run(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::SampleInputStream::sampleFromHeader(), nidas::core::CharacterSensor::searchSampleScanners(), and nidas::dynld::raf::SyncRecordSource::sendSyncHeader().
setRawId()
void nidas::core::Sample::setRawId (dsm_sample_id_t val) inline inherited
Set the full, raw id portion of the sample header.
This method is not typically used except when doing raw IO on a sample. The raw id contains an enumeration of the sample type, along with the fields returned by getId().
References nidas::core::Sample::_header, and nidas::core::SampleHeader::setRawId().
setSpSId()
void nidas::core::Sample::setSpSId (unsigned int val) inline inherited
Set the short id portion of the sample header, containing the sensor + sample ids.
This is the portion of the id without the DSM id.
References nidas::core::Sample::_header, and nidas::core::SampleHeader::setSpSId().
Referenced by ARLIngest::writeLine().
setTimeTag()
void nidas::core::Sample::setTimeTag (dsm_time_t val) inline inherited
References nidas::core::Sample::_header, and nidas::core::SampleHeader::setTimeTag().
Referenced by nidas::core::SampleClock::addSampleDate(), nidas::core::CharacterSensor::adjustTimeTag(), nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::ParoSci_202BG_P::createPressureSample(), nidas::dynld::raf::SidsNetSensor::createSamples(), nidas::dynld::raf::TwoD_USB::createSamples(), nidas::core::NearestResampler::flush(), nidas::core::SampleAverager::flush(), NidsMerge::flushSorter(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::dynld::IR104_Relays::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::dynld::DSC_Event::process(), nidas::dynld::DSC_FreqCounter::process(), nidas::dynld::DSC_PulseCounter::process(), nidas::dynld::ParoSci_202BG_T::process(), nidas::dynld::raf::A2DBoardTempSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::IRIGSensor::process(), nidas::dynld::GPS_NMEA_Serial::process(), nidas::dynld::GPS_Novatel_Serial::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::raf::A2D_Serial::process(), nidas::dynld::raf::BCPD_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::PHIPS_UDP::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::PPT_Serial::process(), nidas::dynld::raf::PSI9116_Sensor::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::TwoD_House::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::VCSEL_Serial::process(), nidas::dynld::raf::Watlow::process(), nidas::dynld::TSI_CPC3772::process(), nidas::dynld::WxtSensor::process(), nidas::dynld::raf::DSMArincSensor::processAlta(), nidas::dynld::raf::TwoD64_USB::processSOR(), nidas::dynld::raf::TwoD64_USB_v3::processSOR(), nidas::dynld::raf::DSMAnalogSensor::processTemperature(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::core::MessageStreamScanner::requestBiggerSample(), MergeVerifier::run(), TestSource::run(), nidas::core::SampleSorter::run(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::SampleInputStream::sampleFromHeader(), nidas::core::CharacterSensor::searchSampleScanners(), nidas::dynld::raf::SyncRecordSource::sendSyncHeader(), and ARLIngest::writeLine().
sizeofDataType()
template<class DataT > static int nidas::core::SampleT< DataT >::sizeofDataType () inline static
Member Data Documentation
_allocLen
template<class DataT > unsigned int nidas::core::SampleT< DataT >::_allocLen protected
Number of bytes allocated in data.
Referenced by nidas::core::SampleT< DataT >::allocateData(), nidas::core::SampleT< DataT >::getAllocByteLength(), nidas::core::SampleT< DataT >::getAllocLength(), and nidas::core::SampleT< DataT >::reallocateData().
_data
template<class DataT > DataT* nidas::core::SampleT< DataT >::_data protected
Pointer to the actual data.
Referenced by nidas::core::SampleT< DataT >::allocateData(), nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getConstVoidDataPtr(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleT< DataT >::getDataValue(), nidas::core::SampleT< DataT >::getType(), nidas::core::SampleT< DataT >::getVoidDataPtr(), nidas::core::SampleT< DataT >::reallocateData(), nidas::core::SampleT< DataT >::setDataValue(), and nidas::core::SampleT< DataT >::~SampleT().
_header
SampleHeader nidas::core::Sample::_header protected inherited
Referenced by nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getDSMId(), nidas::core::Sample::getHeaderPtr(), nidas::core::Sample::getId(), nidas::core::Sample::getRawId(), nidas::core::Sample::getSpSId(), nidas::core::Sample::getTimeTag(), nidas::core::SampleT< DataT >::setDataLength(), nidas::core::Sample::setDSMId(), nidas::core::Sample::setId(), nidas::core::Sample::setRawId(), nidas::core::Sample::setSpSId(), and nidas::core::Sample::setTimeTag().
_nsamps
int Sample::_nsamps static protected inherited
Global count of the number of samples in use by a process.
Incremented in the constructor, decremented in the destructor. Useful for development debugging to track leaks.
Referenced by nidas::core::Sample::Sample(), and nidas::core::Sample::~Sample().
_refCount
int nidas::core::Sample::_refCount mutable protected inherited
The reference count.
Referenced by nidas::core::Sample::holdReference().
_refLock
nidas::util::Mutex nidas::core::Sample::_refLock mutable protected inherited
Referenced by nidas::core::Sample::holdReference().
The documentation for this class was generated from the following file:
nidas/core/Sample.h