nidas: nidas::dynld::isff::GroundStation Class Reference
nidas::dynld::isff::GroundStation Class Reference
GroundStation is a sub-class of a measurement Site.
#include <GroundStation.h>
Public Member Functions
GroundStation ()
virtual ~GroundStation ()
void setName (const std::string &val)
Set the name of the Site.
const std::string & getName () const
void setNumber (int val)
Identify the Site by number.
int getNumber () const
bool operator== (const Site &x) const
Equivalence operator for Site, checks name.
bool operator!= (const Site &x) const
Non-equivalence operator for Site.
bool operator< (const Site &x) const
Less than operator for Site, compares the names.
void setSuffix (const std::string &val)
Set the suffix for the Site.
const std::string & getSuffix () const
const Project * getProject () const
Provide pointer to Project.
Project * getProject ()
void setProject (Project *val)
Set the current project for this Site.
void addDSMConfig (DSMConfig *dsm)
A Site contains one or more DSMs.
void removeDSMConfig (DSMConfig *dsm)
const std::list< const DSMConfig * > & getDSMConfigs () const
const std::list< DSMConfig * > & getDSMConfigs ()
void addServer (DSMServer *srvr)
A Site has one or more DSMServers.
const std::list< DSMServer * > & getServers () const
DSMServer * findServer (const std::string &hostname) const
Look for a server on this aircraft that either has no name or whose name matches hostname.
const DSMConfig * findDSM (const nidas::util::Inet4Address &addr) const
Find a DSM whose name corresponds to a given IP address.
const DSMConfig * findDSM (unsigned int id) const
Find a DSM by id.
const DSMConfig * findDSM (const std::string &name) const
Find a DSM by name.
DSMSensor * findSensor (unsigned int id) const
Find a DSMSensor by the full id, both the DSM id and the sensor id.
void initSensors ()
Initialize all sensors for a Site.
void initSensors (DSMConfig *dsm)
Initialize all sensors for a given dsm.
virtual void addParameter (Parameter *val)
Add a parameter to this Site.
virtual const Parameter * getParameter (const std::string &name) const
virtual const std::list< const Parameter * > & getParameters () const
virtual bool getApplyVariableConversions () const
Do we want DSMSensor::process methods at this site to apply variable conversions? Currently on raf.Aircraft we don't want process methods to apply the conversions.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string.
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $SITE, and $AIRCRAFT.
const Dictionary & getDictionary () const
DSMServerIterator getDSMServerIterator () const
DSMServiceIterator getDSMServiceIterator () const
ProcessorIterator getProcessorIterator () const
DSMConfigIterator getDSMConfigIterator () const
SensorIterator getSensorIterator () const
SampleTagIterator getSampleTagIterator () const
VariableIterator getVariableIterator () const
void validate ()
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Attributes
bool _applyCals
Should NIDAS apply calibrations, or defer them to other processing.
Private Attributes
Project * _project
Pointer back to my project.
std::string _name
int _number
std::string _suffix
nidas::core::Site::MyDictionary _dictionary
std::list< const DSMConfig * > _dsms
std::list< DSMConfig * > _ncDsms
std::list< DSMServer * > _servers
std::map< std::string, Parameter * > _parameterMap
Mapping of Parameters, by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
GroundStation is a sub-class of a measurement Site.
A Site contains a collection of Parameters, so most any Parameter specific to an GroundStation can be supported.
Constructor & Destructor Documentation
GroundStation()
GroundStation::GroundStation ()
~GroundStation()
GroundStation::~GroundStation () virtual
Member Function Documentation
addDSMConfig()
void nidas::core::Site::addDSMConfig (DSMConfig * dsm) inline inherited
A Site contains one or more DSMs.
Site will own the pointer and will delete the DSMConfig in its destructor.
References nidas::core::Site::_dsms, and nidas::core::Site::_ncDsms.
Referenced by nidas::core::Site::fromDOMElement().
addParameter()
void Site::addParameter (Parameter * val) virtual inherited
Add a parameter to this Site.
Site will then own the pointer and will delete it in its destructor.
References nidas::core::Site::_constParameters, nidas::core::Site::_parameterMap, and nidas::core::Parameter::getName().
Referenced by nidas::core::Site::fromDOMElement().
addServer()
void nidas::core::Site::addServer (DSMServer * srvr) inline inherited
A Site has one or more DSMServers.
References nidas::core::Site::_servers.
Referenced by nidas::core::Site::fromDOMElement().
expandString()
std::string nidas::core::Site::expandString (const std::string & input) const inline inherited
Utility function to expand ${TOKEN} or $TOKEN fields in a string.
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue(). If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References nidas::core::Site::_dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::DSMConfig::fromDOMElement(), nidas::core::Site::fromDOMElement(), and PConfig::getHostNames().
findDSM() [1/3]
const DSMConfig * Site::findDSM (const nidas::util::Inet4Address & addr) const inherited
Find a DSM whose name corresponds to a given IP address.
References nidas::core::Site::_dsms, nidas::util::Inet4Address::getAllByName(), nidas::core::DSMConfig::getName(), and VLOG.
Referenced by nidas::core::Project::findDSM().
findDSM() [2/3]
const DSMConfig * Site::findDSM (const std::string & name) const inherited
Find a DSM by name.
References nidas::core::Site::_dsms, nidas::core::DSMConfig::getName(), and VLOG.
findDSM() [3/3]
const DSMConfig * Site::findDSM (unsigned int id) const inherited
Find a DSM by id.
References nidas::core::Site::_dsms, nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getName(), and VLOG.
findSensor()
DSMSensor * Site::findSensor (unsigned int id) const inherited
Find a DSMSensor by the full id, both the DSM id and the sensor id.
References GET_DSM_ID, GET_SPS_ID, nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getId(), nidas::core::SampleTag::getId(), nidas::core::Site::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMSensor::getSensorId(), nidas::core::Site::getSensorIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::SensorIterator::next(), nidas::core::SampleTagIterator::next(), and VLOG.
Referenced by nidas::core::Project::findSensor().
findServer()
DSMServer * Site::findServer (const std::string & hostname) const inherited
Look for a server on this aircraft that either has no name or whose name matches hostname.
If none found, remove any domain names and try again.
References nidas::core::Site::_servers, and nidas::core::DSMServer::getName().
fromDOMElement()
void Site::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::core::Site::_applyCals, nidas::core::Site::_dictionary, nidas::core::Site::addDSMConfig(), nidas::core::Site::addParameter(), nidas::core::Site::addServer(), nidas::core::Parameter::createParameter(), nidas::core::Site::expandString(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getName(), nidas::core::Site::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::Site::getProject(), nidas::core::XDOMAttr::getValue(), nidas::core::Site::setName(), nidas::core::Site::setNumber(), nidas::core::DSMServer::setProject(), nidas::core::DSMConfig::setSite(), nidas::core::DSMServer::setSite(), and nidas::core::Site::setSuffix().
Referenced by nidas::core::Project::fromDOMElement().
getApplyVariableConversions()
virtual bool nidas::core::Site::getApplyVariableConversions () const inline virtual inherited
Do we want DSMSensor::process methods at this site to apply variable conversions? Currently on raf.Aircraft we don't want process methods to apply the conversions.
References nidas::core::Site::_applyCals.
Referenced by nidas::core::Variable::convert().
getDictionary()
const Dictionary& nidas::core::Site::getDictionary () const inline inherited
References nidas::core::Site::_dictionary.
getDSMConfigIterator()
DSMConfigIterator Site::getDSMConfigIterator () const inherited
Referenced by nidas::dynld::UDPSampleOutput::connected(), PConfig::getHostNames(), PConfig::loadVariables(), main(), PConfig::showAll(), and nidas::core::Site::toDOMElement().
getDSMConfigs() [1/2]
const std::list<DSMConfig*>& nidas::core::Site::getDSMConfigs () inline inherited
References nidas::core::Site::_ncDsms.
getDSMConfigs() [2/2]
const std::list<const DSMConfig*>& nidas::core::Site::getDSMConfigs () const inline inherited
References nidas::core::Site::_dsms.
Referenced by nidas::core::Project::findDSMFromHostname(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::Site::initSensors(), PConfig::showCalFiles(), and nidas::core::Site::validate().
getDSMServerIterator()
DSMServerIterator Site::getDSMServerIterator () const inherited
getDSMServiceIterator()
DSMServiceIterator Site::getDSMServiceIterator () const inherited
getName()
const std::string& nidas::core::Site::getName () const inline inherited
References nidas::core::Site::_name.
Referenced by nidas::core::Project::addSite(), SampleCounter::collectMetadata(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::NearestResampler::ctorCommon(), nidas::core::Project::findDSM(), nidas::core::Site::findSensor(), nidas::core::Site::fromDOMElement(), nidas::core::Site::MyDictionary::getTokenValue(), PConfig::loadVariables(), main(), DataPrep::matchVariables(), SampleToDatabase::setSiteAndMeasurement(), PConfig::showAll(), PConfig::showCalFiles(), and nidas::core::Site::toDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNumber()
int nidas::core::Site::getNumber () const inline inherited
References nidas::core::Site::_number.
Referenced by nidas::core::Project::addSite(), nidas::dynld::isff::GOESProject::GOESProject(), PConfig::showAll(), and nidas::core::Site::toDOMElement().
getParameter()
const Parameter * Site::getParameter (const std::string & name) const virtual inherited
References nidas::core::Site::_parameterMap.
getParameters()
const list< const Parameter * > & Site::getParameters () const virtual inherited
References nidas::core::Site::_constParameters.
getProcessorIterator()
ProcessorIterator Site::getProcessorIterator () const inherited
Referenced by nidas::dynld::isff::GOESProject::GOESProject().
getProject() [1/2]
Project* nidas::core::Site::getProject () inline inherited
References nidas::core::Site::_project.
getProject() [2/2]
const Project* nidas::core::Site::getProject () const inline inherited
Provide pointer to Project.
References nidas::core::Site::_project.
Referenced by nidas::core::Site::fromDOMElement(), nidas::core::DSMConfig::getProject(), and nidas::core::Site::MyDictionary::getTokenValue().
getSampleTagIterator()
SampleTagIterator Site::getSampleTagIterator () const inherited
getSensorIterator()
SensorIterator Site::getSensorIterator () const inherited
Referenced by nidas::core::Site::findSensor(), and nidas::core::DSMServer::getSensorIterator().
getServers()
const std::list<DSMServer*>& nidas::core::Site::getServers () const inline inherited
References nidas::core::Site::_servers.
Referenced by nidas::core::DSMServerIterator::hasNext().
getSuffix()
const std::string& nidas::core::Site::getSuffix () const inline inherited
References nidas::core::Site::_suffix.
Referenced by nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::Variable::setSite(), and nidas::core::Variable::setStation().
getTokenValue()
bool nidas::core::Site::getTokenValue (const std::string & token, std::string & value) const inline inherited
Implement a lookup for tokens that I know about, like $SITE, and $AIRCRAFT.
For other tokens, call getProject()->getTokenValue(token,value);
References nidas::core::Site::_dictionary, and nidas::core::Site::MyDictionary::getTokenValue().
Referenced by nidas::core::DSMConfig::MyDictionary::getTokenValue().
getVariableIterator()
VariableIterator Site::getVariableIterator () const inherited
initSensors() [1/2]
void Site::initSensors () inherited
Initialize all sensors for a Site.
Exceptions
nidas::util::IOException
References nidas::core::Site::getDSMConfigs(), and nidas::core::DSMConfig::initSensors().
Referenced by nidas::core::Project::initSensors().
initSensors() [2/2]
void Site::initSensors (DSMConfig * dsm) inherited
Initialize all sensors for a given dsm.
Exceptions
nidas::util::IOException
References nidas::core::Site::getDSMConfigs(), and nidas::core::DSMConfig::initSensors().
operator!=()
bool nidas::core::Site::operator!= (const Site & x) const inline inherited
Non-equivalence operator for Site.
References nidas::core::Site::operator==().
operator<()
bool nidas::core::Site::operator< (const Site & x) const inline inherited
Less than operator for Site, compares the names.
References nidas::core::Site::_name.
operator==()
bool nidas::core::Site::operator== (const Site & x) const inline inherited
Equivalence operator for Site, checks name.
References nidas::core::Site::_name, nidas::core::Site::_number, and nidas::core::Site::_suffix.
Referenced by nidas::core::Site::operator!=().
removeDSMConfig()
void nidas::core::Site::removeDSMConfig (DSMConfig * dsm) inline inherited
References nidas::core::Site::_dsms, and nidas::core::Site::_ncDsms.
setName()
void nidas::core::Site::setName (const std::string & val) inline inherited
Set the name of the Site.
References nidas::core::Site::_name.
Referenced by nidas::core::Site::fromDOMElement().
setNumber()
void nidas::core::Site::setNumber (int val) inline inherited
Identify the Site by number.
The site number can be used for things like a NetCDF station dimension.
Parameters
Site number, 0 means no number is associated with the site.
References nidas::core::Site::_number.
Referenced by nidas::core::Site::fromDOMElement().
setProject()
void nidas::core::Site::setProject (Project * val) inline inherited
Set the current project for this Site.
References nidas::core::Site::_project.
Referenced by nidas::core::Project::fromDOMElement().
setSuffix()
void nidas::core::Site::setSuffix (const std::string & val) inline inherited
Set the suffix for the Site.
All variable names from this site will have the suffix.
References nidas::core::Site::_suffix.
Referenced by nidas::core::Site::fromDOMElement().
toDOMElement()
xercesc::DOMElement * Site::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::Site::getDSMConfigIterator(), nidas::core::Site::getName(), nidas::core::Site::getNumber(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::XDOMElement::setAttributeValue(), and nidas::core::DSMConfig::toDOMParent().
Referenced by nidas::core::Site::toDOMParent().
toDOMParent()
xercesc::DOMElement * Site::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), and nidas::core::Site::toDOMElement().
Referenced by nidas::core::Project::toDOMElement().
validate()
void Site::validate () inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::Site::getDSMConfigs(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getDuplicateIdOK(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getName(), nidas::core::Variable::getName(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::DSMSensor::getVariableIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::DSMConfig::validate().
Referenced by nidas::core::Project::fromDOMElement().
Member Data Documentation
_applyCals
bool nidas::core::Site::_applyCals protected inherited
Should NIDAS apply calibrations, or defer them to other processing.
Referenced by nidas::core::Site::fromDOMElement(), and nidas::core::Site::getApplyVariableConversions().
_constParameters
std::list<const Parameter*> nidas::core::Site::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::Site::addParameter(), and nidas::core::Site::getParameters().
_dictionary
nidas::core::Site::MyDictionary nidas::core::Site::_dictionary private inherited
Referenced by nidas::core::Site::expandString(), nidas::core::Site::fromDOMElement(), nidas::core::Site::getDictionary(), and nidas::core::Site::getTokenValue().
_dsms
std::list<const DSMConfig*> nidas::core::Site::_dsms private inherited
Referenced by nidas::core::Site::addDSMConfig(), nidas::core::Site::findDSM(), nidas::core::Site::getDSMConfigs(), and nidas::core::Site::removeDSMConfig().
_name
std::string nidas::core::Site::_name private inherited
Referenced by nidas::core::Site::getName(), nidas::core::Site::operator<(), nidas::core::Site::operator==(), and nidas::core::Site::setName().
_ncDsms
std::list<DSMConfig*> nidas::core::Site::_ncDsms private inherited
Referenced by nidas::core::Site::addDSMConfig(), nidas::core::Site::getDSMConfigs(), nidas::core::Site::removeDSMConfig(), and nidas::core::Site::~Site().
_number
int nidas::core::Site::_number private inherited
Referenced by nidas::core::Site::getNumber(), nidas::core::Site::operator==(), and nidas::core::Site::setNumber().
_parameterMap
std::map<std::string,Parameter*> nidas::core::Site::_parameterMap private inherited
Mapping of Parameters, by name.
Referenced by nidas::core::Site::addParameter(), nidas::core::Site::getParameter(), and nidas::core::Site::~Site().
_project
Project* nidas::core::Site::_project private inherited
Pointer back to my project.
Referenced by nidas::core::Site::getProject(), and nidas::core::Site::setProject().
_servers
std::list<DSMServer*> nidas::core::Site::_servers private inherited
Referenced by nidas::core::Site::addServer(), nidas::core::Site::findServer(), nidas::core::Site::getServers(), and nidas::core::Site::~Site().
_suffix
std::string nidas::core::Site::_suffix private inherited
Referenced by nidas::core::Site::getSuffix(), nidas::core::Site::operator==(), and nidas::core::Site::setSuffix().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/isff/GroundStation.h
nidas/dynld/isff/GroundStation.cc