nidas: nidas::util::InvalidParameterException Class Reference
nidas::util::InvalidParameterException Class Reference
#include <InvalidParameterException.h>
Public Member Functions
InvalidParameterException (const std::string &module, const std::string &name, const std::string &msg)
Create an InvalidParameterException, passing a name of the software or hardware module, the name of the parameter, and a message.
InvalidParameterException (const std::string &message)
Create an InvalidParameterException, passing a message.
Exception * clone () const
clone myself (a "virtual" constructor).
virtual int getErrno () const
virtual std::string toString () const throw ()
virtual const char * what () const throw ()
Static Public Member Functions
static std::string errnoToString (int err)
Return string description of an errno (from errno.h).
Protected Attributes
std::string _what
int _errno
Constructor & Destructor Documentation
InvalidParameterException() [1/2]
nidas::util::InvalidParameterException::InvalidParameterException (const std::string & module, const std::string & name, const std::string & msg) inline
Create an InvalidParameterException, passing a name of the software or hardware module, the name of the parameter, and a message.
Referenced by clone().
InvalidParameterException() [2/2]
nidas::util::InvalidParameterException::InvalidParameterException (const std::string & message) inline
Create an InvalidParameterException, passing a message.
Member Function Documentation
clone()
Exception* nidas::util::InvalidParameterException::clone () const inline virtual
clone myself (a "virtual" constructor).
Reimplemented from nidas::util::Exception.
References InvalidParameterException().
errnoToString()
string nidas::util::Exception::errnoToString (int err) static inherited
Return string description of an errno (from errno.h).
A convienence method that uses strerror_r(int) from <string.h>.
References err.
Referenced by nidas::util::Thread::cancel(), nidas::util::Inet4Address::getHostName(), nidas::util::Process::getMaxRSS(), nidas::util::Process::getVMemSize(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::NidasApp::parseUsername(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::core::DSMEngine::waitForSignal(), and nidas::core::DSMServerApp::waitForSignal().
getErrno()
virtual int nidas::util::Exception::getErrno () const inline virtual inherited
References nidas::util::Exception::_errno.
Referenced by nidas::util::FileSet::createFile(), nidas::core::IOStream::flush(), nidas::dynld::SampleOutputStream::flush(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::util::SocketImpl::joinGroup(), DataStats::readHeader(), DataStats::readSamples(), nidas::dynld::SampleOutputStream::receive(), MergeVerifier::run(), WriterThread::run(), ServerThread::run(), NidsMerge::run(), nidas::core::DerivedDataReader::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::Socket::ConnectionThread::run(), nidas::util::McSocketListener::run(), and nidas::core::IOStream::write().
toString()
virtual std::string nidas::util::Exception::toString () const throw () inline virtual inherited
References nidas::util::Exception::_what.
Referenced by nidas::dynld::isff::SE_GOESXmtr::detectModel(), nidas::util::SocketImpl::joinGroup(), main(), RemoteSerial::main(), and nidas::core::NidasApp::setupDaemon().
what()
virtual const char* nidas::util::Exception::what () const throw () inline virtual inherited
References nidas::util::Exception::_what.
Referenced by nidas::core::SensorHandler::add(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::dynld::isff::SE_GOESXmtr::cancelTransmit(), nidas::core::NidasApp::checkPidFile(), Garmin::checkPPS(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::util::McSocket< SocketT >::close(), nidas::core::DSMEngine::closeOutputs(), nidas::core::DatagramSocket::connect(), nidas::dynld::RawSampleService::connect(), nidas::dynld::UDPSampleOutput::connected(), nidas::util::FileSet::createFile(), nidas::core::DOMObjectFactory::createObject(), nidas::dynld::isff::WisardMote::createSampleTag(), nidas::core::VariableConverter::createVariableConverter(), nidas::core::DerivedDataReader::deleteInstance(), nidas::dynld::raf::AlicatSDI::derivedDataNotify(), nidas::dynld::raf::PIP_Serial::derivedDataNotify(), nidas::dynld::raf::TwoD_USB::derivedDataNotify(), nidas::dynld::raf::VCSEL2_Serial::derivedDataNotify(), nidas::dynld::raf::VCSEL_Serial::derivedDataNotify(), nidas::core::SampleOutputRequestThread::destroyInstance(), Garmin::disableAllMessages(), Garmin::disableMessage(), Garmin::disablePPS(), nidas::core::DSMEngine::disconnect(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::raf::CVIProcessor::disconnect(), nidas::dynld::raf::SyncRecordGenerator::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::dynld::StatisticsProcessor::disconnect(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::dynld::psql::PSQLSampleOutput::dropAllTables(), nidas::core::DSMEngine::DSMEngine(), Garmin::enableAllMessages(), Garmin::enableMessage(), Garmin::enablePPS(), nidas::dynld::raf::PSI9116_Sensor::executeXmlRpc(), nidas::core::Project::findDSM(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::dynld::SampleOutputStream::flush(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DatagramSocket::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::Socket::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::dynld::raf::DSMAnalogSensor::getA2DSetup(), nidas::core::DSMSensor::getLooper(), nidas::core::Socket::getRemoteInet4Address(), nidas::core::RemoteSerialConnection::handlePollEvents(), nidas::core::RemoteSerialListener::handlePollEvents(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SensorHandler::NotifyPipe::handlePollEvents(), nidas::core::CharacterSensor::init(), nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::SE_GOESXmtr::init(), nidas::dynld::psql::PSQLSampleOutput::init(), nidas::dynld::raf::SyncRecordReader::init(), nidas::core::DerivedDataReader::interrupt(), nidas::core::DSMService::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::XmlRpcThread::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::util::McSocketMulticaster< SocketTT >::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::util::McSocket< SocketT >::joinMulticaster(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::DSMEngine::killXmlRpcThread(), nidas::core::DSMServerApp::killXmlRpcThread(), nidas::util::McSocket< SocketT >::listen(), StatsProcess::listOutputSamples(), PConfig::loadRemoteXML(), nidas::core::NidasApp::lockMemory(), PacketReader::loop(), nidas::core::SerialSensor::Prompter::looperNotify(), nidas::dynld::isff::MOSMote::MOS_TimeSyncer::looperNotify(), SensorSimulator::looperNotify(), PConfig::main(), PSI::main(), SensorSimApp::main(), main(), DataDump::main(), DataStats::main(), DmdA2dCk::main(), StatsProcess::main(), nidas::core::DSMEngine::main(), nidas::core::DSMServerApp::main(), nidas::core::FsMount::mount(), nidas::core::SensorHandler::NotifyPipe::notify(), nidas::core::ServerSocketIODevice::open(), nidas::core::SocketIODevice::open(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::util::FileSet::openNextFile(), nidas::dynld::SampleInputStream::parseInputHeader(), nidas::core::NidasApp::parseInputs(), DataStats::parseRunstring(), DmdA2dCk::parseRunstring(), MergeVerifier::parseRunstring(), PacketReader::parseRunstring(), NidsMerge::parseRunstring(), ProjConfigIO::parseRunstring(), SensorExtract::parseRunstring(), SyncDumper::parseRunstring(), TeeTTy::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), nidas::core::CalFile::parseTime(), nidas::core::NidasApp::parseTime(), nidas::dynld::isff::SE_GOESXmtr::printStatus(), nidas::core::SerialSensor::printStatus(), nidas::dynld::DSC_A2DSensor::printStatus(), nidas::dynld::DSC_Event::printStatus(), nidas::dynld::DSC_FreqCounter::printStatus(), nidas::dynld::DSC_PulseCounter::printStatus(), nidas::dynld::raf::DSMAnalogSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::IRIGSensor::printStatus(), nidas::dynld::raf::LamsSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::dynld::raf::SyncServer::read(), nidas::core::SampleInputHeader::read(), nidas::dynld::raf::A2D_Serial::readCalFile(), nidas::dynld::raf::DSMAnalogSensor::readCalFile(), nidas::core::VariableConverter::readCalFile(), nidas::dynld::ParoSci_202BG_Calibration::readCalFile(), DataStats::readHeader(), Garmin::readInit(), nidas::dynld::isff::Wind3D::readOffsetsAnglesCalFile(), nidas::dynld::isff::PacketInputStream::readSamples(), DataStats::readSamples(), nidas::dynld::UDPSampleOutput::receive(), nidas::dynld::psql::PSQLSampleOutput::receive(), nidas::dynld::raf::CVIProcessor::receive(), nidas::dynld::SampleOutputStream::receive(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::util::SocketImpl::receive(), nidas::core::SensorHandler::remove(), nidas::util::McSocket< SocketT >::request(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), nidas::core::requestXMLConfig(), PConfig::resolveCalFile(), FileSim::rewind(), ARLIngest::run(), DataDump::run(), DataStats::run(), DmdA2dCk::run(), Garmin::run(), GPS_SetClock::run(), DatasetsApp::run(), PacketDecode::run(), DataPrep::run(), MergeVerifier::run(), HeaderUtil::run(), WriterThread::run(), ServerThread::run(), NidsMerge::run(), ProjConfigIO::run(), ExtractFast2D::run(), ExtractDMT::run(), RemoteSerial::run(), SensorExtract::run(), StatsProcess::run(), SyncDumper::run(), TeeI2C::run(), TeeTTy::run(), ublox::run(), nidas::core::DerivedDataReader::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::SensorHandler::run(), nidas::core::SensorOpener::run(), nidas::core::Socket::ConnectionThread::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::raf::SyncServer::run(), nidas::dynld::RawSampleService::Worker::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), nidas::util::ThreadJoiner::run(), nidas::dynld::raf::SyncRecordReader::scanHeader(), Garmin::scanMessages(), nidas::dynld::RawSampleService::schedule(), nidas::dynld::raf::PSI9116_Sensor::sendCommand(), Garmin::sendInit(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::PIP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), Garmin::setBaudRateOption(), TeeI2C::setFIFOPriority(), TeeTTy::setFIFOPriority(), nidas::core::NidasApp::setupProcess(), nidas::dynld::raf::PSI9116_Sensor::stopStreams(), nidas::dynld::isff::CSAT3_Sonic::terminalMode(), nidas::util::Thread::test(), nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120(), nidas::dynld::raf::DSMAnalogSensor::testVoltage(), nidas::dynld::isff::SE_GOESXmtr::transmitData(), ubx_config(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::PIP_Serial::validate(), nidas::core::MultipleUDPSockets::write(), nidas::util::Cond::~Cond(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::DatagramSocket::~DatagramSocket(), nidas::util::Mutex::~Mutex(), nidas::core::SensorHandler::NotifyPipe::~NotifyPipe(), PacketReader::~PacketReader(), nidas::core::RemoteSerialConnection::~RemoteSerialConnection(), nidas::core::RemoteSerialListener::~RemoteSerialListener(), nidas::util::RWLock::~RWLock(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), nidas::core::Socket::~Socket(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator(), and nidas::util::Thread::~Thread().
Member Data Documentation
_errno
int nidas::util::Exception::_errno protected inherited
Referenced by nidas::util::Exception::getErrno(), and nidas::util::Exception::operator=().
_what
std::string nidas::util::Exception::_what protected inherited
Referenced by nidas::util::Exception::operator=(), nidas::core::SampleLengthException::SampleLengthException(), nidas::util::Exception::toString(), nidas::util::Exception::what(), and nidas::core::XMLException::XMLException().
The documentation for this class was generated from the following file:
nidas/util/InvalidParameterException.h