nidas: nidas/apps/raf/cvi_lv_test_out.cc File Reference
cvi_lv_test_out.cc File Reference
#include <nidas/util/Socket.h>
#include <iostream>
#include <fstream>
#include <sstream>
Functions
int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::Socket::close(), nidas::util::Socket::connect(), nidas::util::Socket::getRemoteSocketAddress(), port, nidas::util::Socket::send(), nidas::util::SocketAddress::toString(), usage(), and nidas::util::Exception::what().
usage()
int usage (const char * argv0)
Referenced by main().