nidas: nidas::util::RWLockAttributes Class Reference
nidas::util::RWLockAttributes Class Reference
A C++ wrapper for a POSIX rwlock attributes.
#include <ThreadSupport.h>
Public Member Functions
RWLockAttributes ()
RWLockAttributes (const RWLockAttributes &)
Copy constructor.
~RWLockAttributes ()
void setPShared (int val)
Set the mutex pshared attribute, one of PTHREAD_PROCESS_PRIVATE or PTHREAD_PROCESS_SHARED.
int getPShared () const
pthread_rwlockattr_t * ptr ()
Private Attributes
pthread_rwlockattr_t _attrs
Detailed Description
A C++ wrapper for a POSIX rwlock attributes.
The only supported customization is to be able to share a RWLock between processes.
Constructor & Destructor Documentation
RWLockAttributes() [1/2]
RWLockAttributes::RWLockAttributes ()
References _attrs.
RWLockAttributes() [2/2]
RWLockAttributes::RWLockAttributes (const RWLockAttributes & x)
Copy constructor.
References _attrs, getPShared(), and setPShared().
~RWLockAttributes()
RWLockAttributes::~RWLockAttributes ()
References _attrs.
Member Function Documentation
getPShared()
int RWLockAttributes::getPShared () const
References _attrs.
Referenced by RWLockAttributes().
ptr()
pthread_rwlockattr_t* nidas::util::RWLockAttributes::ptr () inline
References _attrs.
Referenced by nidas::util::RWLock::RWLock().
setPShared()
void RWLockAttributes::setPShared (int val)
Set the mutex pshared attribute, one of PTHREAD_PROCESS_PRIVATE or PTHREAD_PROCESS_SHARED.
See pthread_rwlockattr_setpshared.
Exceptions
Exception
References _attrs.
Referenced by RWLockAttributes().
Member Data Documentation
_attrs
pthread_rwlockattr_t nidas::util::RWLockAttributes::_attrs private
Referenced by getPShared(), ptr(), RWLockAttributes(), setPShared(), and ~RWLockAttributes().
The documentation for this class was generated from the following files:
nidas/util/ThreadSupport.h
nidas/util/ThreadSupport.cc