nidas: SyncDumper Class Reference
SyncDumper Class Reference
Public Member Functions
SyncDumper ()
int parseRunstring (int argc, char **argv)
int run ()
void printHeader ()
Static Public Member Functions
static int usage (const char *argv0)
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
Static Public Attributes
static bool interrupted = false
Private Member Functions
SyncDumper (const SyncDumper &)
SyncDumper & operator= (const SyncDumper &)
Private Attributes
string _dataFileName
n_u::auto_ptr< n_u::SocketAddress > _sockAddr
vector< string > _varnames
vector< const SyncRecordVariable * > _vars
string _dumpHeader
string _dumpJSON
Static Private Attributes
static const int DEFAULT_PORT = 30001
Constructor & Destructor Documentation
SyncDumper() [1/2]
SyncDumper::SyncDumper ()
SyncDumper() [2/2]
SyncDumper::SyncDumper (const SyncDumper &) private
Member Function Documentation
operator=()
SyncDumper& SyncDumper::operator= (const SyncDumper &) private
parseRunstring()
int SyncDumper::parseRunstring (int argc, char ** argv)
References _dataFileName, _dumpHeader, _dumpJSON, _sockAddr, _varnames, DEFAULT_PORT, nidas::util::Inet4Address::getByName(), port, usage(), and nidas::util::Exception::what().
Referenced by main().
printHeader()
void SyncDumper::printHeader ()
run()
int SyncDumper::run ()
References _dataFileName, _dumpHeader, _dumpJSON, _sockAddr, _varnames, _vars, nidas::core::FileSet::getFileSet(), nidas::dynld::raf::SyncRecordReader::getFlightName(), nidas::dynld::raf::SyncRecordVariable::getLagOffset(), nidas::core::Variable::getLength(), nidas::core::Variable::getLongName(), nidas::core::Variable::getName(), nidas::dynld::raf::SyncRecordReader::getNumValues(), nidas::dynld::raf::SyncRecordReader::getProjectName(), nidas::core::Variable::getSampleRate(), nidas::dynld::raf::SyncRecordReader::getSoftwareVersion(), nidas::dynld::raf::SyncRecordVariable::getSyncRecOffset(), nidas::dynld::raf::SyncRecordReader::getTailNumber(), nidas::core::Variable::getUnits(), nidas::dynld::raf::SyncRecordReader::getVariables(), interrupted, len, nidas::dynld::raf::SyncRecordReader::read(), nidas::dynld::raf::SyncRecordReader::textHeader(), time_format(), USECS_PER_SEC, and nidas::util::Exception::what().
Referenced by main().
setupSignals()
void SyncDumper::setupSignals () static
References sigAction().
Referenced by main().
sigAction()
void SyncDumper::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
Referenced by setupSignals().
usage()
int SyncDumper::usage (const char * argv0) static
References DEFAULT_PORT.
Referenced by parseRunstring().
Member Data Documentation
_dataFileName
string SyncDumper::_dataFileName private
Referenced by parseRunstring(), and run().
_dumpHeader
string SyncDumper::_dumpHeader private
Referenced by parseRunstring(), and run().
_dumpJSON
string SyncDumper::_dumpJSON private
Referenced by parseRunstring(), and run().
_sockAddr
n_u::auto_ptr<n_u::SocketAddress> SyncDumper::_sockAddr private
Referenced by parseRunstring(), and run().
_varnames
vector<string> SyncDumper::_varnames private
Referenced by parseRunstring(), and run().
_vars
vector<const SyncRecordVariable*> SyncDumper::_vars private
Referenced by run().
DEFAULT_PORT
const int SyncDumper::DEFAULT_PORT = 30001 static private
Referenced by parseRunstring(), and usage().
interrupted
bool SyncDumper::interrupted = false static
Referenced by run(), and sigAction().
The documentation for this class was generated from the following file:
nidas/apps/sync_dump.cc