nidas: nidas::dynld::AsciiOutput Class Reference
nidas::dynld::AsciiOutput Class Reference
#include <AsciiOutput.h>
Public Types
enum format {
DEFAULT , ASCII , HEX , SIGNED_SHORT ,
UNSIGNED_SHORT , FLOAT , IRIG
}
typedef enum nidas::dynld::AsciiOutput::format format_t
Public Member Functions
AsciiOutput ()
AsciiOutput (IOChannel *iochannel, SampleConnectionRequester *rqstr=0)
virtual ~AsciiOutput ()
void flush () throw ()
Implementation of SampleClient::flush().
void requestConnection (SampleConnectionRequester *requester) throw ()
Request a connection, but don't wait for it.
void connect (nidas::core::SampleSource *)
void setFormat (format_t val)
Set the format for character samples.
bool receive (const Sample *samp)
virtual void setIOChannel (IOChannel *val)
Set the IOChannel for this SampleOutput.
SampleOutput * getOriginal () const
Get pointer to SampleOutput that was cloned.
void setName (const std::string &val)
const std::string & getName () const
bool isRaw () const
void addRequestedSampleTag (SampleTag *tag)
std::list< const SampleTag * > getRequestedSampleTags () const
void addSourceSampleTag (const SampleTag *tag)
void addSourceSampleTags (const std::list< const SampleTag * > &tags)
std::list< const SampleTag * > getSourceSampleTags () const
SampleOutput * connected (IOChannel *ochan)
Implementation of IOChannelRequester::connected().
int getReconnectDelaySecs () const
Base class implementation.
void setReconnectDelaySecs (int val)
int getFd () const
void close ()
dsm_time_t getNextFileTime () const
void createNextFile (dsm_time_t)
size_t write (const void *buf, size_t len)
Raw write method, typically used to write the initial header.
void fromDOMElement (const xercesc::DOMElement *node)
IOChannel * getIOChannel () const
void setHeaderSource (HeaderSource *val)
void setDSMConfig (const DSMConfig *val)
const DSMConfig * getDSMConfig () const
size_t getNumDiscardedSamples () const
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setLatency (float val)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
float getLatency () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
AsciiOutput * clone (IOChannel *iochannel)
AsciiOutput (AsciiOutput &, IOChannel *)
Copy constructor, with a new IOChannel.
void printHeader ()
size_t incrementDiscardedSamples ()
SampleConnectionRequester * getSampleConnectionRequester ()
void disconnect ()
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
Protected Attributes
std::string _name
Private Member Functions
AsciiOutput (const AsciiOutput &)
Copy constructor.
Private Attributes
std::ostringstream _ostr
format_t _format
std::map< dsm_sample_id_t, dsm_time_t > _prevTT
Previous time tags by sample id.
bool _headerOut
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
std::list< const SampleTag * > _constRequestedTags
IOChannel * _iochan
SampleConnectionRequester * _connectionRequester
dsm_time_t _nextFileTime
HeaderSource * _headerSource
const DSMConfig * _dsm
size_t _nsamplesDiscarded
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
std::list< const SampleTag * > _sourceTags
SampleOutput * _original
Pointer to the SampleOutput that I was cloned from.
float _latency
int _reconnectDelaySecs
Static Private Attributes
static XMLCh * namespaceURI = 0
Member Typedef Documentation
format_t
typedef enum nidas::dynld::AsciiOutput::format nidas::dynld::AsciiOutput::format_t
Member Enumeration Documentation
format
enum nidas::dynld::AsciiOutput::format
Enumerator
DEFAULT
ASCII
HEX
SIGNED_SHORT
UNSIGNED_SHORT
FLOAT
IRIG
Constructor & Destructor Documentation
AsciiOutput() [1/4]
AsciiOutput::AsciiOutput ()
Referenced by clone().
AsciiOutput() [2/4]
AsciiOutput::AsciiOutput (IOChannel * iochannel, SampleConnectionRequester * rqstr = 0)
References nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
~AsciiOutput()
virtual nidas::dynld::AsciiOutput::~AsciiOutput () inline virtual
AsciiOutput() [3/4]
AsciiOutput::AsciiOutput (AsciiOutput & x, IOChannel * ioc) protected
Copy constructor, with a new IOChannel.
References nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
AsciiOutput() [4/4]
nidas::dynld::AsciiOutput::AsciiOutput (const AsciiOutput &) private
Copy constructor.
Member Function Documentation
addParameter()
void SampleOutputBase::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::SampleOutputBase::_constParameters, nidas::core::SampleOutputBase::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::SampleOutputBase::fromDOMElement().
addRequestedSampleTag()
void SampleOutputBase::addRequestedSampleTag (SampleTag * tag) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::raf::CVIOutput, and nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, nidas::core::SampleOutputBase::_requestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::raf::CVIOutput::addRequestedSampleTag(), and nidas::core::SampleOutputBase::SampleOutputBase().
addSourceSampleTag()
void SampleOutputBase::addSourceSampleTag (const SampleTag * tag) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::core::SampleOutputBase::addSourceSampleTags(), and nidas::core::SampleOutputBase::SampleOutputBase().
addSourceSampleTags()
void SampleOutputBase::addSourceSampleTags (const std::list< const SampleTag * > & tags) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::addSourceSampleTag().
clone()
AsciiOutput * AsciiOutput::clone (IOChannel * iochannel) protected virtual
Implements nidas::core::SampleOutput.
References AsciiOutput().
close()
void SampleOutputBase::close () virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::UDPSampleOutput, nidas::dynld::SampleOutputStream, nidas::dynld::psql::PSQLSampleOutput, and nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::IOChannel::close(), DLOG, and nidas::core::SampleOutputBase::getName().
Referenced by nidas::dynld::isff::GOESOutput::close(), nidas::dynld::SampleOutputStream::close(), nidas::dynld::UDPSampleOutput::close(), and nidas::core::SampleOutputBase::disconnect().
connect()
void AsciiOutput::connect (nidas::core::SampleSource * source)
Exceptions
nidas::util::IOException
References nidas::core::SampleSource::addSampleClient(), nidas::core::SampleOutputBase::getIOChannel(), and nidas::core::SampleOutputBase::setIOChannel().
connected()
SampleOutput * SampleOutputBase::connected (IOChannel * ochan) virtual inherited
Implementation of IOChannelRequester::connected().
How an IOChannel calls back to a SampleConnectionRequester that it is connected. The ConnectionRequester can then return a clone of itself if the IOChannel is a new instance.
Implements nidas::core::IOChannelRequester.
Reimplemented in nidas::dynld::isff::GOESOutput, nidas::dynld::UDPSampleOutput, nidas::dynld::psql::PSQLSampleOutput, and nidas::dynld::SampleOutputStream.
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::SampleOutput::clone(), nidas::core::IOChannel::close(), nidas::core::SampleConnectionRequester::connect(), nidas::core::IOChannel::getName(), nidas::core::SampleOutputBase::setIOChannel(), and nidas::core::SampleOutputBase::setName().
Referenced by nidas::dynld::SampleOutputStream::connected(), nidas::dynld::UDPSampleOutput::connected(), and nidas::dynld::isff::GOESOutput::connected().
createNextFile()
void SampleOutputBase::createNextFile (dsm_time_t tt) inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_headerSource, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::IOChannel::createFile(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::HeaderSource::sendDefaultHeader(), and nidas::core::HeaderSource::sendHeader().
Referenced by receive(), and nidas::dynld::raf::CVIOutput::receive().
disconnect()
void SampleOutputBase::disconnect () protected inherited
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
This is typically called in the receive() method of a SampleOutput if it gets an IOException when writing data. A common implementation of a connection requester is to delete this SampleOutput after the removing it from the sample stream. So the caller method should immediately return after calling disconnect().
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::close(), nidas::core::SampleConnectionRequester::disconnect(), nidas::core::SampleOutputBase::getName(), and ILOG.
Referenced by receive(), and nidas::dynld::raf::CVIOutput::receive().
flush()
void nidas::dynld::AsciiOutput::flush () throw () inline virtual
Implementation of SampleClient::flush().
Implements nidas::core::SampleClient.
fromDOMElement()
void SampleOutputBase::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::UDPSampleOutput, nidas::dynld::RawSampleOutputStream, nidas::dynld::psql::PSQLSampleOutput, and nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::addParameter(), nidas::core::IOChannel::createIOChannel(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleOutputBase::getDSMConfig(), nidas::core::Project::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), nidas::core::IOChannel::setDSMConfig(), nidas::core::SampleOutputBase::setIOChannel(), nidas::core::SampleOutputBase::setLatency(), nidas::core::SampleOutputBase::setName(), and WLOG.
Referenced by nidas::dynld::RawSampleOutputStream::fromDOMElement(), and nidas::dynld::UDPSampleOutput::fromDOMElement().
getDSMConfig()
const DSMConfig* nidas::core::SampleOutputBase::getDSMConfig () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
getFd()
int SampleOutputBase::getFd () const virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_iochan, and nidas::core::IOChannel::getFd().
getIOChannel()
IOChannel* nidas::core::SampleOutputBase::getIOChannel () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan.
Referenced by AsciiOutput(), connect(), nidas::core::SampleOutputBase::createNextFile(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::GOESOutput::GOESOutput(), printHeader(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::raf::CVIOutput::requestConnection(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), nidas::dynld::isff::GOESOutput::setIOChannel(), and nidas::dynld::UDPSampleOutput::write().
getLatency()
float nidas::core::SampleOutputBase::getLatency () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_latency.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream().
getName()
const std::string& nidas::core::SampleOutputBase::getName () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_name.
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::addConnection(), AsciiOutput(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::core::SampleOutputBase::close(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::disconnect(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::dynld::SampleOutputStream::flush(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::removeConnection(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), nidas::dynld::isff::GOESOutput::setIOChannel(), nidas::dynld::SampleOutputStream::setLatency(), and nidas::dynld::isff::GOESOutput::write().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNextFileTime()
dsm_time_t nidas::core::SampleOutputBase::getNextFileTime () const inline inherited
References nidas::core::SampleOutputBase::_nextFileTime.
Referenced by receive(), and nidas::dynld::raf::CVIOutput::receive().
getNumDiscardedSamples()
size_t nidas::core::SampleOutputBase::getNumDiscardedSamples () const inline inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
getOriginal()
SampleOutput* nidas::core::SampleOutputBase::getOriginal () const inline virtual inherited
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_original.
getParameter()
const Parameter * SampleOutputBase::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::SampleOutputBase::_parameters.
getParameters()
const std::list<const Parameter*>& nidas::core::SampleOutputBase::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleOutputBase::_constParameters.
Referenced by nidas::dynld::UDPSampleOutput::fromDOMElement().
getReconnectDelaySecs()
int SampleOutputBase::getReconnectDelaySecs () const virtual inherited
Base class implementation.
If setReconnectDelaySecs() has been called on this SampleOutput, then that value will be returned. Otherwise this will return the value of the IOChannel.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_reconnectDelaySecs, and nidas::core::IOChannel::getReconnectDelaySecs().
getRequestedSampleTags()
std::list< const SampleTag * > SampleOutputBase::getRequestedSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::GOESOutput::run(), and nidas::core::SampleOutputBase::SampleOutputBase().
getSampleConnectionRequester()
SampleConnectionRequester* nidas::core::SampleOutputBase::getSampleConnectionRequester () inline protected inherited
References nidas::core::SampleOutputBase::_connectionRequester.
getSourceSampleTags()
list< const SampleTag * > SampleOutputBase::getSourceSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase().
incrementDiscardedSamples()
size_t nidas::core::SampleOutputBase::incrementDiscardedSamples () inline protected inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
isRaw()
bool nidas::core::SampleOutputBase::isRaw () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::RawSampleOutputStream, and nidas::dynld::psql::PSQLSampleOutput.
printHeader()
void AsciiOutput::printHeader () protected
Exceptions
nidas::util::IOException
References _headerOut, _ostr, nidas::core::SampleOutputBase::getIOChannel(), and nidas::core::IOChannel::write().
Referenced by receive().
receive()
bool AsciiOutput::receive (const Sample * samp) virtual
Exceptions
Implements nidas::core::SampleClient.
References _format, _headerOut, _ostr, _prevTT, ASCII, nidas::core::CHAR_ST, nidas::core::SampleOutputBase::createNextFile(), DEFAULT, nidas::core::SampleOutputBase::disconnect(), nidas::core::DOUBLE_ST, FLOAT, nidas::core::FLOAT_ST, nidas::util::UTime::format(), fp, GET_DSM_ID, GET_SHORT_ID, nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getDataLength(), nidas::core::Sample::getDataValue(), nidas::core::Sample::getId(), nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), nidas::core::SampleOutputBase::getNextFileTime(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::getType(), HEX, IRIG, nidas::util::Logger::log(), LOG_ERR, printHeader(), SIGNED_SHORT, nidas::dynld::raf::IRIGSensor::statusString(), UNSIGNED_SHORT, USECS_PER_SEC, nidas::util::Exception::what(), and nidas::core::IOChannel::write().
requestConnection()
void AsciiOutput::requestConnection (SampleConnectionRequester * requester) throw () virtual
Request a connection, but don't wait for it.
Requester will be notified via SampleConnectionRequester interface when the connection has been made. It is not necessary to call this method if a SampleOutput is constructed with a connected IOChannel.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::requestConnection().
setDSMConfig()
void nidas::core::SampleOutputBase::setDSMConfig (const DSMConfig * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
setFormat()
void nidas::dynld::AsciiOutput::setFormat (format_t val) inline
Set the format for character samples.
Raw sensor samples are character samples.
setHeaderSource()
void nidas::core::SampleOutputBase::setHeaderSource (HeaderSource * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_headerSource.
Referenced by ARLIngest::run(), NidsMerge::run(), and SensorExtract::run().
setIOChannel()
void SampleOutputBase::setIOChannel (IOChannel * val) virtual inherited
Set the IOChannel for this SampleOutput.
This IOChannel is not yet connected. The IOChannel must be connected before the SampleOutput is used for I/O, using the requestConnection() method, or by IOChannel::connect() followed by SampleOutput::connected(IOChannel*).
Reimplemented in nidas::dynld::isff::GOESOutput, and nidas::dynld::raf::CVIOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::IOChannel::setDSMConfig().
Referenced by connect(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::raf::CVIOutput::setIOChannel(), and nidas::dynld::isff::GOESOutput::setIOChannel().
setLatency()
void nidas::core::SampleOutputBase::setLatency (float val) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the IOStream for a 1/10 sec, then send the data to the physical device.
Parameters
val Latency, in seconds.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::SampleOutputStream.
References nidas::core::SampleOutputBase::_latency.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleOutputStream::setLatency().
setName()
void nidas::core::SampleOutputBase::setName (const std::string & val) inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_name.
Referenced by AsciiOutput(), nidas::core::SampleOutputBase::connected(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), and nidas::dynld::isff::GOESOutput::setIOChannel().
setReconnectDelaySecs()
void SampleOutputBase::setReconnectDelaySecs (int val) virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_reconnectDelaySecs.
Referenced by nidas::dynld::raf::SyncServer::init().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write()
size_t SampleOutputBase::write (const void * buf, size_t len) virtual inherited
Raw write method, typically used to write the initial header.
Exceptions
nidas::util::IOException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_iochan, len, and nidas::core::IOChannel::write().
Member Data Documentation
_connectionRequester
SampleConnectionRequester* nidas::core::SampleOutputBase::_connectionRequester private inherited
Referenced by nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::disconnect(), nidas::core::SampleOutputBase::getSampleConnectionRequester(), and nidas::core::SampleOutputBase::requestConnection().
_constParameters
std::list<const Parameter*> nidas::core::SampleOutputBase::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::SampleOutputBase::addParameter(), and nidas::core::SampleOutputBase::getParameters().
_constRequestedTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_constRequestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::getRequestedSampleTags().
_dsm
const DSMConfig* nidas::core::SampleOutputBase::_dsm private inherited
Referenced by nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::SampleOutputBase::setDSMConfig().
_format
format_t nidas::dynld::AsciiOutput::_format private
Referenced by receive().
_headerOut
bool nidas::dynld::AsciiOutput::_headerOut private
Referenced by printHeader(), and receive().
_headerSource
HeaderSource* nidas::core::SampleOutputBase::_headerSource private inherited
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::setHeaderSource().
_iochan
IOChannel* nidas::core::SampleOutputBase::_iochan private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::getFd(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getReconnectDelaySecs(), nidas::core::SampleOutputBase::requestConnection(), nidas::core::SampleOutputBase::SampleOutputBase(), nidas::core::SampleOutputBase::setIOChannel(), nidas::core::SampleOutputBase::write(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_latency
float nidas::core::SampleOutputBase::_latency private inherited
Referenced by nidas::core::SampleOutputBase::getLatency(), and nidas::core::SampleOutputBase::setLatency().
_name
std::string nidas::core::SampleOutputBase::_name protected inherited
Referenced by nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
_nextFileTime
dsm_time_t nidas::core::SampleOutputBase::_nextFileTime private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::getNextFileTime().
_nsamplesDiscarded
size_t nidas::core::SampleOutputBase::_nsamplesDiscarded private inherited
Referenced by nidas::core::SampleOutputBase::getNumDiscardedSamples(), and nidas::core::SampleOutputBase::incrementDiscardedSamples().
_original
SampleOutput* nidas::core::SampleOutputBase::_original private inherited
Pointer to the SampleOutput that I was cloned from.
Referenced by nidas::core::SampleOutputBase::getOriginal().
_ostr
std::ostringstream nidas::dynld::AsciiOutput::_ostr private
Referenced by printHeader(), and receive().
_parameters
std::map<std::string,Parameter*> nidas::core::SampleOutputBase::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleOutputBase::getParameter(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_prevTT
std::map<dsm_sample_id_t,dsm_time_t> nidas::dynld::AsciiOutput::_prevTT private
Previous time tags by sample id.
Used for displaying time diffs.
Referenced by receive().
_reconnectDelaySecs
int nidas::core::SampleOutputBase::_reconnectDelaySecs private inherited
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs(), and nidas::core::SampleOutputBase::setReconnectDelaySecs().
_requestedTags
std::list<SampleTag*> nidas::core::SampleOutputBase::_requestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_sourceTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_sourceTags private inherited
Referenced by nidas::core::SampleOutputBase::addSourceSampleTag(), and nidas::core::SampleOutputBase::getSourceSampleTags().
_tagsMutex
nidas::util::Mutex nidas::core::SampleOutputBase::_tagsMutex mutable private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), nidas::core::SampleOutputBase::addSourceSampleTag(), nidas::core::SampleOutputBase::getRequestedSampleTags(), and nidas::core::SampleOutputBase::getSourceSampleTags().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/AsciiOutput.h
nidas/dynld/AsciiOutput.cc