nidas: nidas::core::DerivedDataReader Class Reference
nidas::core::DerivedDataReader Class Reference
This class will read, parse and make available the parameters in the onboard real-time broadcast of data.
#include <DerivedDataReader.h>
Classes
struct IWG1_Field
Public Types
enum runStatus { RUN_CANCELED = -1 , RUN_OK = 0 , NOT_RUNNING = 1 , RUN_EXCEPTION = 2 }
Values that can be returned by run method.
enum SchedPolicy { NU_THREAD_OTHER =SCHED_OTHER , NU_THREAD_FIFO =SCHED_FIFO , NU_THREAD_RR =SCHED_RR }
Public Member Functions
float getTrueAirspeed () const
float getAmbientTemperature () const
float getStaticPressure () const
float getLatitude () const
float getLongitude () const
float getAltitude () const
float getRadarAltitude () const
float getTrueHeading () const
float getGroundSpeed () const
int run ()
The method which will run in its own thread.
void addClient (DerivedDataClient *ddc)
Add a client to DerivedDataReader.
void removeClient (DerivedDataClient *ddc)
void interrupt ()
Interrupt this thread.
virtual void start ()
Start the thread running, meaning execute the run method in a separate thread.
virtual int join ()
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
virtual void kill (int sig)
Send a signal to this thread.
virtual void cancel ()
Cancel this thread.
virtual bool isInterrupted () const
Return true when this thread has been interrupted.
virtual bool isRunning () const
Is this thread running?
virtual bool isJoined () const
Has this thread been joined?
virtual bool isDetached () const
Is this a detached thread.
bool isCancelEnabled () const
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
bool isCancelDeferred () const
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
const std::string & getName () const throw ()
Return the name of this thread.
const std::string & getFullName () throw ()
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
bool setRealTimeRoundRobinPriority (int val)
bool setRealTimeFIFOPriority (int val)
bool setNonRealTimePriority ()
void setThreadScheduler (enum SchedPolicy policy, int priority)
void blockSignal (int)
Block a signal in this thread.
void unblockSignal (int)
Install a signal handler and unblock the signal.
Static Public Member Functions
static DerivedDataReader * createInstance (const nidas::util::SocketAddress &)
Create the instance of DerivedDataReader.
static void deleteInstance ()
Delete the singleton instance of DerivedDataReader, shutting down the thread if is is running.
static DerivedDataReader * getInstance ()
Fetch the pointer to the instance of DerivedDataReader.
static Thread * currentThread ()
Return the thread object for the current thread.
static pthread_t currentThreadId ()
static Thread * lookupThread (pthread_t id)
static const std::string & currentName ()
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
static std::string getPolicyString (int policy)
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
static int test (int argc, char **argv)
a test method.
Protected Member Functions
void setCancelEnabled (bool val)
Set the cancel state for this thread - false means cancel requests are ignored.
void setCancelDeferred (bool val)
Set the cancel type for this thread.
pthread_t getId () const
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Private Member Functions
DerivedDataReader (const nidas::util::SocketAddress &)
Constructor.
~DerivedDataReader ()
void notifyClients ()
int parseIWGADTS (const char *)
Parse the IWGADTS trivial broadcast.
DerivedDataReader (const DerivedDataReader &)
No copying.
DerivedDataReader & operator= (const DerivedDataReader &)
No assignment.
virtual void signalHandler (int, siginfo_t *)
Signal handler function for this thread.
virtual int pRun ()
void setThreadSchedulerNolock (enum SchedPolicy policy, int priority)
void makeFullName ()
void registerThread ()
Register this current thread with a static registry of threads by id.
void unregisterThread ()
void unsetId ()
Static Private Member Functions
static void * thr_run (void *me)
static void * thr_run_detached (void *me)
static void thr_cleanup (void *me)
static void thr_cleanup_delete (void *me)
static void thr_add_sig (int sig)
static void sigAction (int sig, siginfo_t *si, void *vptr)
Private Attributes
nidas::util::Mutex _clientMutex
std::list< DerivedDataClient * > _clients
nidas::util::SocketAddress * _saddr
float _tas
float _at
float _ps
float _lat
float _lon
float _alt
float _radarAlt
float _thdg
float _grndSpd
int _parseErrors
int _errorLogs
std::vector< IWG1_Field > _fields
Mutex _mutex
Mutex for accessing _id.
std::string _name
std::string _fullname
pthread_t _id
bool _running
bool _interrupted
bool _cancel_enabled
bool _cancel_deferred
pthread_attr_t _thread_attr
Exception * _exception
Exception thrown by run method.
bool _detached
sigset_t _blockedSignals
sigset_t _unblockedSignals
Static Private Attributes
static DerivedDataReader * _instance = 0
static nidas::util::Mutex _instanceMutex
static std::string unknownName = std::string("unknown")
Detailed Description
This class will read, parse and make available the parameters in the onboard real-time broadcast of data.
Member Enumeration Documentation
runStatus
enum nidas::util::Thread::runStatus inherited
Values that can be returned by run method.
User can define other values greater than RUN_EXCEPTION. These values are then returned by int join(). Note that PTHREAD_CANCELLED is -1
Enumerator
RUN_CANCELED
RUN_OK
NOT_RUNNING
RUN_EXCEPTION
SchedPolicy
enum nidas::util::Thread::SchedPolicy inherited
Enumerator
NU_THREAD_OTHER
NU_THREAD_FIFO
NU_THREAD_RR
Constructor & Destructor Documentation
DerivedDataReader() [1/2]
DerivedDataReader::DerivedDataReader (const nidas::util::SocketAddress & addr) private
Constructor.
The user does not call this constructor directly since this class is a singleton. Instead, the first instance should be created with the static createInstance() method. A pointer to the singleton can be gotten with the static getInstance() method.
References _alt, _at, _fields, _grndSpd, _lat, _lon, _ps, _radarAlt, _tas, _thdg, nidas::util::Thread::blockSignal(), and nidas::util::Thread::unblockSignal().
Referenced by createInstance().
~DerivedDataReader()
DerivedDataReader::~DerivedDataReader () private
References _saddr.
DerivedDataReader() [2/2]
nidas::core::DerivedDataReader::DerivedDataReader (const DerivedDataReader &) private
No copying.
Member Function Documentation
addClient()
void DerivedDataReader::addClient (DerivedDataClient * ddc)
Add a client to DerivedDataReader.
The derivedDataNotify method of the client will be called when derived data is received.
References _clientMutex, _clients, nidas::util::Mutex::lock(), removeClient(), and nidas::util::Mutex::unlock().
Referenced by nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::dynld::raf::AlicatSDI::open(), nidas::dynld::raf::PIP_Serial::open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::CVIOutput::requestConnection(), and nidas::dynld::raf::CVIOutput::setIOChannel().
amInterrupted()
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::Looper::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
blockSignal()
void Thread::blockSignal (int sig) inherited
Block a signal in this thread.
This method is usually called before this Thread has started. If this Thread is currently running, then this method is only effective if called from this Thread, i.e. from its own run() method.
Because SIGINT, SIGTERM and SIGHUP are typically caught in the main thread, they are blocked by default in a Thread. Call unblockSignal(sig) if you want to catch them in a Thread.
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::ConnectionMonitor(), nidas::core::ServerSocket::ConnectionThread::ConnectionThread(), DerivedDataReader(), nidas::util::McSocketListener::McSocketListener(), nidas::util::McSocketMulticaster< SocketTT >::McSocketMulticaster(), nidas::core::SensorHandler::SensorHandler(), nidas::core::SensorOpener::SensorOpener(), nidas::util::Thread::test(), nidas::dynld::RawSampleService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
cancel()
void Thread::cancel () virtual inherited
Cancel this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::DSMService::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), deleteInstance(), and nidas::core::DSMEngine::joinDataThreads().
createInstance()
DerivedDataReader * DerivedDataReader::createInstance (const nidas::util::SocketAddress & addr) static
Create the instance of DerivedDataReader.
References _instance, _instanceMutex, DerivedDataReader(), and nidas::util::Thread::start().
Referenced by nidas::core::DSMEngine::run().
currentName()
static const std::string& nidas::util::Thread::currentName () inline static inherited
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
References nidas::util::Thread::currentThread(), nidas::util::Thread::getName(), and nidas::util::Thread::unknownName.
Referenced by nidas::util::Logger::msg_locked().
currentThread()
Thread * Thread::currentThread () static inherited
Return the thread object for the current thread.
Returns null if not found.
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::currentName(), and nidas::util::Thread::unblockSignal().
currentThreadId()
pthread_t Thread::currentThreadId () static inherited
Referenced by nidas::core::Looper::removeClient().
deleteInstance()
void DerivedDataReader::deleteInstance () static
Delete the singleton instance of DerivedDataReader, shutting down the thread if is is running.
References _instance, _instanceMutex, nidas::util::Thread::cancel(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), PLOG, and nidas::util::Exception::what().
Referenced by nidas::core::DSMEngine::deleteDataThreads().
getAltitude()
float nidas::core::DerivedDataReader::getAltitude () const inline
References _alt.
getAmbientTemperature()
float nidas::core::DerivedDataReader::getAmbientTemperature () const inline
References _at.
Referenced by nidas::dynld::raf::AlicatSDI::derivedDataNotify(), nidas::dynld::raf::VCSEL2_Serial::derivedDataNotify(), and nidas::dynld::raf::VCSEL_Serial::derivedDataNotify().
getFullName()
const std::string & Thread::getFullName () throw () inherited
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
References nidas::util::Thread::_fullname.
Referenced by nidas::util::Thread::pRun(), nidas::util::Thread::test(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
getGroundSpeed()
float nidas::core::DerivedDataReader::getGroundSpeed () const inline
References _grndSpd.
getId()
pthread_t nidas::util::Thread::getId () const inline protected inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Referenced by nidas::util::Thread::isJoined(), nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::core::Looper::removeClient().
getInstance()
DerivedDataReader * DerivedDataReader::getInstance () static
Fetch the pointer to the instance of DerivedDataReader.
References _instance.
Referenced by nidas::dynld::raf::AlicatSDI::close(), nidas::dynld::raf::PIP_Serial::close(), nidas::dynld::raf::TwoD_USB::close(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::DSMEngine::deleteDataThreads(), nidas::core::DSMEngine::interrupt(), nidas::core::DSMEngine::joinDataThreads(), nidas::dynld::raf::AlicatSDI::open(), nidas::dynld::raf::PIP_Serial::open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::CVIOutput::requestConnection(), nidas::dynld::raf::CVIOutput::setIOChannel(), and nidas::dynld::raf::CVIOutput::~CVIOutput().
getLatitude()
float nidas::core::DerivedDataReader::getLatitude () const inline
References _lat.
getLongitude()
float nidas::core::DerivedDataReader::getLongitude () const inline
References _lon.
getName()
const std::string & Thread::getName () const throw () inherited
Return the name of this thread.
References nidas::util::Thread::_name.
Referenced by nidas::core::DSMService::cancel(), nidas::util::Thread::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), nidas::core::SensorHandler::PolledDSMSensor::close(), nidas::util::Thread::currentName(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SampleSorter::heapDecrement(), nidas::core::DSMService::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleSorter::run(), nidas::util::ThreadJoiner::run(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::sigAction(), nidas::util::Thread::start(), nidas::util::Thread::test(), nidas::util::LogContext::threadName(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
getPolicyString()
string Thread::getPolicyString (int policy) static inherited
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
References nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::NU_THREAD_RR.
Referenced by nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::makeFullName().
getRadarAltitude()
float nidas::core::DerivedDataReader::getRadarAltitude () const inline
References _radarAlt.
getStaticPressure()
float nidas::core::DerivedDataReader::getStaticPressure () const inline
References _ps.
Referenced by nidas::dynld::raf::AlicatSDI::derivedDataNotify(), and nidas::dynld::raf::VCSEL2_Serial::derivedDataNotify().
getTrueAirspeed()
float nidas::core::DerivedDataReader::getTrueAirspeed () const inline
References _tas.
Referenced by nidas::dynld::raf::CVIOutput::derivedDataNotify(), nidas::dynld::raf::AlicatSDI::derivedDataNotify(), nidas::dynld::raf::LamsSensor::derivedDataNotify(), and nidas::dynld::raf::TwoD_USB::derivedDataNotify().
getTrueHeading()
float nidas::core::DerivedDataReader::getTrueHeading () const inline
References _thdg.
interrupt()
void DerivedDataReader::interrupt () virtual
Interrupt this thread.
This sets a boolean which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted. This is a "soft" request to terminate the thread.
What follows is a discussion of when to use cancel(), kill(), or interrupt() to terminate a thread.
If you can consistently check the state of isInterrupted() in the run method, and return if it is true, at a time interval which is an acceptable amount of time to wait for the thread to terminate, then using interrupt() should work well.
If the run method does I/O, then things are usually a bit more complicated.
If all I/O is guaranteed to finish quickly, which is a rare situation, or is done with a timeout, such as using select/poll with a timeout before every read/write, then one could still use interrupt() as above, and the thread will terminate within the timeout period.
If the thread does blocking I/O operations, and the I/O might block for a period of time longer than you're willing to wait for the thread to terminate, then you need to use kill(sig) or cancel().
If a signal is sent to the thread with kill(sig) while the thread is blocking on an I/O operation, the I/O will immediately return with an errno of EINTR, and one could then return from the run method, after any necessary cleanup.
However there is a possibility that the signal could be missed. In order to make sure you receive a signal, you must block it, so that any received signals are held as pending, and then atomically unblock it with pselect/ppoll/epoll_pwait before performing the I/O operation.
If you do not use I/O timeouts, or kill(sig) with pselect/ppoll/epoll_pwait, or other tricks such as writing to a pipe that is watched with select/poll in the run method, then using cancel() is the only way to guarantee that your thread will terminate in an acceptable amount of time.
All NIDAS Threads support deferred cancelation. Immediate asynchronous cancellation is not fully supported (and is very hard to get right). Deferred cancelation means that cancellation is delayed until the thread next calls a system function that is a cancellation point. At that point the thread run method will simply terminate without any return value from the system function, and then execute any cleanup methods that may have been registered with pthread_cleanup_push.
A list of cancellation points is provided in the pthreads(7) man page. Cancellation points are typically I/O operations, waits or sleeps.
This immediate thread termination can be a problem if there is a possibility that your objects could be left in a bad state, such as with a mutex locked, though it isn't generally a good practice to hold mutexes during a time-consuming I/O operation, wait or sleep.
One should check the run method to see if the state of the objects is OK if execution stops at any of the cancellation points. Note that logging a message, or writing to cerr is a cancellation point. Typically there is error/exception handling associated with an I/O operation. Ensuring the state is OK upon a cancellation is similar to preparation for a fatal I/O error that requires a return of the run method. One can use setCancelEnabled() to defer cancellation.
One can use pthread_cleanup_push and pthread_cleanup_pop to register cleanup routines that are called when a thread is cancelled if special handling is required.
Reimplemented from nidas::util::Thread.
References nidas::util::Thread::kill(), nidas::util::Exception::what(), and WLOG.
Referenced by nidas::core::DSMEngine::interrupt().
isCancelDeferred()
bool Thread::isCancelDeferred () const inherited
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
References nidas::util::Thread::_cancel_deferred.
isCancelEnabled()
bool Thread::isCancelEnabled () const inherited
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
References nidas::util::Thread::_cancel_enabled.
isDetached()
virtual bool nidas::util::Thread::isDetached () const inline virtual inherited
Is this a detached thread.
References nidas::util::Thread::_detached.
isInterrupted()
virtual bool nidas::util::Thread::isInterrupted () const inline virtual inherited
Return true when this thread has been interrupted.
Implements nidas::util::Runnable.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::core::SampleSorter::flush(), nidas::dynld::raf::SyncServer::read(), ServerThread::run(), Sender::run(), ModemLineSetter::run(), ModemLineMonitor::run(), run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleBuffer::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::SampleSorter::run(), nidas::core::SensorHandler::run(), nidas::core::SensorOpener::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::util::McSocketListener::run(), and nidas::dynld::raf::SyncServer::stop().
isJoined()
virtual bool nidas::util::Thread::isJoined () const inline virtual inherited
Has this thread been joined?
References nidas::util::Thread::getId().
Referenced by nidas::core::FsMount::cancel(), deleteInstance(), nidas::core::SensorHandler::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::util::Thread::test(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
isRunning()
virtual bool nidas::util::Thread::isRunning () const inline virtual inherited
Is this thread running?
References nidas::util::Thread::_mutex, and nidas::util::Thread::_running.
Referenced by nidas::util::Thread::blockSignal(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), deleteInstance(), nidas::core::DSMService::interrupt(), nidas::core::SamplePipeline::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::Looper::removeClient(), nidas::core::ServerSocket::requestConnection(), nidas::core::SensorHandler::run(), nidas::core::Looper::setupClientMaps(), nidas::util::Thread::test(), nidas::util::Thread::unblockSignal(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::util::Thread::~Thread(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
join()
int Thread::join () virtual inherited
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
The return value is the int return value of the run method, or PTHREAD_CANCELED (-1). If the run method threw an Exception, it will be caught and then re-thrown by join.
Exceptions
Exception
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_exception, nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), nidas::util::Thread::getId(), nidas::util::Thread::getName(), nidas::util::Thread::RUN_EXCEPTION, and nidas::util::Thread::RUN_OK.
Referenced by nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocketListener::close(), deleteInstance(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::core::SensorHandler::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::core::DSMEngine::killXmlRpcThread(), nidas::core::DSMServerApp::killXmlRpcThread(), main(), nidas::core::Looper::removeClient(), nidas::util::ThreadJoiner::run(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
kill()
void Thread::kill (int sig) virtual inherited
Send a signal to this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::FsMount::cancel(), interrupt(), nidas::core::SensorHandler::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::XmlRpcThread::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), main(), nidas::core::SensorHandler::scheduleAdd(), nidas::core::SensorHandler::scheduleClose(), nidas::core::SensorHandler::scheduleReopen(), and nidas::core::SensorHandler::sensorIsOpen().
lookupThread()
Thread * Thread::lookupThread (pthread_t id) static inherited
Referenced by nidas::util::LogContext::threadName().
makeFullName()
void Thread::makeFullName () private inherited
References nidas::util::Thread::_cancel_deferred, nidas::util::Thread::_cancel_enabled, nidas::util::Thread::_detached, nidas::util::Thread::_fullname, nidas::util::Thread::_id, nidas::util::Thread::_name, and nidas::util::Thread::getPolicyString().
Referenced by nidas::util::Thread::start().
notifyClients()
void DerivedDataReader::notifyClients () private
References _clientMutex, _clients, nidas::core::DerivedDataClient::derivedDataNotify(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by run().
operator=()
DerivedDataReader& nidas::core::DerivedDataReader::operator= (const DerivedDataReader &) private
No assignment.
parseIWGADTS()
int DerivedDataReader::parseIWGADTS (const char * buffer) private
Parse the IWGADTS trivial broadcast.
Returns
: number of expected comma delimited fields that were found. _nparseErrors is incremented if the expected number of comma delimited fields are not found, and for every field that is not parseable with f.
References _fields, _parseErrors, buffer, nidas::core::floatNAN, and fp.
Referenced by run().
pRun()
int Thread::pRun () private virtual inherited
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_exception, nidas::util::Thread::_mutex, nidas::util::Thread::_unblockedSignals, nidas::util::Exception::clone(), nidas::util::Thread::getFullName(), nidas::util::Thread::getId(), ILOG, nidas::util::Mutex::lock(), nidas::util::Mutex::ptr(), nidas::util::Runnable::run(), and nidas::util::Thread::RUN_EXCEPTION.
Referenced by nidas::util::Thread::thr_run(), and nidas::util::Thread::thr_run_detached().
registerThread()
void Thread::registerThread () private inherited
Register this current thread with a static registry of threads by id.
Thread::registerThread (new Thread ("Main"));
Referenced by nidas::util::Thread::start().
removeClient()
void DerivedDataReader::removeClient (DerivedDataClient * ddc)
References _clientMutex, _clients, nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by addClient(), nidas::dynld::raf::AlicatSDI::close(), nidas::dynld::raf::PIP_Serial::close(), nidas::dynld::raf::TwoD_USB::close(), and nidas::dynld::raf::CVIOutput::~CVIOutput().
run()
int DerivedDataReader::run () virtual
The method which will run in its own thread.
This method must be supplied by the Runnable or Thread subclass.
Exceptions
Exception
Implements nidas::util::Runnable.
References _errorLogs, _parseErrors, _saddr, nidas::util::DatagramSocket::bind(), buffer, nidas::util::DatagramSocket::close(), fd, nidas::util::Exception::getErrno(), nidas::util::DatagramSocket::getFd(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramSocket::getLocalSocketAddress(), nidas::util::Thread::isInterrupted(), NLOG, notifyClients(), parseIWGADTS(), PLOG, nidas::util::DatagramSocket::receive(), nidas::util::Thread::RUN_OK, nidas::util::SocketAddress::toAddressString(), USECS_PER_SEC, nidas::util::Exception::what(), and WLOG.
setCancelDeferred()
void Thread::setCancelDeferred (bool val) protected inherited
Set the cancel type for this thread.
true means cancel requests are deferred until the next cancellation point. false means they occur instantly. This is protected, it should be called only from a thread's own run method. See the pthreads(7) man page for a list of the cancellation points.
Note: non-deferred canceling is difficult to get right. It has not been tested with this class, and is not recommended.
References nidas::util::Thread::_cancel_deferred.
setCancelEnabled()
void Thread::setCancelEnabled (bool val) protected inherited
Set the cancel state for this thread - false means cancel requests are ignored.
See pthread_setcancelstate. This is protected, it should be called only from a thread's own run method.
References nidas::util::Thread::_cancel_enabled.
setNonRealTimePriority()
bool Thread::setNonRealTimePriority () inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::setThreadScheduler().
setRealTimeFIFOPriority()
bool Thread::setRealTimeFIFOPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_FIFO, and nidas::util::Thread::setThreadScheduler().
Referenced by nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setRealTimeRoundRobinPriority()
bool Thread::setRealTimeRoundRobinPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_RR, and nidas::util::Thread::setThreadScheduler().
setThreadScheduler()
void Thread::setThreadScheduler (enum SchedPolicy policy, int priority) inherited
Exceptions
Exception
References nidas::util::Thread::_mutex, and nidas::util::Thread::setThreadSchedulerNolock().
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::getLooper(), nidas::util::Thread::setNonRealTimePriority(), nidas::util::Thread::setRealTimeFIFOPriority(), and nidas::util::Thread::setRealTimeRoundRobinPriority().
setThreadSchedulerNolock()
void Thread::setThreadSchedulerNolock (enum SchedPolicy policy, int priority) private inherited
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::util::Thread::setThreadScheduler(), and nidas::util::Thread::start().
sigAction()
void Thread::sigAction (int sig, siginfo_t * si, void * vptr) static private inherited
References DLOG, nidas::util::Thread::getName(), and nidas::util::Thread::signalHandler().
Referenced by nidas::util::Thread::thr_add_sig().
signalHandler()
virtual void nidas::util::Thread::signalHandler (int , siginfo_t *) inline private virtual inherited
Signal handler function for this thread.
The default handler just sets _interrupt to true, so that amInterrupted() or isInterrupted() will return true. Derived classes can override this method for custom signal handling. However, derived classes are limited in what they can do in their signal handler. Specifically, from the pthread_cond_signal man page:
"It is not safe to use the pthread_cond_signal() function in a signal handler that is invoked asynchronously."
Therefore do not call Cond::signal() from a signal handler.
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_interrupted.
Referenced by nidas::util::Thread::sigAction().
start()
void Thread::start () virtual inherited
Start the thread running, meaning execute the run method in a separate thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_interrupted, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), nidas::util::Thread::getName(), nidas::util::Thread::makeFullName(), nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::registerThread(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::thr_run(), nidas::util::Thread::thr_run_detached(), and WLOG.
Referenced by nidas::util::McSocketListener::accept(), nidas::dynld::RawSampleService::connect(), nidas::dynld::XMLConfigAllService::connected(), nidas::dynld::XMLConfigService::connected(), createInstance(), nidas::dynld::raf::SyncServer::getTimeWindow(), nidas::util::McSocket< SocketT >::joinMulticaster(), main(), nidas::core::FsMount::mount(), nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), nidas::core::SamplePipeline::rawinit(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), ServerThread::run(), PSI::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SensorHandler::run(), nidas::core::Socket::ConnectionThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::dynld::raf::SyncServer::setTimeWindow(), nidas::core::Looper::setupClientMaps(), nidas::core::DSMServerApp::startStatusThread(), nidas::core::DSMEngine::startXmlRpcThread(), and nidas::core::DSMServerApp::startXmlRpcThread().
test()
int Thread::test (int argc, char ** argv) static inherited
a test method.
References nidas::util::Runnable::amInterrupted(), nidas::util::Thread::blockSignal(), nidas::util::Thread::getFullName(), nidas::util::Thread::getName(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Runnable::run(), nidas::util::Thread::Thread(), and nidas::util::Exception::what().
testCancel()
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
thr_add_sig()
void Thread::thr_add_sig (int sig) static private inherited
References nidas::util::Thread::sigAction().
Referenced by nidas::util::Thread::blockSignal(), and nidas::util::Thread::unblockSignal().
thr_cleanup()
void Thread::thr_cleanup (void * me) static private inherited
References nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), ILOG, and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run().
thr_cleanup_delete()
void Thread::thr_cleanup_delete (void * me) static private inherited
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), nidas::util::Mutex::lock(), nidas::util::Mutex::unlock(), and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run_detached().
thr_run()
void * Thread::thr_run (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup().
Referenced by nidas::util::Thread::start().
thr_run_detached()
void * Thread::thr_run_detached (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup_delete().
Referenced by nidas::util::Thread::start().
unblockSignal()
void Thread::unblockSignal (int sig) inherited
Install a signal handler and unblock the signal.
The signal handler will log a message about the receipt of the signal at severity LOG_INFO using the nidas::util::Logger. Then, if the signal handler is being invoked from a registered Thread, the virtual method signalHandler() for that Thread will be called.
The signal handler is installed with the sigaction() system call, and will be the action for the given signal in all threads, including the main() thread. If other threads do not wish to take action on a given signal, they should call blockSignal(sig). Or they can define their own signalHandler() method.
After installing the signal handler, the signal is added to those that are unblocked for the thread, or if the Thread is not yet running, the signal will be unblocked in the thread once it runs.
As with blockSignal(), this method is typically called on this Thread before it has started. If this Thread has started, then the signal will only be unblocked if the method is called from this Thread, i.e. from its own run() method.
To install a signal handler, and then block the signal so that it is held as pending until it is later unblocked, typically with pselect(), or sigwaitinfo(), do:
void Thread::run()
{
    // get the existing signal mask
    sigset_t sigmask;
    pthread_sigmask(SIG_BLOCK,NULL,&sigmask);
    // remove SIGUSR1 from the mask passed to pselect
    sigdelset(&sigmask,SIGUSR1);
    for (;;) {
        pselect(nfd,&readfds,0,0,0,&sigmask);
        ...
    }
}
...
thread.unblockSignal(SIGUSR1);
thread.blockSignal(SIGUSR1);
thread.start();
...
try {
    if (thread.isRunning()) {
        thread.kill(SIGUSR1);
        thread.join()
    }
}
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by DerivedDataReader(), nidas::core::FsMountWorkerThread::FsMountWorkerThread(), nidas::core::StatusListener::StatusListener(), nidas::core::StatusThread::StatusThread(), nidas::dynld::XMLConfigService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
unregisterThread()
void Thread::unregisterThread () private inherited
Referenced by nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
unsetId()
void nidas::util::Thread::unsetId () inline private inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Member Data Documentation
_alt
float nidas::core::DerivedDataReader::_alt private
Referenced by DerivedDataReader(), and getAltitude().
_at
float nidas::core::DerivedDataReader::_at private
Referenced by DerivedDataReader(), and getAmbientTemperature().
_blockedSignals
sigset_t nidas::util::Thread::_blockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
_cancel_deferred
bool nidas::util::Thread::_cancel_deferred private inherited
Referenced by nidas::util::Thread::isCancelDeferred(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelDeferred().
_cancel_enabled
bool nidas::util::Thread::_cancel_enabled private inherited
Referenced by nidas::util::Thread::isCancelEnabled(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelEnabled().
_clientMutex
nidas::util::Mutex nidas::core::DerivedDataReader::_clientMutex private
Referenced by addClient(), notifyClients(), and removeClient().
_clients
std::list<DerivedDataClient*> nidas::core::DerivedDataReader::_clients private
Referenced by addClient(), notifyClients(), and removeClient().
_detached
bool nidas::util::Thread::_detached private inherited
Referenced by nidas::util::Thread::isDetached(), nidas::util::Thread::makeFullName(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_errorLogs
int nidas::core::DerivedDataReader::_errorLogs private
Referenced by run().
_exception
Exception* nidas::util::Thread::_exception private inherited
Exception thrown by run method.
Referenced by nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::util::Thread::~Thread().
_fields
std::vector<IWG1_Field> nidas::core::DerivedDataReader::_fields private
Referenced by DerivedDataReader(), and parseIWGADTS().
_fullname
std::string nidas::util::Thread::_fullname private inherited
Referenced by nidas::util::Thread::getFullName(), and nidas::util::Thread::makeFullName().
_grndSpd
float nidas::core::DerivedDataReader::_grndSpd private
Referenced by DerivedDataReader(), and getGroundSpeed().
_id
pthread_t nidas::util::Thread::_id private inherited
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::makeFullName(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_instance
DerivedDataReader * DerivedDataReader::_instance = 0 static private
Referenced by createInstance(), deleteInstance(), and getInstance().
_instanceMutex
nidas::util::Mutex DerivedDataReader::_instanceMutex static private
Referenced by createInstance(), and deleteInstance().
_interrupted
bool nidas::util::Thread::_interrupted private inherited
Referenced by nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::signalHandler(), and nidas::util::Thread::start().
_lat
float nidas::core::DerivedDataReader::_lat private
Referenced by DerivedDataReader(), and getLatitude().
_lon
float nidas::core::DerivedDataReader::_lon private
Referenced by DerivedDataReader(), and getLongitude().
_mutex
Mutex nidas::util::Thread::_mutex mutable private inherited
Mutex for accessing _id.
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::pRun(), nidas::util::Thread::setThreadScheduler(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_name
std::string nidas::util::Thread::_name private inherited
Referenced by nidas::util::Thread::getName(), and nidas::util::Thread::makeFullName().
_parseErrors
int nidas::core::DerivedDataReader::_parseErrors private
Referenced by parseIWGADTS(), and run().
_ps
float nidas::core::DerivedDataReader::_ps private
Referenced by DerivedDataReader(), and getStaticPressure().
_radarAlt
float nidas::core::DerivedDataReader::_radarAlt private
Referenced by DerivedDataReader(), and getRadarAltitude().
_running
bool nidas::util::Thread::_running private inherited
Referenced by nidas::util::Thread::isRunning(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
_saddr
nidas::util::SocketAddress* nidas::core::DerivedDataReader::_saddr private
Referenced by run(), and ~DerivedDataReader().
_tas
float nidas::core::DerivedDataReader::_tas private
Referenced by DerivedDataReader(), and getTrueAirspeed().
_thdg
float nidas::core::DerivedDataReader::_thdg private
Referenced by DerivedDataReader(), and getTrueHeading().
_thread_attr
pthread_attr_t nidas::util::Thread::_thread_attr private inherited
Referenced by nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_unblockedSignals
sigset_t nidas::util::Thread::_unblockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
unknownName
std::string Thread::unknownName = std::string("unknown") static private inherited
Referenced by nidas::util::Thread::currentName().
The documentation for this class was generated from the following files:
nidas/core/DerivedDataReader.h
nidas/core/DerivedDataReader.cc