nidas: DmdA2dCk Class Reference
DmdA2dCk Class Reference
Public Member Functions
DmdA2dCk ()
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
int run () throw ()
Static Public Member Functions
static int main (int argc, char **argv) throw ()
Private Attributes
NidasApp _app
string _aoutDev
AnalogOut device name.
Constructor & Destructor Documentation
DmdA2dCk()
DmdA2dCk::DmdA2dCk ()
References _app, nidas::core::NidasApp::setApplicationInstance(), and nidas::core::NidasApp::setupSignals().
Member Function Documentation
main()
int DmdA2dCk::main (int argc, char ** argv) throw () static
References parseRunstring(), run(), and nidas::util::Exception::what().
Referenced by main().
parseRunstring()
int DmdA2dCk::parseRunstring (int argc, char ** argv)
References _aoutDev, _app, nidas::core::NidasApp::enableArguments(), nidas::core::NidasAppArg::getValue(), nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::loggingArgs(), nidas::core::NidasApp::parseArgs(), nidas::core::NidasApp::parseInputs(), usage(), nidas::core::NidasApp::Version, nidas::util::Exception::what(), and nidas::core::NidasApp::XmlHeaderFile.
Referenced by main().
run()
int DmdA2dCk::run () throw ()
References _aoutDev, _app, nidas::dynld::DSC_A2DSensor::close(), nidas::dynld::DSC_AnalogOut::close(), nidas::util::Process::expandEnvVars(), nidas::util::UTime::format(), nidas::core::Sample::freeReference(), nidas::core::Sample::getDataLength(), nidas::core::Sample::getDataValue(), nidas::core::DSMSensor::getDeviceName(), nidas::dynld::DSC_AnalogOut::getMaxVoltage(), nidas::dynld::DSC_AnalogOut::getMinVoltage(), nidas::core::DSMConfig::getName(), nidas::dynld::DSC_AnalogOut::getNumOutputs(), nidas::core::DSMConfig::getSensors(), nidas::core::Sample::getTimeTag(), nidas::core::DSMConfigIterator::hasNext(), nidas::dynld::A2DSensor::init(), nidas::core::NidasApp::interrupted(), nidas::core::DSMConfigIterator::next(), nidas::dynld::DSC_AnalogOut::open(), nidas::dynld::DSC_A2DSensor::open(), nidas::core::parseXMLConfigFile(), nidas::dynld::A2DSensor::process(), nidas::core::DSMSensor::readSample(), nidas::core::DSMSensor::readSamples(), nidas::dynld::DSC_AnalogOut::setDeviceName(), nidas::dynld::DSC_AnalogOut::setVoltage(), nidas::dynld::DSC_A2DSensor::validate(), nidas::util::Exception::what(), and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
usage()
int DmdA2dCk::usage (const char * argv0)
References _app, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
_aoutDev
string DmdA2dCk::_aoutDev private
AnalogOut device name.
Referenced by parseRunstring(), and run().
_app
NidasApp DmdA2dCk::_app private
Referenced by DmdA2dCk(), parseRunstring(), run(), and usage().
The documentation for this class was generated from the following file:
nidas/apps/dsc_a2d_ck.cc