nidas: nidas::util::EndianConverter Class Reference
nidas::util::EndianConverter Class Reference abstract
Virtual base class declaring methods for converting numeric values between little-endian and big-endian representations, and for determining the endian represenation of the host system.
#include <EndianConverter.h>
Public Types
enum endianness { EC_UNKNOWN_ENDIAN , EC_BIG_ENDIAN , EC_LITTLE_ENDIAN }
Public Member Functions
virtual ~EndianConverter ()
virtual double doubleValue (const void *) const =0
Get 8 byte double at address, do endian conversion.
virtual double doubleValue (const double &) const =0
virtual float floatValue (const void *) const =0
Get 4 byte float at address, do endian conversion.
virtual float floatValue (const float &) const =0
virtual int32_t int32Value (const void *) const =0
Get 4 byte int32 at address, do endian conversion.
virtual int32_t int32Value (const int32_t &) const =0
virtual int64_t int64Value (const void *) const =0
Get 8 byte int64_t at address, do endian conversion.
virtual int64_t int64Value (const int64_t &) const =0
virtual uint32_t uint32Value (const void *) const =0
Get 4 byte unsigned int32_t at address, do endian conversion.
virtual uint32_t uint32Value (const uint32_t &) const =0
virtual int16_t int16Value (const void *) const =0
virtual int16_t int16Value (const int16_t &) const =0
virtual uint16_t uint16Value (const void *) const =0
virtual uint16_t uint16Value (const uint16_t &) const =0
virtual void doubleCopy (const double &, void *) const =0
Copy 8 byte double to the given address, doing endian conversion.
virtual void floatCopy (const float &, void *) const =0
Copy 4 byte float to the given address, doing endian conversion.
virtual void int32Copy (const int32_t &, void *) const =0
Copy 4 byte int to the given address, doing endian conversion.
virtual void int64Copy (const int64_t &, void *) const =0
Copy 8 byte int64_t to the given address, doing endian conversion.
virtual void uint32Copy (const uint32_t &, void *) const =0
Copy 4 byte unsigned int to the given address, doing endian conversion.
virtual void int16Copy (const int16_t &, void *) const =0
virtual void uint16Copy (const uint16_t &, void *) const =0
Static Public Member Functions
static endianness getHostEndianness ()
Return endianness value for this host.
static const EndianConverter * getConverter (endianness input, endianness output)
Return an EndianConverter for converting from one endian to another.
static const EndianConverter * getConverter (endianness input)
Return an EndianConverter for converting from an endian represenation to the endian representation of th host.
Static Public Attributes
static endianness hostEndianness = EndianConverter::EC_UNKNOWN_ENDIAN
Static Private Member Functions
static endianness privGetHostEndianness ()
Static Private Attributes
static EndianConverter * flipConverter = 0
static EndianConverter * noflipConverter = 0
static Mutex staticInitMutex = Mutex()
Detailed Description
Virtual base class declaring methods for converting numeric values between little-endian and big-endian representations, and for determining the endian represenation of the host system.
Implementations of this class are meant for serializing/de-serializing binary data. The methods read from an address or write to an address. The addresses do not have to be aligned correctly for the data value type.
Member Enumeration Documentation
endianness
enum nidas::util::EndianConverter::endianness
Enumerator
EC_UNKNOWN_ENDIAN
EC_BIG_ENDIAN
EC_LITTLE_ENDIAN
Constructor & Destructor Documentation
~EndianConverter()
virtual nidas::util::EndianConverter::~EndianConverter () inline virtual
Member Function Documentation
doubleCopy()
virtual void nidas::util::EndianConverter::doubleCopy (const double & , void *) const pure virtual
Copy 8 byte double to the given address, doing endian conversion.
Pointer to address does not need to be 8-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
doubleValue() [1/2]
virtual double nidas::util::EndianConverter::doubleValue (const double &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
doubleValue() [2/2]
virtual double nidas::util::EndianConverter::doubleValue (const void *) const pure virtual
Get 8 byte double at address, do endian conversion.
Pointer to address does not need to be 8-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
floatCopy()
virtual void nidas::util::EndianConverter::floatCopy (const float & , void *) const pure virtual
Copy 4 byte float to the given address, doing endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
floatValue() [1/2]
virtual float nidas::util::EndianConverter::floatValue (const float &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
floatValue() [2/2]
virtual float nidas::util::EndianConverter::floatValue (const void *) const pure virtual
Get 4 byte float at address, do endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
getConverter() [1/2]
const EndianConverter * EndianConverter::getConverter (EndianConverter::endianness input) static
Return an EndianConverter for converting from an endian represenation to the endian representation of th host.
If both are the same, then the converter that is returned just does memcpy's and does not change the representation. It is a const pointer since all its methods are const, and the pointer is owned by EndianConverter.
getConverter() [2/2]
const EndianConverter * EndianConverter::getConverter (EndianConverter::endianness input, EndianConverter::endianness output) static
Return an EndianConverter for converting from one endian to another.
If both are the same, then the converter that is returned just does memcpy's and does not change the representation. It is a const pointer since all its methods are const, and the pointer is owned by EndianConverter.
Referenced by nidas::dynld::isff::CSI_IRGA_Sonic::checkSampleTags(), nidas::dynld::DSC_Event::init(), nidas::dynld::DSC_FreqCounter::init(), nidas::dynld::DSC_PulseCounter::init(), nidas::dynld::IEEE_Float::init(), and nidas::dynld::isff::DAUSensor::init().
getHostEndianness()
EndianConverter::endianness EndianConverter::getHostEndianness () static
Return endianness value for this host.
Referenced by nidas::dynld::isff::CSI_IRGA_Sonic::checkSampleTags(), and nidas::dynld::IEEE_Float::init().
int16Copy()
virtual void nidas::util::EndianConverter::int16Copy (const int16_t & , void *) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
int16Value() [1/2]
virtual int16_t nidas::util::EndianConverter::int16Value (const int16_t &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
int16Value() [2/2]
virtual int16_t nidas::util::EndianConverter::int16Value (const void *) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
Referenced by nidas::dynld::isff::CSI_CRX_Binary::process(), and nidas::dynld::isff::CU_Coldwire::process().
int32Copy()
virtual void nidas::util::EndianConverter::int32Copy (const int32_t & , void *) const pure virtual
Copy 4 byte int to the given address, doing endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::FlipConverter.
int32Value() [1/2]
virtual int32_t nidas::util::EndianConverter::int32Value (const int32_t &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
int32Value() [2/2]
virtual int32_t nidas::util::EndianConverter::int32Value (const void *) const pure virtual
Get 4 byte int32 at address, do endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
Referenced by nidas::dynld::raf::IRIGSensor::getIRIGTime(), nidas::dynld::raf::IRIGSensor::getUnixTime(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::raf::TwoD32_USB::process(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::TwoD32_USB::processImage(), nidas::dynld::raf::TwoD64_USB::processSOR(), and ExtractFast2D::run().
int64Copy()
virtual void nidas::util::EndianConverter::int64Copy (const int64_t & , void *) const pure virtual
Copy 8 byte int64_t to the given address, doing endian conversion.
Pointer to address does not need to be 8-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
int64Value() [1/2]
virtual int64_t nidas::util::EndianConverter::int64Value (const int64_t &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
int64Value() [2/2]
virtual int64_t nidas::util::EndianConverter::int64Value (const void *) const pure virtual
Get 8 byte int64_t at address, do endian conversion.
Pointer to address does not need to be 8-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
Referenced by nidas::dynld::raf::IRIGSensor::getIRIGTime(), nidas::dynld::raf::IRIGSensor::getUnixTime(), and nidas::dynld::raf::TwoD64_USB::processImageRecord().
privGetHostEndianness()
EndianConverter::endianness EndianConverter::privGetHostEndianness () static private
References VLOG.
uint16Copy()
virtual void nidas::util::EndianConverter::uint16Copy (const uint16_t & , void *) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
uint16Value() [1/2]
virtual uint16_t nidas::util::EndianConverter::uint16Value (const uint16_t &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
uint16Value() [2/2]
virtual uint16_t nidas::util::EndianConverter::uint16Value (const void *) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
Referenced by nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::isff::WisardMote::readHead(), and nidas::dynld::isff::WisardMote::unpackPicTimeFields().
uint32Copy()
virtual void nidas::util::EndianConverter::uint32Copy (const uint32_t & , void *) const pure virtual
Copy 4 byte unsigned int to the given address, doing endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
uint32Value() [1/2]
virtual uint32_t nidas::util::EndianConverter::uint32Value (const uint32_t &) const pure virtual
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
uint32Value() [2/2]
virtual uint32_t nidas::util::EndianConverter::uint32Value (const void *) const pure virtual
Get 4 byte unsigned int32_t at address, do endian conversion.
Pointer to address does not need to be 4-byte aligned.
Implemented in nidas::util::NoFlipConverter, and nidas::util::FlipConverter.
Referenced by nidas::dynld::raf::UDPArincSensor::decodeTIMER(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::UDPArincSensor::process(), nidas::dynld::isff::WisardMote::unpack10thSec(), and nidas::dynld::isff::WisardMote::unpackAccumSec().
Member Data Documentation
flipConverter
EndianConverter * EndianConverter::flipConverter = 0 static private
hostEndianness
EndianConverter::endianness EndianConverter::hostEndianness = EndianConverter::EC_UNKNOWN_ENDIAN static
noflipConverter
EndianConverter * EndianConverter::noflipConverter = 0 static private
staticInitMutex
Mutex EndianConverter::staticInitMutex = Mutex() static private
The documentation for this class was generated from the following files:
nidas/util/EndianConverter.h
nidas/util/EndianConverter.cc