nidas: nidas/apps/ck_calfile.cc File Reference
ck_calfile.cc File Reference
#include <iostream>
#include <nidas/core/CalFile.h>
Functions
int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::core::CalFile::eof(), nidas::util::UTime::format(), nidas::core::CalFile::getLineNumber(), nidas::core::CalFile::readCF(), nidas::core::CalFile::setFile(), nidas::core::CalFile::setPath(), usage(), and nidas::util::Exception::what().
usage()
int usage (const char * argv0)
Referenced by nidas::util::Process::getMaxRSS(), main(), ARLIngest::parseRunstring(), PacketDecode::parseRunstring(), MergeVerifier::parseRunstring(), HeaderUtil::parseRunstring(), NidsMerge::parseRunstring(), ExtractDMT::parseRunstring(), SensorExtract::parseRunstring(), nidas::dynld::raf::Extract2D::parseRunstring(), and PConfig::parseRunstring().