nidas: nidas::core::Datasets Class Reference
nidas::core::Datasets Class Reference
A collection of Datasets.
#include <Datasets.h>
Public Member Functions
Datasets ()
const Dataset & getDataset (const std::string &name) const
std::list< Dataset > getDatasets () const
void addDataset (const Dataset &val)
void removeDataset (const Dataset &val)
void parseXML (const std::string &xmlFileName, bool verbose=true)
void writeXML (const std::string &xmlFileName)
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node) const
Private Attributes
std::string _xmlName
std::map< std::string, Dataset > _datasetsByName
Detailed Description
A collection of Datasets.
This collection is typically created by parsing an XML file containing a <datasets> element and one or more <dataset> elements.
Constructor & Destructor Documentation
Datasets()
Datasets::Datasets ()
Member Function Documentation
addDataset()
void Datasets::addDataset (const Dataset & val)
Exceptions
nidas::util::InvalidParameterException
References _datasetsByName, and nidas::core::Dataset::getName().
Referenced by fromDOMElement().
fromDOMElement()
void Datasets::fromDOMElement (const xercesc::DOMElement * node)
Exceptions
nidas::util::InvalidParameterException
References addDataset(), nidas::core::Dataset::fromDOMElement(), and nidas::core::XDOMElement::getNodeName().
Referenced by parseXML().
getDataset()
const Dataset & Datasets::getDataset (const std::string & name) const
Exceptions
nidas::util::InvalidParameterException
References _datasetsByName, and _xmlName.
Referenced by StatsProcess::getDataset(), nidas::core::NidasApp::getDataset(), and DatasetsApp::showEnv().
getDatasets()
std::list< Dataset > Datasets::getDatasets () const
References _datasetsByName.
Referenced by DatasetsApp::listDatasetNames(), and toDOMElement().
parseXML()
void Datasets::parseXML (const std::string & xmlFileName, bool verbose = true)
Exceptions
nidas::core::XMLException
nidas::util::InvalidParameterException
References _xmlName, fromDOMElement(), nidas::core::XMLParser::parse(), and verbose.
Referenced by StatsProcess::getDataset(), nidas::core::NidasApp::getDataset(), and DatasetsApp::run().
removeDataset()
void Datasets::removeDataset (const Dataset & val)
References _datasetsByName, and nidas::core::Dataset::getName().
toDOMElement()
xercesc::DOMElement * Datasets::toDOMElement (xercesc::DOMElement * node) const
Exceptions
xercesc::DOMException
References getDatasets(), and nidas::core::Dataset::toDOMParent().
Referenced by toDOMParent(), and writeXML().
toDOMParent()
xercesc::DOMElement * Datasets::toDOMParent (xercesc::DOMElement * parent) const
Exceptions
xercesc::DOMException
References nidas::core::DOMable::getNamespaceURI(), and toDOMElement().
writeXML()
void Datasets::writeXML (const std::string & xmlFileName)
Exceptions
nidas::core::XMLException
nidas::util::IOException
References fd, nidas::core::XMLImplementation::getImplementation(), nidas::core::DOMable::getNamespaceURI(), nidas::core::XMLWriter::setPrettyPrint(), toDOMElement(), and nidas::core::XMLWriter::write().
Member Data Documentation
_datasetsByName
std::map<std::string, Dataset> nidas::core::Datasets::_datasetsByName private
Referenced by addDataset(), getDataset(), getDatasets(), and removeDataset().
_xmlName
std::string nidas::core::Datasets::_xmlName private
Referenced by getDataset(), and parseXML().
The documentation for this class was generated from the following files:
nidas/core/Datasets.h
nidas/core/Datasets.cc