nidas: PConfig Class Reference
PConfig Class Reference
Public Member Functions
PConfig ()
int parseRunstring (NidasApp &app, int argc, char **argv)
void usage (const char *argv0)
bool parseRemoteSpecifier (const std::string &xmlspec, std::string &host, int &port)
void loadFile (const std::string &xmlfile, Project &project)
void loadRemoteXML (const std::string &host, int port, Project &project)
int main ()
void showAll (const Project &project)
void showSensorClasses (const Project &project)
void showCalFiles (const Project &project)
void showHostNames (const Project &project)
void showVariables ()
void loadVariables (const Project &project)
void getHostNames (const Project &project, std::vector< std::string > &dsmnames)
void resolveCalFile (CalFile *cf)
Private Attributes
string _xmlFile
list< string > _sensorClasses
bool _showCalFiles
bool _showHosts
bool _showVariables
variable_map_t _variables
Constructor & Destructor Documentation
PConfig()
PConfig::PConfig () inline
Member Function Documentation
getHostNames()
void PConfig::getHostNames (const Project & project, std::vector< std::string > & dsmnames)
References nidas::core::Site::expandString(), nidas::core::Site::getDSMConfigIterator(), nidas::core::DSMConfig::getName(), nidas::core::Project::getSiteIterator(), nidas::core::SiteIterator::hasNext(), and nidas::core::DSMConfigIterator::hasNext().
loadFile()
void PConfig::loadFile (const std::string & xmlfile, Project & project)
References nidas::core::Project::fromDOMElement(), nidas::core::XMLParser::parse(), nidas::core::XMLParser::setDOMDatatypeNormalization(), nidas::core::XMLParser::setDOMNamespaces(), nidas::core::XMLParser::setDOMValidateIfSchema(), nidas::core::XMLParser::setDOMValidation(), nidas::core::XMLParser::setXercesDoXInclude(), nidas::core::XMLParser::setXercesHandleMultipleImports(), nidas::core::XMLParser::setXercesSchema(), and nidas::core::XMLParser::setXercesSchemaFullChecking().
loadRemoteXML()
void PConfig::loadRemoteXML (const std::string & host, int port, Project & project)
References ELOG, nidas::core::Project::fromDOMElement(), nidas::util::Inet4Address::getByName(), ILOG, port, nidas::core::requestXMLConfig(), and nidas::util::Exception::what().
loadVariables()
void PConfig::loadVariables (const Project & project)
References DLOG, nidas::core::Site::getDSMConfigIterator(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::Project::getSiteIterator(), nidas::core::SampleTag::getStation(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SiteIterator::hasNext(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::SampleTag::isProcessed().
main()
int PConfig::main ()
References ILOG, port, nidas::core::XMLImplementation::terminate(), and nidas::util::Exception::what().
Referenced by main().
parseRemoteSpecifier()
bool PConfig::parseRemoteSpecifier (const std::string & xmlspec, std::string & host, int & port)
References port.
parseRunstring()
int PConfig::parseRunstring (NidasApp & app, int argc, char ** argv)
References nidas::core::NidasAppArg::asBool(), nidas::core::NidasApp::enableArguments(), nidas::core::NidasAppArg::getValue(), nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::loggingArgs(), nidas::core::NidasApp::parseNext(), nidas::core::NidasApp::startArgs(), nidas::core::NidasApp::unparsedArgs(), usage(), and nidas::core::NidasApp::Version.
Referenced by main().
resolveCalFile()
void PConfig::resolveCalFile (CalFile * cf)
References nidas::core::CalFile::close(), DLOG, nidas::core::CalFile::getCurrentFileName(), nidas::core::CalFile::getFile(), nidas::core::CalFile::open(), and nidas::util::Exception::what().
showAll()
void PConfig::showAll (const Project & project)
References nidas::core::DSMSensor::getClassName(), nidas::core::Site::getDSMConfigIterator(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getName(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::Site::getNumber(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::Project::getSiteIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SiteIterator::hasNext(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::SampleTag::isProcessed().
showCalFiles()
void PConfig::showCalFiles (const Project & project)
References nidas::core::VariableConverter::getCalFile(), nidas::core::DSMSensor::getCalFiles(), nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getClassName(), nidas::core::Variable::getConverter(), nidas::core::DSMSensor::getDeviceName(), nidas::core::Site::getDSMConfigs(), nidas::core::DSMSensor::getHeightString(), nidas::core::DSMConfig::getName(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMConfig::getSensors(), nidas::core::Project::getSiteIterator(), nidas::core::SampleTag::getVariables(), and nidas::core::SiteIterator::hasNext().
showHostNames()
void PConfig::showHostNames (const Project & project)
showSensorClasses()
void PConfig::showSensorClasses (const Project & project)
References nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getSensorId(), nidas::core::Project::getSensorIterator(), and nidas::core::SensorIterator::hasNext().
showVariables()
void PConfig::showVariables ()
References nidas::core::SampleTag::getRate(), nidas::core::Variable::getSampleTag(), and rate.
usage()
void PConfig::usage (const char * argv0)
References nidas::core::NidasApp::getApplicationInstance(), and nidas::core::NidasApp::usage().
Member Data Documentation
_sensorClasses
list<string> PConfig::_sensorClasses private
_showCalFiles
bool PConfig::_showCalFiles private
_showHosts
bool PConfig::_showHosts private
_showVariables
bool PConfig::_showVariables private
_variables
variable_map_t PConfig::_variables private
_xmlFile
string PConfig::_xmlFile private
The documentation for this class was generated from the following file:
nidas/apps/ck_xml.cc