nidas: GPS_SetClock Class Reference
GPS_SetClock Class Reference
Public Member Functions
GPS_SetClock ()
int parseRunstring (int argc, char **argv)
int run ()
Static Public Member Functions
static int usage (const char *argv0)
static const char * skipcommas (const char *cp, int ncomma)
static void setSysTime (const n_u::UTime &tgps) throw (n_u::IOException)
Private Attributes
string device
int dataTimeout
int lockTimeout
int baudRate
int gpsOffsetUsecs
Static Private Attributes
static int dataTimeoutDefault = 30
static int lockTimeoutDefault = 600
static int clockDiffMaxSeconds = CLOCK_DIFF_MAX_DEFAULT
If the difference between the GPS and system clock is more than this, set the system clock from the GPS.
Constructor & Destructor Documentation
GPS_SetClock()
GPS_SetClock::GPS_SetClock ()
Member Function Documentation
parseRunstring()
int GPS_SetClock::parseRunstring (int argc, char ** argv)
References baudRate, clockDiffMaxSeconds, dataTimeout, device, gpsOffsetUsecs, lockTimeout, usage(), and USECS_PER_SEC.
Referenced by main().
run()
int GPS_SetClock::run ()
References baudRate, clockDiffMaxSeconds, nidas::util::SerialPort::close(), dataTimeout, device, nidas::util::SerialPort::getFd(), nidas::util::SerialPort::getName(), gpsOffsetUsecs, nidas::util::Termios::iflag(), nidas::util::Termios::lflag(), lockTimeout, nidas::util::Termios::oflag(), nidas::util::SerialPort::open(), nidas::util::SerialPort::readLine(), nidas::util::Termios::setBaudRate(), setSysTime(), skipcommas(), nidas::util::SerialPort::termios(), USECS_PER_SEC, and nidas::util::Exception::what().
Referenced by main().
setSysTime()
void GPS_SetClock::setSysTime (const n_u::UTime & tgps) throw (n_u::IOException) static
References nidas::util::UTime::format(), MSECS_PER_SEC, nidas::util::UTime::toUsecs(), and USECS_PER_SEC.
Referenced by run().
skipcommas()
const char * GPS_SetClock::skipcommas (const char * cp, int ncomma) static
Referenced by run().
usage()
int GPS_SetClock::usage (const char * argv0) static
References CLOCK_DIFF_MAX_DEFAULT, dataTimeoutDefault, and lockTimeoutDefault.
Referenced by parseRunstring().
Member Data Documentation
baudRate
int GPS_SetClock::baudRate private
Referenced by parseRunstring(), and run().
clockDiffMaxSeconds
int GPS_SetClock::clockDiffMaxSeconds = CLOCK_DIFF_MAX_DEFAULT static private
If the difference between the GPS and system clock is more than this, set the system clock from the GPS.
Referenced by parseRunstring(), and run().
dataTimeout
int GPS_SetClock::dataTimeout private
Referenced by parseRunstring(), and run().
dataTimeoutDefault
int GPS_SetClock::dataTimeoutDefault = 30 static private
Referenced by usage().
device
string GPS_SetClock::device private
Referenced by parseRunstring(), and run().
gpsOffsetUsecs
int GPS_SetClock::gpsOffsetUsecs private
Referenced by parseRunstring(), and run().
lockTimeout
int GPS_SetClock::lockTimeout private
Referenced by parseRunstring(), and run().
lockTimeoutDefault
int GPS_SetClock::lockTimeoutDefault = 600 static private
Referenced by usage().
The documentation for this class was generated from the following file:
nidas/apps/gps_nmea_sysclock.cc