nidas: nidas::core::SampleClock Class Reference
nidas::core::SampleClock Class Reference
SampleClock adds date information to sample time tags.
#include <SampleClock.h>
Public Types
enum status_t { NO_CLOCK , OUT_OF_SPEC , OK }
Enumeration of the result of addSampleDate().
Public Member Functions
SampleClock ()
Constructor.
void setMaxClockDiff (int val)
void setTime ()
Update the SampleClock from the UNIX OS clock.
status_t addSampleDate (Sample *samp)
Add date information to a sample time tag.
Static Public Member Functions
static SampleClock * getInstance ()
Private Attributes
int _maxClockDiffSec
dsm_time_t _t0day
dsm_time_t _clockTime
Static Private Attributes
static SampleClock * _instance = new SampleClock()
Detailed Description
SampleClock adds date information to sample time tags.
Sample timetags from the various NIDAS driver modules are only timetagged with the time since 00:00 GMT of the current day. SampleClock adds the day offset to the timetags, so that they are an absolute time.
Member Enumeration Documentation
status_t
enum nidas::core::SampleClock::status_t
Enumeration of the result of addSampleDate().
Enumerator
NO_CLOCK
OUT_OF_SPEC
OK
Constructor & Destructor Documentation
SampleClock()
SampleClock::SampleClock ()
Constructor.
References _clockTime, _t0day, nidas::util::getSystemTime(), nidas::util::timeFloor(), and USECS_PER_DAY.
Member Function Documentation
addSampleDate()
SampleClock::status_t SampleClock::addSampleDate (Sample * samp)
Add date information to a sample time tag.
Parameters
samp A Sample, whose timetag value is a relative time in microseconds since 00:00 GMT.
Returns
Enumeration of time tag status: NO_CLOCK: we don't have absolute time information yet, sample time tag is not valid, OUT_OF_SPEC: sample time differs from absolute time, by more than maxClockDiff, sample time tag is not valid, OK: good sample time.
References _clockTime, _maxClockDiffSec, _t0day, nidas::util::UTime::format(), GET_DSM_ID, GET_SHORT_ID, nidas::core::Sample::getId(), nidas::util::Logger::getInstance(), nidas::util::getSystemTime(), nidas::core::Sample::getTimeTag(), nidas::util::Logger::log(), LOG_DEBUG, OK, OUT_OF_SPEC, SECS_PER_DAY, setTime(), nidas::core::Sample::setTimeTag(), USECS_PER_DAY, and USECS_PER_SEC.
Referenced by nidas::core::DriverSampleScanner::nextSample().
getInstance()
static SampleClock* nidas::core::SampleClock::getInstance () inline static
References _instance.
Referenced by nidas::core::DriverSampleScanner::nextSample().
setMaxClockDiff()
void nidas::core::SampleClock::setMaxClockDiff (int val) inline
Parameters
val A check for reasonable sample times (seconds). If the sample time differs from the clock source time (as set by setTime) by more than maxClockDiff, then the state is set to OUT_OF_SPEC.
References _maxClockDiffSec.
setTime()
void SampleClock::setTime ()
Update the SampleClock from the UNIX OS clock.
References _clockTime, _t0day, nidas::util::getSystemTime(), nidas::util::timeFloor(), and USECS_PER_DAY.
Referenced by addSampleDate().
Member Data Documentation
_clockTime
dsm_time_t nidas::core::SampleClock::_clockTime private
Referenced by addSampleDate(), SampleClock(), and setTime().
_instance
SampleClock * SampleClock::_instance = new SampleClock() static private
Referenced by getInstance().
_maxClockDiffSec
int nidas::core::SampleClock::_maxClockDiffSec private
Referenced by addSampleDate(), and setMaxClockDiff().
_t0day
dsm_time_t nidas::core::SampleClock::_t0day private
Referenced by addSampleDate(), SampleClock(), and setTime().
The documentation for this class was generated from the following files:
nidas/core/SampleClock.h
nidas/core/SampleClock.cc