nidas: SampleDispatcher Class Reference
SampleDispatcher Class Reference
Public Member Functions
SampleDispatcher (InfluxDB *db, const list< DSMSensor * > &sensors, NidasApp &app)
virtual ~SampleDispatcher ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
Private Types
typedef map< dsm_sample_id_t, SampleToDatabase > sample_map_t
Private Member Functions
sample_map_t::iterator findStats (dsm_sample_id_t sampid)
Find the SampleToDatabase for the given sample ID.
Private Attributes
sample_map_t _samples
NidasApp & _app
Member Typedef Documentation
sample_map_t
typedef map<dsm_sample_id_t, SampleToDatabase> SampleDispatcher::sample_map_t private
Constructor & Destructor Documentation
SampleDispatcher()
SampleDispatcher::SampleDispatcher (InfluxDB * db, const list< DSMSensor * > & sensors, NidasApp & app)
References _app, _samples, DLOG, findStats(), nidas::core::NidasApp::formatId(), nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariables(), nidas::core::SampleTagIterator::hasNext(), SampleToDatabase::id, nidas::core::SampleMatcher::match(), nidas::core::SampleTagIterator::next(), and nidas::core::NidasApp::sampleMatcher().
~SampleDispatcher()
virtual SampleDispatcher::~SampleDispatcher () inline virtual
Member Function Documentation
findStats()
sample_map_t::iterator SampleDispatcher::findStats (dsm_sample_id_t sampid) inline private
Find the SampleToDatabase for the given sample ID.
Wisard samples get mapped to one sensor type, so we look for all of them.
References VLOG.
Referenced by SampleDispatcher().
flush()
void SampleDispatcher::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implements nidas::core::SampleClient.
receive()
bool SampleDispatcher::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References DLOG, VLOG, and WLOG.
Member Data Documentation
_app
NidasApp& SampleDispatcher::_app private
Referenced by SampleDispatcher().
_samples
sample_map_t SampleDispatcher::_samples private
Referenced by SampleDispatcher().
The documentation for this class was generated from the following file:
nidas/apps/data_influxdb.cc