nidas: nidas::core::XMLConfigWriterFilter Class Reference
nidas::core::XMLConfigWriterFilter Class Reference
#include <XMLConfigWriter.h>
Public Member Functions
XMLConfigWriterFilter (const DSMConfig *dsm)
Only accept nodes for a certain dsm.
short acceptNode (const xercesc::DOMNode *node) const
unsigned long getWhatToShow () const
void setWhatToShow (unsigned long val)
Private Member Functions
short acceptDSMNode (const xercesc::DOMNode *node) const
XMLConfigWriterFilter (const XMLConfigWriterFilter &)
No copying.
XMLConfigWriterFilter & operator= (const XMLConfigWriterFilter &)
No assignment.
Private Attributes
const DSMConfig * _dsm
unsigned long _whatToShow
Constructor & Destructor Documentation
XMLConfigWriterFilter() [1/2]
XMLConfigWriterFilter::XMLConfigWriterFilter (const DSMConfig * dsm)
Only accept nodes for a certain dsm.
XMLConfigWriterFilter() [2/2]
nidas::core::XMLConfigWriterFilter::XMLConfigWriterFilter (const XMLConfigWriterFilter &) private
No copying.
Member Function Documentation
acceptDSMNode()
short XMLConfigWriterFilter::acceptDSMNode (const xercesc::DOMNode * node) const private
References _dsm, nidas::core::Project::expandString(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMConfig::getName(), nidas::core::XDOMElement::getNodeName(), and nidas::core::DSMConfig::getProject().
Referenced by acceptNode().
acceptNode()
short XMLConfigWriterFilter::acceptNode (const xercesc::DOMNode * node) const
References acceptDSMNode(), nidas::core::XDOMElement::getNodeName(), and getWhatToShow().
getWhatToShow()
unsigned long XMLConfigWriterFilter::getWhatToShow () const
References _whatToShow.
Referenced by acceptNode().
operator=()
XMLConfigWriterFilter& nidas::core::XMLConfigWriterFilter::operator= (const XMLConfigWriterFilter &) private
No assignment.
setWhatToShow()
void XMLConfigWriterFilter::setWhatToShow (unsigned long val)
References _whatToShow.
Member Data Documentation
_dsm
const DSMConfig* nidas::core::XMLConfigWriterFilter::_dsm private
Referenced by acceptDSMNode().
_whatToShow
unsigned long nidas::core::XMLConfigWriterFilter::_whatToShow private
Referenced by getWhatToShow(), and setWhatToShow().
The documentation for this class was generated from the following files:
nidas/core/XMLConfigWriter.h
nidas/core/XMLConfigWriter.cc