nidas: ublox_pkt Class Reference
ublox_pkt Class Reference
Public Member Functions
ublox_pkt (uint8_t uclass, uint8_t id, uint16_t paylen)
ublox_pkt (uint16_t paylen)
~ublox_pkt ()
uint8_t sync1 () const
uint8_t sync2 () const
uint8_t uclass () const
uint8_t id () const
uint8_t * payload () const
void payload (void *ptr)
int16_t len () const
char * beginp () const
char * endp () const
int16_t paylen () const
uint8_t * cksump () const
void cksum ()
Private Member Functions
ublox_pkt (const ublox_pkt &)
ublox_pkt & operator= (const ublox_pkt &)
Private Attributes
int16_t _paylen
uint8_t * _pkt
Constructor & Destructor Documentation
ublox_pkt() [1/3]
ublox_pkt::ublox_pkt (uint8_t uclass, uint8_t id, uint16_t paylen)
References _paylen, _pkt, id(), len(), and uclass().
ublox_pkt() [2/3]
ublox_pkt::ublox_pkt (uint16_t paylen)
References _pkt, and len().
~ublox_pkt()
ublox_pkt::~ublox_pkt ()
References _pkt.
ublox_pkt() [3/3]
ublox_pkt::ublox_pkt (const ublox_pkt &) private
Member Function Documentation
beginp()
char* ublox_pkt::beginp () const inline
Referenced by ublox::write_rdwr().
cksum()
void ublox_pkt::cksum ()
References _pkt, and cksump().
Referenced by ublox::config_nmea(), ublox::config_nmea_all_targets(), ublox::config_port(), ublox::reset(), and ublox::set_rate().
cksump()
uint8_t* ublox_pkt::cksump () const inline
Referenced by cksum().
endp()
char* ublox_pkt::endp () const inline
References len.
id()
uint8_t ublox_pkt::id () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
len()
int16_t ublox_pkt::len () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
operator=()
ublox_pkt& ublox_pkt::operator= (const ublox_pkt &) private
paylen()
int16_t ublox_pkt::paylen () const inline
payload() [1/2]
uint8_t* ublox_pkt::payload () const inline
Referenced by ublox::config_nmea(), ublox::config_nmea_all_targets(), ublox::config_port(), ublox::reset(), ublox::set_rate(), and ublox::write_rdwr().
payload() [2/2]
void ublox_pkt::payload (void * ptr) inline
References payload().
Referenced by payload().
sync1()
uint8_t ublox_pkt::sync1 () const inline
Referenced by ublox::write_rdwr().
sync2()
uint8_t ublox_pkt::sync2 () const inline
Referenced by ublox::write_rdwr().
uclass()
uint8_t ublox_pkt::uclass () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
Member Data Documentation
_paylen
int16_t ublox_pkt::_paylen private
Referenced by ublox_pkt().
_pkt
uint8_t* ublox_pkt::_pkt private
Referenced by cksum(), ublox_pkt(), and ~ublox_pkt().
The documentation for this class was generated from the following file:
nidas/apps/ublox.cc