nidas: nidas::util::DatagramPacketBase Class Reference
nidas::util::DatagramPacketBase Class Reference abstract
Abstract base class for a UDP datagram.
#include <DatagramPacket.h>
Public Member Functions
DatagramPacketBase (int l)
Create a DatagramPacketBase for receiving.
DatagramPacketBase (int l, const Inet4Address &add, int port)
Create a DatagramPacketBase for sending.
DatagramPacketBase (int l, const SocketAddress &add)
DatagramPacketBase (const DatagramPacketBase &x)
Copy constructor.
DatagramPacketBase & operator= (const DatagramPacketBase &rhs)
Assignment operator.
virtual ~DatagramPacketBase ()
Virtual destructor.
SocketAddress & getSocketAddress () const
void setSocketAddress (const SocketAddress &val)
struct sockaddr * getSockAddrPtr ()
const struct sockaddr * getConstSockAddrPtr () const
int getSockAddrLen () const
virtual void * getDataVoidPtr ()=0
Get the pointer to the data portion of the packet.
virtual const void * getConstDataVoidPtr () const =0
virtual void setLength (int val)
Set the value for the current number of bytes in data.
virtual int getLength () const
Get the value for the current number of bytes in data.
void setMaxLength (int val)
Set the allocated length in bytes of the data.
int getMaxLength () const
Return the allocated length in bytes of the data.
Protected Attributes
int maxlength
allocated length in bytes of contents.
int length
length of datagram that was read or will be sent.
SocketAddress * addr
The destination address for a send, or the remote senders address after a receive.
Detailed Description
Abstract base class for a UDP datagram.
Patterned after java.net.DatagramPacket.
Constructor & Destructor Documentation
DatagramPacketBase() [1/4]
nidas::util::DatagramPacketBase::DatagramPacketBase (int l) inline
Create a DatagramPacketBase for receiving.
Parameters
buf allocated space for contents. Pointer is owned by caller, not by the DatagramPacketBase - the DatagramPacketBase destructor does not delete it in its destructor.
length length of allocated space.
DatagramPacketBase() [2/4]
nidas::util::DatagramPacketBase::DatagramPacketBase (int l, const Inet4Address & add, int port) inline
Create a DatagramPacketBase for sending.
Parameters
buf allocated space for contents. Pointer is owned by caller, not by the DatagramPacketBase - the DatagramPacketBase destructor does not delete it in its destructor.
length length of allocated space. @add Inet4Address to send packet to. @port port number to send packet to.
DatagramPacketBase() [3/4]
nidas::util::DatagramPacketBase::DatagramPacketBase (int l, const SocketAddress & add) inline
DatagramPacketBase() [4/4]
nidas::util::DatagramPacketBase::DatagramPacketBase (const DatagramPacketBase & x) inline
Copy constructor.
~DatagramPacketBase()
virtual nidas::util::DatagramPacketBase::~DatagramPacketBase () inline virtual
Virtual destructor.
References addr.
Member Function Documentation
getConstDataVoidPtr()
virtual const void* nidas::util::DatagramPacketBase::getConstDataVoidPtr () const pure virtual
Implemented in nidas::util::DatagramPacketT< DataT >, nidas::util::DatagramPacketT< McSocketData >, and nidas::util::DatagramPacketT< char >.
Referenced by nidas::util::SocketImpl::send().
getConstSockAddrPtr()
const struct sockaddr* nidas::util::DatagramPacketBase::getConstSockAddrPtr () const inline
References addr, and nidas::util::SocketAddress::getConstSockAddrPtr().
Referenced by nidas::util::SocketImpl::send().
getDataVoidPtr()
virtual void* nidas::util::DatagramPacketBase::getDataVoidPtr () pure virtual
Get the pointer to the data portion of the packet.
Implemented in nidas::util::DatagramPacketT< DataT >, nidas::util::DatagramPacketT< McSocketData >, and nidas::util::DatagramPacketT< char >.
Referenced by nidas::util::SocketImpl::receive().
getLength()
virtual int nidas::util::DatagramPacketBase::getLength () const inline virtual
Get the value for the current number of bytes in data.
Either the number of bytes read in a received packet, or the number of bytes to send().
References length.
Referenced by PacketReader::checkPacket(), PacketReader::logBadPacket(), PacketReader::loop(), WriterThread::run(), nidas::core::DerivedDataReader::run(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
getMaxLength()
int nidas::util::DatagramPacketBase::getMaxLength () const inline
Return the allocated length in bytes of the data.
References maxlength.
Referenced by PacketReader::loop(), and nidas::util::SocketImpl::receive().
getSockAddrLen()
int nidas::util::DatagramPacketBase::getSockAddrLen () const inline
References addr, and nidas::util::SocketAddress::getSockAddrLen().
Referenced by nidas::util::SocketImpl::receive(), and nidas::util::SocketImpl::send().
getSockAddrPtr()
struct sockaddr* nidas::util::DatagramPacketBase::getSockAddrPtr () inline
References addr, and nidas::util::SocketAddress::getSockAddrPtr().
Referenced by nidas::util::SocketImpl::receive().
getSocketAddress()
SocketAddress& nidas::util::DatagramPacketBase::getSocketAddress () const inline
References addr.
Referenced by PacketReader::logBadPacket(), PacketReader::loop(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
operator=()
DatagramPacketBase& nidas::util::DatagramPacketBase::operator= (const DatagramPacketBase & rhs) inline
Assignment operator.
References addr, nidas::util::SocketAddress::clone(), length, and maxlength.
setLength()
virtual void nidas::util::DatagramPacketBase::setLength (int val) inline virtual
Set the value for the current number of bytes in data.
/param val Number of bytes, must be <= max length.
References length.
Referenced by PacketReader::checkPacket(), and nidas::util::SocketImpl::receive().
setMaxLength()
void nidas::util::DatagramPacketBase::setMaxLength (int val) inline
Set the allocated length in bytes of the data.
/param val Number of bytes allocated in data.
References maxlength.
setSocketAddress()
void nidas::util::DatagramPacketBase::setSocketAddress (const SocketAddress & val) inline
References addr, and nidas::util::SocketAddress::clone().
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
Member Data Documentation
addr
SocketAddress* nidas::util::DatagramPacketBase::addr protected
The destination address for a send, or the remote senders address after a receive.
Referenced by getConstSockAddrPtr(), getSockAddrLen(), getSockAddrPtr(), getSocketAddress(), operator=(), setSocketAddress(), and ~DatagramPacketBase().
length
int nidas::util::DatagramPacketBase::length protected
length of datagram that was read or will be sent.
Must be <= maxlength.
Referenced by getLength(), operator=(), and setLength().
maxlength
int nidas::util::DatagramPacketBase::maxlength protected
allocated length in bytes of contents.
Referenced by getMaxLength(), operator=(), and setMaxLength().
The documentation for this class was generated from the following file:
nidas/util/DatagramPacket.h