nidas: nidas::core::SensorCatalog Class Reference
nidas::core::SensorCatalog Class Reference
A catalog of sensor DOMElements, implemented with std::map, containing sensor DOMElements, keyed by the ID attributes.
#include <SensorCatalog.h>
Public Member Functions
SensorCatalog ()
SensorCatalog (const SensorCatalog &)
~SensorCatalog ()
SensorCatalog & operator= (const SensorCatalog &)
xercesc::DOMElement *& operator[] (const std::string &id)
const xercesc::DOMElement * find (const std::string &id) const
void fromDOMElement (const xercesc::DOMElement *)
Build this SensorCatalog from a catalog element.
const std::map< std::string, xercesc::DOMElement * > & getMap () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Private Attributes
std::map< std::string, xercesc::DOMElement * > _sensors
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
A catalog of sensor DOMElements, implemented with std::map, containing sensor DOMElements, keyed by the ID attributes.
Constructor & Destructor Documentation
SensorCatalog() [1/2]
SensorCatalog::SensorCatalog ()
SensorCatalog() [2/2]
SensorCatalog::SensorCatalog (const SensorCatalog & x)
~SensorCatalog()
SensorCatalog::~SensorCatalog ()
Member Function Documentation
find()
const xercesc::DOMElement * SensorCatalog::find (const std::string & id) const
References _sensors.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::DSMSensor::getClassName().
fromDOMElement()
void SensorCatalog::fromDOMElement (const xercesc::DOMElement * node) virtual
Build this SensorCatalog from a catalog element.
The SensorCatalog does not own the DOM elements.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References _sensors, nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::Project::fromDOMElement().
getMap()
const std::map<std::string,xercesc::DOMElement*>& nidas::core::SensorCatalog::getMap () const inline
References _sensors.
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
operator=()
SensorCatalog & SensorCatalog::operator= (const SensorCatalog & rhs)
References _sensors.
operator[]()
xercesc::DOMElement*& nidas::core::SensorCatalog::operator[] (const std::string & id) inline
References _sensors.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_sensors
std::map<std::string,xercesc::DOMElement*> nidas::core::SensorCatalog::_sensors private
Referenced by find(), fromDOMElement(), getMap(), operator=(), and operator[]().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/SensorCatalog.h
nidas/core/SensorCatalog.cc