nidas: nidas/apps/viper_dio.cc File Reference
viper_dio.cc File Reference
#include <iostream>
#include <nidas/dynld/ViperDIO.h>
Functions
static int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::BitArray::getBit(), nidas::dynld::ViperDIO::getNumOutputs(), nidas::dynld::ViperDIO::getOutputs(), nidas::dynld::ViperDIO::open(), nidas::util::BitArray::setBit(), nidas::dynld::ViperDIO::setDeviceName(), nidas::dynld::ViperDIO::setOutputs(), and usage().
usage()
static int usage (const char * argv0) static
Referenced by main().