nidas: SensorExtract Class Reference
SensorExtract Class Reference
Public Member Functions
SensorExtract ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
void sendHeader (dsm_time_t, SampleOutput *)
Method called to write a header to an SampleOutput.
void printHeader ()
for debugging.
Static Public Member Functions
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
static int main (int argc, char **argv) throw ()
static int usage (const char *argv0)
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Private Attributes
list< string > inputFileNames
n_u::auto_ptr< n_u::SocketAddress > sockAddr
string outputFileName
int outputFileLength
SampleInputHeader header
set< dsm_sample_id_t > includeIds
set< dsm_sample_id_t > includeDSMIds
set< dsm_sample_id_t > excludeIds
set< int > excludeDSMIds
map< dsm_sample_id_t, dsm_sample_id_t > newIds
map< int, int > newDSMIds
Static Private Attributes
static bool interrupted = false
Constructor & Destructor Documentation
SensorExtract()
SensorExtract::SensorExtract ()
Member Function Documentation
main()
int SensorExtract::main (int argc, char ** argv) throw () static
References parseRunstring(), run(), and setupSignals().
Referenced by main().
parseRunstring()
int SensorExtract::parseRunstring (int argc, char ** argv) throw ()
References nidas::util::Inet4Address::getByName(), NIDAS_RAW_DATA_PORT_TCP, port, SET_DSM_ID, SET_SPS_ID, usage(), and nidas::util::Exception::what().
Referenced by main().
printHeader()
void SensorExtract::printHeader ()
for debugging.
References nidas::core::SampleInputHeader::getArchiveVersion(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::SampleInputHeader::getConfigVersion(), nidas::core::SampleInputHeader::getProjectName(), nidas::core::SampleInputHeader::getSoftwareVersion(), nidas::core::SampleInputHeader::getSystemName(), and header.
Referenced by sendHeader().
run()
int SensorExtract::run () throw ()
References nidas::dynld::SampleOutputStream::close(), excludeDSMIds, excludeIds, nidas::dynld::SampleOutputStream::flush(), nidas::core::Sample::freeReference(), GET_DSM_ID, nidas::core::FileSet::getFileSet(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::util::Logger::getInstance(), nidas::core::Sample::getTimeTag(), header, includeDSMIds, includeIds, inputFileNames, interrupted, nidas::util::Logger::log(), LOG_WARNING, newDSMIds, newIds, outputFileLength, outputFileName, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSample(), nidas::dynld::SampleOutputStream::receive(), SET_DSM_ID, nidas::core::FileSet::setFileLengthSecs(), nidas::core::FileSet::setFileName(), nidas::core::SampleOutputBase::setHeaderSource(), nidas::core::Sample::setId(), nidas::dynld::SampleInputStream::setMaxSampleLength(), sockAddr, nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
Referenced by main().
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
sendHeader()
void SensorExtract::sendHeader (dsm_time_t , SampleOutput * output) virtual
Method called to write a header to an SampleOutput.
Derived classes implement as they see fit.
Exceptions
nidas::util::IOException
Implements nidas::core::HeaderSource.
References header, printHeader(), and nidas::core::SampleInputHeader::write().
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
setupSignals()
void SensorExtract::setupSignals () static
References sigAction().
sigAction()
void SensorExtract::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
Referenced by setupSignals().
usage()
int SensorExtract::usage (const char * argv0) static
References NIDAS_RAW_DATA_PORT_TCP.
Member Data Documentation
excludeDSMIds
set<int> SensorExtract::excludeDSMIds private
Referenced by run().
excludeIds
set<dsm_sample_id_t> SensorExtract::excludeIds private
Referenced by run().
header
SampleInputHeader SensorExtract::header private
Referenced by printHeader(), run(), and sendHeader().
includeDSMIds
set<dsm_sample_id_t> SensorExtract::includeDSMIds private
Referenced by run().
includeIds
set<dsm_sample_id_t> SensorExtract::includeIds private
Referenced by run().
inputFileNames
list<string> SensorExtract::inputFileNames private
Referenced by run().
interrupted
bool SensorExtract::interrupted = false static private
Referenced by run(), and sigAction().
newDSMIds
map<int,int> SensorExtract::newDSMIds private
Referenced by run().
newIds
map<dsm_sample_id_t,dsm_sample_id_t> SensorExtract::newIds private
Referenced by run().
outputFileLength
int SensorExtract::outputFileLength private
Referenced by run().
outputFileName
string SensorExtract::outputFileName private
Referenced by run().
sockAddr
n_u::auto_ptr<n_u::SocketAddress> SensorExtract::sockAddr private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/sensor_extract.cc