nidas: nidas::core::DSMService Class Reference
nidas::core::DSMService Class Reference abstract
Base class for a service, as built from a <service> XML tag.
#include <DSMService.h>
Public Member Functions
DSMService (const std::string &name)
Constructor.
virtual ~DSMService ()
const std::string & getName () const
virtual void setDSMServer (DSMServer *val)
virtual DSMServer * getDSMServer () const
virtual void connect (SampleInput *)=0 throw ()
virtual void addProcessor (SampleIOProcessor *proc)
Add a processor to this RawSampleService.
virtual const std::list< SampleIOProcessor * > & getProcessors () const
const std::list< SampleInput * > & getInputs () const
ProcessorIterator getProcessorIterator () const
virtual void schedule (bool optionalProcessing)=0
schedule this service to run.
virtual int checkSubThreads () throw ()
virtual void cancel () throw ()
virtual void interrupt () throw ()
virtual int join () throw ()
void fromDOMElement (const xercesc::DOMElement *node)
nidas::util::Thread::SchedPolicy getSchedPolicy () const
int getSchedPriority () const
virtual void printClock (std::ostream &) throw ()
virtual void printStatus (std::ostream &, float) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void addSubThread (nidas::util::Thread *) throw ()
Protected Attributes
std::string _name
DSMServer * _server
std::set< nidas::util::Thread * > _subThreads
nidas::util::Mutex _subThreadMutex
std::list< SampleInput * > _inputs
std::list< SampleIOProcessor * > _processors
std::list< IOChannel * > _ochans
nidas::util::Thread::SchedPolicy _threadPolicy
int _threadPriority
Private Member Functions
DSMService (const DSMService &x)
Copying not supported.
DSMService & operator= (const DSMService &x)
Assignment not supported.
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Base class for a service, as built from a <service> XML tag.
Constructor & Destructor Documentation
DSMService() [1/2]
DSMService::DSMService (const std::string & name)
Constructor.
~DSMService()
DSMService::~DSMService () virtual
References _inputs, _ochans, _processors, nidas::core::IOChannel::close(), and nidas::core::SampleInput::close().
DSMService() [2/2]
nidas::core::DSMService::DSMService (const DSMService & x) private
Copying not supported.
Member Function Documentation
addProcessor()
virtual void nidas::core::DSMService::addProcessor (SampleIOProcessor * proc) inline virtual
Add a processor to this RawSampleService.
This is done at configuration (XML) time.
References _processors.
Referenced by fromDOMElement().
addSubThread()
void DSMService::addSubThread (nidas::util::Thread * thd) throw () protected
cancel()
void DSMService::cancel () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Thread::cancel(), nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
checkSubThreads()
int DSMService::checkSubThreads () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
connect()
virtual void nidas::core::DSMService::connect (SampleInput *) throw () pure virtual
Implemented in nidas::dynld::XMLConfigService, and nidas::dynld::RawSampleService.
fromDOMElement()
void DSMService::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::RawSampleService.
References _inputs, _ochans, _threadPolicy, _threadPriority, addProcessor(), nidas::core::IOChannel::createIOChannel(), nidas::core::DOMObjectFactory::createObject(), nidas::core::ServiceCatalog::find(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), getDSMServer(), nidas::util::Logger::getInstance(), getName(), nidas::core::Project::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::DSMServer::getProject(), nidas::core::Project::getServiceCatalog(), nidas::core::XDOMAttr::getValue(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_RR, nidas::core::SampleIOProcessor::setService(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::fromDOMElement(), and nidas::dynld::RawSampleService::fromDOMElement().
getClassName()
const string DSMService::getClassName (const xercesc::DOMElement * node, const Project * project) static
Exceptions
nidas::util::InvalidParameterException
References nidas::core::ServiceCatalog::find(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::Project::getServiceCatalog().
Referenced by nidas::core::DSMServer::fromDOMElement().
getDSMServer()
virtual DSMServer* nidas::core::DSMService::getDSMServer () const inline virtual
References _server.
Referenced by fromDOMElement(), and nidas::dynld::RawSampleService::fromDOMElement().
getInputs()
const std::list<SampleInput*>& nidas::core::DSMService::getInputs () const inline
References _inputs.
getName()
const std::string& nidas::core::DSMService::getName () const inline
References _name.
Referenced by fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::DSMServer::joinServices(), and nidas::core::DSMServer::~DSMServer().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getProcessorIterator()
ProcessorIterator DSMService::getProcessorIterator () const
Referenced by nidas::dynld::RawSampleService::printStatus().
getProcessors()
virtual const std::list<SampleIOProcessor*>& nidas::core::DSMService::getProcessors () const inline virtual
References _processors.
Referenced by nidas::core::ProcessorIterator::hasNext().
getSchedPolicy()
nidas::util::Thread::SchedPolicy nidas::core::DSMService::getSchedPolicy () const inline
References _threadPolicy.
getSchedPriority()
int nidas::core::DSMService::getSchedPriority () const inline
References _threadPriority.
interrupt()
void DSMService::interrupt () throw () virtual
Reimplemented in nidas::dynld::XMLConfigService, and nidas::dynld::RawSampleService.
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::interrupt(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Referenced by nidas::dynld::RawSampleService::interrupt(), nidas::dynld::XMLConfigService::interrupt(), and nidas::core::DSMServer::interruptServices().
join()
int DSMService::join () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, nidas::util::Thread::RUN_OK, and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::joinServices(), and nidas::dynld::RawSampleService::~RawSampleService().
operator=()
DSMService& nidas::core::DSMService::operator= (const DSMService & x) private
Assignment not supported.
printClock()
virtual void nidas::core::DSMService::printClock (std::ostream &) throw () inline virtual
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
printStatus()
virtual void nidas::core::DSMService::printStatus (std::ostream & , float) throw () inline virtual
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
schedule()
virtual void nidas::core::DSMService::schedule (bool optionalProcessing) pure virtual
schedule this service to run.
Exceptions
nidas::util::Exception
Implemented in nidas::dynld::XMLConfigService, and nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServer::scheduleServices().
setDSMServer()
void DSMService::setDSMServer (DSMServer * val) virtual
References _server.
Referenced by nidas::core::DSMServer::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_inputs
std::list<SampleInput*> nidas::core::DSMService::_inputs protected
Referenced by fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), getInputs(), and ~DSMService().
_name
std::string nidas::core::DSMService::_name protected
Referenced by getName().
_ochans
std::list<IOChannel*> nidas::core::DSMService::_ochans protected
Referenced by fromDOMElement(), and ~DSMService().
_processors
std::list<SampleIOProcessor*> nidas::core::DSMService::_processors protected
Referenced by addProcessor(), getProcessors(), and ~DSMService().
_server
DSMServer* nidas::core::DSMService::_server protected
Referenced by getDSMServer(), and setDSMServer().
_subThreadMutex
nidas::util::Mutex nidas::core::DSMService::_subThreadMutex protected
Referenced by cancel(), checkSubThreads(), interrupt(), and join().
_subThreads
std::set<nidas::util::Thread*> nidas::core::DSMService::_subThreads protected
Referenced by cancel(), checkSubThreads(), interrupt(), and join().
_threadPolicy
nidas::util::Thread::SchedPolicy nidas::core::DSMService::_threadPolicy protected
Referenced by fromDOMElement(), and getSchedPolicy().
_threadPriority
int nidas::core::DSMService::_threadPriority protected
Referenced by fromDOMElement(), and getSchedPriority().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/DSMService.h
nidas/core/DSMService.cc