nidas: nidas::core::DSMServiceIterator Class Reference
nidas::core::DSMServiceIterator Class Reference
Class for iterating over the DSMServices of a DSMServer.
#include <NidsIterators.h>
Public Member Functions
DSMServiceIterator (const Project *)
DSMServiceIterator (const Site *)
DSMServiceIterator (const DSMServer *)
DSMServiceIterator ()
bool hasNext ()
DSMService * next ()
Private Attributes
DSMServerIterator _dsmServerIterator
const std::list< DSMService * > * _services
std::list< DSMService * >::const_iterator _dsmServiceItr
Detailed Description
Class for iterating over the DSMServices of a DSMServer.
Constructor & Destructor Documentation
DSMServiceIterator() [1/4]
DSMServiceIterator::DSMServiceIterator (const Project * obj)
DSMServiceIterator() [2/4]
DSMServiceIterator::DSMServiceIterator (const Site * obj)
DSMServiceIterator() [3/4]
DSMServiceIterator::DSMServiceIterator (const DSMServer * obj)
DSMServiceIterator() [4/4]
DSMServiceIterator::DSMServiceIterator ()
Member Function Documentation
hasNext()
bool DSMServiceIterator::hasNext ()
References _dsmServerIterator, _dsmServiceItr, _services, nidas::core::DSMServer::getServices(), nidas::core::DSMServerIterator::hasNext(), and nidas::core::DSMServerIterator::next().
Referenced by nidas::core::ProcessorIterator::hasNext().
next()
DSMService* nidas::core::DSMServiceIterator::next () inline
References _dsmServiceItr.
Referenced by nidas::core::ProcessorIterator::hasNext().
Member Data Documentation
_dsmServerIterator
DSMServerIterator nidas::core::DSMServiceIterator::_dsmServerIterator private
Referenced by hasNext().
_dsmServiceItr
std::list<DSMService*>::const_iterator nidas::core::DSMServiceIterator::_dsmServiceItr private
Referenced by hasNext(), and next().
_services
const std::list<DSMService*>* nidas::core::DSMServiceIterator::_services private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc