nidas: nidas::core::SamplePipeline Class Reference
nidas::core::SamplePipeline Class Reference
SamplePipeline sorts samples that are coming from one or more inputs.
#include <SamplePipeline.h>
Public Member Functions
SamplePipeline ()
virtual ~SamplePipeline ()
std::string getName () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
void connect (SampleSource *src) throw ()
Add an input to be merged and sorted.
void disconnect (SampleSource *src) throw ()
Remove a SampleSource from the SamplePipeline.
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
What SampleTags am I a SampleSource for?
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *client) throw ()
Add a SampleClient that wants all processed samples.
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *, const SampleTag *) throw ()
Add a SampleClient that wants samples which have been merged from various inputs, sorted, processed through a certain DSMSensor, and then re-sorted again.
void removeSampleClientForTag (SampleClient *, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Purge samples from the SampleSorters in this pipeline.
void interrupt ()
Interrupt the SampleSorters in this pipeline.
void join () throw ()
Join the SampleSorters in this pipeline.
void setRealTime (bool val)
bool getRealTime () const
const SampleStats & getSampleStats () const
size_t getSorterNumRawSamples () const
Number of raw samples currently in the sorter.
size_t getSorterNumProcSamples () const
Number of processed samples currently in the sorter.
size_t getSorterNumRawBytes () const
Current size in bytes of the raw sample sorter.
size_t getSorterNumProcBytes () const
Current size in bytes of the processed sample sorter.
size_t getSorterNumRawBytesMax () const
Current size in bytes of the raw sample sorter.
size_t getSorterNumProcBytesMax () const
Current size in bytes of the processed sample sorter.
size_t getNumDiscardedRawSamples () const
Number of raw samples discarded because sorter was getting too big.
size_t getNumDiscardedProcSamples () const
Number of processed samples discarded because sorter was getting too big.
size_t getNumFutureRawSamples () const
Number of raw samples discarded because their timetags were in the future.
size_t getNumFutureProcSamples () const
Number of processed samples discarded because their timetags were in the future.
void setRawSorterLength (float val)
Set length of raw SampleSorter, in seconds.
float getRawSorterLength () const
void setProcSorterLength (float val)
Set length of processed SampleSorter, in seconds.
float getProcSorterLength () const
void setRawHeapMax (size_t val)
Set the maximum amount of heap memory to use for sorting samples.
size_t getRawHeapMax () const
void setProcHeapMax (size_t val)
Set the maximum amount of heap memory to use for sorting samples.
size_t getProcHeapMax () const
void setHeapBlock (bool val)
bool getHeapBlock () const
void setKeepStats (bool val)
void setRawLateSampleCacheSize (unsigned int val)
Get the size of the late sample cache in the raw sample sorter.
unsigned int getRawLateSampleCacheSize () const
Cache this number of samples with potentially anomalous, late time tags in the raw sample sorter.
void setProcLateSampleCacheSize (unsigned int val)
Get the size of the late sample cache in the processed sample sorter.
unsigned int getProcLateSampleCacheSize () const
Cache this number of samples with potentially anomalous, late time tags in the processed sample sorter.
Private Member Functions
void rawinit ()
void procinit ()
SamplePipeline (const SamplePipeline &x)
No copying.
SamplePipeline & operator= (const SamplePipeline &x)
No assignment.
Private Attributes
std::string _name
nidas::util::Mutex _rawMutex
SampleThread * _rawSorter
nidas::util::Mutex _procMutex
SampleThread * _procSorter
std::list< const SampleTag * > _sampleTags
std::list< const DSMConfig * > _dsmConfigs
bool _realTime
float _rawSorterLength
seconds
float _procSorterLength
seconds
size_t _rawHeapMax
size_t _procHeapMax
bool _heapBlock
bool _keepStats
unsigned int _rawLateSampleCacheSize
unsigned int _procLateSampleCacheSize
Detailed Description
SamplePipeline sorts samples that are coming from one or more inputs.
SamplePipeline makes use of two SampleSorters, one called rawSorter and procSorter.
rawSorter is a client of one or more inputs (the text arrows show the sample flow):
input -—v input --> _rawSorter input -—^
After sorting the samples, rawSorter passes them on to the two types of SampleClients that have registered with SamplePipeline. SampleClients that have registered with SamplePipeline::addSampleClient will receive their raw samples directly from rawSorter.
rawSorter -> sampleClients
SampleClients that have registered with SamplePipeline::addProcessedSampleClient will receive their samples indirectly:
rawSorter -> sensor -> procSorter -> processedSampleClients
rawSorter provides sorting of the samples from the various inputs.
procSorter provides sorting of the processed samples. DSMSensors are apt to create processed samples with different time-tags than the input raw samples, therefore they need to be sorted again.
Multiple threads can be passing samples to the sorters. Thread exclusion is enforced when passing the samples to the SampleClient::receive() methods from either sorter, so the SampleClient::receive() methods don't have to worry about being re-entrant.
Constructor & Destructor Documentation
SamplePipeline() [1/2]
SamplePipeline::SamplePipeline ()
~SamplePipeline()
SamplePipeline::~SamplePipeline () virtual
References _procMutex, _procSorter, _rawMutex, _rawSorter, nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
SamplePipeline() [2/2]
nidas::core::SamplePipeline::SamplePipeline (const SamplePipeline & x) private
No copying.
Member Function Documentation
addSampleClient()
void SamplePipeline::addSampleClient (SampleClient * client) throw () virtual
Add a SampleClient that wants all processed samples.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::addSampleClient(), nidas::core::SampleTag::getDSMSensor(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::getRawSampleTag(), and VLOG.
addSampleClientForTag()
void SamplePipeline::addSampleClientForTag (SampleClient * client, const SampleTag * stag) throw () virtual
Add a SampleClient that wants samples which have been merged from various inputs, sorted, processed through a certain DSMSensor, and then re-sorted again.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::addSampleClient(), nidas::core::DSMSensor::addSampleClientForTag(), and nidas::core::DSMSensor::getRawSampleTag().
addSampleTag()
void nidas::core::SamplePipeline::addSampleTag (const SampleTag *) throw () inline virtual
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::addSampleTag().
connect()
void SamplePipeline::connect (SampleSource * src) throw ()
Add an input to be merged and sorted.
SamplePipeline does not own the SampleSource.
References nidas::util::LogContext::active(), nidas::core::SampleSource::addSampleClient(), nidas::util::endlog(), GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getDSMSensor(), nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getName(), nidas::core::SampleSource::getRawSampleSource(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleSource::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), LOG_VERBOSE, and nidas::core::SampleTagIterator::next().
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
disconnect()
void SamplePipeline::disconnect (SampleSource * src) throw ()
Remove a SampleSource from the SamplePipeline.
References nidas::core::SampleTag::getDSMSensor(), nidas::core::SampleSource::getRawSampleSource(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleSource::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::SampleTagIterator::next(), and nidas::core::SampleSource::removeSampleClient().
Referenced by DataDump::run(), DataStats::run(), DataPrep::run(), StatsProcess::run(), and nidas::dynld::raf::SyncServer::stop().
flush()
void nidas::core::SamplePipeline::flush () throw () inline virtual
Purge samples from the SampleSorters in this pipeline.
This call will block, until both sorters are empty.
Implements nidas::core::SampleSource.
References _procSorter, _rawSorter, and nidas::core::SampleThread::flush().
Referenced by nidas::core::DSMEngine::interrupt(), nidas::dynld::raf::SyncServer::read(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
getClientCount()
int nidas::core::SamplePipeline::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::getClientCount().
getHeapBlock()
bool nidas::core::SamplePipeline::getHeapBlock () const inline
References _heapBlock.
Referenced by procinit(), and rawinit().
getName()
std::string nidas::core::SamplePipeline::getName () const inline
References _name.
getNumDiscardedProcSamples()
size_t nidas::core::SamplePipeline::getNumDiscardedProcSamples () const inline
Number of processed samples discarded because sorter was getting too big.
References _procSorter, and nidas::core::SampleThread::getNumDiscardedSamples().
Referenced by nidas::dynld::RawSampleService::printStatus().
getNumDiscardedRawSamples()
size_t nidas::core::SamplePipeline::getNumDiscardedRawSamples () const inline
Number of raw samples discarded because sorter was getting too big.
References _rawSorter, and nidas::core::SampleThread::getNumDiscardedSamples().
Referenced by nidas::dynld::RawSampleService::printStatus().
getNumFutureProcSamples()
size_t nidas::core::SamplePipeline::getNumFutureProcSamples () const inline
Number of processed samples discarded because their timetags were in the future.
References _procSorter, and nidas::core::SampleThread::getNumFutureSamples().
Referenced by nidas::dynld::RawSampleService::printStatus().
getNumFutureRawSamples()
size_t nidas::core::SamplePipeline::getNumFutureRawSamples () const inline
Number of raw samples discarded because their timetags were in the future.
References _rawSorter, and nidas::core::SampleThread::getNumFutureSamples().
Referenced by nidas::dynld::RawSampleService::printStatus().
getProcessedSampleSource()
SampleSource* nidas::core::SamplePipeline::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References procinit().
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::DSMEngine::connectOutputs(), nidas::dynld::raf::SyncServer::init(), nidas::dynld::RawSampleService::printStatus(), DataDump::run(), DataStats::run(), DataPrep::run(), StatsProcess::run(), and nidas::dynld::raf::SyncServer::stop().
getProcHeapMax()
size_t nidas::core::SamplePipeline::getProcHeapMax () const inline
References _procHeapMax.
Referenced by procinit().
getProcLateSampleCacheSize()
unsigned int nidas::core::SamplePipeline::getProcLateSampleCacheSize () const inline
Cache this number of samples with potentially anomalous, late time tags in the processed sample sorter.
See SampleSorter::setLateSampleCacheSize(val).
References _procLateSampleCacheSize.
Referenced by procinit().
getProcSorterLength()
float nidas::core::SamplePipeline::getProcSorterLength () const inline
References _procSorterLength.
Referenced by procinit().
getRawHeapMax()
size_t nidas::core::SamplePipeline::getRawHeapMax () const inline
References _rawHeapMax.
Referenced by rawinit().
getRawLateSampleCacheSize()
unsigned int nidas::core::SamplePipeline::getRawLateSampleCacheSize () const inline
Cache this number of samples with potentially anomalous, late time tags in the raw sample sorter.
See SampleSorter::setLateSampleCacheSize(val).
References _rawLateSampleCacheSize.
Referenced by rawinit().
getRawSampleSource()
SampleSource* nidas::core::SamplePipeline::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References _rawSorter, and rawinit().
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::DSMEngine::connectOutputs(), nidas::dynld::RawSampleService::printClock(), nidas::dynld::RawSampleService::printStatus(), and DataDump::run().
getRawSorterLength()
float nidas::core::SamplePipeline::getRawSorterLength () const inline
References _rawSorterLength.
Referenced by rawinit().
getRealTime()
bool nidas::core::SamplePipeline::getRealTime () const inline
References _realTime.
Referenced by procinit(), and rawinit().
getSampleStats()
const SampleStats& nidas::core::SamplePipeline::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::SamplePipeline::getSampleTagIterator () const inline virtual
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::SamplePipeline::getSampleTags () const inline virtual
What SampleTags am I a SampleSource for?
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::getSampleTags().
getSorterNumProcBytes()
size_t nidas::core::SamplePipeline::getSorterNumProcBytes () const inline
Current size in bytes of the processed sample sorter.
References _procSorter, and nidas::core::SampleThread::getHeapSize().
Referenced by nidas::dynld::RawSampleService::printStatus().
getSorterNumProcBytesMax()
size_t nidas::core::SamplePipeline::getSorterNumProcBytesMax () const inline
Current size in bytes of the processed sample sorter.
References _procSorter, and nidas::core::SampleThread::getHeapMax().
Referenced by nidas::dynld::RawSampleService::printStatus().
getSorterNumProcSamples()
size_t nidas::core::SamplePipeline::getSorterNumProcSamples () const inline
Number of processed samples currently in the sorter.
References _procSorter, and nidas::core::SampleThread::size().
Referenced by nidas::dynld::RawSampleService::printStatus().
getSorterNumRawBytes()
size_t nidas::core::SamplePipeline::getSorterNumRawBytes () const inline
Current size in bytes of the raw sample sorter.
References _rawSorter, and nidas::core::SampleThread::getHeapSize().
Referenced by nidas::dynld::RawSampleService::printStatus().
getSorterNumRawBytesMax()
size_t nidas::core::SamplePipeline::getSorterNumRawBytesMax () const inline
Current size in bytes of the raw sample sorter.
References _rawSorter, and nidas::core::SampleThread::getHeapMax().
Referenced by nidas::dynld::RawSampleService::printStatus().
getSorterNumRawSamples()
size_t nidas::core::SamplePipeline::getSorterNumRawSamples () const inline
Number of raw samples currently in the sorter.
References _rawSorter, and nidas::core::SampleThread::size().
Referenced by nidas::dynld::RawSampleService::printStatus().
interrupt()
void SamplePipeline::interrupt ()
Interrupt the SampleSorters in this pipeline.
References _procMutex, _procSorter, _rawMutex, _rawSorter, nidas::util::Thread::interrupt(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by nidas::core::DSMEngine::interrupt(), nidas::dynld::raf::SyncServer::interrupt(), DataDump::run(), DataStats::run(), DataPrep::run(), StatsProcess::run(), and nidas::dynld::raf::SyncServer::stop().
join()
void SamplePipeline::join () throw ()
Join the SampleSorters in this pipeline.
References _procMutex, _procSorter, _rawMutex, _rawSorter, nidas::util::Thread::getName(), nidas::util::Thread::interrupt(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Mutex::lock(), nidas::util::Mutex::unlock(), nidas::util::Exception::what(), and WLOG.
Referenced by nidas::core::DSMEngine::joinDataThreads(), DataDump::run(), DataStats::run(), DataPrep::run(), StatsProcess::run(), and nidas::dynld::raf::SyncServer::stop().
operator=()
SamplePipeline& nidas::core::SamplePipeline::operator= (const SamplePipeline & x) private
No assignment.
procinit()
void SamplePipeline::procinit () private
References _keepStats, _name, _procMutex, _procSorter, getHeapBlock(), nidas::core::SampleThread::getHeapMax(), nidas::core::SampleThread::getKeepStats(), nidas::core::SampleThread::getLengthSecs(), getProcHeapMax(), getProcLateSampleCacheSize(), getProcSorterLength(), getRealTime(), nidas::core::SampleThread::getRealTime(), nidas::core::SampleThread::setHeapBlock(), nidas::core::SampleThread::setHeapMax(), nidas::core::SampleThread::setKeepStats(), nidas::core::SampleThread::setLateSampleCacheSize(), nidas::core::SampleThread::setLengthSecs(), nidas::core::SampleThread::setRealTime(), nidas::util::Thread::setRealTimeFIFOPriority(), nidas::util::Thread::start(), and VLOG.
Referenced by getProcessedSampleSource().
rawinit()
void SamplePipeline::rawinit () private
References _keepStats, _name, _rawMutex, _rawSorter, getHeapBlock(), nidas::core::SampleThread::getHeapMax(), nidas::core::SampleThread::getKeepStats(), nidas::core::SampleThread::getLengthSecs(), getRawHeapMax(), getRawLateSampleCacheSize(), getRawSorterLength(), getRealTime(), nidas::core::SampleThread::getRealTime(), nidas::core::SampleThread::setHeapBlock(), nidas::core::SampleThread::setHeapMax(), nidas::core::SampleThread::setKeepStats(), nidas::core::SampleThread::setLateSampleCacheSize(), nidas::core::SampleThread::setLengthSecs(), nidas::core::SampleThread::setRealTime(), nidas::util::Thread::setRealTimeFIFOPriority(), nidas::util::Thread::start(), and VLOG.
Referenced by getRawSampleSource().
removeSampleClient()
void SamplePipeline::removeSampleClient (SampleClient * c) throw () virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References nidas::core::SampleTag::getDSMSensor(), nidas::core::DSMSensor::getRawSampleTag(), and nidas::core::DSMSensor::removeSampleClient().
removeSampleClientForTag()
void SamplePipeline::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMSensor::removeSampleClient(), and nidas::core::DSMSensor::removeSampleClientForTag().
removeSampleTag()
void nidas::core::SamplePipeline::removeSampleTag (const SampleTag *) throw () inline virtual
Exceptions
Implements nidas::core::SampleSource.
References _procSorter, and nidas::core::SampleSource::removeSampleTag().
setHeapBlock()
void nidas::core::SamplePipeline::setHeapBlock (bool val) inline
Parameters
val If true, and heapSize exceeds heapMax, then wait for heapSize to be less then heapMax, which will block any SampleSources that are inserting samples into the raw buffer. If false, then discard any samples that are received while heapSize exceeds heapMax.
See also
SampleSorter::setHeapBlock().
References _heapBlock.
Referenced by setRealTime().
setKeepStats()
void nidas::core::SamplePipeline::setKeepStats (bool val) inline
References _keepStats.
Referenced by nidas::core::DSMEngine::openSensors().
setProcHeapMax()
void nidas::core::SamplePipeline::setProcHeapMax (size_t val) inline
Set the maximum amount of heap memory to use for sorting samples.
Parameters
val Maximum size of heap in bytes.
See also
SampleSorter::setHeapMax().
References _procHeapMax.
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataPrep::run(), and StatsProcess::run().
setProcLateSampleCacheSize()
void nidas::core::SamplePipeline::setProcLateSampleCacheSize (unsigned int val) inline
Get the size of the late sample cache in the processed sample sorter.
See SampleSorter::getLateSampleCacheSize(). Default: 0.
References _procLateSampleCacheSize.
Referenced by nidas::core::DSMEngine::openSensors(), and DataPrep::run().
setProcSorterLength()
void nidas::core::SamplePipeline::setProcSorterLength (float val) inline
Set length of processed SampleSorter, in seconds.
References _procSorterLength.
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
setRawHeapMax()
void nidas::core::SamplePipeline::setRawHeapMax (size_t val) inline
Set the maximum amount of heap memory to use for sorting samples.
Parameters
val Maximum size of heap in bytes.
See also
SampleSorter::setHeapMax().
References _rawHeapMax.
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataPrep::run(), and StatsProcess::run().
setRawLateSampleCacheSize()
void nidas::core::SamplePipeline::setRawLateSampleCacheSize (unsigned int val) inline
Get the size of the late sample cache in the raw sample sorter.
See SampleSorter::getLateSampleCacheSize(). Default: 0.
References _rawLateSampleCacheSize.
Referenced by nidas::core::DSMEngine::openSensors(), and DataPrep::run().
setRawSorterLength()
void nidas::core::SamplePipeline::setRawSorterLength (float val) inline
Set length of raw SampleSorter, in seconds.
References _rawSorterLength.
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
setRealTime()
void nidas::core::SamplePipeline::setRealTime (bool val) inline
References _realTime, and setHeapBlock().
Referenced by nidas::dynld::raf::SyncServer::init(), nidas::core::DSMEngine::openSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
Member Data Documentation
_dsmConfigs
std::list<const DSMConfig*> nidas::core::SamplePipeline::_dsmConfigs private
_heapBlock
bool nidas::core::SamplePipeline::_heapBlock private
Referenced by getHeapBlock(), and setHeapBlock().
_keepStats
bool nidas::core::SamplePipeline::_keepStats private
Referenced by procinit(), rawinit(), and setKeepStats().
_name
std::string nidas::core::SamplePipeline::_name private
Referenced by getName(), procinit(), and rawinit().
_procHeapMax
size_t nidas::core::SamplePipeline::_procHeapMax private
Referenced by getProcHeapMax(), and setProcHeapMax().
_procLateSampleCacheSize
unsigned int nidas::core::SamplePipeline::_procLateSampleCacheSize private
Referenced by getProcLateSampleCacheSize(), and setProcLateSampleCacheSize().
_procMutex
nidas::util::Mutex nidas::core::SamplePipeline::_procMutex private
Referenced by interrupt(), join(), procinit(), and ~SamplePipeline().
_procSorter
SampleThread* nidas::core::SamplePipeline::_procSorter private
Referenced by addSampleTag(), flush(), getClientCount(), getNumDiscardedProcSamples(), getNumFutureProcSamples(), getSampleStats(), getSampleTagIterator(), getSampleTags(), getSorterNumProcBytes(), getSorterNumProcBytesMax(), getSorterNumProcSamples(), interrupt(), join(), procinit(), removeSampleTag(), and ~SamplePipeline().
_procSorterLength
float nidas::core::SamplePipeline::_procSorterLength private
seconds
Referenced by getProcSorterLength(), and setProcSorterLength().
_rawHeapMax
size_t nidas::core::SamplePipeline::_rawHeapMax private
Referenced by getRawHeapMax(), and setRawHeapMax().
_rawLateSampleCacheSize
unsigned int nidas::core::SamplePipeline::_rawLateSampleCacheSize private
Referenced by getRawLateSampleCacheSize(), and setRawLateSampleCacheSize().
_rawMutex
nidas::util::Mutex nidas::core::SamplePipeline::_rawMutex private
Referenced by interrupt(), join(), rawinit(), and ~SamplePipeline().
_rawSorter
SampleThread* nidas::core::SamplePipeline::_rawSorter private
Referenced by flush(), getNumDiscardedRawSamples(), getNumFutureRawSamples(), getRawSampleSource(), getSorterNumRawBytes(), getSorterNumRawBytesMax(), getSorterNumRawSamples(), interrupt(), join(), rawinit(), and ~SamplePipeline().
_rawSorterLength
float nidas::core::SamplePipeline::_rawSorterLength private
seconds
Referenced by getRawSorterLength(), and setRawSorterLength().
_realTime
bool nidas::core::SamplePipeline::_realTime private
Referenced by getRealTime(), and setRealTime().
_sampleTags
std::list<const SampleTag*> nidas::core::SamplePipeline::_sampleTags private
The documentation for this class was generated from the following files:
nidas/core/SamplePipeline.h
nidas/core/SamplePipeline.cc