nidas: nidas::util::DatagramSocket Class Reference
nidas::util::DatagramSocket Class Reference
A socket for sending or receiving datagrams, either unicast, broadcast or multicast.
#include <Socket.h>
Public Member Functions
DatagramSocket ()
Create a DatagramSocket not bound to a port.
DatagramSocket (int port)
Create a DatagramSocket bound to a port on all local interfaces (a local address of INADDR_ANY).
DatagramSocket (const Inet4Address &addr, int port)
Creates a datagram socket and binds it to a port at the specified local address.
DatagramSocket (const SocketAddress &addr)
Creates a DatagramSocket and binds it to the specified local address.
virtual ~DatagramSocket () throw ()
MulticastSocket is derived from DatagramSocket, so we provide a virtual destructor.
void close ()
void setTimeout (int val)
Set the timeout for receive(), recv(), and recvfrom() methods.
void connect (const std::string &host, int port)
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
void connect (const Inet4Address &addr, int port)
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
void connect (const SocketAddress &addr)
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
void bind (const Inet4Address &addr, int port)
Bind the DatagramSocket to the specified local address.
void bind (const SocketAddress &addr)
Bind the DatagramSocket to the specified local address.
int getFd () const
void receive (DatagramPacketBase &packet)
Read a packet from the DatagramSocket.
void receive (DatagramPacketBase &packet, Inet4PacketInfo &info, int flags=0)
Read a packet from the DatagramSocket.
void send (const DatagramPacketBase &packet, int flags=0)
size_t recv (void *buf, size_t len, int flags=0)
size_t recvfrom (void *buf, size_t len, int flags, SocketAddress &from)
size_t send (const void *buf, size_t len, int flags=0)
size_t send (const struct iovec *iov, int iovcnt, int flags=MSG_NOSIGNAL)
size_t sendto (const void *buf, size_t len, int flags, const SocketAddress &to)
size_t sendto (const struct iovec *iov, int iovcnt, int flags, const SocketAddress &to)
const SocketAddress & getLocalSocketAddress () const
Get local address of this socket.
int getLocalPort () const
Get local port number of this socket.
void setNonBlocking (bool val)
Do fcntl system call to set O_NONBLOCK file descriptor flag on the socket.
bool isNonBlocking () const
void setReceiveBufferSize (int size)
int getReceiveBufferSize ()
void setSendBufferSize (int size)
int getSendBufferSize ()
std::list< Inet4NetworkInterface > getInterfaces () const
void setBroadcastEnable (bool val)
bool getBroadcastEnable () const
void setPktInfo (bool val)
Control whether a IP_PKTINFO ancillary message is received with each datagram.
Protected Attributes
SocketImpl _impl
Detailed Description
A socket for sending or receiving datagrams, either unicast, broadcast or multicast.
This class provides the default public copy constructors and assignment operators. Objects of this class can be copied and assigned to without restriction. However, because of this, the destructor does not close the socket, so, in general, you should make sure that the socket is closed once at some point.
Typical usage: A receiver of datagrams on port 9000:
DatagramSocket sock(9000);
char buf[512];
Inet4SocketAddress from;
for (;;) {
    sock.recvfrom(buf,sizeof(buf),0,from);
}
sock.close();
A unicast sender of datagrams on port 9000:
DatagramSocket sock;
    Inet4SocketAddress to(Inet4Address::getByName("128.117.80.99"),9000);
for (;;) {
    sock.sendto("hello\n",6,0,to);
    }
sock.close();
A multicast sender of datagrams on port 9000:
DatagramSocket sock;
    Inet4SocketAddress to(Inet4Address::getByName("239.0.0.1"),9000);
for (;;) {
    sock.sendto("hello\n",6,0,to);
    }
sock.close();
A broadcast sender of datagrams on port 9000 to the limited broadcast address of 255.255.255.255. This will fail with a "Network is unreachable" error if there are no external network interfaces UP with an assigned address. Use a broadcast address of 127.255.255.255 to "broadcast" on the loopback interface.
DatagramSocket sock;
sock.setBroadcastEnable(true);
    Inet4SocketAddress to(Inet4Address(INADDR_BROADCAST),9000);
for (;;) {
    sock.sendto("hello\n",6,0,to);
    }
sock.close();
Constructor & Destructor Documentation
DatagramSocket() [1/4]
DatagramSocket::DatagramSocket ()
Create a DatagramSocket not bound to a port.
Exceptions
IOException
DatagramSocket() [2/4]
DatagramSocket::DatagramSocket (int port)
Create a DatagramSocket bound to a port on all local interfaces (a local address of INADDR_ANY).
Parameters
port Port number, 0<=port<=65535. If zero, the system will select an available port number. To find out which port number was selected, use getLocalPort().
Exceptions
IOException
References _impl, nidas::util::SocketImpl::bind(), close(), and port.
DatagramSocket() [3/4]
DatagramSocket::DatagramSocket (const Inet4Address & addr, int port)
Creates a datagram socket and binds it to a port at the specified local address.
The address should correspond to the address of a local interface. Only packets sent the given port and interface, by unicast, broadcast or multicast will be received.
Exceptions
IOException
References _impl, nidas::util::SocketImpl::bind(), close(), and port.
DatagramSocket() [4/4]
DatagramSocket::DatagramSocket (const SocketAddress & addr)
Creates a DatagramSocket and binds it to the specified local address.
The address should correspond to the address of a local interface. Only packets sent the given port and interface, by unicast, broadcast or multicast will be received.
Exceptions
IOException
References _impl, nidas::util::SocketImpl::bind(), and close().
~DatagramSocket()
virtual nidas::util::DatagramSocket::~DatagramSocket () throw () inline virtual
MulticastSocket is derived from DatagramSocket, so we provide a virtual destructor.
Currently there are no other virtual methods, may need some more thought.
Member Function Documentation
bind() [1/2]
void nidas::util::DatagramSocket::bind (const Inet4Address & addr, int port) inline
Bind the DatagramSocket to the specified local address.
The address should correspond to the address of a local interface. Only packets sent to the given port and interface, by unicast, broadcast or multicast will be received.
Exceptions
IOException
References _impl, nidas::util::SocketImpl::bind(), and port.
Referenced by nidas::core::DatagramSocket::connect(), nidas::core::UDPSocketIODevice::open(), and nidas::core::DerivedDataReader::run().
bind() [2/2]
void nidas::util::DatagramSocket::bind (const SocketAddress & addr) inline
Bind the DatagramSocket to the specified local address.
The address should correspond to the address of a local interface. Only packets sent to the given port and interface, by unicast, broadcast or multicast will be received.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::bind().
close()
void nidas::util::DatagramSocket::close () inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::close().
Referenced by nidas::core::DatagramSocket::close(), nidas::core::MultipleUDPSockets::close(), nidas::core::UDPSocketIODevice::close(), DatagramSocket(), nidas::util::McSocket< SocketT >::getInterfaces(), PacketReader::loop(), nidas::core::DerivedDataReader::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::util::McSocketListener::run(), and nidas::util::McSocketListener::~McSocketListener().
connect() [1/3]
void nidas::util::DatagramSocket::connect (const Inet4Address & addr, int port) inline
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
Exceptions
IOException
References _impl, nidas::util::SocketImpl::connect(), and port.
connect() [2/3]
void nidas::util::DatagramSocket::connect (const SocketAddress & addr) inline
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::connect().
connect() [3/3]
void nidas::util::DatagramSocket::connect (const std::string & host, int port) inline
Datagrams are connectionless, so this doesn't establish a true connection, it just sets the default destination address for the send() calls.
Exceptions
UnknownHostException
IOException
References _impl, nidas::util::SocketImpl::connect(), and port.
Referenced by nidas::core::DatagramSocket::connect(), and nidas::util::McSocketListener::run().
getBroadcastEnable()
bool nidas::util::DatagramSocket::getBroadcastEnable () const inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::getBroadcastEnable().
getFd()
int nidas::util::DatagramSocket::getFd () const inline
References _impl, and nidas::util::SocketImpl::getFd().
Referenced by nidas::core::UDPSocketIODevice::close(), nidas::core::DatagramSocket::getFd(), nidas::core::MultipleUDPSockets::getFd(), nidas::core::UDPSocketIODevice::getReadFd(), nidas::core::UDPSocketIODevice::getWriteFd(), nidas::core::DerivedDataReader::run(), and nidas::util::McSocketListener::run().
getInterfaces()
std::list<Inet4NetworkInterface> nidas::util::DatagramSocket::getInterfaces () const inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::getInterfaces().
Referenced by nidas::core::DatagramSocket::getInterfaces().
getLocalPort()
int nidas::util::DatagramSocket::getLocalPort () const inline
Get local port number of this socket.
Exceptions
References _impl, and nidas::util::SocketImpl::getLocalPort().
Referenced by nidas::core::StatusListener::run().
getLocalSocketAddress()
const SocketAddress& nidas::util::DatagramSocket::getLocalSocketAddress () const inline
Get local address of this socket.
Exceptions
References _impl, and nidas::util::SocketImpl::getLocalSocketAddress().
Referenced by nidas::core::MultipleUDPSockets::handleChangedSockets(), nidas::core::DerivedDataReader::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), and nidas::util::McSocketListener::run().
getReceiveBufferSize()
int nidas::util::DatagramSocket::getReceiveBufferSize () inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::getReceiveBufferSize().
Referenced by nidas::core::DatagramSocket::getBufferSize(), and nidas::core::MultipleUDPSockets::getBufferSize().
getSendBufferSize()
int nidas::util::DatagramSocket::getSendBufferSize () inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::getSendBufferSize().
isNonBlocking()
bool nidas::util::DatagramSocket::isNonBlocking () const inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::isNonBlocking().
Referenced by nidas::core::DatagramSocket::isNonBlocking().
receive() [1/2]
void nidas::util::DatagramSocket::receive (DatagramPacketBase & packet) inline
Read a packet from the DatagramSocket.
On return, packet.getLength() will contain the number bytes received, and packet.getSocketAddress() will contain the address of the sender.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::receive().
Referenced by PacketReader::loop(), nidas::core::DerivedDataReader::run(), and nidas::util::McSocketListener::run().
receive() [2/2]
void nidas::util::DatagramSocket::receive (DatagramPacketBase & packet, Inet4PacketInfo & info, int flags = 0) inline
Read a packet from the DatagramSocket.
On return, packet.getLength() will contain the number bytes received, and packet.getSocketAddress() will contain the address of the sender. info will contain the information on the local and destination addresses of the packet, and the interface it was received on. If setPktInfo(true) has not be set on this socket, then it is set prior to receiving the packet, and then unset after receipt of the packet.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::receive().
recv()
size_t nidas::util::DatagramSocket::recv (void * buf, size_t len, int flags = 0) inline
Exceptions
IOException
References _impl, len, and nidas::util::SocketImpl::recv().
Referenced by nidas::core::DatagramSocket::read(), and nidas::core::UDPSocketIODevice::read().
recvfrom()
size_t nidas::util::DatagramSocket::recvfrom (void * buf, size_t len, int flags, SocketAddress & from) inline
Exceptions
IOException
References _impl, len, and nidas::util::SocketImpl::recvfrom().
Referenced by nidas::core::StatusListener::run().
send() [1/3]
void nidas::util::DatagramSocket::send (const DatagramPacketBase & packet, int flags = 0) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::send().
Referenced by nidas::core::DatagramSocket::write(), and nidas::core::UDPSocketIODevice::write().
send() [2/3]
size_t nidas::util::DatagramSocket::send (const struct iovec * iov, int iovcnt, int flags = MSG_NOSIGNAL) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::send().
send() [3/3]
size_t nidas::util::DatagramSocket::send (const void * buf, size_t len, int flags = 0) inline
Exceptions
IOException
References _impl, len, and nidas::util::SocketImpl::send().
sendto() [1/2]
size_t nidas::util::DatagramSocket::sendto (const struct iovec * iov, int iovcnt, int flags, const SocketAddress & to) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::sendto().
sendto() [2/2]
size_t nidas::util::DatagramSocket::sendto (const void * buf, size_t len, int flags, const SocketAddress & to) inline
Exceptions
IOException
References _impl, len, and nidas::util::SocketImpl::sendto().
Referenced by nidas::core::StatusThread::sendStatus(), and nidas::core::MultipleUDPSockets::write().
setBroadcastEnable()
void nidas::util::DatagramSocket::setBroadcastEnable (bool val) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::setBroadcastEnable().
Referenced by nidas::core::UDPSocketIODevice::open().
setNonBlocking()
void nidas::util::DatagramSocket::setNonBlocking (bool val) inline
Do fcntl system call to set O_NONBLOCK file descriptor flag on the socket.
Parameters
val true=set O_NONBLOCK, false=unset O_NONBLOCK.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::setNonBlocking().
Referenced by nidas::core::DatagramSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::McSocketUDP::connected(), and nidas::core::DatagramSocket::setNonBlocking().
setPktInfo()
void nidas::util::DatagramSocket::setPktInfo (bool val) inline
Control whether a IP_PKTINFO ancillary message is received with each datagram.
Only supported on DatagramSockets. The IP_PKTINFO message is converted to an Inet4PacketInfo object which is available via the getInet4PacketInfo() method.
Parameters
val if true enable the IP_PKTINFO message, if false, disable.
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::setPktInfo().
setReceiveBufferSize()
void nidas::util::DatagramSocket::setReceiveBufferSize (int size) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::setReceiveBufferSize().
setSendBufferSize()
void nidas::util::DatagramSocket::setSendBufferSize (int size) inline
Exceptions
IOException
References _impl, and nidas::util::SocketImpl::setSendBufferSize().
setTimeout()
void nidas::util::DatagramSocket::setTimeout (int val) inline
Set the timeout for receive(), recv(), and recvfrom() methods.
Parameters
val timeout in milliseconds. 0=no timeout (infinite) The receive methods will return IOTimeoutException if an operation times out.
References _impl, and nidas::util::SocketImpl::setTimeout().
Referenced by nidas::core::UDPSocketIODevice::read().
Member Data Documentation
_impl
SocketImpl nidas::util::DatagramSocket::_impl protected
Referenced by bind(), close(), connect(), DatagramSocket(), nidas::util::MulticastSocket::findInterface(), getBroadcastEnable(), getFd(), nidas::util::MulticastSocket::getInterface(), getInterfaces(), nidas::util::MulticastSocket::getInterfaces(), getLocalPort(), getLocalSocketAddress(), nidas::util::MulticastSocket::getMulticastLoop(), getReceiveBufferSize(), getSendBufferSize(), nidas::util::MulticastSocket::getTimeToLive(), isNonBlocking(), nidas::util::MulticastSocket::joinGroup(), nidas::util::MulticastSocket::leaveGroup(), receive(), recv(), recvfrom(), send(), sendto(), setBroadcastEnable(), nidas::util::MulticastSocket::setInterface(), nidas::util::MulticastSocket::setMulticastLoop(), setNonBlocking(), setPktInfo(), setReceiveBufferSize(), setSendBufferSize(), setTimeout(), and nidas::util::MulticastSocket::setTimeToLive().
The documentation for this class was generated from the following files:
nidas/util/Socket.h
nidas/util/Socket.cc