nidas: nidas::util::Inet4PacketInfoX Class Reference
nidas::util::Inet4PacketInfoX Class Reference
#include <Inet4PacketInfo.h>
Public Member Functions
Inet4PacketInfoX ()
Inet4SocketAddress getRemoteSocketAddress () const
The remote address of the packet.
void setRemoteSocketAddress (const Inet4SocketAddress &val)
virtual Inet4Address getLocalAddress () const
The local address of the packet.
virtual void setLocalAddress (const Inet4Address &val)
virtual const Inet4Address & getDestinationAddress () const
The destination address of the packet.
virtual void setDestinationAddress (const Inet4Address &val)
virtual const Inet4NetworkInterface & getInterface () const
The interface that the packet was received on.
virtual void setInterface (const Inet4NetworkInterface &val)
virtual int getFlags () const
The flags on the received packet.
virtual void setFlags (int val)
Private Attributes
Inet4SocketAddress _remotesaddr
Inet4Address _localaddr
Inet4Address _destaddr
Inet4NetworkInterface _iface
int _flags
Constructor & Destructor Documentation
Inet4PacketInfoX()
nidas::util::Inet4PacketInfoX::Inet4PacketInfoX () inline
Member Function Documentation
getDestinationAddress()
virtual const Inet4Address& nidas::util::Inet4PacketInfo::getDestinationAddress () const inline virtual inherited
The destination address of the packet.
For a received unicast packet it will be the address of the local interface. Or the destination address could be a multicast address or a broadcast address.
References nidas::util::Inet4PacketInfo::_destaddr.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::McSocketUDP::connected(), nidas::core::McSocket::connected(), and nidas::util::SocketImpl::receive().
getFlags()
virtual int nidas::util::Inet4PacketInfo::getFlags () const inline virtual inherited
The flags on the received packet.
See "man 7 ip". It can contain several flags: MSG_EOR, MSG_TRUNC, MSG_CTRUNC, MSG_OOB, MSG_ERRQUEUE.
References nidas::util::Inet4PacketInfo::_flags.
getInterface()
virtual const Inet4NetworkInterface& nidas::util::Inet4PacketInfo::getInterface () const inline virtual inherited
The interface that the packet was received on.
References nidas::util::Inet4PacketInfo::_iface.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::McSocketUDP::connected(), nidas::core::McSocket::connected(), and nidas::util::SocketImpl::receive().
getLocalAddress()
virtual Inet4Address nidas::util::Inet4PacketInfo::getLocalAddress () const inline virtual inherited
The local address of the packet.
For a received packet, it is the address of the local interface that the packet was received on.
References nidas::util::Inet4PacketInfo::_localaddr.
Referenced by nidas::util::SocketImpl::receive().
getRemoteSocketAddress()
Inet4SocketAddress nidas::util::Inet4PacketInfoX::getRemoteSocketAddress () const inline
The remote address of the packet.
For a received packet, it is the address of the local interface that the packet was sent from.
References _remotesaddr.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::McSocketUDP::connected(), and nidas::core::McSocket::connected().
setDestinationAddress()
virtual void nidas::util::Inet4PacketInfo::setDestinationAddress (const Inet4Address & val) inline virtual inherited
References nidas::util::Inet4PacketInfo::_destaddr.
Referenced by nidas::util::SocketImpl::receive(), and nidas::util::McSocketMulticaster< SocketTT >::run().
setFlags()
virtual void nidas::util::Inet4PacketInfo::setFlags (int val) inline virtual inherited
References nidas::util::Inet4PacketInfo::_flags.
setInterface()
virtual void nidas::util::Inet4PacketInfo::setInterface (const Inet4NetworkInterface & val) inline virtual inherited
References nidas::util::Inet4PacketInfo::_iface.
Referenced by nidas::util::SocketImpl::receive().
setLocalAddress()
virtual void nidas::util::Inet4PacketInfo::setLocalAddress (const Inet4Address & val) inline virtual inherited
References nidas::util::Inet4PacketInfo::_localaddr.
Referenced by nidas::util::SocketImpl::receive(), and nidas::util::McSocketMulticaster< SocketTT >::run().
setRemoteSocketAddress()
void nidas::util::Inet4PacketInfoX::setRemoteSocketAddress (const Inet4SocketAddress & val) inline
References _remotesaddr.
Referenced by nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
Member Data Documentation
_destaddr
Inet4Address nidas::util::Inet4PacketInfo::_destaddr private inherited
Referenced by nidas::util::Inet4PacketInfo::getDestinationAddress(), and nidas::util::Inet4PacketInfo::setDestinationAddress().
_flags
int nidas::util::Inet4PacketInfo::_flags private inherited
Referenced by nidas::util::Inet4PacketInfo::getFlags(), and nidas::util::Inet4PacketInfo::setFlags().
_iface
Inet4NetworkInterface nidas::util::Inet4PacketInfo::_iface private inherited
Referenced by nidas::util::Inet4PacketInfo::getInterface(), and nidas::util::Inet4PacketInfo::setInterface().
_localaddr
Inet4Address nidas::util::Inet4PacketInfo::_localaddr private inherited
Referenced by nidas::util::Inet4PacketInfo::getLocalAddress(), and nidas::util::Inet4PacketInfo::setLocalAddress().
_remotesaddr
Inet4SocketAddress nidas::util::Inet4PacketInfoX::_remotesaddr private
Referenced by getRemoteSocketAddress(), and setRemoteSocketAddress().
The documentation for this class was generated from the following file:
nidas/util/Inet4PacketInfo.h