nidas: nidas/core/Project.cc File Reference
Project.cc File Reference
#include "Project.h"
#include "Site.h"
#include "DSMServer.h"
#include "SampleTag.h"
#include "SensorCatalog.h"
#include "DSMCatalog.h"
#include "ServiceCatalog.h"
#include "DOMObjectFactory.h"
#include "SampleOutput.h"
#include "SampleArchiver.h"
#include "FileSet.h"
#include <nidas/util/Inet4Address.h>
#include <nidas/util/Logger.h>
#include <nidas/util/Socket.h>
#include <nidas/util/auto_ptr.h>
#include <iostream>
#include <sys/utsname.h>
Functions
static void LogSchemeFromDOMElement (const xercesc::DOMElement *node)
Function Documentation
LogSchemeFromDOMElement()
static void LogSchemeFromDOMElement (const xercesc::DOMElement * node) static
References nidas::util::LogConfig::activate, nidas::util::LogScheme::addConfig(), nidas::util::LogConfig::filename_match, nidas::util::LogConfig::function_match, nidas::core::XDOMElement::getAttributeValue(), nidas::util::Logger::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), nidas::util::LogConfig::level, nidas::util::LogConfig::line, nidas::util::LogScheme::setName(), nidas::util::LogScheme::setShowFields(), nidas::util::stringToLogLevel(), nidas::util::LogConfig::tag_match, and nidas::util::Logger::updateScheme().
Referenced by nidas::core::Project::fromDOMElement().