nidas: nidas::dynld::raf::PIP_Serial Class Reference
nidas::dynld::raf::PIP_Serial Class Reference
A class for reading DMT PIP/CIP probe histogram data.
#include <PIP_Serial.h>
Classes
struct InitPIP_blk
struct PIP_blk
Data packet back from probe.
struct SendPIP_BLK
Packet sent to probe to begin sending data.
struct SetAbsoluteTime
Public Types
enum DataTermination { FixedLength , Delimited }
Public Member Functions
PIP_Serial ()
void validate ()
Implementation of DSMSensor::validate for a Character Sensor.
void sendInitString ()
bool process (const Sample *samp, std::list< const Sample * > &results)
Process a raw sample, which in this case means do a sscanf on the character string contents, creating a processed sample of binary floating point data.
virtual void derivedDataNotify (const nidas::core::DerivedDataReader *s) throw ()
PIP has dynamic TAS.
void open (int flags)
open the sensor and perform any intialization to the driver.
void close ()
close my associated device.
unsigned short computeCheckSum (const unsigned char *pkt, int len)
nidas::util::Termios & termios ()
Expose the Termios.
const nidas::util::Termios & getTermios () const
Get a read-only copy of the Termios.
SampleScanner * buildSampleScanner ()
Calls CharacterSensor::buildSampleScanner(), and then sets the per-byte transmission delay for that scanner: SampleScanner::setUsecsPerByte().
IODevice * buildIODevice ()
Creates an IODevice depending on the device name prefix: name prefix type of IODevice inet: TCPSocketIODevice sock: TCPSocketIODevice usock: UDPSocketIODevice btspp: BluetoothRFCommSocketIODevice all others SerialPortIODevice.
void applyTermios ()
If the underlying IODevice is a SerialPortIODevice, update the current Termios to the device.
void setMessageParameters (unsigned int len, const std::string &sep, bool eom)
Set message separator and message length parameters, which are used to parse and time-tag samples from the IODevice.
void printStatus (std::ostream &ostr) throw ()
bool isPrompting () const
Is prompting active, i.e.
void startPrompting ()
Start the prompters.
void stopPrompting ()
void fromDOMElement (const xercesc::DOMElement *node)
int getUsecsPerByte () const
If the underlying IODevice is a SerialPortIODevice, return the value of SerialPortIODevice::getUsecsPerByte(), otherwise return 0, which means no timetag correction for transmission delay will be applied.
void init ()
Initialize the CharacterSensor instance for post-processing.
const std::string & getMessageSeparator () const
Get message separator with backslash sequences replaced by their intended character.
const std::string getBackslashedMessageSeparator () const
Get message separator with backslash sequences added back.
bool getMessageSeparatorAtEOM () const
int getMessageLength () const
virtual void addPrompt (const std::string &promptString, double promptRate, double promptOffset)
Prompting Sensors can have multiple prompts and rates.
const std::list< Prompt > & getPrompts () const
virtual bool isPrompted () const
Is this a prompted sensor.
virtual void togglePrompting ()
void setInitString (const std::string &val)
Set the initialization string(s) for this sensor.
const std::string & getInitString () const
bool getNullTerminated () const
int getNumScanfFailures () const
How many samples have resulted in complete scanf failures - nothing parsed, because the sensor messages do not correspond to the sscanf format.
int getNumScanfPartials () const
How many samples have been partially scanned, because a character in the middle of a message conflicts with the sscanf format.
const std::list< AsciiSscanf * > & getScanfers () const
Return the list of AsciiSscanfs requested for this CharacterSensor.
int getMaxScanfFields () const
The maximum number of fields in any of the AsciiSscanfs for this CharacterSensor.
virtual void validateSscanfs ()
Virtual method to check that the Sscanfs for this CharacterSensor are OK.
bool doesAsciiSscanfs ()
void setDSMConfig (const DSMConfig *val)
Set the DSMConfig for this sensor.
const DSMConfig * getDSMConfig () const
What DSMConfig am I associated with?
const Site * getSite () const
What Site am I associated with?
virtual void setDeviceName (const std::string &val)
Set the name of the system device that the sensor is connected to.
virtual const std::string & getDeviceName () const
Fetch the name of the system device that the sensor is connected to.
virtual void setClassName (const std::string &val)
Set the class name.
virtual const std::string & getClassName () const
Fetch the class name.
virtual void setCatalogName (const std::string &val)
Set the name of the catalog entry for this sensor.
virtual const std::string & getCatalogName () const
Fetch the name of the catalog entry for this sensor.
const std::string & getDSMName () const
Fetch the DSM name.
virtual std::string getName () const
Return a name that should fully identify this sensor.
const std::string & getLocation () const
Location string.
void setLocation (const std::string &val)
const std::string & getSuffix () const
Sensor suffix, which is added to variable names.
void setSuffix (const std::string &val)
int getStation () const
void setStation (int val)
void setHeight (const std::string &val)
Set sensor height above ground via a string which is added to variable names.
void setHeight (float val)
Set sensor height above ground.
const std::string & getHeightString () const
Get sensor height above ground in a string.
float getHeight () const
Get sensor height above ground.
void setDepth (const std::string &val)
Set sensor depth below ground via a string which is added to variable names.
void setDepth (float val)
Set sensor depth below ground.
const std::string & getDepthString () const
Get sensor depth below ground in a string.
float getDepth () const
Get sensor depth below ground.
const std::string & getFullSuffix () const
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $HEIGHT.
const Dictionary & getDictionary () const
SampleSource * getRawSampleSource ()
Implementation of SampleSource::getRawSampleSource().
SampleSource * getProcessedSampleSource ()
Implementation of SampleSource::getProcessedSampleSource().
const SampleTag * getRawSampleTag () const
Convenience function to get my one-and-only raw SampleTag().
virtual void addSampleTag (SampleTag *val)
Add a SampleTag to this sensor.
virtual void removeSampleTag (SampleTag *val)
Remove val from the list of SampleTags, and delete it.
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
std::list< SampleTag * > & getSampleTags ()
Non-const method to get a list of non-const pointers to SampleTags.
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush ()
Implementation of SampleClient::flush().
void distributeRaw (const Sample *s)
Distribute a raw sample which has been read from my file descriptor in real time.
const SampleStats & getSampleStats () const
virtual int getReadFd () const
virtual int getWriteFd () const
virtual bool reopenOnIOException () const
Whether to reopen this sensor on an IOException.
void setId (dsm_sample_id_t val)
Set the various levels of the sensor identification.
void setSensorId (unsigned int val)
void setDSMId (unsigned int val)
dsm_sample_id_t getId () const
Get the various levels of the samples identification.
unsigned int getDSMId () const
unsigned int getSensorId () const
virtual void setLatency (float val)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
virtual float getLatency () const
virtual void setTimeoutMsecs (int val)
Set the sensor timeout value in milliseconds.
virtual int getTimeoutMsecs () const
int getTimeoutCount () const
void incrementTimeoutCount ()
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setIODevice (IODevice *val)
Set the IODevice for this sensor.
void setSampleScanner (SampleScanner *val)
Set the SampleScanner for this sensor.
virtual int getDefaultMode () const
How do I want to be opened.
virtual void setDefaultMode (int val)
virtual size_t getBytesAvailable () const
How many bytes are available to read on this sensor.
virtual size_t read (void *buf, size_t len)
Read from the device (duh).
virtual size_t read (void *buf, size_t len, int msecTimeout)
Read from the device with a timeout.
virtual size_t write (const void *buf, size_t len)
Write to the device (duh).
virtual void ioctl (int request, void *buf, size_t len)
Perform an ioctl on the device.
virtual bool readSamples ()
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
virtual Sample * nextSample ()
Extract the next sample from the buffer.
virtual Sample * readSample ()
Return the next sample.
bool receive (const Sample *s)
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
void printStatusHeader (std::ostream &ostr)
void printStatusTrailer (std::ostream &ostr)
void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
float getObservedSamplingRate () const
float getObservedDataRate () const
size_t getBadTimeTagCount () const
VariableIterator getVariableIterator () const
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
virtual void setTypeName (const std::string &val)
Set the type name of this sensor, e.g.
virtual const std::string & getTypeName (void) const
Get the type name of this sensor.
bool getDuplicateIdOK () const
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
void setDuplicateIdOK (bool val)
Set the duplicate ID attribute of this DSMSensor.
virtual bool getApplyVariableConversions () const
virtual void setApplyVariableConversions (bool val)
virtual int getDriverTimeTagUsecs () const
virtual void setDriverTimeTagUsecs (int val)
void addCalFile (CalFile *val)
Add a calibration file for this DSMSensor.
const std::map< std::string, CalFile * > & getCalFiles ()
Return the collection of CalFiles, mapped by name.
CalFile * getCalFile (const std::string &name)
Return a CalFile by its getName().
void removeCalFiles ()
Remove all CalFiles.
virtual void executeXmlRpc (XmlRpc::XmlRpcValue &, XmlRpc::XmlRpcValue &)
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
virtual const std::list< SampleTag * > & getNonConstSampleTags ()
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
bool allowOpen ()
bool readBuffer ()
Read into my SampleScanner's buffer.
bool readBuffer (int msecTimeout)
Read into my SampleScanner's buffer.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *project)
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
static void deleteLooper ()
static const XMLCh * getNamespaceURI ()
Static Public Attributes
static const size_t N_PIP_CHANNELS = 62
static const size_t N_PIP_HSKP = 16
static const int _InitPacketSize = 10
static const int _setTimePacketSize = 8
static const int _SendDataPacketSize = 12
static const int MAX_CHANNELS = 40
Max # for array sizing.
Protected Member Functions
int packetLen () const
Return the expected data packet length in bytes based on the number of channels being used.
void sendTimePacket ()
Set probe time.
int appendDataAndFindGood (const Sample *sample)
Append _packetLen bytes of data to _waitingData, and find the earliest "good" record possible, where a good record:
virtual void sendInitPacketAndCheckAck (void *packet, int len, int return_len=2)
Send pre-packaged initialization packet to SPP probe and wait for acknowledge packet.
double convert (dsm_time_t tt, double val, unsigned int ivar)
Apply a VariableConversion to an output value.
void initPrompting ()
Perform whatever is necessary to initialize prompting right after the device is opened.
void shutdownPrompting ()
Shutdown prompting, typically done when a device is closed.
void unixDevInit (int flags)
void setPromptRate (const double val)
Set the rate at which <sensor> prompts are sent to this sensor.
double getPromptRate () const
void setPromptOffset (const double val)
double getPromptOffset () const
void setPromptString (const std::string &val)
Set the <sensor> prompt string for this sensor.
const std::string & getPromptString () const
virtual int scanSample (AsciiSscanf *sscanf, const char *inputstr, float *data_ptr)
SampleT< float > * searchSampleScanners (const Sample *samp, SampleTag **stag_out=0) throw ()
Search through the AsciiSscanf instances attached to this sensor, looking for the next scanner which parses at least one variable from the given raw sample.
void adjustTimeTag (SampleTag *stag, SampleT< float > *outs)
Apply TimetagAdjuster and lag adjustments to the timetag of the given sample.
void clearBuffer ()
Clear the internal buffer.
IODevice * getIODevice () const
SampleScanner * getSampleScanner () const
void setFullSuffix (const std::string &val)
virtual int getLagUsecs () const
Return the sampling lag for this sensor in microseconds.
virtual double getLagSecs () const
Return the sampling lag for this sensor in seconds.
virtual void setLagSecs (double val)
Set the sampling lag for this sensor in seconds.
void applyConversions (SampleTag *stag, SampleT< float > *outs, float *results=0)
Perform variable conversions for the variables in stag whose values and sample time have been set in outs.
void trimUnparsed (SampleTag *stag, SampleT< float > *outs, int nparsed)
Fill with floatNAN all the values past nparsed values in output sample outs, and trim the length of the sample to match the length of the variables in SampleTag stag.
VariableIndex findVariableIndex (const std::string &vprefix)
Search all the sample tags for a variable whose name starts with the given prefix, and return it's index in the list of variables in the sample tag.
Static Protected Member Functions
static Looper * getLooper ()
Fetch a pointer to a static instance of a Looper thread.
Protected Attributes
unsigned short _dofReject
unsigned short _airspeedSource
float _trueAirSpeed
True air speed, received from IWGADTS feed.
unsigned short _model
Possibly not needed...
int _nChannels
Number of channels requested to be recorded.
int _nHskp
Number of housekeeping variables added to output data.
std::string _probeName
unsigned short _range
unsigned short _triggerThreshold
unsigned short _opcThreshold [MAX_CHANNELS]
int _noutValues
Total number of floats in the processed output sample.
DataTermination _dataType
Whether we are using fixed length data with checkSum (true), or the modified chips with message terminators.
unsigned short _recDelimiter
size_t _checkSumErrorCnt
unsigned char * _waitingData
Buffer to hold incoming data until we find a chunk that looks like a valid DMT100 data packet.
unsigned short _nWaitingData
int _skippedBytes
size_t _skippedRecordCount
size_t _totalRecordCount
bool _outputDeltaT
Stash sample-rate.
dsm_time_t _prevTime
Store previous time tag.
std::vector< nidas::core::VariableConverter * > _converters
VariableConverters which may have been defined for each output housekeeping variable.
std::map< const SampleTag *, TimetagAdjuster * > _ttadjusters
bool _openable
Whether this sensor is allowed to be opened.
Static Protected Attributes
static const size_t PIPEDV0 = 0
static const size_t PIPEDV64 = 1
static const size_t PIPEDV32 = 2
static const size_t PIPQC = 3
static const size_t PIPPS = 4
static const size_t PIPLWC = 5
static const size_t PIPLWCSLV = 6
static const size_t PIPCBTMP = 7
static const size_t PIPRH = 8
static const size_t PIPRT = 13
static const size_t PIPLSRC = 14
static const size_t PIPLSRP = 15
static const size_t REJOFLOW
static const size_t REJDOF
static const size_t REJEND
Private Member Functions
void addSampleTag (const SampleTag *val)
DSMSensor does provide public support for SampleSource::addSampleTag(const SampleTag* val).
void removeSampleTag (const SampleTag *val)
DSMSensor does not provide public support for SampleSource::removeSampleTag(const SampleTag* val)
Private Attributes
nidas::util::Termios _termios
Serial I/O parameters.
SerialPortIODevice * _serialDevice
Non-null if the underlying IODevice is a SerialPortIODevice.
std::list< Prompter * > _prompters
bool _prompting
int _rts485
Should the RTS line on this port be controled for half-duplex 485? See SerialPortIODevice.h.
std::string _messageSeparator
bool _separatorAtEOM
int _messageLength
std::list< Prompt > _prompts
std::string _promptString
double _promptRate
double _promptOffset
std::list< AsciiSscanf * > _sscanfers
std::list< AsciiSscanf * >::const_iterator _nextSscanfer
int _maxScanfFields
int _scanfFailures
int _scanfPartials
bool _prompted
std::string _initString
String that is sent once after sensor is opened.
std::string _emptyString
std::string _devname
nidas::core::DSMSensor::MyDictionary _dictionary
IODevice * _iodev
int _defaultMode
std::string _className
Class name attribute of this sensor.
std::string _catalogName
std::string _suffix
Sensor suffix, which is added to variable names.
std::string _heightString
std::string _depthString
float _height
std::string _fullSuffix
Concatenation of sensor suffix, and the height or depth string.
std::string _location
SampleScanner * _scanner
const DSMConfig * _dsm
dsm_sample_id_t _id
Id of this sensor.
SampleTag _rawSampleTag
std::list< SampleTag * > _sampleTags
SampleSourceSupport _rawSource
SampleSourceSupport _source
float _latency
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
std::map< std::string, CalFile * > _calFiles
std::string _typeName
int _timeoutMsecs
bool _duplicateIdOK
bool _applyVariableConversions
int _driverTimeTagUsecs
int _nTimeouts
int _lag
int _station
Static Private Attributes
static bool zebra = false
static Looper * _looper = 0
static nidas::util::Mutex _looperMutex
static XMLCh * namespaceURI = 0
Detailed Description
A class for reading DMT PIP/CIP probe histogram data.
RS-422 @ 38400 baud.
Member Enumeration Documentation
DataTermination
enum nidas::dynld::raf::SppSerial::DataTermination inherited
Enumerator
FixedLength
Delimited
Constructor & Destructor Documentation
PIP_Serial()
PIP_Serial::PIP_Serial ()
References _InitPacketSize, nidas::dynld::raf::SppSerial::_nChannels, nidas::dynld::raf::SppSerial::_nHskp, nidas::dynld::raf::PIP_Serial::PIP_blk::chksum, nidas::core::CharacterSensor::init(), N_PIP_CHANNELS, and packetLen().
Member Function Documentation
addCalFile()
void DSMSensor::addCalFile (CalFile * val) inherited
Add a calibration file for this DSMSensor.
After this method is finished, DSMSensor will own the pointer, and will delete it in the DSMSensor destructor.
References nidas::core::DSMSensor::_calFiles, and nidas::core::CalFile::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
addParameter()
void DSMSensor::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::DSMSensor::_constParameters, nidas::core::DSMSensor::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
addPrompt()
virtual void nidas::core::CharacterSensor::addPrompt (const std::string & promptString, double promptRate, double promptOffset) inline virtual inherited
Prompting Sensors can have multiple prompts and rates.
Add another prompt and rate to this sensor.
Parameters
promptString May contain backslash escape sequences.
promptRate prompts/sec.
References nidas::core::CharacterSensor::_prompted, nidas::core::CharacterSensor::_prompts, nidas::core::Prompt::setOffset(), nidas::core::Prompt::setRate(), and nidas::core::Prompt::setString().
Referenced by nidas::core::CharacterSensor::validate().
addSampleClient()
void nidas::core::DSMSensor::addSampleClient (SampleClient * c) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by nidas::core::SamplePipeline::addSampleClient(), and nidas::core::SamplePipeline::addSampleClientForTag().
addSampleClientForTag()
void nidas::core::DSMSensor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
Referenced by nidas::core::SamplePipeline::addSampleClientForTag().
addSampleTag() [1/2]
void DSMSensor::addSampleTag (const SampleTag * val) private virtual inherited
DSMSensor does provide public support for SampleSource::addSampleTag(const SampleTag* val).
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleSource.
addSampleTag() [2/2]
void DSMSensor::addSampleTag (SampleTag * val) virtual inherited
Add a SampleTag to this sensor.
DSMSensor will own the SampleTag. Throw an exception the DSMSensor cannot support the sample (bad rate, wrong number of variables, etc). Note that a SampleTag may be changed after it has been added. addSampleTag() is called when a sensor is initialized from the sensor catalog. The SampleTag may be modified later if it is overridden in the actual sensor entry. For this reason, it is wise to wait to scan the SampleTags of a DSMSensor in the validate(), init() or open() methods, which are invoked after fromDOMElement.
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::isff::DAUSensor, nidas::dynld::iss::WICORSensor, and nidas::dynld::iss::TiltSensor.
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_source, nidas::core::SampleSourceSupport::addSampleTag(), GET_DSM_ID, GET_SHORT_ID, nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::DSMSensor::getName(), nidas::util::Logger::log(), LOG_WARNING, and nidas::core::SampleTag::setDSMSensor().
Referenced by nidas::dynld::iss::TiltSensor::addSampleTag(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::DAUSensor::addSampleTag(), nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::fromDOMElement(), and main().
adjustTimeTag()
void CharacterSensor::adjustTimeTag (SampleTag * stag, SampleT< float > * outs) protected inherited
Apply TimetagAdjuster and lag adjustments to the timetag of the given sample.
References nidas::core::CharacterSensor::_ttadjusters, nidas::core::TimetagAdjuster::adjust(), nidas::core::DSMSensor::getLagUsecs(), nidas::core::Sample::getTimeTag(), and nidas::core::Sample::setTimeTag().
Referenced by nidas::core::CharacterSensor::process().
allowOpen()
bool nidas::core::DSMSensor::allowOpen () inline inherited
References nidas::core::DSMSensor::_openable.
Referenced by nidas::core::DSMConfig::addSensor().
appendDataAndFindGood()
int PIP_Serial::appendDataAndFindGood (const Sample * sample) protected virtual
Append _packetLen bytes of data to _waitingData, and find the earliest "good" record possible, where a good record:
1) is packetLen() bytes long 2) the last two bytes of the record are a valid 16-bit checksum for the rest of the record (_dataType == FixedLength), or the last two bytes match the expected record terminator (_dataType == Delimited)
If a good record is found, the function returns true, data before the good record are dropped, leaving the good record will be at the head of _waitingData. If no good record is found, the function returns false, and the last (packetLen()-1) bytes of _waitingData are retained. Is virtual so PIP can override.
Reimplemented from nidas::dynld::raf::SppSerial.
References nidas::dynld::raf::SppSerial::_dataType, nidas::dynld::raf::SppSerial::_nWaitingData, nidas::dynld::raf::SppSerial::_recDelimiter, nidas::dynld::raf::SppSerial::_skippedBytes, nidas::dynld::raf::SppSerial::_skippedRecordCount, nidas::dynld::raf::SppSerial::_totalRecordCount, nidas::dynld::raf::SppSerial::_waitingData, nidas::dynld::raf::SppSerial::computeCheckSum(), nidas::dynld::raf::SppSerial::Delimited, nidas::dynld::raf::SppSerial::FixedLength, nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), packetLen(), and nidas::dynld::raf::UnpackDMT_UShort().
Referenced by process().
applyConversions()
void DSMSensor::applyConversions (SampleTag * stag, SampleT< float > * outs, float * results = 0) protected inherited
Perform variable conversions for the variables in stag whose values and sample time have been set in outs.
This method can be used by subclasses to apply any variable conversions associated with the variables in the given SampleTag, using a general algorithm which loops over each value in each variable. The min/max value limits of a variable are applied also, so if a variable value is converted but lies outside the min/max range, the value is set to floatNAN. Typically this can be the last step applied to the output sample of a sensor's process() method, and note that the sample time must already be set in the output sample outs, since that time will be used to look up conversions in calibration files.
If results is non-null, then the converted values are written into results instead of overwriting the values in outs. This is used when one variable's results may be used to filter other variables without replacing the one variable's results. An example is the Ifan variable in the TRH WisardMote. results must point to enough memory to hold all of the values in outs, including for any Variables with multiple values (getLength() > 1).
See Variable::convert().
References nidas::core::Variable::convert(), fp, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::getTimeTag(), and nidas::core::SampleTag::getVariables().
Referenced by nidas::dynld::iss::WICORSensor::process(), and nidas::core::CharacterSensor::process().
applyTermios()
void SerialSensor::applyTermios () inherited
If the underlying IODevice is a SerialPortIODevice, update the current Termios to the device.
Exceptions
nidas::util::IOException
References nidas::core::SerialSensor::_serialDevice, nidas::core::SerialSensor::_termios, nidas::core::SerialPortIODevice::applyTermios(), and nidas::core::SerialPortIODevice::termios().
Referenced by nidas::core::RemoteSerialConnection::doEscCmds().
buildIODevice()
IODevice * SerialSensor::buildIODevice () virtual inherited
Creates an IODevice depending on the device name prefix: name prefix type of IODevice inet: TCPSocketIODevice sock: TCPSocketIODevice usock: UDPSocketIODevice btspp: BluetoothRFCommSocketIODevice all others SerialPortIODevice.
If a SerialPortIODevice is created, the Termios of this SerialSensor is copied to the device, which will then be applied when the device is opened.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_rts485, nidas::core::SerialSensor::_serialDevice, nidas::core::SerialSensor::_termios, nidas::core::DSMSensor::getDeviceName(), nidas::core::SerialPortIODevice::setRTS485(), and nidas::core::SerialPortIODevice::termios().
buildSampleScanner()
SampleScanner * SerialSensor::buildSampleScanner () virtual inherited
Calls CharacterSensor::buildSampleScanner(), and then sets the per-byte transmission delay for that scanner: SampleScanner::setUsecsPerByte().
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::CharacterSensor.
Reimplemented in nidas::dynld::GPS_NMEA_Serial.
References nidas::core::CharacterSensor::buildSampleScanner(), DLOG, nidas::core::DSMSensor::getName(), nidas::core::SerialSensor::getUsecsPerByte(), and nidas::core::SampleScanner::setUsecsPerByte().
calcStatistics()
void nidas::core::DSMSensor::calcStatistics (unsigned int periodUsec) inline inherited
Update the sensor sampling statistics.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::calcStatistics().
Referenced by nidas::core::SensorHandler::calcStatistics().
clearBuffer()
void nidas::core::DSMSensor::clearBuffer () inline protected inherited
Clear the internal buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::clearBuffer().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), and nidas::dynld::isff::CSAT3_Sonic::sendRateCommand().
close()
void PIP_Serial::close () virtual
close my associated device.
Exceptions
nidas::util::IOException;
Reimplemented from nidas::core::SerialSensor.
References nidas::core::DSMSensor::close(), nidas::core::DerivedDataReader::getInstance(), and nidas::core::DerivedDataReader::removeClient().
computeCheckSum()
unsigned short SppSerial::computeCheckSum (const unsigned char * pkt, int len) inherited
References len.
Referenced by appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and sendTimePacket().
convert()
double nidas::dynld::raf::SppSerial::convert (dsm_time_t tt, double val, unsigned int ivar) inline protected inherited
Apply a VariableConversion to an output value.
References nidas::dynld::raf::SppSerial::_converters.
Referenced by nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), and nidas::dynld::raf::SPP300_Serial::process().
deleteLooper()
void DSMSensor::deleteLooper () static inherited
References nidas::core::DSMSensor::_looper, and nidas::core::DSMSensor::_looperMutex.
Referenced by nidas::core::DSMEngine::main().
derivedDataNotify()
void PIP_Serial::derivedDataNotify (const nidas::core::DerivedDataReader * s) throw () virtual
PIP has dynamic TAS.
Implements nidas::core::DerivedDataClient.
References nidas::dynld::raf::PIP_Serial::SendPIP_BLK::chksum, nidas::dynld::raf::PIP_Serial::SendPIP_BLK::esc, nidas::util::Logger::getInstance(), nidas::dynld::raf::PIP_Serial::SendPIP_BLK::hostSyncCounter, nidas::dynld::raf::PIP_Serial::SendPIP_BLK::id, nidas::util::Logger::log(), LOG_WARNING, nidas::dynld::raf::PackDMT_ULong(), nidas::dynld::raf::PackDMT_UShort(), nidas::dynld::raf::PIP_Serial::SendPIP_BLK::PASCoefficient, nidas::dynld::raf::PIP_Serial::SendPIP_BLK::relayControl, and nidas::util::Exception::what().
distributeRaw()
void nidas::core::DSMSensor::distributeRaw (const Sample * s) inline inherited
Distribute a raw sample which has been read from my file descriptor in real time.
References nidas::core::DSMSensor::_rawSource, and nidas::core::SampleSourceSupport::distribute().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
doesAsciiSscanfs()
bool CharacterSensor::doesAsciiSscanfs () inherited
Returns
: true if this CharacterSensor as been configured to use one or more AsciiSscanf objects to parse its data.
References nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getScanfFormat(), and nidas::core::SampleTagIterator::hasNext().
Referenced by nidas::core::CharacterSensor::buildSampleScanner().
executeXmlRpc()
virtual void nidas::core::DSMSensor::executeXmlRpc (XmlRpc::XmlRpcValue & , XmlRpc::XmlRpcValue &) inline virtual inherited
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
The default base class method does nothing.
Reimplemented in nidas::dynld::raf::PSI9116_Sensor, and nidas::dynld::raf::DSMAnalogSensor.
Referenced by nidas::core::DSMEngineIntf::SensorAction::execute().
expandString()
std::string nidas::core::DSMSensor::expandString (const std::string & input) const inline inherited
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References nidas::core::DSMSensor::_dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::CalFile::open().
findVariableIndex()
VariableIndex DSMSensor::findVariableIndex (const std::string & vprefix) protected inherited
Search all the sample tags for a variable whose name starts with the given prefix, and return it's index in the list of variables in the sample tag.
If no such variable is found, return -1.
References nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTags(), and nidas::core::SampleTag::getVariables().
flush()
void nidas::core::DSMSensor::flush () inline virtual inherited
Implementation of SampleClient::flush().
This is where a DSMSensor's process() method could send out any buffered results that might be ready.
Implements nidas::core::SampleClient.
Referenced by nidas::dynld::psql::PSQLProcessor::disconnect().
fromDOMElement()
void SerialSensor::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::CharacterSensor.
Reimplemented in nidas::dynld::iss::TiltSensor, nidas::dynld::isff::Wind2D, and nidas::dynld::isff::DAUSensor.
References nidas::core::SerialSensor::_rts485, nidas::core::SerialSensor::_termios, nidas::util::Termios::EVEN, nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DSMSensor::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), nidas::util::Termios::NONE, nidas::util::Termios::ODD, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setParity(), and nidas::util::Termios::setStopBits().
Referenced by nidas::dynld::isff::DAUSensor::fromDOMElement(), nidas::dynld::isff::Wind2D::fromDOMElement(), and nidas::dynld::iss::TiltSensor::fromDOMElement().
getApplyVariableConversions()
virtual bool nidas::core::DSMSensor::getApplyVariableConversions () const inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), and nidas::dynld::raf::SppSerial::validate().
getBackslashedMessageSeparator()
const std::string nidas::core::CharacterSensor::getBackslashedMessageSeparator () const inline inherited
Get message separator with backslash sequences added back.
References nidas::core::CharacterSensor::_messageSeparator, and nidas::util::addBackslashSequences().
Referenced by nidas::core::RemoteSerialConnection::setSensor().
getBadTimeTagCount()
size_t nidas::core::DSMSensor::getBadTimeTagCount () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getBadTimeTagCount().
Referenced by nidas::core::DSMSensor::printStatus().
getBytesAvailable()
virtual size_t nidas::core::DSMSensor::getBytesAvailable () const inline virtual inherited
How many bytes are available to read on this sensor.
See also
IODevice::getBytesAvailable().
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getBytesAvailable().
Referenced by nidas::core::DatagramSampleScanner::readBuffer().
getCalFile()
CalFile * DSMSensor::getCalFile (const std::string & name) inherited
Return a CalFile by its getName().
Will return NULL if not found.
References nidas::core::DSMSensor::_calFiles.
getCalFiles()
const std::map<std::string,CalFile*>& nidas::core::DSMSensor::getCalFiles () inline inherited
Return the collection of CalFiles, mapped by name.
References nidas::core::DSMSensor::_calFiles.
Referenced by sensorTitle(), and PConfig::showCalFiles().
getCatalogName()
virtual const std::string& nidas::core::DSMSensor::getCatalogName () const inline virtual inherited
Fetch the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by SampleCounter::collectMetadata(), ExtractFast2D::countParticles(), SampleToDatabase::defaultMeasurementName(), parseOther(), nidas::core::DSMSensor::printStatus(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), and PConfig::showCalFiles().
getClassName() [1/2]
virtual const std::string& nidas::core::DSMSensor::getClassName () const inline virtual inherited
Fetch the class name.
References nidas::core::DSMSensor::_className.
Referenced by SampleCounter::collectMetadata(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getClassName(), parseAnalog(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), PConfig::showAll(), PConfig::showCalFiles(), PConfig::showSensorClasses(), and nidas::dynld::raf::UDPArincSensor::~UDPArincSensor().
getClassName() [2/2]
const string DSMSensor::getClassName (const xercesc::DOMElement * node, const Project * project) static inherited
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::Project::expandString(), nidas::core::SensorCatalog::find(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMSensor::getClassName(), and nidas::core::Project::getSensorCatalog().
getClientCount()
int nidas::core::DSMSensor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getClientCount().
getDefaultMode()
virtual int nidas::core::DSMSensor::getDefaultMode () const inline virtual inherited
How do I want to be opened.
The user can ignore it if they want to.
Returns
one of O_RDONLY, O_WRONLY or O_RDWR.
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::SensorOpener::run().
getDepth()
float nidas::core::DSMSensor::getDepth () const inline inherited
Get sensor depth below ground.
Returns
Depth of sensor below ground, in meters.
References nidas::core::DSMSensor::_height.
getDepthString()
const std::string& nidas::core::DSMSensor::getDepthString () const inline inherited
Get sensor depth below ground in a string.
Returns
Depth of sensor below ground, e.g. "5cm".
References nidas::core::DSMSensor::_depthString.
Referenced by SampleCounter::collectMetadata().
getDeviceName()
virtual const std::string& nidas::core::DSMSensor::getDeviceName () const inline virtual inherited
Fetch the name of the system device that the sensor is connected to.
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::SensorHandler::add(), nidas::core::CharacterSensor::buildIODevice(), nidas::core::SerialSensor::buildIODevice(), nidas::core::CharacterSensor::buildSampleScanner(), nidas::core::DSMSensor::close(), SampleCounter::collectMetadata(), DataStats::createCounters(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::open(), nidas::core::SerialSensor::open(), nidas::dynld::raf::UDPArincSensor::open(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), DmdA2dCk::run(), nidas::core::CharacterSensor::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), PConfig::showCalFiles(), and nidas::core::DSMSensor::validate().
getDictionary()
const Dictionary& nidas::core::DSMSensor::getDictionary () const inline inherited
References nidas::core::DSMSensor::_dictionary.
Referenced by nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::VariableConverter::fromDOMElement().
getDriverTimeTagUsecs()
virtual int nidas::core::DSMSensor::getDriverTimeTagUsecs () const inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::core::DriverSampleScanner::nextSample().
getDSMConfig()
const DSMConfig* nidas::core::DSMSensor::getDSMConfig () const inline inherited
What DSMConfig am I associated with?
References nidas::core::DSMSensor::_dsm.
Referenced by SampleCounter::collectMetadata(), DataStats::createCounters(), nidas::core::DSMSensor::fromDOMElement(), SampleCounter::generateStreamId(), nidas::core::VariableConverter::getDSMConfig(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), nidas::core::SampleTag::setDSMSensor(), and nidas::core::DSMSensor::validate().
getDSMId()
unsigned int nidas::core::DSMSensor::getDSMId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_DSM_ID.
Referenced by nidas::core::Site::findSensor(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::core::SampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), sensorTitle(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::Site::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), and nidas::core::MessageStreamScanner::warnNonIncrTimeTag().
getDSMName()
const std::string & DSMSensor::getDSMName () const inherited
Fetch the DSM name.
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getName().
Referenced by nidas::core::DSMSensor::getName().
getDuplicateIdOK()
bool nidas::core::DSMSensor::getDuplicateIdOK () const inline inherited
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
That other sensor must also agree that dupicateIdOK are OK. This can be useful if one may not be certain of the device name, e.g. /dev/ttyUSB*, that the system will assign to a sensor may use, but there are identifiers in the data returned that allow one to sort things out. In general, getDuplicateID is false.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getFullSuffix()
const std::string& nidas::core::DSMSensor::getFullSuffix () const inline inherited
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
The full sensor suffix are words 2 and 3 in the dot-separated name: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::fromDOMElement().
getHeight()
float nidas::core::DSMSensor::getHeight () const inline inherited
Get sensor height above ground.
Returns
Height of sensor above ground, in meters. Nan if unknown.
References nidas::core::DSMSensor::_height.
getHeightString()
const std::string& nidas::core::DSMSensor::getHeightString () const inline inherited
Get sensor height above ground in a string.
Returns
Height of sensor above ground, e.g. "15m".
References nidas::core::DSMSensor::_heightString.
Referenced by SampleCounter::collectMetadata(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), ARLIngest::prepareHeaderIds(), SampleToDatabase::SampleToDatabase(), and PConfig::showCalFiles().
getId()
dsm_sample_id_t nidas::core::DSMSensor::getId () const inline inherited
Get the various levels of the samples identification.
A sample tag ID is a 32-bit value comprised of four parts: 6-bit sample type id(not used by DSMSensor), a 10-bit DSM id, 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and GET_FULL_ID.
Referenced by DataStats::createCounters(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::TimetagAdjuster::log(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::DSMArincSensor::processAlta(), nidas::core::SampleTag::SampleTag(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getInitString()
const std::string& nidas::core::CharacterSensor::getInitString () const inline inherited
References nidas::core::CharacterSensor::_initString.
Referenced by nidas::core::CharacterSensor::sendInitString().
getIODevice()
IODevice* nidas::core::DSMSensor::getIODevice () const inline protected inherited
References nidas::core::DSMSensor::_iodev.
getLagSecs()
virtual double nidas::core::DSMSensor::getLagSecs () const inline protected virtual inherited
Return the sampling lag for this sensor in seconds.
See getLagUsecs().
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
getLagUsecs()
virtual int nidas::core::DSMSensor::getLagUsecs () const inline protected virtual inherited
Return the sampling lag for this sensor in microseconds.
A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. Derived classes can use this method in their process method to correct for inherent, constant, sampling lags of a sensor. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
<sensor>
    <parameter name="lag" type = "float" value="0.186"/>
</sensor>
The DSMSensor::fromDOM() method parses this parameter and sets the value of the lag.
References nidas::core::DSMSensor::_lag.
Referenced by nidas::core::CharacterSensor::adjustTimeTag(), and nidas::dynld::raf::UHSAS_Serial::process().
getLatency()
virtual float nidas::core::DSMSensor::getLatency () const inline virtual inherited
References nidas::core::DSMSensor::_latency.
getLocation()
const std::string & DSMSensor::getLocation () const inherited
Location string.
A DSMConfig also has a Location. If the location has not been set for this DSMSensor, then the location of the DSMConfig will be returned.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMSensor::_location, and nidas::core::DSMConfig::getLocation().
Referenced by SampleCounter::collectMetadata(), and nidas::core::DSMSensor::printStatusHeader().
getLooper()
Looper * DSMSensor::getLooper () static protected inherited
Fetch a pointer to a static instance of a Looper thread.
Use this Looper for periodic callbacks, as for prompting, in support of a DSMSensor.
References nidas::core::DSMSensor::_looper, nidas::core::DSMSensor::_looperMutex, nidas::util::Logger::getInstance(), nidas::util::Thread::getPolicyString(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::setThreadScheduler(), and nidas::util::Exception::what().
Referenced by nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
getMaxSampleLength()
unsigned int nidas::core::DSMSensor::getMaxSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMaxSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
getMaxScanfFields()
int nidas::core::CharacterSensor::getMaxScanfFields () const inline inherited
The maximum number of fields in any of the AsciiSscanfs for this CharacterSensor.
Prior to scanning a message, a sample of this size must be allocated.
References nidas::core::CharacterSensor::_maxScanfFields.
getMessageLength()
int nidas::core::CharacterSensor::getMessageLength () const inline inherited
References nidas::core::CharacterSensor::_messageLength.
Referenced by nidas::core::CharacterSensor::buildSampleScanner(), nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::core::SerialSensor::open(), nidas::dynld::isff::CSAT3_Sonic::open(), and nidas::core::RemoteSerialConnection::setSensor().
getMessageSeparator()
const std::string& nidas::core::CharacterSensor::getMessageSeparator () const inline inherited
Get message separator with backslash sequences replaced by their intended character.
References nidas::core::CharacterSensor::_messageSeparator.
Referenced by nidas::core::CharacterSensor::buildSampleScanner(), nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::core::SerialSensor::open(), nidas::dynld::isff::CSAT3_Sonic::open(), and nidas::dynld::raf::CDP_Serial::validate().
getMessageSeparatorAtEOM()
bool nidas::core::CharacterSensor::getMessageSeparatorAtEOM () const inline inherited
References nidas::core::CharacterSensor::_separatorAtEOM.
Referenced by nidas::core::CharacterSensor::buildSampleScanner(), nidas::dynld::isff::CSAT3_Sonic::open(), and nidas::core::RemoteSerialConnection::setSensor().
getMinSampleLength()
unsigned int nidas::core::DSMSensor::getMinSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMinSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
getName()
virtual std::string nidas::core::DSMSensor::getName () const inline virtual inherited
Return a name that should fully identify this sensor.
This name could be used in informative messages. The returned name has this format: dsmName:deviceName.
References nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::getDSMName().
Referenced by nidas::core::SensorHandler::add(), nidas::core::SamplePipeline::addSampleClient(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::SerialSensor::buildSampleScanner(), nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::Arinc_IRS::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::core::SensorHandler::PolledDSMSensor::getName(), nidas::core::SensorHandler::incrementFullBufferReads(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::core::TimetagAdjuster::log(), nidas::core::SerialSensor::open(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::AlicatSDI::open(), open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::UHSAS_Serial::open(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::core::DSMSensor::printStatusHeader(), nidas::dynld::raf::UDPArincSensor::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::SampleScanner::readBuffer(), nidas::core::DatagramSampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), nidas::core::SensorOpener::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), nidas::dynld::raf::TwoD_USB::sendTrueAirspeed(), nidas::core::DSMConfig::sensorFromDOMElement(), nidas::dynld::A2DSensor::setA2DParameters(), nidas::dynld::A2DSensor::setConversionCorrection(), nidas::core::CharacterSensor::setMessageParameters(), nidas::core::RemoteSerialConnection::setSensor(), PConfig::showAll(), nidas::core::CharacterSensor::startPrompting(), nidas::core::CharacterSensor::stopPrompting(), nidas::dynld::isff::CSAT3_Sonic::terminalMode(), nidas::core::CharacterSensor::validate(), nidas::core::DSMSensor::validate(), nidas::core::Site::validate(), nidas::dynld::A2DSensor::validate(), nidas::dynld::raf::AlicatSDI::validate(), nidas::dynld::raf::CDP_Serial::validate(), validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), nidas::dynld::raf::UDPArincSensor::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::CharacterSensor::validateSscanfs(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), nidas::core::MessageStreamScanner::warnNonIncrTimeTag(), nidas::dynld::WxtSensor::wxtValidateSscanfs(), and nidas::dynld::raf::UHSAS_Serial::~UHSAS_Serial().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNonConstSampleTags()
virtual const std::list<SampleTag*>& nidas::core::DSMSensor::getNonConstSampleTags () inline virtual inherited
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
References nidas::core::DSMSensor::_sampleTags.
getNullTerminated()
bool nidas::core::CharacterSensor::getNullTerminated () const inline inherited
References nidas::core::SampleScanner::getNullTerminate(), and nidas::core::DSMSensor::getSampleScanner().
Referenced by nidas::core::RemoteSerialConnection::setSensor().
getNumScanfFailures()
int nidas::core::CharacterSensor::getNumScanfFailures () const inline inherited
How many samples have resulted in complete scanf failures - nothing parsed, because the sensor messages do not correspond to the sscanf format.
References nidas::core::CharacterSensor::_scanfFailures.
getNumScanfPartials()
int nidas::core::CharacterSensor::getNumScanfPartials () const inline inherited
How many samples have been partially scanned, because a character in the middle of a message conflicts with the sscanf format.
References nidas::core::CharacterSensor::_scanfPartials.
getObservedDataRate()
float nidas::core::DSMSensor::getObservedDataRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedDataRate().
Referenced by nidas::core::DSMSensor::printStatus().
getObservedSamplingRate()
float nidas::core::DSMSensor::getObservedSamplingRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedSamplingRate().
Referenced by nidas::core::DSMSensor::printStatus().
getParameter()
const Parameter * DSMSensor::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::DSMSensor::_parameters.
Referenced by nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::dynld::raf::UHSAS_Serial::open(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), nidas::dynld::raf::AlicatSDI::validate(), nidas::dynld::raf::CDP_Serial::validate(), validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::raf::UDPArincSensor::validate().
getParameters()
const std::list<const Parameter*>& nidas::core::DSMSensor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::DSMSensor::_constParameters.
Referenced by nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), and nidas::dynld::A2DSensor::validate().
getProcessedSampleSource()
SampleSource* nidas::core::DSMSensor::getProcessedSampleSource () inline virtual inherited
Implementation of SampleSource::getProcessedSampleSource().
Return the SampleSource for processed samples from this DSMSensor.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::RawSampleService::schedule().
getPromptOffset()
double nidas::core::CharacterSensor::getPromptOffset () const inline protected inherited
References nidas::core::CharacterSensor::_promptOffset.
Referenced by nidas::core::CharacterSensor::validate().
getPromptRate()
double nidas::core::CharacterSensor::getPromptRate () const inline protected inherited
References nidas::core::CharacterSensor::_promptRate.
Referenced by nidas::core::CharacterSensor::validate().
getPrompts()
const std::list<Prompt>& nidas::core::CharacterSensor::getPrompts () const inline inherited
References nidas::core::CharacterSensor::_prompts.
Referenced by nidas::core::SerialSensor::initPrompting(), and nidas::core::CharacterSensor::validate().
getPromptString()
const std::string& nidas::core::CharacterSensor::getPromptString () const inline protected inherited
References nidas::core::CharacterSensor::_promptString.
Referenced by nidas::core::CharacterSensor::validate().
getRawSampleSource()
SampleSource* nidas::core::DSMSensor::getRawSampleSource () inline virtual inherited
Implementation of SampleSource::getRawSampleSource().
Return the SampleSource for raw samples from this DSMSensor. A DSMSensor is only a SampleSource of raw samples when running in real-time, not during post-processing.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_rawSource.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::dynld::RawSampleService::schedule(), and nidas::core::RemoteSerialConnection::setSensor().
getRawSampleTag()
const SampleTag* nidas::core::DSMSensor::getRawSampleTag () const inline inherited
Convenience function to get my one-and-only raw SampleTag().
Equivalent to: getRawSampleSource()->getSampleTags()->front()
References nidas::core::DSMSensor::_rawSampleTag.
Referenced by nidas::core::SamplePipeline::addSampleClient(), nidas::core::SamplePipeline::addSampleClientForTag(), nidas::dynld::RawSampleService::connect(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::dynld::raf::SyncServer::initSensors(), nidas::core::SamplePipeline::removeSampleClient(), nidas::core::SamplePipeline::removeSampleClientForTag(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
getReadFd()
virtual int nidas::core::DSMSensor::getReadFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getReadFd().
Referenced by nidas::core::SensorHandler::PolledDSMSensor::getFd(), nidas::core::SerialSensor::open(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), and nidas::core::SampleScanner::readBuffer().
getSampleScanner()
SampleScanner* nidas::core::DSMSensor::getSampleScanner () const inline protected inherited
References nidas::core::DSMSensor::_scanner.
Referenced by nidas::core::CharacterSensor::getNullTerminated(), and nidas::core::CharacterSensor::setMessageParameters().
getSampleStats()
const SampleStats& nidas::core::DSMSensor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::DSMSensor::getSampleTagIterator () const inline virtual inherited
Implements nidas::core::SampleSource.
Referenced by nidas::core::SamplePipeline::connect(), DataStats::createCounters(), nidas::core::SamplePipeline::disconnect(), nidas::core::CharacterSensor::doesAsciiSscanfs(), nidas::core::Site::findSensor(), nidas::dynld::WxtSensor::init(), PConfig::loadVariables(), parseAnalog(), parseOther(), DataPrep::run(), StatsProcess::run(), SampleDispatcher::SampleDispatcher(), DumpClient::setSensors(), PConfig::showAll(), and nidas::core::DSMSensor::toDOMParent().
getSampleTags() [1/2]
std::list<SampleTag*>& nidas::core::DSMSensor::getSampleTags () inline inherited
Non-const method to get a list of non-const pointers to SampleTags.
References nidas::core::DSMSensor::_sampleTags.
getSampleTags() [2/2]
std::list<const SampleTag*> nidas::core::DSMSensor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::DSMSensor::findVariableIndex(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), PConfig::showCalFiles(), nidas::core::CharacterSensor::validate(), nidas::dynld::A2DSensor::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getScanfers()
const std::list<AsciiSscanf*>& nidas::core::CharacterSensor::getScanfers () const inline inherited
Return the list of AsciiSscanfs requested for this CharacterSensor.
This list is only valid after the init() method has been called.
References nidas::core::CharacterSensor::_sscanfers.
Referenced by nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::isff::ATIK_Sonic::process(), and nidas::dynld::WxtSensor::wxtValidateSscanfs().
getSensorId()
unsigned int nidas::core::DSMSensor::getSensorId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_SPS_ID.
Referenced by SampleToDatabase::defaultMeasurementName(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::CSAT3_Sonic::open(), ARLIngest::prepareHeaderIds(), nidas::core::SampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), sensorTitle(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::DSMSensor::validate(), nidas::core::Site::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), and nidas::core::MessageStreamScanner::warnNonIncrTimeTag().
getSite()
const Site * DSMSensor::getSite () const inherited
What Site am I associated with?
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getSite().
Referenced by SampleCounter::collectMetadata(), and nidas::core::DSMSensor::fromDOMElement().
getStation()
int nidas::core::DSMSensor::getStation () const inline inherited
References nidas::core::DSMSensor::_station.
Referenced by nidas::core::DSMSensor::fromDOMElement().
getSuffix()
const std::string& nidas::core::DSMSensor::getSuffix () const inline inherited
Sensor suffix, which is added to variable names.
It is only necessary to have a sensor suffix to make variable names unique. For example, if there are multiple sensors at the same height, with common variable names, then one can use a sensor suffix to make unique names. The sensor suffix is the second dot-separated word in a variable name, where only the first word is required: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_suffix.
Referenced by ExtractFast2D::countParticles(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), nidas::core::DSMSensor::setDepth(), and nidas::core::DSMSensor::setHeight().
getTermios()
const nidas::util::Termios& nidas::core::SerialSensor::getTermios () const inline inherited
Get a read-only copy of the Termios.
References nidas::core::SerialSensor::_termios.
Referenced by nidas::core::RemoteSerialConnection::setSensor().
getTimeoutCount()
int nidas::core::DSMSensor::getTimeoutCount () const inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::DSMSensor::close().
getTimeoutMsecs()
virtual int nidas::core::DSMSensor::getTimeoutMsecs () const inline virtual inherited
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs(), and nidas::core::RemoteSerialConnection::setSensor().
getTokenValue()
bool nidas::core::DSMSensor::getTokenValue (const std::string & token, std::string & value) const inline inherited
Implement a lookup for tokens that I know about, like $HEIGHT.
For other tokens, call getDSMConfig()->getTokenValue(token,value);
References nidas::core::DSMSensor::_dictionary, and nidas::core::DSMSensor::MyDictionary::getTokenValue().
getTypeName()
virtual const std::string& nidas::core::DSMSensor::getTypeName (void) const inline virtual inherited
Get the type name of this sensor.
References nidas::core::DSMSensor::_typeName.
getUsecsPerByte()
int SerialSensor::getUsecsPerByte () const inherited
If the underlying IODevice is a SerialPortIODevice, return the value of SerialPortIODevice::getUsecsPerByte(), otherwise return 0, which means no timetag correction for transmission delay will be applied.
References nidas::core::SerialSensor::_serialDevice, and nidas::core::SerialPortIODevice::getUsecsPerByte().
Referenced by nidas::core::SerialSensor::buildSampleScanner().
getVariableIterator()
VariableIterator DSMSensor::getVariableIterator () const inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), DataPrep::matchVariables(), and nidas::core::Site::validate().
getWriteFd()
virtual int nidas::core::DSMSensor::getWriteFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getWriteFd().
Referenced by main(), and nidas::core::SerialSensor::open().
incrementTimeoutCount()
void nidas::core::DSMSensor::incrementTimeoutCount () inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::SensorOpener::run().
init()
void CharacterSensor::init () virtual inherited
Initialize the CharacterSensor instance for post-processing.
This should only be done after the CharacterSensor has been initialized with fromDOMElement. Calls validateSscanfs.
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::DSMSensor.
Reimplemented in nidas::dynld::WxtSensor, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::SidsNetSensor, nidas::dynld::raf::A2D_Serial, nidas::dynld::isff::DAUSensor, and nidas::dynld::IEEE_Float.
References nidas::core::CharacterSensor::_maxScanfFields, nidas::core::CharacterSensor::_nextSscanfer, nidas::core::CharacterSensor::_sscanfers, nidas::core::CharacterSensor::_ttadjusters, nidas::core::SampleTag::getId(), nidas::core::Variable::getLength(), nidas::core::DSMSensor::getName(), nidas::core::AsciiSscanf::getNumberOfFields(), nidas::core::SampleTag::getRate(), nidas::core::DSMSensor::getSampleTags(), nidas::core::SampleTag::getScanfFormat(), nidas::core::SampleTag::getTimetagAdjust(), nidas::core::SampleTag::getVariables(), nidas::core::DSMSensor::init(), nidas::util::replaceBackslashSequences(), nidas::core::AsciiSscanf::setFormat(), nidas::core::AsciiSscanf::setSampleTag(), nidas::core::CharacterSensor::validateSscanfs(), and nidas::util::Exception::what().
Referenced by nidas::dynld::raf::BCPD_Serial::BCPD_Serial(), nidas::dynld::raf::CDP_Serial::CDP_Serial(), nidas::dynld::isff::DAUSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), PIP_Serial(), nidas::dynld::raf::SPP100_Serial::SPP100_Serial(), nidas::dynld::raf::SPP200_Serial::SPP200_Serial(), and nidas::dynld::raf::SPP300_Serial::SPP300_Serial().
initPrompting()
void SerialSensor::initPrompting () protected inherited
Perform whatever is necessary to initialize prompting right after the device is opened.
Exceptions
nidas::util::IOException
References nidas::core::SerialSensor::_prompters, nidas::core::Prompt::getOffset(), nidas::core::CharacterSensor::getPrompts(), nidas::core::Prompt::getRate(), nidas::core::Prompt::getString(), nidas::core::CharacterSensor::isPrompted(), MSECS_PER_SEC, nidas::util::replaceBackslashSequences(), nidas::core::SerialSensor::Prompter::setPrompt(), nidas::core::SerialSensor::Prompter::setPromptOffsetMsec(), nidas::core::SerialSensor::Prompter::setPromptPeriodMsec(), and nidas::core::SerialSensor::startPrompting().
Referenced by nidas::core::SerialSensor::open().
ioctl()
virtual void nidas::core::DSMSensor::ioctl (int request, void * buf, size_t len) inline virtual inherited
Perform an ioctl on the device.
request is an integer value which must be supported by the device. Normally this is a value from a header file for the device.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, nidas::core::IODevice::ioctl(), and len.
Referenced by nidas::dynld::raf::IRIGSensor::checkClock(), nidas::dynld::raf::IRIGSensor::getIRIGTime(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::dynld::raf::TwoD_USB::sendTrueAirspeed(), and nidas::dynld::raf::IRIGSensor::setIRIGTime().
isPrompted()
virtual bool nidas::core::CharacterSensor::isPrompted () const inline virtual inherited
Is this a prompted sensor.
Will be true if setPromptString() has been called with a non-empty string, and setPromptRate() has been called with a rate other than IRIG_ZERO_HZ.
References nidas::core::CharacterSensor::_prompted.
Referenced by nidas::core::SerialSensor::initPrompting(), nidas::core::RemoteSerialConnection::setSensor(), nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
isPrompting()
bool nidas::core::SerialSensor::isPrompting () const inline virtual inherited
Is prompting active, i.e.
isPrompted() is true, and startPrompting has been called?
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_prompting.
nextSample()
virtual Sample* nidas::core::DSMSensor::nextSample () inline virtual inherited
Extract the next sample from the buffer.
Returns a null pointer if there are no samples left in the buffer.
Reimplemented in nidas::dynld::raf::UDPArincSensor, and nidas::dynld::raf::A2D_Serial.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::nextSample().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::raf::A2D_Serial::nextSample(), nidas::dynld::raf::UDPArincSensor::nextSample(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::DSMSensor::readSample(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
open()
void PIP_Serial::open (int flags) virtual
open the sensor and perform any intialization to the driver.
Reimplemented from nidas::core::SerialSensor.
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), nidas::util::Logger::getInstance(), nidas::core::DSMSensor::getName(), nidas::util::Logger::log(), LOG_WARNING, and nidas::core::SerialSensor::open().
packetLen()
int nidas::dynld::raf::PIP_Serial::packetLen () const inline protected virtual
Return the expected data packet length in bytes based on the number of channels being used.
Implements nidas::dynld::raf::SppSerial.
Referenced by appendDataAndFindGood(), PIP_Serial(), process(), sendInitString(), and validate().
printStatus()
void SerialSensor::printStatus (std::ostream & ostr) throw () virtual inherited
Reimplemented from nidas::core::DSMSensor.
Reimplemented in nidas::dynld::raf::A2D_Serial.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, nidas::core::DSMSensor::printStatus(), and nidas::util::Exception::what().
printStatusHeader()
void DSMSensor::printStatusHeader (std::ostream & ostr) inherited
References nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::zebra.
Referenced by nidas::core::DSMEngineStat::run().
printStatusTrailer()
void DSMSensor::printStatusTrailer (std::ostream & ostr) inherited
Referenced by nidas::core::DSMEngineStat::run().
process()
bool PIP_Serial::process (const Sample * , std::list< const Sample * > & result) virtual
Process a raw sample, which in this case means do a sscanf on the character string contents, creating a processed sample of binary floating point data.
Exceptions
Reimplemented from nidas::core::CharacterSensor.
References nidas::dynld::raf::SppSerial::_nChannels, nidas::dynld::raf::SppSerial::_noutValues, nidas::dynld::raf::SppSerial::_nWaitingData, nidas::dynld::raf::SppSerial::_outputDeltaT, nidas::dynld::raf::SppSerial::_prevTime, nidas::dynld::raf::SppSerial::_waitingData, appendDataAndFindGood(), nidas::dynld::raf::PIP_Serial::PIP_blk::binCount, nidas::dynld::raf::PIP_Serial::PIP_blk::chksum, nidas::dynld::raf::SppSerial::convert(), nidas::dynld::raf::PIP_Serial::PIP_blk::DOFRejectCount, nidas::dynld::raf::PIP_Serial::PIP_blk::EndRejectCount, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::DSMSensor::getId(), nidas::core::Sample::getTimeTag(), nidas::dynld::raf::PIP_Serial::PIP_blk::housekeeping, nidas::dynld::raf::PIP_Serial::PIP_blk::oversizeReject, packetLen(), PIPCBTMP, PIPEDV0, PIPEDV32, PIPEDV64, PIPLSRC, PIPLSRP, nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), nidas::dynld::raf::UnpackDMT_UShort(), and USECS_PER_SEC.
read() [1/2]
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len) inline virtual inherited
Read from the device (duh).
Behaves like the read(2) system call, without a file descriptor argument, and with an IOException.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
Referenced by main(), nidas::core::SampleScanner::readBuffer(), nidas::core::DatagramSampleScanner::readBuffer(), and nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck().
read() [2/2]
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len, int msecTimeout) inline virtual inherited
Read from the device with a timeout.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
readBuffer() [1/2]
bool nidas::core::DSMSensor::readBuffer () inline inherited
Read into my SampleScanner's buffer.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::DSMSensor::readSample(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
readBuffer() [2/2]
bool nidas::core::DSMSensor::readBuffer (int msecTimeout) inline inherited
Read into my SampleScanner's buffer.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
readSample()
Sample * DSMSensor::readSample () virtual inherited
Return the next sample.
Buffer(s) will be read if necessary.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
Referenced by DmdA2dCk::run().
readSamples()
bool DSMSensor::readSamples () virtual inherited
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
This method is called by SensorHander, when select/poll indicates that data is available on the file descriptor returned by getReadFd(). This is a convienence method which does a readBuffer() to read available data from the DSMSensor into a buffer, and then repeatedly calls nextSample() to extract all samples out of that buffer.
Exceptions
nidas::util::IOException;
References nidas::core::DSMSensor::_rawSource, nidas::core::SampleSourceSupport::distribute(), DLOG, nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getName(), nidas::core::Project::getName(), nidas::core::DSMConfig::getProject(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
Referenced by DmdA2dCk::run().
receive()
bool DSMSensor::receive (const Sample * s) virtual inherited
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
In real-time operations, a DSMSensor can be added as a raw SampleClient of itself, using addRawSampleClient(). In post-processing, a DSMSensor typically receives samples with its own sample id from a SampleSorter. receive() then applies further processing via the process() method.
Implements nidas::core::SampleClient.
References nidas::core::DSMSensor::_source, nidas::core::SampleSourceSupport::distribute(), and nidas::core::DSMSensor::process().
removeCalFiles()
void DSMSensor::removeCalFiles () inherited
Remove all CalFiles.
References nidas::core::DSMSensor::_calFiles.
Referenced by nidas::core::DSMSensor::~DSMSensor().
removeSampleClient()
void nidas::core::DSMSensor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by nidas::core::SamplePipeline::removeSampleClient(), and nidas::core::SamplePipeline::removeSampleClientForTag().
removeSampleClientForTag()
void nidas::core::DSMSensor::removeSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
Referenced by nidas::core::SamplePipeline::removeSampleClientForTag().
removeSampleTag() [1/2]
void DSMSensor::removeSampleTag (const SampleTag * val) private virtual inherited
DSMSensor does not provide public support for SampleSource::removeSampleTag(const SampleTag* val)
Exceptions
Implements nidas::core::SampleSource.
removeSampleTag() [2/2]
void DSMSensor::removeSampleTag (SampleTag * val) virtual inherited
Remove val from the list of SampleTags, and delete it.
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleTag().
reopenOnIOException()
virtual bool nidas::core::DSMSensor::reopenOnIOException () const inline virtual inherited
Whether to reopen this sensor on an IOException.
The base method returns true. Over-ride if a reopen should not be attempted.
scanSample()
int CharacterSensor::scanSample (AsciiSscanf * sscanf, const char * inputstr, float * data_ptr) protected virtual inherited
Reimplemented in nidas::dynld::WxtSensor.
References nidas::core::AsciiSscanf::getNumberOfFields(), and nidas::core::AsciiSscanf::sscanf().
searchSampleScanners()
SampleT< float > * CharacterSensor::searchSampleScanners (const Sample * samp, SampleTag ** stag_out = 0) throw () protected inherited
Search through the AsciiSscanf instances attached to this sensor, looking for the next scanner which parses at least one variable from the given raw sample.
The search picks up after the last scanner which matched a sample. The parsed values are added to a new Sample, and a pointer to the new Sample is returned. If stag_out is non-null, it is set to the SampleTag pointer for the AsciiSscanf which matched. If no scanners match this sample, then this returns null. The returned Sample has a reference which must be freed by the caller or passed on. Any unparsed variables in the returned sample are filled with NaN using trimUnparsed(). The time tag of the new Sample is set to the time of raw sample samp. No other time tag adjustments or variable conversions are applied, that is up to the caller.
References nidas::util::LogContext::active(), nidas::core::CHAR_ST, nidas::core::SampleT< DataT >::freeReference(), nidas::core::SampleT< DataT >::getConstVoidDataPtr(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::AsciiSscanf::getFormat(), nidas::core::SampleTag::getId(), nidas::core::AsciiSscanf::getNumberOfFields(), nidas::core::AsciiSscanf::getSampleTag(), nidas::util::LogContext::log(), LOG_DEBUG, nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by nidas::core::CharacterSensor::process().
sendInitPacketAndCheckAck()
void SppSerial::sendInitPacketAndCheckAck (void * packet, int len, int return_len = 2) protected virtual inherited
Send pre-packaged initialization packet to SPP probe and wait for acknowledge packet.
@parameter packet is the pre-populated intialization packet to send. @parameter len is the length in bytes of the above packet. @parameter return_len is the length of the return packet from the probe.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::clearBuffer(), nidas::core::DSMSensor::getName(), ILOG, len, MSECS_PER_SEC, nidas::core::DSMSensor::read(), nidas::core::DSMSensor::readBuffer(), nidas::core::SerialSensor::setMessageParameters(), setup_pkt, nidas::util::UTime::toUsecs(), USECS_PER_SEC, nidas::util::Exception::what(), and nidas::core::DSMSensor::write().
Referenced by nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and sendTimePacket().
sendInitString()
void PIP_Serial::sendInitString () virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::CharacterSensor.
References _airspeedSource, _dofReject, _InitPacketSize, nidas::dynld::raf::SppSerial::computeCheckSum(), nidas::core::DSMSensor::getName(), nidas::dynld::raf::PackDMT_UShort(), packetLen(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::core::SerialSensor::setMessageParameters(), setup_pkt, and nidas::util::Exception::what().
sendTimePacket()
void PIP_Serial::sendTimePacket () protected
Set probe time.
References _setTimePacketSize, nidas::dynld::raf::PIP_Serial::SetAbsoluteTime::chksum, nidas::dynld::raf::SppSerial::computeCheckSum(), nidas::dynld::raf::PIP_Serial::SetAbsoluteTime::esc, nidas::dynld::raf::PIP_Serial::SetAbsoluteTime::hour, nidas::dynld::raf::PIP_Serial::SetAbsoluteTime::id, nidas::dynld::raf::PackDMT_UShort(), and nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck().
setApplyVariableConversions()
virtual void nidas::core::DSMSensor::setApplyVariableConversions (bool val) inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setCatalogName()
virtual void nidas::core::DSMSensor::setCatalogName (const std::string & val) inline virtual inherited
Set the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setClassName()
virtual void nidas::core::DSMSensor::setClassName (const std::string & val) inline virtual inherited
Set the class name.
In the usual usage this method is not used, and getClassName() is over-ridden in a derived class to return a constant string.
References nidas::core::DSMSensor::_className.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setDefaultMode()
virtual void nidas::core::DSMSensor::setDefaultMode (int val) inline virtual inherited
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SerialSensor::SerialSensor(), and nidas::dynld::raf::TwoD_USB::TwoD_USB().
setDepth() [1/2]
void DSMSensor::setDepth (const std::string & val) inherited
Set sensor depth below ground via a string which is added to variable names.
Parameters
val String containing sensor below and units in meters (m) or centimeters(cm), e.g. "5cm". This depth string is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setDepth() [2/2]
void DSMSensor::setDepth (float val) inherited
Set sensor depth below ground.
Parameters
val depth below ground, in meters. The depth is converted to centimeters and is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
setDeviceName()
virtual void nidas::core::DSMSensor::setDeviceName (const std::string & val) inline virtual inherited
Set the name of the system device that the sensor is connected to.
Parameters
val Name of device, e.g. "/dev/xxx0".
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and main().
setDriverTimeTagUsecs()
virtual void nidas::core::DSMSensor::setDriverTimeTagUsecs (int val) inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::dynld::raf::DSMArincSensor::buildIODevice(), and nidas::dynld::raf::IRIGSensor::buildSampleScanner().
setDSMConfig()
void DSMSensor::setDSMConfig (const DSMConfig * val) inherited
Set the DSMConfig for this sensor.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMConfig::getId(), and nidas::core::DSMSensor::setDSMId().
Referenced by nidas::core::DSMConfig::sensorFromDOMElement(), and nidas::core::SensorHandler::~SensorHandler().
setDSMId()
void nidas::core::DSMSensor::setDSMId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_DSM_ID.
Referenced by nidas::core::DSMSensor::setDSMConfig().
setDuplicateIdOK()
void nidas::core::DSMSensor::setDuplicateIdOK (bool val) inline inherited
Set the duplicate ID attribute of this DSMSensor.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setFullSuffix()
void nidas::core::DSMSensor::setFullSuffix (const std::string & val) inline protected inherited
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
setHeight() [1/2]
void DSMSensor::setHeight (const std::string & val) inherited
Set sensor height above ground via a string which is added to variable names.
Parameters
val String containing sensor height and units in meters (m) or centimeters(cm), e.g. "15m". This height string is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setHeight() [2/2]
void DSMSensor::setHeight (float val) inherited
Set sensor height above ground.
Parameters
val height above ground, in meters. The height is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
setId()
void nidas::core::DSMSensor::setId (dsm_sample_id_t val) inline inherited
Set the various levels of the sensor identification.
A sensor ID is a 32-bit value comprised of four parts: 6-bit sample type id (not used by DSMSensor), 10-bit DSM id, and 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and SET_FULL_ID.
setInitString()
void nidas::core::CharacterSensor::setInitString (const std::string & val) inline inherited
Set the initialization string(s) for this sensor.
The init string may contain backslash escape sequences like the prompt string.
References nidas::core::CharacterSensor::_initString.
Referenced by nidas::core::CharacterSensor::fromDOMElement().
setIODevice()
void nidas::core::DSMSensor::setIODevice (IODevice * val) inline inherited
Set the IODevice for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_iodev.
setLagSecs()
virtual void nidas::core::DSMSensor::setLagSecs (double val) inline protected virtual inherited
Set the sampling lag for this sensor in seconds.
This lag should then used to correct the timetags of the processed samples in the process() method of derived classes. Note that this lag is not used to alter the timetags of the raw samples. Raw samples are saved with the un-altered timetag that was determined at the moment they were sampled.
The lag is stored as a signed integer of microseconds, so lags should be between += 2147 seconds. No warning or exception is given if the value exceeds that limit. If your lag is greater than that I suggest you junk your sensor! A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
<parameter name="lag" type = "float" value="0.186"/>
The DSMSensor::fromDOM() method parses this parameter and calls this method to set the lag. process() methods in derived classes must apply this lag value. The DSMSensor base class does not adjust time tags of processed samples.
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setLatency()
virtual void nidas::core::DSMSensor::setLatency (float val) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the driver for a 1/10 sec, then send the data to user space. Generally it should be set before doing a sensor open().
Parameters
val Latency, in seconds.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DSMSensor::_latency.
Referenced by nidas::dynld::A2DSensor::A2DSensor(), nidas::core::DSMSensor::fromDOMElement(), and nidas::dynld::A2DSensor::validate().
setLocation()
void nidas::core::DSMSensor::setLocation (const std::string & val) inline inherited
References nidas::core::DSMSensor::_location.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setMessageParameters()
void SerialSensor::setMessageParameters (unsigned int len, const std::string & sep, bool eom) virtual inherited
Set message separator and message length parameters, which are used to parse and time-tag samples from the IODevice.
Exceptions
nidas::util::InvalidParameterException,nidas::util::IOException
Reimplemented from nidas::core::CharacterSensor.
References len, and nidas::core::CharacterSensor::setMessageParameters().
Referenced by nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::terminalMode(), nidas::dynld::raf::CDP_Serial::validate(), and validate().
setPromptOffset()
void nidas::core::CharacterSensor::setPromptOffset (const double val) inline protected inherited
References nidas::core::CharacterSensor::_promptOffset.
Referenced by nidas::core::CharacterSensor::fromDOMElement().
setPromptRate()
void nidas::core::CharacterSensor::setPromptRate (const double val) inline protected inherited
Set the rate at which <sensor> prompts are sent to this sensor.
This will be set on a CharacterSensor if a <prompt> element is found for <sensor>, not as a sub-element of <sample>.
References nidas::core::CharacterSensor::_promptRate.
Referenced by nidas::core::CharacterSensor::fromDOMElement().
setPromptString()
void nidas::core::CharacterSensor::setPromptString (const std::string & val) inline protected inherited
Set the <sensor> prompt string for this sensor.
The prompt string may contain backslash escape sequences and null characters, so be carefull when copying to a char*.
References nidas::core::CharacterSensor::_promptString.
Referenced by nidas::core::CharacterSensor::fromDOMElement().
setSampleScanner()
void nidas::core::DSMSensor::setSampleScanner (SampleScanner * val) inline inherited
Set the SampleScanner for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_scanner.
setSensorId()
void nidas::core::DSMSensor::setSensorId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_SPS_ID.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setStation()
void DSMSensor::setStation (int val) inherited
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_station, and nidas::core::SampleTag::setStation().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setSuffix()
void DSMSensor::setSuffix (const std::string & val) inherited
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::_suffix, and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setTimeoutMsecs()
virtual void nidas::core::DSMSensor::setTimeoutMsecs (int val) inline virtual inherited
Set the sensor timeout value in milliseconds.
A value of 0 means no timeout (e.g. infinite). If no data is received for this period, then the sensor is closed, and re-opened. For efficiency reasons, the system may not actually detect a sensor timeout of less than 1 second, so setting it to less than 1000 milliseconds will likely not reduce the time before a sensor timeout is detected.
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::RemoteSerialConnection::doEscCmds(), and nidas::core::DSMSensor::fromDOMElement().
setTypeName()
virtual void nidas::core::DSMSensor::setTypeName (const std::string & val) inline virtual inherited
Set the type name of this sensor, e.g.
: "ACME Model 99 Mach7 Particle Disambiguator". This is meant for descriptive purposes only, and is not meant to change the behavior of a sensor object.
References nidas::core::DSMSensor::_typeName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
shutdownPrompting()
void SerialSensor::shutdownPrompting () protected inherited
Shutdown prompting, typically done when a device is closed.
Exceptions
nidas::util::IOException
References nidas::core::SerialSensor::_prompters, and nidas::core::SerialSensor::stopPrompting().
Referenced by nidas::core::SerialSensor::close().
startPrompting()
void SerialSensor::startPrompting () virtual inherited
Start the prompters.
They can be started and stopped multiple times once a SerialSensor is opened.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_prompters, nidas::core::SerialSensor::_prompting, nidas::core::Looper::addClient(), nidas::core::DSMSensor::getLooper(), nidas::core::SerialSensor::Prompter::getPromptOffsetMsec(), nidas::core::SerialSensor::Prompter::getPromptPeriodMsec(), and nidas::core::CharacterSensor::isPrompted().
Referenced by nidas::core::SerialSensor::initPrompting().
stopPrompting()
void SerialSensor::stopPrompting () virtual inherited
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_prompters, nidas::core::SerialSensor::_prompting, nidas::core::DSMSensor::getLooper(), nidas::core::CharacterSensor::isPrompted(), and nidas::core::Looper::removeClient().
Referenced by nidas::core::SerialSensor::shutdownPrompting().
termios()
nidas::util::Termios& nidas::core::SerialSensor::termios () inline inherited
Expose the Termios.
One must call applyTermios() to apply any changes to the serial port.
References nidas::core::SerialSensor::_termios.
Referenced by nidas::core::RemoteSerialConnection::doEscCmds().
toDOMElement()
xercesc::DOMElement * DSMSensor::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Exceptions
xercesc::DOMException;
Reimplemented from nidas::core::DOMable.
Referenced by nidas::core::DSMSensor::toDOMParent().
toDOMParent()
xercesc::DOMElement * DSMSensor::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::DSMSensor::toDOMElement(), and nidas::core::SampleTag::toDOMParent().
Referenced by nidas::core::DSMConfig::toDOMElement().
togglePrompting()
virtual void nidas::core::CharacterSensor::togglePrompting () inline virtual inherited
Exceptions
nidas::util::IOException
References nidas::core::CharacterSensor::isPrompting(), nidas::core::CharacterSensor::startPrompting(), and nidas::core::CharacterSensor::stopPrompting().
Referenced by nidas::core::RemoteSerialConnection::doEscCmds().
trimUnparsed()
void DSMSensor::trimUnparsed (SampleTag * stag, SampleT< float > * outs, int nparsed) protected inherited
Fill with floatNAN all the values past nparsed values in output sample outs, and trim the length of the sample to match the length of the variables in SampleTag stag.
process() methods which support partial scans of messages can use this to finalize an output sample according to the SampleTag that was matched with it and the number of values parsed.
References nidas::core::floatNAN, fp, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Variable::getLength(), nidas::core::SampleTag::getVariables(), and nidas::core::SampleT< DataT >::setDataLength().
Referenced by nidas::dynld::iss::WICORSensor::process().
unixDevInit()
void nidas::core::SerialSensor::unixDevInit (int flags) protected inherited
Exceptions
nidas::util::IOException
validate()
void PIP_Serial::validate () virtual
Implementation of DSMSensor::validate for a Character Sensor.
Currently initializes all the prompts for this sensor.
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::CharacterSensor.
References _dofReject, nidas::core::DSMSensor::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMSensor::getParameter(), packetLen(), nidas::core::SerialSensor::setMessageParameters(), nidas::dynld::raf::SppSerial::validate(), and nidas::util::Exception::what().
validateSscanfs()
void CharacterSensor::validateSscanfs () virtual inherited
Virtual method to check that the Sscanfs for this CharacterSensor are OK.
The default implementation checks that the number of parse fields in each sscanf parser matches the number of variables in the associated output sample.
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::WxtSensor, nidas::dynld::isff::Wind3D, and nidas::dynld::isff::Wind2D.
References nidas::core::CharacterSensor::_sscanfers, nidas::util::Logger::getInstance(), nidas::core::Variable::getLength(), nidas::core::DSMSensor::getName(), nidas::core::AsciiSscanf::getNumberOfFields(), nidas::core::AsciiSscanf::getSampleTag(), nidas::core::SampleTag::getVariables(), nidas::util::Logger::log(), and LOG_WARNING.
Referenced by nidas::core::CharacterSensor::init().
write()
virtual size_t nidas::core::DSMSensor::write (const void * buf, size_t len) inline virtual inherited
Write to the device (duh).
Behaves like write(2) system call, without a file descriptor argument, and with an IOException.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::write().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::AlicatSDI::open(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::raf::AlicatSDI::sendFlow(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::core::CharacterSensor::sendInitString(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
Member Data Documentation
_airspeedSource
unsigned short nidas::dynld::raf::PIP_Serial::_airspeedSource protected
Referenced by sendInitString().
_applyVariableConversions
bool nidas::core::DSMSensor::_applyVariableConversions private inherited
Referenced by nidas::core::DSMSensor::getApplyVariableConversions(), and nidas::core::DSMSensor::setApplyVariableConversions().
_calFiles
std::map<std::string,CalFile*> nidas::core::DSMSensor::_calFiles private inherited
Referenced by nidas::core::DSMSensor::addCalFile(), nidas::core::DSMSensor::getCalFile(), nidas::core::DSMSensor::getCalFiles(), and nidas::core::DSMSensor::removeCalFiles().
_catalogName
std::string nidas::core::DSMSensor::_catalogName private inherited
Referenced by nidas::core::DSMSensor::getCatalogName(), and nidas::core::DSMSensor::setCatalogName().
_checkSumErrorCnt
size_t nidas::dynld::raf::SppSerial::_checkSumErrorCnt protected inherited
_className
std::string nidas::core::DSMSensor::_className private inherited
Class name attribute of this sensor.
Only used here for informative messages.
Referenced by nidas::core::DSMSensor::getClassName(), and nidas::core::DSMSensor::setClassName().
_constParameters
std::list<const Parameter*> nidas::core::DSMSensor::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::DSMSensor::addParameter(), and nidas::core::DSMSensor::getParameters().
_converters
std::vector<nidas::core::VariableConverter*> nidas::dynld::raf::SppSerial::_converters protected inherited
VariableConverters which may have been defined for each output housekeeping variable.
Currently there are no conversions for the individual histogram bins.
Referenced by nidas::dynld::raf::SppSerial::convert(), and nidas::dynld::raf::SppSerial::validate().
_dataType
DataTermination nidas::dynld::raf::SppSerial::_dataType protected inherited
Whether we are using fixed length data with checkSum (true), or the modified chips with message terminators.
Default is FixedLength.
See also
DataTermination
Referenced by appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), and nidas::dynld::raf::CDP_Serial::validate().
_defaultMode
int nidas::core::DSMSensor::_defaultMode private inherited
Referenced by nidas::core::DSMSensor::getDefaultMode(), and nidas::core::DSMSensor::setDefaultMode().
_depthString
std::string nidas::core::DSMSensor::_depthString private inherited
Referenced by nidas::core::DSMSensor::getDepthString(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
_devname
std::string nidas::core::DSMSensor::_devname private inherited
Referenced by nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::setDeviceName().
_dictionary
nidas::core::DSMSensor::MyDictionary nidas::core::DSMSensor::_dictionary private inherited
Referenced by nidas::core::DSMSensor::expandString(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getDictionary(), and nidas::core::DSMSensor::getTokenValue().
_dofReject
unsigned short nidas::dynld::raf::PIP_Serial::_dofReject protected
Referenced by sendInitString(), and validate().
_driverTimeTagUsecs
int nidas::core::DSMSensor::_driverTimeTagUsecs private inherited
Referenced by nidas::core::DSMSensor::getDriverTimeTagUsecs(), and nidas::core::DSMSensor::setDriverTimeTagUsecs().
_dsm
const DSMConfig* nidas::core::DSMSensor::_dsm private inherited
Referenced by nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMName(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getSite(), and nidas::core::DSMSensor::setDSMConfig().
_duplicateIdOK
bool nidas::core::DSMSensor::_duplicateIdOK private inherited
Referenced by nidas::core::DSMSensor::getDuplicateIdOK(), and nidas::core::DSMSensor::setDuplicateIdOK().
_emptyString
std::string nidas::core::CharacterSensor::_emptyString private inherited
_fullSuffix
std::string nidas::core::DSMSensor::_fullSuffix private inherited
Concatenation of sensor suffix, and the height or depth string.
Referenced by nidas::core::DSMSensor::getFullSuffix(), and nidas::core::DSMSensor::setFullSuffix().
_height
float nidas::core::DSMSensor::_height private inherited
Referenced by nidas::core::DSMSensor::getDepth(), nidas::core::DSMSensor::getHeight(), nidas::core::DSMSensor::setDepth(), and nidas::core::DSMSensor::setHeight().
_heightString
std::string nidas::core::DSMSensor::_heightString private inherited
Referenced by nidas::core::DSMSensor::getHeightString(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
_id
dsm_sample_id_t nidas::core::DSMSensor::_id private inherited
Id of this sensor.
Raw samples from this sensor will have this id.
Referenced by nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getId(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::setDSMId(), nidas::core::DSMSensor::setId(), and nidas::core::DSMSensor::setSensorId().
_InitPacketSize
const int nidas::dynld::raf::PIP_Serial::_InitPacketSize = 10 static
Referenced by PIP_Serial(), and sendInitString().
_initString
std::string nidas::core::CharacterSensor::_initString private inherited
String that is sent once after sensor is opened.
Referenced by nidas::core::CharacterSensor::getInitString(), and nidas::core::CharacterSensor::setInitString().
_iodev
IODevice* nidas::core::DSMSensor::_iodev private inherited
Referenced by nidas::core::DSMSensor::close(), nidas::core::DSMSensor::getBytesAvailable(), nidas::core::DSMSensor::getIODevice(), nidas::core::DSMSensor::getReadFd(), nidas::core::DSMSensor::getWriteFd(), nidas::core::DSMSensor::ioctl(), nidas::core::DSMSensor::open(), nidas::core::DSMSensor::read(), nidas::core::DSMSensor::setIODevice(), nidas::core::DSMSensor::write(), and nidas::core::DSMSensor::~DSMSensor().
_lag
int nidas::core::DSMSensor::_lag private inherited
Referenced by nidas::core::DSMSensor::getLagSecs(), nidas::core::DSMSensor::getLagUsecs(), and nidas::core::DSMSensor::setLagSecs().
_latency
float nidas::core::DSMSensor::_latency private inherited
Referenced by nidas::core::DSMSensor::getLatency(), and nidas::core::DSMSensor::setLatency().
_location
std::string nidas::core::DSMSensor::_location private inherited
Referenced by nidas::core::DSMSensor::getLocation(), and nidas::core::DSMSensor::setLocation().
_looper
Looper * DSMSensor::_looper = 0 static private inherited
Referenced by nidas::core::DSMSensor::deleteLooper(), and nidas::core::DSMSensor::getLooper().
_looperMutex
n_u::Mutex DSMSensor::_looperMutex static private inherited
Referenced by nidas::core::DSMSensor::deleteLooper(), and nidas::core::DSMSensor::getLooper().
_maxScanfFields
int nidas::core::CharacterSensor::_maxScanfFields private inherited
Referenced by nidas::core::CharacterSensor::getMaxScanfFields(), and nidas::core::CharacterSensor::init().
_messageLength
int nidas::core::CharacterSensor::_messageLength private inherited
Referenced by nidas::core::CharacterSensor::getMessageLength(), and nidas::core::CharacterSensor::setMessageParameters().
_messageSeparator
std::string nidas::core::CharacterSensor::_messageSeparator private inherited
Referenced by nidas::core::CharacterSensor::getBackslashedMessageSeparator(), nidas::core::CharacterSensor::getMessageSeparator(), and nidas::core::CharacterSensor::setMessageParameters().
_model
unsigned short nidas::dynld::raf::SppSerial::_model protected inherited
Possibly not needed...
_nChannels
int nidas::dynld::raf::SppSerial::_nChannels protected inherited
Number of channels requested to be recorded.
Referenced by nidas::dynld::raf::BCPD_Serial::BCPD_Serial(), nidas::dynld::raf::CDP_Serial::CDP_Serial(), nidas::dynld::raf::BCPD_Serial::packetLen(), nidas::dynld::raf::CDP_Serial::packetLen(), nidas::dynld::raf::SPP100_Serial::packetLen(), nidas::dynld::raf::SPP200_Serial::packetLen(), nidas::dynld::raf::SPP300_Serial::packetLen(), PIP_Serial(), nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::SPP100_Serial(), nidas::dynld::raf::SPP200_Serial::SPP200_Serial(), nidas::dynld::raf::SPP300_Serial::SPP300_Serial(), and nidas::dynld::raf::SppSerial::validate().
_nextSscanfer
std::list<AsciiSscanf*>::const_iterator nidas::core::CharacterSensor::_nextSscanfer private inherited
Referenced by nidas::core::CharacterSensor::init().
_nHskp
int nidas::dynld::raf::SppSerial::_nHskp protected inherited
Number of housekeeping variables added to output data.
Referenced by nidas::dynld::raf::BCPD_Serial::BCPD_Serial(), nidas::dynld::raf::CDP_Serial::CDP_Serial(), PIP_Serial(), nidas::dynld::raf::SPP100_Serial::SPP100_Serial(), nidas::dynld::raf::SPP200_Serial::SPP200_Serial(), nidas::dynld::raf::SPP300_Serial::SPP300_Serial(), and nidas::dynld::raf::SppSerial::validate().
_noutValues
int nidas::dynld::raf::SppSerial::_noutValues protected inherited
Total number of floats in the processed output sample.
Referenced by nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), and nidas::dynld::raf::SppSerial::validate().
_nTimeouts
int nidas::core::DSMSensor::_nTimeouts private inherited
Referenced by nidas::core::DSMSensor::getTimeoutCount(), and nidas::core::DSMSensor::incrementTimeoutCount().
_nWaitingData
unsigned short nidas::dynld::raf::SppSerial::_nWaitingData protected inherited
Referenced by appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), and nidas::dynld::raf::SppSerial::validate().
_opcThreshold
unsigned short nidas::dynld::raf::SppSerial::_opcThreshold[MAX_CHANNELS] protected inherited
Referenced by nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and nidas::dynld::raf::SppSerial::validate().
_openable
bool nidas::core::DSMSensor::_openable protected inherited
Whether this sensor is allowed to be opened.
Most cases the answer is yes/true. But certain sensors should not be opened due to implementation. e.g. DSMArincSensor when used in conjunction with the UDPArincSensor for then Alta ENET appliance.
The fallout from setting this to false is that the sensor will not be added to SensorHandler.
Referenced by nidas::core::DSMSensor::allowOpen(), and nidas::dynld::raf::DSMArincSensor::fromDOMElement().
_outputDeltaT
bool nidas::dynld::raf::SppSerial::_outputDeltaT protected inherited
Stash sample-rate.
The rw histogram counts we want to convert to a counts per second by multiplying by sample rate. Whether to output DELTAT variable. validate() will detect if DELTAT variable is last variable in sample list of variables. If so this is set to true.
Referenced by nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), and nidas::dynld::raf::SppSerial::validate().
_parameters
std::map<std::string,Parameter*> nidas::core::DSMSensor::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::DSMSensor::addParameter(), nidas::core::DSMSensor::getParameter(), and nidas::core::DSMSensor::~DSMSensor().
_prevTime
dsm_time_t nidas::dynld::raf::SppSerial::_prevTime protected inherited
Store previous time tag.
We can then generate a delta T for statistics or output.
Referenced by nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), and nidas::dynld::raf::SPP300_Serial::process().
_probeName
std::string nidas::dynld::raf::SppSerial::_probeName protected inherited
Referenced by nidas::dynld::raf::SppSerial::validate().
_prompted
bool nidas::core::CharacterSensor::_prompted private inherited
Referenced by nidas::core::CharacterSensor::addPrompt(), nidas::core::CharacterSensor::isPrompted(), and nidas::core::CharacterSensor::validate().
_prompters
std::list<Prompter*> nidas::core::SerialSensor::_prompters private inherited
Referenced by nidas::core::SerialSensor::initPrompting(), nidas::core::SerialSensor::shutdownPrompting(), nidas::core::SerialSensor::startPrompting(), nidas::core::SerialSensor::stopPrompting(), and nidas::core::SerialSensor::~SerialSensor().
_prompting
bool nidas::core::SerialSensor::_prompting private inherited
Referenced by nidas::core::SerialSensor::isPrompting(), nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
_promptOffset
double nidas::core::CharacterSensor::_promptOffset private inherited
Referenced by nidas::core::CharacterSensor::getPromptOffset(), and nidas::core::CharacterSensor::setPromptOffset().
_promptRate
double nidas::core::CharacterSensor::_promptRate private inherited
Referenced by nidas::core::CharacterSensor::getPromptRate(), and nidas::core::CharacterSensor::setPromptRate().
_prompts
std::list<Prompt> nidas::core::CharacterSensor::_prompts private inherited
Referenced by nidas::core::CharacterSensor::addPrompt(), and nidas::core::CharacterSensor::getPrompts().
_promptString
std::string nidas::core::CharacterSensor::_promptString private inherited
Referenced by nidas::core::CharacterSensor::getPromptString(), and nidas::core::CharacterSensor::setPromptString().
_range
unsigned short nidas::dynld::raf::SppSerial::_range protected inherited
Referenced by nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and nidas::dynld::raf::SppSerial::validate().
_rawSampleTag
SampleTag nidas::core::DSMSensor::_rawSampleTag private inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::DSMSensor::getRawSampleTag().
_rawSource
SampleSourceSupport nidas::core::DSMSensor::_rawSource private inherited
Referenced by nidas::core::DSMSensor::distributeRaw(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getRawSampleSource(), and nidas::core::DSMSensor::readSamples().
_recDelimiter
unsigned short nidas::dynld::raf::SppSerial::_recDelimiter protected inherited
Referenced by appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), and nidas::dynld::raf::CDP_Serial::validate().
_rts485
int nidas::core::SerialSensor::_rts485 private inherited
Should the RTS line on this port be controled for half-duplex 485? See SerialPortIODevice.h.
Referenced by nidas::core::SerialSensor::buildIODevice(), and nidas::core::SerialSensor::fromDOMElement().
_sampleTags
std::list<SampleTag*> nidas::core::DSMSensor::_sampleTags private inherited
Referenced by nidas::core::DSMSensor::addSampleTag(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getNonConstSampleTags(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMSensor::removeSampleTag(), nidas::core::DSMSensor::setStation(), and nidas::core::DSMSensor::~DSMSensor().
_scanfFailures
int nidas::core::CharacterSensor::_scanfFailures private inherited
Referenced by nidas::core::CharacterSensor::getNumScanfFailures().
_scanfPartials
int nidas::core::CharacterSensor::_scanfPartials private inherited
Referenced by nidas::core::CharacterSensor::getNumScanfPartials().
_scanner
SampleScanner* nidas::core::DSMSensor::_scanner private inherited
Referenced by nidas::core::DSMSensor::calcStatistics(), nidas::core::DSMSensor::clearBuffer(), nidas::core::DSMSensor::getBadTimeTagCount(), nidas::core::DSMSensor::getMaxSampleLength(), nidas::core::DSMSensor::getMinSampleLength(), nidas::core::DSMSensor::getObservedDataRate(), nidas::core::DSMSensor::getObservedSamplingRate(), nidas::core::DSMSensor::getSampleScanner(), nidas::core::DSMSensor::nextSample(), nidas::core::DSMSensor::open(), nidas::core::DSMSensor::readBuffer(), nidas::core::DSMSensor::setSampleScanner(), and nidas::core::DSMSensor::~DSMSensor().
_SendDataPacketSize
const int nidas::dynld::raf::PIP_Serial::_SendDataPacketSize = 12 static
_separatorAtEOM
bool nidas::core::CharacterSensor::_separatorAtEOM private inherited
Referenced by nidas::core::CharacterSensor::getMessageSeparatorAtEOM(), and nidas::core::CharacterSensor::setMessageParameters().
_serialDevice
SerialPortIODevice* nidas::core::SerialSensor::_serialDevice private inherited
Non-null if the underlying IODevice is a SerialPortIODevice.
Referenced by nidas::core::SerialSensor::applyTermios(), nidas::core::SerialSensor::buildIODevice(), and nidas::core::SerialSensor::getUsecsPerByte().
_setTimePacketSize
const int nidas::dynld::raf::PIP_Serial::_setTimePacketSize = 8 static
Referenced by sendTimePacket().
_skippedBytes
int nidas::dynld::raf::SppSerial::_skippedBytes protected inherited
Referenced by appendDataAndFindGood(), and nidas::dynld::raf::SppSerial::appendDataAndFindGood().
_skippedRecordCount
size_t nidas::dynld::raf::SppSerial::_skippedRecordCount protected inherited
Referenced by appendDataAndFindGood(), and nidas::dynld::raf::SppSerial::appendDataAndFindGood().
_source
SampleSourceSupport nidas::core::DSMSensor::_source private inherited
Referenced by nidas::core::DSMSensor::addSampleClient(), nidas::core::DSMSensor::addSampleClientForTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::DSMSensor::getClientCount(), nidas::core::DSMSensor::getSampleStats(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMSensor::receive(), nidas::core::DSMSensor::removeSampleClient(), nidas::core::DSMSensor::removeSampleClientForTag(), and nidas::core::DSMSensor::removeSampleTag().
_sscanfers
std::list<AsciiSscanf*> nidas::core::CharacterSensor::_sscanfers private inherited
Referenced by nidas::core::CharacterSensor::getScanfers(), nidas::core::CharacterSensor::init(), nidas::core::CharacterSensor::validateSscanfs(), and nidas::core::CharacterSensor::~CharacterSensor().
_station
int nidas::core::DSMSensor::_station private inherited
Referenced by nidas::core::DSMSensor::getStation(), and nidas::core::DSMSensor::setStation().
_suffix
std::string nidas::core::DSMSensor::_suffix private inherited
Sensor suffix, which is added to variable names.
Referenced by nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setSuffix().
_termios
nidas::util::Termios nidas::core::SerialSensor::_termios private inherited
Serial I/O parameters.
Referenced by nidas::core::SerialSensor::applyTermios(), nidas::core::SerialSensor::buildIODevice(), nidas::core::SerialSensor::fromDOMElement(), nidas::core::SerialSensor::getTermios(), nidas::core::SerialSensor::SerialSensor(), and nidas::core::SerialSensor::termios().
_timeoutMsecs
int nidas::core::DSMSensor::_timeoutMsecs private inherited
Referenced by nidas::core::DSMSensor::getTimeoutMsecs(), and nidas::core::DSMSensor::setTimeoutMsecs().
_totalRecordCount
size_t nidas::dynld::raf::SppSerial::_totalRecordCount protected inherited
Referenced by appendDataAndFindGood(), and nidas::dynld::raf::SppSerial::appendDataAndFindGood().
_triggerThreshold
unsigned short nidas::dynld::raf::SppSerial::_triggerThreshold protected inherited
Referenced by nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and nidas::dynld::raf::SppSerial::validate().
_trueAirSpeed
float nidas::dynld::raf::PIP_Serial::_trueAirSpeed protected
True air speed, received from IWGADTS feed.
_ttadjusters
std::map<const SampleTag*, TimetagAdjuster*> nidas::core::CharacterSensor::_ttadjusters protected inherited
Referenced by nidas::core::CharacterSensor::adjustTimeTag(), nidas::core::CharacterSensor::init(), and nidas::core::CharacterSensor::~CharacterSensor().
_typeName
std::string nidas::core::DSMSensor::_typeName private inherited
Referenced by nidas::core::DSMSensor::getTypeName(), and nidas::core::DSMSensor::setTypeName().
_waitingData
unsigned char* nidas::dynld::raf::SppSerial::_waitingData protected inherited
Buffer to hold incoming data until we find a chunk that looks like a valid DMT100 data packet.
The buffer size is 2 * the expected packet length (packetLen()) so that we can hold the current incoming chunk plus anything remaining from the previous chunk. _nWaitingData keeps track of how much of the buffer is actually in use.
Referenced by appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), nidas::dynld::raf::CDP_Serial::process(), process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), and nidas::dynld::raf::SppSerial::validate().
MAX_CHANNELS
const int nidas::dynld::raf::SppSerial::MAX_CHANNELS = 40 static inherited
Max # for array sizing.
Valid number of channels are 10, 20, 30 and 40.
Referenced by nidas::dynld::raf::BCPD_Serial::BCPD_Serial(), nidas::dynld::raf::CDP_Serial::CDP_Serial(), nidas::dynld::raf::SPP100_Serial::SPP100_Serial(), nidas::dynld::raf::SPP200_Serial::SPP200_Serial(), and nidas::dynld::raf::SPP300_Serial::SPP300_Serial().
N_PIP_CHANNELS
const size_t nidas::dynld::raf::PIP_Serial::N_PIP_CHANNELS = 62 static
Referenced by PIP_Serial().
N_PIP_HSKP
const size_t nidas::dynld::raf::PIP_Serial::N_PIP_HSKP = 16 static
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
PIPCBTMP
const size_t PIP_Serial::PIPCBTMP = 7 static protected
Referenced by process().
PIPEDV0
const size_t PIP_Serial::PIPEDV0 = 0 static protected
Referenced by process().
PIPEDV32
const size_t PIP_Serial::PIPEDV32 = 2 static protected
Referenced by process().
PIPEDV64
const size_t PIP_Serial::PIPEDV64 = 1 static protected
Referenced by process().
PIPLSRC
const size_t PIP_Serial::PIPLSRC = 14 static protected
Referenced by process().
PIPLSRP
const size_t PIP_Serial::PIPLSRP = 15 static protected
Referenced by process().
PIPLWC
const size_t PIP_Serial::PIPLWC = 5 static protected
PIPLWCSLV
const size_t PIP_Serial::PIPLWCSLV = 6 static protected
PIPPS
const size_t PIP_Serial::PIPPS = 4 static protected
PIPQC
const size_t PIP_Serial::PIPQC = 3 static protected
PIPRH
const size_t PIP_Serial::PIPRH = 8 static protected
PIPRT
const size_t PIP_Serial::PIPRT = 13 static protected
REJDOF
const size_t nidas::dynld::raf::PIP_Serial::REJDOF static protected
REJEND
const size_t nidas::dynld::raf::PIP_Serial::REJEND static protected
REJOFLOW
const size_t nidas::dynld::raf::PIP_Serial::REJOFLOW static protected
zebra
bool DSMSensor::zebra = false static private inherited
Referenced by nidas::core::DSMSensor::printStatus(), and nidas::core::DSMSensor::printStatusHeader().
The documentation for this class was generated from the following files:
nidas/dynld/raf/PIP_Serial.h
nidas/dynld/raf/PIP_Serial.cc