nidas: nidas::core::SamplePool< SampleType > Class Template Reference
nidas::core::SamplePool< SampleType > Class Template Reference
A pool of Samples.
#include <SamplePool.h>
Public Member Functions
SampleType * getSample (unsigned int len)
Get a sample of at least len elements from the pool.
void putSample (const SampleType *)
Return a sample to the pool.
int getNSamplesAlloc () const
int getNSamplesOut () const
int getNSmallSamplesIn () const
int getNMediumSamplesIn () const
int getNLargeSamplesIn () const
Static Public Member Functions
static SamplePool * getInstance ()
Get a pointer to the singleton instance.
static void deleteInstance ()
Singleton cleanup on program exit.
Public Attributes
int _nsmall
int _nmedium
int _nlarge
int _nsamplesOut
int _nsamplesAlloc
Private Member Functions
SamplePool ()
~SamplePool ()
SampleType * getSample (SampleType **vec, int *veclen, unsigned int len)
void putSample (const SampleType *, SampleType ***vecp, int *veclen, int *nalloc)
SamplePool (const SamplePool &)
No copying.
SamplePool & operator= (const SamplePool &)
No assignment.
Private Attributes
SampleType ** _smallSamples
SampleType ** _mediumSamples
SampleType ** _largeSamples
int _smallSize
int _mediumSize
int _largeSize
nidas::util::Mutex _poolLock
Static Private Attributes
static SamplePool * _instance = 0
static nidas::util::Mutex _instanceLock = nidas::util::Mutex()
static const unsigned int SMALL_SAMPLE_MAXSIZE = 64
maximum number of elements in a small sample
static const unsigned int MEDIUM_SAMPLE_MAXSIZE = 512
maximum number of elements in a medium sized sample
Detailed Description
template<typename SampleType>
class nidas::core::SamplePool< SampleType >
A pool of Samples.
Actually three pools, containing samples segregated by size. A SamplePool can used as a singleton, and accessed from anywhere, via the getInstance() static member function.
Constructor & Destructor Documentation
SamplePool() [1/2]
template<class SampleType > nidas::core::SamplePool< SampleType >::SamplePool private
References nidas::core::SamplePool< SampleType >::_largeSamples, nidas::core::SamplePool< SampleType >::_largeSize, nidas::core::SamplePool< SampleType >::_mediumSamples, nidas::core::SamplePool< SampleType >::_mediumSize, nidas::core::SamplePool< SampleType >::_smallSamples, nidas::core::SamplePool< SampleType >::_smallSize, DLOG, nidas::core::SamplePool< SampleType >::MEDIUM_SAMPLE_MAXSIZE, and nidas::core::SamplePool< SampleType >::SMALL_SAMPLE_MAXSIZE.
~SamplePool()
template<class SampleType > nidas::core::SamplePool< SampleType >::~SamplePool private
References nidas::core::SamplePools::getInstance(), and nidas::core::SamplePools::removePool().
SamplePool() [2/2]
template<typename SampleType > nidas::core::SamplePool< SampleType >::SamplePool (const SamplePool< SampleType > &) private
No copying.
Member Function Documentation
deleteInstance()
template<class SampleType > void nidas::core::SamplePool< SampleType >::deleteInstance static
Singleton cleanup on program exit.
getInstance()
template<class SampleType > SamplePool< SampleType > * nidas::core::SamplePool< SampleType >::getInstance static
Get a pointer to the singleton instance.
References nidas::core::SamplePools::addPool(), and nidas::core::SamplePools::getInstance().
getNLargeSamplesIn()
template<typename SampleType > int nidas::core::SamplePool< SampleType >::getNLargeSamplesIn () const inline virtual
Implements nidas::core::SamplePoolInterface.
References nidas::core::SamplePool< SampleType >::_nlarge.
getNMediumSamplesIn()
template<typename SampleType > int nidas::core::SamplePool< SampleType >::getNMediumSamplesIn () const inline virtual
Implements nidas::core::SamplePoolInterface.
References nidas::core::SamplePool< SampleType >::_nmedium.
getNSamplesAlloc()
template<typename SampleType > int nidas::core::SamplePool< SampleType >::getNSamplesAlloc () const inline virtual
Implements nidas::core::SamplePoolInterface.
References nidas::core::SamplePool< SampleType >::_nsamplesAlloc.
getNSamplesOut()
template<typename SampleType > int nidas::core::SamplePool< SampleType >::getNSamplesOut () const inline virtual
Implements nidas::core::SamplePoolInterface.
References nidas::core::SamplePool< SampleType >::_nsamplesOut.
getNSmallSamplesIn()
template<typename SampleType > int nidas::core::SamplePool< SampleType >::getNSmallSamplesIn () const inline virtual
Implements nidas::core::SamplePoolInterface.
References nidas::core::SamplePool< SampleType >::_nsmall.
getSample() [1/2]
template<class SampleType > SampleType * nidas::core::SamplePool< SampleType >::getSample (SampleType ** vec, int * veclen, unsigned int len) private
References nidas::core::floatNAN, and len.
getSample() [2/2]
template<class SampleType > SampleType * nidas::core::SamplePool< SampleType >::getSample (unsigned int len)
Get a sample of at least len elements from the pool.
References nidas::core::getSample(), and len.
Referenced by nidas::core::getSample().
operator=()
template<typename SampleType > SamplePool& nidas::core::SamplePool< SampleType >::operator= (const SamplePool< SampleType > &) private
No assignment.
putSample() [1/2]
template<class SampleType > void nidas::core::SamplePool< SampleType >::putSample (const SampleType * sample)
Return a sample to the pool.
References DLOG, and len.
Referenced by nidas::core::SampleT< DataT >::freeReference().
putSample() [2/2]
template<class SampleType > void nidas::core::SamplePool< SampleType >::putSample (const SampleType * sample, SampleType *** vecp, int * veclen, int * nalloc) private
References DLOG.
Member Data Documentation
_instance
template<class SampleType > SamplePool< SampleType > * nidas::core::SamplePool< SampleType >::_instance = 0 static private
_instanceLock
template<class SampleType > nidas::util::Mutex nidas::core::SamplePool< SampleType >::_instanceLock = nidas::util::Mutex() static private
_largeSamples
template<typename SampleType > SampleType** nidas::core::SamplePool< SampleType >::_largeSamples private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
_largeSize
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_largeSize private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
_mediumSamples
template<typename SampleType > SampleType** nidas::core::SamplePool< SampleType >::_mediumSamples private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
_mediumSize
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_mediumSize private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
_nlarge
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_nlarge
Referenced by nidas::core::SamplePool< SampleType >::getNLargeSamplesIn().
_nmedium
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_nmedium
Referenced by nidas::core::SamplePool< SampleType >::getNMediumSamplesIn().
_nsamplesAlloc
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_nsamplesAlloc
Referenced by nidas::core::SamplePool< SampleType >::getNSamplesAlloc().
_nsamplesOut
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_nsamplesOut
Referenced by nidas::core::SamplePool< SampleType >::getNSamplesOut().
_nsmall
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_nsmall
Referenced by nidas::core::SamplePool< SampleType >::getNSmallSamplesIn().
_poolLock
template<typename SampleType > nidas::util::Mutex nidas::core::SamplePool< SampleType >::_poolLock private
_smallSamples
template<typename SampleType > SampleType** nidas::core::SamplePool< SampleType >::_smallSamples private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
_smallSize
template<typename SampleType > int nidas::core::SamplePool< SampleType >::_smallSize private
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
MEDIUM_SAMPLE_MAXSIZE
template<typename SampleType > const unsigned int nidas::core::SamplePool< SampleType >::MEDIUM_SAMPLE_MAXSIZE = 512 static private
maximum number of elements in a medium sized sample
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
SMALL_SAMPLE_MAXSIZE
template<typename SampleType > const unsigned int nidas::core::SamplePool< SampleType >::SMALL_SAMPLE_MAXSIZE = 64 static private
maximum number of elements in a small sample
Referenced by nidas::core::SamplePool< SampleType >::SamplePool().
The documentation for this class was generated from the following file:
nidas/core/SamplePool.h