nidas: nidas::core::Socket Class Reference
nidas::core::Socket Class Reference
Implementation of an IOChannel, over a Socket.
#include <Socket.h>
Classes
class ConnectionThread
Public Member Functions
Socket ()
Constructor.
Socket (nidas::util::Socket *sock)
Constructor from a connected nidas::util::Socket.
~Socket ()
Socket * clone () const
Derived classes must provide clone.
void requestConnection (IOChannelRequester *service)
IOChannel * connect ()
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
void setRequestType (enum McSocketRequest val)
enum McSocketRequest getRequestType () const
void setKeepAliveIdleSecs (int val)
Do setKeepAliveIdleSecs(int secs) on underlying socket.
int getKeepAliveIdleSecs () const
Return getKeepAliveIdleSecs() on underlying socket.
std::list< nidas::util::Inet4NetworkInterface > getInterfaces () const
void setNonBlocking (bool val)
Do setNonBlocking(val) on underlying socket.
bool isNonBlocking () const
Return isNonBlocking() of underlying socket.
size_t getBufferSize () const throw ()
Return suggested buffer length.
size_t read (void *buf, size_t len)
Do the actual hardware read.
size_t write (const void *buf, size_t len)
Do the actual hardware write.
size_t write (const struct iovec *iov, int iovcnt)
Do the actual hardware write.
void close ()
int getFd () const
const std::string & getName () const
void setName (const std::string &val)
nidas::util::Inet4Address getRemoteInet4Address ()
void setRemoteHostPort (const std::string &host, unsigned short port)
Set the hostname and port of the remote connection.
const std::string & getRemoteHost () const
Get the name of the remote host.
unsigned short getRemotePort () const
const std::string & getRemoteUnixPath () const
Get the name of the remote host.
void setRemoteUnixPath (const std::string &unixPath)
Set the pathname for the unix socket connection.
void setRemoteSocketAddress (const nidas::util::SocketAddress &val)
const nidas::util::SocketAddress & getRemoteSocketAddress ()
This method does a DNS lookup of the value of getRemoteHost(), and so it can throw an UnknownHostException.
void fromDOMElement (const xercesc::DOMElement *)
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createSocket (const xercesc::DOMElement *)
Create either a Socket or a McSocket from a DOMElement.
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
Socket (const Socket &x)
Copy constructor.
Private Member Functions
Socket & operator= (const Socket &)
No assignment.
Private Attributes
nidas::util::auto_ptr< nidas::util::SocketAddress > _remoteSockAddr
std::string _remoteHost
unsigned short _remotePort
std::string _unixPath
nidas::util::Socket * _nusocket
std::string _name
IOChannelRequester * _iochanRequester
ConnectionThread * _connectionThread
bool _firstRead
bool _newInput
int _keepAliveIdleSecs
bool _nonBlocking
nidas::util::Mutex _connectionMutex
enum McSocketRequest _requestType
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Implementation of an IOChannel, over a Socket.
Constructor & Destructor Documentation
Socket() [1/3]
Socket::Socket ()
Constructor.
References setName().
Referenced by clone(), and createSocket().
Socket() [2/3]
Socket::Socket (nidas::util::Socket * sock)
Constructor from a connected nidas::util::Socket.
Parameters
sock Pointer to the connected nidas::util::Socket. Socket will own the pointer and will delete it it its destructor.
References _keepAliveIdleSecs, _nonBlocking, _nusocket, _remoteHost, _remoteSockAddr, _unixPath, nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::util::Socket::getKeepAliveIdleSecs(), nidas::util::Socket::isNonBlocking(), setRemoteHostPort(), setRemoteUnixPath(), and nidas::util::UnixSocketAddress::toString().
~Socket()
Socket::~Socket ()
References _connectionMutex, _connectionThread, _nusocket, close(), nidas::core::Socket::ConnectionThread::interrupt(), nidas::util::Exception::what(), and WLOG.
Socket() [3/3]
Socket::Socket (const Socket & x) protected
Copy constructor.
References _nusocket.
Member Function Documentation
clone()
Socket * Socket::clone () const virtual
Derived classes must provide clone.
Implements nidas::core::IOChannel.
References Socket().
close()
void Socket::close () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::Socket::close().
Referenced by WriterThread::run(), and ~Socket().
connect()
IOChannel * Socket::connect () virtual
Exceptions
nidas::util::IOException
nidas::util::UnknownHostException
Implements nidas::core::IOChannel.
References _firstRead, _keepAliveIdleSecs, _newInput, _nonBlocking, _nusocket, nidas::util::Socket::connect(), nidas::util::SocketAddress::getConstSockAddrPtr(), nidas::util::SocketAddress::getFamily(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::util::Socket::getInterfaces(), nidas::util::Socket::getLocalSocketAddress(), getRemoteSocketAddress(), nidas::util::Socket::getRemoteSocketAddress(), nidas::core::IOChannel::setConnectionInfo(), nidas::util::Socket::setKeepAliveIdleSecs(), setName(), nidas::util::Socket::setNonBlocking(), and nidas::util::SocketAddress::toAddressString().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
createSocket()
IOChannel * Socket::createSocket (const xercesc::DOMElement * node) static
Create either a Socket or a McSocket from a DOMElement.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::XDOMElement::getAttributeValue(), and Socket().
Referenced by nidas::core::IOChannel::createIOChannel().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void Socket::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Process::expandEnvVars(), nidas::util::Inet4Address::getByName(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), port, setKeepAliveIdleSecs(), setNonBlocking(), setRemoteHostPort(), setRemoteUnixPath(), nidas::util::Exception::what(), and WLOG.
getBufferSize()
size_t Socket::getBufferSize () const throw () virtual
Return suggested buffer length.
Reimplemented from nidas::core::IOChannel.
References _nusocket, and nidas::util::Socket::getReceiveBufferSize().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::core::Socket::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::Socket::getFd().
getInterfaces()
std::list<nidas::util::Inet4NetworkInterface> nidas::core::Socket::getInterfaces () const inline
Exceptions
nidas::util::IOException
References _nusocket, and nidas::util::Socket::getInterfaces().
getKeepAliveIdleSecs()
int nidas::core::Socket::getKeepAliveIdleSecs () const inline
Return getKeepAliveIdleSecs() on underlying socket.
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs, _nusocket, and nidas::util::Socket::getKeepAliveIdleSecs().
getName()
const std::string& nidas::core::Socket::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by fromDOMElement(), nidas::core::ServerSocket::fromDOMElement(), requestConnection(), and nidas::core::Socket::ConnectionThread::run().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRemoteHost()
const std::string& nidas::core::Socket::getRemoteHost () const inline
Get the name of the remote host.
References _remoteHost.
getRemoteInet4Address()
n_u::Inet4Address Socket::getRemoteInet4Address ()
References nidas::util::SocketAddress::getConstSockAddrPtr(), nidas::util::SocketAddress::getFamily(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::util::Logger::getInstance(), getRemoteSocketAddress(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
getRemotePort()
unsigned short nidas::core::Socket::getRemotePort () const inline
References _remotePort.
getRemoteSocketAddress()
const n_u::SocketAddress & Socket::getRemoteSocketAddress ()
This method does a DNS lookup of the value of getRemoteHost(), and so it can throw an UnknownHostException.
This is different behaviour from the the nidas::util::Socket::getRemoteSocketAddress() method, which does not throw an exception.
Exceptions
nidas::util::UnknownHostException
References _remoteHost, _remotePort, _remoteSockAddr, nidas::util::Inet4Address::getByName(), getRemoteUnixPath(), setName(), and setRemoteSocketAddress().
Referenced by connect(), getRemoteInet4Address(), WriterThread::run(), and nidas::core::ServerSocket::ConnectionThread::run().
getRemoteUnixPath()
const std::string& nidas::core::Socket::getRemoteUnixPath () const inline
Get the name of the remote host.
References _unixPath.
Referenced by getRemoteSocketAddress().
getRequestType()
enum McSocketRequest nidas::core::Socket::getRequestType () const inline virtual
Reimplemented from nidas::core::IOChannel.
References _requestType.
isNewInput()
virtual bool nidas::core::Socket::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _newInput.
isNonBlocking()
bool nidas::core::Socket::isNonBlocking () const inline virtual
Return isNonBlocking() of underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking, _nusocket, and nidas::util::Socket::isNonBlocking().
operator=()
Socket& nidas::core::Socket::operator= (const Socket &) private
No assignment.
read()
size_t nidas::core::Socket::read (void * buf, size_t len) inline virtual
Do the actual hardware read.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _firstRead, _newInput, _nusocket, len, and nidas::util::Socket::recv().
requestConnection()
void Socket::requestConnection (IOChannelRequester * service) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _connectionMutex, _connectionThread, _iochanRequester, getName(), nidas::util::Thread::start(), and nidas::util::Exception::what().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setKeepAliveIdleSecs()
void nidas::core::Socket::setKeepAliveIdleSecs (int val) inline
Do setKeepAliveIdleSecs(int secs) on underlying socket.
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs, _nusocket, and nidas::util::Socket::setKeepAliveIdleSecs().
Referenced by fromDOMElement(), and nidas::core::ServerSocket::fromDOMElement().
setName()
void nidas::core::Socket::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by connect(), nidas::core::ServerSocket::fromDOMElement(), getRemoteSocketAddress(), and Socket().
setNonBlocking()
void nidas::core::Socket::setNonBlocking (bool val) inline virtual
Do setNonBlocking(val) on underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking, _nusocket, and nidas::util::Socket::setNonBlocking().
Referenced by nidas::core::ServerSocket::connect(), fromDOMElement(), nidas::core::ServerSocket::fromDOMElement(), and WriterThread::run().
setRemoteHostPort()
void Socket::setRemoteHostPort (const std::string & host, unsigned short port)
Set the hostname and port of the remote connection.
This method does not try to do a DNS host lookup. The DNS lookup will be done at connect time.
References _remoteHost, _remotePort, and port.
Referenced by fromDOMElement(), and Socket().
setRemoteSocketAddress()
void Socket::setRemoteSocketAddress (const nidas::util::SocketAddress & val)
References _remoteSockAddr, and nidas::util::SocketAddress::clone().
Referenced by getRemoteSocketAddress().
setRemoteUnixPath()
void Socket::setRemoteUnixPath (const std::string & unixPath)
Set the pathname for the unix socket connection.
References _unixPath.
Referenced by fromDOMElement(), and Socket().
setRequestType()
void nidas::core::Socket::setRequestType (enum McSocketRequest val) inline virtual
Reimplemented from nidas::core::IOChannel.
Referenced by nidas::core::McSocket::connect(), and nidas::core::McSocket::connected().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t nidas::core::Socket::write (const struct iovec * iov, int iovcnt) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::Socket::send().
write() [2/2]
size_t nidas::core::Socket::write (const void * buf, size_t len) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, nidas::util::UTime::format(), len, and nidas::util::Socket::send().
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_connectionMutex
nidas::util::Mutex nidas::core::Socket::_connectionMutex private
Referenced by requestConnection(), and ~Socket().
_connectionThread
ConnectionThread* nidas::core::Socket::_connectionThread private
Referenced by requestConnection(), and ~Socket().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_firstRead
bool nidas::core::Socket::_firstRead private
Referenced by connect(), and read().
_iochanRequester
IOChannelRequester* nidas::core::Socket::_iochanRequester private
Referenced by requestConnection().
_keepAliveIdleSecs
int nidas::core::Socket::_keepAliveIdleSecs private
Referenced by connect(), getKeepAliveIdleSecs(), setKeepAliveIdleSecs(), and Socket().
_name
std::string nidas::core::Socket::_name private
Referenced by getName(), and setName().
_newInput
bool nidas::core::Socket::_newInput private
Referenced by connect(), isNewInput(), and read().
_nonBlocking
bool nidas::core::Socket::_nonBlocking private
Referenced by connect(), isNonBlocking(), setNonBlocking(), and Socket().
_nusocket
nidas::util::Socket* nidas::core::Socket::_nusocket private
Referenced by close(), connect(), getBufferSize(), getFd(), getInterfaces(), getKeepAliveIdleSecs(), isNonBlocking(), read(), setKeepAliveIdleSecs(), setNonBlocking(), Socket(), write(), and ~Socket().
_remoteHost
std::string nidas::core::Socket::_remoteHost private
Referenced by getRemoteHost(), getRemoteSocketAddress(), setRemoteHostPort(), and Socket().
_remotePort
unsigned short nidas::core::Socket::_remotePort private
Referenced by getRemotePort(), getRemoteSocketAddress(), and setRemoteHostPort().
_remoteSockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::Socket::_remoteSockAddr private
Referenced by getRemoteSocketAddress(), setRemoteSocketAddress(), and Socket().
_requestType
enum McSocketRequest nidas::core::Socket::_requestType private
Referenced by getRequestType().
_unixPath
std::string nidas::core::Socket::_unixPath private
Referenced by getRemoteUnixPath(), setRemoteUnixPath(), and Socket().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/Socket.h
nidas/core/Socket.cc