nidas: MergeVerifier Class Reference
MergeVerifier Class Reference
Public Member Functions
MergeVerifier ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
void printHeader (const SampleInputHeader &header)
for debugging.
void reportMissing (SampleInputStream *input, SampleInputStream *merge, Sample *samp)
void reportBackward (int nback, SampleInputStream *input, Sample *samp)
void reportDuplicate (unsigned ndup, SampleInputStream *merge, Sample *samp)
Static Public Member Functions
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
static int main (int argc, char **argv) throw ()
static int usage (const char *argv0)
Private Attributes
vector< list< string > > inputFileNames
list< string > mergeFileNames
long readAheadUsecs
n_u::UTime startTime
n_u::UTime endTime
size_t nmissing
Static Private Attributes
static bool interrupted = false
Constructor & Destructor Documentation
MergeVerifier()
MergeVerifier::MergeVerifier ()
Member Function Documentation
main()
int MergeVerifier::main (int argc, char ** argv) throw () static
References parseRunstring(), run(), and setupSignals().
Referenced by main().
parseRunstring()
int MergeVerifier::parseRunstring (int argc, char ** argv) throw ()
References nidas::util::UTime::parse(), usage(), USECS_PER_SEC, and nidas::util::Exception::what().
Referenced by main().
printHeader()
void MergeVerifier::printHeader (const SampleInputHeader & header)
for debugging.
References nidas::core::SampleInputHeader::getArchiveVersion(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::SampleInputHeader::getConfigVersion(), nidas::core::SampleInputHeader::getProjectName(), nidas::core::SampleInputHeader::getSoftwareVersion(), and nidas::core::SampleInputHeader::getSystemName().
Referenced by run().
reportBackward()
void MergeVerifier::reportBackward (int nback, SampleInputStream * input, Sample * samp)
References nidas::util::UTime::format(), GET_DSM_ID, GET_SHORT_ID, nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getName(), nidas::core::Sample::getTimeTag(), and nmissing.
Referenced by run().
reportDuplicate()
void MergeVerifier::reportDuplicate (unsigned ndup, SampleInputStream * merge, Sample * samp)
References nidas::util::UTime::format(), GET_DSM_ID, GET_SHORT_ID, nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getName(), and nidas::core::Sample::getTimeTag().
Referenced by run().
reportMissing()
void MergeVerifier::reportMissing (SampleInputStream * input, SampleInputStream * merge, Sample * samp)
References nidas::util::UTime::format(), GET_DSM_ID, GET_SHORT_ID, nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getName(), nidas::core::Sample::getTimeTag(), and nmissing.
Referenced by run().
run()
int MergeVerifier::run () throw ()
References nidas::core::FileSet::addFileName(), endTime, nidas::util::UTime::format(), nidas::core::Sample::freeReference(), nidas::util::Exception::getErrno(), nidas::core::FileSet::getFileSet(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::FileSet::getName(), nidas::dynld::SampleInputStream::getName(), nidas::core::Sample::getTimeTag(), inputFileNames, interrupted, mergeFileNames, printHeader(), readAheadUsecs, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSample(), reportBackward(), reportDuplicate(), reportMissing(), nidas::core::FileSet::setEndTime(), nidas::core::FileSet::setFileName(), nidas::dynld::SampleInputStream::setMaxSampleLength(), nidas::dynld::SampleInputStream::setMaxSampleTime(), nidas::dynld::SampleInputStream::setMinSampleTime(), nidas::core::FileSet::setStartTime(), nidas::core::Sample::setTimeTag(), startTime, nidas::util::UTime::toUsecs(), USECS_PER_DAY, and nidas::util::Exception::what().
Referenced by main().
setupSignals()
void MergeVerifier::setupSignals () static
References sigAction().
sigAction()
void MergeVerifier::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
Referenced by setupSignals().
usage()
int MergeVerifier::usage (const char * argv0) static
Member Data Documentation
endTime
n_u::UTime MergeVerifier::endTime private
Referenced by run().
inputFileNames
vector<list<string> > MergeVerifier::inputFileNames private
Referenced by run().
interrupted
bool MergeVerifier::interrupted = false static private
Referenced by run(), and sigAction().
mergeFileNames
list<string> MergeVerifier::mergeFileNames private
Referenced by run().
nmissing
size_t MergeVerifier::nmissing private
Referenced by reportBackward(), and reportMissing().
readAheadUsecs
long MergeVerifier::readAheadUsecs private
Referenced by run().
startTime
n_u::UTime MergeVerifier::startTime private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/merge_verify.cc