nidas: nidas::dynld::raf::CVIProcessor Class Reference
nidas::dynld::raf::CVIProcessor Class Reference
Processor to support Counter-flow Virtual Impactor.
#include <CVIProcessor.h>
Public Member Functions
CVIProcessor ()
~CVIProcessor ()
void flush () throw ()
Implementation of SampleSource and SampleClient flush().
void addRequestedSampleTag (SampleTag *tag)
void connectSource (SampleSource *) override
Do common operations necessary when a input has connected:
void disconnectSource (SampleSource *) throw ()
Disconnect a SampleSource from this CVIProcessor.
void connect (SampleOutput *output) throw ()
Do common operations necessary when a output has connected:
void disconnect (SampleOutput *output) throw ()
Do common operations necessary when a output has disconnected:
void setD2ADeviceName (const std::string &val)
const std::string & getD2ADeviceName () const
void setDigIODeviceName (const std::string &val)
const std::string & getDigIODeviceName ()
bool receive (const Sample *s) throw ()
The CVIProcessor receive method is configured to received the processed samples from CVI_LV_Input.
void fromDOMElement (const xercesc::DOMElement *node)
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual std::list< const SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
virtual void printStatus (std::ostream &, float, int &) throw ()
virtual void init (dsm_time_t) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void attachLVInput (SampleSource *src, const SampleTag *tag)
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
CVIProcessor (const CVIProcessor &)
Copy not supported.
CVIProcessor & operator= (const CVIProcessor &)
Assignment not supported.
Private Attributes
nidas::util::Mutex _connectionMutex
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
SampleTag * _outputSampleTag
std::string _d2aDeviceName
std::string _digioDeviceName
std::vector< bool > _varMatched
SampleAverager _averager
float _rate
dsm_sample_id_t _lvSampleId
DSC_AnalogOut _aout
ViperDIO _dout
unsigned int _numD2A
unsigned int _numDigout
float _vouts [5]
int _douts [4]
const Site * _site
std::string _name
dsm_sample_id_t _id
std::list< const SampleTag * > _constRequestedTags
std::list< SampleOutput * > _origOutputs
bool _optional
const DSMService * _service
What service am I a part of?
const DSMConfig * _dsm
Or, what DSM am I a part of?
std::list< Parameter * > _parameters
std::list< const Parameter * > _constParameters
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Processor to support Counter-flow Virtual Impactor.
Constructor & Destructor Documentation
CVIProcessor() [1/2]
CVIProcessor::CVIProcessor ()
~CVIProcessor()
CVIProcessor::~CVIProcessor ()
References nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
CVIProcessor() [2/2]
nidas::dynld::raf::CVIProcessor::CVIProcessor (const CVIProcessor &) private
Copy not supported.
Member Function Documentation
addOutput()
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
addParameter()
void SampleIOProcessor::addParameter (Parameter * val) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::SampleIOProcessor::_constParameters, and nidas::core::SampleIOProcessor::_parameters.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
addRequestedSampleTag()
void CVIProcessor::addRequestedSampleTag (SampleTag * tag) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleTag::getRate(), nidas::core::DSMConfig::getSite(), nidas::core::SampleTag::getVariables(), and nidas::core::Variable::setSite().
addSampleClient()
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleClientForTag()
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
addSampleTag()
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
attachLVInput()
void CVIProcessor::attachLVInput (SampleSource * src, const SampleTag * tag) protected
Exceptions
nidas::util::IOException
References nidas::core::SampleSource::addSampleClientForTag(), and nidas::core::SampleTag::getId().
connect()
void CVIProcessor::connect (SampleOutput * output) throw () virtual
Do common operations necessary when a output has connected:
do: output->init().
add output to a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References ILOG.
connectSource()
void CVIProcessor::connectSource (SampleSource * source) override virtual
Do common operations necessary when a input has connected:
Copy the DSMConfig information from the input to the disconnected outputs.
Request connections for all disconnected outputs.
connect() methods in subclasses should do whatever initialization necessary before invoking this CVIProcessor::connect().
Exceptions
nidas::util::InvalidParameterException
nidas::util::IOException
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), nidas::core::Project::findSensor(), GET_DSM_ID, GET_SHORT_ID, nidas::core::SampleTag::getId(), nidas::core::Project::getInstance(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::core::DSMSensor::getName(), nidas::core::SampleSource::getProcessedSampleSource(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleSource::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), and nidas::core::SampleTagIterator::next().
disconnect()
void CVIProcessor::disconnect (SampleOutput * output) throw () virtual
Do common operations necessary when a output has disconnected:
do: output->close().
remove output from a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
disconnectSource()
void CVIProcessor::disconnectSource (SampleSource * source) throw () virtual
Disconnect a SampleSource from this CVIProcessor.
Calls flush() on the averager and closes the digital and analog outputs.
Implements nidas::core::SampleIOProcessor.
flush()
void CVIProcessor::flush () throw () virtual
Implementation of SampleSource and SampleClient flush().
Implements nidas::core::SampleClient.
References nidas::core::SampleClient::flush().
fromDOMElement()
void CVIProcessor::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::SampleIOProcessor::getName(), and nidas::core::Parameter::getStringValue().
getClientCount()
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getClientCount().
getD2ADeviceName()
const std::string& nidas::dynld::raf::CVIProcessor::getD2ADeviceName () const inline
getDigIODeviceName()
const std::string& nidas::dynld::raf::CVIProcessor::getDigIODeviceName () inline
getDSMConfig()
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
getId()
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
getName()
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::connectSource(), fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getOutputs()
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::SampleArchiver::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::dynld::raf::SyncRecordGenerator::connectSource(), nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
getParameters()
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
getProcessedSampleSource()
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
getRawSampleSource()
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getRequestedSampleTags()
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
getSampleId()
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
getSampleStats()
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::SampleIOProcessor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::psql::PSQLProcessor.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
getService()
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
init()
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
isOptional()
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
operator=()
CVIProcessor& nidas::dynld::raf::CVIProcessor::operator= (const CVIProcessor &) private
Assignment not supported.
printStatus()
virtual void nidas::core::SampleIOProcessor::printStatus (std::ostream & , float , int &) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::core::SampleArchiver.
Referenced by nidas::dynld::RawSampleService::printStatus().
receive()
bool CVIProcessor::receive (const Sample * s) throw () virtual
The CVIProcessor receive method is configured to received the processed samples from CVI_LV_Input.
These samples contain settings for the analog and digital out channels. receive() reads these values and controls the outputs accordingly.
Implements nidas::core::SampleClient.
References nidas::util::BitArray::any(), nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, nidas::util::BitArray::setBit(), and nidas::util::Exception::what().
removeRequestedSampleTag()
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
removeSampleClient()
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleClientForTag()
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
removeSampleTag()
void SampleIOProcessor::removeSampleTag (const SampleTag *) throw () virtual inherited
Exceptions
Implements nidas::core::SampleSource.
setD2ADeviceName()
void nidas::dynld::raf::CVIProcessor::setD2ADeviceName (const std::string & val) inline
setDigIODeviceName()
void nidas::dynld::raf::CVIProcessor::setDigIODeviceName (const std::string & val) inline
setDSMConfig()
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
setName()
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
setOptional()
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
setSampleId()
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
setService()
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_aout
DSC_AnalogOut nidas::dynld::raf::CVIProcessor::_aout private
_averager
SampleAverager nidas::dynld::raf::CVIProcessor::_averager private
_connectedOutputs
std::set<SampleOutput*> nidas::dynld::raf::CVIProcessor::_connectedOutputs private
_connectedSources
std::set<SampleSource*> nidas::dynld::raf::CVIProcessor::_connectedSources private
_connectionMutex
nidas::util::Mutex nidas::dynld::raf::CVIProcessor::_connectionMutex private
_constParameters
std::list<const Parameter*> nidas::core::SampleIOProcessor::_constParameters private inherited
Referenced by nidas::core::SampleIOProcessor::addParameter(), and nidas::core::SampleIOProcessor::getParameters().
_constRequestedTags
std::list<const SampleTag*> nidas::core::SampleIOProcessor::_constRequestedTags private inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), and nidas::core::SampleIOProcessor::removeRequestedSampleTag().
_d2aDeviceName
std::string nidas::dynld::raf::CVIProcessor::_d2aDeviceName private
_digioDeviceName
std::string nidas::dynld::raf::CVIProcessor::_digioDeviceName private
_dout
ViperDIO nidas::dynld::raf::CVIProcessor::_dout private
_douts
int nidas::dynld::raf::CVIProcessor::_douts[4] private
_dsm
const DSMConfig* nidas::core::SampleIOProcessor::_dsm private inherited
Or, what DSM am I a part of?
Referenced by nidas::core::SampleIOProcessor::getDSMConfig(), and nidas::core::SampleIOProcessor::setDSMConfig().
_id
dsm_sample_id_t nidas::core::SampleIOProcessor::_id private inherited
Referenced by nidas::core::SampleIOProcessor::getId(), nidas::core::SampleIOProcessor::getSampleId(), and nidas::core::SampleIOProcessor::setSampleId().
_lvSampleId
dsm_sample_id_t nidas::dynld::raf::CVIProcessor::_lvSampleId private
_name
std::string nidas::core::SampleIOProcessor::_name private inherited
Referenced by nidas::core::SampleIOProcessor::getName(), and nidas::core::SampleIOProcessor::setName().
_numD2A
unsigned int nidas::dynld::raf::CVIProcessor::_numD2A private
_numDigout
unsigned int nidas::dynld::raf::CVIProcessor::_numDigout private
_optional
bool nidas::core::SampleIOProcessor::_optional private inherited
Referenced by nidas::core::SampleIOProcessor::isOptional(), and nidas::core::SampleIOProcessor::setOptional().
_origOutputs
std::list<SampleOutput*> nidas::core::SampleIOProcessor::_origOutputs private inherited
Referenced by nidas::core::SampleIOProcessor::addOutput(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleIOProcessor::getOutputs(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_outputSampleTag
SampleTag* nidas::dynld::raf::CVIProcessor::_outputSampleTag private
_parameters
std::list<Parameter*> nidas::core::SampleIOProcessor::_parameters private inherited
Referenced by nidas::core::SampleIOProcessor::addParameter(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_rate
float nidas::dynld::raf::CVIProcessor::_rate private
_requestedTags
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_service
const DSMService* nidas::core::SampleIOProcessor::_service private inherited
What service am I a part of?
Referenced by nidas::core::SampleIOProcessor::getService(), and nidas::core::SampleIOProcessor::setService().
_site
const Site* nidas::dynld::raf::CVIProcessor::_site private
_source
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
_tagsMutex
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
_varMatched
std::vector<bool> nidas::dynld::raf::CVIProcessor::_varMatched private
_vouts
float nidas::dynld::raf::CVIProcessor::_vouts[5] private
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/raf/CVIProcessor.h
nidas/dynld/raf/CVIProcessor.cc