nidas: nidas::core::NearestResampler Class Reference
nidas::core::NearestResampler Class Reference
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
#include <NearestResampler.h>
Public Member Functions
NearestResampler (const std::vector< const Variable * > &vars, bool nansVariable=true)
Constructor.
NearestResampler (const std::vector< Variable * > &vars, bool nansVariable=true)
~NearestResampler ()
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const SampleTag * > getSampleTags () const
Get the SampleTag of my merged output sample.
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
void connect (SampleSource *src)
Connect the resampler to a SampleSource.
void disconnect (SampleSource *src) throw ()
bool receive (const Sample *s) throw ()
Implementation of SampleClient::receive().
void flush () throw ()
Implementation of Resampler::flush().
Private Member Functions
void ctorCommon (const std::vector< const Variable * > &vars, bool nansVariable)
Common tasks of constructors.
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
NearestResampler & operator= (const NearestResampler &)
No assignment.
NearestResampler (const NearestResampler &x)
No copy.
Private Attributes
SampleSourceSupport _source
SampleTag _outSample
std::vector< Variable * > _reqVars
Requested variables.
std::map< Variable *, unsigned int > _outVarIndices
Index of each requested output variable in the output sample.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _inmap
For each input sample, first index of variable data values to be read.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _lenmap
For each input sample, length of variables to read.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _outmap
For each input sample, index into output sample of each variable.
unsigned int _ndataValues
unsigned int _outlen
unsigned int _master
int _nmaster
dsm_time_t * _prevTT
dsm_time_t * _nearTT
float * _prevData
float * _nearData
int * _samplesSinceMaster
std::map< dsm_sample_id_t, unsigned int > _ttOutOfOrder
bool _debug
Detailed Description
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
The first variable added to NearestResample with the addVariable() method becomes the "master" variable. The time tags of the master variable become the output sample time tags, and values of other variables are merged into the output sample by associating those values with the nearest time tag to the master times.
The only requirement is that the samples which are fed to the receive() method should be sorted in time. It they aren't sorted some data will be lost. NearestResampler does not need to know sampling rates, and the sampling rates of the input variables, including the master variable, may vary.
Constructor & Destructor Documentation
NearestResampler() [1/3]
NearestResampler::NearestResampler (const std::vector< const Variable * > & vars, bool nansVariable = true)
Constructor.
References ctorCommon().
NearestResampler() [2/3]
NearestResampler::NearestResampler (const std::vector< Variable * > & vars, bool nansVariable = true)
References ctorCommon().
~NearestResampler()
NearestResampler::~NearestResampler ()
References _nearData, _nearTT, _prevData, _prevTT, _reqVars, and _samplesSinceMaster.
NearestResampler() [3/3]
nidas::core::NearestResampler::NearestResampler (const NearestResampler & x) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::core::NearestResampler::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleClientForTag()
void nidas::core::NearestResampler::addSampleClientForTag (SampleClient * client, const SampleTag *) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleTag()
void nidas::core::NearestResampler::addSampleTag (const SampleTag * tag) throw () inline private virtual
Add a SampleTag to this SampleSource.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleTag().
Referenced by ctorCommon().
connect()
void NearestResampler::connect (SampleSource * src) virtual
Connect the resampler to a SampleSource.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::Resampler.
References _inmap, _lenmap, _outmap, _outVarIndices, _reqVars, nidas::core::SampleSource::addSampleClientForTag(), nidas::core::SampleTag::getDataIndex(), nidas::core::SampleTag::getId(), nidas::core::Variable::getLength(), nidas::core::Variable::getName(), nidas::core::Variable::getNameWithoutSite(), nidas::core::SampleSource::getSampleTags(), nidas::core::Variable::getStation(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), nidas::core::VariableIterator::next(), and WLOG.
Referenced by nidas::dynld::StatisticsCruncher::connect().
ctorCommon()
void NearestResampler::ctorCommon (const std::vector< const Variable * > & vars, bool nansVariable) private
Common tasks of constructors.
References _debug, _master, _ndataValues, _nearData, _nearTT, _nmaster, _outlen, _outSample, _outVarIndices, _prevData, _prevTT, _reqVars, _samplesSinceMaster, addSampleTag(), nidas::core::SampleTag::addVariable(), nidas::core::floatNAN, GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getId(), nidas::core::Project::getInstance(), nidas::core::Variable::getLength(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::Variable::getSampleTag(), nidas::core::Variable::getSite(), nidas::core::Variable::getStation(), nidas::core::Project::getUniqueSampleId(), nidas::core::SampleTag::setDSMId(), nidas::core::Variable::setName(), nidas::core::SampleTag::setSampleId(), nidas::core::Variable::setType(), nidas::core::Variable::setUnits(), and nidas::core::Variable::WEIGHT.
Referenced by NearestResampler().
disconnect()
void NearestResampler::disconnect (SampleSource * src) throw () virtual
Implements nidas::core::Resampler.
flush()
void NearestResampler::flush () throw () virtual
Implementation of Resampler::flush().
Send out whatever samples are available.
Implements nidas::core::Resampler.
References _master, _ndataValues, _nearData, _nearTT, _nmaster, _outlen, _outSample, _prevData, _prevTT, _samplesSinceMaster, _source, nidas::core::SampleSourceSupport::distribute(), nidas::core::floatNAN, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleTag::getId(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
getClientCount()
int nidas::core::NearestResampler::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getClientCount().
getProcessedSampleSource()
SampleSource* nidas::core::NearestResampler::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _source.
getRawSampleSource()
SampleSource* nidas::core::NearestResampler::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getSampleStats()
const SampleStats& nidas::core::NearestResampler::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::NearestResampler::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::NearestResampler::getSampleTags () const inline virtual
Get the SampleTag of my merged output sample.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTags().
operator=()
NearestResampler& nidas::core::NearestResampler::operator= (const NearestResampler &) private
No assignment.
receive()
bool NearestResampler::receive (const Sample * s) throw () virtual
Implementation of SampleClient::receive().
Implements nidas::core::SampleClient.
References nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::core::floatNAN, nidas::util::UTime::format(), GET_DSM_ID, GET_SPS_ID, nidas::core::SampleT< DataT >::getDataLength(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), USECS_PER_SEC, and WLOG.
removeSampleClient()
void nidas::core::NearestResampler::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleClientForTag()
void nidas::core::NearestResampler::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleTag()
void nidas::core::NearestResampler::removeSampleTag (const SampleTag *) throw () inline private virtual
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleTag().
Member Data Documentation
_debug
bool nidas::core::NearestResampler::_debug private
Referenced by ctorCommon().
_inmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResampler::_inmap private
For each input sample, first index of variable data values to be read.
Referenced by connect().
_lenmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResampler::_lenmap private
For each input sample, length of variables to read.
Referenced by connect().
_master
unsigned int nidas::core::NearestResampler::_master private
Referenced by ctorCommon(), and flush().
_ndataValues
unsigned int nidas::core::NearestResampler::_ndataValues private
Referenced by ctorCommon(), and flush().
_nearData
float* nidas::core::NearestResampler::_nearData private
Referenced by ctorCommon(), flush(), and ~NearestResampler().
_nearTT
dsm_time_t* nidas::core::NearestResampler::_nearTT private
Referenced by ctorCommon(), flush(), and ~NearestResampler().
_nmaster
int nidas::core::NearestResampler::_nmaster private
Referenced by ctorCommon(), and flush().
_outlen
unsigned int nidas::core::NearestResampler::_outlen private
Referenced by ctorCommon(), and flush().
_outmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResampler::_outmap private
For each input sample, index into output sample of each variable.
Referenced by connect().
_outSample
SampleTag nidas::core::NearestResampler::_outSample private
Referenced by ctorCommon(), and flush().
_outVarIndices
std::map<Variable*,unsigned int> nidas::core::NearestResampler::_outVarIndices private
Index of each requested output variable in the output sample.
Referenced by connect(), and ctorCommon().
_prevData
float* nidas::core::NearestResampler::_prevData private
Referenced by ctorCommon(), flush(), and ~NearestResampler().
_prevTT
dsm_time_t* nidas::core::NearestResampler::_prevTT private
Referenced by ctorCommon(), flush(), and ~NearestResampler().
_reqVars
std::vector<Variable *> nidas::core::NearestResampler::_reqVars private
Requested variables.
Referenced by connect(), ctorCommon(), and ~NearestResampler().
_samplesSinceMaster
int* nidas::core::NearestResampler::_samplesSinceMaster private
Referenced by ctorCommon(), flush(), and ~NearestResampler().
_source
SampleSourceSupport nidas::core::NearestResampler::_source private
Referenced by addSampleClient(), addSampleClientForTag(), addSampleTag(), flush(), getClientCount(), getProcessedSampleSource(), getSampleStats(), getSampleTagIterator(), getSampleTags(), removeSampleClient(), removeSampleClientForTag(), and removeSampleTag().
_ttOutOfOrder
std::map<dsm_sample_id_t,unsigned int> nidas::core::NearestResampler::_ttOutOfOrder private
The documentation for this class was generated from the following files:
nidas/core/NearestResampler.h
nidas/core/NearestResampler.cc