nidas: nidas::core::Dataset Class Reference
nidas::core::Dataset Class Reference
A Dataset is a named collection of parameters, that are used in data processing.
#include <Datasets.h>
Public Member Functions
Dataset ()
const std::string & getName () const
void setName (const std::string &val)
const std::string & getDescription () const
void setDescription (const std::string &val)
float getResolutionSecs () const
void setResolutionSecs (float val)
void addEnvironmentVariable (const std::string &name, const std::string &value)
Add an environment variable to this Dataset.
std::map< std::string, std::string > getEnvironmentVariables () const
void putenv () const
Update the process environment with the current list of environment variables in the Dataset.
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node) const
Private Attributes
std::string _name
std::string _desc
float _resSecs
std::map< std::string, std::string > _envVars
Detailed Description
A Dataset is a named collection of parameters, that are used in data processing.
In addition to a name, a long-winded description, a resolution in seconds, there are one or more name=value string parameters which are typically set in a Unix process environment.
Constructor & Destructor Documentation
Dataset()
Dataset::Dataset ()
Member Function Documentation
addEnvironmentVariable()
void Dataset::addEnvironmentVariable (const std::string & name, const std::string & value)
Add an environment variable to this Dataset.
The actual process environment is not effected. After doing addEnvironmentVariable() one or more times, use Dataset::putenv() to update the actual process environment. Set value to an empty string to remove a variable from the environment.
References _envVars.
fromDOMElement()
void Dataset::fromDOMElement (const xercesc::DOMElement * node)
Exceptions
nidas::util::InvalidParameterException
References _envVars, _resSecs, getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), setDescription(), and setName().
Referenced by nidas::core::Datasets::fromDOMElement().
getDescription()
const std::string& nidas::core::Dataset::getDescription () const inline
References _desc.
Referenced by toDOMElement().
getEnvironmentVariables()
std::map<std::string,std::string> nidas::core::Dataset::getEnvironmentVariables () const inline
References _envVars.
Referenced by DatasetsApp::showEnv().
getName()
const std::string& nidas::core::Dataset::getName () const inline
References _name.
Referenced by nidas::core::Datasets::addDataset(), fromDOMElement(), DatasetsApp::listDatasetNames(), putenv(), nidas::core::Datasets::removeDataset(), DatasetsApp::showEnv(), and toDOMElement().
getResolutionSecs()
float nidas::core::Dataset::getResolutionSecs () const inline
References _resSecs.
Referenced by StatsProcess::getDataset(), and toDOMElement().
putenv()
void Dataset::putenv () const
Update the process environment with the current list of environment variables in the Dataset.
References _envVars, getName(), and nidas::util::Process::setEnvVar().
Referenced by StatsProcess::getDataset(), and nidas::core::NidasApp::getDataset().
setDescription()
void nidas::core::Dataset::setDescription (const std::string & val) inline
References _desc.
Referenced by fromDOMElement().
setName()
void nidas::core::Dataset::setName (const std::string & val) inline
References _name.
Referenced by fromDOMElement().
setResolutionSecs()
void nidas::core::Dataset::setResolutionSecs (float val) inline
References _resSecs.
toDOMElement()
xercesc::DOMElement * Dataset::toDOMElement (xercesc::DOMElement * node) const
Exceptions
xercesc::DOMException
References _envVars, getDescription(), getName(), nidas::core::DOMable::getNamespaceURI(), getResolutionSecs(), and nidas::core::XDOMElement::setAttributeValue().
Referenced by toDOMParent().
toDOMParent()
xercesc::DOMElement * Dataset::toDOMParent (xercesc::DOMElement * parent) const
Exceptions
xercesc::DOMException
References nidas::core::DOMable::getNamespaceURI(), and toDOMElement().
Referenced by nidas::core::Datasets::toDOMElement().
Member Data Documentation
_desc
std::string nidas::core::Dataset::_desc private
Referenced by getDescription(), and setDescription().
_envVars
std::map<std::string,std::string> nidas::core::Dataset::_envVars private
Referenced by addEnvironmentVariable(), fromDOMElement(), getEnvironmentVariables(), putenv(), and toDOMElement().
_name
std::string nidas::core::Dataset::_name private
Referenced by getName(), and setName().
_resSecs
float nidas::core::Dataset::_resSecs private
Referenced by fromDOMElement(), getResolutionSecs(), and setResolutionSecs().
The documentation for this class was generated from the following files:
nidas/core/Datasets.h
nidas/core/Datasets.cc