nidas: FixedSim Class Reference
FixedSim Class Reference
Send a fixed message at a given rate or after a prompt.
Public Member Functions
FixedSim (n_u::SerialPort *p, const string &m, enum sep_type septype, string sep, bool prompted, string prompt, float rate, int nmessages)
void sendMessage ()
Implement this to send a message from the simulated sensor.
virtual void writeMessage (const std::string &msg)
Subclasses generate the message to send, then call writeMessage() to send it out.
virtual void writeMessage (const char *buf, std::streamsize l)
overloaded function useful for writing binary data
virtual void run ()
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
void interrupt ()
Stop the simulation.
bool isInterrupted () const
n_u::SerialPort * port ()
Protected Member Functions
Looper * getLooper ()
void looperNotify () override
Method called by Looper.
void readPrompts ()
Protected Attributes
n_u::SerialPort * _port
bool _prompted
string _prompt
float _rate
int _nmessages
bool _interrupted
Static Protected Attributes
static Looper * _looper = 0
Private Attributes
string _msg
enum sep_type _septype
string _separator
Detailed Description
Send a fixed message at a given rate or after a prompt.
Constructor & Destructor Documentation
FixedSim()
FixedSim::FixedSim (n_u::SerialPort * p, const string & m, enum sep_type septype, string sep, bool prompted, string prompt, float rate, int nmessages)
References _msg, _separator, _septype, BOM_SEPARATOR, and EOM_SEPARATOR.
Member Function Documentation
getLooper()
Looper * SensorSimulator::getLooper () protected inherited
interrupt()
void SensorSimulator::interrupt () inline inherited
Stop the simulation.
Referenced by FileSim::sendASCIIMessage(), and FileSim::sendBinaryMessage().
isInterrupted()
bool SensorSimulator::isInterrupted () const inline inherited
looperNotify()
void SensorSimulator::looperNotify () override protected virtual inherited
Method called by Looper.
This method should not be a heavy user of resources, since the notification of other clients is delayed until this method finishes. If much work is to be done, this method should post a semaphore for another worker thread to proceed.
Implements nidas::core::LooperClient.
References nidas::util::Exception::what().
port()
n_u::SerialPort* SensorSimulator::port () inline inherited
readPrompts()
void SensorSimulator::readPrompts () protected inherited
run()
void SensorSimulator::run () virtual inherited
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
run() will return when isInterrupted() is true.
Reimplemented in Csat3Sim.
References MSECS_PER_SEC.
sendMessage()
void FixedSim::sendMessage () virtual
Implement this to send a message from the simulated sensor.
Exceptions
nidas::util::IOException
Implements SensorSimulator.
References _msg, and SensorSimulator::writeMessage().
writeMessage() [1/2]
virtual void SensorSimulator::writeMessage (const char * buf, std::streamsize l) inline virtual inherited
overloaded function useful for writing binary data
writeMessage() [2/2]
virtual void SensorSimulator::writeMessage (const std::string & msg) inline virtual inherited
Subclasses generate the message to send, then call writeMessage() to send it out.
Referenced by FileSim::sendASCIIMessage(), FileSim::sendBinaryMessage(), and sendMessage().
Member Data Documentation
_interrupted
bool SensorSimulator::_interrupted protected inherited
_looper
Looper * SensorSimulator::_looper = 0 static protected inherited
_msg
string FixedSim::_msg private
Referenced by FixedSim(), and sendMessage().
_nmessages
int SensorSimulator::_nmessages protected inherited
Referenced by Csat3Sim::run().
_port
n_u::SerialPort* SensorSimulator::_port protected inherited
Referenced by Csat3Sim::run(), and Csat3Sim::sendMessage().
_prompt
string SensorSimulator::_prompt protected inherited
_prompted
bool SensorSimulator::_prompted protected inherited
_rate
float SensorSimulator::_rate protected inherited
Referenced by Csat3Sim::run().
_separator
string FixedSim::_separator private
Referenced by FixedSim().
_septype
enum sep_type FixedSim::_septype private
Referenced by FixedSim().
The documentation for this class was generated from the following file:
nidas/apps/sensor_sim.cc