nidas: nidas::core::Project Class Reference
nidas::core::Project Class Reference
#include <Project.h>
Classes
class MyDictionary
Public Member Functions
Project ()
virtual ~Project ()
void parseXMLConfigFile (const std::string &xmlfilepath)
Convenient method to fill this Project instance from the configuration in the XML file at xmlfilepath, using the nidas::core::parseXMLConfigFile() function.
void setName (const std::string &val)
const std::string & getName () const
void setSystemName (const std::string &val)
const std::string & getSystemName () const
void setConfigVersion (const std::string &val)
const std::string & getConfigVersion () const
void setConfigName (const std::string &val)
const std::string & getConfigName () const
void setFlightName (const std::string &val)
const std::string & getFlightName () const
void addSite (Site *val)
const std::list< Site * > & getSites () const
int getMaxSiteNumber () const
Convenience function to return the maximum site number.
int getMinSiteNumber () const
void addServer (DSMServer *srvr)
A Project has one or more DSMServers.
const std::list< DSMServer * > & getServers () const
std::list< DSMServer * > findServers (const std::string &hostname) const
Look for a server for this project that either has no name or whose name matches hostname.
DSMServer * findServer (const nidas::util::Inet4Address &addr) const
const DSMConfig * findDSM (const nidas::util::Inet4Address &addr) const
Find a DSM whose name corresponds to a given IP address.
const DSMConfig * findDSM (const std::string &name) const
DSMConfig * findDSMFromHostname (const std::string &hostname)
Find a DSMConfig in any site in this project whose name matches the given hostname.
const DSMConfig * findDSM (unsigned int id) const
Find a DSM matching id;.
std::list< nidas::core::FileSet * > findServerSampleOutputStreamFileSets (const std::string &name) const
Find SampleOutputStreamFileSets belonging to SampleArchivers of DSMServers whose name matches the argument name.
std::list< nidas::core::FileSet * > findServerSampleOutputStreamFileSets () const
Call findServerSampleOutputStreamFileSets(name) passing the nodename returned by uname(2).
std::list< nidas::core::FileSet * > findSampleOutputStreamFileSets (const std::string &dsmName) const
Find SampleOutputStreamFileSets belonging to the given DSM.
std::list< nidas::core::FileSet * > findSampleOutputStreamFileSets () const
Find SampleOutputStreamFileSets of all DSMs.
DSMSensor * findSensor (dsm_sample_id_t id) const
DSMSensor * findSensor (const SampleTag *tag) const
Site * findSite (int stationNumber) const
Find a Site with the given station number.
Site * findSite (const std::string &name) const
Find a Site with the given name.
dsm_sample_id_t getUniqueSampleId (unsigned int dsmid)
Get a temporary unique sample id for a given DSM id.
void setSensorCatalog (SensorCatalog *val)
SensorCatalog * getSensorCatalog () const
void setDSMCatalog (DSMCatalog *val)
DSMCatalog * getDSMCatalog () const
void setServiceCatalog (ServiceCatalog *val)
ServiceCatalog * getServiceCatalog () const
DSMServerIterator getDSMServerIterator () const
DSMServiceIterator getDSMServiceIterator () const
ProcessorIterator getProcessorIterator () const
SiteIterator getSiteIterator () const
DSMConfigIterator getDSMConfigIterator () const
SensorIterator getSensorIterator () const
SampleTagIterator getSampleTagIterator () const
VariableIterator getVariableIterator () const
void initSensors ()
Initialize all sensors for a Project.
void initSensors (Site *site)
Initialize all sensors for a given Site.
void initSensors (DSMConfig *dsm)
Initialize all sensors for a given dsm.
const Parameter * getParameter (const std::string &name) const
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $PROJECT, and $SYSTEM.
const Dictionary & getDictionary () const
void setDataset (const Dataset &val)
const Dataset & getDataset () const
void disableAutoconfig (bool disable)
When true, autoconfig elements in the config document are removed before realizing the Project with fromDOMElement().
Static Public Member Functions
static Project * getInstance ()
Project is a singleton.
static void destroyInstance ()
Destory the singleton.
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void addParameter (Parameter *val)
Add a parameter to this Project.
Private Member Functions
void removeAutoConfig (xercesc::DOMNode *node, bool bumpRecursion=false)
Scan the DOM and pull out any <autoconfig> tags, as well as change the autoconfig classes back to DSMSerialSensor, or isff.PropVane as needed, and remove porttype attributes.
Project (const Project &)
Copy not supported.
Project & operator= (const Project &)
Assignment not supported.
Private Attributes
std::string _name
std::string _sysname
std::string _configVersion
std::string _configName
Name of XML file that this project was initialized from.
std::string _flightName
nidas::core::Project::MyDictionary _dictionary
std::list< Site * > _sites
SensorCatalog * _sensorCatalog
DSMCatalog * _dsmCatalog
ServiceCatalog * _serviceCatalog
std::list< DSMServer * > _servers
nidas::util::Mutex _lookupLock
std::map< dsm_sample_id_t, const DSMConfig * > _dsmById
nidas::util::Mutex _sensorMapLock
std::map< dsm_sample_id_t, DSMSensor * > _sensorById
std::map< int, Site * > _siteByStationNumber
std::map< std::string, Site * > _siteByName
std::set< dsm_sample_id_t > _usedIds
int _maxSiteNumber
int _minSiteNumber
std::list< Parameter * > _parameters
List of pointers to Parameters.
Dataset _dataset
The current dataset.
bool _disableAutoconfig
Static Private Attributes
static Project * _instance = 0
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
Project() [1/2]
Project::Project ()
References _instance.
~Project()
Project::~Project () virtual
References _dsmCatalog, _instance, _parameters, _sensorCatalog, _servers, _serviceCatalog, and _sites.
Project() [2/2]
nidas::core::Project::Project (const Project &) private
Copy not supported.
The main problem with a supporting a copy constructor is that one would need a clone for all the DSMSensors, which would be hard to get and keep correct. Instead of copying/cloning a project, create a new one and initialize it from a DOMElement.
Member Function Documentation
addParameter()
void nidas::core::Project::addParameter (Parameter * val) inline protected
Add a parameter to this Project.
Project will then own the pointer and will delete it in its destructor.
References _parameters.
Referenced by fromDOMElement().
addServer()
void nidas::core::Project::addServer (DSMServer * srvr) inline
A Project has one or more DSMServers.
References _servers.
Referenced by fromDOMElement().
addSite()
void Project::addSite (Site * val)
References _lookupLock, _maxSiteNumber, _minSiteNumber, _siteByName, _siteByStationNumber, _sites, nidas::core::Site::getName(), nidas::core::Site::getNumber(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by fromDOMElement().
destroyInstance()
void Project::destroyInstance () static
Destory the singleton.
Referenced by main(), AutoProject::~AutoProject(), and nidas::core::NidasApp::~NidasApp().
disableAutoconfig()
void nidas::core::Project::disableAutoconfig (bool disable) inline
When true, autoconfig elements in the config document are removed before realizing the Project with fromDOMElement().
References _disableAutoconfig.
Referenced by nidas::core::DSMEngine::initialize().
expandString()
std::string nidas::core::Project::expandString (const std::string & input) const inline
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References _dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::XMLConfigWriterFilter::acceptDSMNode(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::WisardMote::createSampleTag(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::DSMSensor::getClassName(), and nidas::dynld::isff::WindOrienter::handleParameter().
findDSM() [1/3]
const DSMConfig * Project::findDSM (const nidas::util::Inet4Address & addr) const
Find a DSM whose name corresponds to a given IP address.
References DLOG, nidas::core::Site::findDSM(), nidas::util::Inet4Address::getAllByName(), getDSMConfigIterator(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4NetworkInterface::getIndex(), nidas::util::Logger::getInstance(), nidas::util::Inet4NetworkInterface::getInterface(), nidas::core::DSMConfig::getName(), nidas::core::Site::getName(), nidas::util::Inet4NetworkInterface::getName(), getSiteIterator(), nidas::core::SiteIterator::hasNext(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Exception::what(), and WLOG.
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::XMLConfigService::connected(), findDSM(), findSampleOutputStreamFileSets(), StatsProcess::getStatisticsProcessor(), and nidas::dynld::SampleInputStream::setIOChannel().
findDSM() [2/3]
const DSMConfig * Project::findDSM (const std::string & name) const
References findDSM(), nidas::core::Site::findDSM(), nidas::util::Inet4Address::getAllByName(), getSiteIterator(), nidas::core::SiteIterator::hasNext(), and WLOG.
findDSM() [3/3]
const DSMConfig * Project::findDSM (unsigned int id) const
Find a DSM matching id;.
References _dsmById, _lookupLock, DLOG, nidas::core::Site::findDSM(), getSiteIterator(), nidas::core::SiteIterator::hasNext(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
findDSMFromHostname()
DSMConfig * Project::findDSMFromHostname (const std::string & hostname)
Find a DSMConfig in any site in this project whose name matches the given hostname.
If the hostname is fully qualified, then the match is attempted against the long name first and then the shortened name, with everything past the first '.' removed.
If there is only one DSM in the entire project config, then that DSM is always returned.
DSMEngine uses this method to look up it's DSMConfig instance on startup, based on the current hostname setting.
References nidas::core::Site::getDSMConfigs(), nidas::util::Logger::getInstance(), nidas::core::DSMConfig::getName(), getSites(), nidas::util::Logger::log(), and LOG_INFO.
Referenced by nidas::core::DSMEngine::initialize().
findSampleOutputStreamFileSets() [1/2]
list< nidas::core::FileSet * > Project::findSampleOutputStreamFileSets () const
Find SampleOutputStreamFileSets of all DSMs.
References nidas::core::DSMConfig::findSampleOutputStreamFileSets(), getDSMConfigIterator(), and nidas::core::DSMConfigIterator::hasNext().
findSampleOutputStreamFileSets() [2/2]
list< nidas::core::FileSet * > Project::findSampleOutputStreamFileSets (const std::string & dsmName) const
Find SampleOutputStreamFileSets belonging to the given DSM.
References findDSM(), and nidas::core::DSMConfig::findSampleOutputStreamFileSets().
Referenced by DataPrep::run(), and StatsProcess::run().
findSensor() [1/2]
DSMSensor * Project::findSensor (const SampleTag * tag) const
References findSensor(), and nidas::core::SampleTag::getId().
findSensor() [2/2]
DSMSensor * Project::findSensor (dsm_sample_id_t id) const
References _sensorById, _sensorMapLock, nidas::core::Site::findSensor(), getSiteIterator(), nidas::core::SiteIterator::hasNext(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by nidas::dynld::raf::CVIProcessor::connectSource(), findSensor(), nidas::dynld::ParoSci_202BG_P::init(), and nidas::dynld::ParoSci_202BG_T::init().
findServer()
DSMServer * Project::findServer (const nidas::util::Inet4Address & addr) const
References nidas::util::Inet4Address::getAllByName(), getDSMServerIterator(), nidas::core::DSMServer::getName(), nidas::core::DSMServerIterator::hasNext(), and nidas::core::DSMServerIterator::next().
Referenced by findServers().
findServers()
list< DSMServer * > Project::findServers (const std::string & hostname) const
Look for a server for this project that either has no name or whose name matches hostname.
Look for a server for this project that whose name matches my hostname.
If none found, remove any domain names and try again. Then search the project Sites.
If none found, remove any domain names and try again. If still none found return any configured servers with no name.
References findServer(), nidas::util::Inet4Address::getAllByName(), getDSMServerIterator(), nidas::core::DSMServer::getName(), nidas::core::DSMServerIterator::hasNext(), and nidas::core::DSMServerIterator::next().
Referenced by findServerSampleOutputStreamFileSets(), StatsProcess::getStatisticsProcessor(), and nidas::core::DSMServerApp::run().
findServerSampleOutputStreamFileSets() [1/2]
list< nidas::core::FileSet * > Project::findServerSampleOutputStreamFileSets () const
Call findServerSampleOutputStreamFileSets(name) passing the nodename returned by uname(2).
Exceptions
nidas::util::Exception
References WLOG.
findServerSampleOutputStreamFileSets() [2/2]
list< nidas::core::FileSet * > Project::findServerSampleOutputStreamFileSets (const std::string & name) const
Find SampleOutputStreamFileSets belonging to SampleArchivers of DSMServers whose name matches the argument name.
If no DSMServer names exactly match, then return the filesets corresponding to a DSMServer with an empty name.
References findServers(), nidas::core::SampleOutput::getIOChannel(), nidas::core::DSMServer::getName(), nidas::core::SampleIOProcessor::getOutputs(), nidas::core::DSMServer::getProcessorIterator(), nidas::core::ProcessorIterator::hasNext(), and nidas::core::ProcessorIterator::next().
Referenced by nidas::core::GetAdsFileName::execute(), DataPrep::run(), and StatsProcess::run().
findSite() [1/2]
Site * Project::findSite (const std::string & name) const
Find a Site with the given name.
References _lookupLock, and _siteByName.
findSite() [2/2]
Site * Project::findSite (int stationNumber) const
Find a Site with the given station number.
References _lookupLock, and _siteByStationNumber.
fromDOMElement()
void Project::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References _dictionary, _disableAutoconfig, _maxSiteNumber, addParameter(), addServer(), addSite(), nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DSMCatalog::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::SensorCatalog::fromDOMElement(), nidas::core::ServiceCatalog::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), ILOG, LogSchemeFromDOMElement(), removeAutoConfig(), setConfigName(), setConfigVersion(), setDSMCatalog(), setName(), nidas::core::DSMServer::setProject(), nidas::core::Site::setProject(), setSensorCatalog(), setServiceCatalog(), setSystemName(), nidas::core::Site::validate(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMEngine::initialize(), nidas::core::ProjectConfig::initProject(), StatsProcess::listOutputSamples(), PConfig::loadFile(), PConfig::loadRemoteXML(), main(), nidas::core::DSMServerApp::parseXMLConfigFile(), parseXMLConfigFile(), DataPrep::run(), ExtractFast2D::run(), ExtractDMT::run(), and StatsProcess::run().
getConfigName()
const std::string& nidas::core::Project::getConfigName () const inline
References _configName.
getConfigVersion()
const std::string& nidas::core::Project::getConfigVersion () const inline
References _configVersion.
getDataset()
const Dataset& nidas::core::Project::getDataset () const inline
References _dataset.
getDictionary()
const Dictionary& nidas::core::Project::getDictionary () const inline
References _dictionary.
getDSMCatalog()
DSMCatalog* nidas::core::Project::getDSMCatalog () const inline
References _dsmCatalog.
Referenced by nidas::core::DSMConfig::fromDOMElement().
getDSMConfigIterator()
DSMConfigIterator Project::getDSMConfigIterator () const
Referenced by nidas::core::GetDsmList::execute(), findDSM(), findSampleOutputStreamFileSets(), DataPrep::matchVariables(), ExtractFast2D::run(), and ExtractDMT::run().
getDSMServerIterator()
DSMServerIterator Project::getDSMServerIterator () const
Referenced by findServer(), and findServers().
getDSMServiceIterator()
DSMServiceIterator Project::getDSMServiceIterator () const
getFlightName()
const string & Project::getFlightName () const
References _flightName, and _lookupLock.
getInstance()
Project * Project::getInstance () static
Project is a singleton.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), AutoProject::AutoProject(), nidas::dynld::RawSampleService::connect(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::raf::SyncRecordSource::connect(), nidas::dynld::XMLConfigService::connected(), nidas::dynld::UDPSampleOutput::connected(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::isff::WisardMote::createSampleTag(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::PacketInputStream::getGOESProject(), nidas::core::NidasApp::getProject(), nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::dynld::isff::WindOrienter::handleParameter(), nidas::dynld::ParoSci_202BG_P::init(), nidas::dynld::ParoSci_202BG_T::init(), nidas::dynld::psql::PSQLSampleOutput::initializeGlobalAttributes(), nidas::dynld::raf::SyncServer::initProject(), nidas::dynld::raf::SyncServer::initSensors(), main(), nidas::dynld::isff::Wind3D::parseParameters(), ARLIngest::prepareHeaderIds(), nidas::core::SampleScanner::readBuffer(), ExtractFast2D::run(), ExtractDMT::run(), nidas::dynld::XMLConfigService::Worker::run(), nidas::core::SampleAverager::SampleAverager(), nidas::core::HeaderSource::setDefaults(), nidas::core::FileSet::setDir(), nidas::core::FileSet::setFileName(), and nidas::dynld::SampleInputStream::setIOChannel().
getMaxSiteNumber()
int nidas::core::Project::getMaxSiteNumber () const inline
Convenience function to return the maximum site number.
References _maxSiteNumber.
getMinSiteNumber()
int nidas::core::Project::getMinSiteNumber () const inline
References _minSiteNumber.
getName()
const std::string& nidas::core::Project::getName () const inline
References _name.
Referenced by SampleCounter::collectMetadata(), nidas::dynld::UDPSampleOutput::connected(), fromDOMElement(), nidas::core::DSMService::fromDOMElement(), SampleCounter::generateStreamId(), nidas::dynld::isff::PacketInputStream::getGOESProject(), nidas::core::Project::MyDictionary::getTokenValue(), nidas::dynld::psql::PSQLSampleOutput::initializeGlobalAttributes(), nidas::core::DSMSensor::readSamples(), and toDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getParameter()
const Parameter * Project::getParameter (const std::string & name) const
References _parameters, and nidas::core::Parameter::getName().
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::isff::PacketInputStream::getGOESProject(), and nidas::dynld::isff::Wind3D::parseParameters().
getProcessorIterator()
ProcessorIterator Project::getProcessorIterator () const
getSampleTagIterator()
SampleTagIterator Project::getSampleTagIterator () const
Referenced by getUniqueSampleId().
getSensorCatalog()
SensorCatalog* nidas::core::Project::getSensorCatalog () const inline
References _sensorCatalog.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::DSMSensor::getClassName().
getSensorIterator()
SensorIterator Project::getSensorIterator () const
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMServer::getSensorIterator(), nidas::dynld::raf::SyncServer::initSensors(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromProject(), and PConfig::showSensorClasses().
getServers()
const std::list<DSMServer*>& nidas::core::Project::getServers () const inline
References _servers.
getServiceCatalog()
ServiceCatalog* nidas::core::Project::getServiceCatalog () const inline
References _serviceCatalog.
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::getClassName().
getSiteIterator()
SiteIterator Project::getSiteIterator () const
Referenced by nidas::dynld::UDPSampleOutput::connected(), findDSM(), findSensor(), PConfig::getHostNames(), PConfig::loadVariables(), PConfig::showAll(), PConfig::showCalFiles(), and toDOMElement().
getSites()
const std::list<Site*>& nidas::core::Project::getSites () const inline
References _sites.
Referenced by findDSMFromHostname(), nidas::dynld::raf::Aircraft::getAircraft(), and initSensors().
getSystemName()
const std::string& nidas::core::Project::getSystemName () const inline
References _sysname.
Referenced by nidas::core::Project::MyDictionary::getTokenValue(), and nidas::core::HeaderSource::setDefaults().
getTokenValue()
bool nidas::core::Project::getTokenValue (const std::string & token, std::string & value) const inline
Implement a lookup for tokens that I know about, like $PROJECT, and $SYSTEM.
For other tokens, look them up in the process environment.
References _dictionary, and nidas::core::Project::MyDictionary::getTokenValue().
Referenced by nidas::core::Site::MyDictionary::getTokenValue().
getUniqueSampleId()
dsm_sample_id_t Project::getUniqueSampleId (unsigned int dsmid)
Get a temporary unique sample id for a given DSM id.
This id can be used for identifying derived samples during processing, when they are passed between SampleSources and SampleClients. The value of these ids is not saved anywhere, and so they are meant to be used for temporary connections, not for archived samples.
References _sensorMapLock, _usedIds, GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SampleTagIterator::next(), SET_DSM_ID, and SET_SHORT_ID.
Referenced by nidas::core::NearestResampler::ctorCommon(), and nidas::core::NearestResamplerAtRate::ctorCommon().
getVariableIterator()
VariableIterator Project::getVariableIterator () const
initSensors() [1/3]
void Project::initSensors ()
Initialize all sensors for a Project.
Exceptions
nidas::util::IOException
References getSites(), and nidas::core::Site::initSensors().
Referenced by nidas::core::DSMServer::scheduleServices().
initSensors() [2/3]
void Project::initSensors (DSMConfig * dsm)
Initialize all sensors for a given dsm.
Exceptions
nidas::util::IOException
References getSites(), and nidas::core::Site::initSensors().
initSensors() [3/3]
void Project::initSensors (Site * site)
Initialize all sensors for a given Site.
Initialize all sensors for a Site.
Exceptions
nidas::util::IOException
References getSites(), and nidas::core::Site::initSensors().
operator=()
Project& nidas::core::Project::operator= (const Project &) private
Assignment not supported.
See comments about copy constructor.
parseXMLConfigFile()
void Project::parseXMLConfigFile (const std::string & xmlfilepath)
Convenient method to fill this Project instance from the configuration in the XML file at xmlfilepath, using the nidas::core::parseXMLConfigFile() function.
Exceptions
nidas::core::XMLException
References fromDOMElement(), nidas::core::parseXMLConfigFile(), and nidas::core::XMLImplementation::terminate().
Referenced by nidas::dynld::raf::SyncServer::initProject().
removeAutoConfig()
void Project::removeAutoConfig (xercesc::DOMNode * node, bool bumpRecursion = false) private
Scan the DOM and pull out any <autoconfig> tags, as well as change the autoconfig classes back to DSMSerialSensor, or isff.PropVane as needed, and remove porttype attributes.
References nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getElement(), nidas::core::XDOMElement::getNodeName(), ILOG, nidas::core::XDOMElement::setAttributeValue(), and VLOG.
Referenced by fromDOMElement().
setConfigName()
void nidas::core::Project::setConfigName (const std::string & val) inline
References _configName.
Referenced by fromDOMElement(), nidas::core::DSMEngine::initialize(), nidas::dynld::raf::SyncServer::initProject(), DataPrep::run(), StatsProcess::run(), and nidas::core::DSMServerApp::run().
setConfigVersion()
void nidas::core::Project::setConfigVersion (const std::string & val) inline
References _configVersion.
Referenced by fromDOMElement().
setDataset()
void nidas::core::Project::setDataset (const Dataset & val) inline
References _dataset.
Referenced by DataPrep::run(), StatsProcess::run(), and nidas::core::DSMServerApp::run().
setDSMCatalog()
void nidas::core::Project::setDSMCatalog (DSMCatalog * val) inline
References _dsmCatalog.
Referenced by fromDOMElement().
setFlightName()
void nidas::core::Project::setFlightName (const std::string & val) inline
References _flightName.
setName()
void nidas::core::Project::setName (const std::string & val) inline
References _name.
Referenced by fromDOMElement().
setSensorCatalog()
void nidas::core::Project::setSensorCatalog (SensorCatalog * val) inline
References _sensorCatalog.
Referenced by fromDOMElement().
setServiceCatalog()
void nidas::core::Project::setServiceCatalog (ServiceCatalog * val) inline
References _serviceCatalog.
Referenced by fromDOMElement().
setSystemName()
void nidas::core::Project::setSystemName (const std::string & val) inline
References _sysname.
Referenced by fromDOMElement().
toDOMElement()
xercesc::DOMElement * Project::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References getName(), getSiteIterator(), nidas::core::SiteIterator::hasNext(), nidas::core::XDOMElement::setAttributeValue(), and nidas::core::Site::toDOMParent().
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), and toDOMParent().
toDOMParent()
xercesc::DOMElement * Project::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), and toDOMElement().
Member Data Documentation
_configName
std::string nidas::core::Project::_configName private
Name of XML file that this project was initialized from.
Referenced by getConfigName(), and setConfigName().
_configVersion
std::string nidas::core::Project::_configVersion private
Referenced by getConfigVersion(), and setConfigVersion().
_dataset
Dataset nidas::core::Project::_dataset private
The current dataset.
Referenced by getDataset(), and setDataset().
_dictionary
nidas::core::Project::MyDictionary nidas::core::Project::_dictionary private
Referenced by expandString(), fromDOMElement(), getDictionary(), and getTokenValue().
_disableAutoconfig
bool nidas::core::Project::_disableAutoconfig private
Referenced by disableAutoconfig(), and fromDOMElement().
_dsmById
std::map<dsm_sample_id_t,const DSMConfig*> nidas::core::Project::_dsmById mutable private
Referenced by findDSM().
_dsmCatalog
DSMCatalog* nidas::core::Project::_dsmCatalog private
Referenced by getDSMCatalog(), setDSMCatalog(), and ~Project().
_flightName
std::string nidas::core::Project::_flightName mutable private
Referenced by getFlightName(), and setFlightName().
_instance
Project * Project::_instance = 0 static private
Referenced by Project(), and ~Project().
_lookupLock
nidas::util::Mutex nidas::core::Project::_lookupLock mutable private
Referenced by addSite(), findDSM(), findSite(), and getFlightName().
_maxSiteNumber
int nidas::core::Project::_maxSiteNumber private
Referenced by addSite(), fromDOMElement(), and getMaxSiteNumber().
_minSiteNumber
int nidas::core::Project::_minSiteNumber private
Referenced by addSite(), and getMinSiteNumber().
_name
std::string nidas::core::Project::_name private
Referenced by getName(), and setName().
_parameters
std::list<Parameter*> nidas::core::Project::_parameters private
List of pointers to Parameters.
Referenced by addParameter(), getParameter(), and ~Project().
_sensorById
std::map<dsm_sample_id_t,DSMSensor*> nidas::core::Project::_sensorById mutable private
Referenced by findSensor().
_sensorCatalog
SensorCatalog* nidas::core::Project::_sensorCatalog private
Referenced by getSensorCatalog(), setSensorCatalog(), and ~Project().
_sensorMapLock
nidas::util::Mutex nidas::core::Project::_sensorMapLock mutable private
Referenced by findSensor(), and getUniqueSampleId().
_servers
std::list<DSMServer*> nidas::core::Project::_servers private
Referenced by addServer(), getServers(), and ~Project().
_serviceCatalog
ServiceCatalog* nidas::core::Project::_serviceCatalog private
Referenced by getServiceCatalog(), setServiceCatalog(), and ~Project().
_siteByName
std::map<std::string,Site*> nidas::core::Project::_siteByName private
Referenced by addSite(), and findSite().
_siteByStationNumber
std::map<int,Site*> nidas::core::Project::_siteByStationNumber private
Referenced by addSite(), and findSite().
_sites
std::list<Site*> nidas::core::Project::_sites private
Referenced by addSite(), getSites(), and ~Project().
_sysname
std::string nidas::core::Project::_sysname private
Referenced by getSystemName(), and setSystemName().
_usedIds
std::set<dsm_sample_id_t> nidas::core::Project::_usedIds private
Referenced by getUniqueSampleId().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/Project.h
nidas/core/Project.cc