nidas: nidas::dynld::isff::GOESOutput Class Reference
nidas::dynld::isff::GOESOutput Class Reference
A SampleOutput for packaging data for a GOES DCP Transmitter.
#include <GOESOutput.h>
Public Member Functions
GOESOutput (nidas::core::IOChannel *ioc=0, SampleConnectionRequester *rqstr=0)
Constructor.
~GOESOutput ()
Destructor.
void flush () throw ()
Implementation of SampleClient::flush().
void setIOChannel (nidas::core::IOChannel *val)
Set the IOChannel for this SampleOutput.
GOESOutput * clone (nidas::core::IOChannel *iochannel=0)
Clone invokes copy constructor.
SampleOutput * connected (nidas::core::IOChannel *ochan) throw ()
Implemention of IOChannelRequester::connected().
int getXmitInterval () const
The GOES transmit interval, in seconds.
int getXmitOffset () const
The GOES transmit offset, in seconds.
void addRequestedSampleTag (nidas::core::SampleTag *tag) throw (nidas::util::InvalidParameterException)
void addSourceSampleTag (const nidas::core::SampleTag *tag) throw (nidas::util::InvalidParameterException)
void close () throw ()
size_t write (const void *, size_t) throw (nidas::util::IOException)
Raw write not supported.
bool receive (const Sample *) throw ()
Send a data record to the RPC server.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
int run () throw (nidas::util::Exception)
The method which will run in its own thread.
void interrupt ()
Interrupt this run method.
bool isInterrupted () const
Has the run method been interrupted?
SampleOutput * getOriginal () const
Get pointer to SampleOutput that was cloned.
void setName (const std::string &val)
const std::string & getName () const
bool isRaw () const
std::list< const SampleTag * > getRequestedSampleTags () const
void addSourceSampleTags (const std::list< const SampleTag * > &tags)
std::list< const SampleTag * > getSourceSampleTags () const
void requestConnection (SampleConnectionRequester *)
Request a connection, but don't wait for it.
int getReconnectDelaySecs () const
Base class implementation.
void setReconnectDelaySecs (int val)
int getFd () const
dsm_time_t getNextFileTime () const
void createNextFile (dsm_time_t)
IOChannel * getIOChannel () const
void setHeaderSource (HeaderSource *val)
void setDSMConfig (const DSMConfig *val)
const DSMConfig * getDSMConfig () const
size_t getNumDiscardedSamples () const
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setLatency (float val)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
float getLatency () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
GOESOutput (GOESOutput &, nidas::core::IOChannel *)
Copy constructor, with a new IOChannel*.
void joinThread () throw ()
void cancelThread () throw ()
void killThread () throw ()
size_t incrementDiscardedSamples ()
SampleConnectionRequester * getSampleConnectionRequester ()
void disconnect ()
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Protected Attributes
std::string _name
Private Member Functions
GOESOutput (const GOESOutput &)
No normal copy.
GOESOutput & operator= (const GOESOutput &)
No assignment.
Private Attributes
GOESXmtr * _goesXmtr
std::map< dsm_sample_id_t, std::vector< std::vector< std::pair< int, int > > > > _sampleMap
std::vector< SampleT< float > * > _outputSamples
nidas::util::Mutex _sampleMutex
nidas::util::ThreadRunnable * _xmitThread
bool _interrupted
int _configid
int _stationNumber
long long _maxPeriodUsec
Not sure what the plan was for this.
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
std::list< const SampleTag * > _constRequestedTags
IOChannel * _iochan
SampleConnectionRequester * _connectionRequester
dsm_time_t _nextFileTime
HeaderSource * _headerSource
const DSMConfig * _dsm
size_t _nsamplesDiscarded
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
std::list< const SampleTag * > _sourceTags
SampleOutput * _original
Pointer to the SampleOutput that I was cloned from.
float _latency
int _reconnectDelaySecs
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
A SampleOutput for packaging data for a GOES DCP Transmitter.
Constructor & Destructor Documentation
GOESOutput() [1/3]
GOESOutput::GOESOutput (nidas::core::IOChannel * ioc = 0, SampleConnectionRequester * rqstr = 0)
Constructor.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), and LOG_ERR.
Referenced by clone().
~GOESOutput()
GOESOutput::~GOESOutput ()
Destructor.
References _xmitThread, cancelThread(), and joinThread().
GOESOutput() [2/3]
GOESOutput::GOESOutput (GOESOutput & x, nidas::core::IOChannel * ioc) protected
Copy constructor, with a new IOChannel*.
Used by clone().
References _goesXmtr, nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), nidas::util::Logger::log(), LOG_ERR, and nidas::core::SampleOutputBase::setName().
GOESOutput() [3/3]
nidas::dynld::isff::GOESOutput::GOESOutput (const GOESOutput &) private
No normal copy.
Member Function Documentation
addParameter()
void SampleOutputBase::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::SampleOutputBase::_constParameters, nidas::core::SampleOutputBase::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::SampleOutputBase::fromDOMElement().
addRequestedSampleTag()
void GOESOutput::addRequestedSampleTag (nidas::core::SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::addRequestedSampleTag(), GET_DSM_ID, GET_SPS_ID, nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::Parameter::getStringValue(), nidas::core::Parameter::getType(), nidas::core::Variable::setName(), and nidas::core::Parameter::STRING_PARAM.
addSourceSampleTag()
void GOESOutput::addSourceSampleTag (const nidas::core::SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::addSourceSampleTag(), nidas::core::Project::getInstance(), nidas::util::Logger::getInstance(), nidas::core::Parameter::getLength(), nidas::core::Variable::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::Project::getParameter(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), ILOG, nidas::util::Logger::log(), LOG_ERR, and nidas::core::VariableIterator::next().
addSourceSampleTags()
void SampleOutputBase::addSourceSampleTags (const std::list< const SampleTag * > & tags) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::addSourceSampleTag().
amInterrupted()
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::Looper::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::DSMServerStat::run(), run(), and nidas::util::Thread::test().
cancelThread()
void GOESOutput::cancelThread () throw () protected
References _xmitThread, nidas::util::Thread::cancel(), nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getName(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Referenced by close(), and ~GOESOutput().
clone()
GOESOutput* nidas::dynld::isff::GOESOutput::clone (nidas::core::IOChannel * iochannel = 0) inline virtual
Clone invokes copy constructor.
Implements nidas::core::SampleOutput.
References GOESOutput().
close()
void GOESOutput::close () throw () virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleOutputBase.
References cancelThread(), nidas::core::SampleOutputBase::close(), and joinThread().
connected()
SampleOutput * GOESOutput::connected (nidas::core::IOChannel * ochan) throw () virtual
Implemention of IOChannelRequester::connected().
Once we have the connection to the transmitter, initialize things before sending packets.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::connected(), nidas::core::floatNAN, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::Variable::getName(), nidas::core::SampleTag::getPeriod(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTag::getVariables(), nidas::core::VariableIterator::hasNext(), nidas::util::Logger::log(), LOG_WARNING, nidas::core::VariableIterator::next(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), nidas::util::UTime::toUsecs(), and USECS_PER_SEC.
createNextFile()
void SampleOutputBase::createNextFile (dsm_time_t tt) inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_headerSource, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::IOChannel::createFile(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::HeaderSource::sendDefaultHeader(), and nidas::core::HeaderSource::sendHeader().
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
disconnect()
void SampleOutputBase::disconnect () protected inherited
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
This is typically called in the receive() method of a SampleOutput if it gets an IOException when writing data. A common implementation of a connection requester is to delete this SampleOutput after the removing it from the sample stream. So the caller method should immediately return after calling disconnect().
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::close(), nidas::core::SampleConnectionRequester::disconnect(), nidas::core::SampleOutputBase::getName(), and ILOG.
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
flush()
void nidas::dynld::isff::GOESOutput::flush () throw () inline virtual
Implementation of SampleClient::flush().
Implements nidas::core::SampleClient.
fromDOMElement()
void GOESOutput::fromDOMElement (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::IOChannel::createIOChannel(), nidas::core::SampleTag::fromDOMElement(), nidas::core::DOMable::fromDOMElement(), and nidas::core::XDOMElement::getNodeName().
getDSMConfig()
const DSMConfig* nidas::core::SampleOutputBase::getDSMConfig () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
getFd()
int SampleOutputBase::getFd () const virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_iochan, and nidas::core::IOChannel::getFd().
getIOChannel()
IOChannel* nidas::core::SampleOutputBase::getIOChannel () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), nidas::dynld::AsciiOutput::connect(), nidas::core::SampleOutputBase::createNextFile(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), GOESOutput(), nidas::dynld::AsciiOutput::printHeader(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::raf::CVIOutput::requestConnection(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), setIOChannel(), and nidas::dynld::UDPSampleOutput::write().
getLatency()
float nidas::core::SampleOutputBase::getLatency () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_latency.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream().
getName()
const std::string& nidas::core::SampleOutputBase::getName () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_name.
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::addConnection(), nidas::dynld::AsciiOutput::AsciiOutput(), cancelThread(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::core::SampleOutputBase::close(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::disconnect(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::dynld::SampleOutputStream::flush(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), GOESOutput(), joinThread(), killThread(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::removeConnection(), run(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), setIOChannel(), nidas::dynld::SampleOutputStream::setLatency(), and write().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNextFileTime()
dsm_time_t nidas::core::SampleOutputBase::getNextFileTime () const inline inherited
References nidas::core::SampleOutputBase::_nextFileTime.
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
getNumDiscardedSamples()
size_t nidas::core::SampleOutputBase::getNumDiscardedSamples () const inline inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
getOriginal()
SampleOutput* nidas::core::SampleOutputBase::getOriginal () const inline virtual inherited
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_original.
getParameter()
const Parameter * SampleOutputBase::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::SampleOutputBase::_parameters.
getParameters()
const std::list<const Parameter*>& nidas::core::SampleOutputBase::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleOutputBase::_constParameters.
Referenced by nidas::dynld::UDPSampleOutput::fromDOMElement().
getReconnectDelaySecs()
int SampleOutputBase::getReconnectDelaySecs () const virtual inherited
Base class implementation.
If setReconnectDelaySecs() has been called on this SampleOutput, then that value will be returned. Otherwise this will return the value of the IOChannel.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_reconnectDelaySecs, and nidas::core::IOChannel::getReconnectDelaySecs().
getRequestedSampleTags()
std::list< const SampleTag * > SampleOutputBase::getRequestedSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), run(), and nidas::core::SampleOutputBase::SampleOutputBase().
getSampleConnectionRequester()
SampleConnectionRequester* nidas::core::SampleOutputBase::getSampleConnectionRequester () inline protected inherited
References nidas::core::SampleOutputBase::_connectionRequester.
getSourceSampleTags()
list< const SampleTag * > SampleOutputBase::getSourceSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase().
getXmitInterval()
int nidas::dynld::isff::GOESOutput::getXmitInterval () const inline
The GOES transmit interval, in seconds.
References _goesXmtr, and nidas::dynld::isff::GOESXmtr::getXmitInterval().
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), and run().
getXmitOffset()
int nidas::dynld::isff::GOESOutput::getXmitOffset () const inline
The GOES transmit offset, in seconds.
References _goesXmtr, and nidas::dynld::isff::GOESXmtr::getXmitOffset().
Referenced by run().
incrementDiscardedSamples()
size_t nidas::core::SampleOutputBase::incrementDiscardedSamples () inline protected inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
interrupt()
void GOESOutput::interrupt () virtual
Interrupt this run method.
This sets a flag which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted.
Implements nidas::util::Runnable.
References _interrupted.
isInterrupted()
bool nidas::dynld::isff::GOESOutput::isInterrupted () const inline virtual
Has the run method been interrupted?
Implements nidas::util::Runnable.
References _interrupted.
isRaw()
bool nidas::core::SampleOutputBase::isRaw () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::RawSampleOutputStream, and nidas::dynld::psql::PSQLSampleOutput.
joinThread()
void GOESOutput::joinThread () throw () protected
References _xmitThread, nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getName(), nidas::util::ThreadRunnable::interrupt(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Referenced by close(), and ~GOESOutput().
killThread()
void GOESOutput::killThread () throw () protected
References _xmitThread, nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getName(), nidas::util::Thread::isRunning(), nidas::util::Thread::kill(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
operator=()
GOESOutput& nidas::dynld::isff::GOESOutput::operator= (const GOESOutput &) private
No assignment.
receive()
bool GOESOutput::receive (const Sample * samp) throw () virtual
Send a data record to the RPC server.
Implements nidas::core::SampleClient.
References nidas::util::UTime::format(), nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::util::Logger::getInstance(), nidas::core::Sample::getTimeTag(), nidas::util::Logger::log(), LOG_ERR, USECS_PER_MSEC, USECS_PER_SEC, and WLOG.
requestConnection()
void SampleOutputBase::requestConnection (SampleConnectionRequester * requester) virtual inherited
Request a connection, but don't wait for it.
Requester will be notified via SampleConnectionRequester interface when the connection has been made. It is not necessary to call this method if a SampleOutput is constructed with a connected IOChannel.
Exceptions
nidas::util::IOException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, and nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::_iochan, and nidas::core::IOChannel::requestConnection().
Referenced by nidas::dynld::AsciiOutput::requestConnection(), and nidas::dynld::raf::CVIOutput::requestConnection().
run()
int GOESOutput::run () throw (nidas::util::Exception) virtual
The method which will run in its own thread.
This method must be supplied by the Runnable or Thread subclass.
Exceptions
Exception
Implements nidas::util::Runnable.
References _configid, _goesXmtr, _interrupted, _outputSamples, _sampleMutex, nidas::util::Runnable::amInterrupted(), nidas::core::floatNAN, nidas::util::UTime::format(), nidas::core::SampleT< DataT >::freeReference(), nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getName(), nidas::core::SampleTag::getPeriod(), nidas::core::SampleOutputBase::getRequestedSampleTags(), nidas::core::Sample::getTimeTag(), nidas::core::SampleTag::getVariables(), getXmitInterval(), getXmitOffset(), nidas::dynld::isff::GOESXmtr::init(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, MSECS_PER_SEC, periodMsec, PLOG, nidas::dynld::isff::GOESXmtr::printStatus(), nidas::dynld::isff::GOESXmtr::reset(), nidas::util::Thread::RUN_OK, nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), nidas::util::sleepUntil(), nidas::util::UTime::toUsecs(), nidas::dynld::isff::GOESXmtr::transmitData(), nidas::util::Mutex::unlock(), USECS_PER_MSEC, USECS_PER_SEC, nidas::util::Exception::what(), and WLOG.
setDSMConfig()
void nidas::core::SampleOutputBase::setDSMConfig (const DSMConfig * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
setHeaderSource()
void nidas::core::SampleOutputBase::setHeaderSource (HeaderSource * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_headerSource.
Referenced by ARLIngest::run(), NidsMerge::run(), and SensorExtract::run().
setIOChannel()
void GOESOutput::setIOChannel (nidas::core::IOChannel * val) virtual
Set the IOChannel for this SampleOutput.
This IOChannel is not yet connected. The IOChannel must be connected before the SampleOutput is used for I/O, using the requestConnection() method, or by IOChannel::connect() followed by SampleOutput::connected(IOChannel*).
Reimplemented from nidas::core::SampleOutputBase.
References _goesXmtr, nidas::util::Logger::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SampleOutputBase::setIOChannel(), and nidas::core::SampleOutputBase::setName().
setLatency()
void nidas::core::SampleOutputBase::setLatency (float val) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the IOStream for a 1/10 sec, then send the data to the physical device.
Parameters
val Latency, in seconds.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::SampleOutputStream.
References nidas::core::SampleOutputBase::_latency.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleOutputStream::setLatency().
setName()
void nidas::core::SampleOutputBase::setName (const std::string & val) inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_name.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), nidas::core::SampleOutputBase::connected(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::fromDOMElement(), GOESOutput(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), and setIOChannel().
setReconnectDelaySecs()
void SampleOutputBase::setReconnectDelaySecs (int val) virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_reconnectDelaySecs.
Referenced by nidas::dynld::raf::SyncServer::init().
testCancel()
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write()
size_t nidas::dynld::isff::GOESOutput::write (const void * , size_t) throw (nidas::util::IOException) inline virtual
Raw write not supported.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::getName().
Member Data Documentation
_configid
int nidas::dynld::isff::GOESOutput::_configid private
Referenced by run().
_connectionRequester
SampleConnectionRequester* nidas::core::SampleOutputBase::_connectionRequester private inherited
Referenced by nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::disconnect(), nidas::core::SampleOutputBase::getSampleConnectionRequester(), and nidas::core::SampleOutputBase::requestConnection().
_constParameters
std::list<const Parameter*> nidas::core::SampleOutputBase::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::SampleOutputBase::addParameter(), and nidas::core::SampleOutputBase::getParameters().
_constRequestedTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_constRequestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::getRequestedSampleTags().
_dsm
const DSMConfig* nidas::core::SampleOutputBase::_dsm private inherited
Referenced by nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::SampleOutputBase::setDSMConfig().
_goesXmtr
GOESXmtr* nidas::dynld::isff::GOESOutput::_goesXmtr private
Referenced by getXmitInterval(), getXmitOffset(), GOESOutput(), run(), and setIOChannel().
_headerSource
HeaderSource* nidas::core::SampleOutputBase::_headerSource private inherited
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::setHeaderSource().
_interrupted
bool nidas::dynld::isff::GOESOutput::_interrupted private
Referenced by interrupt(), isInterrupted(), and run().
_iochan
IOChannel* nidas::core::SampleOutputBase::_iochan private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::getFd(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getReconnectDelaySecs(), nidas::core::SampleOutputBase::requestConnection(), nidas::core::SampleOutputBase::SampleOutputBase(), nidas::core::SampleOutputBase::setIOChannel(), nidas::core::SampleOutputBase::write(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_latency
float nidas::core::SampleOutputBase::_latency private inherited
Referenced by nidas::core::SampleOutputBase::getLatency(), and nidas::core::SampleOutputBase::setLatency().
_maxPeriodUsec
long long nidas::dynld::isff::GOESOutput::_maxPeriodUsec private
Not sure what the plan was for this.
Not currently used.
_name
std::string nidas::core::SampleOutputBase::_name protected inherited
Referenced by nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
_nextFileTime
dsm_time_t nidas::core::SampleOutputBase::_nextFileTime private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::getNextFileTime().
_nsamplesDiscarded
size_t nidas::core::SampleOutputBase::_nsamplesDiscarded private inherited
Referenced by nidas::core::SampleOutputBase::getNumDiscardedSamples(), and nidas::core::SampleOutputBase::incrementDiscardedSamples().
_original
SampleOutput* nidas::core::SampleOutputBase::_original private inherited
Pointer to the SampleOutput that I was cloned from.
Referenced by nidas::core::SampleOutputBase::getOriginal().
_outputSamples
std::vector<SampleT<float>*> nidas::dynld::isff::GOESOutput::_outputSamples private
Referenced by run().
_parameters
std::map<std::string,Parameter*> nidas::core::SampleOutputBase::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleOutputBase::getParameter(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_reconnectDelaySecs
int nidas::core::SampleOutputBase::_reconnectDelaySecs private inherited
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs(), and nidas::core::SampleOutputBase::setReconnectDelaySecs().
_requestedTags
std::list<SampleTag*> nidas::core::SampleOutputBase::_requestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_sampleMap
std::map<dsm_sample_id_t,std::vector<std::vector<std::pair<int,int> > > > nidas::dynld::isff::GOESOutput::_sampleMap private
_sampleMutex
nidas::util::Mutex nidas::dynld::isff::GOESOutput::_sampleMutex private
Referenced by run().
_sourceTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_sourceTags private inherited
Referenced by nidas::core::SampleOutputBase::addSourceSampleTag(), and nidas::core::SampleOutputBase::getSourceSampleTags().
_stationNumber
int nidas::dynld::isff::GOESOutput::_stationNumber private
_tagsMutex
nidas::util::Mutex nidas::core::SampleOutputBase::_tagsMutex mutable private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), nidas::core::SampleOutputBase::addSourceSampleTag(), nidas::core::SampleOutputBase::getRequestedSampleTags(), and nidas::core::SampleOutputBase::getSourceSampleTags().
_xmitThread
nidas::util::ThreadRunnable* nidas::dynld::isff::GOESOutput::_xmitThread private
Referenced by cancelThread(), joinThread(), killThread(), and ~GOESOutput().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/isff/GOESOutput.h
nidas/dynld/isff/GOESOutput.cc