nidas: nidas::core::DSMEngine Class Reference
nidas::core::DSMEngine Class Reference
Application for running the NIDAS data acquistion process.
#include <DSMEngine.h>
Public Types
enum command {
DSM_STOP , DSM_RUN , DSM_QUIT , DSM_RESTART ,
DSM_REBOOT , DSM_SHUTDOWN
}
Public Member Functions
DSMEngine ()
~DSMEngine ()
Nuke it.
void initLogger ()
Initialize the Logger.
int initProcess ()
Initialize various process parameters, uid, etc.
int run () throw ()
main loop
int parseRunstring (int argc, char **argv)
Parse the runstring parameters.
void usage ()
Print runstring usage to stderr.
void start ()
Starts the main loop (for the XMLRPC call).
void stop ()
Stops the main loop (for the XMLRPC call).
void restart ()
Restarts the main loop (for the XMLRPC call).
void quit ()
Quit the main loop.
void shutdown ()
Quits the main loop, and spawns a "halt" shell command.
void reboot ()
Quits the main loop, and spawns a "reboot" shell command.
const DSMConfig * getDSMConfig () const
const SensorHandler * getSensorHandler () const
void registerSensorWithXmlRpc (const std::string &devname, DSMSensor *)
Sensors register with the DSMEngineIntf XmlRpcThread if they have a executeXmlRpc() method which can be invoked with a "SensorAction" XmlRpc request.
bool quitCommand (enum command command)
enum command getCommand () const
Static Public Member Functions
static int main (int argc, char **argv) throw ()
Entry point to run a DSMEngine process from a command line.
static DSMEngine * getInstance ()
Get a pointer to the singleton instance of DSMEngine created by main().
Private Types
enum run_states { DSM_RUNNING , DSM_ERROR , DSM_STOPPED }
Private Member Functions
void setupSignals ()
Create a signal mask, and block those masked signals.
void waitForSignal (int secs)
Unblock and wait for signals of interest.
void initialize (xercesc::DOMDocument *projectDoc)
Initialize the DSMEngine based on the parameters in the DOMDocument.
void startXmlRpcThread ()
void killXmlRpcThread ()
void openSensors ()
void connectOutputs ()
void connectProcessors ()
void disconnectProcessors () throw ()
void closeOutputs () throw ()
void interrupt ()
void deleteDataThreads () throw ()
void joinDataThreads () throw ()
void connect (SampleOutput *) throw ()
Implementation of SampleConnectionRequester connect methods.
void disconnect (SampleOutput *) throw ()
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
void connect (SampleInput *) throw ()
DSMEngine does not receive SampleInputs, so this will die with an assert.
void disconnect (SampleInput *) throw ()
DSMEngine does not receive SampleInputs, so these will die with an assert.
DSMEngine (const DSMEngine &)
No copy.
DSMEngine & operator= (const DSMEngine &)
No assignment.
Private Attributes
bool _externalControl
bool _disableAutoconfig
enum nidas::core::DSMEngine::run_states _runState
enum command _command
bool _syslogit
Whether to log messages on syslog (true) or stderr (false).
std::string _configFile
Name of XML configuration file.
nidas::util::Inet4SocketAddress _configSockAddr
Address to use when fishing for the XML configuration.
Project * _project
DSMConfig * _dsmConfig
SensorHandler * _selector
SamplePipeline * _pipeline
DSMEngineStat * _statusThread
A thread that generates streaming XML time and status.
DSMEngineIntf * _xmlrpcThread
This thread provides XML-based Remote Procedure calls.
std::set< SampleOutput * > _outputSet
Connected SampleOutputs.
nidas::util::Mutex _outputMutex
int _logLevel
sigset_t _signalMask
pthread_t _myThreadId
NidasApp _app
NidasAppArg ExternalControl
NidasAppArg DisableAutoConfig
Static Private Attributes
static DSMEngine * _instance = 0
Detailed Description
Application for running the NIDAS data acquistion process.
Member Enumeration Documentation
command
enum nidas::core::DSMEngine::command
Enumerator
DSM_STOP
DSM_RUN
DSM_QUIT
DSM_RESTART
DSM_REBOOT
DSM_SHUTDOWN
run_states
enum nidas::core::DSMEngine::run_states private
Enumerator
DSM_RUNNING
DSM_ERROR
DSM_STOPPED
Constructor & Destructor Documentation
DSMEngine() [1/2]
DSMEngine::DSMEngine ()
References _configSockAddr, nidas::util::Inet4Address::getByName(), NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, setupSignals(), and nidas::util::Exception::what().
~DSMEngine()
DSMEngine::~DSMEngine ()
Nuke it.
References _project, _statusThread, _xmlrpcThread, nidas::core::SamplePools::deleteInstance(), and nidas::core::SampleOutputRequestThread::destroyInstance().
DSMEngine() [2/2]
nidas::core::DSMEngine::DSMEngine (const DSMEngine &) private
No copy.
Member Function Documentation
closeOutputs()
void DSMEngine::closeOutputs () throw () private
References _dsmConfig, _outputMutex, _outputSet, _pipeline, nidas::core::SampleOutputRequestThread::clear(), nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::core::DSMConfig::getOutputs(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::SamplePipeline::getRawSampleSource(), nidas::core::SampleOutput::isRaw(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SampleSource::removeSampleClient(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
Referenced by run().
connect() [1/2]
void nidas::core::DSMEngine::connect (SampleInput *) throw () inline private
DSMEngine does not receive SampleInputs, so this will die with an assert.
connect() [2/2]
void DSMEngine::connect (SampleOutput * output) throw () private virtual
Implementation of SampleConnectionRequester connect methods.
This is how DSMEngine is notified of remote connections.
Implements nidas::core::SampleConnectionRequester.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), and LOG_INFO.
connectOutputs()
void DSMEngine::connectOutputs () private
Exceptions
nidas::util::IOException
References _dsmConfig, _pipeline, nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), DLOG, nidas::core::SampleOutputRequestThread::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::DSMConfig::getOutputs(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::SamplePipeline::getRawSampleSource(), nidas::core::SampleSource::getSampleTags(), and nidas::core::SampleOutput::isRaw().
Referenced by run().
connectProcessors()
void DSMEngine::connectProcessors () private
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
References _dsmConfig, _pipeline, nidas::core::SampleIOProcessor::connectSource(), nidas::core::DSMConfig::getProcessorIterator(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::ProcessorIterator::hasNext(), nidas::core::SensorIterator::hasNext(), nidas::core::DSMSensor::init(), nidas::core::ProcessorIterator::next(), and nidas::core::SensorIterator::next().
Referenced by run().
deleteDataThreads()
void DSMEngine::deleteDataThreads () throw () private
References _pipeline, _selector, _statusThread, nidas::core::DerivedDataReader::deleteInstance(), and nidas::core::DerivedDataReader::getInstance().
Referenced by run().
disconnect() [1/2]
void nidas::core::DSMEngine::disconnect (SampleInput *) throw () inline private
DSMEngine does not receive SampleInputs, so these will die with an assert.
disconnect() [2/2]
void DSMEngine::disconnect (SampleOutput * output) throw () private virtual
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
disconnectProcessors()
void DSMEngine::disconnectProcessors () throw () private
References _dsmConfig, _pipeline, nidas::core::SampleIOProcessor::disconnectSource(), nidas::core::SampleSource::flush(), nidas::core::DSMConfig::getProcessorIterator(), nidas::core::ProcessorIterator::hasNext(), and nidas::core::ProcessorIterator::next().
Referenced by run().
getCommand()
enum command nidas::core::DSMEngine::getCommand () const inline
References DSM_QUIT, DSM_REBOOT, and DSM_SHUTDOWN.
Referenced by main().
getDSMConfig()
const DSMConfig* nidas::core::DSMEngine::getDSMConfig () const inline
References _dsmConfig.
Referenced by nidas::core::DSMEngineStat::run().
getInstance()
static DSMEngine* nidas::core::DSMEngine::getInstance () inline static
Get a pointer to the singleton instance of DSMEngine created by main().
References _instance.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::raf::PSI9116_Sensor::open(), and nidas::core::DSMEngineStat::run().
getSensorHandler()
const SensorHandler* nidas::core::DSMEngine::getSensorHandler () const inline
References _selector.
Referenced by nidas::core::DSMEngineStat::run().
initialize()
void DSMEngine::initialize (xercesc::DOMDocument * projectDoc) private
Initialize the DSMEngine based on the parameters in the DOMDocument.
This method initializes the Project object, _project from the DOM, and sets the value of _dsmConfig.
Exceptions
nidas::util::InvalidParameterException
References _app, _configFile, _disableAutoconfig, _dsmConfig, _project, nidas::core::Project::disableAutoconfig(), nidas::core::Project::findDSMFromHostname(), nidas::core::Project::fromDOMElement(), nidas::core::NidasApp::getHostName(), and nidas::core::Project::setConfigName().
Referenced by run().
initLogger()
void DSMEngine::initLogger ()
Initialize the Logger.
References _app, and nidas::core::NidasApp::setupDaemon().
Referenced by main().
initProcess()
int DSMEngine::initProcess ()
Initialize various process parameters, uid, etc.
References _app, nidas::core::NidasApp::checkPidFile(), nidas::core::NidasApp::lockMemory(), and nidas::core::NidasApp::setupProcess().
Referenced by main().
interrupt()
void DSMEngine::interrupt () private
References _pipeline, _selector, _statusThread, nidas::core::SamplePipeline::flush(), nidas::core::DerivedDataReader::getInstance(), nidas::core::DerivedDataReader::interrupt(), nidas::core::SamplePipeline::interrupt(), nidas::core::SensorHandler::interrupt(), and nidas::util::Thread::interrupt().
Referenced by run().
joinDataThreads()
void DSMEngine::joinDataThreads () throw () private
References _pipeline, _selector, _statusThread, nidas::util::Thread::cancel(), DLOG, nidas::core::DerivedDataReader::getInstance(), nidas::core::SamplePipeline::join(), nidas::core::SensorHandler::join(), nidas::util::Thread::join(), PLOG, USECS_PER_SEC, nidas::util::Exception::what(), and WLOG.
Referenced by run().
killXmlRpcThread()
void DSMEngine::killXmlRpcThread () private
Exceptions
References _xmlrpcThread, DLOG, nidas::core::XmlRpcThread::interrupt(), nidas::util::Thread::join(), nidas::util::Exception::what(), and WLOG.
Referenced by main().
main()
int DSMEngine::main (int argc, char ** argv) throw () static
Entry point to run a DSMEngine process from a command line.
main creates an instance of DSMEngine, passes it the command line arguments and calls the run method.
References nidas::core::DSMSensor::deleteLooper(), getCommand(), nidas::core::SamplePoolInterface::getNLargeSamplesIn(), nidas::core::SamplePoolInterface::getNMediumSamplesIn(), nidas::core::SamplePoolInterface::getNSamplesOut(), nidas::core::SamplePoolInterface::getNSmallSamplesIn(), ILOG, initLogger(), initProcess(), killXmlRpcThread(), NSECS_PER_SEC, parseRunstring(), PLOG, run(), nidas::util::Process::spawn(), startXmlRpcThread(), nidas::core::XMLImplementation::terminate(), and nidas::util::Exception::what().
Referenced by main().
openSensors()
void DSMEngine::openSensors () private
Exceptions
nidas::util::IOException
References _dsmConfig, _pipeline, _selector, nidas::core::SamplePipeline::connect(), nidas::util::Logger::getInstance(), nidas::core::DSMConfig::getProcHeapMax(), nidas::core::DSMConfig::getProcLateSampleCacheSize(), nidas::core::DSMConfig::getProcSorterLength(), nidas::core::DSMConfig::getRawHeapMax(), nidas::core::DSMConfig::getRawLateSampleCacheSize(), nidas::core::DSMConfig::getRawSorterLength(), nidas::core::DSMConfig::getRemoteSerialSocketPort(), nidas::core::DSMConfig::getSensors(), nidas::util::Logger::log(), LOG_INFO, nidas::core::DSMConfig::openSensors(), nidas::core::SamplePipeline::setKeepStats(), nidas::core::SamplePipeline::setProcHeapMax(), nidas::core::SamplePipeline::setProcLateSampleCacheSize(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRawHeapMax(), nidas::core::SamplePipeline::setRawLateSampleCacheSize(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), nidas::util::Thread::setRealTimeFIFOPriority(), and nidas::util::Thread::start().
Referenced by run().
operator=()
DSMEngine& nidas::core::DSMEngine::operator= (const DSMEngine &) private
No assignment.
parseRunstring()
int DSMEngine::parseRunstring (int argc, char ** argv)
Parse the runstring parameters.
If the runstring parameters are not OK, then DSMEngine::usage() is called to print a message to stderr, and this method then returns a error value of 1.
Returns
0: OK, 1: failure.
References _app, _configFile, _configSockAddr, _externalControl, nidas::core::NidasAppArg::asBool(), nidas::core::NidasApp::DebugDaemon, DisableAutoConfig, nidas::core::NidasApp::enableArguments(), ExternalControl, nidas::util::Inet4Address::getByName(), nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::Hostname, nidas::core::NidasApp::loggingArgs(), NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, nidas::core::NidasApp::parseArgs(), nidas::core::NidasApp::PidFile, port, usage(), nidas::core::NidasApp::Username, nidas::core::NidasApp::Version, and nidas::util::Exception::what().
Referenced by main().
quit()
void DSMEngine::quit ()
Quit the main loop.
References _myThreadId.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
quitCommand()
bool nidas::core::DSMEngine::quitCommand (enum command command) inline
Referenced by run().
reboot()
void DSMEngine::reboot ()
Quits the main loop, and spawns a "reboot" shell command.
References _command, _myThreadId, and DSM_REBOOT.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
registerSensorWithXmlRpc()
void DSMEngine::registerSensorWithXmlRpc (const std::string & devname, DSMSensor * sensor)
Sensors register with the DSMEngineIntf XmlRpcThread if they have a executeXmlRpc() method which can be invoked with a "SensorAction" XmlRpc request.
Parameters
devname string matching the "device" XmlRpc parameter, typically the device name.
References _xmlrpcThread, and nidas::core::DSMEngineIntf::registerSensor().
Referenced by nidas::dynld::raf::DSMAnalogSensor::open(), and nidas::dynld::raf::PSI9116_Sensor::open().
restart()
void DSMEngine::restart ()
Restarts the main loop (for the XMLRPC call).
References _myThreadId.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
run()
int DSMEngine::run () throw ()
main loop
References _command, _configFile, _configSockAddr, _dsmConfig, _project, _runState, _signalMask, _statusThread, closeOutputs(), connectOutputs(), connectProcessors(), nidas::core::DerivedDataReader::createInstance(), deleteDataThreads(), disconnectProcessors(), DSM_ERROR, DSM_RESTART, DSM_RUN, DSM_RUNNING, DSM_STOP, nidas::util::Process::expandEnvVars(), nidas::core::DSMConfig::getDerivedDataSocketAddr(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::SocketAddress::getPort(), nidas::core::DSMConfig::getStatusSocketAddr(), initialize(), interrupt(), joinDataThreads(), openSensors(), nidas::core::parseXMLConfigFile(), PLOG, quitCommand(), nidas::core::requestXMLConfig(), nidas::util::Thread::start(), nidas::core::XMLImplementation::terminate(), waitForSignal(), and nidas::util::Exception::what().
Referenced by main().
setupSignals()
void DSMEngine::setupSignals () private
Create a signal mask, and block those masked signals.
DSMEngine uses sigwait, and does not register asynchronous signal handlers.
References _signalMask.
Referenced by DSMEngine().
shutdown()
void DSMEngine::shutdown ()
Quits the main loop, and spawns a "halt" shell command.
References _command, _myThreadId, and DSM_SHUTDOWN.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
start()
void DSMEngine::start ()
Starts the main loop (for the XMLRPC call).
References _command, _myThreadId, and DSM_RUN.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
startXmlRpcThread()
void DSMEngine::startXmlRpcThread () private
Exceptions
nidas::util::Exception
References _externalControl, _xmlrpcThread, and nidas::util::Thread::start().
Referenced by main().
stop()
void DSMEngine::stop ()
Stops the main loop (for the XMLRPC call).
References _command, _myThreadId, and DSM_STOP.
Referenced by nidas::core::DSMEngineIntf::DSMAction::execute().
usage()
void DSMEngine::usage ()
Print runstring usage to stderr.
References _app, nidas::core::NidasApp::getName(), NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
waitForSignal()
void DSMEngine::waitForSignal (int secs) private
Unblock and wait for signals of interest.
References _command, _signalMask, DSM_QUIT, DSM_RESTART, nidas::util::Exception::errnoToString(), ILOG, PLOG, timeoutSecs, and WLOG.
Referenced by run().
Member Data Documentation
_app
NidasApp nidas::core::DSMEngine::_app private
Referenced by initialize(), initLogger(), initProcess(), parseRunstring(), and usage().
_command
enum command nidas::core::DSMEngine::_command private
Referenced by reboot(), run(), shutdown(), start(), stop(), and waitForSignal().
_configFile
std::string nidas::core::DSMEngine::_configFile private
Name of XML configuration file.
If empty, multicast for config.
Referenced by initialize(), parseRunstring(), and run().
_configSockAddr
nidas::util::Inet4SocketAddress nidas::core::DSMEngine::_configSockAddr private
Address to use when fishing for the XML configuration.
Referenced by DSMEngine(), parseRunstring(), and run().
_disableAutoconfig
bool nidas::core::DSMEngine::_disableAutoconfig private
Referenced by initialize().
_dsmConfig
DSMConfig* nidas::core::DSMEngine::_dsmConfig private
Referenced by closeOutputs(), connectOutputs(), connectProcessors(), disconnectProcessors(), getDSMConfig(), initialize(), openSensors(), and run().
_externalControl
bool nidas::core::DSMEngine::_externalControl private
Referenced by parseRunstring(), and startXmlRpcThread().
_instance
DSMEngine * DSMEngine::_instance = 0 static private
Referenced by getInstance().
_logLevel
int nidas::core::DSMEngine::_logLevel private
_myThreadId
pthread_t nidas::core::DSMEngine::_myThreadId private
Referenced by quit(), reboot(), restart(), shutdown(), start(), and stop().
_outputMutex
nidas::util::Mutex nidas::core::DSMEngine::_outputMutex private
Referenced by closeOutputs().
_outputSet
std::set<SampleOutput*> nidas::core::DSMEngine::_outputSet private
Connected SampleOutputs.
Referenced by closeOutputs().
_pipeline
SamplePipeline* nidas::core::DSMEngine::_pipeline private
Referenced by closeOutputs(), connectOutputs(), connectProcessors(), deleteDataThreads(), disconnectProcessors(), interrupt(), joinDataThreads(), and openSensors().
_project
Project* nidas::core::DSMEngine::_project private
Referenced by initialize(), run(), and ~DSMEngine().
_runState
enum nidas::core::DSMEngine::run_states nidas::core::DSMEngine::_runState private
Referenced by run().
_selector
SensorHandler* nidas::core::DSMEngine::_selector private
Referenced by deleteDataThreads(), getSensorHandler(), interrupt(), joinDataThreads(), and openSensors().
_signalMask
sigset_t nidas::core::DSMEngine::_signalMask private
Referenced by run(), setupSignals(), and waitForSignal().
_statusThread
DSMEngineStat* nidas::core::DSMEngine::_statusThread private
A thread that generates streaming XML time and status.
Referenced by deleteDataThreads(), interrupt(), joinDataThreads(), run(), and ~DSMEngine().
_syslogit
bool nidas::core::DSMEngine::_syslogit private
Whether to log messages on syslog (true) or stderr (false).
Set to false from -d runstring option, otherwise true.
_xmlrpcThread
DSMEngineIntf* nidas::core::DSMEngine::_xmlrpcThread private
This thread provides XML-based Remote Procedure calls.
Referenced by killXmlRpcThread(), registerSensorWithXmlRpc(), startXmlRpcThread(), and ~DSMEngine().
DisableAutoConfig
NidasAppArg nidas::core::DSMEngine::DisableAutoConfig private
Referenced by parseRunstring().
ExternalControl
NidasAppArg nidas::core::DSMEngine::ExternalControl private
Referenced by parseRunstring().
The documentation for this class was generated from the following files:
nidas/core/DSMEngine.h
nidas/core/DSMEngine.cc