nidas: nidas::dynld::isff::SimGOESXmtr Class Reference
nidas::dynld::isff::SimGOESXmtr Class Reference abstract
An IOChannel implementation to simulate a GOES transmitter.
#include <SimGOESXmtr.h>
Public Member Functions
SimGOESXmtr ()
Constructor.
SimGOESXmtr (const SimGOESXmtr &)
Copy constructor.
~SimGOESXmtr ()
Destructor.
SimGOESXmtr * clone () const
Clone invokes default copy constructor.
void setRFBaud (long val) throw (nidas::util::InvalidParameterException)
Set the RF baud rate.
int getRFBaud () const
void open () throw (nidas::util::IOException)
size_t read (void *, size_t) throw (nidas::util::IOException)
Do the actual hardware read.
size_t write (const void *, size_t) throw (nidas::util::IOException)
Do the actual hardware write.
size_t write (const struct iovec *, int) throw (nidas::util::IOException)
Do the actual hardware write.
void transmitData (const nidas::util::UTime &at, int configid, const Sample *) throw (nidas::util::IOException)
Queue a sample for writing to a GOES transmitter.
unsigned long checkId () throw (nidas::util::IOException)
int checkClock () throw (nidas::util::IOException)
Check transmitter clock, and correct it if necessary.
void printStatus () throw ()
Request that transmitter status be printed to an output stream.
void reset () throw (nidas::util::IOException)
void init () throw (nidas::util::IOException)
Initialize tranmitter.
const std::string & getName () const
void setName (const std::string &val)
void setId (unsigned long val)
unsigned long getId () const
void setChannel (int val)
int getChannel () const
void setXmitInterval (long val)
Set the transmission interval.
int getXmitInterval () const
void setXmitOffset (long val)
Set the transmission offset.
int getXmitOffset () const
void requestConnection (IOChannelRequester *rqstr) throw (nidas::util::IOException)
Request a connection.
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
void setNonBlocking (bool val __attribute__((unused))) throw (nidas::util::IOException)
virtual void setNonBlocking (bool val)=0
bool isNonBlocking () const throw (nidas::util::IOException)
void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
void close () throw (nidas::util::IOException)
int getFd () const
void setStatusFile (const std::string &val)
const std::string & getStatusFile () const
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Attributes
nidas::util::SerialPort _port
Private Attributes
nidas::util::UTime _transmitQueueTime
nidas::util::UTime _transmitAtTime
nidas::util::UTime _transmitSampleTime
int _rfBaud
unsigned long _id
int _channel
int _xmitInterval
int _xmitOffset
std::string _statusFile
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
An IOChannel implementation to simulate a GOES transmitter.
Constructor & Destructor Documentation
SimGOESXmtr() [1/2]
SimGOESXmtr::SimGOESXmtr ()
Constructor.
SimGOESXmtr() [2/2]
SimGOESXmtr::SimGOESXmtr (const SimGOESXmtr & x)
Copy constructor.
~SimGOESXmtr()
SimGOESXmtr::~SimGOESXmtr ()
Destructor.
Member Function Documentation
checkClock()
int SimGOESXmtr::checkClock () throw (nidas::util::IOException) virtual
Check transmitter clock, and correct it if necessary.
Returns
transmitter clock minus system clock, in milliseconds.
Implements nidas::dynld::isff::GOESXmtr.
checkId()
unsigned long SimGOESXmtr::checkId () throw (nidas::util::IOException) virtual
Implements nidas::dynld::isff::GOESXmtr.
clone()
SimGOESXmtr* nidas::dynld::isff::SimGOESXmtr::clone () const inline virtual
Clone invokes default copy constructor.
Implements nidas::core::IOChannel.
close()
void nidas::dynld::isff::GOESXmtr::close () throw (nidas::util::IOException) inline virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
Reimplemented in nidas::dynld::isff::SE_GOESXmtr.
connect()
IOChannel * GOESXmtr::connect () throw (nidas::util::IOException) virtual inherited
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Exceptions
nidas::util::IOException
nidas::util::UnknownHostException
Implements nidas::core::IOChannel.
References nidas::dynld::isff::GOESXmtr::open().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
void nidas::dynld::isff::GOESXmtr::flush () throw (nidas::util::IOException) inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::IOChannel.
Reimplemented in nidas::dynld::isff::SE_GOESXmtr.
fromDOMElement()
void GOESXmtr::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Termios::EVEN, nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), nidas::util::Termios::NONE, nidas::util::Termios::ODD, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setParity(), and nidas::util::Termios::setStopBits().
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getChannel()
int nidas::dynld::isff::GOESXmtr::getChannel () const inline inherited
Referenced by printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::dynld::isff::GOESXmtr::getFd () const inline virtual inherited
Implements nidas::core::IOChannel.
getId()
unsigned long nidas::dynld::isff::GOESXmtr::getId () const inline inherited
Referenced by nidas::dynld::isff::SE_GOESXmtr::checkId(), and nidas::dynld::isff::SE_GOESXmtr::setXmtrId().
getName()
const std::string& nidas::dynld::isff::GOESXmtr::getName () const inline virtual inherited
Implements nidas::core::IOChannel.
Referenced by nidas::dynld::isff::SE_GOESXmtr::checkClock(), nidas::dynld::isff::SE_GOESXmtr::checkId(), nidas::dynld::isff::SE_GOESXmtr::checkStatus(), nidas::dynld::isff::SE_GOESXmtr::decodeClock(), nidas::dynld::isff::SE_GOESXmtr::detectModel(), nidas::dynld::isff::SE_GOESXmtr::doSelfTest(), nidas::dynld::isff::SE_GOESXmtr::getSelfTestResults(), nidas::dynld::isff::SE_GOESXmtr::recv(), nidas::dynld::isff::SE_GOESXmtr::reset(), nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120(), nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getRFBaud()
int nidas::dynld::isff::SimGOESXmtr::getRFBaud () const inline virtual
Implements nidas::dynld::isff::GOESXmtr.
Referenced by printStatus().
getStatusFile()
const std::string& nidas::dynld::isff::GOESXmtr::getStatusFile () const inline inherited
Referenced by nidas::dynld::isff::SE_GOESXmtr::printStatus().
getXmitInterval()
int nidas::dynld::isff::GOESXmtr::getXmitInterval () const inline inherited
Referenced by nidas::dynld::isff::GOESOutput::getXmitInterval(), printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
getXmitOffset()
int nidas::dynld::isff::GOESXmtr::getXmitOffset () const inline inherited
Referenced by nidas::dynld::isff::GOESOutput::getXmitOffset(), printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
init()
void nidas::dynld::isff::SimGOESXmtr::init () throw (nidas::util::IOException) inline virtual
Initialize tranmitter.
Implements nidas::dynld::isff::GOESXmtr.
isNewInput()
virtual bool nidas::core::IOChannel::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented in nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::core::IOStream::read(), and nidas::core::IOStream::readUntil().
isNonBlocking()
bool nidas::dynld::isff::GOESXmtr::isNonBlocking () const throw (nidas::util::IOException) inline virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
open()
void SimGOESXmtr::open () throw (nidas::util::IOException) virtual
Reimplemented from nidas::dynld::isff::GOESXmtr.
printStatus()
void SimGOESXmtr::printStatus () throw () virtual
Request that transmitter status be printed to an output stream.
Implements nidas::dynld::isff::GOESXmtr.
References nidas::dynld::isff::GOESXmtr::_port, _transmitAtTime, _transmitQueueTime, _transmitSampleTime, nidas::util::UTime::format(), nidas::dynld::isff::GOESXmtr::getChannel(), nidas::util::SerialPort::getName(), getRFBaud(), nidas::dynld::isff::GOESXmtr::getXmitInterval(), and nidas::dynld::isff::GOESXmtr::getXmitOffset().
read()
size_t nidas::dynld::isff::SimGOESXmtr::read (void * , size_t) throw (nidas::util::IOException) inline virtual
Do the actual hardware read.
Implements nidas::core::IOChannel.
requestConnection()
void GOESXmtr::requestConnection (IOChannelRequester * rqstr) throw (nidas::util::IOException) virtual inherited
Request a connection.
Implements nidas::core::IOChannel.
reset()
void nidas::dynld::isff::SimGOESXmtr::reset () throw (nidas::util::IOException) inline virtual
Implements nidas::dynld::isff::GOESXmtr.
setChannel()
void nidas::dynld::isff::GOESXmtr::setChannel (int val) inline inherited
Referenced by main().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setId()
void nidas::dynld::isff::GOESXmtr::setId (unsigned long val) inline inherited
Referenced by main().
setName()
void nidas::dynld::isff::GOESXmtr::setName (const std::string & val) inline virtual inherited
Implements nidas::core::IOChannel.
Referenced by main().
setNonBlocking() [1/2]
void nidas::dynld::isff::GOESXmtr::setNonBlocking (bool val __attribute__(unused)) throw (nidas::util::IOException) inline inherited
setNonBlocking() [2/2]
virtual void nidas::core::IOChannel::setNonBlocking (bool val) pure virtual inherited
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setNonBlocking().
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setRFBaud()
void nidas::dynld::isff::SimGOESXmtr::setRFBaud (long val) throw (nidas::util::InvalidParameterException) inline virtual
Set the RF baud rate.
Parameters
val RF baud, in bits/sec.
Implements nidas::dynld::isff::GOESXmtr.
setStatusFile()
void nidas::dynld::isff::GOESXmtr::setStatusFile (const std::string & val) inline inherited
setXmitInterval()
void nidas::dynld::isff::GOESXmtr::setXmitInterval (long val) inline inherited
Set the transmission interval.
Parameters
val Interval, in seconds.
setXmitOffset()
void nidas::dynld::isff::GOESXmtr::setXmitOffset (long val) inline inherited
Set the transmission offset.
Parameters
val Offset, in seconds.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
transmitData()
void SimGOESXmtr::transmitData (const nidas::util::UTime & at, int configid, const Sample * samp) throw (nidas::util::IOException) virtual
Queue a sample for writing to a GOES transmitter.
Implements nidas::dynld::isff::GOESXmtr.
write() [1/2]
size_t nidas::dynld::isff::SimGOESXmtr::write (const struct iovec * , int) throw (nidas::util::IOException) inline virtual
Do the actual hardware write.
Implements nidas::core::IOChannel.
write() [2/2]
size_t nidas::dynld::isff::SimGOESXmtr::write (const void * , size_t) throw (nidas::util::IOException) inline virtual
Do the actual hardware write.
Implements nidas::core::IOChannel.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_channel
int nidas::dynld::isff::GOESXmtr::_channel private inherited
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_id
unsigned long nidas::dynld::isff::GOESXmtr::_id private inherited
_port
nidas::util::SerialPort nidas::dynld::isff::GOESXmtr::_port protected inherited
Referenced by nidas::dynld::isff::SE_GOESXmtr::getXmtrClockDelay(), nidas::dynld::isff::GOESXmtr::open(), printStatus(), nidas::dynld::isff::SE_GOESXmtr::SE_GOESXmtr(), nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
_rfBaud
int nidas::dynld::isff::SimGOESXmtr::_rfBaud private
_statusFile
std::string nidas::dynld::isff::GOESXmtr::_statusFile private inherited
_transmitAtTime
nidas::util::UTime nidas::dynld::isff::SimGOESXmtr::_transmitAtTime private
Referenced by printStatus().
_transmitQueueTime
nidas::util::UTime nidas::dynld::isff::SimGOESXmtr::_transmitQueueTime private
Referenced by printStatus().
_transmitSampleTime
nidas::util::UTime nidas::dynld::isff::SimGOESXmtr::_transmitSampleTime private
Referenced by printStatus().
_xmitInterval
int nidas::dynld::isff::GOESXmtr::_xmitInterval private inherited
_xmitOffset
int nidas::dynld::isff::GOESXmtr::_xmitOffset private inherited
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/isff/SimGOESXmtr.h
nidas/dynld/isff/SimGOESXmtr.cc