nidas: TestClient Class Reference
TestClient Class Reference abstract
Public Member Functions
TestClient ()
bool receive (const Sample *s) throw ()
Method called to pass a sample to this client.
virtual void flush ()=0
Ask that this SampleClient send out any buffered Samples that it may be holding.
Public Attributes
int nsamples
Constructor & Destructor Documentation
TestClient()
TestClient::TestClient () inline
Member Function Documentation
flush()
virtual void nidas::core::SampleClient::flush () pure virtual inherited
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implemented in nidas::core::SampleThread, nidas::core::Resampler, nidas::dynld::UDPSampleOutput, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::CVIOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, nidas::dynld::AsciiOutput, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, DumpClient, DataStats, SampleDispatcher, and DumpClient.
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::flush(), nidas::dynld::raf::CVIProcessor::flush(), nidas::dynld::SampleProcessor::flush(), nidas::dynld::StatisticsProcessor::flush(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleIOProcessor::~SampleIOProcessor(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
receive()
bool TestClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
Member Data Documentation
nsamples
int TestClient::nsamples
The documentation for this class was generated from the following file:
nidas/apps/sample_test.cc