nidas: nidas/apps/isff/set_emerald.c File Reference
set_emerald.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <nidas/linux/diamond/emerald.h>
Functions
int printConfig (int fd, const char *devname, int eepromAccess)
int setConfig (int fd, const char *devname, int port0Addr, const int *irqs, int eepromAccess)
int getNumBoards (int fd, const char *devname)
int getISABaseAddr (int fd, const char *devname, unsigned long *baseaddr)
int enablePorts (int fd, const char *devname)
int getPortMode (int fd, const char *devname, int eepromAccess)
int setPortMode (int fd, const char *devname, int eepromAccess, int mode)
void usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
enablePorts()
int enablePorts (int fd, const char * devname)
References EMERALD_IOCPORTENABLE, and fd.
Referenced by main().
getISABaseAddr()
int getISABaseAddr (int fd, const char * devname, unsigned long * baseaddr)
References EMERALD_IOCGISABASE, and fd.
Referenced by main().
getNumBoards()
int getNumBoards (int fd, const char * devname)
References EMERALD_IOCGNBOARD, and fd.
Referenced by main().
getPortMode()
int getPortMode (int fd, const char * devname, int eepromAccess)
References EMERALD_IOCG_EEMODE, EMERALD_IOCG_MODE, fd, and emerald_mode::mode.
Referenced by main().
main()
int main (int argc, char ** argv)
References enablePorts(), fd, getISABaseAddr(), getNumBoards(), getPortMode(), irqs, printConfig(), setConfig(), setPortMode(), and usage().
printConfig()
int printConfig (int fd, const char * devname, int eepromAccess)
References EMERALD_IOCGEEPORTCONFIG, EMERALD_IOCGPORTCONFIG, fd, emerald_serial_port::ioport, emerald_serial_port::irq, emerald_config::ports, and printf().
Referenced by main().
setConfig()
int setConfig (int fd, const char * devname, int port0Addr, const int * irqs, int eepromAccess)
References EMERALD_IOCEECONFIGLOAD, EMERALD_IOCSEEPORTCONFIG, EMERALD_IOCSPORTCONFIG, fd, emerald_serial_port::ioport, emerald_serial_port::irq, irqs, emerald_config::ports, and printf().
Referenced by main().
setPortMode()
int setPortMode (int fd, const char * devname, int eepromAccess, int mode)
References EMERALD_IOCEECONFIGLOAD, EMERALD_IOCS_EEMODE, EMERALD_IOCS_MODE, fd, and emerald_mode::mode.
Referenced by main().
usage()
void usage (const char * argv0)
Referenced by main().