nidas: DumpClient Class Reference
DumpClient Class Reference
Public Types
enum format {
DEFAULT , ASCII , HEX_FMT , SIGNED_SHORT ,
UNSIGNED_SHORT , FLOAT , IRIG , INT32 ,
ASCII_7 , NAKED , ASCII , BINARY1 ,
BINARY2
}
enum format {
DEFAULT , ASCII , HEX_FMT , SIGNED_SHORT ,
UNSIGNED_SHORT , FLOAT , IRIG , INT32 ,
ASCII_7 , NAKED , ASCII , BINARY1 ,
BINARY2
}
typedef enum DumpClient::format format_t
typedef enum DumpClient::format format_t
Public Member Functions
DumpClient (const SampleMatcher &, format_t, ostream &)
virtual ~DumpClient ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printHeader ()
DumpClient::format_t typeToFormat (sampleType t)
void setWarningTime (float w)
void setShowDeltaT (bool show)
void setShowLen (bool show)
void setTimeFormat (const std::string &fmt)
void setCSV (bool enable)
void setSensors (list< DSMSensor * > &sensors)
DumpClient (format_t, ostream &, int asciiPrecision)
virtual ~DumpClient ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printHeader (vector< const Variable * > vars)
void setStartTime (const n_u::UTime &val)
void setEndTime (const n_u::UTime &val)
void setDOS (bool val)
bool getDOS () const
bool finished () const
Private Member Functions
int getWidth (const std::string &name)
std::ostream & setfield (std::ostream &out, const std::string &name, int width=0)
Setup the ostream for the given field, depending on the field separator and field width.
void dumpNaked (const Sample *samp)
DumpClient (const DumpClient &)
DumpClient & operator= (const DumpClient &)
Private Attributes
SampleMatcher _samples
format_t format
ostream & ostr
const n_u::EndianConverter * fromLittle
dsm_time_t prev_tt
float warntime
bool showdeltat
bool showlen
string timeformat
bool csv
vector< string > vnames
map< string, int > widths
Map a column name to a width.
format_t _format
ostream & _ostr
n_u::UTime _startTime
n_u::UTime _endTime
bool _checkStart
bool _checkEnd
bool _dosOut
int _asciiPrecision
bool _finished
Member Typedef Documentation
format_t [1/2]
typedef enum DumpClient::format DumpClient::format_t
format_t [2/2]
typedef enum DumpClient::format DumpClient::format_t
Member Enumeration Documentation
format [1/2]
enum DumpClient::format
Enumerator
DEFAULT
ASCII
HEX_FMT
SIGNED_SHORT
UNSIGNED_SHORT
FLOAT
IRIG
INT32
ASCII_7
NAKED
ASCII
BINARY1
BINARY2
format [2/2]
enum DumpClient::format
Enumerator
DEFAULT
ASCII
HEX_FMT
SIGNED_SHORT
UNSIGNED_SHORT
FLOAT
IRIG
INT32
ASCII_7
NAKED
ASCII
BINARY1
BINARY2
Constructor & Destructor Documentation
DumpClient() [1/3]
DumpClient::DumpClient (const SampleMatcher & matcher, format_t fmt, ostream & outstr)
~DumpClient() [1/2]
virtual DumpClient::~DumpClient () inline virtual
DumpClient() [2/3]
DumpClient::DumpClient (const DumpClient &) private
DumpClient() [3/3]
DumpClient::DumpClient (format_t fmt, ostream & outstr, int asciiPrecision)
~DumpClient() [2/2]
virtual DumpClient::~DumpClient () inline virtual
Member Function Documentation
dumpNaked()
void DumpClient::dumpNaked (const Sample * samp) private
References nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), and ostr.
finished()
bool DumpClient::finished () const inline
Referenced by DataPrep::run().
flush() [1/2]
void DumpClient::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implements nidas::core::SampleClient.
flush() [2/2]
void DumpClient::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implements nidas::core::SampleClient.
getDOS()
bool DumpClient::getDOS () const inline
getWidth()
int DumpClient::getWidth (const std::string & name) inline private
Referenced by printHeader(), and setfield().
operator=()
DumpClient& DumpClient::operator= (const DumpClient &) private
printHeader() [1/2]
void DumpClient::printHeader ()
References _samples, csv, nidas::core::NidasApp::IdFormat::decimalWidth(), nidas::core::SampleMatcher::exclusiveMatch(), nidas::core::NidasApp::getIdFormat(), getWidth(), ostr, setfield(), showdeltat, showlen, vnames, and widths.
Referenced by DataDump::run(), and DataPrep::run().
printHeader() [2/2]
void DumpClient::printHeader (vector< const Variable * > vars)
References _dosOut, nidas::core::Variable::getConverter(), nidas::core::Variable::getName(), nidas::core::Variable::getUnits(), and nidas::core::VariableConverter::getUnits().
receive() [1/2]
bool DumpClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References nidas::util::addBackslashSequences(), nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::util::UTime::format(), nidas::core::NidasApp::formatSampleId(), GET_DSM_ID, and USECS_PER_SEC.
receive() [2/2]
bool DumpClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
setCSV()
void DumpClient::setCSV (bool enable) inline
Referenced by DataDump::run().
setDOS()
void DumpClient::setDOS (bool val) inline
Referenced by DataPrep::run().
setEndTime()
void DumpClient::setEndTime (const n_u::UTime & val) inline
Referenced by DataPrep::run().
setfield()
std::ostream & DumpClient::setfield (std::ostream & out, const std::string & name, int width = 0) private
Setup the ostream for the given field, depending on the field separator and field width.
References csv, and getWidth().
Referenced by printHeader().
setSensors()
void DumpClient::setSensors (list< DSMSensor * > & sensors)
References _samples, nidas::core::SampleMatcher::exclusiveMatch(), nidas::core::SampleTag::getId(), nidas::core::Variable::getPrefix(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::SampleMatcher::match(), nidas::core::SampleTagIterator::next(), nidas::core::VariableIterator::next(), and vnames.
Referenced by DataDump::run().
setShowDeltaT()
void DumpClient::setShowDeltaT (bool show) inline
Referenced by DataDump::run().
setShowLen()
void DumpClient::setShowLen (bool show) inline
Referenced by DataDump::run().
setStartTime()
void DumpClient::setStartTime (const n_u::UTime & val) inline
Referenced by DataPrep::run().
setTimeFormat()
void DumpClient::setTimeFormat (const std::string & fmt) inline
Referenced by DataDump::run().
setWarningTime()
void DumpClient::setWarningTime (float w) inline
Referenced by DataDump::run().
typeToFormat()
DumpClient::format_t DumpClient::typeToFormat (sampleType t)
References ASCII, nidas::core::CHAR_ST, nidas::core::DOUBLE_ST, FLOAT, nidas::core::FLOAT_ST, HEX_FMT, INT32, nidas::core::INT32_ST, nidas::core::INT64_ST, nidas::core::SHORT_ST, SIGNED_SHORT, nidas::core::UCHAR_ST, nidas::core::UINT32_ST, nidas::core::UNKNOWN_ST, UNSIGNED_SHORT, and nidas::core::USHORT_ST.
Member Data Documentation
_asciiPrecision
int DumpClient::_asciiPrecision private
_checkEnd
bool DumpClient::_checkEnd private
_checkStart
bool DumpClient::_checkStart private
_dosOut
bool DumpClient::_dosOut private
Referenced by printHeader().
_endTime
n_u::UTime DumpClient::_endTime private
_finished
bool DumpClient::_finished private
_format
format_t DumpClient::_format private
_ostr
ostream& DumpClient::_ostr private
_samples
SampleMatcher DumpClient::_samples private
Referenced by printHeader(), and setSensors().
_startTime
n_u::UTime DumpClient::_startTime private
csv
bool DumpClient::csv private
Referenced by printHeader(), and setfield().
format
format_t DumpClient::format private
fromLittle
const n_u::EndianConverter* DumpClient::fromLittle private
ostr
ostream& DumpClient::ostr private
Referenced by dumpNaked(), and printHeader().
prev_tt
dsm_time_t DumpClient::prev_tt private
showdeltat
bool DumpClient::showdeltat private
Referenced by printHeader().
showlen
bool DumpClient::showlen private
Referenced by printHeader().
timeformat
string DumpClient::timeformat private
vnames
vector<string> DumpClient::vnames private
Referenced by printHeader(), and setSensors().
warntime
float DumpClient::warntime private
widths
map<string, int> DumpClient::widths private
Map a column name to a width.
Referenced by printHeader().
The documentation for this class was generated from the following files:
nidas/apps/data_dump.cc
nidas/apps/isff/prep.cc