nidas: nidas/apps/status_listener.cc File Reference
status_listener.cc File Reference
#include <nidas/core/StatusListener.h>
#include <nidas/core/Datagrams.h>
#include <nidas/util/IOException.h>
#include <nidas/util/Logger.h>
#include <iostream>
#include <string>
#include <unistd.h>
#include <getopt.h>
Functions
static int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::Logger::createInstance(), debug, DLOG, nidas::util::Logger::getInstance(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::LogConfig::level, nidas::util::LOGGER_DEBUG, nidas::util::LOGGER_INFO, NIDAS_XMLRPC_STATUS_PORT_TCP, PLOG, nidas::util::Logger::setScheme(), nidas::util::Thread::start(), nidas::util::Exception::toString(), usage(), and nidas::util::Exception::what().
usage()
static int usage (const char * argv0) static
Referenced by main().