nidas: nidas::core::SensorHandler::PolledDSMSensor Class Reference
nidas::core::SensorHandler::PolledDSMSensor Class Reference
Public Member Functions
PolledDSMSensor (DSMSensor *sensor, SensorHandler *handler)
~PolledDSMSensor ()
Destructor does not close().
bool handlePollEvents (uint32_t events) throw ()
DSMSensor * getDSMSensor ()
int getFd () const
const std::string getName () const
int getTimeoutMsecs () const
void setupTimeouts (int checkIntervalMsecs)
SensorHandler implements a fairly crude way to detect timeouts on data read from sensors.
bool checkTimeout ()
The SensorHandler will call this method of each opened sensor at the interval specified previously in the call to setupTimeouts(int), or perhaps somewhat less often, due to normal overhead.
void close ()
Remove this DSMSensor from those being polled, then call its close() method.
Private Member Functions
PolledDSMSensor (const PolledDSMSensor &)
PolledDSMSensor & operator= (const PolledDSMSensor &)
Private Attributes
DSMSensor * _sensor
SensorHandler * _handler
int _nTimeoutChecks
How many times this sensor has been checked for timeouts since the last time data was reads.
int _nTimeoutChecksMax
How many timeout checks constitute an timeout on this sensor.
int _lastCheckInterval
What the previous timeout check interval was.
Constructor & Destructor Documentation
PolledDSMSensor() [1/2]
SensorHandler::PolledDSMSensor::PolledDSMSensor (DSMSensor * sensor, SensorHandler * handler)
Exceptions
nidas::util::IOException
References _handler, nidas::core::SensorHandler::getEpollFd(), getFd(), and getName().
~PolledDSMSensor()
nidas::core::SensorHandler::PolledDSMSensor::~PolledDSMSensor () inline
Destructor does not close().
PolledDSMSensor() [2/2]
nidas::core::SensorHandler::PolledDSMSensor::PolledDSMSensor (const PolledDSMSensor &) private
Member Function Documentation
checkTimeout()
bool SensorHandler::PolledDSMSensor::checkTimeout ()
The SensorHandler will call this method of each opened sensor at the interval specified previously in the call to setupTimeouts(int), or perhaps somewhat less often, due to normal overhead.
If handlePollEvents(events) with an event mask of EPOLLEDIN has not bee called since the last call to checkTimeout, then increment _nTimeoutChecks.
Returns
: true if _nTimeoutChecks is equal to _nTimeoutChecksMax. false otherwise.
References nidas::util::Thread::getName(), MSECS_PER_SEC, and WLOG.
Referenced by nidas::core::SensorHandler::checkTimeouts().
close()
void SensorHandler::PolledDSMSensor::close ()
Remove this DSMSensor from those being polled, then call its close() method.
Exceptions
nidas::util::IOException
References nidas::util::Thread::getName().
Referenced by nidas::core::SensorHandler::~SensorHandler().
getDSMSensor()
DSMSensor* nidas::core::SensorHandler::PolledDSMSensor::getDSMSensor () inline
References _sensor.
Referenced by nidas::core::SensorHandler::handlePollingChange().
getFd()
int nidas::core::SensorHandler::PolledDSMSensor::getFd () const inline virtual
Implements nidas::core::Polled.
References _sensor, and nidas::core::DSMSensor::getReadFd().
Referenced by nidas::core::SensorHandler::handlePollingChange(), and PolledDSMSensor().
getName()
const std::string nidas::core::SensorHandler::PolledDSMSensor::getName () const inline
References _sensor, and nidas::core::DSMSensor::getName().
Referenced by PolledDSMSensor().
getTimeoutMsecs()
int nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs () const inline
References _sensor, and nidas::core::DSMSensor::getTimeoutMsecs().
Referenced by nidas::core::SensorHandler::handlePollingChange().
handlePollEvents()
bool SensorHandler::PolledDSMSensor::handlePollEvents (uint32_t events) throw () virtual
Returns
: true: read consumed all available data.
Implements nidas::core::Polled.
References nidas::util::Exception::getErrno(), nidas::util::Thread::getName(), N_POLLERR, N_POLLHUP, N_POLLIN, N_POLLRDHUP, NLOG, PLOG, nidas::util::Exception::what(), and WLOG.
operator=()
PolledDSMSensor& nidas::core::SensorHandler::PolledDSMSensor::operator= (const PolledDSMSensor &) private
setupTimeouts()
void SensorHandler::PolledDSMSensor::setupTimeouts (int checkIntervalMsecs)
SensorHandler implements a fairly crude way to detect timeouts on data read from sensors.
It determines the minimum timeout value for the currently opened sensors. This value, but not less than 1000 milliseconds, is the parameter msecs, which is passed here to each opened sensor from time to time as the group of sensors changes.
In this simple implementation, this method sets the value of _nTimeoutChecksMax to: getTimeoutMsecs() + msecs -1)/msecs
Referenced by nidas::core::SensorHandler::setupTimeouts().
Member Data Documentation
_handler
SensorHandler* nidas::core::SensorHandler::PolledDSMSensor::_handler private
Referenced by PolledDSMSensor().
_lastCheckInterval
int nidas::core::SensorHandler::PolledDSMSensor::_lastCheckInterval private
What the previous timeout check interval was.
This value is used to scale _nTimeoutChecks if the check interval changes, which happens when the list of polled sensors changes.
_nTimeoutChecks
int nidas::core::SensorHandler::PolledDSMSensor::_nTimeoutChecks private
How many times this sensor has been checked for timeouts since the last time data was reads.
_nTimeoutChecksMax
int nidas::core::SensorHandler::PolledDSMSensor::_nTimeoutChecksMax private
How many timeout checks constitute an timeout on this sensor.
_sensor
DSMSensor* nidas::core::SensorHandler::PolledDSMSensor::_sensor private
Referenced by getDSMSensor(), getFd(), getName(), and getTimeoutMsecs().
The documentation for this class was generated from the following files:
nidas/core/SensorHandler.h
nidas/core/SensorHandler.cc