nidas: nidas::util::Inet4NetworkInterface Class Reference
nidas::util::Inet4NetworkInterface Class Reference
#include <Inet4NetworkInterface.h>
Public Member Functions
Inet4NetworkInterface ()
Inet4NetworkInterface (const std::string &name, Inet4Address addr, Inet4Address brdcastAddr, Inet4Address netmask, int mtu, int index, short flags)
const std::string & getName () const
The name of the interface: like "lo", "eth0", etc.
int getIndex () const
The index of the interface.
Inet4Address getAddress () const
The IPV4 address of the interface.
Inet4Address getBroadcastAddress () const
The IPV4 broadcast address of the interface.
Inet4Address getNetMask () const
The IPV4 network mask of the interface.
int getMTU () const
The mtu of the interface.
short getFlags () const
The interface flags.
Static Public Member Functions
static Inet4NetworkInterface getInterface (const Inet4Address &addr)
Return an Inet4NetworkInterface corresponding to the given address.
Private Attributes
std::string _name
int _index
Inet4Address _addr
Inet4Address _baddr
Inet4Address _netmask
int _mtu
short _flags
Constructor & Destructor Documentation
Inet4NetworkInterface() [1/2]
nidas::util::Inet4NetworkInterface::Inet4NetworkInterface () inline
Inet4NetworkInterface() [2/2]
nidas::util::Inet4NetworkInterface::Inet4NetworkInterface (const std::string & name, Inet4Address addr, Inet4Address brdcastAddr, Inet4Address netmask, int mtu, int index, short flags) inline
Member Function Documentation
getAddress()
Inet4Address nidas::util::Inet4NetworkInterface::getAddress () const inline
The IPV4 address of the interface.
References _addr.
Referenced by nidas::core::MultipleUDPSockets::addClient(), nidas::util::SocketImpl::getInterface(), getInterface(), nidas::util::SocketImpl::joinGroup(), nidas::util::SocketImpl::leaveGroup(), nidas::util::listMulticastInterfaces(), nidas::util::SocketImpl::receive(), nidas::core::DSMServerStat::run(), and nidas::util::SocketImpl::setInterface().
getBroadcastAddress()
Inet4Address nidas::util::Inet4NetworkInterface::getBroadcastAddress () const inline
The IPV4 broadcast address of the interface.
References _baddr.
getFlags()
short nidas::util::Inet4NetworkInterface::getFlags () const inline
The interface flags.
Use macros like IFF_UP, IFF_BROADCAST, IFF_POINTOPOINT, IFF_MULTICAST, IFF_LOOPBACK from net/if.h to check for capabilities. See man netdevice.
References _flags.
Referenced by nidas::util::SocketImpl::joinGroup(), nidas::util::listMulticastInterfaces(), nidas::core::StatusListener::run(), and nidas::core::DSMServerStat::run().
getIndex()
int nidas::util::Inet4NetworkInterface::getIndex () const inline
The index of the interface.
References _index.
Referenced by nidas::core::Project::findDSM(), nidas::util::SocketImpl::joinGroup(), nidas::util::SocketImpl::leaveGroup(), nidas::util::listMulticastInterfaces(), nidas::util::SocketImpl::receive(), and nidas::util::SocketImpl::setInterface().
getInterface()
Inet4NetworkInterface Inet4NetworkInterface::getInterface (const Inet4Address & addr) static
Return an Inet4NetworkInterface corresponding to the given address.
If the address does not match the address of an interface on this host, then the Inet4NetworkInterface returned will have a getIndex() value of -1. This static method will throw an IOException if a temporary TCP Socket cannot be created on this host, or if the system call to fetch its interfaces fails.
Exceptions
nidas::util::IOException
References _index, nidas::util::Socket::close(), DLOG, getAddress(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Socket::getInterfaces(), and getName().
Referenced by nidas::core::Project::findDSM().
getMTU()
int nidas::util::Inet4NetworkInterface::getMTU () const inline
The mtu of the interface.
References _mtu.
getName()
const std::string& nidas::util::Inet4NetworkInterface::getName () const inline
The name of the interface: like "lo", "eth0", etc.
References _name.
Referenced by nidas::core::Project::findDSM(), getInterface(), nidas::util::SocketImpl::joinGroup(), nidas::util::listMulticastInterfaces(), nidas::util::SocketImpl::receive(), nidas::core::StatusListener::run(), and nidas::util::SocketImpl::setInterface().
getNetMask()
Inet4Address nidas::util::Inet4NetworkInterface::getNetMask () const inline
The IPV4 network mask of the interface.
References _netmask.
Member Data Documentation
_addr
Inet4Address nidas::util::Inet4NetworkInterface::_addr private
Referenced by getAddress().
_baddr
Inet4Address nidas::util::Inet4NetworkInterface::_baddr private
Referenced by getBroadcastAddress().
_flags
short nidas::util::Inet4NetworkInterface::_flags private
Referenced by getFlags().
_index
int nidas::util::Inet4NetworkInterface::_index private
Referenced by getIndex(), and getInterface().
_mtu
int nidas::util::Inet4NetworkInterface::_mtu private
Referenced by getMTU().
_name
std::string nidas::util::Inet4NetworkInterface::_name private
Referenced by getName().
_netmask
Inet4Address nidas::util::Inet4NetworkInterface::_netmask private
Referenced by getNetMask().
The documentation for this class was generated from the following files:
nidas/util/Inet4NetworkInterface.h
nidas/util/Inet4NetworkInterface.cc