nidas: TeeTTy Class Reference
TeeTTy Class Reference
Public Member Functions
TeeTTy ()
int parseRunstring (int argc, char **argv)
int run ()
void setFIFOPriority (int val)
void setupSignals ()
Static Public Member Functions
static int usage (const char *argv0)
Private Attributes
string progname
string ttyname
n_u::SerialOptions ttyopts
list< string > rwptys
list< string > roptys
bool readonly
bool asDaemon
int priority
sigset_t _signalMask
int linedisc
Constructor & Destructor Documentation
TeeTTy()
TeeTTy::TeeTTy ()
Member Function Documentation
parseRunstring()
int TeeTTy::parseRunstring (int argc, char ** argv)
References asDaemon, linedisc, nidas::util::SerialOptions::parse(), priority, progname, readonly, roptys, rwptys, ttyname, ttyopts, usage(), and nidas::util::Exception::what().
Referenced by main().
run()
int TeeTTy::run ()
References _signalMask, nidas::util::LogScheme::addConfig(), nidas::util::Termios::apply(), asDaemon, nidas::util::Logger::createInstance(), nidas::util::SerialPort::createPtyLink(), DLOG, fd, nidas::util::SerialPort::getFd(), nidas::util::SerialPort::getName(), nidas::util::Termios::getRaw(), nidas::util::SerialOptions::getTermios(), interrupted, nidas::util::LogConfig::level, linedisc, nidas::util::SerialPort::open(), PLOG, priority, progname, nidas::util::SerialPort::read(), readonly, roptys, rwptys, setFIFOPriority(), nidas::util::Termios::setRaw(), nidas::util::Logger::setScheme(), setupSignals(), nidas::util::SerialPort::termios(), ttyname, ttyopts, USECS_PER_SEC, nidas::util::Exception::what(), WLOG, and nidas::util::SerialPort::write().
Referenced by main().
setFIFOPriority()
void TeeTTy::setFIFOPriority (int val)
References progname, nidas::util::Exception::what(), and WLOG.
Referenced by run().
setupSignals()
void TeeTTy::setupSignals ()
References _signalMask, and sigAction().
Referenced by run().
usage()
int TeeTTy::usage (const char * argv0) static
References nidas::util::SerialOptions::usage().
Referenced by parseRunstring().
Member Data Documentation
_signalMask
sigset_t TeeTTy::_signalMask private
Referenced by run(), and setupSignals().
asDaemon
bool TeeTTy::asDaemon private
Referenced by parseRunstring(), and run().
linedisc
int TeeTTy::linedisc private
Referenced by parseRunstring(), and run().
priority
int TeeTTy::priority private
Referenced by parseRunstring(), and run().
progname
string TeeTTy::progname private
Referenced by parseRunstring(), run(), and setFIFOPriority().
readonly
bool TeeTTy::readonly private
Referenced by parseRunstring(), and run().
roptys
list<string> TeeTTy::roptys private
Referenced by parseRunstring(), and run().
rwptys
list<string> TeeTTy::rwptys private
Referenced by parseRunstring(), and run().
ttyname
string TeeTTy::ttyname private
Referenced by parseRunstring(), and run().
ttyopts
n_u::SerialOptions TeeTTy::ttyopts private
Referenced by parseRunstring(), and run().
The documentation for this class was generated from the following file:
nidas/apps/tee_tty.cc