nidas: RemoteSerial Class Reference
RemoteSerial Class Reference
RemoteSerial provides a connection between a user's stdin/stdout and a DSMSerialSensor - so that one can send and receive characters while the sensor is connected and being sampled by the DSM.
Public Member Functions
~RemoteSerial ()
Public destructor.
int main (int argc, char *argv[])
Entry point for passing command line args.
int parseRunstring (int argc, char *argv[])
Configure parameters from runstring.
int usage (const char *argv0)
void run ()
Polling loop, reading and writing from stdin/stdout and socket.
void interrupt ()
It's time to quit.
Static Public Member Functions
static RemoteSerial * getInstance ()
Static method to get singleton instance.
static void signalCatcher (int isig)
Signal handler.
Static Public Attributes
static const char ESC = '\x1b'
Private Types
enum output { HEX , ASCII , BOTH }
Private Member Functions
RemoteSerial ()
void removeStdin ()
void setupSignals ()
void setupStdinout ()
void restoreStdin ()
void openConnection (n_u::Inet4SocketAddress saddr, const string &sensorName)
string socketReadLine ()
void charout (char c)
RemoteSerial (const RemoteSerial &)
No copying.
RemoteSerial & operator= (const RemoteSerial &)
No assignment.
Private Attributes
bool interrupted
enum output outputOption
string hostName
unsigned short socketPort
bool stdinAltered
struct termios termio_save
n_u::Socket * socket
string sensorName
struct pollfd pollfds [2]
const int BUFSIZE
char * buffer
int bufhead
int buftail
int baud
string parity
int databits
int stopbits
string messageSeparator
bool separatorAtEOM
int messageLength
int _stdinfd
Static Private Attributes
static RemoteSerial * instance = 0
Detailed Description
RemoteSerial provides a connection between a user's stdin/stdout and a DSMSerialSensor - so that one can send and receive characters while the sensor is connected and being sampled by the DSM.
Member Enumeration Documentation
output
enum RemoteSerial::output private
Enumerator
HEX
ASCII
BOTH
Constructor & Destructor Documentation
~RemoteSerial()
RemoteSerial::~RemoteSerial ()
Public destructor.
References buffer, nidas::util::Socket::close(), instance, and socket.
RemoteSerial() [1/2]
RemoteSerial::RemoteSerial () private
References buffer, and bufhead.
Referenced by getInstance().
RemoteSerial() [2/2]
RemoteSerial::RemoteSerial (const RemoteSerial &) private
No copying.
Member Function Documentation
charout()
void RemoteSerial::charout (char c) private
References ASCII, BOTH, HEX, outputOption, and printf().
Referenced by run().
getInstance()
RemoteSerial * RemoteSerial::getInstance () static
Static method to get singleton instance.
The singleton pattern is used here so that signal handlers can access the RemoteSerial instance.
References instance, and RemoteSerial().
Referenced by main(), and signalCatcher().
interrupt()
void RemoteSerial::interrupt () inline
It's time to quit.
References interrupted.
Referenced by run(), and signalCatcher().
main()
int RemoteSerial::main (int argc, char * argv[])
Entry point for passing command line args.
References nidas::util::Inet4Address::getByName(), hostName, openConnection(), parseRunstring(), restoreStdin(), run(), sensorName, setupSignals(), setupStdinout(), socketPort, and nidas::util::Exception::toString().
openConnection()
void RemoteSerial::openConnection (n_u::Inet4SocketAddress saddr, const string & sensorName) private
References _stdinfd, baud, databits, messageLength, messageSeparator, parity, nidas::util::replaceBackslashSequences(), nidas::util::Socket::sendall(), sensorName, separatorAtEOM, socket, socketReadLine(), stopbits, and nidas::util::Inet4SocketAddress::toString().
Referenced by main().
operator=()
RemoteSerial& RemoteSerial::operator= (const RemoteSerial &) private
No assignment.
parseRunstring()
int RemoteSerial::parseRunstring (int argc, char * argv[])
Configure parameters from runstring.
References ASCII, BOTH, HEX, hostName, outputOption, removeStdin(), sensorName, socketPort, and usage().
Referenced by main().
removeStdin()
void RemoteSerial::removeStdin () inline private
Referenced by parseRunstring(), run(), and signalCatcher().
restoreStdin()
void RemoteSerial::restoreStdin () private
References _stdinfd, stdinAltered, and termio_save.
Referenced by main().
run()
void RemoteSerial::run ()
Polling loop, reading and writing from stdin/stdout and socket.
References _stdinfd, ASCII, buffer, BUFSIZE, charout(), ESC, nidas::util::Socket::getFd(), nidas::util::Socket::getRemoteSocketAddress(), HEX, interrupt(), interrupted, messageLength, messageSeparator, outputOption, pollfds, printf(), nidas::util::Socket::recv(), removeStdin(), nidas::util::Socket::sendall(), separatorAtEOM, socket, nidas::util::SocketAddress::toString(), and nidas::util::Exception::what().
Referenced by main().
setupSignals()
void RemoteSerial::setupSignals () private
References signalCatcher().
Referenced by main().
setupStdinout()
void RemoteSerial::setupStdinout () private
References _stdinfd, stdinAltered, and termio_save.
Referenced by main().
signalCatcher()
void RemoteSerial::signalCatcher (int isig) static
Signal handler.
catch signals
References getInstance(), interrupt(), and removeStdin().
Referenced by setupSignals().
socketReadLine()
string RemoteSerial::socketReadLine () private
References buffer, bufhead, BUFSIZE, buftail, len, nidas::util::Socket::recv(), and socket.
Referenced by openConnection().
usage()
int RemoteSerial::usage (const char * argv0)
Referenced by parseRunstring().
Member Data Documentation
_stdinfd
int RemoteSerial::_stdinfd private
Referenced by openConnection(), restoreStdin(), run(), and setupStdinout().
baud
int RemoteSerial::baud private
Referenced by openConnection().
buffer
char* RemoteSerial::buffer private
Referenced by RemoteSerial(), run(), socketReadLine(), and ~RemoteSerial().
bufhead
int RemoteSerial::bufhead private
Referenced by RemoteSerial(), and socketReadLine().
BUFSIZE
const int RemoteSerial::BUFSIZE private
Referenced by run(), and socketReadLine().
buftail
int RemoteSerial::buftail private
Referenced by socketReadLine().
databits
int RemoteSerial::databits private
Referenced by openConnection().
ESC
const char RemoteSerial::ESC = '\x1b' static
Referenced by run().
hostName
string RemoteSerial::hostName private
Referenced by main(), and parseRunstring().
instance
RemoteSerial * RemoteSerial::instance = 0 static private
Referenced by getInstance(), and ~RemoteSerial().
interrupted
bool RemoteSerial::interrupted private
Referenced by run().
messageLength
int RemoteSerial::messageLength private
Referenced by openConnection(), and run().
messageSeparator
string RemoteSerial::messageSeparator private
Referenced by openConnection(), and run().
outputOption
enum output RemoteSerial::outputOption private
Referenced by charout(), parseRunstring(), and run().
parity
string RemoteSerial::parity private
Referenced by openConnection().
pollfds
struct pollfd RemoteSerial::pollfds[2] private
Referenced by run().
sensorName
string RemoteSerial::sensorName private
Referenced by main(), openConnection(), and parseRunstring().
separatorAtEOM
bool RemoteSerial::separatorAtEOM private
Referenced by openConnection(), and run().
socket
n_u::Socket* RemoteSerial::socket private
Referenced by openConnection(), run(), socketReadLine(), and ~RemoteSerial().
socketPort
unsigned short RemoteSerial::socketPort private
Referenced by main(), and parseRunstring().
stdinAltered
bool RemoteSerial::stdinAltered private
Referenced by restoreStdin(), and setupStdinout().
stopbits
int RemoteSerial::stopbits private
Referenced by openConnection().
termio_save
struct termios RemoteSerial::termio_save private
Referenced by restoreStdin(), and setupStdinout().
The documentation for this class was generated from the following file:
nidas/apps/rserial.cc