nidas: nidas::dynld::isff::PacketParser Class Reference
nidas::dynld::isff::PacketParser Class Reference
#include <Packets.h>
Public Types
enum packet_type { NESDIS_PT , UNKNOWN_PT }
enum info_type { NESDIS_IT , SUTRON_IT , UNKNOWN_IT }
Public Member Functions
PacketParser () throw (nidas::util::ParseException)
~PacketParser ()
enum packet_type parse (const char *) throw (nidas::util::ParseException)
const nidas::util::UTime & getPacketTime () const
const PacketInfo * getPacketInfo () const
int getStationId () const
int getConfigId () const
int getSampleId () const
void parseData (float *, int nvars)
Private Member Functions
PacketParser (const PacketParser &)
No copying.
PacketParser & operator= (const PacketParser &)
No assignment.
Private Attributes
int _nPacketTypes
int _nInfoTypes
const size_t _nmatch
Max number of parenthesized expressions in any regular expression.
::regmatch_t * _pmatch
Array for returning pointer to beginning of the match to each parenthesized expression.
PacketInfo * _packetInfo
int _infoType
nidas::util::UTime _packetTime
int _stationId
const char * _packetPtr
Pointer into the current packet.
const char * _endOfPacket
One past the end of the current packet.
int _configId
int _sampleId
Static Private Attributes
::regex_t ** _packetPreg = 0
::regex_t ** _infoPreg = 0
static nidas::util::Mutex _pregMutex
Member Enumeration Documentation
info_type
enum nidas::dynld::isff::PacketParser::info_type
Enumerator
NESDIS_IT
SUTRON_IT
UNKNOWN_IT
packet_type
enum nidas::dynld::isff::PacketParser::packet_type
Enumerator
NESDIS_PT
UNKNOWN_PT
Constructor & Destructor Documentation
PacketParser() [1/2]
PacketParser::PacketParser () throw (nidas::util::ParseException)
~PacketParser()
PacketParser::~PacketParser ()
PacketParser() [2/2]
nidas::dynld::isff::PacketParser::PacketParser (const PacketParser &) private
No copying.
Member Function Documentation
getConfigId()
int nidas::dynld::isff::PacketParser::getConfigId () const inline
References _configId.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getPacketInfo()
const PacketInfo* nidas::dynld::isff::PacketParser::getPacketInfo () const inline
References _packetInfo.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getPacketTime()
const nidas::util::UTime& nidas::dynld::isff::PacketParser::getPacketTime () const inline
References _packetTime.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getSampleId()
int nidas::dynld::isff::PacketParser::getSampleId () const inline
References _sampleId.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getStationId()
int nidas::dynld::isff::PacketParser::getStationId () const inline
References _stationId.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
operator=()
PacketParser& nidas::dynld::isff::PacketParser::operator= (const PacketParser &) private
No assignment.
parse()
PacketParser::packet_type PacketParser::parse (const char * packet) throw (nidas::util::ParseException)
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
parseData()
void PacketParser::parseData (float * fptr, int nvars)
References nidas::dynld::isff::GOES::float_decode_4x6(), and nidas::core::floatNAN.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
Member Data Documentation
_configId
int nidas::dynld::isff::PacketParser::_configId private
Referenced by getConfigId().
_endOfPacket
const char* nidas::dynld::isff::PacketParser::_endOfPacket private
One past the end of the current packet.
_infoPreg
regex_t ** PacketParser::_infoPreg = 0 static private
_infoType
int nidas::dynld::isff::PacketParser::_infoType private
_nInfoTypes
int nidas::dynld::isff::PacketParser::_nInfoTypes private
_nmatch
const size_t nidas::dynld::isff::PacketParser::_nmatch private
Max number of parenthesized expressions in any regular expression.
_nPacketTypes
int nidas::dynld::isff::PacketParser::_nPacketTypes private
_packetInfo
PacketInfo* nidas::dynld::isff::PacketParser::_packetInfo private
Referenced by getPacketInfo().
_packetPreg
regex_t ** PacketParser::_packetPreg = 0 static private
_packetPtr
const char* nidas::dynld::isff::PacketParser::_packetPtr private
Pointer into the current packet.
_packetTime
nidas::util::UTime nidas::dynld::isff::PacketParser::_packetTime private
Referenced by getPacketTime().
_pmatch
::regmatch_t* nidas::dynld::isff::PacketParser::_pmatch private
Array for returning pointer to beginning of the match to each parenthesized expression.
_pregMutex
nidas::util::Mutex PacketParser::_pregMutex static private
_sampleId
int nidas::dynld::isff::PacketParser::_sampleId private
Referenced by getSampleId().
_stationId
int nidas::dynld::isff::PacketParser::_stationId private
Referenced by getStationId().
The documentation for this class was generated from the following files:
nidas/dynld/isff/Packets.h
nidas/dynld/isff/Packets.cc