nidas: Logging
Logging
Three main classes comprise the nidas::util logging facility:
Modules
Integer Logger Levels
Define constants equal to the syslog levels, so we can redefine the syslog symbols.
Logging Macros
These macros specify a log point in the code from which the given message can be logged with the given log level.
Files
file Logger.h
Header file for the nidas::util logging facility.
Classes
class nidas::util::LogContext
The LogContext is created at a point in the application code and filled in with details about that log point, such as the file and line number, and the function name of the containing function, and the log level of that log point, such as LOGGER_DEBUG or LOGGER_ERROR.
class nidas::util::LogConfig
A configuration to enable or disable a matching set of log points.
class nidas::util::LogScheme
A LogScheme is a vector of LogConfig's and the vector of fields to show in log messages.
class nidas::util::LogMessage
A class for formatting and streaming a log message.
class nidas::util::Logger
Simple logging class, based on UNIX syslog interface.
Macros
#define LOG_CONTEXT(LEVEL) nidas::util::LEVEL, __FILE__, __PRETTY_FUNCTION__, __LINE__
#define LOG_STATIC_CONTEXT(LEVEL) nidas::util::LEVEL, __FILE__, "file_static_scope", __LINE__
Expand to LogContext tuple outside function scope.
#define LOG_EMERG LOG_CONTEXT(LOGGER_EMERG)
#define LOG_ALERT LOG_CONTEXT(LOGGER_ALERT)
#define LOG_CRIT LOG_CONTEXT(LOGGER_CRIT)
#define LOG_ERR LOG_CONTEXT(LOGGER_ERR)
#define LOG_WARNING LOG_CONTEXT(LOGGER_WARNING)
#define LOG_NOTICE LOG_CONTEXT(LOGGER_NOTICE)
#define LOG_INFO LOG_CONTEXT(LOGGER_INFO)
#define LOG_DEBUG LOG_CONTEXT(LOGGER_DEBUG)
#define LOG_VERBOSE LOG_CONTEXT(LOGGER_VERBOSE)
#define LOGGER_LOGPOINT(LEVEL, TAGS, MSG)
This macro creates a static LogContext instance that is not in thread-local storage and therefore is not thread-safe.
Functions
int nidas::util::stringToLogLevel (const std::string &slevel)
Convert the name of a log level to its integer value.
string nidas::util::logLevelToString (int)
Convert an integral log level to a string name.
LogMessage & nidas::util::endlog (LogMessage &logmsg)
LogMessage manipulator which logs the current message buffer, if any, and then clears the message.
LogMessage & nidas::util::operator<< (LogMessage &logmsg, LogMessage &(*op)(LogMessage &))
Template to call LogMessage manipulators like endlog when streamed to a LogMessage.
template<typename T >
LogMessage & nidas::util::LogMessage::operator<< (const T &t)
Everything streamed to a LogMessage is passed on to the underlying ostringstream, including ostream manipulators.
void nidas::util::LogContext::log (const std::string &msg) const
Convenience method which writes the given message to the current Logger instance, passing this object as the LogContext instance.
LogMessage nidas::util::LogContext::log () const
Return a LogMessage associated with this LogContext, so the message will be logged through this context when the LogMessage goes out of scope.
template<typename T >
T nidas::util::LogScheme::getParameterT (const std::string &name, const T &dvalue=T())
Lookup a parameter with name name in a LogScheme and convert the value to the type of the dvalue parameter.
const int nidas::util::LOGGER_EMERGENCY = LOG_EMERG
const int nidas::util::LOGGER_ALERT = LOG_ALERT
const int nidas::util::LOGGER_CRIT = LOG_CRIT
const int nidas::util::LOGGER_CRITICAL = LOG_CRIT
const int nidas::util::LOGGER_ERROR = LOG_ERR
const int nidas::util::LOGGER_ERR = LOG_ERR
const int nidas::util::LOGGER_PROBLEM = LOG_ERR
const int nidas::util::LOGGER_WARNING = LOG_WARNING
const int nidas::util::LOGGER_NOTICE = LOG_NOTICE
const int nidas::util::LOGGER_INFO = LOG_INFO
const int nidas::util::LOGGER_DEBUG = LOG_DEBUG
const int nidas::util::LOGGER_VERBOSE = LOG_DEBUG+1
const int nidas::util::LOGGER_NONE = LOG_EMERG-1
#define ALOG(MSG) LOGGER_LOGPOINT(LOGGER_ALERT,"",MSG)
#define CLOG(MSG) LOGGER_LOGPOINT(LOGGER_CRITICAL,"",MSG)
#define PLOG(MSG) LOGGER_LOGPOINT(LOGGER_ERR,"",MSG)
#define WLOG(MSG) LOGGER_LOGPOINT(LOGGER_WARNING,"",MSG)
#define NLOG(MSG) LOGGER_LOGPOINT(LOGGER_NOTICE,"",MSG)
#define ILOG(MSG) LOGGER_LOGPOINT(LOGGER_INFO,"",MSG)
#define DLOG(MSG) LOGGER_LOGPOINT(LOGGER_DEBUG,"",MSG)
#define VLOG(MSG) LOGGER_LOGPOINT(LOGGER_VERBOSE,"",MSG)
#define ELOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_EMERG,TAGS,MSG)
#define ALOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_ALERT,TAGS,MSG)
#define CLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_CRITICAL,TAGS,MSG)
#define PLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_ERR,TAGS,MSG)
#define WLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_WARNING,TAGS,MSG)
#define NLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_NOTICE,TAGS,MSG)
#define ILOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_INFO,TAGS,MSG)
#define DLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_DEBUG,TAGS,MSG)
#define VLOGT(TAGS, MSG) LOGGER_LOGPOINT(LOGGER_VERBOSE,TAGS,MSG)
Detailed Description
Three main classes comprise the nidas::util logging facility:
nidas::util::LogContext
nidas::util::Logger
nidas::util::LogConfig
The intended use of this interface is through the Logging Macros. These macros automatically instantiate a LogContext and control the formatting and sending of the log message according to the current logging configuration. The advantage of the macros is that they are less verbose and there is no overhead formatting the message parameters if the log message is not currently enabled. However, the original form of calling the Logger::log() method directly still works. That form could be more natural in some cases. It is equivalent to the macros except the log message call cannot suppressed: the message itself is suppressed within the log() method by checking the LogContext against the current configuration. The syslog macros like LOG_EMERG are redefined to be a comma-separated list of the LogContext parameters, so those parameters are passed into the log() call. In other words, consider original logging code that looks like this:
n_u::Logger::getInstance()->log(LOG_INFO,
   "~DSMEngine %s: %s",output->getName().c_str(),e.what());
LOG_INFO is expanded to this:
nidas::util::LOGGER_INFO, __FILE__, __PRETTY_FUNCTION__, __LINE__
So the log() call receives all of the context information it needs to first of all compile a more complete log message, and second to determine if the message has been enabled.
The log() call above could be rewritten using a macro as follows:
ILOG(("~DSMEngine %s: %s",output->getName().c_str(),e.what()));
or alternatively with ostream operators:
ILOG(("~DSMEngine ") << output->getName() << ": " << e.what());
LogConfig objects can be created to configure the set of log points which will be active. See Logging Configuration Schemes.
NIDAS can configure the available logging schemes and the current scheme through the XML config file. Below is an excerpt from within the <project> element. The log scheme is set with the <logger> element.
Todo:
A nice enhancement someday would be to set the log scheme name from the dsm command-line.
 <logger scheme='everything' />
 <logscheme name='everything'>
 <showfields>all</showfields>
 <logconfig level='debug'/>
 <logconfig filematch='nidas'/>
 </logscheme>
 <logscheme name='everything-but-utils'>
 <showfields>all</showfields>
 <logconfig level='debug'/>
 <logconfig filematch='util' activate='false'/>
 </logscheme>
<logscheme name='nothing'>
    </logscheme>
    <logscheme name='info'>
    <logconfig level='info'/>
    </logscheme>
    <logscheme name='sampledebug'>
    <logconfig level='debug'/>
    <logconfig tagmatch='samples'/>
    </logscheme>
    <logscheme name='iss-debug'>
    <showfields>level,time,function,message</showfields>
    <logconfig filematch='dynld/iss'/>
    </logscheme>
    <logscheme name='tilt-sensor-debug'>
    <logconfig filematch='dynld/iss'/>
    <logconfig filematch='dynld/psql'/>
    <logconfig filematch='nidas/core'/>
    </logscheme>
Macro Definition Documentation
ALOG
#define ALOG (MSG) LOGGER_LOGPOINT(LOGGER_ALERT,"",MSG)
ALOGT
#define ALOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_ALERT,TAGS,MSG)
CLOG
#define CLOG (MSG) LOGGER_LOGPOINT(LOGGER_CRITICAL,"",MSG)
CLOGT
#define CLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_CRITICAL,TAGS,MSG)
DLOG
#define DLOG (MSG) LOGGER_LOGPOINT(LOGGER_DEBUG,"",MSG)
DLOGT
#define DLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_DEBUG,TAGS,MSG)
ELOGT
#define ELOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_EMERG,TAGS,MSG)
ILOG
#define ILOG (MSG) LOGGER_LOGPOINT(LOGGER_INFO,"",MSG)
ILOGT
#define ILOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_INFO,TAGS,MSG)
LOG_ALERT
#define LOG_ALERT LOG_CONTEXT(LOGGER_ALERT)
LOG_CONTEXT
#define LOG_CONTEXT (LEVEL) nidas::util::LEVEL, __FILE__, __PRETTY_FUNCTION__, __LINE__
LOG_CRIT
#define LOG_CRIT LOG_CONTEXT(LOGGER_CRIT)
LOG_DEBUG
#define LOG_DEBUG LOG_CONTEXT(LOGGER_DEBUG)
LOG_EMERG
#define LOG_EMERG LOG_CONTEXT(LOGGER_EMERG)
LOG_ERR
#define LOG_ERR LOG_CONTEXT(LOGGER_ERR)
LOG_INFO
#define LOG_INFO LOG_CONTEXT(LOGGER_INFO)
LOG_NOTICE
#define LOG_NOTICE LOG_CONTEXT(LOGGER_NOTICE)
LOG_STATIC_CONTEXT
#define LOG_STATIC_CONTEXT (LEVEL) nidas::util::LEVEL, __FILE__, "file_static_scope", __LINE__
Expand to LogContext tuple outside function scope.
Use this macro to expand to the LogContext arguments when not inside a function, when PRETTY_FUNCTION is not valid.
LOG_VERBOSE
#define LOG_VERBOSE LOG_CONTEXT(LOGGER_VERBOSE)
LOG_WARNING
#define LOG_WARNING LOG_CONTEXT(LOGGER_WARNING)
LOGGER_LOGPOINT
#define LOGGER_LOGPOINT (LEVEL, TAGS, MSG)
Value:
    do {                                                                \
        static nidas::util::LogContext logctxt                          \
            (nidas::util::LEVEL, __FILE__,__PRETTY_FUNCTION__,          \
             __LINE__,TAGS);                                            \
        if (logctxt.active())                                           \
            logctxt.log(nidas::util::LogMessage().format MSG); }        \
    while (0)
This macro creates a static LogContext instance that is not in thread-local storage and therefore is not thread-safe.
The active flag will be written from any thread which changes the log configuration, and reads of the active flag happen in all threads which execute this log point. TLS was implemented at one point, but it turned out not to be portable enough. Locking is not really warranted given that in practice logging configurations do not change during runtime.
If thread-safety is required, then an automatic lock can be added to the beginning of the do-while block. I don't think the static initialization needs to happen inside the lock, at least for GCC. GCC already guards static initialization, but helgrind or DRD may not be able to recognize that without surrounding the block with a pthread lock. The actual check of the active flag probably should be thread-safe, since presumably one thread will initially write it and then multiple threads will read it. If the write happens inside the guard and only reads happen outside, then maybe that's safe enough since the reconfiguration of running log points does not happen in practice.
The lock used cannot be the global logging lock unless it is unlocked before calling the log() method, since the global lock is locked by the log() method and the lock is not recurisve. One goal for all this is to make things look reasonable and consistent to program checkers like helgrind.
The VERBOSE log level is intended for very verbose log messages which typically would only be used by developers. They are never enabled by a default LogConfig, they are above the DEBUG threshold, and in practice their overhead should be minimized by testing whether the log point is active() before generating any log output. It should be safe to compile them into code, and that should be preferred over surrounding them in a pre-processor conditional compilation block.
NLOG
#define NLOG (MSG) LOGGER_LOGPOINT(LOGGER_NOTICE,"",MSG)
NLOGT
#define NLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_NOTICE,TAGS,MSG)
PLOG
#define PLOG (MSG) LOGGER_LOGPOINT(LOGGER_ERR,"",MSG)
PLOGT
#define PLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_ERR,TAGS,MSG)
VLOG
#define VLOG (MSG) LOGGER_LOGPOINT(LOGGER_VERBOSE,"",MSG)
VLOGT
#define VLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_VERBOSE,TAGS,MSG)
WLOG
#define WLOG (MSG) LOGGER_LOGPOINT(LOGGER_WARNING,"",MSG)
WLOGT
#define WLOGT (TAGS, MSG) LOGGER_LOGPOINT(LOGGER_WARNING,TAGS,MSG)
Function Documentation
endlog()
LogMessage& nidas::util::endlog (LogMessage & logmsg) inline
LogMessage manipulator which logs the current message buffer, if any, and then clears the message.
References nidas::util::LogMessage::log().
Referenced by nidas::core::SamplePipeline::connect(), nidas::dynld::raf::TwoD_USB::countParticle(), nidas::dynld::raf::SyncRecordSource::preLoadCalibrations(), nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::core::SampleSorter::run(), and nidas::dynld::raf::SyncRecordSource::slog().
getParameterT()
template<typename T > T nidas::util::LogScheme::getParameterT (const std::string & name, const T & dvalue = T())
Lookup a parameter with name name in a LogScheme and convert the value to the type of the dvalue parameter.
If the parameter has not been set in this LogScheme or cannot be converted, then return dvalue.
Below is an example of using a log parameter to throttle the frequency of a log message. The first section retrieves the value from the currently active LogScheme, the second logs the message.
_discardWarningCount = 1000;
_discardWarningCount =
  Logger::getScheme().getParameterT("_discard_warning_count",
                                    _discardWarningCount);
Then use the parameter value like so:
if (!(_discardedSamples++ % _discardWarningCount))
    WLOG(("%d samples discarded... ", _discardedSamples));
See the NidasApp class 'logparam' option to set a LogScheme parameter on the command-line.
References nidas::util::LogScheme::getParameter().
Referenced by nidas::dynld::GPS_NMEA_Serial::GPS_NMEA_Serial(), and nidas::core::SampleSorter::SampleSorter().
log() [1/2]
LogMessage nidas::util::LogContext::log () const inline
Return a LogMessage associated with this LogContext, so the message will be logged through this context when the LogMessage goes out of scope.
Typically this is used as a temporary object to which the log message content can be streamed, which can be a little more convenient than formatting the message separately and then passing it to log(const std::string& msg). Also see the LogMessage() constructor which takes a LogContext.
static LogContext lp(LOG_INFO);
if (lp.active())
{
    lp.log() << "complicated info output...";
}
log() [2/2]
void nidas::util::LogContext::log (const std::string & msg) const inline
Convenience method which writes the given message to the current Logger instance, passing this object as the LogContext instance.
static LogContext lp(LOG_INFO);
if (lp.active())
{
    LogMessage msg;
    msg << "complicated info output...";
    lp.log(msg);
}
References nidas::util::Logger::getInstance(), and nidas::util::Logger::msg().
Referenced by nidas::dynld::raf::SyncRecordSource::allocateRecord(), nidas::dynld::SampleInputStream::closeBlocks(), nidas::core::BadSampleFilter::invalidSampleHeader(), nidas::util::LogMessage::log(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::iss::TiltSensor::process(), nidas::core::CalFile::readCFInclude(), nidas::util::SocketImpl::receive(), nidas::dynld::SampleInputStream::sampleFromHeader(), nidas::core::CharacterSensor::searchSampleScanners(), nidas::dynld::raf::SyncRecordSource::sendSyncRecord(), and nidas::dynld::SampleOutputStream::write().
logLevelToString()
std::string nidas::util::logLevelToString (int)
Convert an integral log level to a string name.
Returns
The name for the given log level, or else "emergency".
Referenced by nidas::util::LogContext::levelName().
operator<<() [1/2]
template<typename T > LogMessage & nidas::util::LogMessage::operator<< (const T & t) inline
Everything streamed to a LogMessage is passed on to the underlying ostringstream, including ostream manipulators.
References nidas::util::LogMessage::msg.
operator<<() [2/2]
LogMessage& nidas::util::operator<< (LogMessage & logmsg, LogMessage &(*)(LogMessage &) op) inline
Template to call LogMessage manipulators like endlog when streamed to a LogMessage.
stringToLogLevel()
int nidas::util::stringToLogLevel (const std::string & slevel)
Convert the name of a log level to its integer value.
Returns
The log level value, or -1 if the name is not recognized.
References nidas::util::LOGGER_NONE, and nidas::util::LOGGER_WARNING.
Referenced by LogSchemeFromDOMElement(), and parse_log_level().
Variable Documentation
LOGGER_ALERT
const int nidas::util::LOGGER_ALERT = LOG_ALERT
LOGGER_CRIT
const int nidas::util::LOGGER_CRIT = LOG_CRIT
LOGGER_CRITICAL
const int nidas::util::LOGGER_CRITICAL = LOG_CRIT
LOGGER_DEBUG
const int nidas::util::LOGGER_DEBUG = LOG_DEBUG
Referenced by main().
LOGGER_EMERGENCY
const int nidas::util::LOGGER_EMERGENCY = LOG_EMERG
LOGGER_ERR
const int nidas::util::LOGGER_ERR = LOG_ERR
LOGGER_ERROR
const int nidas::util::LOGGER_ERROR = LOG_ERR
LOGGER_INFO
const int nidas::util::LOGGER_INFO = LOG_INFO
Referenced by main(), nidas::core::NidasApp::setupLogScheme(), nidas::dynld::isff::ATIK_Sonic::~ATIK_Sonic(), nidas::core::CharacterSensor::~CharacterSensor(), nidas::dynld::isff::CSAT3_Sonic::~CSAT3_Sonic(), nidas::dynld::isff::CSI_CRX_Binary::~CSI_CRX_Binary(), nidas::dynld::isff::CSI_IRGA_Sonic::~CSI_IRGA_Sonic(), and nidas::dynld::raf::DSMArincSensor::~DSMArincSensor().
LOGGER_NONE
const int nidas::util::LOGGER_NONE = LOG_EMERG-1
Referenced by nidas::util::LogScheme::logLevel(), parse_log_level(), and nidas::util::stringToLogLevel().
LOGGER_NOTICE
const int nidas::util::LOGGER_NOTICE = LOG_NOTICE
LOGGER_PROBLEM
const int nidas::util::LOGGER_PROBLEM = LOG_ERR
LOGGER_VERBOSE
const int nidas::util::LOGGER_VERBOSE = LOG_DEBUG+1
Referenced by nidas::util::Logger::msg_locked(), and parse_log_level().
LOGGER_WARNING
const int nidas::util::LOGGER_WARNING = LOG_WARNING
Referenced by get_scheme(), main(), and nidas::util::stringToLogLevel().