nidas: nidas::core::XMLCachingParser Class Reference
nidas::core::XMLCachingParser Class Reference
Derived class of XMLParser that keeps its DOMDocuments when parsing an XML disk file, and returns the cached DOMDocument if the file hasn't changed.
#include <XMLParser.h>
Public Member Functions
xercesc::DOMDocument * parse (const std::string &xmlFile)
Parse from a file.
void setDOMValidation (bool val)
DOMBuilder::setFilter is not yet implemented in xerces c++ 2.6.0 void setFilter(xercesc::DOMBuilderFilter* filter)
void setDOMValidateIfSchema (bool val)
Enable/disable schema validation.
void setDOMNamespaces (bool val)
Enable/disable namespace processing.
void setXercesSchema (bool val)
Enable/disable schema support.
void setXercesSchemaFullChecking (bool val)
Enable/disable full schema constraint checking, including checking which may be time-consuming or memory intensive.
void setDOMDatatypeNormalization (bool val)
Enable/disable datatype normalization.
void setXercesUserAdoptsDOMDocument (bool val)
Control who owns DOMDocument pointer.
void setXercesHandleMultipleImports (bool val)
void setXercesDoXInclude (bool val)
xercesc::DOMDocument * parse (const std::string &xmlFile, bool verbose=true)
xercesc::DOMDocument * parse (xercesc::InputSource &source)
Static Public Member Functions
static XMLCachingParser * getInstance ()
static void destroyInstance ()
static time_t getFileModTime (const std::string &name)
Parse from an InputSource.
Protected Member Functions
XMLCachingParser ()
~XMLCachingParser ()
Protected Attributes
std::map< std::string, time_t > _modTimeCache
std::map< std::string, xercesc::DOMDocument * > _docCache
nidas::util::Mutex _cacheLock
xercesc::DOMImplementation * _impl
xercesc::DOMBuilder * _parser
XMLErrorHandler _errorHandler
Static Protected Attributes
static XMLCachingParser * _instance = 0
static nidas::util::Mutex _instanceLock
Private Member Functions
XMLCachingParser (const XMLCachingParser &)
No copying.
XMLCachingParser & operator= (const XMLCachingParser &)
No assignment.
Detailed Description
Derived class of XMLParser that keeps its DOMDocuments when parsing an XML disk file, and returns the cached DOMDocument if the file hasn't changed.
Constructor & Destructor Documentation
XMLCachingParser() [1/2]
XMLCachingParser::XMLCachingParser () protected
Exceptions
nidas::core::XMLException
Referenced by getInstance().
~XMLCachingParser()
XMLCachingParser::~XMLCachingParser () protected
References _cacheLock, and _docCache.
XMLCachingParser() [2/2]
nidas::core::XMLCachingParser::XMLCachingParser (const XMLCachingParser &) private
No copying.
Member Function Documentation
destroyInstance()
void XMLCachingParser::destroyInstance () static
References _instance, and _instanceLock.
Referenced by nidas::core::DSMServerApp::main().
getFileModTime()
time_t XMLCachingParser::getFileModTime (const std::string & name) static
Parse from an InputSource.
This is not cached.
Exceptions
nidas::util::IOException
Referenced by parse().
getInstance()
XMLCachingParser * XMLCachingParser::getInstance () static
Exceptions
nidas::core::XMLException
References _instance, _instanceLock, and XMLCachingParser().
Referenced by nidas::core::DSMServerApp::parseXMLConfigFile(), and nidas::dynld::XMLConfigService::Worker::run().
operator=()
XMLCachingParser& nidas::core::XMLCachingParser::operator= (const XMLCachingParser &) private
No assignment.
parse() [1/3]
xercesc::DOMDocument * XMLCachingParser::parse (const std::string & xmlFile)
Parse from a file.
This will return the DOMDocument pointer of the a previous parse result if the file has not been modified since the last time it was parsed. The pointer to the DOMDocuemnt is owned by XMLCachingParser and the user should not call doc->release();
Exceptions
nidas::core::XMLException
nidas::util::IOException
References _cacheLock, _docCache, _modTimeCache, getFileModTime(), and nidas::core::XMLParser::parse().
Referenced by nidas::core::DSMServerApp::parseXMLConfigFile(), and nidas::dynld::XMLConfigService::Worker::run().
parse() [2/3]
xercesc::DOMDocument * XMLParser::parse (const std::string & xmlFile, bool verbose = true) inherited
Exceptions
nidas::core::XMLException
References nidas::core::XMLParser::_errorHandler, nidas::core::XMLParser::_parser, nidas::core::XMLErrorHandler::getXMLException(), NLOG, nidas::core::XMLErrorHandler::resetErrors(), and verbose.
Referenced by PConfig::loadFile(), main(), parse(), nidas::core::ProjectConfigs::parseXML(), nidas::core::Datasets::parseXML(), and PacketDecode::run().
parse() [3/3]
xercesc::DOMDocument * XMLParser::parse (xercesc::InputSource & source) inherited
Exceptions
nidas::core::XMLException
References nidas::core::XMLParser::_errorHandler, nidas::core::XMLParser::_parser, nidas::core::XMLErrorHandler::getXMLException(), and nidas::core::XMLErrorHandler::resetErrors().
setDOMDatatypeNormalization()
void XMLParser::setDOMDatatypeNormalization (bool val) inherited
Enable/disable datatype normalization.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true let the validation process do its datatype normalization that is defined in the used schema language. If false disable datatype normalization. The XML 1.0 attribute value normalization always occurs though.
Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMNamespaces()
void XMLParser::setDOMNamespaces (bool val) inherited
Enable/disable namespace processing.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true perform namespace processing. Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMValidateIfSchema()
void XMLParser::setDOMValidateIfSchema (bool val) inherited
Enable/disable schema validation.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true the parser will validate the document only if a grammar is specified. If false validation is determined by the state of the validation feature, see setDOMValidation().
Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMValidation()
void XMLParser::setDOMValidation (bool val) inherited
DOMBuilder::setFilter is not yet implemented in xerces c++ 2.6.0 void setFilter(xercesc::DOMBuilderFilter* filter)
Enable/disable validation. See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val Boolean value specifying whether to report all validation errors. Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesDoXInclude()
void XMLParser::setXercesDoXInclude (bool val) inherited
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesHandleMultipleImports()
void XMLParser::setXercesHandleMultipleImports (bool val) inherited
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesSchema()
void XMLParser::setXercesSchema (bool val) inherited
Enable/disable schema support.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true enable the parser's schema support. Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesSchemaFullChecking()
void XMLParser::setXercesSchemaFullChecking (bool val) inherited
Enable/disable full schema constraint checking, including checking which may be time-consuming or memory intensive.
Currently, particle unique attribution constraint checking and particle derivation restriction checking are controlled by this option.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true enable schema constraint checking. Default: false.
References nidas::core::XMLParser::_parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesUserAdoptsDOMDocument()
void XMLParser::setXercesUserAdoptsDOMDocument (bool val) inherited
Control who owns DOMDocument pointer.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true the caller will adopt the DOMDocument that is returned from the parse method and thus is responsible to call DOMDocument::release() to release the associated memory. The parser will not release it. The ownership is transferred from the parser to the caller. If false the returned DOMDocument from the parse method is owned by the parser and thus will be deleted when the parser is released.
References nidas::core::XMLParser::_parser.
Referenced by nidas::core::XMLParser::XMLParser().
Member Data Documentation
_cacheLock
nidas::util::Mutex nidas::core::XMLCachingParser::_cacheLock protected
Referenced by parse(), and ~XMLCachingParser().
_docCache
std::map<std::string,xercesc::DOMDocument*> nidas::core::XMLCachingParser::_docCache protected
Referenced by parse(), and ~XMLCachingParser().
_errorHandler
XMLErrorHandler nidas::core::XMLParser::_errorHandler protected inherited
Referenced by nidas::core::XMLParser::parse(), and nidas::core::XMLParser::XMLParser().
_impl
xercesc::DOMImplementation* nidas::core::XMLParser::_impl protected inherited
Referenced by nidas::core::XMLParser::XMLParser().
_instance
XMLCachingParser * XMLCachingParser::_instance = 0 static protected
Referenced by destroyInstance(), and getInstance().
_instanceLock
n_u::Mutex XMLCachingParser::_instanceLock static protected
Referenced by destroyInstance(), and getInstance().
_modTimeCache
std::map<std::string,time_t> nidas::core::XMLCachingParser::_modTimeCache protected
Referenced by parse().
_parser
xercesc::DOMBuilder* nidas::core::XMLParser::_parser protected inherited
Referenced by nidas::core::XMLParser::parse(), nidas::core::XMLParser::setDOMDatatypeNormalization(), nidas::core::XMLParser::setDOMNamespaces(), nidas::core::XMLParser::setDOMValidateIfSchema(), nidas::core::XMLParser::setDOMValidation(), nidas::core::XMLParser::setXercesDoXInclude(), nidas::core::XMLParser::setXercesHandleMultipleImports(), nidas::core::XMLParser::setXercesSchema(), nidas::core::XMLParser::setXercesSchemaFullChecking(), nidas::core::XMLParser::setXercesUserAdoptsDOMDocument(), nidas::core::XMLParser::XMLParser(), and nidas::core::XMLParser::~XMLParser().
The documentation for this class was generated from the following files:
nidas/core/XMLParser.h
nidas/core/XMLParser.cc