nidas: StatsProcess Class Reference
StatsProcess Class Reference
Public Member Functions
StatsProcess ()
int parseRunstring (int argc, char **argv)
int run () throw ()
int usage (const char *argv0)
bool getFillGaps () const
int listOutputSamples ()
Dataset getDataset ()
void requireConfigsXML ()
StatisticsProcessor * getStatisticsProcessor (Project &project, const DSMConfig *&matchedDSM, DSMServer *&matchedServer)
Static Public Member Functions
static int main (int argc, char **argv) throw ()
Private Attributes
string _xmlFileName
string _dsmName
string _configName
float _sorterLength
bool _daemonMode
n_u::UTime _startTime
n_u::UTime _endTime
int _niceValue
int _period
string _configsXMLName
bool _fillGaps
bool _doListOutputSamples
vector< unsigned int > _selectedOutputSampleIds
string _datasetName
NidasApp _app
NidasAppArg NiceValue
NidasAppArg SorterLength
NidasAppArg Period
NidasAppArg DaemonMode
NidasAppArg SetDSM
NidasAppArg DSMName
BadSampleFilterArg FilterArg
Static Private Attributes
static const int DEFAULT_PORT = 30000
static const int DEFAULT_PERIOD = 300
Constructor & Destructor Documentation
StatsProcess()
StatsProcess::StatsProcess ()
Member Function Documentation
getDataset()
Dataset StatsProcess::getDataset ()
References _datasetName, _period, nidas::util::Process::expandEnvVars(), nidas::core::Datasets::getDataset(), nidas::core::Dataset::getResolutionSecs(), nidas::core::Datasets::parseXML(), and nidas::core::Dataset::putenv().
Referenced by run().
getFillGaps()
bool StatsProcess::getFillGaps () const inline
Referenced by run().
getStatisticsProcessor()
StatisticsProcessor * StatsProcess::getStatisticsProcessor (Project & project, const DSMConfig *& matchedDSM, DSMServer *& matchedServer)
References _app, _dsmName, _period, nidas::core::Project::findDSM(), nidas::core::Project::findServers(), nidas::core::NidasApp::getHostName(), nidas::dynld::StatisticsProcessor::getPeriod(), nidas::core::DSMConfig::getProcessorIterator(), nidas::core::DSMServer::getProcessorIterator(), nidas::core::ProcessorIterator::hasNext(), nidas::core::ProcessorIterator::next(), PLOG, and VLOG.
Referenced by listOutputSamples(), and run().
listOutputSamples()
int StatsProcess::listOutputSamples ()
References _configName, _configsXMLName, _startTime, _xmlFileName, nidas::util::Process::expandEnvVars(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfigs::getConfig(), nidas::core::Variable::getName(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::getSampleId(), nidas::core::SampleTag::getSpSId(), getStatisticsProcessor(), nidas::core::SampleTag::getVariables(), ILOG, nidas::core::ProjectConfig::initProject(), nidas::core::ProjectConfigs::parseXML(), nidas::core::parseXMLConfigFile(), PLOG, requireConfigsXML(), nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
Referenced by main().
main()
int StatsProcess::main (int argc, char ** argv) throw () static
References _doListOutputSamples, listOutputSamples(), parseRunstring(), run(), nidas::core::NidasApp::setupSignals(), and nidas::util::Exception::what().
Referenced by main().
parseRunstring()
int StatsProcess::parseRunstring (int argc, char ** argv)
References _app, _configName, _daemonMode, _doListOutputSamples, _dsmName, _endTime, _fillGaps, _niceValue, _period, _selectedOutputSampleIds, _sorterLength, _startTime, _xmlFileName, nidas::util::LogContext::active(), nidas::core::NidasAppInputFilesArg::allowFiles, nidas::core::NidasAppInputFilesArg::allowSockets, nidas::core::NidasApp::allowUnrecognized(), nidas::core::NidasAppArgv::argc, nidas::core::NidasAppArgv::argv, nidas::core::NidasAppArg::asBool(), nidas::core::NidasAppArg::asFloat(), nidas::core::NidasAppArg::asInt(), DaemonMode, nidas::core::NidasApp::dataFileNames(), nidas::core::NidasApp::DatasetName, DEFAULT_PORT, DSMName, nidas::core::NidasApp::enableArguments(), nidas::core::NidasApp::EndTime, FilterArg, nidas::core::NidasApp::getEndTime(), nidas::core::NidasApp::getShortHostName(), nidas::core::NidasApp::getStartTime(), nidas::core::NidasAppArg::getValue(), nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::Hostname, nidas::core::NidasApp::InputFiles, LOG_DEBUG, nidas::core::NidasApp::loggingArgs(), NiceValue, nidas::core::NidasApp::parseArgs(), nidas::core::NidasApp::parseInputs(), Period, nidas::core::NidasAppInputFilesArg::setDefaultInput(), SetDSM, nidas::core::NidasAppArg::setFlags(), nidas::core::NidasApp::socketAddress(), SorterLength, nidas::core::NidasApp::StartTime, nidas::util::UTime::toUsecs(), nidas::core::NidasAppArgv::unparsedArgs(), usage(), USECS_PER_DAY, nidas::core::NidasApp::Version, nidas::core::NidasApp::XmlHeaderFile, and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
requireConfigsXML()
void StatsProcess::requireConfigsXML () inline
Referenced by listOutputSamples(), and run().
run()
int StatsProcess::run () throw ()
References _app, _configName, _configsXMLName, _daemonMode, _datasetName, _dsmName, _endTime, _niceValue, _selectedOutputSampleIds, _sorterLength, _startTime, _xmlFileName, nidas::dynld::SampleInputStream::addSampleTag(), nidas::core::SampleSource::addSampleTag(), nidas::core::FileSet::clone(), nidas::dynld::SampleInputStream::close(), nidas::core::SamplePipeline::connect(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::NidasApp::dataFileNames(), nidas::core::SamplePipeline::disconnect(), nidas::dynld::StatisticsProcessor::disconnectSource(), DLOG, nidas::util::Process::expandEnvVars(), FilterArg, nidas::core::Project::findSampleOutputStreamFileSets(), nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::core::SamplePipeline::flush(), nidas::util::UTime::format(), nidas::core::Project::fromDOMElement(), nidas::core::SampleInputHeader::getArchiveVersion(), nidas::core::ProjectConfig::getBeginTime(), nidas::core::ProjectConfigs::getConfig(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::SampleInputHeader::getConfigVersion(), getDataset(), nidas::core::ProjectConfig::getEndTime(), nidas::core::FileSet::getFileSet(), getFillGaps(), nidas::core::BadSampleFilterArg::getFilter(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::SampleIOProcessor::getOutputs(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::NidasApp::getProcessName(), nidas::core::SampleInputHeader::getProjectName(), nidas::core::DSMSensor::getRawSampleTag(), nidas::util::Socket::getRemoteSocketAddress(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::DSMServer::getSensorIterator(), nidas::core::SampleInputHeader::getSoftwareVersion(), getStatisticsProcessor(), nidas::core::SampleInputHeader::getSystemName(), nidas::core::ProjectConfig::getXMLName(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), ILOG, nidas::core::DSMSensor::init(), nidas::core::ProjectConfig::initProject(), nidas::core::SamplePipeline::interrupt(), nidas::core::NidasApp::interrupted(), nidas::core::SamplePipeline::join(), nidas::core::SensorIterator::next(), nidas::core::SampleTagIterator::next(), nidas::core::ProjectConfigs::parseXML(), nidas::core::parseXMLConfigFile(), PLOG, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSamples(), nidas::core::SampleOutput::requestConnection(), requireConfigsXML(), nidas::dynld::SampleInputStream::search(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), nidas::dynld::SampleInputStream::setBadSampleFilter(), nidas::core::Project::setConfigName(), nidas::core::Project::setDataset(), nidas::core::BadSampleFilter::setDefaultTimeRange(), nidas::core::FileSet::setEndTime(), nidas::dynld::StatisticsProcessor::setEndTime(), nidas::dynld::StatisticsProcessor::setFillGaps(), nidas::util::Socket::setKeepAliveIdleSecs(), nidas::core::SamplePipeline::setProcHeapMax(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRawHeapMax(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), nidas::core::FileSet::setStartTime(), nidas::dynld::StatisticsProcessor::setStartTime(), nidas::core::NidasApp::setupDaemon(), nidas::core::NidasApp::socketAddress(), nidas::util::SocketAddress::toString(), nidas::util::UTime::toUsecs(), nidas::util::Exception::what(), and WLOG.
Referenced by main().
usage()
int StatsProcess::usage (const char * argv0)
References _app, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
_app
NidasApp StatsProcess::_app private
Referenced by getStatisticsProcessor(), parseRunstring(), run(), and usage().
_configName
string StatsProcess::_configName private
Referenced by listOutputSamples(), parseRunstring(), and run().
_configsXMLName
string StatsProcess::_configsXMLName private
Referenced by listOutputSamples(), and run().
_daemonMode
bool StatsProcess::_daemonMode private
Referenced by parseRunstring(), and run().
_datasetName
string StatsProcess::_datasetName private
Referenced by getDataset(), and run().
_doListOutputSamples
bool StatsProcess::_doListOutputSamples private
Referenced by main(), and parseRunstring().
_dsmName
string StatsProcess::_dsmName private
Referenced by getStatisticsProcessor(), parseRunstring(), and run().
_endTime
n_u::UTime StatsProcess::_endTime private
Referenced by parseRunstring(), and run().
_fillGaps
bool StatsProcess::_fillGaps private
Referenced by parseRunstring().
_niceValue
int StatsProcess::_niceValue private
Referenced by parseRunstring(), and run().
_period
int StatsProcess::_period private
Referenced by getDataset(), getStatisticsProcessor(), and parseRunstring().
_selectedOutputSampleIds
vector<unsigned int> StatsProcess::_selectedOutputSampleIds private
Referenced by parseRunstring(), and run().
_sorterLength
float StatsProcess::_sorterLength private
Referenced by parseRunstring(), and run().
_startTime
n_u::UTime StatsProcess::_startTime private
Referenced by listOutputSamples(), parseRunstring(), and run().
_xmlFileName
string StatsProcess::_xmlFileName private
Referenced by listOutputSamples(), parseRunstring(), and run().
DaemonMode
NidasAppArg StatsProcess::DaemonMode private
Referenced by parseRunstring().
DEFAULT_PERIOD
const int StatsProcess::DEFAULT_PERIOD = 300 static private
DEFAULT_PORT
const int StatsProcess::DEFAULT_PORT = 30000 static private
Referenced by parseRunstring().
DSMName
NidasAppArg StatsProcess::DSMName private
Referenced by parseRunstring().
FilterArg
BadSampleFilterArg StatsProcess::FilterArg private
Referenced by parseRunstring(), and run().
NiceValue
NidasAppArg StatsProcess::NiceValue private
Referenced by parseRunstring().
Period
NidasAppArg StatsProcess::Period private
Referenced by parseRunstring().
SetDSM
NidasAppArg StatsProcess::SetDSM private
Referenced by parseRunstring().
SorterLength
NidasAppArg StatsProcess::SorterLength private
Referenced by parseRunstring().
The documentation for this class was generated from the following file:
nidas/apps/statsproc.cc