nidas: nidas::core::NearestResamplerAtRate Class Reference
nidas::core::NearestResamplerAtRate Class Reference
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
#include <NearestResamplerAtRate.h>
Public Member Functions
NearestResamplerAtRate (const std::vector< const Variable * > &vars, bool nansVariable=true)
Constructor.
NearestResamplerAtRate (const std::vector< Variable * > &vars, bool nansVariable=true)
~NearestResamplerAtRate ()
void setRate (double val)
Set the requested output rate, in Hz.
double getRate () const
void setMiddleTimeTags (bool val)
If true, generate output timetags that are the middle of the requested output periods.
bool getMiddleTimeTags () const
void setFillGaps (bool val)
Should output records of all missing data (nans), be generated, or just discarded.
bool getFillGaps () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const SampleTag * > getSampleTags () const
Get the SampleTag of my merged output sample.
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of Resampler::flush().
const SampleStats & getSampleStats () const
void connect (SampleSource *input)
Connect the resampler to a SampleSource.
void disconnect (SampleSource *input) throw ()
bool receive (const Sample *s) throw ()
Method called to pass a sample to this client.
Private Member Functions
void ctorCommon (const std::vector< const Variable * > &vars, bool nansVariable)
Common tasks of constructors.
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
void sendSample (dsm_time_t) throw ()
NearestResamplerAtRate & operator= (const NearestResamplerAtRate &)
No assignment.
NearestResamplerAtRate (const NearestResamplerAtRate &x)
No copy.
Private Attributes
SampleSourceSupport _source
SampleTag _outSample
std::vector< Variable * > _reqVars
Requested variables.
std::map< Variable *, unsigned int > _outVarIndices
Index of each requested output variable in the output sample.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _inmap
For each input sample, first index of variable data values to be read.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _lenmap
For each input sample, length of variables to read.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _outmap
For each input sample, index into output sample of each variable.
int _ndataValues
int _outlen
double _rate
int _deltatUsec
The output deltaT, 1/rate in microseconds.
int _deltatUsecD10
DeltaT over 10.
int _deltatUsecD2
DeltaT over 2.
bool _exactDeltatUsec
True if simple integer math is used to increment output sample time tags.
bool _middleTimeTags
If true, generate output timetags that are the middle of the requested output periods.
dsm_time_t _outputTT
dsm_time_t _nextOutputTT
dsm_time_t * _prevTT
dsm_time_t * _nearTT
float * _prevData
float * _nearData
int * _samplesSinceOutput
SampleT< float > * _osamp
bool _fillGaps
std::map< dsm_sample_id_t, unsigned int > _ttOutOfOrder
Detailed Description
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
The output sample time tags will be evenly spaced at the given rate, and values of variables are merged into the output sample by associating those values with the nearest time tag to the output time tags.
The only requirement is that the samples which are fed to the receive() method should be sorted in time. It they aren't sorted some data will be lost. NearestResamplerAtRate does not need to know sampling rates, and the sampling rates of the input variables, including the master variable, may vary.
This resampler operates in two modes, based on the value of the setMiddleTimeTags() attribute.
If getMiddleTimeTags() is true, generate output timetags that are at the middle of the requested output periods. For example, for a rate=20, deltaT=0.05 sec, the output timetags will be 00:00:00.025, 00:00:00.075, etc. The output sample at 00:00:00.025 contains the nearest input values from the time period centered at 00:00:00.025.
If getMiddleTimeTags() is false, the output time tags for the above example would be 00:00:00.00, 00:00:00.05, etc. The output sample at 00:00:00.00 contains the nearest input values from the time period centered at 00:00:00.00.
Because of assumed input timetag jitter (inaccuracy), the nearest point matching algorithm is a bit forgiving. When matching for the nearest points to time t, input samples will be matched whose time tags are between t - 0.9*deltatT <= inputTimeTag <= t + 0.9*deltaT. If more than one input sample lies in the window, then the nearest one is used. This input window is of size 1.8 * deltaT, rather than 1.0 * deltaT, which is what one might expect. Therefore an input point could be matched with two output points. In this example, it is possible that an output sample at 00:00:00.025 could contain an input value from the previous day.
Constructor & Destructor Documentation
NearestResamplerAtRate() [1/3]
NearestResamplerAtRate::NearestResamplerAtRate (const std::vector< const Variable * > & vars, bool nansVariable = true)
Constructor.
References ctorCommon().
NearestResamplerAtRate() [2/3]
NearestResamplerAtRate::NearestResamplerAtRate (const std::vector< Variable * > & vars, bool nansVariable = true)
References ctorCommon().
~NearestResamplerAtRate()
NearestResamplerAtRate::~NearestResamplerAtRate ()
References _nearData, _nearTT, _osamp, _prevData, _prevTT, _reqVars, _samplesSinceOutput, and nidas::core::SampleT< DataT >::freeReference().
NearestResamplerAtRate() [3/3]
nidas::core::NearestResamplerAtRate::NearestResamplerAtRate (const NearestResamplerAtRate & x) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::core::NearestResamplerAtRate::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleClientForTag()
void nidas::core::NearestResamplerAtRate::addSampleClientForTag (SampleClient * client, const SampleTag *) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleTag()
void nidas::core::NearestResamplerAtRate::addSampleTag (const SampleTag * tag) throw () inline private virtual
Add a SampleTag to this SampleSource.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleTag().
Referenced by ctorCommon().
connect()
void NearestResamplerAtRate::connect (SampleSource * input) virtual
Connect the resampler to a SampleSource.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::Resampler.
References _inmap, _lenmap, _outmap, _outVarIndices, _reqVars, nidas::core::SampleSource::addSampleClientForTag(), GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getDataIndex(), nidas::core::SampleTag::getDSMId(), nidas::core::SampleTag::getId(), nidas::core::Variable::getLength(), nidas::core::Variable::getName(), nidas::core::Variable::getSampleTag(), nidas::core::SampleSource::getSampleTags(), nidas::core::SampleTag::getSpSId(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), nidas::core::VariableIterator::next(), and WLOG.
ctorCommon()
void NearestResamplerAtRate::ctorCommon (const std::vector< const Variable * > & vars, bool nansVariable) private
Common tasks of constructors.
References _ndataValues, _nearData, _nearTT, _nextOutputTT, _outlen, _outputTT, _outSample, _outVarIndices, _prevData, _prevTT, _reqVars, _samplesSinceOutput, addSampleTag(), nidas::core::SampleTag::addVariable(), nidas::core::floatNAN, GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getDSMId(), nidas::core::SampleTag::getId(), nidas::core::Project::getInstance(), nidas::core::Variable::getLength(), nidas::core::Variable::getName(), nidas::core::Variable::getSampleTag(), nidas::core::SampleTag::getSpSId(), nidas::core::Project::getUniqueSampleId(), nidas::core::SampleTag::setDSMId(), nidas::core::Variable::setName(), setRate(), nidas::core::SampleTag::setSampleId(), nidas::core::Variable::setType(), nidas::core::Variable::setUnits(), and nidas::core::Variable::WEIGHT.
Referenced by NearestResamplerAtRate().
disconnect()
void NearestResamplerAtRate::disconnect (SampleSource * input) throw () virtual
Implements nidas::core::Resampler.
flush()
void NearestResamplerAtRate::flush () throw () virtual
Implementation of Resampler::flush().
Implements nidas::core::Resampler.
References _nextOutputTT, and sendSample().
getClientCount()
int nidas::core::NearestResamplerAtRate::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getClientCount().
getFillGaps()
bool nidas::core::NearestResamplerAtRate::getFillGaps () const inline
References _fillGaps.
getMiddleTimeTags()
bool nidas::core::NearestResamplerAtRate::getMiddleTimeTags () const inline
References _middleTimeTags.
getProcessedSampleSource()
SampleSource* nidas::core::NearestResamplerAtRate::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _source.
getRate()
double nidas::core::NearestResamplerAtRate::getRate () const inline
References _rate.
getRawSampleSource()
SampleSource* nidas::core::NearestResamplerAtRate::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getSampleStats()
const SampleStats& nidas::core::NearestResamplerAtRate::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::NearestResamplerAtRate::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::NearestResamplerAtRate::getSampleTags () const inline virtual
Get the SampleTag of my merged output sample.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTags().
operator=()
NearestResamplerAtRate& nidas::core::NearestResamplerAtRate::operator= (const NearestResamplerAtRate &) private
No assignment.
receive()
bool NearestResamplerAtRate::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::util::UTime::format(), GET_DSM_ID, GET_SHORT_ID, GET_SPS_ID, USECS_PER_SEC, and WLOG.
removeSampleClient()
void nidas::core::NearestResamplerAtRate::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleClientForTag()
void nidas::core::NearestResamplerAtRate::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleTag()
void nidas::core::NearestResamplerAtRate::removeSampleTag (const SampleTag *) throw () inline private virtual
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleTag().
sendSample()
void NearestResamplerAtRate::sendSample (dsm_time_t tt) throw () private
References nidas::core::floatNAN, and USECS_PER_SEC.
Referenced by flush().
setFillGaps()
void nidas::core::NearestResamplerAtRate::setFillGaps (bool val) inline
Should output records of all missing data (nans), be generated, or just discarded.
References _fillGaps.
Referenced by DataPrep::run().
setMiddleTimeTags()
void nidas::core::NearestResamplerAtRate::setMiddleTimeTags (bool val) inline
If true, generate output timetags that are the middle of the requested output periods.
For example, for a rate=20, deltaT=0.05 sec, the output timetags will be 00:00:00.025, 00:00:00.075, etc. The sample at 00:00:00.025 contains the nearest input values from the time period centered at 00:00:00.025 If false, the output time tags for the above example would be 00:00:00.00, 00:00:00.05, etc. The sample at 00:00:00.00 contains the nearest input values from the time period centerd at 00:00:00.00, i.e. points from the previous day could be used.
References _middleTimeTags.
Referenced by DataPrep::run().
setRate()
void NearestResamplerAtRate::setRate (double val)
Set the requested output rate, in Hz.
For rates < 1 it is best to choose a value such that 10^6/rate is an integer. If you really want rate=1/3 Hz, specify rate to 7 significant figures, 0.3333333, and you will avoid round off errors in the time tag. Output rates > 1 should be integers, or of a value with enough significant figures such that 10^6/rate is an integer. Support for other rates could be added if (really) necessary.
References _deltatUsec, _deltatUsecD10, _deltatUsecD2, _exactDeltatUsec, _rate, and USECS_PER_SEC.
Referenced by ctorCommon(), and DataPrep::run().
Member Data Documentation
_deltatUsec
int nidas::core::NearestResamplerAtRate::_deltatUsec private
The output deltaT, 1/rate in microseconds.
Referenced by setRate().
_deltatUsecD10
int nidas::core::NearestResamplerAtRate::_deltatUsecD10 private
DeltaT over 10.
A fudge factur used for doing nearest point alignments.
Referenced by setRate().
_deltatUsecD2
int nidas::core::NearestResamplerAtRate::_deltatUsecD2 private
DeltaT over 2.
Referenced by setRate().
_exactDeltatUsec
bool nidas::core::NearestResamplerAtRate::_exactDeltatUsec private
True if simple integer math is used to increment output sample time tags.
This will be the case if rate <= 1.0 or 1/rate is within 0.02 microseconds if an integer.
Referenced by setRate().
_fillGaps
bool nidas::core::NearestResamplerAtRate::_fillGaps private
Referenced by getFillGaps(), and setFillGaps().
_inmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResamplerAtRate::_inmap private
For each input sample, first index of variable data values to be read.
Referenced by connect().
_lenmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResamplerAtRate::_lenmap private
For each input sample, length of variables to read.
Referenced by connect().
_middleTimeTags
bool nidas::core::NearestResamplerAtRate::_middleTimeTags private
If true, generate output timetags that are the middle of the requested output periods.
For example, for a rate=20, deltaT=0.05 sec, the output timetags will be 00:00:00.025, 00:00:00.075, etc. The sample at 00:00:00.025 contains the nearest input values from the period 00:00:00.0 to 00:00:00.05 If false, the output time tags for the above example would be 00:00:00.00, 00:00:00.05, etc. The sample at 00:00:00.00 contains the nearest input values from 23:59:59.975 to 00:00:00.025.
Referenced by getMiddleTimeTags(), and setMiddleTimeTags().
_ndataValues
int nidas::core::NearestResamplerAtRate::_ndataValues private
Referenced by ctorCommon().
_nearData
float* nidas::core::NearestResamplerAtRate::_nearData private
Referenced by ctorCommon(), and ~NearestResamplerAtRate().
_nearTT
dsm_time_t* nidas::core::NearestResamplerAtRate::_nearTT private
Referenced by ctorCommon(), and ~NearestResamplerAtRate().
_nextOutputTT
dsm_time_t nidas::core::NearestResamplerAtRate::_nextOutputTT private
Referenced by ctorCommon(), and flush().
_osamp
SampleT<float>* nidas::core::NearestResamplerAtRate::_osamp private
Referenced by ~NearestResamplerAtRate().
_outlen
int nidas::core::NearestResamplerAtRate::_outlen private
Referenced by ctorCommon().
_outmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::NearestResamplerAtRate::_outmap private
For each input sample, index into output sample of each variable.
Referenced by connect().
_outputTT
dsm_time_t nidas::core::NearestResamplerAtRate::_outputTT private
Referenced by ctorCommon().
_outSample
SampleTag nidas::core::NearestResamplerAtRate::_outSample private
Referenced by ctorCommon().
_outVarIndices
std::map<Variable*,unsigned int> nidas::core::NearestResamplerAtRate::_outVarIndices private
Index of each requested output variable in the output sample.
Referenced by connect(), and ctorCommon().
_prevData
float* nidas::core::NearestResamplerAtRate::_prevData private
Referenced by ctorCommon(), and ~NearestResamplerAtRate().
_prevTT
dsm_time_t* nidas::core::NearestResamplerAtRate::_prevTT private
Referenced by ctorCommon(), and ~NearestResamplerAtRate().
_rate
double nidas::core::NearestResamplerAtRate::_rate private
Referenced by getRate(), and setRate().
_reqVars
std::vector<Variable *> nidas::core::NearestResamplerAtRate::_reqVars private
Requested variables.
Referenced by connect(), ctorCommon(), and ~NearestResamplerAtRate().
_samplesSinceOutput
int* nidas::core::NearestResamplerAtRate::_samplesSinceOutput private
Referenced by ctorCommon(), and ~NearestResamplerAtRate().
_source
SampleSourceSupport nidas::core::NearestResamplerAtRate::_source private
Referenced by addSampleClient(), addSampleClientForTag(), addSampleTag(), getClientCount(), getProcessedSampleSource(), getSampleStats(), getSampleTagIterator(), getSampleTags(), removeSampleClient(), removeSampleClientForTag(), and removeSampleTag().
_ttOutOfOrder
std::map<dsm_sample_id_t,unsigned int> nidas::core::NearestResamplerAtRate::_ttOutOfOrder private
The documentation for this class was generated from the following files:
nidas/core/NearestResamplerAtRate.h
nidas/core/NearestResamplerAtRate.cc