nidas: nidas::core::ServerSocket Class Reference
nidas::core::ServerSocket Class Reference
Implementation of an IOChannel, over a ServerSocket.
#include <Socket.h>
Classes
class ConnectionThread
Public Member Functions
ServerSocket ()
Constructor.
ServerSocket (const nidas::util::SocketAddress &addr)
Constructor.
~ServerSocket ()
ServerSocket * clone () const
Derived classes must provide clone.
void requestConnection (IOChannelRequester *service)
IOChannel * connect ()
const std::string & getName () const
void setName (const std::string &val)
int getFd () const
void setKeepAliveIdleSecs (int val)
Set the value of keepAliveIdleSecs.
int getKeepAliveIdleSecs () const
Return keepAliveIdleSecs for this ServerSocket.
void setNonBlocking (bool val)
The blocking flag that will be set on accepted connections.
bool isNonBlocking () const
size_t read (void *, size_t)
ServerSocket will never be called to do an actual read.
size_t write (const void *, size_t)
ServerSocket should never be called to do an actual write.
size_t write (const struct iovec *, int)
ServerSocket should never be called to do an actual write.
void close ()
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
Static Public Member Functions
static IOChannel * createSocket (const xercesc::DOMElement *)
Create either a Socket or a McSocket from a DOMElement.
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
ServerSocket (const ServerSocket &x)
Copy constructor.
Private Member Functions
ServerSocket & operator= (const ServerSocket &)
No assignment.
Private Attributes
nidas::util::auto_ptr< nidas::util::SocketAddress > _localSockAddr
std::string _name
nidas::util::ServerSocket * _servSock
IOChannelRequester * _iochanRequester
ConnectionThread * _connectionThread
int _keepAliveIdleSecs
bool _nonBlocking
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Implementation of an IOChannel, over a ServerSocket.
Constructor & Destructor Documentation
ServerSocket() [1/3]
ServerSocket::ServerSocket ()
Constructor.
References _localSockAddr, and setName().
Referenced by clone().
ServerSocket() [2/3]
ServerSocket::ServerSocket (const nidas::util::SocketAddress & addr)
Constructor.
References _localSockAddr, and setName().
~ServerSocket()
ServerSocket::~ServerSocket ()
References _connectionThread, _servSock, close(), DLOG, nidas::util::Logger::getInstance(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
ServerSocket() [3/3]
ServerSocket::ServerSocket (const ServerSocket & x) protected
Copy constructor.
Member Function Documentation
clone()
ServerSocket * ServerSocket::clone () const virtual
Derived classes must provide clone.
Implements nidas::core::IOChannel.
References ServerSocket().
close()
void ServerSocket::close () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _connectionThread, _servSock, nidas::util::ServerSocket::close(), and nidas::core::ServerSocket::ConnectionThread::interrupt().
Referenced by nidas::dynld::raf::SyncServer::init(), and ~ServerSocket().
connect()
IOChannel * ServerSocket::connect () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _keepAliveIdleSecs, _localSockAddr, _nonBlocking, _servSock, nidas::util::ServerSocket::accept(), ILOG, nidas::util::Socket::setKeepAliveIdleSecs(), and nidas::core::Socket::setNonBlocking().
Referenced by nidas::dynld::raf::SyncServer::init().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
createSocket()
static IOChannel* nidas::core::ServerSocket::createSocket (const xercesc::DOMElement *) static
Create either a Socket or a McSocket from a DOMElement.
Exceptions
nidas::util::InvalidParameterException
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void ServerSocket::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Process::expandEnvVars(), nidas::core::Socket::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), port, nidas::core::Socket::setKeepAliveIdleSecs(), nidas::core::Socket::setName(), and nidas::core::Socket::setNonBlocking().
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::core::ServerSocket::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _servSock, and nidas::util::ServerSocket::getFd().
getKeepAliveIdleSecs()
int nidas::core::ServerSocket::getKeepAliveIdleSecs () const inline
Return keepAliveIdleSecs for this ServerSocket.
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs.
getName()
const std::string& nidas::core::ServerSocket::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by requestConnection().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
isNewInput()
virtual bool nidas::core::IOChannel::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented in nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::core::IOStream::read(), and nidas::core::IOStream::readUntil().
isNonBlocking()
bool nidas::core::ServerSocket::isNonBlocking () const inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking.
operator=()
ServerSocket& nidas::core::ServerSocket::operator= (const ServerSocket &) private
No assignment.
read()
size_t nidas::core::ServerSocket::read (void * , size_t) inline virtual
ServerSocket will never be called to do an actual read.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
requestConnection()
void ServerSocket::requestConnection (IOChannelRequester * service) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _connectionThread, _iochanRequester, _localSockAddr, _servSock, getName(), ILOG, nidas::util::Thread::isRunning(), nidas::util::Thread::start(), and nidas::util::Exception::what().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setKeepAliveIdleSecs()
void nidas::core::ServerSocket::setKeepAliveIdleSecs (int val) inline
Set the value of keepAliveIdleSecs.
This is set on each accepted socket connection. It does not pertain to the socket which is waiting for connections.
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs.
setName()
void nidas::core::ServerSocket::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by ServerSocket().
setNonBlocking()
void nidas::core::ServerSocket::setNonBlocking (bool val) inline virtual
The blocking flag that will be set on accepted connections.
The ServerSocket itself is always non-blocking.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking.
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
toDOMElement()
xercesc::DOMElement * ServerSocket::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
toDOMParent()
xercesc::DOMElement * ServerSocket::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), and nidas::core::DOMable::toDOMElement().
write() [1/2]
size_t nidas::core::ServerSocket::write (const struct iovec * , int) inline virtual
ServerSocket should never be called to do an actual write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
write() [2/2]
size_t nidas::core::ServerSocket::write (const void * , size_t) inline virtual
ServerSocket should never be called to do an actual write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_connectionThread
ConnectionThread* nidas::core::ServerSocket::_connectionThread private
Referenced by close(), requestConnection(), and ~ServerSocket().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_iochanRequester
IOChannelRequester* nidas::core::ServerSocket::_iochanRequester private
Referenced by requestConnection().
_keepAliveIdleSecs
int nidas::core::ServerSocket::_keepAliveIdleSecs private
Referenced by connect(), getKeepAliveIdleSecs(), and setKeepAliveIdleSecs().
_localSockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::ServerSocket::_localSockAddr private
Referenced by connect(), requestConnection(), and ServerSocket().
_name
std::string nidas::core::ServerSocket::_name private
Referenced by getName(), and setName().
_nonBlocking
bool nidas::core::ServerSocket::_nonBlocking private
Referenced by connect(), isNonBlocking(), and setNonBlocking().
_servSock
nidas::util::ServerSocket* nidas::core::ServerSocket::_servSock private
Referenced by close(), connect(), getFd(), requestConnection(), and ~ServerSocket().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/Socket.h
nidas/core/Socket.cc