nidas: nidas/apps/tee_tty.cc File Reference
tee_tty.cc File Reference
#include <nidas/Config.h>
#include <nidas/util/SerialPort.h>
#include <nidas/util/SerialOptions.h>
#include <nidas/util/UTime.h>
#include <nidas/util/Logger.h>
#include <linux/tty.h>
#include <vector>
#include <list>
#include <sched.h>
#include <signal.h>
#include <cstdlib>
Classes
class TeeTTy
Functions
static void sigAction (int sig, siginfo_t *siginfo, void *)
int main (int argc, char **argv)
Variables
bool interrupted = false
Function Documentation
main()
int main (int argc, char ** argv)
References TeeTTy::parseRunstring(), and TeeTTy::run().
sigAction()
static void sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted, and NLOG.
Referenced by TeeTTy::setupSignals().
Variable Documentation
interrupted
bool interrupted = false
Referenced by TeeTTy::run(), and sigAction().