nidas: nidas/linux/util/pc104_irq_watchdog.c File Reference
pc104_irq_watchdog.c File Reference
#include <linux/module.h>
#include <linux/timer.h>
#include <linux/spinlock.h>
#include <nidas/linux/isa_bus.h>
#include <nidas/linux/Revision.h>
#include <nidas/linux/klog.h>
Macros
#define REPO_REVISION "unknown"
Functions
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_DESCRIPTION ("NCAR pc104 IRQ watchdog")
MODULE_LICENSE ("GPL")
MODULE_VERSION (REPO_REVISION)
DEFINE_SPINLOCK (pc104_irq_watchdog_spinlock)
static unsigned long pc104_irq_pending (void)
static void pc104_irq_handler (unsigned int irq)
static void pc104_irq_watchdog_timer_func (unsigned long arg)
static void __exit pc104_irq_watchdog_cleanup (void)
static int __init pc104_irq_watchdog_init (void)
module_init (pc104_irq_watchdog_init)
module_exit (pc104_irq_watchdog_cleanup)
Variables
static struct timer_list pc104_irq_watchdog_timer
static unsigned int watchdogDetectedInterrupts = 0
Macro Definition Documentation
REPO_REVISION
#define REPO_REVISION "unknown"
Function Documentation
DEFINE_SPINLOCK()
DEFINE_SPINLOCK (pc104_irq_watchdog_spinlock)
MODULE_AUTHOR()
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_DESCRIPTION()
MODULE_DESCRIPTION ("NCAR pc104 IRQ watchdog")
module_exit()
module_exit (pc104_irq_watchdog_cleanup)
module_init()
module_init (pc104_irq_watchdog_init)
MODULE_LICENSE()
MODULE_LICENSE ("GPL")
MODULE_VERSION()
MODULE_VERSION (REPO_REVISION)
pc104_irq_handler()
static void pc104_irq_handler (unsigned int irq) static
References pc104_irq_pending().
Referenced by pc104_irq_watchdog_timer_func().
pc104_irq_pending()
static unsigned long pc104_irq_pending (void) inline static
Referenced by pc104_irq_handler(), and pc104_irq_watchdog_timer_func().
pc104_irq_watchdog_cleanup()
static void __exit pc104_irq_watchdog_cleanup (void) static
References pc104_irq_watchdog_timer.
pc104_irq_watchdog_init()
static int __init pc104_irq_watchdog_init (void) static
References pc104_irq_watchdog_timer, pc104_irq_watchdog_timer_func(), and REPO_REVISION.
pc104_irq_watchdog_timer_func()
static void pc104_irq_watchdog_timer_func (unsigned long arg) static
References pc104_irq_handler(), pc104_irq_pending(), pc104_irq_watchdog_timer, and watchdogDetectedInterrupts.
Referenced by pc104_irq_watchdog_init().
Variable Documentation
pc104_irq_watchdog_timer
struct timer_list pc104_irq_watchdog_timer static
Referenced by pc104_irq_watchdog_cleanup(), pc104_irq_watchdog_init(), and pc104_irq_watchdog_timer_func().
watchdogDetectedInterrupts
unsigned int watchdogDetectedInterrupts = 0 static
Referenced by pc104_irq_watchdog_timer_func().