nidas: nidas::core::BadSampleFilterArg Class Reference
nidas::core::BadSampleFilterArg Class Reference
BadSampleFilterArg is a NidasAppArg for configuring a BadSampleFilter with filter rules pased to the –filter option.
#include <BadSampleFilter.h>
Public Member Functions
BadSampleFilterArg ()
BadSampleFilter & getFilter ()
virtual bool parse (const ArgVector &argv, int *argi=0)
If argv[argi] matches this argument, then set the flag that was found and also the value if this argument takes a value, and return true.
void setRequired (bool isRequired=true)
Set whether this argument is required.
bool isRequired ()
Return whether this argument is required.
void acceptShortFlag (bool enable)
Set whether short flags are enabled or not.
void addFlag (const std::string &flag)
Add a flag which this argument should accept.
void setFlags (const std::string &flags)
Completely replace the flags which this argument should accept.
operator nidas_app_arglist_t ()
Provide conversion to an arglist so a single NidasAppArg can be passed where an arglist is expected.
std::string usage (const std::string &indent=" ")
Render the usage string for this particular argument, taking into account which flags are enabled.
bool specified ()
Return true if this argument has been filled in from a command-line argument list, such as after a call to NidasApp::parseArgs().
const std::string & getValue ()
If this argument has been parsed from a command line list (specified() returns true), then return the value passed after the flag.
const std::string & getFlag ()
Return the command-line flag which this argument consumed.
bool asBool ()
An argument is true if it is a stand-alone flag and was specified in the arguments, or else if the flag value evaluates to true.
int asInt ()
Parse the argument value as an integer, where the value could be the default if no value has been explicitly parsed with parse().
float asFloat ()
Same as asInt(), except parse the argument value as a float.
bool accept (const std::string &flag)
Return true if the given command-line flag matches one of this argument's flags.
void setUsageString (const std::string &text)
std::string getUsageFlags ()
Return the string of flags accepted by this NidasAppArg according to the acceptShortFlag() setting.
void setDefault (const std::string &dvalue)
std::string getDefault ()
Protected Member Functions
bool single ()
Return true for arguments which are only a single argument.
Protected Attributes
std::string _flags
std::string _syntax
std::string _usage
std::string _default
std::string _arg
std::string _value
bool _enableShortFlag
bool _required
Private Attributes
BadSampleFilter _bsf
Detailed Description
BadSampleFilterArg is a NidasAppArg for configuring a BadSampleFilter with filter rules pased to the –filter option.
Constructor & Destructor Documentation
BadSampleFilterArg()
BadSampleFilterArg::BadSampleFilterArg ()
Member Function Documentation
accept()
bool NidasAppArg::accept (const std::string & flag) inherited
Return true if the given command-line flag matches one of this argument's flags.
References nidas::core::NidasAppArg::_default, nidas::core::NidasAppArg::_enableShortFlag, nidas::core::NidasAppArg::_flags, nidas::core::NidasAppArg::_value, and nidas::core::NidasAppArg::single().
Referenced by parse(), and nidas::core::NidasAppArg::parse().
acceptShortFlag()
void nidas::core::NidasAppArg::acceptShortFlag (bool enable) inline inherited
Set whether short flags are enabled or not.
Pass enable as false to disable short flags and require only long flags instead. By default short flags are enabled.
References nidas::core::NidasAppArg::_enableShortFlag.
Referenced by PacketReader::parseRunstring(), and NidsMerge::parseRunstring().
addFlag()
void NidasAppArg::addFlag (const std::string & flag) inherited
Add a flag which this argument should accept.
Use this to allow an application to accept deprecated flags like -B and -E.
References nidas::core::NidasAppArg::_flags.
asBool()
bool NidasAppArg::asBool () inherited
An argument is true if it is a stand-alone flag and was specified in the arguments, or else if the flag value evaluates to true.
References nidas::core::NidasAppArg::_flags, and nidas::core::NidasAppArg::getValue().
Referenced by TeeI2C::i2c_byte_reads(), DataStats::parseRunstring(), DataPrep::parseRunstring(), StatsProcess::parseRunstring(), TeeI2C::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), nidas::core::DSMServerApp::parseRunstring(), PConfig::parseRunstring(), DataDump::run(), NidsMerge::run(), nidas::core::NidasApp::setupDaemon(), and nidas::core::NidasApp::setupDaemonLogging().
asFloat()
float NidasAppArg::asFloat () inherited
Same as asInt(), except parse the argument value as a float.
References nidas::core::NidasAppArg::_flags, and nidas::core::NidasAppArg::getValue().
Referenced by DataDump::parseRunstring(), DataPrep::parseRunstring(), and StatsProcess::parseRunstring().
asInt()
int NidasAppArg::asInt () inherited
Parse the argument value as an integer, where the value could be the default if no value has been explicitly parsed with parse().
Throw NidasAppException if the whole value cannot be parsed as an integer. See also asFloat().
References nidas::core::NidasAppArg::_flags, and nidas::core::NidasAppArg::getValue().
Referenced by DataStats::parseRunstring(), DataPrep::parseRunstring(), NidsMerge::parseRunstring(), StatsProcess::parseRunstring(), TeeI2C::parseRunstring(), and DataPrep::run().
getDefault()
std::string nidas::core::NidasAppArg::getDefault () inline inherited
References nidas::core::NidasAppArg::_default.
getFilter()
BadSampleFilter& nidas::core::BadSampleFilterArg::getFilter () inline
References _bsf.
Referenced by DataDump::run(), DataStats::run(), DataPrep::run(), NidsMerge::run(), and StatsProcess::run().
getFlag()
const std::string & NidasAppArg::getFlag () inherited
Return the command-line flag which this argument consumed.
For example, if an argument with multiple flags is matched, then getFlag() returns the flag that matched the argument.
References nidas::core::NidasAppArg::_arg.
Referenced by DataPrep::parseRunstring().
getUsageFlags()
std::string NidasAppArg::getUsageFlags () inherited
Return the string of flags accepted by this NidasAppArg according to the acceptShortFlag() setting.
References nidas::core::NidasAppArg::_default, nidas::core::NidasAppArg::_enableShortFlag, nidas::core::NidasAppArg::_flags, and nidas::core::NidasAppArg::single().
Referenced by nidas::core::NidasAppArg::usage().
getValue()
const std::string & NidasAppArg::getValue () inherited
If this argument has been parsed from a command line list (specified() returns true), then return the value passed after the flag.
Otherwise return the default value.
References nidas::core::NidasAppArg::_default, nidas::core::NidasAppArg::_value, and nidas::core::NidasAppArg::specified().
Referenced by nidas::core::NidasAppArg::asBool(), nidas::core::NidasAppArg::asFloat(), nidas::core::NidasAppArg::asInt(), nidas::core::NidasApp::checkPidFile(), DataStats::jsonReport(), nidas::core::NidasApp::parseNext(), DmdA2dCk::parseRunstring(), DataPrep::parseRunstring(), NidsMerge::parseRunstring(), StatsProcess::parseRunstring(), nidas::core::DSMServerApp::parseRunstring(), and PConfig::parseRunstring().
isRequired()
bool NidasAppArg::isRequired () inherited
Return whether this argument is required.
See setRequired().
References nidas::core::NidasAppArg::_required.
Referenced by nidas::core::NidasAppArg::setRequired().
operator nidas_app_arglist_t()
nidas::core::NidasAppArg::operator nidas_app_arglist_t () inline inherited
Provide conversion to an arglist so a single NidasAppArg can be passed where an arglist is expected.
parse()
bool BadSampleFilterArg::parse (const ArgVector & argv, int * argi = 0) virtual
If argv[argi] matches this argument, then set the flag that was found and also the value if this argument takes a value, and return true.
Otherwise return false. The vector is not modified, but if argi is nonzero, then it is used as the starting index into argv, and it is advanced according to the number of elements of argv consumed by this argument. This method is virtual so subclasses can implement customized parsing, such as optionally consuming more than one argument following a flag.
Reimplemented from nidas::core::NidasAppArg.
References nidas::core::NidasAppArg::_arg, _bsf, nidas::core::NidasAppArg::_value, nidas::core::NidasAppArg::accept(), nidas::core::expectArg(), nidas::core::BadSampleFilter::setFilterBadSamples(), and nidas::core::BadSampleFilter::setRules().
setDefault()
void nidas::core::NidasAppArg::setDefault (const std::string & dvalue) inline inherited
References nidas::core::NidasAppArg::_default.
Referenced by nidas::core::NidasApp::NidasApp().
setFlags()
void NidasAppArg::setFlags (const std::string & flags) inherited
Completely replace the flags which this argument should accept.
This should be avoided if possible, otherwise the flags will not be consistent across applications. However, in some cases this is necessary to remove a conflicting short flag.
References nidas::core::NidasAppArg::_flags.
Referenced by DataPrep::parseRunstring(), and StatsProcess::parseRunstring().
setRequired()
void NidasAppArg::setRequired (bool isRequired = true) inherited
Set whether this argument is required.
A required argument must be supplied on the command line even if it has a default value. If an argument is not required because it has a default value, then an application should not set that argument to be required.
Defaults to true, but the client may disable this option by setting the argument to false.
References nidas::core::NidasAppArg::_required, and nidas::core::NidasAppArg::isRequired().
setUsageString()
void nidas::core::NidasAppArg::setUsageString (const std::string & text) inline inherited
References nidas::core::NidasAppArg::_usage.
Referenced by nidas::core::NidasApp::NidasApp(), DataPrep::parseRunstring(), and nidas::core::NidasAppInputFilesArg::updateUsage().
single()
bool NidasAppArg::single () protected inherited
Return true for arguments which are only a single argument.
They are a single command-line flag with no following value, and typically implying a boolean value. This is equivalent to not specifying a syntax when the argument is created.
References nidas::core::NidasAppArg::_syntax.
Referenced by nidas::core::NidasAppArg::accept(), nidas::core::NidasAppArg::getUsageFlags(), and nidas::core::NidasAppArg::parse().
specified()
bool NidasAppArg::specified () inherited
Return true if this argument has been filled in from a command-line argument list, such as after a call to NidasApp::parseArgs().
If true, then this argument stores the flag that was recognized, and also the value of any additional parameters to this argument.
References nidas::core::NidasAppArg::_arg.
Referenced by DataStats::addCounter(), nidas::core::NidasAppArg::getValue(), NidsMerge::parseRunstring(), TeeI2C::parseRunstring(), DataStats::report(), and nidas::core::NidasApp::setupDaemonLogging().
usage()
std::string NidasAppArg::usage (const std::string & indent = " ") inherited
Render the usage string for this particular argument, taking into account which flags are enabled.
The returned string is formatted like below, and always ends in a newline:
<indent><flag>[,<flag>...] [<syntax>] [default: <default>] <indent><indent>Description line one <indent><indent>Description line two ...
References nidas::core::NidasAppArg::_default, nidas::core::NidasAppArg::_syntax, nidas::core::NidasAppArg::_usage, and nidas::core::NidasAppArg::getUsageFlags().
Referenced by nidas::core::NidasApp::usage().
Member Data Documentation
_arg
std::string nidas::core::NidasAppArg::_arg protected inherited
Referenced by nidas::core::NidasAppArg::getFlag(), parse(), nidas::core::NidasAppArg::parse(), and nidas::core::NidasAppArg::specified().
_bsf
BadSampleFilter nidas::core::BadSampleFilterArg::_bsf private
Referenced by getFilter(), and parse().
_default
std::string nidas::core::NidasAppArg::_default protected inherited
Referenced by nidas::core::NidasAppArg::accept(), nidas::core::NidasAppArg::getDefault(), nidas::core::NidasAppArg::getUsageFlags(), nidas::core::NidasAppArg::getValue(), nidas::core::NidasAppArg::setDefault(), and nidas::core::NidasAppArg::usage().
_enableShortFlag
bool nidas::core::NidasAppArg::_enableShortFlag protected inherited
Referenced by nidas::core::NidasAppArg::accept(), nidas::core::NidasAppArg::acceptShortFlag(), and nidas::core::NidasAppArg::getUsageFlags().
_flags
std::string nidas::core::NidasAppArg::_flags protected inherited
Referenced by nidas::core::NidasAppArg::accept(), nidas::core::NidasAppArg::addFlag(), nidas::core::NidasAppArg::asBool(), nidas::core::NidasAppArg::asFloat(), nidas::core::NidasAppArg::asInt(), nidas::core::NidasAppArg::getUsageFlags(), and nidas::core::NidasAppArg::setFlags().
_required
bool nidas::core::NidasAppArg::_required protected inherited
Referenced by nidas::core::NidasAppArg::isRequired(), and nidas::core::NidasAppArg::setRequired().
_syntax
std::string nidas::core::NidasAppArg::_syntax protected inherited
Referenced by nidas::core::NidasAppArg::single(), and nidas::core::NidasAppArg::usage().
_usage
std::string nidas::core::NidasAppArg::_usage protected inherited
Referenced by nidas::core::NidasAppArg::setUsageString(), and nidas::core::NidasAppArg::usage().
_value
std::string nidas::core::NidasAppArg::_value protected inherited
Referenced by nidas::core::NidasAppArg::accept(), nidas::core::NidasAppArg::getValue(), parse(), and nidas::core::NidasAppArg::parse().
The documentation for this class was generated from the following files:
nidas/core/BadSampleFilter.h
nidas/core/BadSampleFilter.cc