nidas: nidas::core::Prompt Class Reference
nidas::core::Prompt Class Reference
Class to contain prompt information - string and rate.
#include <Prompt.h>
Public Member Functions
Prompt ()
void setString (const std::string &val)
const std::string & getString () const
void setRate (const double val)
Set rate of desired prompting, in Hz (sec^-1).
double getRate () const
void setOffset (const double val)
Set prompt offset in seconds.
double getOffset () const
Private Attributes
std::string _promptString
double _promptRate
double _promptOffset
Detailed Description
Class to contain prompt information - string and rate.
Constructor & Destructor Documentation
Prompt()
nidas::core::Prompt::Prompt () inline
Member Function Documentation
getOffset()
double nidas::core::Prompt::getOffset () const inline
References _promptOffset.
Referenced by nidas::core::SerialSensor::initPrompting().
getRate()
double nidas::core::Prompt::getRate () const inline
References _promptRate.
Referenced by nidas::core::SerialSensor::initPrompting().
getString()
const std::string& nidas::core::Prompt::getString () const inline
References _promptString.
Referenced by nidas::core::SerialSensor::initPrompting().
setOffset()
void nidas::core::Prompt::setOffset (const double val) inline
Set prompt offset in seconds.
For example, for a rate of 10Hz, an offset of 0 would result in prompts at 0.0, 0.1, 0.2 seconds after each second. An offset of 0.01 would result in prompts at 0.01, 0.11, 0.21 seconds after the second.
References _promptOffset.
Referenced by nidas::core::CharacterSensor::addPrompt().
setRate()
void nidas::core::Prompt::setRate (const double val) inline
Set rate of desired prompting, in Hz (sec^-1).
References _promptRate.
Referenced by nidas::core::CharacterSensor::addPrompt().
setString()
void nidas::core::Prompt::setString (const std::string & val) inline
References _promptString.
Referenced by nidas::core::CharacterSensor::addPrompt().
Member Data Documentation
_promptOffset
double nidas::core::Prompt::_promptOffset private
Referenced by getOffset(), and setOffset().
_promptRate
double nidas::core::Prompt::_promptRate private
Referenced by getRate(), and setRate().
_promptString
std::string nidas::core::Prompt::_promptString private
Referenced by getString(), and setString().
The documentation for this class was generated from the following file:
nidas/core/Prompt.h