nidas: DataStats Class Reference
DataStats Class Reference
Public Member Functions
DataStats ()
~DataStats ()
int run ()
void readHeader (SampleInputStream &sis)
void readSamples (SampleInputStream &sis)
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
void createCounters (const list< DSMSensor * > &sensors)
Create a SampleCounter for each of the sample tags in the given sensors, if any.
SampleCounter * addCounter (const SampleCounter &counter)
Copy the counter into the samples map and return a reference to it.
SampleCounter * getCounter (dsm_sample_id_t sid)
Return a pointer to the SampleCounter for the given sample id sid.
bool reportsExhausted (int nreports=-1)
void restartStats (const UTime &start, const UTime &end)
Recalculate statistics as needed based on the current collection of data and time period.
void clearSampleQueue ()
void report ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printReport (std::ostream &outs)
void jsonReport ()
void resetResults ()
Static Public Member Functions
static int main (int argc, char **argv)
static void handleSignal (int signum)
Private Types
typedef map< dsm_sample_id_t, SampleCounter > sample_map_t
typedef std::list< const Sample * > sample_queue
Private Member Functions
dsm_sample_id_t hashId (dsm_sample_id_t sid)
void createJsonWriters ()
Private Attributes
sample_map_t _samples
bool _reportall
bool _reportdata
bool _singlemote
bool _fullnames
bool _realtime
UTime _period_start
UTime _period_end
UTime _start_time
int _count
int _period
int _update
int _nreports
sample_queue _sampleq
NidasApp _app
NidasAppArg Period
NidasAppArg Update
NidasAppArg Count
NidasAppArg AllSamples
NidasAppArg ShowData
NidasAppArg SingleMote
NidasAppArg Fullnames
BadSampleFilterArg FilterArg
NidasAppArg JsonOutput
n_u::auto_ptr< Json::StyledStreamWriter > streamWriter
n_u::auto_ptr< Json::StyledStreamWriter > headerWriter
Static Private Attributes
static const int DEFAULT_PORT = 30000
static bool _alarm
Member Typedef Documentation
sample_map_t
typedef map<dsm_sample_id_t, SampleCounter> DataStats::sample_map_t private
sample_queue
typedef std::list<const Sample*> DataStats::sample_queue private
Constructor & Destructor Documentation
DataStats()
DataStats::DataStats ()
References _app, nidas::core::NidasAppInputFilesArg::allowFiles, nidas::core::NidasAppInputFilesArg::allowSockets, AllSamples, Count, DEFAULT_PORT, nidas::core::NidasApp::enableArguments(), FilterArg, nidas::core::NidasApp::FormatHexId, nidas::core::NidasApp::FormatSampleId, Fullnames, nidas::core::NidasApp::Help, nidas::core::NidasApp::InputFiles, JsonOutput, nidas::core::NidasApp::loggingArgs(), Period, nidas::core::NidasApp::ProcessData, nidas::core::NidasApp::SampleRanges, nidas::core::NidasApp::setApplicationInstance(), nidas::core::NidasAppInputFilesArg::setDefaultInput(), nidas::core::NidasApp::setupSignals(), ShowData, SingleMote, Update, nidas::core::NidasApp::Version, and nidas::core::NidasApp::XmlHeaderFile.
~DataStats()
DataStats::~DataStats () inline
Member Function Documentation
addCounter()
SampleCounter * DataStats::addCounter (const SampleCounter & counter)
Copy the counter into the samples map and return a reference to it.
Also configure the counter according to whether json output or data statistics should be enabled. Mote sensor IDs for the same sensor type will be hashed to one bucket, as will sensors with different mote IDs if _singlemote is enabled. This should only be called if getCounter() does not return a counter for the sample ID.
References _reportdata, _samples, SampleCounter::enableData(), SampleCounter::enableJSON(), hashId(), SampleCounter::id, JsonOutput, and nidas::core::NidasAppArg::specified().
Referenced by createCounters().
clearSampleQueue()
void DataStats::clearSampleQueue ()
References _sampleq, and nidas::core::Sample::freeReference().
createCounters()
void DataStats::createCounters (const list< DSMSensor * > & sensors)
Create a SampleCounter for each of the sample tags in the given sensors, if any.
Set singlemote to expect only one mote for each sensor type. When a wisard sensor returns multiple sample tags with different mote IDs, samples will only be expected from one of those tags.
References _app, addCounter(), DLOG, nidas::core::NidasApp::formatId(), getCounter(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getId(), nidas::core::SampleTag::getId(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariables(), nidas::core::SampleTagIterator::hasNext(), nidas::core::SampleMatcher::match(), nidas::core::SampleTagIterator::next(), nidas::core::NidasApp::processData(), and nidas::core::NidasApp::sampleMatcher().
Referenced by run().
createJsonWriters()
void DataStats::createJsonWriters () inline private
Referenced by jsonReport().
flush()
void DataStats::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implements nidas::core::SampleClient.
getCounter()
SampleCounter * DataStats::getCounter (dsm_sample_id_t sid)
Return a pointer to the SampleCounter for the given sample id sid.
If no such counter exists, return null. Mote sensor sample IDs are hashed into buckets by sensor type and according to the _singlemote setting, so the returned SampleCounter may not have the same ID as the one passed in.
References _samples, and hashId().
Referenced by createCounters(), and restartStats().
handleSignal()
void DataStats::handleSignal (int signum) static
References nidas::core::NidasApp::setInterrupted().
Referenced by run().
hashId()
dsm_sample_id_t DataStats::hashId (dsm_sample_id_t sid) private
References _app, _singlemote, nidas::core::NidasApp::formatId(), and VLOG.
Referenced by addCounter(), and getCounter().
jsonReport()
void DataStats::jsonReport ()
References _period, _period_end, _period_start, _reportall, _reportdata, _samples, _start_time, _update, createJsonWriters(), createObject(), nidas::core::NidasAppArg::getValue(), headerWriter, ILOG, SampleCounter::jsonData(), SampleCounter::jsonHeader(), JsonOutput, SampleCounter::jsonStats(), SampleCounter::nsamps, SampleCounter::streamid, and streamWriter.
Referenced by report().
main()
int DataStats::main (int argc, char ** argv) static
References parseRunstring(), run(), and nidas::util::Exception::what().
Referenced by main().
parseRunstring()
int DataStats::parseRunstring (int argc, char ** argv)
References _app, _count, _fullnames, _period, _reportall, _reportdata, _singlemote, _update, AllSamples, nidas::core::NidasAppArg::asBool(), nidas::core::NidasAppArg::asInt(), Count, Fullnames, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::parseArgs(), nidas::core::NidasApp::parseInputs(), Period, ShowData, SingleMote, Update, usage(), and nidas::util::Exception::what().
Referenced by main().
printReport()
void DataStats::printReport (std::ostream & outs)
References _fullnames, _reportall, _reportdata, _samples, SampleCounter::computeRate(), nidas::core::NidasApp::formatSampleId(), GET_DSM_ID, SampleCounter::getHeaderLine(), SampleCounter::id, SampleCounter::maxDeltaTs, SampleCounter::maxlens, SampleCounter::minDeltaTs, SampleCounter::minlens, MSECS_PER_SEC, SampleCounter::nsamps, SampleCounter::printData(), rate, SampleCounter::t1s, SampleCounter::t2s, USECS_PER_MSEC, and USECS_PER_SEC.
Referenced by report().
readHeader()
void DataStats::readHeader (SampleInputStream & sis)
References _alarm, _app, _nreports, _realtime, _update, DLOG, nidas::util::Exception::getErrno(), nidas::core::NidasApp::interrupted(), nidas::dynld::SampleInputStream::readInputHeader(), reportsExhausted(), and nidas::util::Exception::what().
Referenced by run().
readSamples()
void DataStats::readSamples (SampleInputStream & sis)
References _alarm, _app, _period_end, _realtime, _update, DLOG, nidas::util::Exception::getErrno(), nidas::core::NidasApp::interrupted(), nidas::dynld::SampleInputStream::readSamples(), nidas::util::UTime::toSecs(), nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
Referenced by run().
receive()
bool DataStats::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References DLOG, nidas::core::NidasApp::formatId(), nidas::core::SampleMatcher::match(), SampleCounter::receive(), nidas::core::NidasApp::sampleMatcher(), nidas::util::UTime::toUsecs(), and VLOG.
report()
void DataStats::report ()
References _period, _period_end, _period_start, _realtime, ILOG, JsonOutput, jsonReport(), printReport(), and nidas::core::NidasAppArg::specified().
Referenced by run().
reportsExhausted()
bool DataStats::reportsExhausted (int nreports = -1) inline
Referenced by readHeader(), and run().
resetResults()
void DataStats::resetResults ()
References _samples.
Referenced by restartStats().
restartStats()
void DataStats::restartStats (const UTime & start, const UTime & end)
Recalculate statistics as needed based on the current collection of data and time period.
References _sampleq, SampleCounter::accumulateSample(), DLOG, getCounter(), nidas::core::Sample::getId(), nidas::core::Sample::getTimeTag(), resetResults(), and nidas::util::UTime::toUsecs().
Referenced by run().
run()
int DataStats::run ()
References _app, _nreports, _period, _period_end, _period_start, _realtime, _start_time, _update, nidas::dynld::SampleInputStream::addSampleClient(), nidas::core::SampleSource::addSampleClient(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::core::NidasApp::addSignal(), nidas::dynld::SampleInputStream::close(), nidas::core::FileSet::connect(), nidas::core::SamplePipeline::connect(), createCounters(), nidas::core::NidasApp::dataFileNames(), nidas::core::SamplePipeline::disconnect(), DLOG, nidas::util::Process::expandEnvVars(), FilterArg, nidas::core::SamplePipeline::flush(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::FileSet::getFileSet(), nidas::core::BadSampleFilterArg::getFilter(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMConfig::getSensors(), handleSignal(), nidas::core::DSMConfigIterator::hasNext(), ILOG, nidas::core::DSMSensor::init(), nidas::core::SamplePipeline::interrupt(), nidas::core::NidasApp::interrupted(), nidas::core::SamplePipeline::join(), nidas::core::DSMConfigIterator::next(), nidas::core::parseXMLConfigFile(), nidas::core::NidasApp::processData(), readHeader(), readSamples(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::core::SampleSource::removeSampleClient(), report(), reportsExhausted(), restartStats(), nidas::dynld::SampleInputStream::setBadSampleFilter(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), nidas::core::NidasApp::socketAddress(), USECS_PER_SEC, nidas::util::Exception::what(), and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
usage()
int DataStats::usage (const char * argv0)
References _app, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
_alarm
bool DataStats::_alarm static private
Referenced by readHeader(), and readSamples().
_app
NidasApp DataStats::_app private
Referenced by createCounters(), DataStats(), hashId(), parseRunstring(), readHeader(), readSamples(), run(), and usage().
_count
int DataStats::_count private
Referenced by parseRunstring().
_fullnames
bool DataStats::_fullnames private
Referenced by parseRunstring(), and printReport().
_nreports
int DataStats::_nreports private
Referenced by readHeader(), and run().
_period
int DataStats::_period private
Referenced by jsonReport(), parseRunstring(), report(), and run().
_period_end
UTime DataStats::_period_end private
Referenced by jsonReport(), readSamples(), report(), and run().
_period_start
UTime DataStats::_period_start private
Referenced by jsonReport(), report(), and run().
_realtime
bool DataStats::_realtime private
Referenced by readHeader(), readSamples(), report(), and run().
_reportall
bool DataStats::_reportall private
Referenced by jsonReport(), parseRunstring(), and printReport().
_reportdata
bool DataStats::_reportdata private
Referenced by addCounter(), jsonReport(), parseRunstring(), and printReport().
_sampleq
sample_queue DataStats::_sampleq private
Referenced by clearSampleQueue(), and restartStats().
_samples
sample_map_t DataStats::_samples private
Referenced by addCounter(), getCounter(), jsonReport(), printReport(), and resetResults().
_singlemote
bool DataStats::_singlemote private
Referenced by hashId(), and parseRunstring().
_start_time
UTime DataStats::_start_time private
Referenced by jsonReport(), and run().
_update
int DataStats::_update private
Referenced by jsonReport(), parseRunstring(), readHeader(), readSamples(), and run().
AllSamples
NidasAppArg DataStats::AllSamples private
Referenced by DataStats(), and parseRunstring().
Count
NidasAppArg DataStats::Count private
Referenced by DataStats(), and parseRunstring().
DEFAULT_PORT
const int DataStats::DEFAULT_PORT = 30000 static private
Referenced by DataStats().
FilterArg
BadSampleFilterArg DataStats::FilterArg private
Referenced by DataStats(), and run().
Fullnames
NidasAppArg DataStats::Fullnames private
Referenced by DataStats(), and parseRunstring().
headerWriter
n_u::auto_ptr<Json::StyledStreamWriter> DataStats::headerWriter private
Referenced by jsonReport().
JsonOutput
NidasAppArg DataStats::JsonOutput private
Referenced by addCounter(), DataStats(), jsonReport(), and report().
Period
NidasAppArg DataStats::Period private
Referenced by DataStats(), and parseRunstring().
ShowData
NidasAppArg DataStats::ShowData private
Referenced by DataStats(), and parseRunstring().
SingleMote
NidasAppArg DataStats::SingleMote private
Referenced by DataStats(), and parseRunstring().
streamWriter
n_u::auto_ptr<Json::StyledStreamWriter> DataStats::streamWriter private
Referenced by jsonReport().
Update
NidasAppArg DataStats::Update private
Referenced by DataStats(), and parseRunstring().
The documentation for this class was generated from the following file:
nidas/apps/data_stats.cc