nidas: HeaderUtil Class Reference
HeaderUtil Class Reference
Public Member Functions
HeaderUtil ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
void printHeader (const SampleInputHeader &header)
Static Public Member Functions
static int main (int argc, char **argv) throw ()
static int usage (const char *argv0)
Private Attributes
string fileName
string archiveVersion
string softwareVersion
string projectName
string systemName
string configName
string configVersion
bool update
Constructor & Destructor Documentation
HeaderUtil()
HeaderUtil::HeaderUtil ()
Member Function Documentation
main()
int HeaderUtil::main (int argc, char ** argv) throw () static
References parseRunstring(), and run().
Referenced by main().
parseRunstring()
int HeaderUtil::parseRunstring (int argc, char ** argv) throw ()
References usage().
Referenced by main().
printHeader()
void HeaderUtil::printHeader (const SampleInputHeader & header)
References nidas::core::SampleInputHeader::toString().
Referenced by run().
run()
int HeaderUtil::run () throw ()
References archiveVersion, nidas::core::IOStream::available(), nidas::core::UnixIOChannel::close(), configName, configVersion, fd, fileName, nidas::core::IOStream::flush(), nidas::core::SampleInputHeader::getLength(), printHeader(), projectName, nidas::core::SampleInputHeader::read(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), nidas::core::SampleInputHeader::setSystemName(), nidas::core::IOStream::skip(), softwareVersion, systemName, nidas::core::SampleInputHeader::toString(), update, nidas::util::Exception::what(), and nidas::core::SampleInputHeader::write().
Referenced by main().
usage()
int HeaderUtil::usage (const char * argv0) static
Member Data Documentation
archiveVersion
string HeaderUtil::archiveVersion private
Referenced by run().
configName
string HeaderUtil::configName private
Referenced by run().
configVersion
string HeaderUtil::configVersion private
Referenced by run().
fileName
string HeaderUtil::fileName private
Referenced by run().
projectName
string HeaderUtil::projectName private
Referenced by run().
softwareVersion
string HeaderUtil::softwareVersion private
Referenced by run().
systemName
string HeaderUtil::systemName private
Referenced by run().
update
bool HeaderUtil::update private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/n_hdr_util.cc