nidas: nidas::core::SamplePoolInterface Class Reference
nidas::core::SamplePoolInterface Class Reference abstract
#include <SamplePool.h>
Public Member Functions
virtual ~SamplePoolInterface ()
virtual int getNSamplesAlloc () const =0
virtual int getNSamplesOut () const =0
virtual int getNSmallSamplesIn () const =0
virtual int getNMediumSamplesIn () const =0
virtual int getNLargeSamplesIn () const =0
Constructor & Destructor Documentation
~SamplePoolInterface()
virtual nidas::core::SamplePoolInterface::~SamplePoolInterface () inline virtual
Member Function Documentation
getNLargeSamplesIn()
virtual int nidas::core::SamplePoolInterface::getNLargeSamplesIn () const pure virtual
Implemented in nidas::core::SamplePool< SampleType >.
Referenced by nidas::core::DSMEngine::main().
getNMediumSamplesIn()
virtual int nidas::core::SamplePoolInterface::getNMediumSamplesIn () const pure virtual
Implemented in nidas::core::SamplePool< SampleType >.
Referenced by nidas::core::DSMEngine::main().
getNSamplesAlloc()
virtual int nidas::core::SamplePoolInterface::getNSamplesAlloc () const pure virtual
Implemented in nidas::core::SamplePool< SampleType >.
Referenced by nidas::core::SensorHandler::run().
getNSamplesOut()
virtual int nidas::core::SamplePoolInterface::getNSamplesOut () const pure virtual
Implemented in nidas::core::SamplePool< SampleType >.
Referenced by nidas::core::DSMEngine::main(), and nidas::core::SensorHandler::run().
getNSmallSamplesIn()
virtual int nidas::core::SamplePoolInterface::getNSmallSamplesIn () const pure virtual
Implemented in nidas::core::SamplePool< SampleType >.
Referenced by nidas::core::DSMEngine::main().
The documentation for this class was generated from the following file:
nidas/core/SamplePool.h