nidas: nidas::dynld::isff::GOESProject Class Reference
nidas::dynld::isff::GOESProject Class Reference
#include <GOESProject.h>
Public Member Functions
GOESProject (nidas::core::Project *p) throw (nidas::util::InvalidParameterException)
~GOESProject ()
nidas::core::Project * getProject () const
int getStationNumber (unsigned long goesId) const throw (nidas::util::InvalidParameterException)
Get the station number, corresponding to a GOES id.
int getXmitInterval (int stationNumber) const throw (nidas::util::InvalidParameterException)
int getXmitOffset (int stationNumber) const throw (nidas::util::InvalidParameterException)
const nidas::core::SampleTag * getGOESSampleTag (int stationNumber) const throw (nidas::util::InvalidParameterException)
void addSampleTag (nidas::core::SampleTag *tag) throw ()
const nidas::core::SampleTag * getSampleTag (int stationNumber, int sampleId) const
Get a SampleTag*, corresponding to station and sampleid.
std::list< const nidas::core::SampleTag * > getSampleTags () const
unsigned long getGOESId (int stationNum) const throw (nidas::util::InvalidParameterException)
Private Member Functions
GOESProject (const GOESProject &x)
GOESProject & operator= (const GOESProject &x) const
void readGOESIds () throw (nidas::util::InvalidParameterException)
Private Attributes
nidas::core::Project * _project
std::vector< unsigned long > _goesIds
std::map< unsigned long, int > _stationNumbersById
std::map< nidas::core::dsm_sample_id_t, const nidas::core::SampleTag * > _sampleTagsById
std::vector< int > _xmitOffsets
std::vector< int > _xmitIntervals
std::list< nidas::core::SampleTag * > _sampleTags
std::list< const nidas::core::SampleTag * > _constSampleTags
std::vector< nidas::core::SampleTag * > _goesTags
Constructor & Destructor Documentation
GOESProject() [1/2]
GOESProject::GOESProject (nidas::core::Project * p) throw (nidas::util::InvalidParameterException)
References nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getId(), nidas::core::ParameterT< T >::getLength(), nidas::core::Variable::getLongName(), nidas::core::Site::getNumber(), nidas::core::SampleIOProcessor::getOutputs(), nidas::core::Site::getProcessorIterator(), nidas::core::SampleOutputBase::getRequestedSampleTags(), nidas::core::SampleTag::getSpSId(), nidas::core::Parameter::getType(), nidas::core::Variable::getUnits(), nidas::core::ParameterT< T >::getValue(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), nidas::dynld::isff::GOESOutput::getXmitInterval(), nidas::core::SiteIterator::hasNext(), nidas::core::ProcessorIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::Parameter::INT_PARAM, nidas::core::SiteIterator::next(), nidas::core::ProcessorIterator::next(), nidas::core::VariableIterator::next(), nidas::core::SampleTag::setDSMId(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), nidas::core::SampleTag::setPeriod(), nidas::core::SampleTag::setSampleId(), and nidas::core::Variable::setUnits().
~GOESProject()
GOESProject::~GOESProject ()
GOESProject() [2/2]
nidas::dynld::isff::GOESProject::GOESProject (const GOESProject & x) private
Member Function Documentation
addSampleTag()
void nidas::dynld::isff::GOESProject::addSampleTag (nidas::core::SampleTag * tag) throw () inline
References _constSampleTags, and _sampleTags.
getGOESId()
unsigned long GOESProject::getGOESId (int stationNum) const throw (nidas::util::InvalidParameterException)
getGOESSampleTag()
const SampleTag * GOESProject::getGOESSampleTag (int stationNumber) const throw (nidas::util::InvalidParameterException)
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getProject()
nidas::core::Project* nidas::dynld::isff::GOESProject::getProject () const inline
References _project.
getSampleTag()
const SampleTag * GOESProject::getSampleTag (int stationNumber, int sampleId) const
Get a SampleTag*, corresponding to station and sampleid.
Returns
0: SampleTag corresponding to a dsm id of stationNumber+1, and the given sampleId not found.
References SET_DSM_ID.
Referenced by nidas::dynld::isff::PacketInputStream::findSampleTag().
getSampleTags()
std::list<const nidas::core::SampleTag*> nidas::dynld::isff::GOESProject::getSampleTags () const inline
References _constSampleTags.
Referenced by nidas::dynld::isff::PacketInputStream::getSampleTags().
getStationNumber()
int GOESProject::getStationNumber (unsigned long goesId) const throw (nidas::util::InvalidParameterException)
Get the station number, corresponding to a GOES id.
Returns
non-negative number. Throws InvalidParameterException if there is no "goes_ids" integer parameter for the Project, or the goesId is not valid.
Referenced by nidas::dynld::isff::PacketInputStream::findSampleTag(), and nidas::dynld::isff::PacketInputStream::readSamples().
getXmitInterval()
int GOESProject::getXmitInterval (int stationNumber) const throw (nidas::util::InvalidParameterException)
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getXmitOffset()
int GOESProject::getXmitOffset (int stationNumber) const throw (nidas::util::InvalidParameterException)
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
operator=()
GOESProject& nidas::dynld::isff::GOESProject::operator= (const GOESProject & x) const private
readGOESIds()
void nidas::dynld::isff::GOESProject::readGOESIds () throw (nidas::util::InvalidParameterException) private
Member Data Documentation
_constSampleTags
std::list<const nidas::core::SampleTag*> nidas::dynld::isff::GOESProject::_constSampleTags private
Referenced by addSampleTag(), and getSampleTags().
_goesIds
std::vector<unsigned long> nidas::dynld::isff::GOESProject::_goesIds private
_goesTags
std::vector<nidas::core::SampleTag*> nidas::dynld::isff::GOESProject::_goesTags private
_project
nidas::core::Project* nidas::dynld::isff::GOESProject::_project private
Referenced by getProject().
_sampleTags
std::list<nidas::core::SampleTag*> nidas::dynld::isff::GOESProject::_sampleTags private
Referenced by addSampleTag().
_sampleTagsById
std::map<nidas::core::dsm_sample_id_t,const nidas::core::SampleTag*> nidas::dynld::isff::GOESProject::_sampleTagsById private
_stationNumbersById
std::map<unsigned long,int> nidas::dynld::isff::GOESProject::_stationNumbersById private
_xmitIntervals
std::vector<int> nidas::dynld::isff::GOESProject::_xmitIntervals private
_xmitOffsets
std::vector<int> nidas::dynld::isff::GOESProject::_xmitOffsets private
The documentation for this class was generated from the following files:
nidas/dynld/isff/GOESProject.h
nidas/dynld/isff/GOESProject.cc