nidas: nidas::core::ServerSocketIODevice Class Reference
nidas::core::ServerSocketIODevice Class Reference
An IODevice supporting a TCP or UNIX server socket.
#include <ServerSocketIODevice.h>
Public Member Functions
ServerSocketIODevice ()
Create a SocketIODevice.
virtual ~ServerSocketIODevice ()
int getReadFd () const
The file descriptor used when reading from this SocketIODevice.
int getWriteFd () const
The file descriptor used when writing to this sensor.
void open (int flags)
Open the socket.
size_t read (void *buf, size_t len)
Read from the sensor.
size_t read (void *buf, size_t len, int msecTimeout)
Read from the sensor with a timeout in milliseconds.
size_t write (const void *buf, size_t len)
Write to the sensor.
void ioctl (int, void *, size_t)
Perform an ioctl on the device.
void close ()
close the sensor (and any associated FIFOs).
void setTcpNoDelay (bool val)
bool getTcpNoDelay ()
virtual void setName (const std::string &val)
Set the device name to be opened for this sensor.
virtual const std::string & getName () const
virtual size_t getBytesAvailable () const
Return how many bytes are available to read on this IODevice.
Protected Member Functions
void closeServerSocket ()
Private Member Functions
ServerSocketIODevice (const ServerSocketIODevice &)
No copying.
ServerSocketIODevice & operator= (const ServerSocketIODevice &)
No assignment.
Private Attributes
int _addrtype
The type of the destination address, AF_INET or AF_UNIX.
std::string _unixPath
Path name of AF_UNIX socket.
int _sockPort
Port number that is parsed from sensor name.
nidas::util::auto_ptr< nidas::util::SocketAddress > _sockAddr
The destination socket address.
nidas::util::ServerSocket * _serverSocket
The listen socket.
nidas::util::Socket * _socket
bool _tcpNoDelay
std::string _devname
Whether to reopen this sensor on an IOException.
Detailed Description
An IODevice supporting a TCP or UNIX server socket.
This class has a critical limitation and isn't currently used anywhere in NIDAS. The IODevice::open() method should not block, and this class violates that because open() does a nidas::util::ServerSocket::accept() which can block forever. To really support this class we need to spawn a ServerSocket listening thread.
Constructor & Destructor Documentation
ServerSocketIODevice() [1/2]
ServerSocketIODevice::ServerSocketIODevice ()
Create a SocketIODevice.
No IO operations to the sensor are performed in the constructor (hence no IOExceptions).
~ServerSocketIODevice()
ServerSocketIODevice::~ServerSocketIODevice () virtual
References close(), and closeServerSocket().
ServerSocketIODevice() [2/2]
nidas::core::ServerSocketIODevice::ServerSocketIODevice (const ServerSocketIODevice &) private
No copying.
Member Function Documentation
close()
void ServerSocketIODevice::close () virtual
close the sensor (and any associated FIFOs).
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, nidas::util::Socket::close(), nidas::util::Socket::getFd(), nidas::util::Logger::getInstance(), nidas::core::IODevice::getName(), nidas::util::Logger::log(), and LOG_INFO.
Referenced by open(), and ~ServerSocketIODevice().
closeServerSocket()
void ServerSocketIODevice::closeServerSocket () protected
Exceptions
nidas::util::IOException
References _serverSocket, nidas::util::ServerSocket::close(), and nidas::util::ServerSocket::getFd().
Referenced by ~ServerSocketIODevice().
getBytesAvailable()
virtual size_t nidas::core::IODevice::getBytesAvailable () const inline virtual inherited
Return how many bytes are available to read on this IODevice.
This method is only useful when ioctl FIONREAD is supported on this this IODevice, as for example with a UDP socket. It is not available, and not necessary, on most other devices, like serial ports, TCP sockets, or devices with nidas driver module support, in which case it will return an nidas::util::IOException. It is an optimization for use with UDP sockets, where after select determines that data is available on the socket file descriptor, a read will only read one datagram, even if there are more than one packet available, which would not be optimal if a sensor generated many small packets. Rather than returning back to select, we check if there are more datagrams to read. This is not necessary on other types of IODevices, where it is just a matter of using a big enough buffer to get all (or most) available data after a select.
According to man udp(7), FIONREAD will return 0 if the size of the next packet is 0. So, if select/poll indicate there is data available, one read at least should be done, just in case a sensor sends a datagram of length 0, otherwise it will never be consumed.
Exceptions
nidas::util::IOException
References err, nidas::core::IODevice::getName(), nidas::core::IODevice::getReadFd(), and nidas::core::IODevice::ioctl().
Referenced by nidas::core::DSMSensor::getBytesAvailable().
getName()
virtual const std::string& nidas::core::IODevice::getName () const inline virtual inherited
References nidas::core::IODevice::_devname.
Referenced by nidas::core::SerialPortIODevice::applyTermios(), close(), nidas::core::TCPSocketIODevice::close(), nidas::core::UDPSocketIODevice::close(), nidas::core::UnixIODevice::close(), nidas::core::IODevice::getBytesAvailable(), nidas::core::UnixIODevice::ioctl(), ioctl(), nidas::core::SocketIODevice::ioctl(), open(), nidas::core::SocketIODevice::open(), nidas::core::UnixIODevice::open(), nidas::core::UnixIODevice::read(), and nidas::core::UnixIODevice::write().
getReadFd()
int nidas::core::ServerSocketIODevice::getReadFd () const inline virtual
The file descriptor used when reading from this SocketIODevice.
Implements nidas::core::IODevice.
References _socket, and nidas::util::Socket::getFd().
getTcpNoDelay()
bool nidas::core::ServerSocketIODevice::getTcpNoDelay () inline
Exceptions
nidas::util::IOException
References _tcpNoDelay.
Referenced by open().
getWriteFd()
int nidas::core::ServerSocketIODevice::getWriteFd () const inline virtual
The file descriptor used when writing to this sensor.
Implements nidas::core::IODevice.
References _socket, and nidas::util::Socket::getFd().
ioctl()
void nidas::core::ServerSocketIODevice::ioctl (int , void * , size_t) inline virtual
Perform an ioctl on the device.
Not necessary for a socket, and will throw an IOException.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References nidas::core::IODevice::getName().
open()
void ServerSocketIODevice::open (int flags) virtual
Open the socket.
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
Implements nidas::core::IODevice.
References _addrtype, _serverSocket, _sockAddr, _socket, _sockPort, _unixPath, nidas::util::ServerSocket::accept(), close(), nidas::util::Inet4Address::getByName(), nidas::core::IODevice::getName(), getTcpNoDelay(), nidas::core::SocketIODevice::parseAddress(), nidas::util::Socket::setNonBlocking(), nidas::util::Socket::setTcpNoDelay(), and nidas::util::Exception::what().
operator=()
ServerSocketIODevice& nidas::core::ServerSocketIODevice::operator= (const ServerSocketIODevice &) private
No assignment.
read() [1/2]
size_t nidas::core::ServerSocketIODevice::read (void * buf, size_t len) inline virtual
Read from the sensor.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::Socket::recv().
read() [2/2]
size_t nidas::core::ServerSocketIODevice::read (void * buf, size_t len, int msecTimeout) inline virtual
Read from the sensor with a timeout in milliseconds.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, nidas::util::Socket::recv(), and nidas::util::Socket::setTimeout().
setName()
virtual void nidas::core::IODevice::setName (const std::string & val) inline virtual inherited
Set the device name to be opened for this sensor.
References nidas::core::IODevice::_devname.
Referenced by nidas::core::DSMSensor::open(), and nidas::core::UnixIODevice::UnixIODevice().
setTcpNoDelay()
void nidas::core::ServerSocketIODevice::setTcpNoDelay (bool val) inline
Exceptions
nidas::util::IOException
References _tcpNoDelay.
Referenced by nidas::dynld::raf::CVI_LV_Input::buildIODevice().
write()
size_t nidas::core::ServerSocketIODevice::write (const void * buf, size_t len) inline virtual
Write to the sensor.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::Socket::send().
Member Data Documentation
_addrtype
int nidas::core::ServerSocketIODevice::_addrtype private
The type of the destination address, AF_INET or AF_UNIX.
Referenced by open().
_devname
std::string nidas::core::IODevice::_devname private inherited
Whether to reopen this sensor on an IOException.
Referenced by nidas::core::IODevice::getName(), and nidas::core::IODevice::setName().
_serverSocket
nidas::util::ServerSocket* nidas::core::ServerSocketIODevice::_serverSocket private
The listen socket.
This isn't in an auto_ptr because one must close the socket prior to deleting it. The nidas::util::Socket destructor does not close the file descriptor.
Referenced by closeServerSocket(), and open().
_sockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::ServerSocketIODevice::_sockAddr private
The destination socket address.
Referenced by open().
_socket
nidas::util::Socket* nidas::core::ServerSocketIODevice::_socket private
Referenced by close(), getReadFd(), getWriteFd(), open(), read(), and write().
_sockPort
int nidas::core::ServerSocketIODevice::_sockPort private
Port number that is parsed from sensor name.
Referenced by open().
_tcpNoDelay
bool nidas::core::ServerSocketIODevice::_tcpNoDelay private
Referenced by getTcpNoDelay(), and setTcpNoDelay().
_unixPath
std::string nidas::core::ServerSocketIODevice::_unixPath private
Path name of AF_UNIX socket.
Referenced by open().
The documentation for this class was generated from the following files:
nidas/core/ServerSocketIODevice.h
nidas/core/ServerSocketIODevice.cc