nidas: nidas::dynld::psql::PSQLSampleOutput Class Reference
nidas::dynld::psql::PSQLSampleOutput Class Reference
#include <PSQLSampleOutput.h>
Public Member Functions
PSQLSampleOutput ()
PSQLSampleOutput (const PSQLSampleOutput &)
virtual ~PSQLSampleOutput ()
PSQLSampleOutput * clone (IOChannel *iochannel=0) const
void setName (const std::string &val)
const std::string & getName () const
bool isRaw () const
void setPseudoPort (int val)
int getPseudoPort () const
void setDSMConfigs (const std::list< const DSMConfig * > &val)
void addDSMConfig (const DSMConfig *)
const std::list< const DSMConfig * > & getDSMConfigs () const
void addSampleTag (const SampleTag *tag) throw (nidas::util::InvalidParameterException)
void requestConnection (SampleConnectionRequester *) throw (nidas::util::IOException)
Request a connection, but don't wait for it.
void connected (SampleOutput *origout, SampleOutput *newout) throw ()
void connect () throw (nidas::util::IOException)
void connected (IOChannel *output) throw ()
Implementation of IOChannelRequester::connected().
void init () throw ()
bool receive (const Sample *) throw ()
Method called to pass a sample to this client.
int getFd () const
void flush () throw (nidas::util::IOException)
Ask that this SampleClient send out any buffered Samples that it may be holding.
void close () throw (nidas::util::IOException)
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
IOStream * getIOStream ()
Get the IOStream of this SampleOutputStream.
size_t write (const void *buf, size_t len, bool streamFlush)
size_t write (const void *buf, size_t len)
Raw write method, typically used to write the initial header.
void setLatency (float val)
Outgoing data is buffered in an IOStream.
virtual void setIOChannel (IOChannel *val)
Set the IOChannel for this SampleOutput.
SampleOutput * getOriginal () const
Get pointer to SampleOutput that was cloned.
void addRequestedSampleTag (SampleTag *tag)
std::list< const SampleTag * > getRequestedSampleTags () const
void addSourceSampleTag (const SampleTag *tag)
void addSourceSampleTags (const std::list< const SampleTag * > &tags)
std::list< const SampleTag * > getSourceSampleTags () const
int getReconnectDelaySecs () const
Base class implementation.
void setReconnectDelaySecs (int val)
dsm_time_t getNextFileTime () const
void createNextFile (dsm_time_t)
IOChannel * getIOChannel () const
void setHeaderSource (HeaderSource *val)
void setDSMConfig (const DSMConfig *val)
const DSMConfig * getDSMConfig () const
size_t getNumDiscardedSamples () const
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
float getLatency () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void submitCommand (const std::string &command) throw (nidas::util::IOException)
void createTables () throw (nidas::util::IOException)
void dropAllTables () throw ()
void initializeGlobalAttributes () throw (nidas::util::IOException)
void addVariable (const Variable *var) throw (nidas::util::IOException)
void addCategory (const std::string &varName, const std::string &category) throw (nidas::util::IOException)
size_t write (const Sample *samp, bool streamFlush)
SampleOutputStream * clone (IOChannel *iochannel)
size_t incrementDiscardedSamples ()
SampleConnectionRequester * getSampleConnectionRequester ()
void disconnect ()
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
Protected Attributes
std::string name
SampleConnectionRequester * connectionRequester
std::list< const DSMConfig * > dsms
PSQLChannel * psqlChannel
std::map< float, const SampleTag * > tagsByRate
std::map< float, std::string > tablesByRate
std::map< dsm_sample_id_t, const SampleTag * > tagsById
float missingValue
bool first
int dberrors
IOStream * _iostream
std::string _name
Private Attributes
int _maxUsecs
Maximum number of microseconds between physical writes.
dsm_time_t _lastFlushTT
Timetag of last flush of IOStream.
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
std::list< const SampleTag * > _constRequestedTags
IOChannel * _iochan
SampleConnectionRequester * _connectionRequester
dsm_time_t _nextFileTime
HeaderSource * _headerSource
const DSMConfig * _dsm
size_t _nsamplesDiscarded
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
std::list< const SampleTag * > _sourceTags
SampleOutput * _original
Pointer to the SampleOutput that I was cloned from.
float _latency
int _reconnectDelaySecs
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
PSQLSampleOutput() [1/2]
PSQLSampleOutput::PSQLSampleOutput ()
Referenced by clone().
PSQLSampleOutput() [2/2]
PSQLSampleOutput::PSQLSampleOutput (const PSQLSampleOutput & x)
~PSQLSampleOutput()
PSQLSampleOutput::~PSQLSampleOutput () virtual
References psqlChannel.
Member Function Documentation
addCategory()
void PSQLSampleOutput::addCategory (const std::string & varName, const std::string & category) throw (nidas::util::IOException) protected
addDSMConfig()
void PSQLSampleOutput::addDSMConfig (const DSMConfig * val)
References dsms.
addParameter()
void SampleOutputBase::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::SampleOutputBase::_constParameters, nidas::core::SampleOutputBase::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::SampleOutputBase::fromDOMElement().
addRequestedSampleTag()
void SampleOutputBase::addRequestedSampleTag (SampleTag * tag) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::raf::CVIOutput, and nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, nidas::core::SampleOutputBase::_requestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::raf::CVIOutput::addRequestedSampleTag(), and nidas::core::SampleOutputBase::SampleOutputBase().
addSampleTag()
void PSQLSampleOutput::addSampleTag (const SampleTag * tag) throw (nidas::util::InvalidParameterException)
References DLOG.
Referenced by nidas::dynld::psql::PSQLProcessor::connected().
addSourceSampleTag()
void SampleOutputBase::addSourceSampleTag (const SampleTag * tag) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::core::SampleOutputBase::addSourceSampleTags(), and nidas::core::SampleOutputBase::SampleOutputBase().
addSourceSampleTags()
void SampleOutputBase::addSourceSampleTags (const std::list< const SampleTag * > & tags) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::addSourceSampleTag().
addVariable()
void PSQLSampleOutput::addVariable (const Variable * var) throw (nidas::util::IOException) protected
References nidas::core::VariableConverter::getUnits().
Referenced by createTables().
clone() [1/2]
SampleOutputStream * SampleOutputStream::clone (IOChannel * iochannel) protected virtual inherited
Implements nidas::core::SampleOutput.
References nidas::dynld::SampleOutputStream::SampleOutputStream().
clone() [2/2]
PSQLSampleOutput * PSQLSampleOutput::clone (IOChannel * iochannel = 0) const
References DLOG, name, psqlChannel, and PSQLSampleOutput().
close()
void PSQLSampleOutput::close () throw (nidas::util::IOException) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::dynld::psql::PSQLChannel::close(), and psqlChannel.
connect()
void PSQLSampleOutput::connect () throw (nidas::util::IOException)
References nidas::dynld::psql::PSQLChannel::connect(), DLOG, name, and psqlChannel.
connected() [1/2]
void PSQLSampleOutput::connected (IOChannel * ochan) throw () virtual
Implementation of IOChannelRequester::connected().
How an IOChannel calls back to a SampleConnectionRequester that it is connected. The ConnectionRequester can then return a clone of itself if the IOChannel is a new instance.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::dynld::SampleOutputStream::connected(), and DLOG.
connected() [2/2]
void PSQLSampleOutput::connected (SampleOutput * origout, SampleOutput * newout) throw ()
References DLOG.
createNextFile()
void SampleOutputBase::createNextFile (dsm_time_t tt) inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_headerSource, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::IOChannel::createFile(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::HeaderSource::sendDefaultHeader(), and nidas::core::HeaderSource::sendHeader().
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
createTables()
void PSQLSampleOutput::createTables () throw (nidas::util::IOException) protected
References addVariable(), nidas::core::Variable::getName(), nidas::core::SampleTag::getVariables(), rate, submitCommand(), and tagsByRate.
Referenced by init().
disconnect()
void SampleOutputBase::disconnect () protected inherited
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
This is typically called in the receive() method of a SampleOutput if it gets an IOException when writing data. A common implementation of a connection requester is to delete this SampleOutput after the removing it from the sample stream. So the caller method should immediately return after calling disconnect().
Exceptions
nidas::util::IOException
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::close(), nidas::core::SampleConnectionRequester::disconnect(), nidas::core::SampleOutputBase::getName(), and ILOG.
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
dropAllTables()
void PSQLSampleOutput::dropAllTables () throw () protected
References DLOG, getName(), PLOG, submitCommand(), and nidas::util::Exception::what().
Referenced by init().
flush()
void PSQLSampleOutput::flush () throw (nidas::util::IOException) virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implements nidas::core::SampleClient.
References nidas::dynld::psql::PSQLChannel::flush(), and psqlChannel.
fromDOMElement()
void PSQLSampleOutput::fromDOMElement (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::IOChannel::createIOChannel(), and DLOG.
getDSMConfig()
const DSMConfig* nidas::core::SampleOutputBase::getDSMConfig () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
getDSMConfigs()
const std::list< const DSMConfig * > & PSQLSampleOutput::getDSMConfigs () const
References dsms.
getFd()
int nidas::dynld::psql::PSQLSampleOutput::getFd () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
getIOChannel()
IOChannel* nidas::core::SampleOutputBase::getIOChannel () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), nidas::dynld::AsciiOutput::connect(), nidas::core::SampleOutputBase::createNextFile(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::AsciiOutput::printHeader(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::raf::CVIOutput::requestConnection(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::raf::CVIOutput::setIOChannel(), nidas::dynld::isff::GOESOutput::setIOChannel(), and nidas::dynld::UDPSampleOutput::write().
getIOStream()
IOStream* nidas::dynld::SampleOutputStream::getIOStream () inline inherited
Get the IOStream of this SampleOutputStream.
SampleOutputStream owns the pointer and will delete the IOStream in its destructor. The IOStream is available after a SammpleOutputStream is constructed with an connected IOChannel, or after the connected() method has been called and before close().
getLatency()
float nidas::core::SampleOutputBase::getLatency () const inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_latency.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream().
getName()
const std::string& nidas::dynld::psql::PSQLSampleOutput::getName () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
References name.
Referenced by dropAllTables(), and init().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNextFileTime()
dsm_time_t nidas::core::SampleOutputBase::getNextFileTime () const inline inherited
References nidas::core::SampleOutputBase::_nextFileTime.
Referenced by nidas::dynld::AsciiOutput::receive(), and nidas::dynld::raf::CVIOutput::receive().
getNumDiscardedSamples()
size_t nidas::core::SampleOutputBase::getNumDiscardedSamples () const inline inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
getOriginal()
SampleOutput* nidas::core::SampleOutputBase::getOriginal () const inline virtual inherited
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_original.
getParameter()
const Parameter * SampleOutputBase::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::SampleOutputBase::_parameters.
getParameters()
const std::list<const Parameter*>& nidas::core::SampleOutputBase::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleOutputBase::_constParameters.
Referenced by nidas::dynld::UDPSampleOutput::fromDOMElement().
getPseudoPort()
int nidas::dynld::psql::PSQLSampleOutput::getPseudoPort () const inline
getReconnectDelaySecs()
int SampleOutputBase::getReconnectDelaySecs () const virtual inherited
Base class implementation.
If setReconnectDelaySecs() has been called on this SampleOutput, then that value will be returned. Otherwise this will return the value of the IOChannel.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_reconnectDelaySecs, and nidas::core::IOChannel::getReconnectDelaySecs().
getRequestedSampleTags()
std::list< const SampleTag * > SampleOutputBase::getRequestedSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::GOESOutput::run(), and nidas::core::SampleOutputBase::SampleOutputBase().
getSampleConnectionRequester()
SampleConnectionRequester* nidas::core::SampleOutputBase::getSampleConnectionRequester () inline protected inherited
References nidas::core::SampleOutputBase::_connectionRequester.
getSourceSampleTags()
list< const SampleTag * > SampleOutputBase::getSourceSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase().
incrementDiscardedSamples()
size_t nidas::core::SampleOutputBase::incrementDiscardedSamples () inline protected inherited
References nidas::core::SampleOutputBase::_nsamplesDiscarded.
init()
void PSQLSampleOutput::init () throw ()
References createTables(), DLOG, dropAllTables(), nidas::util::Logger::getInstance(), getName(), initializeGlobalAttributes(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
initializeGlobalAttributes()
void PSQLSampleOutput::initializeGlobalAttributes () throw (nidas::util::IOException) protected
References DLOG, nidas::core::Project::getInstance(), nidas::core::Project::getName(), and submitCommand().
Referenced by init().
isRaw()
bool nidas::dynld::psql::PSQLSampleOutput::isRaw () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
receive()
bool PSQLSampleOutput::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::util::Logger::getInstance(), nidas::core::SampleTag::getRate(), nidas::util::Logger::log(), LOG_ERR, USECS_PER_MSEC, USECS_PER_SEC, and nidas::util::Exception::what().
requestConnection()
void PSQLSampleOutput::requestConnection (SampleConnectionRequester * requester) throw (nidas::util::IOException) virtual
Request a connection, but don't wait for it.
Requester will be notified via SampleConnectionRequester interface when the connection has been made. It is not necessary to call this method if a SampleOutput is constructed with a connected IOChannel.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleOutputBase.
References DLOG.
setDSMConfig()
void nidas::core::SampleOutputBase::setDSMConfig (const DSMConfig * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_dsm.
setDSMConfigs()
void PSQLSampleOutput::setDSMConfigs (const std::list< const DSMConfig * > & val)
References dsms.
setHeaderSource()
void nidas::core::SampleOutputBase::setHeaderSource (HeaderSource * val) inline virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_headerSource.
Referenced by ARLIngest::run(), NidsMerge::run(), and SensorExtract::run().
setIOChannel()
void SampleOutputBase::setIOChannel (IOChannel * val) virtual inherited
Set the IOChannel for this SampleOutput.
This IOChannel is not yet connected. The IOChannel must be connected before the SampleOutput is used for I/O, using the requestConnection() method, or by IOChannel::connect() followed by SampleOutput::connected(IOChannel*).
Reimplemented in nidas::dynld::isff::GOESOutput, and nidas::dynld::raf::CVIOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::IOChannel::setDSMConfig().
Referenced by nidas::dynld::AsciiOutput::connect(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::raf::CVIOutput::setIOChannel(), and nidas::dynld::isff::GOESOutput::setIOChannel().
setLatency()
void SampleOutputStream::setLatency (float val) virtual inherited
Outgoing data is buffered in an IOStream.
The stream will be flushed when the difference between successive time tags exceeds this value. This is a useful parameter for real-time applications.
Parameters
val Number of seconds between physical writes. Default is set in SampleOutputBase.
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SampleOutputBase.
References nidas::dynld::SampleOutputStream::_maxUsecs, nidas::core::SampleOutputBase::getName(), nidas::core::SampleOutputBase::setLatency(), and USECS_PER_SEC.
setName()
void nidas::dynld::psql::PSQLSampleOutput::setName (const std::string & val) inline virtual
Reimplemented from nidas::core::SampleOutputBase.
References name.
setPseudoPort()
void nidas::dynld::psql::PSQLSampleOutput::setPseudoPort (int val) inline
setReconnectDelaySecs()
void SampleOutputBase::setReconnectDelaySecs (int val) virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_reconnectDelaySecs.
Referenced by nidas::dynld::raf::SyncServer::init().
submitCommand()
void PSQLSampleOutput::submitCommand (const std::string & command) throw (nidas::util::IOException) protected
Referenced by createTables(), dropAllTables(), and initializeGlobalAttributes().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/3]
size_t SampleOutputStream::write (const Sample * samp, bool streamFlush) protected inherited
Exceptions
nidas::util::IOException
References nidas::dynld::SampleOutputStream::_iostream, nidas::util::LogContext::active(), nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getHeaderLength(), nidas::core::Sample::getHeaderPtr(), nidas::core::Sample::getRawId(), nidas::core::SampleHeader::getSizeOf(), nidas::core::Sample::getTimeTag(), nidas::util::LogContext::log(), LOG_VERBOSE, nidas::core::SampleHeader::setTimeTag(), and nidas::core::IOStream::write().
write() [2/3]
size_t SampleOutputBase::write (const void * buf, size_t len) virtual inherited
Raw write method, typically used to write the initial header.
Exceptions
nidas::util::IOException
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_iochan, len, and nidas::core::IOChannel::write().
write() [3/3]
size_t SampleOutputStream::write (const void * buf, size_t len, bool streamFlush) inherited
Exceptions
nidas::util::IOException
References nidas::dynld::SampleOutputStream::_iostream, nidas::dynld::SampleOutputStream::flush(), len, and nidas::core::IOStream::write().
Member Data Documentation
_connectionRequester
SampleConnectionRequester* nidas::core::SampleOutputBase::_connectionRequester private inherited
Referenced by nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::disconnect(), nidas::core::SampleOutputBase::getSampleConnectionRequester(), and nidas::core::SampleOutputBase::requestConnection().
_constParameters
std::list<const Parameter*> nidas::core::SampleOutputBase::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::SampleOutputBase::addParameter(), and nidas::core::SampleOutputBase::getParameters().
_constRequestedTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_constRequestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::getRequestedSampleTags().
_dsm
const DSMConfig* nidas::core::SampleOutputBase::_dsm private inherited
Referenced by nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::SampleOutputBase::setDSMConfig().
_headerSource
HeaderSource* nidas::core::SampleOutputBase::_headerSource private inherited
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::setHeaderSource().
_iochan
IOChannel* nidas::core::SampleOutputBase::_iochan private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::getFd(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getReconnectDelaySecs(), nidas::core::SampleOutputBase::requestConnection(), nidas::core::SampleOutputBase::SampleOutputBase(), nidas::core::SampleOutputBase::setIOChannel(), nidas::core::SampleOutputBase::write(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_iostream
IOStream* nidas::dynld::SampleOutputStream::_iostream protected inherited
Referenced by nidas::dynld::SampleOutputStream::close(), nidas::dynld::SampleOutputStream::flush(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::SampleOutputStream::write(), and nidas::dynld::SampleOutputStream::~SampleOutputStream().
_lastFlushTT
dsm_time_t nidas::dynld::SampleOutputStream::_lastFlushTT private inherited
Timetag of last flush of IOStream.
_latency
float nidas::core::SampleOutputBase::_latency private inherited
Referenced by nidas::core::SampleOutputBase::getLatency(), and nidas::core::SampleOutputBase::setLatency().
_maxUsecs
int nidas::dynld::SampleOutputStream::_maxUsecs private inherited
Maximum number of microseconds between physical writes.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream(), and nidas::dynld::SampleOutputStream::setLatency().
_name
std::string nidas::core::SampleOutputBase::_name protected inherited
Referenced by nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
_nextFileTime
dsm_time_t nidas::core::SampleOutputBase::_nextFileTime private inherited
Referenced by nidas::core::SampleOutputBase::close(), nidas::core::SampleOutputBase::connected(), nidas::core::SampleOutputBase::createNextFile(), and nidas::core::SampleOutputBase::getNextFileTime().
_nsamplesDiscarded
size_t nidas::core::SampleOutputBase::_nsamplesDiscarded private inherited
Referenced by nidas::core::SampleOutputBase::getNumDiscardedSamples(), and nidas::core::SampleOutputBase::incrementDiscardedSamples().
_original
SampleOutput* nidas::core::SampleOutputBase::_original private inherited
Pointer to the SampleOutput that I was cloned from.
Referenced by nidas::core::SampleOutputBase::getOriginal().
_parameters
std::map<std::string,Parameter*> nidas::core::SampleOutputBase::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleOutputBase::getParameter(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_reconnectDelaySecs
int nidas::core::SampleOutputBase::_reconnectDelaySecs private inherited
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs(), and nidas::core::SampleOutputBase::setReconnectDelaySecs().
_requestedTags
std::list<SampleTag*> nidas::core::SampleOutputBase::_requestedTags private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), and nidas::core::SampleOutputBase::~SampleOutputBase().
_sourceTags
std::list<const SampleTag*> nidas::core::SampleOutputBase::_sourceTags private inherited
Referenced by nidas::core::SampleOutputBase::addSourceSampleTag(), and nidas::core::SampleOutputBase::getSourceSampleTags().
_tagsMutex
nidas::util::Mutex nidas::core::SampleOutputBase::_tagsMutex mutable private inherited
Referenced by nidas::core::SampleOutputBase::addRequestedSampleTag(), nidas::core::SampleOutputBase::addSourceSampleTag(), nidas::core::SampleOutputBase::getRequestedSampleTags(), and nidas::core::SampleOutputBase::getSourceSampleTags().
connectionRequester
SampleConnectionRequester* nidas::dynld::psql::PSQLSampleOutput::connectionRequester protected
dberrors
int nidas::dynld::psql::PSQLSampleOutput::dberrors protected
dsms
std::list<const DSMConfig*> nidas::dynld::psql::PSQLSampleOutput::dsms protected
Referenced by addDSMConfig(), getDSMConfigs(), and setDSMConfigs().
first
bool nidas::dynld::psql::PSQLSampleOutput::first protected
missingValue
float nidas::dynld::psql::PSQLSampleOutput::missingValue protected
name
std::string nidas::dynld::psql::PSQLSampleOutput::name protected
Referenced by clone(), connect(), getName(), and setName().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
psqlChannel
PSQLChannel* nidas::dynld::psql::PSQLSampleOutput::psqlChannel protected
Referenced by clone(), close(), connect(), flush(), and ~PSQLSampleOutput().
tablesByRate
std::map<float,std::string> nidas::dynld::psql::PSQLSampleOutput::tablesByRate protected
tagsById
std::map<dsm_sample_id_t,const SampleTag*> nidas::dynld::psql::PSQLSampleOutput::tagsById protected
tagsByRate
std::map<float,const SampleTag*> nidas::dynld::psql::PSQLSampleOutput::tagsByRate protected
Referenced by createTables().
The documentation for this class was generated from the following files:
nidas/dynld/psql/PSQLSampleOutput.h
nidas/dynld/psql/PSQLSampleOutput.cc