nidas: nidas::core::SampleStats Class Reference
nidas::core::SampleStats Class Reference
A source of samples.
#include <SampleStats.h>
Public Member Functions
SampleStats ()
long long getNumBytes () const
void addNumBytes (int n)
size_t getNumSamples () const
void addNumSamples (int n)
dsm_time_t getLastTimeTag () const
void setLastTimeTag (dsm_time_t val)
Private Attributes
long long _nbytes
dsm_time_t _lastTT
size_t _nsamples
Detailed Description
A source of samples.
A SampleSource maintains a list of SampleClients. When a SampleSource has a Sample ready, it will call the receive method of all its SampleClients. SampleClients register/unregister with a SampleSource via the addSampleClient/removeSampleClient methods.
Constructor & Destructor Documentation
SampleStats()
nidas::core::SampleStats::SampleStats () inline
Member Function Documentation
addNumBytes()
void nidas::core::SampleStats::addNumBytes (int n) inline
References _nbytes.
addNumSamples()
void nidas::core::SampleStats::addNumSamples (int n) inline
References _nsamples.
getLastTimeTag()
dsm_time_t nidas::core::SampleStats::getLastTimeTag () const inline
References _lastTT.
Referenced by nidas::dynld::RawSampleService::printClock(), nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
getNumBytes()
long long nidas::core::SampleStats::getNumBytes () const inline
References _nbytes.
Referenced by nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
getNumSamples()
size_t nidas::core::SampleStats::getNumSamples () const inline
References _nsamples.
Referenced by nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
setLastTimeTag()
void nidas::core::SampleStats::setLastTimeTag (dsm_time_t val) inline
References _lastTT.
Member Data Documentation
_lastTT
dsm_time_t nidas::core::SampleStats::_lastTT private
Referenced by getLastTimeTag(), and setLastTimeTag().
_nbytes
long long nidas::core::SampleStats::_nbytes private
Referenced by addNumBytes(), and getNumBytes().
_nsamples
size_t nidas::core::SampleStats::_nsamples private
Referenced by addNumSamples(), and getNumSamples().
The documentation for this class was generated from the following file:
nidas/core/SampleStats.h