nidas: nidas::core::SampleConnectionRequester Class Reference
nidas::core::SampleConnectionRequester Class Reference abstract
Interface for an object that requests connections SampleOutputs.
#include <ConnectionRequester.h>
Public Member Functions
virtual ~SampleConnectionRequester ()
virtual void connect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they are connected.
virtual void disconnect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
Detailed Description
Interface for an object that requests connections SampleOutputs.
Constructor & Destructor Documentation
~SampleConnectionRequester()
virtual nidas::core::SampleConnectionRequester::~SampleConnectionRequester () inline virtual
Member Function Documentation
connect()
virtual void nidas::core::SampleConnectionRequester::connect (SampleOutput * output) throw () pure virtual
How SampleOutputs notify their SampleConnectionRequester that they are connected.
Implemented in nidas::dynld::StatisticsProcessor, nidas::dynld::SampleProcessor, nidas::dynld::raf::SyncServer, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::raf::CVIProcessor, nidas::core::SampleArchiver, and nidas::core::DSMEngine.
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), and nidas::core::SampleOutputBase::connected().
disconnect()
virtual void nidas::core::SampleConnectionRequester::disconnect (SampleOutput * output) throw () pure virtual
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
Implemented in nidas::dynld::StatisticsProcessor, nidas::dynld::SampleProcessor, nidas::dynld::raf::SyncServer, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::raf::CVIProcessor, nidas::core::SampleArchiver, and nidas::core::DSMEngine.
Referenced by nidas::core::SampleOutputBase::disconnect(), and nidas::dynld::psql::PSQLProcessor::disconnect().
The documentation for this class was generated from the following file:
nidas/core/ConnectionRequester.h