nidas: nidas::core::ProjectConfig Class Reference
nidas::core::ProjectConfig Class Reference
#include <ProjectConfigs.h>
Public Member Functions
ProjectConfig ()
const std::string & getName () const
void setName (const std::string &val)
const std::string & getXMLName () const
void setXMLName (const std::string &val)
const nidas::util::UTime & getBeginTime () const
void setBeginTime (const nidas::util::UTime &val)
const nidas::util::UTime & getEndTime () const
void setEndTime (const nidas::util::UTime &val)
void addEnvironmentVariable (const std::string &name, const std::string &value)
Add an environment variable to this ProjectConfig.
std::map< std::string, std::string > getEnvironmentVariables () const
void putenv () const
Update the process environment with the current list of environment variables in the ProjectConfig.
void initProject (Project &project) const
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node) const
Private Attributes
std::string _name
std::string _xmlName
nidas::util::UTime _beginTime
nidas::util::UTime _endTime
std::map< std::string, std::string > _envVars
Constructor & Destructor Documentation
ProjectConfig()
ProjectConfig::ProjectConfig ()
References getBeginTime(), setEndTime(), and USECS_PER_DAY.
Member Function Documentation
addEnvironmentVariable()
void ProjectConfig::addEnvironmentVariable (const std::string & name, const std::string & value)
Add an environment variable to this ProjectConfig.
The actual process environment is not effected. After doing addEnvironmentVariable() one or more times, use ProjectConfig::putenv() to update the actual process environment. Set value to an empty string to remove a variable from the environment.
References _envVars.
fromDOMElement()
void ProjectConfig::fromDOMElement (const xercesc::DOMElement * node)
Exceptions
nidas::util::InvalidParameterException
References _envVars, getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), nidas::util::UTime::parse(), setBeginTime(), setEndTime(), setName(), setXMLName(), and nidas::util::Exception::what().
Referenced by nidas::core::ProjectConfigs::fromDOMElement().
getBeginTime()
const nidas::util::UTime& nidas::core::ProjectConfig::getBeginTime () const inline
References _beginTime.
Referenced by nidas::core::ProjectConfigs::addConfigByTime(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), nidas::core::ProjectConfigTimeComparator::operator()(), ProjectConfig(), DataPrep::run(), StatsProcess::run(), and toDOMElement().
getEndTime()
const nidas::util::UTime& nidas::core::ProjectConfig::getEndTime () const inline
References _endTime.
Referenced by nidas::core::ProjectConfigs::addConfigByTime(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), nidas::core::ProjectConfigTimeComparator::operator()(), DataPrep::run(), StatsProcess::run(), and toDOMElement().
getEnvironmentVariables()
std::map<std::string,std::string> nidas::core::ProjectConfig::getEnvironmentVariables () const inline
References _envVars.
getName()
const std::string& nidas::core::ProjectConfig::getName () const inline
References _name.
Referenced by nidas::core::ProjectConfigs::addConfigByName(), ProjConfigIO::addConfigByTime(), fromDOMElement(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), putenv(), and toDOMElement().
getXMLName()
const std::string& nidas::core::ProjectConfig::getXMLName () const inline
References _xmlName.
Referenced by ProjConfigIO::getConfig(), ProjConfigIO::getConfigForTime(), initProject(), ProjConfigIO::listConfigs(), DataPrep::run(), StatsProcess::run(), nidas::core::DSMServerApp::run(), and toDOMElement().
initProject()
void ProjectConfig::initProject (Project & project) const
Parameters
project the project, by reference.
Exceptions
nidas::core::XMLException
nidas::util::InvalidParameterException
References nidas::util::Process::expandEnvVars(), nidas::core::Project::fromDOMElement(), getXMLName(), nidas::core::parseXMLConfigFile(), and putenv().
Referenced by StatsProcess::listOutputSamples(), DataPrep::run(), StatsProcess::run(), and nidas::core::DSMServerApp::run().
putenv()
void ProjectConfig::putenv () const
Update the process environment with the current list of environment variables in the ProjectConfig.
References _envVars, nidas::util::Process::getEnvVar(), getName(), and nidas::util::Process::setEnvVar().
Referenced by initProject().
setBeginTime()
void nidas::core::ProjectConfig::setBeginTime (const nidas::util::UTime & val) inline
References _beginTime.
Referenced by ProjConfigIO::addConfigByTime(), and fromDOMElement().
setEndTime()
void nidas::core::ProjectConfig::setEndTime (const nidas::util::UTime & val) inline
References _endTime.
Referenced by ProjConfigIO::addConfigByTime(), fromDOMElement(), ProjectConfig(), and ProjConfigIO::termConfig().
setName()
void nidas::core::ProjectConfig::setName (const std::string & val) inline
References _name.
Referenced by ProjConfigIO::addConfigByTime(), and fromDOMElement().
setXMLName()
void nidas::core::ProjectConfig::setXMLName (const std::string & val) inline
References _xmlName.
Referenced by ProjConfigIO::addConfigByTime(), and fromDOMElement().
toDOMElement()
xercesc::DOMElement * ProjectConfig::toDOMElement (xercesc::DOMElement * node) const
Exceptions
xercesc::DOMException
References _envVars, getBeginTime(), getEndTime(), getName(), nidas::core::DOMable::getNamespaceURI(), getXMLName(), and nidas::core::XDOMElement::setAttributeValue().
Referenced by toDOMParent().
toDOMParent()
xercesc::DOMElement * ProjectConfig::toDOMParent (xercesc::DOMElement * parent) const
Exceptions
xercesc::DOMException
References nidas::core::DOMable::getNamespaceURI(), and toDOMElement().
Referenced by nidas::core::ProjectConfigs::toDOMElement().
Member Data Documentation
_beginTime
nidas::util::UTime nidas::core::ProjectConfig::_beginTime private
Referenced by getBeginTime(), and setBeginTime().
_endTime
nidas::util::UTime nidas::core::ProjectConfig::_endTime private
Referenced by getEndTime(), and setEndTime().
_envVars
std::map<std::string,std::string> nidas::core::ProjectConfig::_envVars private
Referenced by addEnvironmentVariable(), fromDOMElement(), getEnvironmentVariables(), putenv(), and toDOMElement().
_name
std::string nidas::core::ProjectConfig::_name private
Referenced by getName(), and setName().
_xmlName
std::string nidas::core::ProjectConfig::_xmlName private
Referenced by getXMLName(), and setXMLName().
The documentation for this class was generated from the following files:
nidas/core/ProjectConfigs.h
nidas/core/ProjectConfigs.cc