nidas: nidas::core::MultipleUDPSockets Class Reference
nidas::core::MultipleUDPSockets Class Reference
#include <MultipleUDPSockets.h>
Public Member Functions
MultipleUDPSockets ()
MultipleUDPSockets (const MultipleUDPSockets &x)
MultipleUDPSockets * clone () const
Derived classes must provide clone.
IOChannel * connect ()
void connected (nidas::util::DatagramSocket *sock, const nidas::util::Inet4PacketInfoX &pktinfo) throw ()
size_t getBufferSize () const throw ()
Return suggested buffer length.
size_t read (void *, size_t)
size_t write (const void *buf, size_t len)
size_t write (const struct iovec *iov, int iovcnt)
void close ()
int getFd () const
void fromDOMElement (const xercesc::DOMElement *)
void addClient (const ConnectionInfo &info)
From the Inet4PacketInfoX associated with the received request, determine if we need to create a new socket to send data to the requester.
void removeClient (const nidas::util::Inet4SocketAddress &remoteSAddr)
void removeClient (nidas::util::DatagramSocket *)
void setDataPort (unsigned short val)
unsigned short getDataPort () const
void setRequestType (enum McSocketRequest val)
enum McSocketRequest getRequestType () const
bool isRequester () const
Does this McSocket request connections, or does it listen for incoming connections.
void setRequester (bool val)
void setName (const std::string &val)
const std::string & getName () const
void requestConnection (IOChannelRequester *service)
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
void setNonBlocking (bool val)
Do setNonBlocking(val) on underlying socket.
bool isNonBlocking () const
Return isNonBlocking() of underlying socket.
void setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress &val)
const nidas::util::Inet4SocketAddress & getInet4McastSocketAddress () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Attributes
IOChannelRequester * _iochanRequester
MyMcSocket _mcsocket
Private Member Functions
void handleChangedSockets ()
Private Attributes
nidas::util::Mutex _socketMutex
std::list< std::pair< nidas::util::DatagramSocket *, nidas::util::Inet4SocketAddress > > _sockets
std::list< std::pair< nidas::util::DatagramSocket *, nidas::util::Inet4SocketAddress > > _pendingSockets
std::list< nidas::util::DatagramSocket * > _pendingRemoveSockets
std::map< nidas::util::Inet4SocketAddress, nidas::util::Inet4Address > _multicastInterfaces
The local multicast interface of each remote client.
std::map< nidas::util::Inet4Address, std::set< nidas::util::Inet4SocketAddress > > _multicastClients
Remote clients of each multicast interface.
std::map< nidas::util::Inet4Address, nidas::util::DatagramSocket * > _multicastSockets
Socket of each multicast interface.
std::map< nidas::util::Inet4SocketAddress, nidas::util::DatagramSocket * > _unicastSockets
Unicast Sockets for each destination.
bool _socketsChanged
unsigned short _dataPortNumber
std::string _name
bool _amRequester
bool _firstRead
bool _newInput
bool _nonBlocking
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
MultipleUDPSockets() [1/2]
MultipleUDPSockets::MultipleUDPSockets ()
References nidas::core::McSocketUDP::setName().
Referenced by clone().
MultipleUDPSockets() [2/2]
MultipleUDPSockets::MultipleUDPSockets (const MultipleUDPSockets & x)
References nidas::core::McSocketUDP::setName().
Member Function Documentation
addClient()
void MultipleUDPSockets::addClient (const ConnectionInfo & info)
From the Inet4PacketInfoX associated with the received request, determine if we need to create a new socket to send data to the requester.
If this is a new destination address for unicast packets add a new nidas::util::DatagramSocket. Or, if the requester sent a multicast request, and it was received on an interface which has not received requests before, then add a new nidas::util::MulticastSocket on that interface.
References _multicastClients, _multicastInterfaces, _multicastSockets, _pendingSockets, _socketMutex, _socketsChanged, _unicastSockets, nidas::util::Inet4NetworkInterface::getAddress(), getDataPort(), nidas::core::ConnectionInfo::getDestinationAddress(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::core::McSocketUDP::getInet4McastSocketAddress(), nidas::core::ConnectionInfo::getInterface(), nidas::core::ConnectionInfo::getRemoteSocketAddress(), ILOG, nidas::util::Inet4Address::isMultiCastAddress(), nidas::util::Mutex::lock(), nidas::util::MulticastSocket::setInterface(), nidas::util::MulticastSocket::setMulticastLoop(), nidas::util::Inet4SocketAddress::setPort(), nidas::util::Inet4SocketAddress::toAddressString(), and nidas::util::Mutex::unlock().
Referenced by connect().
clone()
MultipleUDPSockets * MultipleUDPSockets::clone () const virtual
Derived classes must provide clone.
Reimplemented from nidas::core::McSocketUDP.
References MultipleUDPSockets().
close()
void MultipleUDPSockets::close () virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::McSocketUDP.
References _pendingSockets, _socketMutex, _sockets, _socketsChanged, nidas::util::DatagramSocket::close(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
connect()
IOChannel * MultipleUDPSockets::connect () virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::McSocketUDP.
References nidas::core::McSocketUDP::_mcsocket, nidas::util::McSocket< SocketT >::accept(), addClient(), nidas::util::Inet4PacketInfo::getDestinationAddress(), nidas::util::Inet4PacketInfo::getInterface(), nidas::util::Inet4PacketInfoX::getRemoteSocketAddress(), nidas::core::McSocketUDP::isNonBlocking(), nidas::core::IOChannel::setConnectionInfo(), and nidas::core::DatagramSocket::setNonBlocking().
connected()
void MultipleUDPSockets::connected (nidas::util::DatagramSocket * sock, const nidas::util::Inet4PacketInfoX & pktinfo) throw () virtual
Reimplemented from nidas::core::McSocketUDP.
References ILOG, nidas::core::IOChannel::setConnectionInfo(), and nidas::core::DatagramSocket::setNonBlocking().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void MultipleUDPSockets::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::McSocketUDP.
References nidas::util::Process::expandEnvVars(), nidas::util::Inet4Address::getByName(), nidas::util::Logger::getInstance(), nidas::core::McSocketUDP::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), nidas::util::Logger::log(), LOG_WARNING, NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, port, nidas::core::McSocketUDP::setInet4McastSocketAddress(), nidas::core::McSocketUDP::setNonBlocking(), nidas::core::McSocketUDP::setRequester(), nidas::core::McSocketUDP::setRequestType(), and nidas::core::UDP_PROCESSED_SAMPLE_FEED.
getBufferSize()
size_t MultipleUDPSockets::getBufferSize () const throw () virtual
Return suggested buffer length.
Reimplemented from nidas::core::IOChannel.
References _socketMutex, _sockets, and nidas::util::DatagramSocket::getReceiveBufferSize().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDataPort()
unsigned short nidas::core::MultipleUDPSockets::getDataPort () const inline
References _dataPortNumber.
Referenced by addClient().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int MultipleUDPSockets::getFd () const virtual
Reimplemented from nidas::core::McSocketUDP.
References _socketMutex, _sockets, and nidas::util::DatagramSocket::getFd().
getInet4McastSocketAddress()
const nidas::util::Inet4SocketAddress& nidas::core::McSocketUDP::getInet4McastSocketAddress () const inline inherited
References nidas::core::McSocketUDP::_mcsocket, and nidas::util::McSocket< SocketT >::getInet4McastSocketAddress().
Referenced by addClient().
getName()
const std::string& nidas::core::McSocketUDP::getName () const inline virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::McSocketUDP::_name.
Referenced by nidas::core::McSocketUDP::fromDOMElement(), and fromDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
enum McSocketRequest nidas::core::McSocketUDP::getRequestType () const inline virtual inherited
Reimplemented from nidas::core::IOChannel.
References nidas::core::McSocketUDP::_mcsocket, and nidas::util::McSocket< SocketT >::setRequestType().
handleChangedSockets()
void MultipleUDPSockets::handleChangedSockets () private
References _pendingRemoveSockets, _pendingSockets, _socketMutex, _sockets, _socketsChanged, nidas::util::DatagramSocket::getLocalSocketAddress(), nidas::util::Mutex::lock(), nidas::util::SocketAddress::toAddressString(), nidas::util::Mutex::unlock(), and WLOG.
Referenced by write().
isNewInput()
virtual bool nidas::core::McSocketUDP::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References nidas::core::McSocketUDP::_newInput.
isNonBlocking()
bool nidas::core::McSocketUDP::isNonBlocking () const inline virtual inherited
Return isNonBlocking() of underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References nidas::core::McSocketUDP::_nonBlocking.
Referenced by nidas::core::McSocketUDP::connect(), connect(), and nidas::core::McSocketUDP::connected().
isRequester()
bool nidas::core::McSocketUDP::isRequester () const inline inherited
Does this McSocket request connections, or does it listen for incoming connections.
References nidas::core::McSocketUDP::_amRequester.
Referenced by nidas::core::McSocketUDP::connect(), nidas::core::McSocketUDP::fromDOMElement(), and nidas::core::McSocketUDP::requestConnection().
read()
size_t nidas::core::MultipleUDPSockets::read (void * , size_t) inline virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::McSocketUDP.
removeClient() [1/2]
void MultipleUDPSockets::removeClient (const nidas::util::Inet4SocketAddress & remoteSAddr)
References _multicastClients, _multicastInterfaces, _multicastSockets, _pendingRemoveSockets, _socketMutex, _socketsChanged, _unicastSockets, DLOG, ILOG, and nidas::util::Inet4SocketAddress::toAddressString().
Referenced by write().
removeClient() [2/2]
void MultipleUDPSockets::removeClient (nidas::util::DatagramSocket * dsock)
References _multicastClients, _multicastInterfaces, _multicastSockets, _pendingRemoveSockets, _socketMutex, _socketsChanged, _unicastSockets, and ILOG.
requestConnection()
void McSocketUDP::requestConnection (IOChannelRequester * service) virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References nidas::core::McSocketUDP::_iochanRequester, nidas::core::McSocketUDP::_mcsocket, nidas::core::McSocketUDP::isRequester(), nidas::util::McSocket< SocketT >::listen(), and nidas::util::McSocket< SocketT >::request().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), connected(), and nidas::core::McSocket::connected().
setDataPort()
void nidas::core::MultipleUDPSockets::setDataPort (unsigned short val) inline
References _dataPortNumber.
Referenced by nidas::dynld::UDPSampleOutput::fromDOMElement().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setInet4McastSocketAddress()
void nidas::core::McSocketUDP::setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress & val) inline inherited
References nidas::core::McSocketUDP::_mcsocket, and nidas::util::McSocket< SocketT >::setInet4McastSocketAddress().
Referenced by nidas::core::McSocketUDP::fromDOMElement(), and fromDOMElement().
setName()
void nidas::core::McSocketUDP::setName (const std::string & val) inline virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::McSocketUDP::_name.
Referenced by nidas::core::McSocketUDP::McSocketUDP(), and MultipleUDPSockets().
setNonBlocking()
void nidas::core::McSocketUDP::setNonBlocking (bool val) inline virtual inherited
Do setNonBlocking(val) on underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References nidas::core::McSocketUDP::_nonBlocking.
Referenced by nidas::core::McSocketUDP::fromDOMElement(), and fromDOMElement().
setRequester()
void nidas::core::McSocketUDP::setRequester (bool val) inline inherited
References nidas::core::McSocketUDP::_amRequester.
Referenced by nidas::core::McSocketUDP::fromDOMElement(), and fromDOMElement().
setRequestType()
void nidas::core::McSocketUDP::setRequestType (enum McSocketRequest val) inline virtual inherited
Reimplemented from nidas::core::IOChannel.
Referenced by nidas::core::McSocketUDP::fromDOMElement(), and fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t MultipleUDPSockets::write (const struct iovec * iov, int iovcnt) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::McSocketUDP.
References _sockets, _socketsChanged, handleChangedSockets(), ILOG, removeClient(), nidas::util::DatagramSocket::sendto(), and nidas::util::Exception::what().
write() [2/2]
size_t MultipleUDPSockets::write (const void * buf, size_t len) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::McSocketUDP.
References _sockets, _socketsChanged, handleChangedSockets(), ILOG, len, removeClient(), nidas::util::DatagramSocket::sendto(), and nidas::util::Exception::what().
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_amRequester
bool nidas::core::McSocketUDP::_amRequester private inherited
Referenced by nidas::core::McSocketUDP::isRequester(), and nidas::core::McSocketUDP::setRequester().
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dataPortNumber
unsigned short nidas::core::MultipleUDPSockets::_dataPortNumber private
Referenced by getDataPort(), and setDataPort().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_firstRead
bool nidas::core::McSocketUDP::_firstRead private inherited
_iochanRequester
IOChannelRequester* nidas::core::McSocketUDP::_iochanRequester protected inherited
Referenced by nidas::core::McSocketUDP::connected(), and nidas::core::McSocketUDP::requestConnection().
_mcsocket
MyMcSocket nidas::core::McSocketUDP::_mcsocket protected inherited
Referenced by nidas::core::McSocketUDP::close(), nidas::core::McSocketUDP::connect(), connect(), nidas::core::McSocketUDP::getInet4McastSocketAddress(), nidas::core::McSocketUDP::getRequestType(), nidas::core::McSocketUDP::requestConnection(), and nidas::core::McSocketUDP::setInet4McastSocketAddress().
_multicastClients
std::map<nidas::util::Inet4Address,std::set<nidas::util::Inet4SocketAddress> > nidas::core::MultipleUDPSockets::_multicastClients private
Remote clients of each multicast interface.
Referenced by addClient(), and removeClient().
_multicastInterfaces
std::map<nidas::util::Inet4SocketAddress,nidas::util::Inet4Address> nidas::core::MultipleUDPSockets::_multicastInterfaces private
The local multicast interface of each remote client.
Referenced by addClient(), and removeClient().
_multicastSockets
std::map<nidas::util::Inet4Address,nidas::util::DatagramSocket*> nidas::core::MultipleUDPSockets::_multicastSockets private
Socket of each multicast interface.
Referenced by addClient(), and removeClient().
_name
std::string nidas::core::McSocketUDP::_name private inherited
Referenced by nidas::core::McSocketUDP::getName(), and nidas::core::McSocketUDP::setName().
_newInput
bool nidas::core::McSocketUDP::_newInput private inherited
Referenced by nidas::core::McSocketUDP::isNewInput().
_nonBlocking
bool nidas::core::McSocketUDP::_nonBlocking private inherited
Referenced by nidas::core::McSocketUDP::isNonBlocking(), and nidas::core::McSocketUDP::setNonBlocking().
_pendingRemoveSockets
std::list<nidas::util::DatagramSocket*> nidas::core::MultipleUDPSockets::_pendingRemoveSockets private
Referenced by handleChangedSockets(), and removeClient().
_pendingSockets
std::list<std::pair<nidas::util::DatagramSocket*,nidas::util::Inet4SocketAddress> > nidas::core::MultipleUDPSockets::_pendingSockets private
Referenced by addClient(), close(), and handleChangedSockets().
_socketMutex
nidas::util::Mutex nidas::core::MultipleUDPSockets::_socketMutex mutable private
Referenced by addClient(), close(), getBufferSize(), getFd(), handleChangedSockets(), and removeClient().
_sockets
std::list<std::pair<nidas::util::DatagramSocket*,nidas::util::Inet4SocketAddress> > nidas::core::MultipleUDPSockets::_sockets private
Referenced by close(), getBufferSize(), getFd(), handleChangedSockets(), and write().
_socketsChanged
bool nidas::core::MultipleUDPSockets::_socketsChanged private
Referenced by addClient(), close(), handleChangedSockets(), removeClient(), and write().
_unicastSockets
std::map<nidas::util::Inet4SocketAddress,nidas::util::DatagramSocket*> nidas::core::MultipleUDPSockets::_unicastSockets private
Unicast Sockets for each destination.
Referenced by addClient(), and removeClient().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/MultipleUDPSockets.h
nidas/core/MultipleUDPSockets.cc