nidas: nidas::core::Parameter Class Reference
nidas::core::Parameter Class Reference abstract
#include <Parameter.h>
Public Types
enum parType { STRING_PARAM , FLOAT_PARAM , INT_PARAM , BOOL_PARAM }
typedef enum parType parType
Public Member Functions
virtual void assign (const Parameter &)=0
virtual ~Parameter ()
virtual Parameter * clone () const =0
const std::string & getName () const
void setName (const std::string &val)
parType getType () const
virtual int getLength () const =0
virtual double getNumericValue (int i) const
virtual std::string getStringValue (int i) const
virtual void fromDOMElement (const xercesc::DOMElement *, const Dictionary *dict)=0
Static Public Member Functions
static Parameter * createParameter (const xercesc::DOMElement *, const Dictionary *d=0)
Protected Member Functions
Parameter (parType t)
Protected Attributes
std::string _name
parType _type
Member Typedef Documentation
parType
typedef enum parType nidas::core::Parameter::parType
Member Enumeration Documentation
parType
enum nidas::core::Parameter::parType
Enumerator
STRING_PARAM
FLOAT_PARAM
INT_PARAM
BOOL_PARAM
Constructor & Destructor Documentation
~Parameter()
virtual nidas::core::Parameter::~Parameter () inline virtual
Parameter()
nidas::core::Parameter::Parameter (parType t) inline protected
Member Function Documentation
assign()
virtual void nidas::core::Parameter::assign (const Parameter &) pure virtual
Implemented in nidas::core::ParameterT< T >.
clone()
virtual Parameter* nidas::core::Parameter::clone () const pure virtual
Implemented in nidas::core::ParameterT< T >.
Referenced by nidas::core::SampleTag::operator=(), nidas::core::Variable::operator=(), nidas::core::VariableConverter::operator=(), nidas::core::SampleTag::SampleTag(), nidas::core::Variable::Variable(), and nidas::core::VariableConverter::VariableConverter().
createParameter()
Parameter * Parameter::createParameter (const xercesc::DOMElement * node, const Dictionary * d = 0) static
Exceptions
nidas::util::InvalidParameterException
References fromDOMElement(), getLength(), nidas::core::XDOMAttr::getName(), and nidas::core::XDOMAttr::getValue().
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), and nidas::core::SampleOutputBase::fromDOMElement().
fromDOMElement()
virtual void nidas::core::Parameter::fromDOMElement (const xercesc::DOMElement * , const Dictionary * dict) pure virtual
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::ParameterT< T >.
Referenced by createParameter().
getLength()
virtual int nidas::core::Parameter::getLength () const pure virtual
Implemented in nidas::core::ParameterT< T >.
Referenced by nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), createParameter(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::dynld::isff::Wind2D::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::raf::LamsSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::raf::Aircraft::getTailNumber(), nidas::dynld::isff::WindOrienter::handleParameter(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::raf::UHSAS_Serial::open(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::Wind3D::parseParameters(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), nidas::dynld::A2DSensor::validate(), nidas::dynld::IEEE_Float::validate(), nidas::dynld::isff::WisardMote::validate(), nidas::dynld::raf::A2D_Serial::validate(), nidas::dynld::raf::DSMAnalogSensor::validate(), and nidas::dynld::raf::SppSerial::validate().
getName()
const std::string& nidas::core::Parameter::getName () const inline
References _name.
Referenced by nidas::core::DSMSensor::addParameter(), nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleTag::addParameter(), nidas::core::Site::addParameter(), nidas::core::VariableConverter::addParameter(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::core::Project::getParameter(), nidas::core::SampleTag::getParameter(), nidas::dynld::isff::WindOrienter::handleParameter(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::Wind3D::parseParameters(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::A2DSensor::validate(), nidas::dynld::IEEE_Float::validate(), and nidas::dynld::raf::A2D_Serial::validate().
getNumericValue()
double Parameter::getNumericValue (int i) const virtual
References nidas::core::floatNAN.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::dynld::raf::LamsSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::UHSAS_Serial::open(), parseAnalog(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::Wind3D::parseParameters(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), ExtractFast2D::run(), ExtractDMT::run(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::A2DSensor::validate(), nidas::dynld::isff::WisardMote::validate(), nidas::dynld::raf::A2D_Serial::validate(), nidas::dynld::raf::AlicatSDI::validate(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::PIP_Serial::validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::raf::UDPArincSensor::validate().
getStringValue()
std::string Parameter::getStringValue (int i) const virtual
Referenced by nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::Wind2D::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::raf::Aircraft::getTailNumber(), nidas::dynld::isff::WindOrienter::handleParameter(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), ExtractFast2D::run(), ExtractDMT::run(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), sensorTitle(), nidas::dynld::A2DSensor::validate(), nidas::dynld::IEEE_Float::validate(), nidas::dynld::raf::A2D_Serial::validate(), and nidas::dynld::raf::UDPArincSensor::validate().
getType()
parType nidas::core::Parameter::getType () const inline
References _type.
Referenced by nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::PacketInputStream::getGOESProject(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::WindOrienter::handleParameter(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::Wind3D::parseParameters(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::A2DSensor::validate(), nidas::dynld::IEEE_Float::validate(), nidas::dynld::isff::WisardMote::validate(), and nidas::dynld::raf::A2D_Serial::validate().
setName()
void nidas::core::Parameter::setName (const std::string & val) inline
References _name.
Referenced by main(), and nidas::dynld::raf::Aircraft::setTailNumber().
Member Data Documentation
_name
std::string nidas::core::Parameter::_name protected
Referenced by getName(), and setName().
_type
parType nidas::core::Parameter::_type protected
Referenced by getType().
The documentation for this class was generated from the following files:
nidas/core/Parameter.h
nidas/core/Parameter.cc