nidas: DMD_MMAT_test Class Reference
DMD_MMAT_test Class Reference
Public Member Functions
DMD_MMAT_test ()
int usage (const char *argv0)
int parseRunstring (int argc, char *argv[])
void run ()
DMD_MMAT_test ()
int usage (const char *argv0)
int parseRunstring (int argc, char *argv[])
void run ()
Private Attributes
float _rate
string _deviceName
vector< waveout > _waveforms
bool _autocalA2D
vector< const_out > _const_out
bool _verbose
Constructor & Destructor Documentation
DMD_MMAT_test() [1/2]
DMD_MMAT_test::DMD_MMAT_test ()
DMD_MMAT_test() [2/2]
DMD_MMAT_test::DMD_MMAT_test ()
Member Function Documentation
parseRunstring() [1/2]
int DMD_MMAT_test::parseRunstring (int argc, char * argv[])
References _autocalA2D, _deviceName, _rate, _waveforms, waveout::chan, waveout::constant, waveout::len, usage(), waveout::vend, and waveout::vstart.
Referenced by main().
parseRunstring() [2/2]
int DMD_MMAT_test::parseRunstring (int argc, char * argv[])
run() [1/2]
void DMD_MMAT_test::run ()
References _autocalA2D, _deviceName, _rate, _waveforms, DMMAT_D2A_Outputs::active, DMMAT_D2A_Conversion::cmax, DMMAT_D2A_Conversion::cmin, DMMAT_D2A_Outputs::counts, DMMAT_A2D_DO_AUTOCAL, DMMAT_ADD_WAVEFORM, DMMAT_D2A_GET, DMMAT_D2A_GET_CONVERSION, DMMAT_D2A_GET_NOUTPUTS, DMMAT_D2A_OUTPUTS_PER_BRD, DMMAT_D2A_SET, DMMAT_D2A_SET_CONFIG, DMMAT_START, DMMAT_STOP, fd, DMMAT_D2A_Outputs::nout, D2A_Waveform::point, DMMAT_D2A_Conversion::vmax, DMMAT_D2A_Conversion::vmin, and D2A_Config::waveformRate.
Referenced by main().
run() [2/2]
void DMD_MMAT_test::run ()
usage() [1/2]
int DMD_MMAT_test::usage (const char * argv0)
Referenced by parseRunstring().
usage() [2/2]
int DMD_MMAT_test::usage (const char * argv0)
Member Data Documentation
_autocalA2D
bool DMD_MMAT_test::_autocalA2D private
Referenced by parseRunstring(), and run().
_const_out
vector<const_out> DMD_MMAT_test::_const_out private
_deviceName
string DMD_MMAT_test::_deviceName private
Referenced by parseRunstring(), and run().
_rate
float DMD_MMAT_test::_rate private
Referenced by parseRunstring(), and run().
_verbose
bool DMD_MMAT_test::_verbose private
_waveforms
vector<waveout> DMD_MMAT_test::_waveforms private
Referenced by parseRunstring(), and run().
The documentation for this class was generated from the following files:
nidas/apps/dmd_mmat_test.cc
nidas/apps/dmd_mmat_vout_const.cc