nidas: nidas::dynld::StatisticsCruncher Class Reference
nidas::dynld::StatisticsCruncher Class Reference
#include <StatisticsCruncher.h>
Classes
struct sampleInfo
Public Types
enum statsEnumType {
STATS_UNKNOWN , STATS_MINIMUM , STATS_MAXIMUM , STATS_MEAN ,
STATS_VAR , STATS_COV , STATS_FLUX , STATS_RFLUX ,
STATS_SFLUX , STATS_TRIVAR , STATS_PRUNEDTRIVAR , STATS_WINDDIR ,
STATS_SUM
}
Types of statistics I can generate.
typedef enum nidas::dynld::StatisticsCruncher::statsEnumType statisticsType
Types of statistics I can generate.
Public Member Functions
StatisticsCruncher (StatisticsProcessor *proc, const SampleTag *stag, statisticsType type, std::string countsName, bool higherMoments)
Constructor.
~StatisticsCruncher ()
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const SampleTag * > getSampleTags () const
Get the output SampleTags.
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of Resampler::flush().
const SampleStats & getSampleStats () const
bool receive (const Sample *s) throw ()
Method called to pass a sample to this client.
void connect (SampleSource *source)
Connect a SamplePipeline to the cruncher.
void disconnect (SampleSource *source) throw ()
void connect (SampleOutput *output)
Connect a SamplePipeline to the cruncher.
void disconnect (SampleOutput *output)
void setStartTime (const nidas::util::UTime &val)
nidas::util::UTime getStartTime () const
void setEndTime (const nidas::util::UTime &val)
nidas::util::UTime getEndTime () const
long long getPeriodUsecs () const
bool getFillGaps () const
Whether to generate output samples over time gaps.
void setFillGaps (bool val)
Static Public Member Functions
static statisticsType getStatisticsType (const std::string &type)
Protected Member Functions
void attach (SampleSource *source)
void splitNames ()
Split input variable names at periods.
std::string makeName (int i, int j=-1, int k=-1, int l=-1)
Create a derived variable name from input variables i,j,k,l.
std::string makeUnits (int i, int j=-1, int k=-1, int l=-1)
Create a derived units field from input variables i,j,k,l.
std::string makeUnits (const std::vector< std::string > &)
void createCombinations ()
void setupMoments (unsigned int nvars, unsigned int moment)
void setupMinMax (const std::string &)
void setupWindDir ()
void setupCovariances ()
void setupTrivariances ()
void setupPrunedTrivariances ()
void setupFluxes ()
void setupReducedFluxes ()
void setupReducedScalarFluxes ()
void initStats ()
void zeroStats ()
void computeStats ()
void addVariable (const std::string &name, const std::string &longname, const std::string &units)
Private Member Functions
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
StatisticsCruncher (const StatisticsCruncher &)
No copy.
StatisticsCruncher & operator= (const StatisticsCruncher &)
No assignment.
Private Attributes
StatisticsProcessor * _proc
SampleSourceSupport _source
SampleTag _reqTag
std::vector< const Variable * > _reqVariables
unsigned int _ninvars
Number of input variables.
std::string _countsName
Name of counts variable.
bool _numpoints
Does the user want number-of-points output?
dsm_time_t _periodUsecs
bool _crossTerms
Does this cruncher compute cross-terms?
NearestResampler * _resampler
statisticsType _statsType
Types of statistics I can generate.
std::vector< std::vector< std::string > > _splitVarNames
Input variable names, split at dots.
std::string _leadCommon
Portion after the first dot-separated word that is common to all variable names.
std::string _commonSuffix
Trailing portion that is common to all variable names.
SampleTag _outSample
unsigned int _nOutVar
unsigned int _outlen
dsm_time_t _tout
std::map< dsm_sample_id_t, sampleInfo > _sampleMap
float * _xMin
float * _xMax
double * _xSum
double ** _xySum
double * _xyzSum
double * _x4Sum
unsigned int * _nSamples
unsigned int ** _triComb
unsigned int _nsum
Number of simple sums to maintain.
unsigned int _ncov
Number of covariances to compute.
unsigned int _ntri
Number of trivariances to compute.
unsigned int _n1mom
Number of 1st,2nd,3rd,4th moments to compute.
unsigned int _n2mom
unsigned int _n3mom
unsigned int _n4mom
unsigned int _ntot
Total number of products to compute.
bool _higherMoments
const Site * _site
int _station
nidas::util::UTime _startTime
nidas::util::UTime _endTime
bool _fillGaps
Member Typedef Documentation
statisticsType
typedef enum nidas::dynld::StatisticsCruncher::statsEnumType nidas::dynld::StatisticsCruncher::statisticsType
Types of statistics I can generate.
Member Enumeration Documentation
statsEnumType
enum nidas::dynld::StatisticsCruncher::statsEnumType
Types of statistics I can generate.
Enumerator
STATS_UNKNOWN
STATS_MINIMUM
STATS_MAXIMUM
STATS_MEAN
STATS_VAR
STATS_COV
STATS_FLUX
STATS_RFLUX
STATS_SFLUX
STATS_TRIVAR
STATS_PRUNEDTRIVAR
STATS_WINDDIR
STATS_SUM
Constructor & Destructor Documentation
StatisticsCruncher() [1/2]
StatisticsCruncher::StatisticsCruncher (StatisticsProcessor * proc, const SampleTag * stag, statisticsType type, std::string countsName, bool higherMoments)
Constructor.
References _crossTerms, _ninvars, _numpoints, _outSample, _periodUsecs, _reqTag, _reqVariables, _site, _statsType, addSampleTag(), nidas::core::SampleTag::getDSMId(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSpSId(), MSECS_PER_SEC, nidas::core::SampleTag::setDSMId(), nidas::core::SampleTag::setRate(), nidas::core::SampleTag::setSampleId(), STATS_COV, STATS_FLUX, STATS_MAXIMUM, STATS_MEAN, STATS_MINIMUM, STATS_PRUNEDTRIVAR, STATS_RFLUX, STATS_SFLUX, STATS_SUM, STATS_TRIVAR, STATS_UNKNOWN, STATS_VAR, STATS_WINDDIR, and USECS_PER_MSEC.
~StatisticsCruncher()
StatisticsCruncher::~StatisticsCruncher ()
References _nSamples, _ntri, _resampler, _sampleMap, _triComb, _x4Sum, _xMax, _xMin, _xSum, _xySum, _xyzSum, and nidas::dynld::StatisticsCruncher::sampleInfo::varIndices.
StatisticsCruncher() [2/2]
nidas::dynld::StatisticsCruncher::StatisticsCruncher (const StatisticsCruncher &) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::dynld::StatisticsCruncher::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::StatisticsProcessor::connect().
addSampleClientForTag()
void nidas::dynld::StatisticsCruncher::addSampleClientForTag (SampleClient * client, const SampleTag *) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
addSampleTag()
void nidas::dynld::StatisticsCruncher::addSampleTag (const SampleTag * tag) throw () inline private virtual
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Implements nidas::core::SampleSource.
Referenced by StatisticsCruncher().
addVariable()
void StatisticsCruncher::addVariable (const std::string & name, const std::string & longname, const std::string & units) protected
References _nOutVar, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by setupMoments().
attach()
void StatisticsCruncher::attach (SampleSource * source) protected
Exceptions
nidas::util::InvalidParameterException
References _crossTerms, _ninvars, _outSample, _reqTag, _reqVariables, _sampleMap, _station, nidas::core::SampleSource::addSampleClientForTag(), GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getDataIndex(), nidas::core::SampleTag::getDSMId(), nidas::core::SampleTag::getId(), nidas::core::Variable::getLongName(), nidas::core::Variable::getName(), nidas::core::Variable::getSampleTag(), nidas::core::SampleSource::getSampleTags(), nidas::core::SampleTag::getSpSId(), nidas::core::Variable::getStation(), nidas::core::Variable::getType(), nidas::core::Variable::getUnits(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), ILOG, nidas::core::VariableIterator::next(), nidas::core::SampleTag::setStation(), nidas::dynld::StatisticsCruncher::sampleInfo::varIndices, nidas::core::Variable::WEIGHT, nidas::dynld::StatisticsCruncher::sampleInfo::weightsIndex, and WLOG.
Referenced by connect().
computeStats()
void StatisticsCruncher::computeStats () protected
References _higherMoments, _n1mom, _n3mom, _n4mom, _ninvars, _nSamples, _ntot, _ntri, _numpoints, _outlen, _outSample, _periodUsecs, _source, _statsType, _tout, _triComb, _x4Sum, _xMax, _xMin, _xSum, _xySum, _xyzSum, nidas::util::LogContext::active(), nidas::util::dirFromUV(), nidas::core::SampleSourceSupport::distribute(), nidas::core::floatNAN, nidas::util::UTime::format(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleTag::getId(), LOG_VERBOSE, nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), STATS_FLUX, STATS_MAXIMUM, STATS_MEAN, STATS_MINIMUM, STATS_PRUNEDTRIVAR, STATS_RFLUX, STATS_SFLUX, STATS_SUM, STATS_TRIVAR, STATS_VAR, STATS_WINDDIR, and zeroStats().
Referenced by flush().
connect() [1/2]
void nidas::dynld::StatisticsCruncher::connect (SampleOutput * output)
Connect a SamplePipeline to the cruncher.
connect() [2/2]
void StatisticsCruncher::connect (SampleSource * source) virtual
Connect a SamplePipeline to the cruncher.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::Resampler.
References _crossTerms, _outSample, _reqTag, _reqVariables, _resampler, attach(), nidas::core::NearestResampler::connect(), createCombinations(), DLOG, nidas::core::SampleTag::getId(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::SampleSource::getSampleTagIterator(), nidas::core::Variable::getSite(), nidas::core::SampleTag::getStation(), nidas::core::Variable::getStation(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTag::getVariables(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), initStats(), nidas::core::SampleTagIterator::next(), nidas::core::VariableIterator::next(), WLOG, and zeroStats().
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
createCombinations()
void StatisticsCruncher::createCombinations () protected
Exceptions
nidas::util::InvalidParameterException
References _higherMoments, _n1mom, _n2mom, _n3mom, _n4mom, _ncov, _ninvars, _nOutVar, _ntot, _ntri, _outSample, _station, _statsType, _triComb, nidas::util::LogContext::active(), nidas::core::Variable::getName(), nidas::core::Variable::getStation(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTag::getVariables(), nidas::core::VariableIterator::hasNext(), LOG_VERBOSE, nidas::core::VariableIterator::next(), nidas::core::Variable::setStation(), setupCovariances(), setupFluxes(), setupMinMax(), setupMoments(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), setupTrivariances(), setupWindDir(), splitNames(), STATS_COV, STATS_FLUX, STATS_MAXIMUM, STATS_MEAN, STATS_MINIMUM, STATS_PRUNEDTRIVAR, STATS_RFLUX, STATS_SFLUX, STATS_SUM, STATS_TRIVAR, STATS_VAR, STATS_WINDDIR, and VLOG.
Referenced by connect().
disconnect() [1/2]
void nidas::dynld::StatisticsCruncher::disconnect (SampleOutput * output)
disconnect() [2/2]
void StatisticsCruncher::disconnect (SampleSource * source) throw () virtual
Implements nidas::core::Resampler.
Referenced by nidas::dynld::StatisticsProcessor::disconnectSource().
flush()
void StatisticsCruncher::flush () throw () virtual
Implementation of Resampler::flush().
Implements nidas::core::Resampler.
References _ninvars, _nSamples, _periodUsecs, _tout, and computeStats().
Referenced by nidas::dynld::StatisticsProcessor::disconnectSource(), nidas::dynld::StatisticsProcessor::flush(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
getClientCount()
int nidas::dynld::StatisticsCruncher::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
getEndTime()
nidas::util::UTime nidas::dynld::StatisticsCruncher::getEndTime () const inline
getFillGaps()
bool nidas::dynld::StatisticsCruncher::getFillGaps () const inline
Whether to generate output samples over time gaps.
In some circumstances one might be generating statistics for separate time periods, and one does not want to output samples of missing data for the gaps between the periods.
getPeriodUsecs()
long long nidas::dynld::StatisticsCruncher::getPeriodUsecs () const inline
getProcessedSampleSource()
SampleSource* nidas::dynld::StatisticsCruncher::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
getRawSampleSource()
SampleSource* nidas::dynld::StatisticsCruncher::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getSampleStats()
const SampleStats& nidas::dynld::StatisticsCruncher::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
getSampleTagIterator()
SampleTagIterator nidas::dynld::StatisticsCruncher::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
getSampleTags()
std::list<const SampleTag*> nidas::dynld::StatisticsCruncher::getSampleTags () const inline virtual
Get the output SampleTags.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
getStartTime()
nidas::util::UTime nidas::dynld::StatisticsCruncher::getStartTime () const inline
getStatisticsType()
StatisticsCruncher::statisticsType StatisticsCruncher::getStatisticsType (const std::string & type) static
Exceptions
nidas::util::InvalidParameterException
References STATS_COV, STATS_FLUX, STATS_MAXIMUM, STATS_MEAN, STATS_MINIMUM, STATS_PRUNEDTRIVAR, STATS_RFLUX, STATS_SFLUX, STATS_SUM, STATS_TRIVAR, STATS_VAR, and STATS_WINDDIR.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag().
initStats()
void StatisticsCruncher::initStats () protected
References _commonSuffix, _countsName, _leadCommon, _n2mom, _n3mom, _n4mom, _ncov, _ninvars, _nSamples, _nsum, _ntot, _ntri, _numpoints, _outlen, _outSample, _proc, _station, _statsType, _x4Sum, _xMax, _xMin, _xSum, _xySum, _xyzSum, nidas::core::SampleTag::addVariable(), nidas::core::Variable::getName(), nidas::dynld::StatisticsProcessor::getUniqueCountsName(), nidas::core::SampleTag::getVariables(), nidas::core::Variable::setName(), nidas::core::Variable::setStation(), nidas::core::Variable::setType(), nidas::core::Variable::setUnits(), STATS_FLUX, STATS_MAXIMUM, STATS_MINIMUM, STATS_RFLUX, STATS_SFLUX, and nidas::core::Variable::WEIGHT.
Referenced by connect().
makeName()
string StatisticsCruncher::makeName (int i, int j = -1, int k = -1, int l = -1) protected
Create a derived variable name from input variables i,j,k,l.
Specify j,k,l for 2nd,3rd,4th order products.
References _commonSuffix, _leadCommon, and _splitVarNames.
Referenced by setupCovariances(), setupFluxes(), setupMoments(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), and setupTrivariances().
makeUnits() [1/2]
std::string StatisticsCruncher::makeUnits (const std::vector< std::string > & units) protected
makeUnits() [2/2]
string StatisticsCruncher::makeUnits (int i, int j = -1, int k = -1, int l = -1) protected
Create a derived units field from input variables i,j,k,l.
Specify j,k,l for 2nd,3rd,4th order products.
References _reqVariables.
Referenced by setupCovariances(), setupFluxes(), setupMinMax(), setupMoments(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), and setupTrivariances().
operator=()
StatisticsCruncher& nidas::dynld::StatisticsCruncher::operator= (const StatisticsCruncher &) private
No assignment.
receive()
bool StatisticsCruncher::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References nidas::util::LogContext::active(), nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::util::UTime::format(), LOG_VERBOSE, nidas::dynld::StatisticsCruncher::sampleInfo::varIndices, nidas::dynld::StatisticsCruncher::sampleInfo::weightsIndex, and WLOG.
removeSampleClient()
void nidas::dynld::StatisticsCruncher::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::StatisticsProcessor::disconnect(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
removeSampleClientForTag()
void nidas::dynld::StatisticsCruncher::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
removeSampleTag()
void nidas::dynld::StatisticsCruncher::removeSampleTag (const SampleTag *) throw () inline private virtual
Exceptions
Implements nidas::core::SampleSource.
setEndTime()
void nidas::dynld::StatisticsCruncher::setEndTime (const nidas::util::UTime & val) inline
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
setFillGaps()
void nidas::dynld::StatisticsCruncher::setFillGaps (bool val) inline
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
setStartTime()
void StatisticsCruncher::setStartTime (const nidas::util::UTime & val)
References _periodUsecs, _startTime, _tout, and nidas::util::UTime::toUsecs().
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
setupCovariances()
void StatisticsCruncher::setupCovariances () protected
References _ncov, _ninvars, _nOutVar, _nsum, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupFluxes()
void StatisticsCruncher::setupFluxes () protected
References _ncov, _ninvars, _nOutVar, _nsum, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupMinMax()
void StatisticsCruncher::setupMinMax (const std::string &) protected
References _commonSuffix, _leadCommon, _n1mom, _ninvars, _nOutVar, _nsum, _outSample, _splitVarNames, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeUnits(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupMoments()
void StatisticsCruncher::setupMoments (unsigned int nvars, unsigned int moment) protected
References _n1mom, _n2mom, _n3mom, _n4mom, _nsum, _reqVariables, addVariable(), makeName(), and makeUnits().
Referenced by createCombinations(), and setupPrunedTrivariances().
setupPrunedTrivariances()
void StatisticsCruncher::setupPrunedTrivariances () protected
References _n3mom, _ninvars, _nOutVar, _nsum, _ntri, _outSample, _triComb, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), nidas::core::Variable::setUnits(), and setupMoments().
Referenced by createCombinations().
setupReducedFluxes()
void StatisticsCruncher::setupReducedFluxes () protected
References _ncov, _ninvars, _nOutVar, _nsum, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupReducedScalarFluxes()
void StatisticsCruncher::setupReducedScalarFluxes () protected
References _ncov, _ninvars, _nOutVar, _nsum, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupTrivariances()
void StatisticsCruncher::setupTrivariances () protected
References _ninvars, _nOutVar, _nsum, _ntri, _outSample, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), makeName(), makeUnits(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
setupWindDir()
void StatisticsCruncher::setupWindDir () protected
Exceptions
nidas::util::InvalidParameterException
References _commonSuffix, _leadCommon, _n1mom, _nOutVar, _nsum, _outSample, _splitVarNames, nidas::core::SampleTag::addVariable(), nidas::core::Variable::setLongName(), nidas::core::Variable::setName(), and nidas::core::Variable::setUnits().
Referenced by createCombinations().
splitNames()
void StatisticsCruncher::splitNames () protected
Split input variable names at periods.
References _commonSuffix, _leadCommon, _reqVariables, and _splitVarNames.
Referenced by createCombinations().
zeroStats()
void StatisticsCruncher::zeroStats () protected
References _n2mom, _n3mom, _n4mom, _ncov, _ninvars, _nSamples, _nsum, _ntri, _x4Sum, _xMax, _xMin, _xSum, _xySum, and _xyzSum.
Referenced by computeStats(), and connect().
Member Data Documentation
_commonSuffix
std::string nidas::dynld::StatisticsCruncher::_commonSuffix private
Trailing portion that is common to all variable names.
Referenced by initStats(), makeName(), setupMinMax(), setupWindDir(), and splitNames().
_countsName
std::string nidas::dynld::StatisticsCruncher::_countsName private
Name of counts variable.
Referenced by initStats().
_crossTerms
bool nidas::dynld::StatisticsCruncher::_crossTerms private
Does this cruncher compute cross-terms?
Referenced by attach(), connect(), and StatisticsCruncher().
_endTime
nidas::util::UTime nidas::dynld::StatisticsCruncher::_endTime private
_fillGaps
bool nidas::dynld::StatisticsCruncher::_fillGaps private
_higherMoments
bool nidas::dynld::StatisticsCruncher::_higherMoments private
Referenced by computeStats(), and createCombinations().
_leadCommon
std::string nidas::dynld::StatisticsCruncher::_leadCommon private
Portion after the first dot-separated word that is common to all variable names.
Referenced by initStats(), makeName(), setupMinMax(), setupWindDir(), and splitNames().
_n1mom
unsigned int nidas::dynld::StatisticsCruncher::_n1mom private
Number of 1st,2nd,3rd,4th moments to compute.
Referenced by computeStats(), createCombinations(), setupMinMax(), setupMoments(), and setupWindDir().
_n2mom
unsigned int nidas::dynld::StatisticsCruncher::_n2mom private
Referenced by createCombinations(), initStats(), setupMoments(), and zeroStats().
_n3mom
unsigned int nidas::dynld::StatisticsCruncher::_n3mom private
Referenced by computeStats(), createCombinations(), initStats(), setupMoments(), setupPrunedTrivariances(), and zeroStats().
_n4mom
unsigned int nidas::dynld::StatisticsCruncher::_n4mom private
Referenced by computeStats(), createCombinations(), initStats(), setupMoments(), and zeroStats().
_ncov
unsigned int nidas::dynld::StatisticsCruncher::_ncov private
Number of covariances to compute.
Referenced by createCombinations(), initStats(), setupCovariances(), setupFluxes(), setupReducedFluxes(), setupReducedScalarFluxes(), and zeroStats().
_ninvars
unsigned int nidas::dynld::StatisticsCruncher::_ninvars private
Number of input variables.
Referenced by attach(), computeStats(), createCombinations(), flush(), initStats(), setupCovariances(), setupFluxes(), setupMinMax(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), setupTrivariances(), StatisticsCruncher(), and zeroStats().
_nOutVar
unsigned int nidas::dynld::StatisticsCruncher::_nOutVar private
Referenced by addVariable(), createCombinations(), setupCovariances(), setupFluxes(), setupMinMax(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), setupTrivariances(), and setupWindDir().
_nSamples
unsigned int* nidas::dynld::StatisticsCruncher::_nSamples private
Referenced by computeStats(), flush(), initStats(), zeroStats(), and ~StatisticsCruncher().
_nsum
unsigned int nidas::dynld::StatisticsCruncher::_nsum private
Number of simple sums to maintain.
Referenced by initStats(), setupCovariances(), setupFluxes(), setupMinMax(), setupMoments(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), setupTrivariances(), setupWindDir(), and zeroStats().
_ntot
unsigned int nidas::dynld::StatisticsCruncher::_ntot private
Total number of products to compute.
Referenced by computeStats(), createCombinations(), and initStats().
_ntri
unsigned int nidas::dynld::StatisticsCruncher::_ntri private
Number of trivariances to compute.
Referenced by computeStats(), createCombinations(), initStats(), setupPrunedTrivariances(), setupTrivariances(), zeroStats(), and ~StatisticsCruncher().
_numpoints
bool nidas::dynld::StatisticsCruncher::_numpoints private
Does the user want number-of-points output?
Referenced by computeStats(), initStats(), and StatisticsCruncher().
_outlen
unsigned int nidas::dynld::StatisticsCruncher::_outlen private
Referenced by computeStats(), and initStats().
_outSample
SampleTag nidas::dynld::StatisticsCruncher::_outSample private
Referenced by addVariable(), attach(), computeStats(), connect(), createCombinations(), initStats(), setupCovariances(), setupFluxes(), setupMinMax(), setupPrunedTrivariances(), setupReducedFluxes(), setupReducedScalarFluxes(), setupTrivariances(), setupWindDir(), and StatisticsCruncher().
_periodUsecs
dsm_time_t nidas::dynld::StatisticsCruncher::_periodUsecs private
Referenced by computeStats(), flush(), setStartTime(), and StatisticsCruncher().
_proc
StatisticsProcessor* nidas::dynld::StatisticsCruncher::_proc private
Referenced by initStats().
_reqTag
SampleTag nidas::dynld::StatisticsCruncher::_reqTag private
Referenced by attach(), connect(), and StatisticsCruncher().
_reqVariables
std::vector<const Variable*> nidas::dynld::StatisticsCruncher::_reqVariables private
Referenced by attach(), connect(), makeUnits(), setupMoments(), splitNames(), and StatisticsCruncher().
_resampler
NearestResampler* nidas::dynld::StatisticsCruncher::_resampler private
Referenced by connect(), and ~StatisticsCruncher().
_sampleMap
std::map<dsm_sample_id_t,sampleInfo > nidas::dynld::StatisticsCruncher::_sampleMap private
Referenced by attach(), and ~StatisticsCruncher().
_site
const Site* nidas::dynld::StatisticsCruncher::_site private
Referenced by StatisticsCruncher().
_source
SampleSourceSupport nidas::dynld::StatisticsCruncher::_source private
Referenced by computeStats().
_splitVarNames
std::vector<std::vector<std::string> > nidas::dynld::StatisticsCruncher::_splitVarNames private
Input variable names, split at dots.
Referenced by makeName(), setupMinMax(), setupWindDir(), and splitNames().
_startTime
nidas::util::UTime nidas::dynld::StatisticsCruncher::_startTime private
Referenced by setStartTime().
_station
int nidas::dynld::StatisticsCruncher::_station private
Referenced by attach(), createCombinations(), and initStats().
_statsType
statisticsType nidas::dynld::StatisticsCruncher::_statsType private
Types of statistics I can generate.
Referenced by computeStats(), createCombinations(), initStats(), and StatisticsCruncher().
_tout
dsm_time_t nidas::dynld::StatisticsCruncher::_tout private
Referenced by computeStats(), flush(), and setStartTime().
_triComb
unsigned int** nidas::dynld::StatisticsCruncher::_triComb private
Referenced by computeStats(), createCombinations(), setupPrunedTrivariances(), and ~StatisticsCruncher().
_x4Sum
double* nidas::dynld::StatisticsCruncher::_x4Sum private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
_xMax
float* nidas::dynld::StatisticsCruncher::_xMax private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
_xMin
float* nidas::dynld::StatisticsCruncher::_xMin private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
_xSum
double* nidas::dynld::StatisticsCruncher::_xSum private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
_xySum
double** nidas::dynld::StatisticsCruncher::_xySum private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
_xyzSum
double* nidas::dynld::StatisticsCruncher::_xyzSum private
Referenced by computeStats(), initStats(), zeroStats(), and ~StatisticsCruncher().
The documentation for this class was generated from the following files:
nidas/dynld/StatisticsCruncher.h
nidas/dynld/StatisticsCruncher.cc