nidas: nidas/apps/isff/ck_goes.cc File Reference
ck_goes.cc File Reference
#include <nidas/dynld/isff/SE_GOESXmtr.h>
#include <iostream>
Functions
int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::dynld::isff::SE_GOESXmtr::doSelfTest(), nidas::dynld::isff::SE_GOESXmtr::init(), nidas::dynld::isff::GOESXmtr::open(), nidas::dynld::isff::SE_GOESXmtr::printStatus(), nidas::dynld::isff::GOESXmtr::setChannel(), nidas::dynld::isff::GOESXmtr::setId(), nidas::dynld::isff::GOESXmtr::setName(), usage(), and nidas::util::Exception::what().
usage()
int usage (const char * argv0)
Referenced by main().