nidas: nidas::util::SocketImpl Class Reference
nidas::util::SocketImpl Class Reference
Implementation of a socket, providing a C++ interface to system socket calls: socket,bind,listen,accept,setsockopt, etc.
#include <Socket.h>
Public Member Functions
SocketImpl (int domain, int type)
SocketImpl (int fd, const SocketAddress &remoteaddr)
SocketImpl (const SocketImpl &x)
Copy constructor.
SocketImpl & operator= (const SocketImpl &rhs)
Assignment operator.
~SocketImpl ()
int getFd () const
int getDomain () const
Get the domain of this socket: AF_UNIX, AF_INET, etc, from sys/socket.h.
void setBacklog (int val)
const SocketAddress & getLocalSocketAddress () const
Get local socket address of this socket.
int getLocalPort () const
Get local port number of this socket.
const SocketAddress & getRemoteSocketAddress () const
Get remote socket address of this socket.
int getRemotePort () const
Get remote port number of this socket.
void setReuseAddress (bool val)
void setNonBlocking (bool val)
bool isNonBlocking () const
void setTcpNoDelay (bool val)
Set the TCP_NODELAY (man 7 tcp) option on the socket.
bool getTcpNoDelay ()
Get the TCP_NODELAY (man 7 tcp) option on the socket.
void setTimeout (int val)
Set the timeout for receive(), recv(), and recvfrom() methods.
int getTimeout () const
void setKeepAlive (bool val)
Set or unset the SO_KEEPALIVE socket option.
bool getKeepAlive () const
Get the current value of the SO_KEEPALIVE socket option.
void setKeepAliveIdleSecs (int val)
Set the number of seconds a connection needs to be idle before TCP begins sending out keep-alive probes (TCP_KEEPIDLE).
int getKeepAliveIdleSecs () const
Get the current value of TCP_KEEPIDLE on this socket.
int getInQueueSize () const
Get number of bytes currently unread in the local input queue.
int getOutQueueSize () const
Get number of bytes currently unsent in the local output queue.
void close ()
void bind (int port)
void bind (const Inet4Address &addr, int port)
void bind (const SocketAddress &sockaddr)
void listen ()
Socket * accept ()
void connect (const std::string &dest, int port)
void connect (const Inet4Address &addr, int port)
void connect (const SocketAddress &addr)
void receive (DatagramPacketBase &packet)
void receive (DatagramPacketBase &packet, Inet4PacketInfo &info, int flags=0)
size_t recv (void *buf, size_t len, int flags=0)
Receive data on a socket.
size_t recvfrom (void *buf, size_t len, int flags, SocketAddress &from)
void send (const DatagramPacketBase &packet, int flags=0)
size_t send (const void *buf, size_t len, int flags=0)
send data on socket.
size_t send (const struct iovec *iov, int iovcnt, int flags=0)
size_t sendto (const void *buf, size_t len, int flags, const SocketAddress &to)
size_t sendto (const struct iovec *iov, int iovcnt, int flags, const SocketAddress &to)
void sendall (const void *buf, size_t len, int flags=0)
send all data in buffer on socket, repeating send() as necessary, until all data is sent (or an exception occurs).
void joinGroup (Inet4Address groupAddr)
Join a multicast group on all interfaces.
void joinGroup (Inet4Address groupAddr, const Inet4NetworkInterface &)
Join a multicast group on a specific interface.
void leaveGroup (Inet4Address groupAddr)
Leave a multicast group on all interfaces.
void leaveGroup (Inet4Address groupAddr, const Inet4NetworkInterface &iaddr)
Leave a multicast group on a given interface.
void setReceiveBufferSize (int size)
int getReceiveBufferSize ()
void setSendBufferSize (int size)
int getSendBufferSize ()
void setTimeToLive (int val)
int getTimeToLive () const
void setPktInfo (bool val)
Control whether a IP_PKTINFO ancillary message is received with each datagram.
bool getPktInfo () const
void setMulticastLoop (bool val)
Whether to set the IP_MULTICAST_LOOP socket option.
bool getMulticastLoop () const
void setInterface (Inet4Address maddr, const Inet4NetworkInterface &iaddr)
void setInterface (Inet4Address iaddr)
Inet4NetworkInterface getInterface () const
Inet4NetworkInterface getInterface (const std::string &name) const
Inet4NetworkInterface findInterface (const Inet4Address &) const
std::list< Inet4NetworkInterface > getInterfaces () const
void setBroadcastEnable (bool val)
Enable or disable SO_BROADCAST.
bool getBroadcastEnable () const
Protected Member Functions
void getLocalAddr ()
Do system call to determine local address of this socket.
void getRemoteAddr ()
Do system call to determine address of remote end.
Protected Attributes
int _sockdomain
int _socktype
SocketAddress * _localaddr
SocketAddress * _remoteaddr
int _fd
int _backlog
bool _reuseaddr
bool _hasTimeout
struct timespec _timeout
bool _pktInfo
Detailed Description
Implementation of a socket, providing a C++ interface to system socket calls: socket,bind,listen,accept,setsockopt, etc.
This is patterned after java.net.SocketImpl. This class includes methods for both stream (TCP) and datagram (UDP) sockets. We also haven't implemented the socket implementation factory from Java.
This class provides the public copy constructors and assignment operators. Objects of this class can be copied and assigned to without restriction. However, because of this, the destructor does not close the socket file descriptor, so, in general, you should make sure that the socket is closed once at some point.
Constructor & Destructor Documentation
SocketImpl() [1/3]
SocketImpl::SocketImpl (int domain, int type)
Exceptions
IOException
References _fd, _localaddr, _remoteaddr, _sockdomain, _socktype, nidas::util::SocketAddress::clone(), and getLocalAddr().
SocketImpl() [2/3]
SocketImpl::SocketImpl (int fd, const SocketAddress & remoteaddr)
Exceptions
IOException
References getLocalAddr().
SocketImpl() [3/3]
SocketImpl::SocketImpl (const SocketImpl & x)
Copy constructor.
~SocketImpl()
SocketImpl::~SocketImpl ()
References _localaddr, and _remoteaddr.
Member Function Documentation
accept()
Socket * SocketImpl::accept ()
Exceptions
IOException
References _fd, _localaddr, _sockdomain, _socktype, NLOG, nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::ServerSocket::accept().
bind() [1/3]
void SocketImpl::bind (const Inet4Address & addr, int port)
Exceptions
IOException
References bind(), and port.
bind() [2/3]
void SocketImpl::bind (const SocketAddress & sockaddr)
Exceptions
IOException
References _fd, _reuseaddr, _sockdomain, _socktype, bind(), nidas::util::SocketAddress::getConstSockAddrPtr(), getLocalAddr(), nidas::util::SocketAddress::getPort(), nidas::util::SocketAddress::getSockAddrLen(), listen(), nidas::util::SocketAddress::toAddressString(), and WLOG.
bind() [3/3]
void SocketImpl::bind (int port)
Exceptions
IOException
References port.
Referenced by bind(), nidas::util::DatagramSocket::bind(), nidas::util::DatagramSocket::DatagramSocket(), and nidas::util::ServerSocket::ServerSocket().
close()
void SocketImpl::close ()
Exceptions
IOException
References _fd, fd, getLocalSocketAddress(), getRemoteSocketAddress(), and VLOG.
Referenced by nidas::util::Socket::close(), nidas::util::ServerSocket::close(), and nidas::util::DatagramSocket::close().
connect() [1/3]
void SocketImpl::connect (const Inet4Address & addr, int port)
Exceptions
IOException
References connect(), and port.
connect() [2/3]
void SocketImpl::connect (const SocketAddress & addr)
Exceptions
IOException
References _fd, _sockdomain, _socktype, connect(), nidas::util::SocketAddress::getConstSockAddrPtr(), getLocalAddr(), getRemoteAddr(), nidas::util::SocketAddress::getSockAddrLen(), and nidas::util::SocketAddress::toAddressString().
connect() [3/3]
void SocketImpl::connect (const std::string & dest, int port)
Exceptions
UnknownHostException
IOException
References nidas::util::Inet4Address::getByName(), and port.
Referenced by connect(), nidas::util::Socket::connect(), and nidas::util::DatagramSocket::connect().
findInterface()
Inet4NetworkInterface SocketImpl::findInterface (const Inet4Address & iaddr) const
Exceptions
IOException
References nidas::util::Inet4Address::bitsMatch(), and getInterfaces().
Referenced by nidas::util::MulticastSocket::findInterface().
getBroadcastEnable()
bool SocketImpl::getBroadcastEnable () const
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::DatagramSocket::getBroadcastEnable().
getDomain()
int nidas::util::SocketImpl::getDomain () const inline
Get the domain of this socket: AF_UNIX, AF_INET, etc, from sys/socket.h.
References _sockdomain.
Referenced by nidas::util::Socket::getDomain(), nidas::util::ServerSocket::getDomain(), getInQueueSize(), getKeepAlive(), getKeepAliveIdleSecs(), getOutQueueSize(), getTcpNoDelay(), setKeepAlive(), setKeepAliveIdleSecs(), and setTcpNoDelay().
getFd()
int nidas::util::SocketImpl::getFd () const inline
References _fd.
Referenced by nidas::util::Socket::getFd(), nidas::util::ServerSocket::getFd(), nidas::util::DatagramSocket::getFd(), getInterface(), getInterfaces(), and receive().
getInQueueSize()
int SocketImpl::getInQueueSize () const
Get number of bytes currently unread in the local input queue.
This does a call to ioctl(fd, SIOCINQ, &num); See man 7 tcp or udp.
Exceptions
IOException
References _fd, _localaddr, getDomain(), and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::getInQueueSize().
getInterface() [1/2]
Inet4NetworkInterface SocketImpl::getInterface () const
Exceptions
IOException
References _fd, _localaddr, nidas::util::Inet4NetworkInterface::getAddress(), getFd(), nidas::util::Inet4Address::getHostAddress(), getInterfaces(), nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::MulticastSocket::getInterface(), getInterfaces(), and receive().
getInterface() [2/2]
Inet4NetworkInterface SocketImpl::getInterface (const std::string & name) const
Exceptions
IOException
References getFd(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::util::Inet4SocketAddress::toString(), and VLOG.
getInterfaces()
list< Inet4NetworkInterface > SocketImpl::getInterfaces () const
Exceptions
IOException
References getFd(), getInterface(), and VLOG.
Referenced by findInterface(), getInterface(), nidas::util::Socket::getInterfaces(), nidas::util::DatagramSocket::getInterfaces(), nidas::util::MulticastSocket::getInterfaces(), joinGroup(), and leaveGroup().
getKeepAlive()
bool SocketImpl::getKeepAlive () const
Get the current value of the SO_KEEPALIVE socket option.
Exceptions
IOException
References _fd, _localaddr, getDomain(), len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::getKeepAlive(), and setKeepAliveIdleSecs().
getKeepAliveIdleSecs()
int SocketImpl::getKeepAliveIdleSecs () const
Get the current value of TCP_KEEPIDLE on this socket.
Returns
Number of seconds a connection needs to be idle before TCP begins sending out keep-alive probes (TCP_KEEPIDLE).
Exceptions
IOException
References _fd, _localaddr, getDomain(), len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::getKeepAliveIdleSecs().
getLocalAddr()
void SocketImpl::getLocalAddr () protected
Do system call to determine local address of this socket.
Exceptions
IOException
References _fd, _localaddr, _sockdomain, nidas::util::SocketAddress::toString(), and VLOG.
Referenced by bind(), connect(), and SocketImpl().
getLocalPort()
int nidas::util::SocketImpl::getLocalPort () const inline
Get local port number of this socket.
Exceptions
References _localaddr, and nidas::util::SocketAddress::getPort().
Referenced by nidas::util::Socket::getLocalPort(), nidas::util::ServerSocket::getLocalPort(), and nidas::util::DatagramSocket::getLocalPort().
getLocalSocketAddress()
const SocketAddress& nidas::util::SocketImpl::getLocalSocketAddress () const inline
Get local socket address of this socket.
Exceptions
References _localaddr.
Referenced by close(), nidas::util::Socket::getLocalSocketAddress(), nidas::util::ServerSocket::getLocalSocketAddress(), and nidas::util::DatagramSocket::getLocalSocketAddress().
getMulticastLoop()
bool SocketImpl::getMulticastLoop () const
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
getOutQueueSize()
int SocketImpl::getOutQueueSize () const
Get number of bytes currently unsent in the local output queue.
This does a call to ioctl(fd, SIOCOUTQ, &num); See man 7 tcp or udp.
Exceptions
IOException
References _fd, _localaddr, getDomain(), and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::getOutQueueSize().
getPktInfo()
bool nidas::util::SocketImpl::getPktInfo () const inline
References _pktInfo.
Referenced by receive().
getReceiveBufferSize()
int SocketImpl::getReceiveBufferSize ()
Exceptions
IOException
References _fd, _localaddr, nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::Socket::getReceiveBufferSize(), nidas::util::ServerSocket::getReceiveBufferSize(), and nidas::util::DatagramSocket::getReceiveBufferSize().
getRemoteAddr()
void SocketImpl::getRemoteAddr () protected
Do system call to determine address of remote end.
Exceptions
IOException
References _fd, _remoteaddr, _sockdomain, nidas::util::SocketAddress::toString(), and VLOG.
Referenced by connect().
getRemotePort()
int nidas::util::SocketImpl::getRemotePort () const inline
Get remote port number of this socket.
Exceptions
References _remoteaddr, and nidas::util::SocketAddress::getPort().
Referenced by nidas::util::Socket::getRemotePort().
getRemoteSocketAddress()
const SocketAddress& nidas::util::SocketImpl::getRemoteSocketAddress () const inline
Get remote socket address of this socket.
Exceptions
References _remoteaddr.
Referenced by close(), and nidas::util::Socket::getRemoteSocketAddress().
getSendBufferSize()
int SocketImpl::getSendBufferSize ()
Exceptions
IOException
References _fd, _localaddr, nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::Socket::getSendBufferSize(), nidas::util::ServerSocket::getSendBufferSize(), and nidas::util::DatagramSocket::getSendBufferSize().
getTcpNoDelay()
bool SocketImpl::getTcpNoDelay ()
Get the TCP_NODELAY (man 7 tcp) option on the socket.
Returns
true if TCP_NODELAY is set on the socket.
Exceptions
IOException
References _fd, _localaddr, getDomain(), len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::getTcpNoDelay().
getTimeout()
int SocketImpl::getTimeout () const
References _timeout, MSECS_PER_SEC, and NSECS_PER_MSEC.
Referenced by operator=().
getTimeToLive()
int SocketImpl::getTimeToLive () const
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::MulticastSocket::getMulticastLoop(), and nidas::util::MulticastSocket::getTimeToLive().
isNonBlocking()
bool SocketImpl::isNonBlocking () const
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::isNonBlocking(), nidas::util::ServerSocket::isNonBlocking(), and nidas::util::DatagramSocket::isNonBlocking().
joinGroup() [1/2]
void SocketImpl::joinGroup (Inet4Address groupAddr)
Join a multicast group on all interfaces.
Exceptions
IOException
References ELOG, nidas::util::Exception::getErrno(), nidas::util::Inet4NetworkInterface::getFlags(), nidas::util::Inet4Address::getHostAddress(), getInterfaces(), and nidas::util::Exception::toString().
Referenced by nidas::util::MulticastSocket::joinGroup().
joinGroup() [2/2]
void SocketImpl::joinGroup (Inet4Address groupAddr, const Inet4NetworkInterface & iface)
Join a multicast group on a specific interface.
According to "man 7 ip", if the interface adddress "is equal to INADDR_ANY an appropriate interface is chosen by the system", which may not be what you want. This was eth0 on a system with lo,eth0 and eth1.
Exceptions
IOException
References _fd, nidas::util::Inet4NetworkInterface::getAddress(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4Address::getInAddr(), nidas::util::Inet4NetworkInterface::getIndex(), nidas::util::Inet4NetworkInterface::getName(), and VLOG.
leaveGroup() [1/2]
void SocketImpl::leaveGroup (Inet4Address groupAddr)
Leave a multicast group on all interfaces.
Exceptions
IOException
References getInterfaces().
Referenced by nidas::util::MulticastSocket::leaveGroup().
leaveGroup() [2/2]
void SocketImpl::leaveGroup (Inet4Address groupAddr, const Inet4NetworkInterface & iaddr)
Leave a multicast group on a given interface.
Exceptions
IOException
References _fd, nidas::util::Inet4NetworkInterface::getAddress(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4Address::getInAddr(), and nidas::util::Inet4NetworkInterface::getIndex().
listen()
void SocketImpl::listen ()
Exceptions
IOException
References _backlog, _fd, _localaddr, _sockdomain, _socktype, and nidas::util::SocketAddress::toAddressString().
Referenced by bind().
operator=()
SocketImpl & SocketImpl::operator= (const SocketImpl & rhs)
Assignment operator.
References _backlog, _fd, _localaddr, _pktInfo, _remoteaddr, _reuseaddr, _sockdomain, _socktype, nidas::util::SocketAddress::clone(), getTimeout(), and setTimeout().
receive() [1/2]
void SocketImpl::receive (DatagramPacketBase & packet)
Exceptions
IOException
References _fd, _hasTimeout, _localaddr, _timeout, nidas::util::DatagramPacketBase::getDataVoidPtr(), nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSockAddrPtr(), ILOG, recvfrom(), nidas::util::DatagramPacketBase::setLength(), and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::DatagramSocket::receive().
receive() [2/2]
void SocketImpl::receive (DatagramPacketBase & packet, Inet4PacketInfo & info, int flags = 0)
Exceptions
IOException
References _fd, _hasTimeout, _localaddr, _timeout, nidas::util::LogContext::active(), nidas::util::Inet4NetworkInterface::getAddress(), nidas::util::DatagramPacketBase::getDataVoidPtr(), nidas::util::Inet4PacketInfo::getDestinationAddress(), getFd(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4NetworkInterface::getIndex(), nidas::util::Inet4PacketInfo::getInterface(), getInterface(), nidas::util::Inet4PacketInfo::getLocalAddress(), nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::Inet4NetworkInterface::getName(), getPktInfo(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSockAddrPtr(), ILOG, nidas::util::LogContext::log(), LOG_DEBUG, nidas::util::Inet4PacketInfo::setDestinationAddress(), nidas::util::Inet4PacketInfo::setInterface(), nidas::util::DatagramPacketBase::setLength(), nidas::util::Inet4PacketInfo::setLocalAddress(), setPktInfo(), nidas::util::SocketAddress::toAddressString(), nidas::util::Exception::what(), and WLOG.
recv()
size_t SocketImpl::recv (void * buf, size_t len, int flags = 0)
Receive data on a socket.
See "man 2 recv" for values of the flags parameter (none of which have been tested). An EOFException is returned if the remote host does an orderly shutdown of the socket.
Exceptions
IOException
References _fd, _hasTimeout, _localaddr, _timeout, ILOG, len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::recv(), and nidas::util::DatagramSocket::recv().
recvfrom()
size_t SocketImpl::recvfrom (void * buf, size_t len, int flags, SocketAddress & from)
Exceptions
IOException
References _fd, _hasTimeout, _localaddr, _timeout, nidas::util::SocketAddress::getSockAddrLen(), nidas::util::SocketAddress::getSockAddrPtr(), ILOG, len, and nidas::util::SocketAddress::toAddressString().
Referenced by receive(), and nidas::util::DatagramSocket::recvfrom().
send() [1/3]
void SocketImpl::send (const DatagramPacketBase & packet, int flags = 0)
Exceptions
IOException
References _fd, nidas::util::DatagramPacketBase::getConstDataVoidPtr(), nidas::util::DatagramPacketBase::getConstSockAddrPtr(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSocketAddress(), sendto(), nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::DatagramSocket::send(), send(), nidas::util::Socket::send(), and sendall().
send() [2/3]
size_t SocketImpl::send (const struct iovec * iov, int iovcnt, int flags = 0)
Exceptions
IOException
References _fd, _remoteaddr, and nidas::util::SocketAddress::toAddressString().
send() [3/3]
size_t SocketImpl::send (const void * buf, size_t len, int flags = 0)
send data on socket.
See send UNIX man page.
Parameters
buf pointer to buffer.
len number of bytes to send. @flags bitwise OR of flags for send. Default: 0.
Returns
Number of bytes written to socket. If using non-blocking IO, either via setNonBlocking(true), or by setting the MSG_DONTWAIT in flags, and the system function returns EAGAIN or EWOULDBLOCK, then the return value will be 0, and no IOException is thrown.
Exceptions
IOException
References _fd, _remoteaddr, len, send(), and nidas::util::SocketAddress::toAddressString().
sendall()
void SocketImpl::sendall (const void * buf, size_t len, int flags = 0)
send all data in buffer on socket, repeating send() as necessary, until all data is sent (or an exception occurs).
Parameters
buf pointer to buffer.
len number of bytes to send. @flags bitwise OR of flags for send. Default: 0.
Returns
Number of bytes written to socket. It is not recommended to use this method if using non-blocking IO.
Exceptions
IOException
References _fd, _remoteaddr, len, send(), and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::sendall().
sendto() [1/2]
size_t SocketImpl::sendto (const struct iovec * iov, int iovcnt, int flags, const SocketAddress & to)
Exceptions
IOException
References _fd, _remoteaddr, nidas::util::SocketAddress::getConstSockAddrPtr(), nidas::util::SocketAddress::getSockAddrLen(), and nidas::util::SocketAddress::toAddressString().
sendto() [2/2]
size_t SocketImpl::sendto (const void * buf, size_t len, int flags, const SocketAddress & to)
Exceptions
IOException
References _fd, nidas::util::SocketAddress::getConstSockAddrPtr(), nidas::util::SocketAddress::getSockAddrLen(), len, and nidas::util::SocketAddress::toAddressString().
Referenced by send(), and nidas::util::DatagramSocket::sendto().
setBacklog()
void nidas::util::SocketImpl::setBacklog (int val) inline
References _backlog.
Referenced by nidas::util::ServerSocket::ServerSocket().
setBroadcastEnable()
void SocketImpl::setBroadcastEnable (bool val)
Enable or disable SO_BROADCAST.
Note that broadcasting is generally not advised, best to use multicast instead.
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::DatagramSocket::setBroadcastEnable().
setInterface() [1/2]
void SocketImpl::setInterface (Inet4Address iaddr)
Exceptions
IOException
References _fd, _localaddr, nidas::util::Inet4Address::getInAddr(), and nidas::util::SocketAddress::toAddressString().
setInterface() [2/2]
void SocketImpl::setInterface (Inet4Address maddr, const Inet4NetworkInterface & iaddr)
Exceptions
IOException
References _fd, _localaddr, nidas::util::Inet4NetworkInterface::getAddress(), nidas::util::Inet4Address::getHostAddress(), nidas::util::Inet4Address::getInAddr(), nidas::util::Inet4NetworkInterface::getIndex(), nidas::util::Inet4NetworkInterface::getName(), nidas::util::SocketAddress::toAddressString(), and VLOG.
Referenced by nidas::util::MulticastSocket::setInterface().
setKeepAlive()
void SocketImpl::setKeepAlive (bool val)
Set or unset the SO_KEEPALIVE socket option.
Exceptions
IOException
References _fd, _localaddr, getDomain(), len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::setKeepAlive(), and setKeepAliveIdleSecs().
setKeepAliveIdleSecs()
void SocketImpl::setKeepAliveIdleSecs (int val)
Set the number of seconds a connection needs to be idle before TCP begins sending out keep-alive probes (TCP_KEEPIDLE).
Only appropriate for stream (TCP) connections, not datagrams (UDP). Calls setKeepAlive(true) if necessary so that the SO_KEEPALIVE option is set.
Parameters
val Number of seconds.
Exceptions
IOException man 7 tcp: tcp_keepalive_time The number of seconds a connection needs to be idle before TCP begins send- ing out keep-alive probes. Keep-alives are only sent when the SO_KEEPALIVE socket option is enabled. The default value is 7200 seconds (2 hours). An idle connection is terminated after approximately an additional 11 minutes (9 probes an interval of 75 seconds apart) when keep-alive is enabled.
Note that underlying connection tracking mechanisms and application timeouts may be much shorter.
References _fd, _localaddr, getDomain(), getKeepAlive(), len, setKeepAlive(), and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::setKeepAliveIdleSecs().
setMulticastLoop()
void SocketImpl::setMulticastLoop (bool val)
Whether to set the IP_MULTICAST_LOOP socket option.
According to "man 7 ip", IP_MULTICAST_LOOP controls "whether sent multicast packets should be looped back to the local sockets." This behaviour seems to be the default in Linux in that setting this does not seem to be necessary for a process on a host to receive multicast packets that are sent out on one of its interfaces, providing the multicast reader has joined that interface, and a firewall is not blocking them.
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
setNonBlocking()
void SocketImpl::setNonBlocking (bool val)
Exceptions
IOException
References _fd, _localaddr, ILOG, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::ServerSocket::ServerSocket(), nidas::util::Socket::setNonBlocking(), nidas::util::ServerSocket::setNonBlocking(), and nidas::util::DatagramSocket::setNonBlocking().
setPktInfo()
void SocketImpl::setPktInfo (bool val)
Control whether a IP_PKTINFO ancillary message is received with each datagram.
Only supported on DatagramSockets. The IP_PKTINFO message is converted to an Inet4PacketInfo object which is available via the getInet4PacketInfo() method.
Parameters
val if true enable the IP_PKTINFO message, if false, disable.
Exceptions
IOException
References _fd, _localaddr, _pktInfo, len, and nidas::util::SocketAddress::toAddressString().
Referenced by receive(), and nidas::util::DatagramSocket::setPktInfo().
setReceiveBufferSize()
void SocketImpl::setReceiveBufferSize (int size)
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::setReceiveBufferSize(), nidas::util::ServerSocket::setReceiveBufferSize(), and nidas::util::DatagramSocket::setReceiveBufferSize().
setReuseAddress()
void nidas::util::SocketImpl::setReuseAddress (bool val) inline
References _reuseaddr.
setSendBufferSize()
void SocketImpl::setSendBufferSize (int size)
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::setSendBufferSize(), nidas::util::ServerSocket::setSendBufferSize(), and nidas::util::DatagramSocket::setSendBufferSize().
setTcpNoDelay()
void SocketImpl::setTcpNoDelay (bool val)
Set the TCP_NODELAY (man 7 tcp) option on the socket.
This option is only appropriate for TCP sockets.
Parameters
val If true, set TCP_NODELAY. If false unset it.
Exceptions
IOException
References _fd, _localaddr, getDomain(), ILOG, len, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::Socket::setTcpNoDelay().
setTimeout()
void SocketImpl::setTimeout (int val)
Set the timeout for receive(), recv(), and recvfrom() methods.
Parameters
val timeout in milliseconds. 0=no timeout (infinite) The receive methods will return IOTimeoutException if an operation times out.
References _hasTimeout, _timeout, MSECS_PER_SEC, and NSECS_PER_MSEC.
Referenced by operator=(), nidas::util::Socket::setTimeout(), and nidas::util::DatagramSocket::setTimeout().
setTimeToLive()
void SocketImpl::setTimeToLive (int val)
Exceptions
IOException
References _fd, _localaddr, and nidas::util::SocketAddress::toAddressString().
Referenced by nidas::util::MulticastSocket::setMulticastLoop(), and nidas::util::MulticastSocket::setTimeToLive().
Member Data Documentation
_backlog
int nidas::util::SocketImpl::_backlog protected
Referenced by listen(), operator=(), and setBacklog().
_fd
int nidas::util::SocketImpl::_fd protected
Referenced by accept(), bind(), close(), connect(), getBroadcastEnable(), getFd(), getInQueueSize(), getInterface(), getKeepAlive(), getKeepAliveIdleSecs(), getLocalAddr(), getMulticastLoop(), getOutQueueSize(), getReceiveBufferSize(), getRemoteAddr(), getSendBufferSize(), getTcpNoDelay(), getTimeToLive(), isNonBlocking(), joinGroup(), leaveGroup(), listen(), operator=(), receive(), recv(), recvfrom(), send(), sendall(), sendto(), setBroadcastEnable(), setInterface(), setKeepAlive(), setKeepAliveIdleSecs(), setMulticastLoop(), setNonBlocking(), setPktInfo(), setReceiveBufferSize(), setSendBufferSize(), setTcpNoDelay(), setTimeToLive(), and SocketImpl().
_hasTimeout
bool nidas::util::SocketImpl::_hasTimeout protected
Referenced by receive(), recv(), recvfrom(), and setTimeout().
_localaddr
SocketAddress* nidas::util::SocketImpl::_localaddr protected
Referenced by accept(), getBroadcastEnable(), getInQueueSize(), getInterface(), getKeepAlive(), getKeepAliveIdleSecs(), getLocalAddr(), getLocalPort(), getLocalSocketAddress(), getMulticastLoop(), getOutQueueSize(), getReceiveBufferSize(), getSendBufferSize(), getTcpNoDelay(), getTimeToLive(), isNonBlocking(), listen(), operator=(), receive(), recv(), recvfrom(), setBroadcastEnable(), setInterface(), setKeepAlive(), setKeepAliveIdleSecs(), setMulticastLoop(), setNonBlocking(), setPktInfo(), setReceiveBufferSize(), setSendBufferSize(), setTcpNoDelay(), setTimeToLive(), SocketImpl(), and ~SocketImpl().
_pktInfo
bool nidas::util::SocketImpl::_pktInfo protected
Referenced by getPktInfo(), operator=(), and setPktInfo().
_remoteaddr
SocketAddress* nidas::util::SocketImpl::_remoteaddr protected
Referenced by getRemoteAddr(), getRemotePort(), getRemoteSocketAddress(), operator=(), send(), sendall(), sendto(), SocketImpl(), and ~SocketImpl().
_reuseaddr
bool nidas::util::SocketImpl::_reuseaddr protected
Referenced by bind(), operator=(), and setReuseAddress().
_sockdomain
int nidas::util::SocketImpl::_sockdomain protected
Referenced by accept(), bind(), connect(), getDomain(), getLocalAddr(), getRemoteAddr(), listen(), operator=(), and SocketImpl().
_socktype
int nidas::util::SocketImpl::_socktype protected
Referenced by accept(), bind(), connect(), listen(), operator=(), and SocketImpl().
_timeout
struct timespec nidas::util::SocketImpl::_timeout protected
Referenced by getTimeout(), receive(), recv(), recvfrom(), and setTimeout().
The documentation for this class was generated from the following files:
nidas/util/Socket.h
nidas/util/Socket.cc