nidas: nidas::core::DSMServerIterator Class Reference
nidas::core::DSMServerIterator Class Reference
Class for iterating over the DSMServers of a Project.
#include <NidsIterators.h>
Public Member Functions
DSMServerIterator (const Project *)
DSMServerIterator (const Site *)
DSMServerIterator ()
bool hasNext ()
DSMServer * next ()
Private Attributes
const std::list< DSMServer * > * _servers
std::list< DSMServer * >::const_iterator _serverItr
SiteIterator _siteIterator
Detailed Description
Class for iterating over the DSMServers of a Project.
Constructor & Destructor Documentation
DSMServerIterator() [1/3]
DSMServerIterator::DSMServerIterator (const Project * obj)
DSMServerIterator() [2/3]
DSMServerIterator::DSMServerIterator (const Site * obj)
DSMServerIterator() [3/3]
DSMServerIterator::DSMServerIterator ()
Member Function Documentation
hasNext()
bool DSMServerIterator::hasNext ()
References _serverItr, _servers, _siteIterator, nidas::core::Site::getServers(), nidas::core::SiteIterator::hasNext(), and nidas::core::SiteIterator::next().
Referenced by nidas::core::Project::findServer(), nidas::core::Project::findServers(), and nidas::core::DSMServiceIterator::hasNext().
next()
DSMServer* nidas::core::DSMServerIterator::next () inline
References _serverItr.
Referenced by nidas::core::Project::findServer(), nidas::core::Project::findServers(), and nidas::core::DSMServiceIterator::hasNext().
Member Data Documentation
_serverItr
std::list<DSMServer*>::const_iterator nidas::core::DSMServerIterator::_serverItr private
Referenced by hasNext(), and next().
_servers
const std::list<DSMServer*>* nidas::core::DSMServerIterator::_servers private
Referenced by hasNext().
_siteIterator
SiteIterator nidas::core::DSMServerIterator::_siteIterator private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc