nidas: nidas/apps/sync_dump.cc File Reference
sync_dump.cc File Reference
#include <ctime>
#include <nidas/core/FileSet.h>
#include <nidas/util/Logger.h>
#include <nidas/util/auto_ptr.h>
#include <nidas/core/Socket.h>
#include <nidas/dynld/SampleInputStream.h>
#include <nidas/dynld/raf/SyncRecordReader.h>
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <vector>
#include <iterator>
#include <unistd.h>
#include <getopt.h>
Classes
class SyncDumper
Functions
std::string time_format (dsm_time_t tt)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::Logger::createInstance(), nidas::util::LogConfig::level, nidas::util::LOGGER_DEBUG, SyncDumper::parseRunstring(), SyncDumper::run(), nidas::util::Logger::setScheme(), and SyncDumper::setupSignals().
time_format()
std::string time_format (dsm_time_t tt) inline
References nidas::util::UTime::format().
Referenced by SyncDumper::run().