nidas: nidas::core::UnixIOChannel Class Reference
nidas::core::UnixIOChannel Class Reference
Simple implementation of an IOChannel, over an opened file descriptor.
#include <UnixIOChannel.h>
Public Member Functions
UnixIOChannel (const std::string &name, int fd)
Constructor.
~UnixIOChannel ()
Destructor.
UnixIOChannel * clone () const
Clone invokes default copy constructor.
void requestConnection (IOChannelRequester *rqstr)
RequestConnection just returns connected immediately.
IOChannel * connect ()
Pretty simple, we're connected already.
void setNonBlocking (bool val)
Set the state of O_NONBLOCK with fcntl system call.
bool isNonBlocking () const
Do fcntl to determine value of O_NONBLOCK flag.
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
size_t read (void *buf, size_t len)
Do the actual hardware read.
size_t write (const void *buf, size_t len)
Do the actual hardware write.
size_t write (const struct iovec *iov, int iovcnt)
Do the actual hardware write.
void close ()
int getFd () const
const std::string & getName () const
void setName (const std::string &val)
void fromDOMElement (const xercesc::DOMElement *)
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
UnixIOChannel (const UnixIOChannel &x)
Constructor.
Protected Attributes
std::string _name
int _fd
bool _newInput
Private Attributes
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Simple implementation of an IOChannel, over an opened file descriptor.
Constructor & Destructor Documentation
UnixIOChannel() [1/2]
nidas::core::UnixIOChannel::UnixIOChannel (const std::string & name, int fd) inline
Constructor.
Referenced by clone().
~UnixIOChannel()
nidas::core::UnixIOChannel::~UnixIOChannel () inline
Destructor.
Does not close the device.
UnixIOChannel() [2/2]
nidas::core::UnixIOChannel::UnixIOChannel (const UnixIOChannel & x) inline protected
Constructor.
Member Function Documentation
clone()
UnixIOChannel* nidas::core::UnixIOChannel::clone () const inline virtual
Clone invokes default copy constructor.
Implements nidas::core::IOChannel.
References UnixIOChannel().
close()
void nidas::core::UnixIOChannel::close () inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, and getName().
Referenced by HeaderUtil::run().
connect()
IOChannel* nidas::core::UnixIOChannel::connect () inline virtual
Pretty simple, we're connected already.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void nidas::core::UnixIOChannel::fromDOMElement (const xercesc::DOMElement *) inline virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::core::UnixIOChannel::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _fd.
getName()
const std::string& nidas::core::UnixIOChannel::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by close(), isNonBlocking(), read(), setNonBlocking(), and write().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
isNewInput()
virtual bool nidas::core::UnixIOChannel::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _newInput.
isNonBlocking()
bool UnixIOChannel::isNonBlocking () const virtual
Do fcntl to determine value of O_NONBLOCK flag.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, and getName().
read()
size_t nidas::core::UnixIOChannel::read (void * buf, size_t len) inline virtual
Do the actual hardware read.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, _newInput, getName(), and len.
requestConnection()
void nidas::core::UnixIOChannel::requestConnection (IOChannelRequester * rqstr) inline virtual
RequestConnection just returns connected immediately.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References nidas::core::IOChannelRequester::connected().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setName()
void nidas::core::UnixIOChannel::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
setNonBlocking()
void UnixIOChannel::setNonBlocking (bool val) virtual
Set the state of O_NONBLOCK with fcntl system call.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, and getName().
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t nidas::core::UnixIOChannel::write (const struct iovec * iov, int iovcnt) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, _newInput, and getName().
write() [2/2]
size_t nidas::core::UnixIOChannel::write (const void * buf, size_t len) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fd, _newInput, getName(), and len.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_fd
int nidas::core::UnixIOChannel::_fd protected
Referenced by close(), getFd(), isNonBlocking(), read(), setNonBlocking(), and write().
_name
std::string nidas::core::UnixIOChannel::_name protected
Referenced by getName(), and setName().
_newInput
bool nidas::core::UnixIOChannel::_newInput protected
Referenced by isNewInput(), read(), and write().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/UnixIOChannel.h
nidas/core/UnixIOChannel.cc