nidas: nidas::core::FileSet Class Reference
nidas::core::FileSet Class Reference
Implementation of an IOChannel using an nidas::util::FileSet.
#include <FileSet.h>
Public Member Functions
FileSet ()
FileSet (nidas::util::FileSet *fset)
Constructor from a pointer to a nidas::util::FileSet.
~FileSet ()
int getReconnectDelaySecs () const
bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
const std::string & getName () const
void setDir (const std::string &val)
Set the directory portion of the file search path.
void setFileName (const std::string &val)
Set the file portion of the file search path.
void requestConnection (IOChannelRequester *requester)
IOChannel * connect ()
void setNonBlocking (bool val)
bool isNonBlocking () const
void setMount (FsMount *val)
FileSet will own the FsMount.
void mounted ()
This method is called by FsMount when it is done.
FileSet * clone () const
Clone myself.
dsm_time_t createFile (dsm_time_t t, bool exact)
size_t read (void *buf, size_t len)
size_t write (const void *buf, size_t len)
size_t write (const struct iovec *iov, int iovcnt)
void close ()
int getFd () const
void fromDOMElement (const xercesc::DOMElement *node)
const std::string & getCurrentName () const
Get name of current file.
void setStartTime (const nidas::util::UTime &val)
nidas::util::UTime getStartTime () const
void setEndTime (const nidas::util::UTime &val)
nidas::util::UTime getEndTime () const
void setFileLengthSecs (int val)
Set/get the file length in seconds.
int getFileLengthSecs () const
void addFileName (const std::string &val)
long long getFileSize () const
int getLastErrno () const
Get last error value.
void setKeepOpening (bool keepopening)
Set whether the FileSet should keep going to the next file when an error happens opening a file.
bool keepOpening ()
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual void flush ()
Default flush implementation does nothing.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static FileSet * getFileSet (const std::list< std::string > &filenames)
Convienence function to return a pointer to a nidas::core::FileSet, given a list of files.
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
FileSet (const FileSet &x)
Copy constructor.
void setName (const std::string &val)
Recognizeable name of this IOChannel - used for informative messages.
Protected Attributes
nidas::util::FileSet * _fset
std::string _name
IOChannelRequester * _requester
FsMount * _mount
Private Member Functions
FileSet & operator= (const FileSet &)
No assignment.
Private Attributes
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Implementation of an IOChannel using an nidas::util::FileSet.
Constructor & Destructor Documentation
FileSet() [1/3]
FileSet::FileSet ()
Referenced by clone(), and getFileSet().
FileSet() [2/3]
FileSet::FileSet (nidas::util::FileSet * fset)
Constructor from a pointer to a nidas::util::FileSet.
nidas::core::FileSet will own the pointer.
~FileSet()
FileSet::~FileSet ()
References _fset, and _mount.
FileSet() [3/3]
FileSet::FileSet (const FileSet & x) protected
Copy constructor.
References _mount.
Member Function Documentation
addFileName()
void nidas::core::FileSet::addFileName (const std::string & val) inline
References _fset, and nidas::util::FileSet::addFileName().
Referenced by getFileSet(), PacketDecode::run(), and MergeVerifier::run().
clone()
FileSet* nidas::core::FileSet::clone () const inline virtual
Clone myself.
Implements nidas::core::IOChannel.
References FileSet().
Referenced by DataPrep::run(), and StatsProcess::run().
close()
void FileSet::close () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fset, _mount, nidas::core::FsMount::cancel(), nidas::util::FileSet::closeFile(), and nidas::core::FsMount::unmount().
connect()
IOChannel * FileSet::connect () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _mount, and nidas::core::FsMount::mount().
Referenced by nidas::dynld::raf::SyncServer::openStream(), DataDump::run(), and DataStats::run().
createFile()
dsm_time_t FileSet::createFile (dsm_time_t t, bool exact) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::IOChannel.
References _fset, nidas::util::FileSet::createFile(), and nidas::util::UTime::toUsecs().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void FileSet::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References _mount, nidas::core::FsMount::fromDOMElement(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), setDir(), setFileLengthSecs(), and setFileName().
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getCurrentName()
const std::string& nidas::core::FileSet::getCurrentName () const inline
Get name of current file.
References _fset, and nidas::util::FileSet::getCurrentName().
Referenced by nidas::core::GetAdsFileName::execute(), getName(), and nidas::core::SampleArchiver::printStatus().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by setDir(), and setFileName().
getEndTime()
nidas::util::UTime nidas::core::FileSet::getEndTime () const inline
References _fset, and nidas::util::FileSet::getStartTime().
getFd()
int nidas::core::FileSet::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _fset, and nidas::util::FileSet::getFd().
getFileLengthSecs()
int nidas::core::FileSet::getFileLengthSecs () const inline
References _fset, and nidas::util::FileSet::getFileLengthSecs().
getFileSet()
FileSet * FileSet::getFileSet (const std::list< std::string > & filenames) static
Convienence function to return a pointer to a nidas::core::FileSet, given a list of files.
If one or more of the files have a .bz2 suffix, the FileSet returned will be a nidas::core::Bzip2FileSet. Note that a Bzip2FileSet cannot be used to read a non-compressed file, so one should not mix compressed and non-compressed files in the list.
Exceptions
nidas::util::InvalidParameterException
References addFileName(), and FileSet().
Referenced by nidas::dynld::raf::SyncServer::openStream(), DataDump::run(), DataStats::run(), DataPrep::run(), MergeVerifier::run(), NidsMerge::run(), ExtractFast2D::run(), ExtractDMT::run(), SensorExtract::run(), StatsProcess::run(), and SyncDumper::run().
getFileSize()
long long nidas::core::FileSet::getFileSize () const inline
Exceptions
nidas::util::IOException
References _fset, and nidas::util::FileSet::getFileSize().
Referenced by nidas::core::SampleArchiver::printStatus().
getLastErrno()
int nidas::core::FileSet::getLastErrno () const inline
Get last error value.
Should be 0. Currently only supported for an output file, to be queried by a system status thread.
References _fset, and nidas::util::FileSet::getLastErrno().
getName()
const std::string & FileSet::getName () const virtual
Implements nidas::core::IOChannel.
References _name, and getCurrentName().
Referenced by fromDOMElement(), nidas::core::FsMount::mount(), MergeVerifier::run(), NidsMerge::run(), setNonBlocking(), and write().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
int nidas::core::FileSet::getReconnectDelaySecs () const inline virtual
Reimplemented from nidas::core::IOChannel.
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getStartTime()
nidas::util::UTime nidas::core::FileSet::getStartTime () const inline
References _fset, and nidas::util::FileSet::getStartTime().
isNewInput()
bool nidas::core::FileSet::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _fset, and nidas::util::FileSet::isNewFile().
isNonBlocking()
bool nidas::core::FileSet::isNonBlocking () const inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
keepOpening()
bool nidas::core::FileSet::keepOpening () inline
References _fset, and nidas::util::FileSet::keepOpening().
mounted()
void FileSet::mounted ()
This method is called by FsMount when it is done.
References _mount, _requester, nidas::core::IOChannelRequester::connected(), and nidas::core::FsMount::isMounted().
Referenced by nidas::core::FsMount::finished(), and nidas::core::FsMount::mount().
operator=()
FileSet& nidas::core::FileSet::operator= (const FileSet &) private
No assignment.
read()
size_t nidas::core::FileSet::read (void * buf, size_t len) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fset, len, and nidas::util::FileSet::read().
requestConnection()
void FileSet::requestConnection (IOChannelRequester * requester) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _mount, _requester, nidas::core::IOChannelRequester::connected(), nidas::core::FsMount::isMounted(), and nidas::core::FsMount::mount().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDir()
void FileSet::setDir (const std::string & val)
Set the directory portion of the file search path.
This may contain environment variables, and tokens like $DSM, $SITE, $AIRCRAFT.
References _fset, nidas::core::IOChannel::getDSMConfig(), nidas::core::Project::getInstance(), nidas::util::FileSet::getPath(), nidas::util::FileSet::setDir(), and setName().
Referenced by fromDOMElement().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setEndTime()
void nidas::core::FileSet::setEndTime (const nidas::util::UTime & val) inline
References _fset, and nidas::util::FileSet::setEndTime().
Referenced by DataPrep::run(), MergeVerifier::run(), NidsMerge::run(), and StatsProcess::run().
setFileLengthSecs()
void nidas::core::FileSet::setFileLengthSecs (int val) inline
Set/get the file length in seconds.
References _fset, and nidas::util::FileSet::setFileLengthSecs().
Referenced by fromDOMElement(), ARLIngest::run(), NidsMerge::run(), and SensorExtract::run().
setFileName()
void FileSet::setFileName (const std::string & val)
Set the file portion of the file search path.
This may contain environment variables, and tokens like $DSM, $SITE, $AIRCRAFT.
References _fset, nidas::core::IOChannel::getDSMConfig(), nidas::core::Project::getInstance(), nidas::util::FileSet::getPath(), nidas::util::FileSet::setFileName(), and setName().
Referenced by fromDOMElement(), ARLIngest::run(), MergeVerifier::run(), NidsMerge::run(), and SensorExtract::run().
setKeepOpening()
void nidas::core::FileSet::setKeepOpening (bool keepopening) inline
Set whether the FileSet should keep going to the next file when an error happens opening a file.
References _fset, and nidas::util::FileSet::setKeepOpening().
Referenced by NidsMerge::run().
setMount()
void nidas::core::FileSet::setMount (FsMount * val) inline
FileSet will own the FsMount.
References _mount.
setName()
void FileSet::setName (const std::string & val) protected virtual
Recognizeable name of this IOChannel - used for informative messages.
Implements nidas::core::IOChannel.
References _name.
Referenced by setDir(), and setFileName().
setNonBlocking()
void nidas::core::FileSet::setNonBlocking (bool val) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References getName(), and PLOG.
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setStartTime()
void nidas::core::FileSet::setStartTime (const nidas::util::UTime & val) inline
References _fset, and nidas::util::FileSet::setStartTime().
Referenced by DataPrep::run(), MergeVerifier::run(), NidsMerge::run(), and StatsProcess::run().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t nidas::core::FileSet::write (const struct iovec * iov, int iovcnt) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fset, and nidas::util::FileSet::write().
write() [2/2]
size_t nidas::core::FileSet::write (const void * buf, size_t len) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _fset, getName(), len, and nidas::util::FileSet::write().
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_fset
nidas::util::FileSet* nidas::core::FileSet::_fset protected
Referenced by addFileName(), close(), createFile(), getCurrentName(), getEndTime(), getFd(), getFileLengthSecs(), getFileSize(), getLastErrno(), getStartTime(), isNewInput(), keepOpening(), read(), setDir(), setEndTime(), setFileLengthSecs(), setFileName(), setKeepOpening(), setStartTime(), write(), and ~FileSet().
_mount
FsMount* nidas::core::FileSet::_mount protected
Referenced by close(), connect(), FileSet(), fromDOMElement(), mounted(), requestConnection(), setMount(), and ~FileSet().
_name
std::string nidas::core::FileSet::_name protected
Referenced by getName(), and setName().
_requester
IOChannelRequester* nidas::core::FileSet::_requester protected
Referenced by mounted(), and requestConnection().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/FileSet.h
nidas/core/FileSet.cc