nidas: nidas::util::FileSet Class Reference
nidas::util::FileSet Class Reference
A description of a set of output files, consisting of a directory name and a file name format containing UNIX strftime conversion specifiers, like Y, m, etc.
#include <FileSet.h>
Public Member Functions
FileSet ()
constructor
FileSet (const FileSet &x)
Copy constructor.
FileSet & operator= (const FileSet &x)
Assignment operator.
virtual FileSet * clone () const
Virtual constructor.
virtual ~FileSet ()
Destructor.
virtual void setDir (const std::string &val)
Set directory portion of file path.
virtual const std::string & getDir ()
int getFd () const
bool isNewFile () const
virtual void setFileName (const std::string &val)
Set file name portion of file path.
virtual const std::string & getFileName ()
virtual const std::string & getPath ()
Get the full path, the concatenation of getDir() and getFileName().
virtual void addFileName (const std::string &val)
void setFileLengthSecs (int val)
Set/get the file length in seconds.
int getFileLengthSecs () const
virtual UTime createFile (UTime tfile, bool exact)
Create a new file, with a name formed from a time.
void setStartTime (const UTime &val)
UTime getStartTime () const
void setEndTime (const UTime &val)
UTime getEndTime () const
const std::string & getCurrentName () const
Get name of current file.
virtual void closeFile ()
Closes any file currently open.
virtual void openFileForWriting (const std::string &filename)
Open a new file for writing.
void openNextFile ()
Open the next file to be read.
virtual size_t read (void *buf, size_t count)
Read from current file.
virtual size_t write (const void *buf, size_t count)
Write to current file.
virtual size_t write (const struct iovec *iov, int iovcnt)
void checkPathFormat (const UTime &t1, const UTime &t2)
Check that any date or time descriptors, e.g.
std::list< std::string > matchFiles (const UTime &t1, const UTime &t2)
long long getFileSize () const
int getLastErrno () const
Get last error value.
void setKeepOpening (bool keepopening)
Set whether the FileSet should keep going to the next file when an error happens opening a file.
bool keepOpening ()
Static Public Member Functions
static void createDirectory (const std::string &name, mode_t mode)
static std::string getDirPortion (const std::string &path)
Utility function to return the directory portion of a file path.
static std::string getFilePortion (const std::string &path)
Utility function to return the file portion of a file path.
static std::string makePath (const std::string &dir, const std::string &file)
Utility function to create a full path name from a directory and file portion.
Static Public Attributes
static const char pathSeparator = '/'
Protected Member Functions
std::string formatName (const UTime &t1)
Static Protected Member Functions
static void replaceChars (std::string &in, const std::string &pat, const std::string &rep)
Protected Attributes
const std::time_put< char > & _timeputter
bool _newFile
int _lastErrno
This value can get set by getFileSize() which is a const method.
int _fd
bool _keepopening
Private Member Functions
void initialize ()
Private Attributes
std::string _dir
std::string _filename
std::string _currname
std::string _fullpath
UTime _startTime
UTime _endTime
std::list< std::string > _fileset
std::list< std::string >::iterator _fileiter
bool _initialized
long long _fileLength
File length, in microseconds.
Detailed Description
A description of a set of output files, consisting of a directory name and a file name format containing UNIX strftime conversion specifiers, like Y, m, etc.
Typically this class is used by an archive method.
Constructor & Destructor Documentation
FileSet() [1/2]
FileSet::FileSet ()
constructor
Referenced by clone().
FileSet() [2/2]
FileSet::FileSet (const FileSet & x)
Copy constructor.
Only permissable before it is opened.
~FileSet()
FileSet::~FileSet () virtual
Destructor.
Closes current file, ignoring possible IOException if the file isn't open.
References closeFile().
Member Function Documentation
addFileName()
virtual void nidas::util::FileSet::addFileName (const std::string & val) inline virtual
References _fileset.
Referenced by nidas::core::FileSet::addFileName().
checkPathFormat()
void FileSet::checkPathFormat (const UTime & t1, const UTime & t2)
Check that any date or time descriptors, e.g.
"%y", "%m", in the full file path string are in the correct order, so that a default lexical sort will sort the file path names in time order. The descriptors in the path must be in decreasing time-interval order, e.g. year before month, month before day, etc.
Exceptions
IOException
References _fullpath, nidas::util::UTime::format(), and USECS_PER_DAY.
Referenced by matchFiles().
clone()
FileSet * FileSet::clone () const virtual
Virtual constructor.
Only permissable before *this is opened.
References FileSet().
closeFile()
void FileSet::closeFile () virtual
Closes any file currently open.
The base implementation closes the file descriptor. Subclasses override this method to close alternate resources.
Exceptions
IOException
References _currname, _fd, DLOG, and fd.
Referenced by nidas::core::FileSet::close(), createFile(), openNextFile(), operator=(), read(), and ~FileSet().
createDirectory()
void FileSet::createDirectory (const std::string & name, mode_t mode) static
Exceptions
IOException
References DLOG, getDirPortion(), and ILOG.
Referenced by nidas::core::NidasApp::checkPidFile(), createFile(), and nidas::core::FsMount::mount().
createFile()
UTime FileSet::createFile (UTime tfile, bool exact) virtual
Create a new file, with a name formed from a time.
Create a file using a time to create the name.
Parameters
tfile Time to use when creating file name.
exact Use exact time when creating file name, else the time is truncated by getFileLengthSecs.
Returns
Start time of next file, i.e. when to create next file.
Exceptions
IOException Return the time of the next file.
References _currname, _fileLength, _fullpath, _lastErrno, _newFile, closeFile(), createDirectory(), DLOG, nidas::util::UTime::format(), ftime(), getDirPortion(), nidas::util::Exception::getErrno(), ILOG, openFileForWriting(), nidas::util::UTime::toUsecs(), USECS_PER_SEC, nidas::util::Exception::what(), and WLOG.
Referenced by nidas::core::FileSet::createFile().
formatName()
string FileSet::formatName (const UTime & t1) protected
References _fullpath, and nidas::util::UTime::format().
Referenced by initialize().
getCurrentName()
const std::string& nidas::util::FileSet::getCurrentName () const inline
Get name of current file.
References _currname.
Referenced by nidas::core::FileSet::getCurrentName().
getDir()
virtual const std::string& nidas::util::FileSet::getDir () inline virtual
References _dir.
Referenced by setFileName().
getDirPortion()
string FileSet::getDirPortion (const std::string & path) static
Utility function to return the directory portion of a file path.
If the directory portion is empty, returns ".". Uses pathSeparator to determine directory and file portion.
References pathSeparator.
Referenced by nidas::core::NidasApp::checkPidFile(), createDirectory(), createFile(), and matchFiles().
getEndTime()
UTime nidas::util::FileSet::getEndTime () const inline
References _endTime.
getFd()
int nidas::util::FileSet::getFd () const inline
References _fd.
Referenced by nidas::core::FileSet::getFd().
getFileLengthSecs()
int nidas::util::FileSet::getFileLengthSecs () const inline
References _fileLength, and USECS_PER_SEC.
Referenced by nidas::core::FileSet::getFileLengthSecs().
getFileName()
virtual const std::string& nidas::util::FileSet::getFileName () inline virtual
References _filename.
Referenced by setDir().
getFilePortion()
string FileSet::getFilePortion (const std::string & path) static
Utility function to return the file portion of a file path.
Uses pathSeparator to determine directory and file portion.
References pathSeparator.
Referenced by matchFiles().
getFileSize()
long long FileSet::getFileSize () const
Exceptions
IOException
References _currname, _fd, and _lastErrno.
Referenced by nidas::core::FileSet::getFileSize().
getLastErrno()
int nidas::util::FileSet::getLastErrno () const inline
Get last error value.
Should be 0. Currently only supported for an output file, to be queried by a system status thread.
References _lastErrno.
Referenced by nidas::core::FileSet::getLastErrno().
getPath()
virtual const std::string& nidas::util::FileSet::getPath () inline virtual
Get the full path, the concatenation of getDir() and getFileName().
References _fullpath.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getStartTime()
UTime nidas::util::FileSet::getStartTime () const inline
References _startTime.
Referenced by nidas::core::FileSet::getEndTime(), and nidas::core::FileSet::getStartTime().
initialize()
void FileSet::initialize () private
References _endTime, _fileiter, _fileLength, _fileset, _fullpath, _initialized, _startTime, DLOG, formatName(), matchFiles(), nidas::util::UTime::toUsecs(), and USECS_PER_DAY.
Referenced by openNextFile().
isNewFile()
bool nidas::util::FileSet::isNewFile () const inline
References _newFile.
Referenced by nidas::core::FileSet::isNewInput().
keepOpening()
bool nidas::util::FileSet::keepOpening () inline
References _keepopening.
Referenced by nidas::core::FileSet::keepOpening().
makePath()
string FileSet::makePath (const std::string & dir, const std::string & file) static
Utility function to create a full path name from a directory and file portion.
If the directory portion is an empty string, or ".", then the result path will have no directory portion.
References pathSeparator.
Referenced by matchFiles(), setDir(), and setFileName().
matchFiles()
list< string > FileSet::matchFiles (const UTime & t1, const UTime & t2)
Exceptions
IOException
References _fullpath, checkPathFormat(), DLOG, nidas::util::UTime::format(), ftime(), getDirPortion(), getFilePortion(), makePath(), replaceChars(), USECS_PER_DAY, and USECS_PER_HOUR.
Referenced by initialize().
openFileForWriting()
void FileSet::openFileForWriting (const std::string & filename) virtual
Open a new file for writing.
The filename is the path for the new file as generated from the filename template and a time. The base implementation calls open64() and sets the file descriptor.
Exceptions
IOException
References _fd, and _lastErrno.
Referenced by createFile().
openNextFile()
void FileSet::openNextFile ()
Open the next file to be read.
Exceptions
IOException
References _currname, _fd, _fileiter, _fileset, _initialized, _keepopening, _newFile, closeFile(), DLOG, ELOG, ILOG, initialize(), and nidas::util::Exception::what().
Referenced by read().
operator=()
FileSet & FileSet::operator= (const FileSet & x)
Assignment operator.
Only permissable before it is opened.
References _currname, _dir, _endTime, _fileiter, _fileLength, _filename, _fileset, _fullpath, _initialized, _keepopening, _lastErrno, _newFile, _startTime, and closeFile().
read()
size_t FileSet::read (void * buf, size_t count) virtual
Read from current file.
Exceptions
IOException
References _currname, _fd, _newFile, closeFile(), and openNextFile().
Referenced by nidas::core::FileSet::read().
replaceChars()
void FileSet::replaceChars (std::string & in, const std::string & pat, const std::string & rep) static protected
Referenced by matchFiles().
setDir()
void FileSet::setDir (const std::string & val) virtual
Set directory portion of file path.
This may contain strftime conversion specifiers, like Y in order to put a year in the directory name.
References _dir, _fullpath, getFileName(), and makePath().
Referenced by nidas::core::FileSet::setDir().
setEndTime()
void nidas::util::FileSet::setEndTime (const UTime & val) inline
References _endTime.
Referenced by nidas::core::FileSet::setEndTime().
setFileLengthSecs()
void nidas::util::FileSet::setFileLengthSecs (int val) inline
Set/get the file length in seconds.
0 means unlimited.
References _fileLength, and USECS_PER_SEC.
Referenced by nidas::core::FileSet::setFileLengthSecs().
setFileName()
void FileSet::setFileName (const std::string & val) virtual
Set file name portion of file path.
This can contain strftime conversion specifiers. FileSet inserts the pathSeparator between the directory and the file name when creating the full file path string. Otherwise there is no distinction between the directory and file portion.
References _filename, _fullpath, getDir(), and makePath().
Referenced by nidas::core::FileSet::setFileName().
setKeepOpening()
void nidas::util::FileSet::setKeepOpening (bool keepopening) inline
Set whether the FileSet should keep going to the next file when an error happens opening a file.
References _keepopening.
Referenced by nidas::core::FileSet::setKeepOpening().
setStartTime()
void nidas::util::FileSet::setStartTime (const UTime & val) inline
References _startTime.
Referenced by nidas::core::FileSet::setStartTime().
write() [1/2]
size_t FileSet::write (const struct iovec * iov, int iovcnt) virtual
Exceptions
IOException
References _currname, _fd, and _lastErrno.
write() [2/2]
size_t FileSet::write (const void * buf, size_t count) virtual
Write to current file.
Exceptions
IOException
References _currname, _fd, and _lastErrno.
Referenced by nidas::core::FileSet::write().
Member Data Documentation
_currname
std::string nidas::util::FileSet::_currname private
Referenced by closeFile(), createFile(), getCurrentName(), getFileSize(), openNextFile(), operator=(), read(), and write().
_dir
std::string nidas::util::FileSet::_dir private
Referenced by getDir(), operator=(), and setDir().
_endTime
UTime nidas::util::FileSet::_endTime private
Referenced by getEndTime(), initialize(), operator=(), and setEndTime().
_fd
int nidas::util::FileSet::_fd protected
Referenced by closeFile(), getFd(), getFileSize(), openFileForWriting(), openNextFile(), read(), and write().
_fileiter
std::list<std::string>::iterator nidas::util::FileSet::_fileiter private
Referenced by initialize(), openNextFile(), and operator=().
_fileLength
long long nidas::util::FileSet::_fileLength private
File length, in microseconds.
Referenced by createFile(), getFileLengthSecs(), initialize(), operator=(), and setFileLengthSecs().
_filename
std::string nidas::util::FileSet::_filename private
Referenced by getFileName(), operator=(), and setFileName().
_fileset
std::list<std::string> nidas::util::FileSet::_fileset private
Referenced by addFileName(), initialize(), openNextFile(), and operator=().
_fullpath
std::string nidas::util::FileSet::_fullpath private
Referenced by checkPathFormat(), createFile(), formatName(), getPath(), initialize(), matchFiles(), operator=(), setDir(), and setFileName().
_initialized
bool nidas::util::FileSet::_initialized private
Referenced by initialize(), openNextFile(), and operator=().
_keepopening
bool nidas::util::FileSet::_keepopening protected
Referenced by keepOpening(), openNextFile(), operator=(), and setKeepOpening().
_lastErrno
int nidas::util::FileSet::_lastErrno mutable protected
This value can get set by getFileSize() which is a const method.
Referenced by createFile(), getFileSize(), getLastErrno(), openFileForWriting(), operator=(), and write().
_newFile
bool nidas::util::FileSet::_newFile protected
Referenced by createFile(), isNewFile(), openNextFile(), operator=(), and read().
_startTime
UTime nidas::util::FileSet::_startTime private
Referenced by getStartTime(), initialize(), operator=(), and setStartTime().
_timeputter
const std::time_put<char>& nidas::util::FileSet::_timeputter protected
pathSeparator
const char FileSet::pathSeparator = '/' static
Referenced by getDirPortion(), getFilePortion(), and makePath().
The documentation for this class was generated from the following files:
nidas/util/FileSet.h
nidas/util/FileSet.cc