nidas: nidas/linux/usbtwod/usbtwod.c File Reference
usbtwod.c File Reference
#include "usbtwod.h"
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/errno.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/uaccess.h>
#include <linux/usb.h>
#include <linux/poll.h>
#include <linux/timer.h>
#include <linux/moduleparam.h>
#include <nidas/linux/klog.h>
#include <nidas/linux/Revision.h>
Macros
#define REPO_REVISION "unknown"
#define NCAR_VENDOR_ID 0x2D2D
#define USB2D_64_PRODUCT_ID 0x2D00
#define USB2D_32_PRODUCT_ID 0x2D01
#define USB2D_64_V3_PRODUCT_ID 0x2D03
#define TWOD_MUTEX_LOCK(d) mutex_lock(d);
#define TWOD_MUTEX_UNLOCK(d) mutex_unlock(d);
Functions
MODULE_DEVICE_TABLE (usb, twod_table)
static DEFINE_MUTEX (twod_open_lock)
MODULE_PARM_DESC (throttleRate, "desired sampling rate (image/sec). 100/N or 100*N where N is integer, or 0 to sample as fast as possible")
module_param (throttleRate, uint, 0)
static void twod_dev_free (struct usb_twod *dev)
static void twod_dev_delete (struct kref *kref)
static void twod_tas_tx_bulk_callback (struct urb *urb)
static struct urb * twod_make_tas_urb (struct usb_twod *dev)
static int write_tas (struct usb_twod *dev)
static void send_tas_timer_func (struct timer_list *tlist)
static int twod_set_sor_rate (struct usb_twod *dev, int rate)
static int usb_twod_submit_img_urb (struct usb_twod *dev, struct urb *urb)
static int usb_twod_submit_sor_urb (struct usb_twod *dev, struct urb *urb)
static void urb_throttle_func (struct timer_list *tlist)
static void twod_img_rx_bulk_callback (struct urb *urb)
static struct urb * twod_make_img_urb (struct usb_twod *dev)
static void twod_sor_rx_bulk_callback (struct urb *urb)
static struct urb * twod_make_sor_urb (struct usb_twod *dev)
static int twod_open (struct inode *inode, struct file *file)
static int twod_release (struct inode *inode, struct file *file)
static unsigned int twod_poll (struct file *file, poll_table *wait)
static ssize_t twod_read (struct file *file, char __user *buffer, size_t count, loff_t *ppos)
static long twod_ioctl (struct file *file, unsigned int cmd, unsigned long arg)
static int twod_probe (struct usb_interface *interface, const struct usb_device_id *id)
static void twod_disconnect (struct usb_interface *interface)
static int __init usb_twod_init (void)
static void __exit usb_twod_exit (void)
module_init (usb_twod_init)
module_exit (usb_twod_exit)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Chris Webster <cjw@ucar.edu>")
MODULE_DESCRIPTION ("USB PMS-2D Probe Driver")
MODULE_VERSION (REPO_REVISION)
Variables
static struct usb_device_id twod_table []
static unsigned int throttleRate = 0
static struct usb_driver twod_driver
static struct file_operations twod_fops
static struct usb_class_driver usbtwod_64
static struct usb_class_driver usbtwod_32
Macro Definition Documentation
NCAR_VENDOR_ID
#define NCAR_VENDOR_ID 0x2D2D
REPO_REVISION
#define REPO_REVISION "unknown"
TWOD_MUTEX_LOCK
#define TWOD_MUTEX_LOCK (d) mutex_lock(d);
TWOD_MUTEX_UNLOCK
#define TWOD_MUTEX_UNLOCK (d) mutex_unlock(d);
USB2D_32_PRODUCT_ID
#define USB2D_32_PRODUCT_ID 0x2D01
USB2D_64_PRODUCT_ID
#define USB2D_64_PRODUCT_ID 0x2D00
USB2D_64_V3_PRODUCT_ID
#define USB2D_64_V3_PRODUCT_ID 0x2D03
Function Documentation
DEFINE_MUTEX()
static DEFINE_MUTEX (twod_open_lock) static
MODULE_AUTHOR()
MODULE_AUTHOR ("Chris Webster <cjw@ucar.edu>")
MODULE_DESCRIPTION()
MODULE_DESCRIPTION ("USB PMS-2D Probe Driver")
MODULE_DEVICE_TABLE()
MODULE_DEVICE_TABLE (usb , twod_table)
module_exit()
module_exit (usb_twod_exit)
module_init()
module_init (usb_twod_init)
MODULE_LICENSE()
MODULE_LICENSE ("GPL")
module_param()
module_param (throttleRate , uint , 0)
MODULE_PARM_DESC()
MODULE_PARM_DESC (throttleRate , "desired sampling rate (image/sec). 100/N or 100*N where N is integer, or 0 to sample as fast as possible")
MODULE_VERSION()
MODULE_VERSION (REPO_REVISION)
send_tas_timer_func()
static void send_tas_timer_func (struct timer_list * tlist) static
References write_tas().
Referenced by twod_open().
twod_dev_delete()
static void twod_dev_delete (struct kref * kref) static
References twod_dev_free().
Referenced by twod_disconnect(), twod_open(), twod_probe(), and twod_release().
twod_dev_free()
static void twod_dev_free (struct usb_twod * dev) static
Referenced by twod_dev_delete(), and twod_release().
twod_disconnect()
static void twod_disconnect (struct usb_interface * interface) static
References twod_dev_delete(), TWOD_MUTEX_LOCK, TWOD_MUTEX_UNLOCK, usbtwod_32, and usbtwod_64.
twod_img_rx_bulk_callback()
static void twod_img_rx_bulk_callback (struct urb * urb) static
References TWOD_IMGv2_TYPE, TWOD_IMGv3_TYPE, and usb_twod_submit_img_urb().
Referenced by twod_make_img_urb().
twod_ioctl()
static long twod_ioctl (struct file * file, unsigned int cmd, unsigned long arg) static
twod_make_img_urb()
static struct urb* twod_make_img_urb (struct usb_twod * dev) static
References twod_img_rx_bulk_callback().
Referenced by twod_open().
twod_make_sor_urb()
static struct urb* twod_make_sor_urb (struct usb_twod * dev) static
References twod_sor_rx_bulk_callback().
Referenced by twod_open().
twod_make_tas_urb()
static struct urb* twod_make_tas_urb (struct usb_twod * dev) static
References twod_tas_tx_bulk_callback().
Referenced by twod_open().
twod_open()
static int twod_open (struct inode * inode, struct file * file) static
References MSECS_PER_SEC, send_tas_timer_func(), throttleRate, twod_dev_delete(), twod_driver, twod_make_img_urb(), twod_make_sor_urb(), twod_make_tas_urb(), TWOD_MUTEX_LOCK, TWOD_MUTEX_UNLOCK, urb_throttle_func(), usb_twod_submit_img_urb(), and usb_twod_submit_sor_urb().
twod_poll()
static unsigned int twod_poll (struct file * file, poll_table * wait) static
twod_probe()
static int twod_probe (struct usb_interface * interface, const struct usb_device_id * id) static
References twod_dev_delete(), USB2D_64_V3_PRODUCT_ID, usbtwod_32, and usbtwod_64.
twod_read()
static ssize_t twod_read (struct file * file, char __user * buffer, size_t count, loff_t * ppos) static
References buffer, if(), TWOD_IMG_TYPE, TWOD_IMGv2_TYPE, TWOD_IMGv3_TYPE, TWOD_SOR_TYPE, TWOD_SORv3_TYPE, usb_twod_submit_img_urb(), and usb_twod_submit_sor_urb().
twod_release()
static int twod_release (struct inode * inode, struct file * file) static
References if(), throttleRate, twod_dev_delete(), twod_dev_free(), and twod_set_sor_rate().
twod_set_sor_rate()
static int twod_set_sor_rate (struct usb_twod * dev, int rate) static
References rate, and TMSECS_PER_SEC.
Referenced by twod_release().
twod_sor_rx_bulk_callback()
static void twod_sor_rx_bulk_callback (struct urb * urb) static
References if(), TWOD_SOR_TYPE, TWOD_SORv3_TYPE, and usb_twod_submit_sor_urb().
Referenced by twod_make_sor_urb().
twod_tas_tx_bulk_callback()
static void twod_tas_tx_bulk_callback (struct urb * urb) static
Referenced by twod_make_tas_urb().
urb_throttle_func()
static void urb_throttle_func (struct timer_list * tlist) static
Referenced by twod_open().
usb_twod_exit()
static void __exit usb_twod_exit (void) static
References twod_driver.
usb_twod_init()
static int __init usb_twod_init (void) static
References REPO_REVISION, and twod_driver.
usb_twod_submit_img_urb()
static int usb_twod_submit_img_urb (struct usb_twod * dev, struct urb * urb) static
References throttleRate.
Referenced by twod_img_rx_bulk_callback(), twod_open(), and twod_read().
usb_twod_submit_sor_urb()
static int usb_twod_submit_sor_urb (struct usb_twod * dev, struct urb * urb) static
Referenced by twod_open(), twod_read(), and twod_sor_rx_bulk_callback().
write_tas()
static int write_tas (struct usb_twod * dev) static
Referenced by send_tas_timer_func().
Variable Documentation
throttleRate
unsigned int throttleRate = 0 static
Referenced by twod_open(), twod_release(), and usb_twod_submit_img_urb().
twod_driver
static struct usb_driver twod_driver static
Initial value:
= {
        .name = "usbtwod",
        .id_table = twod_table,
        .probe = twod_probe,
        .disconnect = twod_disconnect,
}
Referenced by twod_open(), usb_twod_exit(), and usb_twod_init().
twod_fops
struct file_operations twod_fops static
Initial value:
= {
        .owner = THIS_MODULE,
        .read = twod_read,
        .poll = twod_poll,
        .unlocked_ioctl = twod_ioctl,
        .open = twod_open,
        .release = twod_release,
        .llseek  = no_llseek,
}
twod_table
struct usb_device_id twod_table[] static
Initial value:
= {
        {USB_DEVICE(NCAR_VENDOR_ID, USB2D_64_PRODUCT_ID)},
        {USB_DEVICE(NCAR_VENDOR_ID, USB2D_64_V3_PRODUCT_ID)},
        {USB_DEVICE(NCAR_VENDOR_ID, USB2D_32_PRODUCT_ID)},
        {}
}
usbtwod_32
struct usb_class_driver usbtwod_32 static
Initial value:
= {
        .name = "usbtwod_32_%d",
        .fops = &twod_fops,
        .minor_base = USB_TWOD_32_MINOR_BASE,
}
Referenced by twod_disconnect(), and twod_probe().
usbtwod_64
struct usb_class_driver usbtwod_64 static
Initial value:
= {
        .name = "usbtwod_64_%d",
        .fops = &twod_fops,
        .minor_base = USB_TWOD_64_MINOR_BASE,
}
Referenced by twod_disconnect(), and twod_probe().