nidas: EmeraldDIO Class Reference
EmeraldDIO Class Reference
Public Member Functions
EmeraldDIO ()
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
int doRequest ()
Private Attributes
bool _input
string _devName
int _fd
int _outputVal
Constructor & Destructor Documentation
EmeraldDIO()
EmeraldDIO::EmeraldDIO ()
Member Function Documentation
doRequest()
int EmeraldDIO::doRequest ()
References _devName, _fd, _input, _outputVal, EMERALD_IOCGDIO, EMERALD_IOCGDIOOUT, EMERALD_IOCSDIO, and EMERALD_IOCSDIOOUT.
Referenced by main().
parseRunstring()
int EmeraldDIO::parseRunstring (int argc, char ** argv)
References _devName, _input, _outputVal, and usage().
Referenced by main().
usage()
int EmeraldDIO::usage (const char * argv0)
Referenced by parseRunstring().
Member Data Documentation
_devName
string EmeraldDIO::_devName private
Referenced by doRequest(), and parseRunstring().
_fd
int EmeraldDIO::_fd private
Referenced by doRequest().
_input
bool EmeraldDIO::_input private
Referenced by doRequest(), and parseRunstring().
_outputVal
int EmeraldDIO::_outputVal private
Referenced by doRequest(), and parseRunstring().
The documentation for this class was generated from the following file:
nidas/apps/isff/emerald_dio.cc