nidas: Csat3Sim Class Reference
Csat3Sim Class Reference
Simulate a CSAT3 sonic.
Public Member Functions
Csat3Sim (n_u::SerialPort *p, float rate, int nmessages)
void run ()
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
void sendMessage ()
Implement this to send a message from the simulated sensor.
virtual void writeMessage (const std::string &msg)
Subclasses generate the message to send, then call writeMessage() to send it out.
virtual void writeMessage (const char *buf, std::streamsize l)
overloaded function useful for writing binary data
void interrupt ()
Stop the simulation.
bool isInterrupted () const
n_u::SerialPort * port ()
Protected Member Functions
Looper * getLooper ()
void looperNotify () override
Method called by Looper.
void readPrompts ()
Protected Attributes
n_u::SerialPort * _port
bool _prompted
string _prompt
float _rate
int _nmessages
bool _interrupted
Static Protected Attributes
static Looper * _looper = 0
Private Attributes
int _cntr
Detailed Description
Simulate a CSAT3 sonic.
Constructor & Destructor Documentation
Csat3Sim()
Csat3Sim::Csat3Sim (n_u::SerialPort * p, float rate, int nmessages) inline
Member Function Documentation
getLooper()
Looper * SensorSimulator::getLooper () protected inherited
interrupt()
void SensorSimulator::interrupt () inline inherited
Stop the simulation.
Referenced by FileSim::sendASCIIMessage(), and FileSim::sendBinaryMessage().
isInterrupted()
bool SensorSimulator::isInterrupted () const inline inherited
looperNotify()
void SensorSimulator::looperNotify () override protected virtual inherited
Method called by Looper.
This method should not be a heavy user of resources, since the notification of other clients is delayed until this method finishes. If much work is to be done, this method should post a semaphore for another worker thread to proceed.
Implements nidas::core::LooperClient.
References nidas::util::Exception::what().
port()
n_u::SerialPort* SensorSimulator::port () inline inherited
readPrompts()
void SensorSimulator::readPrompts () protected inherited
run()
void Csat3Sim::run () virtual
Default implementation of run will call the sendMessage() method either after receipt of a prompt or at the given rate if the sensor is not prompted.
run() will return when isInterrupted() is true.
Reimplemented from SensorSimulator.
References _cntr, SensorSimulator::_nmessages, SensorSimulator::_port, SensorSimulator::_rate, nidas::util::SerialPort::getFd(), nidas::util::SerialPort::getName(), nidas::util::SerialPort::read(), running, sendMessage(), USECS_PER_SEC, and nidas::util::SerialPort::write().
sendMessage()
void Csat3Sim::sendMessage () virtual
Implement this to send a message from the simulated sensor.
Exceptions
nidas::util::IOException
Implements SensorSimulator.
References _cntr, SensorSimulator::_port, len, and nidas::util::SerialPort::write().
Referenced by run().
writeMessage() [1/2]
virtual void SensorSimulator::writeMessage (const char * buf, std::streamsize l) inline virtual inherited
overloaded function useful for writing binary data
writeMessage() [2/2]
virtual void SensorSimulator::writeMessage (const std::string & msg) inline virtual inherited
Subclasses generate the message to send, then call writeMessage() to send it out.
Referenced by FileSim::sendASCIIMessage(), FileSim::sendBinaryMessage(), and FixedSim::sendMessage().
Member Data Documentation
_cntr
int Csat3Sim::_cntr private
Referenced by run(), and sendMessage().
_interrupted
bool SensorSimulator::_interrupted protected inherited
_looper
Looper * SensorSimulator::_looper = 0 static protected inherited
_nmessages
int SensorSimulator::_nmessages protected inherited
Referenced by run().
_port
n_u::SerialPort* SensorSimulator::_port protected inherited
Referenced by run(), and sendMessage().
_prompt
string SensorSimulator::_prompt protected inherited
_prompted
bool SensorSimulator::_prompted protected inherited
_rate
float SensorSimulator::_rate protected inherited
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/sensor_sim.cc