nidas: nidas::core::McSocket Class Reference
nidas::core::McSocket Class Reference
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::Socket> to establish a TCP connection.
#include <McSocket.h>
Classes
class MyMcSocket
Public Member Functions
McSocket ()
Constructor.
~McSocket ()
McSocket * clone () const
Derived classes must provide clone.
void setRequestType (enum McSocketRequest val)
enum McSocketRequest getRequestType () const
bool isRequester () const
Does this McSocket request connections, or does it listen for incoming connections.
void setRequester (bool val)
void setName (const std::string &val)
const std::string & getName () const
void requestConnection (IOChannelRequester *service)
IOChannel * connect ()
virtual void connected (nidas::util::Socket *sock, const nidas::util::Inet4PacketInfoX &pktinfo)
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
void setKeepAliveIdleSecs (int val)
int getKeepAliveIdleSecs () const
void setNonBlocking (bool val)
Do setNonBlocking(val) on underlying socket.
bool isNonBlocking () const
Return isNonBlocking() of underlying socket.
size_t read (void *, size_t)
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
size_t write (const void *, size_t)
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
size_t write (const struct iovec *, int)
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
void close ()
int getFd () const
void fromDOMElement (const xercesc::DOMElement *)
void setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress &val)
const nidas::util::Inet4SocketAddress & getInet4McastSocketAddress () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
McSocket (const McSocket &)
Copy constructor.
Protected Attributes
IOChannelRequester * _iochanRequester
MyMcSocket _mcsocket
Private Member Functions
McSocket & operator= (const McSocket &)
No assignment.
Private Attributes
std::string _name
bool _amRequester
bool _firstRead
bool _newInput
int _keepAliveIdleSecs
bool _nonBlocking
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::Socket> to establish a TCP connection.
Constructor & Destructor Documentation
McSocket() [1/2]
McSocket::McSocket ()
Constructor.
References setName().
Referenced by clone().
~McSocket()
nidas::core::McSocket::~McSocket () inline
McSocket() [2/2]
McSocket::McSocket (const McSocket & x) protected
Copy constructor.
Should only be called before nidas::util::Socket is connected.
Member Function Documentation
clone()
McSocket * McSocket::clone () const virtual
Derived classes must provide clone.
Implements nidas::core::IOChannel.
References McSocket().
close()
void McSocket::close () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _mcsocket, and nidas::util::McSocket< SocketT >::close().
connect()
IOChannel * McSocket::connect () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _keepAliveIdleSecs, _mcsocket, nidas::util::McSocket< SocketT >::accept(), nidas::util::McSocket< SocketT >::connect(), nidas::util::Inet4PacketInfo::getDestinationAddress(), nidas::util::Inet4PacketInfo::getInterface(), nidas::util::Inet4PacketInfoX::getRemoteSocketAddress(), getRequestType(), isNonBlocking(), isRequester(), nidas::core::IOChannel::setConnectionInfo(), nidas::util::Socket::setKeepAliveIdleSecs(), nidas::util::Socket::setNonBlocking(), and nidas::core::Socket::setRequestType().
connected()
void McSocket::connected (nidas::util::Socket * sock, const nidas::util::Inet4PacketInfoX & pktinfo) virtual
References _iochanRequester, _keepAliveIdleSecs, nidas::core::IOChannelRequester::connected(), nidas::util::Inet4PacketInfo::getDestinationAddress(), nidas::util::Inet4PacketInfo::getInterface(), nidas::util::Inet4PacketInfoX::getRemoteSocketAddress(), getRequestType(), isNonBlocking(), nidas::core::IOChannel::setConnectionInfo(), nidas::util::Socket::setKeepAliveIdleSecs(), nidas::util::Socket::setNonBlocking(), and nidas::core::Socket::setRequestType().
Referenced by nidas::core::McSocket::MyMcSocket::connected().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void McSocket::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References _keepAliveIdleSecs, nidas::util::Process::expandEnvVars(), nidas::util::Inet4Address::getByName(), nidas::util::Logger::getInstance(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), isRequester(), nidas::util::Logger::log(), LOG_WARNING, NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, port, setInet4McastSocketAddress(), setNonBlocking(), setRequester(), and setRequestType().
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int McSocket::getFd () const virtual
Implements nidas::core::IOChannel.
getInet4McastSocketAddress()
const nidas::util::Inet4SocketAddress& nidas::core::McSocket::getInet4McastSocketAddress () const inline
References _mcsocket, and nidas::util::McSocket< SocketT >::getInet4McastSocketAddress().
getKeepAliveIdleSecs()
int nidas::core::McSocket::getKeepAliveIdleSecs () const inline
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs.
getName()
const std::string& nidas::core::McSocket::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by fromDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
enum McSocketRequest nidas::core::McSocket::getRequestType () const inline virtual
Reimplemented from nidas::core::IOChannel.
References _mcsocket, and nidas::util::McSocket< SocketT >::setRequestType().
Referenced by connect(), and connected().
isNewInput()
virtual bool nidas::core::McSocket::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _newInput.
isNonBlocking()
bool nidas::core::McSocket::isNonBlocking () const inline virtual
Return isNonBlocking() of underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking.
Referenced by connect(), and connected().
isRequester()
bool nidas::core::McSocket::isRequester () const inline
Does this McSocket request connections, or does it listen for incoming connections.
References _amRequester.
Referenced by connect(), fromDOMElement(), and requestConnection().
operator=()
McSocket& nidas::core::McSocket::operator= (const McSocket &) private
No assignment.
read()
size_t nidas::core::McSocket::read (void * , size_t) inline virtual
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
requestConnection()
void McSocket::requestConnection (IOChannelRequester * service) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _iochanRequester, _mcsocket, isRequester(), nidas::util::McSocket< SocketT >::listen(), and nidas::util::McSocket< SocketT >::request().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setInet4McastSocketAddress()
void nidas::core::McSocket::setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress & val) inline
References _mcsocket, and nidas::util::McSocket< SocketT >::setInet4McastSocketAddress().
Referenced by fromDOMElement().
setKeepAliveIdleSecs()
void nidas::core::McSocket::setKeepAliveIdleSecs (int val) inline
Exceptions
nidas::util::IOException
References _keepAliveIdleSecs.
setName()
void nidas::core::McSocket::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by McSocket().
setNonBlocking()
void nidas::core::McSocket::setNonBlocking (bool val) inline virtual
Do setNonBlocking(val) on underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking.
Referenced by fromDOMElement().
setRequester()
void nidas::core::McSocket::setRequester (bool val) inline
References _amRequester.
Referenced by fromDOMElement().
setRequestType()
void nidas::core::McSocket::setRequestType (enum McSocketRequest val) inline virtual
Reimplemented from nidas::core::IOChannel.
Referenced by fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t nidas::core::McSocket::write (const struct iovec * , int) inline virtual
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
write() [2/2]
size_t nidas::core::McSocket::write (const void * , size_t) inline virtual
A McSocket shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_amRequester
bool nidas::core::McSocket::_amRequester private
Referenced by isRequester(), and setRequester().
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_firstRead
bool nidas::core::McSocket::_firstRead private
_iochanRequester
IOChannelRequester* nidas::core::McSocket::_iochanRequester protected
Referenced by connected(), and requestConnection().
_keepAliveIdleSecs
int nidas::core::McSocket::_keepAliveIdleSecs private
Referenced by connect(), connected(), fromDOMElement(), getKeepAliveIdleSecs(), and setKeepAliveIdleSecs().
_mcsocket
MyMcSocket nidas::core::McSocket::_mcsocket protected
Referenced by close(), connect(), getInet4McastSocketAddress(), getRequestType(), requestConnection(), and setInet4McastSocketAddress().
_name
std::string nidas::core::McSocket::_name private
Referenced by getName(), and setName().
_newInput
bool nidas::core::McSocket::_newInput private
Referenced by isNewInput().
_nonBlocking
bool nidas::core::McSocket::_nonBlocking private
Referenced by isNonBlocking(), and setNonBlocking().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/McSocket.h
nidas/core/McSocket.cc