nidas: nidas::core::Site::MyDictionary Class Reference
nidas::core::Site::MyDictionary Class Reference
Public Member Functions
MyDictionary (Site *site)
MyDictionary (const MyDictionary &x)
MyDictionary & operator= (const MyDictionary &rhs)
bool getTokenValue (const std::string &token, std::string &value) const
std::string expandString (const std::string &input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Private Attributes
Site * _site
Constructor & Destructor Documentation
MyDictionary() [1/2]
nidas::core::Site::MyDictionary::MyDictionary (Site * site) inline
MyDictionary() [2/2]
nidas::core::Site::MyDictionary::MyDictionary (const MyDictionary & x) inline
Member Function Documentation
expandString()
string Dictionary::expandString (const std::string & input) const inherited
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Referenced by nidas::core::DSMConfig::expandString(), nidas::core::DSMSensor::expandString(), nidas::core::Project::expandString(), nidas::core::Site::expandString(), and nidas::core::ParameterT< T >::fromDOMElement().
getTokenValue()
bool Site::MyDictionary::getTokenValue (const std::string & token, std::string & value) const virtual
Implements nidas::core::Dictionary.
References _site, nidas::core::Site::getName(), nidas::core::Site::getProject(), and nidas::core::Project::getTokenValue().
Referenced by nidas::core::Site::getTokenValue().
operator=()
MyDictionary& nidas::core::Site::MyDictionary::operator= (const MyDictionary & rhs) inline
References _site.
Member Data Documentation
_site
Site* nidas::core::Site::MyDictionary::_site private
Referenced by getTokenValue(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/Site.h
nidas/core/Site.cc