nidas: nidas/apps/data_stats.cc File Reference
data_stats.cc File Reference
#include <ctime>
#include <nidas/core/FileSet.h>
#include <nidas/core/Socket.h>
#include <nidas/dynld/RawSampleInputStream.h>
#include <nidas/core/Project.h>
#include <nidas/core/XMLParser.h>
#include <nidas/core/SamplePipeline.h>
#include <nidas/core/DSMConfig.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/Variable.h>
#include <nidas/core/NidasApp.h>
#include <nidas/core/BadSampleFilter.h>
#include <nidas/util/EOFException.h>
#include <nidas/util/Process.h>
#include <nidas/util/Logger.h>
#include <nidas/util/auto_ptr.h>
#include <nidas/util/util.h>
#include <set>
#include <map>
#include <deque>
#include <iostream>
#include <iomanip>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>
#include <json/json.h>
Classes
class SampleCounter
SampleCounter accumulates samples and values for a particular sample stream.
class DataStats
class AutoProject
Macros
#define NIDAS_JSONCPP_ENABLED 1
#define NIDAS_JSONCPP_STREAMWRITER 0
Functions
std::string assign_if_set (Json::Value &object, const std::string &key, const std::string &value)
If the metadata string value is not empty, assign that value to the json field named key.
Json::Value & createObject (Json::Value &value)
int main (int argc, char **argv)
Macro Definition Documentation
NIDAS_JSONCPP_ENABLED
#define NIDAS_JSONCPP_ENABLED 1
NIDAS_JSONCPP_STREAMWRITER
#define NIDAS_JSONCPP_STREAMWRITER 0
Function Documentation
assign_if_set()
std::string assign_if_set (Json::Value & object, const std::string & key, const std::string & value)
If the metadata string value is not empty, assign that value to the json field named key.
Referenced by SampleCounter::collectMetadata().
createObject()
Json::Value& createObject (Json::Value & value) inline
Referenced by DataStats::jsonReport().
main()
int main (int argc, char ** argv)
References DataStats::main().