nidas: nidas::core::Polynomial Class Reference
nidas::core::Polynomial Class Reference
#include <VariableConverter.h>
Public Member Functions
Polynomial ()
Polynomial * clone () const
void setCoefficients (const std::vector< float > &vals)
void setCoefficients (const float *fp, unsigned int n)
const std::vector< float > & getCoefficients () const
const float * getCoefficients (unsigned int &n) const
double convert (dsm_time_t t, double val)
void reset ()
Reset the converter to invalid or default settings, such as after an error occurs parsing a CalFile.
void parseFields (CalFile *cf)
Parse the fields in the current CalFile record for the particular settings and coefficients needed by this converter.
std::string toString () const
Generate a string description of this VariableConverter.
void fromString (const std::string &)
void fromDOMElement (const xercesc::DOMElement *)
virtual void readCalFile (dsm_time_t) throw ()
Before a VariableConverter can be used for a conversion, the converter's CalFile, if it exists, needs to be advanced to the right record for the current sample time.
void setCalFileHandler (CalFileHandler *)
Set the instance of CalFileHandler which will be called and given first option to handle new CalFile records.
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setCalFile (CalFile *)
CalFile * getCalFile ()
const CalFile * getCalFile () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static double eval (double x, float *p, unsigned int np)
This is static and defined inline below so the implementation can be shared with at least the one class in dynld which uses it: ParoSci_202BG_Calibration.
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void abortCalFile (const std::string &what)
Protected Attributes
CalFile * _calFile
CalFileHandler * _handler
Private Attributes
std::vector< float > _coefs
std::string _units
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
const Variable * _variable
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
Polynomial()
Polynomial::Polynomial ()
References setCoefficients().
Referenced by clone().
Member Function Documentation
abortCalFile()
void VariableConverter::abortCalFile (const std::string & what) protected inherited
References nidas::core::VariableConverter::_calFile, nidas::core::CalFile::getCurrentFileName(), nidas::core::VariableConverter::reset(), and WLOG.
addParameter()
void VariableConverter::addParameter (Parameter * val) inherited
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::VariableConverter::_constParameters, nidas::core::VariableConverter::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::VariableConverter::fromDOMElement(), nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
clone()
Polynomial * Polynomial::clone () const virtual
Implements nidas::core::VariableConverter.
Reimplemented in nidas::dynld::isff::RebsLinear.
References Polynomial().
convert()
double Polynomial::convert (dsm_time_t t, double val) virtual
Implements nidas::core::VariableConverter.
References _coefs, eval(), and nidas::core::VariableConverter::readCalFile().
createFromString()
VariableConverter * VariableConverter::createFromString (const std::string & str) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::VariableConverter::fromString().
createVariableConverter()
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
eval()
double nidas::core::Polynomial::eval (double x, float * p, unsigned int np) inline static
This is static and defined inline below so the implementation can be shared with at least the one class in dynld which uses it: ParoSci_202BG_Calibration.
Referenced by nidas::dynld::ParoSci_202BG_Calibration::computePressure(), nidas::dynld::ParoSci_202BG_Calibration::computeTemperature(), and convert().
fromDOMElement()
void Polynomial::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::VariableConverter.
References nidas::core::VariableConverter::fromDOMElement(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), and setCoefficients().
fromString()
void Polynomial::fromString (const std::string & str) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::VariableConverter.
References setCoefficients(), and nidas::core::VariableConverter::setUnits().
getCalFile() [1/2]
CalFile* nidas::core::VariableConverter::getCalFile () inline inherited
References nidas::core::VariableConverter::_calFile.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::core::SampleTag::fromDOMElement(), and PConfig::showCalFiles().
getCalFile() [2/2]
const CalFile* nidas::core::VariableConverter::getCalFile () const inline inherited
References nidas::core::VariableConverter::_calFile.
getCoefficients() [1/2]
const std::vector<float>& nidas::core::Polynomial::getCoefficients () const inline
References _coefs.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
getCoefficients() [2/2]
const float* nidas::core::Polynomial::getCoefficients (unsigned int & n) const inline
References _coefs.
getDSMConfig()
const DSMConfig * VariableConverter::getDSMConfig () const inherited
References nidas::core::DSMSensor::getDSMConfig(), and nidas::core::VariableConverter::getDSMSensor().
getDSMSensor()
const DSMSensor * VariableConverter::getDSMSensor () const inherited
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and nidas::core::VariableConverter::getVariable().
Referenced by nidas::core::VariableConverter::fromDOMElement(), and nidas::core::VariableConverter::getDSMConfig().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getParameter()
const Parameter * VariableConverter::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::VariableConverter::_parameters.
getParameters()
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline inherited
Get list of parameters.
References nidas::core::VariableConverter::_constParameters.
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
getUnits()
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::psql::PSQLSampleOutput::addVariable(), nidas::dynld::raf::SyncRecordSource::createHeader(), DumpClient::printHeader(), SampleToDatabase::SampleToDatabase(), nidas::core::Variable::toDOMElement(), nidas::core::Linear::toString(), and toString().
getVariable()
const Variable* nidas::core::VariableConverter::getVariable () const inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::VariableConverter::getDSMSensor().
parseFields()
void Polynomial::parseFields (CalFile * cf) virtual
Parse the fields in the current CalFile record for the particular settings and coefficients needed by this converter.
Implements nidas::core::VariableConverter.
References nidas::core::VariableConverter::_calFile, DLOG, nidas::util::UTime::format(), nidas::core::CalFile::getCurrentFileName(), nidas::core::CalFile::getCurrentTime(), nidas::core::CalFile::getFields(), nidas::core::CalFile::getLineNumber(), nidas::core::CalFile::nextTime(), setCoefficients(), and WLOG.
readCalFile()
void VariableConverter::readCalFile (dsm_time_t t) throw () virtual inherited
Before a VariableConverter can be used for a conversion, the converter's CalFile, if it exists, needs to be advanced to the right record for the current sample time.
As records are read, this method calls parseFields() so the VariableConverter subclass can extract the particular information it needs from the CalFile fields, typically coefficients.
For sensors which need to extend the kind of conversions which can be specified by a CalFile, there is a callback function available. See setCalFileHandler().
References DLOG, nidas::util::UTime::format(), and nidas::util::Exception::what().
Referenced by nidas::core::Linear::convert(), convert(), nidas::dynld::isff::NCAR_TRH::convertVariable(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
reset()
void Polynomial::reset () virtual
Reset the converter to invalid or default settings, such as after an error occurs parsing a CalFile.
Implements nidas::core::VariableConverter.
References nidas::core::floatNAN, and setCoefficients().
setCalFile()
void VariableConverter::setCalFile (CalFile * val) inherited
References nidas::core::VariableConverter::_calFile.
Referenced by nidas::core::VariableConverter::fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
setCalFileHandler()
void VariableConverter::setCalFileHandler (CalFileHandler * cfh) inherited
Set the instance of CalFileHandler which will be called and given first option to handle new CalFile records.
Pass null to disable the callbacks.
References nidas::core::VariableConverter::_handler.
Referenced by nidas::dynld::isff::NCAR_TRH::validate().
setCoefficients() [1/2]
void Polynomial::setCoefficients (const float * fp, unsigned int n)
References _coefs, and fp.
setCoefficients() [2/2]
void Polynomial::setCoefficients (const std::vector< float > & vals)
Referenced by fromDOMElement(), fromString(), parseFields(), Polynomial(), reset(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
setUnits()
void nidas::core::VariableConverter::setUnits (const std::string & val) inline inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::core::Variable::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::Linear::fromString(), fromString(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
setVariable()
void nidas::core::VariableConverter::setVariable (const Variable * val) inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::Variable::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
toString()
std::string Polynomial::toString () const virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implements nidas::core::VariableConverter.
References _coefs, and nidas::core::VariableConverter::getUnits().
Member Data Documentation
_calFile
CalFile* nidas::core::VariableConverter::_calFile protected inherited
Referenced by nidas::core::VariableConverter::abortCalFile(), nidas::core::VariableConverter::getCalFile(), nidas::core::VariableConverter::operator=(), parseFields(), nidas::core::VariableConverter::setCalFile(), nidas::core::VariableConverter::VariableConverter(), and nidas::core::VariableConverter::~VariableConverter().
_coefs
std::vector<float> nidas::core::Polynomial::_coefs private
Referenced by convert(), getCoefficients(), setCoefficients(), and toString().
_constParameters
std::list<const Parameter*> nidas::core::VariableConverter::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::VariableConverter::addParameter(), nidas::core::VariableConverter::getParameters(), and nidas::core::VariableConverter::~VariableConverter().
_handler
CalFileHandler* nidas::core::VariableConverter::_handler protected inherited
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::setCalFileHandler().
_parameters
std::map<std::string,Parameter*> nidas::core::VariableConverter::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::VariableConverter::addParameter(), and nidas::core::VariableConverter::getParameter().
_units
std::string nidas::core::VariableConverter::_units private inherited
Referenced by nidas::core::VariableConverter::getUnits(), nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::setUnits().
_variable
const Variable* nidas::core::VariableConverter::_variable private inherited
Referenced by nidas::core::VariableConverter::getVariable(), nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::setVariable().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/VariableConverter.h
nidas/core/VariableConverter.cc