nidas: nidas::core::SampleThread Class Reference
nidas::core::SampleThread Class Reference abstract
Interface for a Thread for buffering samples.
#include <SampleThread.h>
Public Types
enum runStatus { RUN_CANCELED = -1 , RUN_OK = 0 , NOT_RUNNING = 1 , RUN_EXCEPTION = 2 }
Values that can be returned by run method.
enum SchedPolicy { NU_THREAD_OTHER =SCHED_OTHER , NU_THREAD_FIFO =SCHED_FIFO , NU_THREAD_RR =SCHED_RR }
Public Member Functions
SampleThread (const std::string &name)
virtual ~SampleThread ()
virtual void flush ()=0 throw ()
Both SampleClient and SampleSource have a flush() method.
virtual void setKeepStats (bool val)=0
virtual bool getKeepStats () const =0
virtual size_t size () const =0
Number of samples that have not be distributed.
virtual void setLengthSecs (float val)=0
virtual float getLengthSecs () const =0
virtual void setHeapMax (size_t val)=0
Set the maximum amount of heap memory to use for sorting samples.
virtual size_t getHeapMax () const =0
virtual size_t getHeapSize () const =0
Get the current amount of heap being used for sorting.
virtual void setHeapBlock (bool val)=0
virtual bool getHeapBlock () const =0
virtual size_t getNumDiscardedSamples () const =0
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
virtual size_t getNumFutureSamples () const =0
Number of samples discarded because their timetags were in the future.
virtual void setRealTime (bool val)=0
Is this thread running in real-time, meaning is it handling recently sampled data? If so then we can screen for bad sample time-tags by checking against the system clock, which is trusted.
virtual bool getRealTime () const =0
virtual void setLateSampleCacheSize (unsigned int val)=0
virtual unsigned int getLateSampleCacheSize () const =0
virtual void start ()
Start the thread running, meaning execute the run method in a separate thread.
virtual int join ()
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
virtual void kill (int sig)
Send a signal to this thread.
virtual void cancel ()
Cancel this thread.
virtual void interrupt ()
Interrupt this thread.
virtual bool isInterrupted () const
Return true when this thread has been interrupted.
virtual bool isRunning () const
Is this thread running?
virtual bool isJoined () const
Has this thread been joined?
virtual bool isDetached () const
Is this a detached thread.
bool isCancelEnabled () const
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
bool isCancelDeferred () const
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
const std::string & getName () const throw ()
Return the name of this thread.
const std::string & getFullName () throw ()
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
bool setRealTimeRoundRobinPriority (int val)
bool setRealTimeFIFOPriority (int val)
bool setNonRealTimePriority ()
void setThreadScheduler (enum SchedPolicy policy, int priority)
void blockSignal (int)
Block a signal in this thread.
void unblockSignal (int)
Install a signal handler and unblock the signal.
virtual int run ()=0
The method which will run in its own thread.
virtual bool receive (const Sample *s)=0
Method called to pass a sample to this client.
virtual SampleSource * getRawSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual SampleSource * getProcessedSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addSampleTag (const SampleTag *)=0
Add a SampleTag to this SampleSource.
virtual void removeSampleTag (const SampleTag *)=0
virtual std::list< const SampleTag * > getSampleTags () const =0
What SampleTags am I a SampleSource for?
virtual SampleTagIterator getSampleTagIterator () const =0
virtual void addSampleClient (SampleClient *c)=0
Add a SampleClient of all Samples to this SampleSource.
virtual void removeSampleClient (SampleClient *c)=0
Remove a SampleClient from this SampleSource.
virtual void addSampleClientForTag (SampleClient *c, const SampleTag *)=0
Add a SampleClient to this SampleSource.
virtual void removeSampleClientForTag (SampleClient *c, const SampleTag *)=0
Remove a SampleClient for a given SampleTag from this SampleSource.
virtual int getClientCount () const =0
How many SampleClients are currently in my list.
virtual const SampleStats & getSampleStats () const =0
Static Public Member Functions
static Thread * currentThread ()
Return the thread object for the current thread.
static pthread_t currentThreadId ()
static Thread * lookupThread (pthread_t id)
static const std::string & currentName ()
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
static std::string getPolicyString (int policy)
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
static int test (int argc, char **argv)
a test method.
Protected Member Functions
void setCancelEnabled (bool val)
Set the cancel state for this thread - false means cancel requests are ignored.
void setCancelDeferred (bool val)
Set the cancel type for this thread.
pthread_t getId () const
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Private Member Functions
virtual void signalHandler (int, siginfo_t *)
Signal handler function for this thread.
virtual int pRun ()
void setThreadSchedulerNolock (enum SchedPolicy policy, int priority)
void makeFullName ()
void registerThread ()
Register this current thread with a static registry of threads by id.
void unregisterThread ()
void unsetId ()
Static Private Member Functions
static void * thr_run (void *me)
static void * thr_run_detached (void *me)
static void thr_cleanup (void *me)
static void thr_cleanup_delete (void *me)
static void thr_add_sig (int sig)
static void sigAction (int sig, siginfo_t *si, void *vptr)
Private Attributes
Mutex _mutex
Mutex for accessing _id.
std::string _name
std::string _fullname
pthread_t _id
bool _running
bool _interrupted
bool _cancel_enabled
bool _cancel_deferred
pthread_attr_t _thread_attr
Exception * _exception
Exception thrown by run method.
bool _detached
sigset_t _blockedSignals
sigset_t _unblockedSignals
Static Private Attributes
static std::string unknownName = std::string("unknown")
Detailed Description
Interface for a Thread for buffering samples.
Samples are received by the SampleClient side of this interface. The SampleSource side runs in a separate thread, sending out samples when they are ready. This interface can be inplemented by a SampleSorter if time-sorting is desired, or by a simple FIFO buffer. Either implementation provides thread separation where the thread using the SampleClient side could run as a high-priority real-time thread, doing time-critical time-tagging and acquisition, and the SampleSource runs as a normal-priority thread, doing less time-critical things like post-processing, or sample archiving.
Member Enumeration Documentation
runStatus
enum nidas::util::Thread::runStatus inherited
Values that can be returned by run method.
User can define other values greater than RUN_EXCEPTION. These values are then returned by int join(). Note that PTHREAD_CANCELLED is -1
Enumerator
RUN_CANCELED
RUN_OK
NOT_RUNNING
RUN_EXCEPTION
SchedPolicy
enum nidas::util::Thread::SchedPolicy inherited
Enumerator
NU_THREAD_OTHER
NU_THREAD_FIFO
NU_THREAD_RR
Constructor & Destructor Documentation
SampleThread()
nidas::core::SampleThread::SampleThread (const std::string & name) inline
~SampleThread()
virtual nidas::core::SampleThread::~SampleThread () inline virtual
Member Function Documentation
addSampleClient()
virtual void nidas::core::SampleSource::addSampleClient (SampleClient * c) pure virtual inherited
Add a SampleClient of all Samples to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::AsciiOutput::connect(), nidas::core::SampleArchiver::connect(), nidas::dynld::SampleProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), DataDump::run(), DataStats::run(), and nidas::core::RemoteSerialConnection::setSensor().
addSampleClientForTag()
virtual void nidas::core::SampleSource::addSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::raf::CVIProcessor::attachLVInput(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), and nidas::core::NearestResampler::connect().
addSampleTag()
virtual void nidas::core::SampleSource::addSampleTag (const SampleTag *) pure virtual inherited
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::addSampleTag(), nidas::dynld::RawSampleService::fromDOMElement(), DataPrep::run(), and StatsProcess::run().
amInterrupted()
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::Looper::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
blockSignal()
void Thread::blockSignal (int sig) inherited
Block a signal in this thread.
This method is usually called before this Thread has started. If this Thread is currently running, then this method is only effective if called from this Thread, i.e. from its own run() method.
Because SIGINT, SIGTERM and SIGHUP are typically caught in the main thread, they are blocked by default in a Thread. Call unblockSignal(sig) if you want to catch them in a Thread.
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::ConnectionMonitor(), nidas::core::ServerSocket::ConnectionThread::ConnectionThread(), nidas::core::DerivedDataReader::DerivedDataReader(), nidas::util::McSocketListener::McSocketListener(), nidas::util::McSocketMulticaster< SocketTT >::McSocketMulticaster(), nidas::core::SensorHandler::SensorHandler(), nidas::core::SensorOpener::SensorOpener(), nidas::util::Thread::test(), nidas::dynld::RawSampleService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
cancel()
void Thread::cancel () virtual inherited
Cancel this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::DSMService::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DerivedDataReader::deleteInstance(), and nidas::core::DSMEngine::joinDataThreads().
currentName()
static const std::string& nidas::util::Thread::currentName () inline static inherited
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
References nidas::util::Thread::currentThread(), nidas::util::Thread::getName(), and nidas::util::Thread::unknownName.
Referenced by nidas::util::Logger::msg_locked().
currentThread()
Thread * Thread::currentThread () static inherited
Return the thread object for the current thread.
Returns null if not found.
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::currentName(), and nidas::util::Thread::unblockSignal().
currentThreadId()
pthread_t Thread::currentThreadId () static inherited
Referenced by nidas::core::Looper::removeClient().
flush()
virtual void nidas::core::SampleThread::flush () throw () pure virtual
Both SampleClient and SampleSource have a flush() method.
Redeclaring it here as pure virtual removes the ambiguity.
Implements nidas::core::SampleClient.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::flush().
getClientCount()
virtual int nidas::core::SampleSource::getClientCount () const pure virtual inherited
How many SampleClients are currently in my list.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getClientCount().
getFullName()
const std::string & Thread::getFullName () throw () inherited
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
References nidas::util::Thread::_fullname.
Referenced by nidas::util::Thread::pRun(), nidas::util::Thread::test(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
getHeapBlock()
virtual bool nidas::core::SampleThread::getHeapBlock () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
getHeapMax()
virtual size_t nidas::core::SampleThread::getHeapMax () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::getSorterNumProcBytesMax(), nidas::core::SamplePipeline::getSorterNumRawBytesMax(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
getHeapSize()
virtual size_t nidas::core::SampleThread::getHeapSize () const pure virtual
Get the current amount of heap being used for sorting.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::getSorterNumProcBytes(), and nidas::core::SamplePipeline::getSorterNumRawBytes().
getId()
pthread_t nidas::util::Thread::getId () const inline protected inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Referenced by nidas::util::Thread::isJoined(), nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::core::Looper::removeClient().
getKeepStats()
virtual bool nidas::core::SampleThread::getKeepStats () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
getLateSampleCacheSize()
virtual unsigned int nidas::core::SampleThread::getLateSampleCacheSize () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
getLengthSecs()
virtual float nidas::core::SampleThread::getLengthSecs () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
getName()
const std::string & Thread::getName () const throw () inherited
Return the name of this thread.
References nidas::util::Thread::_name.
Referenced by nidas::core::DSMService::cancel(), nidas::util::Thread::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), nidas::core::SensorHandler::PolledDSMSensor::close(), nidas::util::Thread::currentName(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SampleSorter::heapDecrement(), nidas::core::DSMService::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleSorter::run(), nidas::util::ThreadJoiner::run(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::sigAction(), nidas::util::Thread::start(), nidas::util::Thread::test(), nidas::util::LogContext::threadName(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
getNumDiscardedSamples()
virtual size_t nidas::core::SampleThread::getNumDiscardedSamples () const pure virtual
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::getNumDiscardedProcSamples(), and nidas::core::SamplePipeline::getNumDiscardedRawSamples().
getNumFutureSamples()
virtual size_t nidas::core::SampleThread::getNumFutureSamples () const pure virtual
Number of samples discarded because their timetags were in the future.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::getNumFutureProcSamples(), and nidas::core::SamplePipeline::getNumFutureRawSamples().
getPolicyString()
string Thread::getPolicyString (int policy) static inherited
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
References nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::NU_THREAD_RR.
Referenced by nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::makeFullName().
getProcessedSampleSource()
virtual SampleSource* nidas::core::SampleSource::getProcessedSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SampleArchiver::connectSource(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), and nidas::core::SampleArchiver::disconnectSource().
getRawSampleSource()
virtual SampleSource* nidas::core::SampleSource::getRawSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SampleArchiver::disconnectSource().
getRealTime()
virtual bool nidas::core::SampleThread::getRealTime () const pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
getSampleStats()
virtual const SampleStats& nidas::core::SampleSource::getSampleStats () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getSampleStats(), nidas::dynld::RawSampleService::printClock(), nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
getSampleTagIterator()
virtual SampleTagIterator nidas::core::SampleSource::getSampleTagIterator () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SamplePipeline::getSampleTagIterator().
getSampleTags()
virtual std::list<const SampleTag*> nidas::core::SampleSource::getSampleTags () const pure virtual inherited
What SampleTags am I a SampleSource for?
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::psql::PSQLProcessor, nidas::dynld::isff::PacketInputStream, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), nidas::core::NearestResampler::connect(), nidas::core::DSMEngine::connectOutputs(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::SamplePipeline::getSampleTags(), DataPrep::run(), and nidas::dynld::RawSampleService::schedule().
interrupt()
void Thread::interrupt () virtual inherited
Interrupt this thread.
This sets a boolean which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted. This is a "soft" request to terminate the thread.
What follows is a discussion of when to use cancel(), kill(), or interrupt() to terminate a thread.
If you can consistently check the state of isInterrupted() in the run method, and return if it is true, at a time interval which is an acceptable amount of time to wait for the thread to terminate, then using interrupt() should work well.
If the run method does I/O, then things are usually a bit more complicated.
If all I/O is guaranteed to finish quickly, which is a rare situation, or is done with a timeout, such as using select/poll with a timeout before every read/write, then one could still use interrupt() as above, and the thread will terminate within the timeout period.
If the thread does blocking I/O operations, and the I/O might block for a period of time longer than you're willing to wait for the thread to terminate, then you need to use kill(sig) or cancel().
If a signal is sent to the thread with kill(sig) while the thread is blocking on an I/O operation, the I/O will immediately return with an errno of EINTR, and one could then return from the run method, after any necessary cleanup.
However there is a possibility that the signal could be missed. In order to make sure you receive a signal, you must block it, so that any received signals are held as pending, and then atomically unblock it with pselect/ppoll/epoll_pwait before performing the I/O operation.
If you do not use I/O timeouts, or kill(sig) with pselect/ppoll/epoll_pwait, or other tricks such as writing to a pipe that is watched with select/poll in the run method, then using cancel() is the only way to guarantee that your thread will terminate in an acceptable amount of time.
All NIDAS Threads support deferred cancelation. Immediate asynchronous cancellation is not fully supported (and is very hard to get right). Deferred cancelation means that cancellation is delayed until the thread next calls a system function that is a cancellation point. At that point the thread run method will simply terminate without any return value from the system function, and then execute any cleanup methods that may have been registered with pthread_cleanup_push.
A list of cancellation points is provided in the pthreads(7) man page. Cancellation points are typically I/O operations, waits or sleeps.
This immediate thread termination can be a problem if there is a possibility that your objects could be left in a bad state, such as with a mutex locked, though it isn't generally a good practice to hold mutexes during a time-consuming I/O operation, wait or sleep.
One should check the run method to see if the state of the objects is OK if execution stops at any of the cancellation points. Note that logging a message, or writing to cerr is a cancellation point. Typically there is error/exception handling associated with an I/O operation. Ensuring the state is OK upon a cancellation is similar to preparation for a fatal I/O error that requires a return of the run method. One can use setCancelEnabled() to defer cancellation.
One can use pthread_cleanup_push and pthread_cleanup_pop to register cleanup routines that are called when a thread is cancelled if special handling is required.
Implements nidas::util::Runnable.
Reimplemented in nidas::util::ThreadRunnable, nidas::util::McSocketMulticaster< SocketTT >, nidas::util::McSocketListener, nidas::dynld::XMLConfigService::Worker, nidas::dynld::UDPSampleOutput::XMLSocketListener, nidas::dynld::UDPSampleOutput::VariableListWorker, nidas::dynld::RawSampleService::Worker, nidas::dynld::raf::SyncServer, nidas::core::XmlRpcThread, nidas::core::ServerSocket::ConnectionThread, nidas::core::Socket::ConnectionThread, nidas::core::SensorOpener, nidas::core::SensorHandler, nidas::core::SampleSorter, nidas::core::SampleOutputRequestThread, nidas::core::SampleBuffer, and nidas::core::DerivedDataReader.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::dynld::UDPSampleOutput::close(), nidas::core::DSMEngine::interrupt(), nidas::core::DSMService::interrupt(), nidas::core::SampleOutputRequestThread::interrupt(), nidas::core::SamplePipeline::interrupt(), nidas::core::SampleSorter::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::dynld::raf::SyncServer::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::SamplePipeline::join(), nidas::core::Looper::removeClient(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
isCancelDeferred()
bool Thread::isCancelDeferred () const inherited
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
References nidas::util::Thread::_cancel_deferred.
isCancelEnabled()
bool Thread::isCancelEnabled () const inherited
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
References nidas::util::Thread::_cancel_enabled.
isDetached()
virtual bool nidas::util::Thread::isDetached () const inline virtual inherited
Is this a detached thread.
References nidas::util::Thread::_detached.
isInterrupted()
virtual bool nidas::util::Thread::isInterrupted () const inline virtual inherited
Return true when this thread has been interrupted.
Implements nidas::util::Runnable.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::core::SampleSorter::flush(), nidas::dynld::raf::SyncServer::read(), ServerThread::run(), Sender::run(), ModemLineSetter::run(), ModemLineMonitor::run(), nidas::core::DerivedDataReader::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleBuffer::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::SampleSorter::run(), nidas::core::SensorHandler::run(), nidas::core::SensorOpener::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::util::McSocketListener::run(), and nidas::dynld::raf::SyncServer::stop().
isJoined()
virtual bool nidas::util::Thread::isJoined () const inline virtual inherited
Has this thread been joined?
References nidas::util::Thread::getId().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::SensorHandler::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::util::Thread::test(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
isRunning()
virtual bool nidas::util::Thread::isRunning () const inline virtual inherited
Is this thread running?
References nidas::util::Thread::_mutex, and nidas::util::Thread::_running.
Referenced by nidas::util::Thread::blockSignal(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::DSMService::interrupt(), nidas::core::SamplePipeline::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::Looper::removeClient(), nidas::core::ServerSocket::requestConnection(), nidas::core::SensorHandler::run(), nidas::core::Looper::setupClientMaps(), nidas::util::Thread::test(), nidas::util::Thread::unblockSignal(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::util::Thread::~Thread(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
join()
int Thread::join () virtual inherited
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
The return value is the int return value of the run method, or PTHREAD_CANCELED (-1). If the run method threw an Exception, it will be caught and then re-thrown by join.
Exceptions
Exception
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_exception, nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), nidas::util::Thread::getId(), nidas::util::Thread::getName(), nidas::util::Thread::RUN_EXCEPTION, and nidas::util::Thread::RUN_OK.
Referenced by nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocketListener::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::core::SensorHandler::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::core::DSMEngine::killXmlRpcThread(), nidas::core::DSMServerApp::killXmlRpcThread(), main(), nidas::core::Looper::removeClient(), nidas::util::ThreadJoiner::run(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
kill()
void Thread::kill (int sig) virtual inherited
Send a signal to this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::interrupt(), nidas::core::SensorHandler::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::XmlRpcThread::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), main(), nidas::core::SensorHandler::scheduleAdd(), nidas::core::SensorHandler::scheduleClose(), nidas::core::SensorHandler::scheduleReopen(), and nidas::core::SensorHandler::sensorIsOpen().
lookupThread()
Thread * Thread::lookupThread (pthread_t id) static inherited
Referenced by nidas::util::LogContext::threadName().
makeFullName()
void Thread::makeFullName () private inherited
References nidas::util::Thread::_cancel_deferred, nidas::util::Thread::_cancel_enabled, nidas::util::Thread::_detached, nidas::util::Thread::_fullname, nidas::util::Thread::_id, nidas::util::Thread::_name, and nidas::util::Thread::getPolicyString().
Referenced by nidas::util::Thread::start().
pRun()
int Thread::pRun () private virtual inherited
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_exception, nidas::util::Thread::_mutex, nidas::util::Thread::_unblockedSignals, nidas::util::Exception::clone(), nidas::util::Thread::getFullName(), nidas::util::Thread::getId(), ILOG, nidas::util::Mutex::lock(), nidas::util::Mutex::ptr(), nidas::util::Runnable::run(), and nidas::util::Thread::RUN_EXCEPTION.
Referenced by nidas::util::Thread::thr_run(), and nidas::util::Thread::thr_run_detached().
receive()
virtual bool nidas::core::SampleClient::receive (const Sample * s) pure virtual inherited
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, DumpClient, DataStats, SampleDispatcher, DumpClient, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, TestClient, nidas::dynld::raf::SyncRecordSource, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, and nidas::dynld::UDPSampleOutput.
registerThread()
void Thread::registerThread () private inherited
Register this current thread with a static registry of threads by id.
Thread::registerThread (new Thread ("Main"));
Referenced by nidas::util::Thread::start().
removeSampleClient()
virtual void nidas::core::SampleSource::removeSampleClient (SampleClient * c) pure virtual inherited
Remove a SampleClient from this SampleSource.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::core::SamplePipeline::disconnect(), DataDump::run(), DataStats::run(), nidas::core::SampleArchiver::~SampleArchiver(), and nidas::dynld::SampleProcessor::~SampleProcessor().
removeSampleClientForTag()
virtual void nidas::core::SampleSource::removeSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
removeSampleTag()
virtual void nidas::core::SampleSource::removeSampleTag (const SampleTag *) pure virtual inherited
Exceptions
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::removeSampleTag().
run()
virtual int nidas::util::Runnable::run () pure virtual inherited
The method which will run in its own thread.
This method must be supplied by the Runnable or Thread subclass.
Exceptions
Exception
Implemented in nidas::util::ThreadJoiner, nidas::util::ThreadRunnable, nidas::util::McSocketMulticaster< SocketTT >, nidas::util::McSocketListener, nidas::dynld::XMLConfigService::Worker, nidas::dynld::UDPSampleOutput::XMLSocketListener, nidas::dynld::UDPSampleOutput::ConnectionMonitor, nidas::dynld::UDPSampleOutput::VariableListWorker, nidas::dynld::RawSampleService::Worker, nidas::dynld::raf::SyncServer, nidas::dynld::isff::GOESOutput, nidas::core::DSMServerStat, nidas::core::DSMEngineStat, nidas::core::StatusListener, nidas::core::ServerSocket::ConnectionThread, nidas::core::Socket::ConnectionThread, nidas::core::SensorOpener, nidas::core::SensorHandler, nidas::core::SampleSorter, nidas::core::SampleOutputRequestThread, nidas::core::SampleBuffer, nidas::core::Looper, nidas::core::FsMountWorkerThread, nidas::core::DSMServerIntf, nidas::core::DSMEngineIntf, nidas::core::DerivedDataReader, ModemLineMonitor, ModemLineSetter, Sender, TestSource, PSI, DataWriter, ServerThread, and WriterThread.
Referenced by nidas::util::Thread::pRun(), nidas::util::ThreadRunnable::run(), and nidas::util::Thread::test().
setCancelDeferred()
void Thread::setCancelDeferred (bool val) protected inherited
Set the cancel type for this thread.
true means cancel requests are deferred until the next cancellation point. false means they occur instantly. This is protected, it should be called only from a thread's own run method. See the pthreads(7) man page for a list of the cancellation points.
Note: non-deferred canceling is difficult to get right. It has not been tested with this class, and is not recommended.
References nidas::util::Thread::_cancel_deferred.
setCancelEnabled()
void Thread::setCancelEnabled (bool val) protected inherited
Set the cancel state for this thread - false means cancel requests are ignored.
See pthread_setcancelstate. This is protected, it should be called only from a thread's own run method.
References nidas::util::Thread::_cancel_enabled.
setHeapBlock()
virtual void nidas::core::SampleThread::setHeapBlock (bool val) pure virtual
Parameters
val If true, and heapSize exceeds heapMax, then wait for heapSize to be less then heapMax, which will block any SampleSources that are inserting samples into this sorter. If false, then discard any samples that are received while heapSize exceeds heapMax.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setHeapMax()
virtual void nidas::core::SampleThread::setHeapMax (size_t val) pure virtual
Set the maximum amount of heap memory to use for sorting samples.
Parameters
val Maximum size of heap in bytes.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setKeepStats()
virtual void nidas::core::SampleThread::setKeepStats (bool val) pure virtual
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setLateSampleCacheSize()
virtual void nidas::core::SampleThread::setLateSampleCacheSize (unsigned int val) pure virtual
Implemented in nidas::core::SampleBuffer, and nidas::core::SampleSorter.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setLengthSecs()
virtual void nidas::core::SampleThread::setLengthSecs (float val) pure virtual
Implemented in nidas::core::SampleBuffer, and nidas::core::SampleSorter.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setNonRealTimePriority()
bool Thread::setNonRealTimePriority () inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::setThreadScheduler().
setRealTime()
virtual void nidas::core::SampleThread::setRealTime (bool val) pure virtual
Is this thread running in real-time, meaning is it handling recently sampled data? If so then we can screen for bad sample time-tags by checking against the system clock, which is trusted.
Note that real-time here doesn't mean running at real-time priority.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setRealTimeFIFOPriority()
bool Thread::setRealTimeFIFOPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_FIFO, and nidas::util::Thread::setThreadScheduler().
Referenced by nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setRealTimeRoundRobinPriority()
bool Thread::setRealTimeRoundRobinPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_RR, and nidas::util::Thread::setThreadScheduler().
setThreadScheduler()
void Thread::setThreadScheduler (enum SchedPolicy policy, int priority) inherited
Exceptions
Exception
References nidas::util::Thread::_mutex, and nidas::util::Thread::setThreadSchedulerNolock().
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::getLooper(), nidas::util::Thread::setNonRealTimePriority(), nidas::util::Thread::setRealTimeFIFOPriority(), and nidas::util::Thread::setRealTimeRoundRobinPriority().
setThreadSchedulerNolock()
void Thread::setThreadSchedulerNolock (enum SchedPolicy policy, int priority) private inherited
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::util::Thread::setThreadScheduler(), and nidas::util::Thread::start().
sigAction()
void Thread::sigAction (int sig, siginfo_t * si, void * vptr) static private inherited
References DLOG, nidas::util::Thread::getName(), and nidas::util::Thread::signalHandler().
Referenced by nidas::util::Thread::thr_add_sig().
signalHandler()
virtual void nidas::util::Thread::signalHandler (int , siginfo_t *) inline private virtual inherited
Signal handler function for this thread.
The default handler just sets _interrupt to true, so that amInterrupted() or isInterrupted() will return true. Derived classes can override this method for custom signal handling. However, derived classes are limited in what they can do in their signal handler. Specifically, from the pthread_cond_signal man page:
"It is not safe to use the pthread_cond_signal() function in a signal handler that is invoked asynchronously."
Therefore do not call Cond::signal() from a signal handler.
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_interrupted.
Referenced by nidas::util::Thread::sigAction().
size()
virtual size_t nidas::core::SampleThread::size () const pure virtual
Number of samples that have not be distributed.
Implemented in nidas::core::SampleSorter, and nidas::core::SampleBuffer.
Referenced by nidas::core::SamplePipeline::getSorterNumProcSamples(), and nidas::core::SamplePipeline::getSorterNumRawSamples().
start()
void Thread::start () virtual inherited
Start the thread running, meaning execute the run method in a separate thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_interrupted, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), nidas::util::Thread::getName(), nidas::util::Thread::makeFullName(), nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::registerThread(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::thr_run(), nidas::util::Thread::thr_run_detached(), and WLOG.
Referenced by nidas::util::McSocketListener::accept(), nidas::dynld::RawSampleService::connect(), nidas::dynld::XMLConfigAllService::connected(), nidas::dynld::XMLConfigService::connected(), nidas::core::DerivedDataReader::createInstance(), nidas::dynld::raf::SyncServer::getTimeWindow(), nidas::util::McSocket< SocketT >::joinMulticaster(), main(), nidas::core::FsMount::mount(), nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), nidas::core::SamplePipeline::rawinit(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), ServerThread::run(), PSI::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SensorHandler::run(), nidas::core::Socket::ConnectionThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::dynld::raf::SyncServer::setTimeWindow(), nidas::core::Looper::setupClientMaps(), nidas::core::DSMServerApp::startStatusThread(), nidas::core::DSMEngine::startXmlRpcThread(), and nidas::core::DSMServerApp::startXmlRpcThread().
test()
int Thread::test (int argc, char ** argv) static inherited
a test method.
References nidas::util::Runnable::amInterrupted(), nidas::util::Thread::blockSignal(), nidas::util::Thread::getFullName(), nidas::util::Thread::getName(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Runnable::run(), nidas::util::Thread::Thread(), and nidas::util::Exception::what().
testCancel()
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
thr_add_sig()
void Thread::thr_add_sig (int sig) static private inherited
References nidas::util::Thread::sigAction().
Referenced by nidas::util::Thread::blockSignal(), and nidas::util::Thread::unblockSignal().
thr_cleanup()
void Thread::thr_cleanup (void * me) static private inherited
References nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), ILOG, and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run().
thr_cleanup_delete()
void Thread::thr_cleanup_delete (void * me) static private inherited
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), nidas::util::Mutex::lock(), nidas::util::Mutex::unlock(), and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run_detached().
thr_run()
void * Thread::thr_run (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup().
Referenced by nidas::util::Thread::start().
thr_run_detached()
void * Thread::thr_run_detached (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup_delete().
Referenced by nidas::util::Thread::start().
unblockSignal()
void Thread::unblockSignal (int sig) inherited
Install a signal handler and unblock the signal.
The signal handler will log a message about the receipt of the signal at severity LOG_INFO using the nidas::util::Logger. Then, if the signal handler is being invoked from a registered Thread, the virtual method signalHandler() for that Thread will be called.
The signal handler is installed with the sigaction() system call, and will be the action for the given signal in all threads, including the main() thread. If other threads do not wish to take action on a given signal, they should call blockSignal(sig). Or they can define their own signalHandler() method.
After installing the signal handler, the signal is added to those that are unblocked for the thread, or if the Thread is not yet running, the signal will be unblocked in the thread once it runs.
As with blockSignal(), this method is typically called on this Thread before it has started. If this Thread has started, then the signal will only be unblocked if the method is called from this Thread, i.e. from its own run() method.
To install a signal handler, and then block the signal so that it is held as pending until it is later unblocked, typically with pselect(), or sigwaitinfo(), do:
void Thread::run()
{
    // get the existing signal mask
    sigset_t sigmask;
    pthread_sigmask(SIG_BLOCK,NULL,&sigmask);
    // remove SIGUSR1 from the mask passed to pselect
    sigdelset(&sigmask,SIGUSR1);
    for (;;) {
        pselect(nfd,&readfds,0,0,0,&sigmask);
        ...
    }
}
...
thread.unblockSignal(SIGUSR1);
thread.blockSignal(SIGUSR1);
thread.start();
...
try {
    if (thread.isRunning()) {
        thread.kill(SIGUSR1);
        thread.join()
    }
}
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::core::DerivedDataReader::DerivedDataReader(), nidas::core::FsMountWorkerThread::FsMountWorkerThread(), nidas::core::StatusListener::StatusListener(), nidas::core::StatusThread::StatusThread(), nidas::dynld::XMLConfigService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
unregisterThread()
void Thread::unregisterThread () private inherited
Referenced by nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
unsetId()
void nidas::util::Thread::unsetId () inline private inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Member Data Documentation
_blockedSignals
sigset_t nidas::util::Thread::_blockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
_cancel_deferred
bool nidas::util::Thread::_cancel_deferred private inherited
Referenced by nidas::util::Thread::isCancelDeferred(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelDeferred().
_cancel_enabled
bool nidas::util::Thread::_cancel_enabled private inherited
Referenced by nidas::util::Thread::isCancelEnabled(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelEnabled().
_detached
bool nidas::util::Thread::_detached private inherited
Referenced by nidas::util::Thread::isDetached(), nidas::util::Thread::makeFullName(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_exception
Exception* nidas::util::Thread::_exception private inherited
Exception thrown by run method.
Referenced by nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::util::Thread::~Thread().
_fullname
std::string nidas::util::Thread::_fullname private inherited
Referenced by nidas::util::Thread::getFullName(), and nidas::util::Thread::makeFullName().
_id
pthread_t nidas::util::Thread::_id private inherited
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::makeFullName(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_interrupted
bool nidas::util::Thread::_interrupted private inherited
Referenced by nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::signalHandler(), and nidas::util::Thread::start().
_mutex
Mutex nidas::util::Thread::_mutex mutable private inherited
Mutex for accessing _id.
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::pRun(), nidas::util::Thread::setThreadScheduler(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_name
std::string nidas::util::Thread::_name private inherited
Referenced by nidas::util::Thread::getName(), and nidas::util::Thread::makeFullName().
_running
bool nidas::util::Thread::_running private inherited
Referenced by nidas::util::Thread::isRunning(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
_thread_attr
pthread_attr_t nidas::util::Thread::_thread_attr private inherited
Referenced by nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_unblockedSignals
sigset_t nidas::util::Thread::_unblockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
unknownName
std::string Thread::unknownName = std::string("unknown") static private inherited
Referenced by nidas::util::Thread::currentName().
The documentation for this class was generated from the following file:
nidas/core/SampleThread.h