nidas: nidas::core::DSMServer Class Reference
nidas::core::DSMServer Class Reference
A provider of services to a DSM.
#include <DSMServer.h>
Public Member Functions
DSMServer ()
virtual ~DSMServer ()
const std::string & getName () const
void setName (const std::string &val)
const std::string & getXMLConfigFileName () const
void setXMLConfigFileName (const std::string &val)
void addService (DSMService *service)
const std::list< DSMService * > & getServices () const
void setProject (Project *val)
const Project * getProject () const
void setSite (const Site *val)
const Site * getSite () const
DSMServiceIterator getDSMServiceIterator () const
ProcessorIterator getProcessorIterator () const
SensorIterator getSensorIterator () const
SampleTagIterator getSampleTagIterator () const
void addThread (nidas::util::Thread *thrd)
void scheduleServices (bool optionalProcessing)
void interruptServices () throw ()
void joinServices () throw ()
void setStatusSocketAddr (const nidas::util::SocketAddress &val)
const nidas::util::SocketAddress & getStatusSocketAddr () const
void fromDOMElement (const xercesc::DOMElement *)
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Private Member Functions
DSMServer (const DSMServer &)
Copy not supported.
DSMServer & operator= (const DSMServer &)
Assignment not supported.
Private Attributes
std::string _name
Name of this server.
Project * _project
const Site * _site
What Site to I serve? Can be NULL if this DSMServer is not for a specific Site, but serves the Project.
std::list< DSMService * > _services
The DSMServices that we've been configured to start.
std::string _xmlFileName
nidas::util::SocketAddress * _statusSocketAddr
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
A provider of services to a DSM.
Constructor & Destructor Documentation
DSMServer() [1/2]
DSMServer::DSMServer ()
~DSMServer()
DSMServer::~DSMServer () virtual
References _services, _statusSocketAddr, and nidas::core::DSMService::getName().
DSMServer() [2/2]
nidas::core::DSMServer::DSMServer (const DSMServer &) private
Copy not supported.
Member Function Documentation
addService()
void nidas::core::DSMServer::addService (DSMService * service) inline
References _services.
Referenced by fromDOMElement().
addThread()
void nidas::core::DSMServer::addThread (nidas::util::Thread * thrd)
fromDOMElement()
void DSMServer::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References addService(), nidas::core::DOMObjectFactory::createObject(), nidas::core::DSMService::fromDOMElement(), nidas::util::Inet4Address::getByName(), nidas::core::DSMService::getClassName(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), getProject(), nidas::core::XDOMAttr::getValue(), NIDAS_MULTICAST_ADDR, port, nidas::core::DSMService::setDSMServer(), setName(), setStatusSocketAddr(), and nidas::util::Exception::what().
Referenced by nidas::core::Project::fromDOMElement(), and nidas::core::Site::fromDOMElement().
getDSMServiceIterator()
DSMServiceIterator DSMServer::getDSMServiceIterator () const
getName()
const std::string& nidas::core::DSMServer::getName () const inline
References _name.
Referenced by nidas::core::Project::findServer(), nidas::core::Site::findServer(), nidas::core::Project::findServers(), nidas::core::Project::findServerSampleOutputStreamFileSets(), and fromDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getProcessorIterator()
ProcessorIterator DSMServer::getProcessorIterator () const
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), and StatsProcess::getStatisticsProcessor().
getProject()
const Project* nidas::core::DSMServer::getProject () const inline
References _project.
Referenced by nidas::core::GetDsmList::execute(), nidas::core::GetAdsFileName::execute(), fromDOMElement(), and nidas::core::DSMService::fromDOMElement().
getSampleTagIterator()
SampleTagIterator DSMServer::getSampleTagIterator () const
getSensorIterator()
SensorIterator DSMServer::getSensorIterator () const
References _project, nidas::core::Project::getSensorIterator(), nidas::core::Site::getSensorIterator(), and getSite().
Referenced by nidas::dynld::RawSampleService::fromDOMElement(), StatsProcess::run(), nidas::core::DSMServerStat::run(), and nidas::dynld::RawSampleService::schedule().
getServices()
const std::list<DSMService*>& nidas::core::DSMServer::getServices () const inline
References _services.
Referenced by nidas::core::DSMServiceIterator::hasNext(), and nidas::core::DSMServerStat::run().
getSite()
const Site* nidas::core::DSMServer::getSite () const inline
References _site.
Referenced by getSensorIterator().
getStatusSocketAddr()
const nidas::util::SocketAddress& nidas::core::DSMServer::getStatusSocketAddr () const inline
References _statusSocketAddr.
Referenced by nidas::core::DSMServerApp::run(), nidas::core::DSMServerStat::run(), and nidas::core::DSMServerApp::startStatusThread().
getXMLConfigFileName()
const std::string& nidas::core::DSMServer::getXMLConfigFileName () const inline
References _xmlFileName.
interruptServices()
void DSMServer::interruptServices () throw ()
References _services, nidas::core::SampleOutputRequestThread::clear(), nidas::core::SampleOutputRequestThread::getInstance(), and nidas::core::DSMService::interrupt().
Referenced by nidas::core::DSMServerApp::run().
joinServices()
void DSMServer::joinServices () throw ()
References _services, nidas::core::DSMService::getName(), ILOG, and nidas::core::DSMService::join().
Referenced by nidas::core::DSMServerApp::run().
operator=()
DSMServer& nidas::core::DSMServer::operator= (const DSMServer &) private
Assignment not supported.
scheduleServices()
void DSMServer::scheduleServices (bool optionalProcessing)
Exceptions
nidas::util::Exception
References _project, _services, nidas::core::Project::initSensors(), and nidas::core::DSMService::schedule().
Referenced by nidas::core::DSMServerApp::run().
setName()
void nidas::core::DSMServer::setName (const std::string & val) inline
References _name.
Referenced by fromDOMElement().
setProject()
void nidas::core::DSMServer::setProject (Project * val) inline
References _project.
Referenced by nidas::core::Project::fromDOMElement(), and nidas::core::Site::fromDOMElement().
setSite()
void nidas::core::DSMServer::setSite (const Site * val) inline
References _site.
Referenced by nidas::core::Site::fromDOMElement().
setStatusSocketAddr()
void nidas::core::DSMServer::setStatusSocketAddr (const nidas::util::SocketAddress & val) inline
References _statusSocketAddr, and nidas::util::SocketAddress::clone().
Referenced by fromDOMElement().
setXMLConfigFileName()
void nidas::core::DSMServer::setXMLConfigFileName (const std::string & val) inline
References _xmlFileName.
Referenced by nidas::core::DSMServerApp::run().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_name
std::string nidas::core::DSMServer::_name private
Name of this server.
This should correspond to a hostname of a machine.
Referenced by getName(), and setName().
_project
Project* nidas::core::DSMServer::_project private
Referenced by getProject(), getSensorIterator(), scheduleServices(), and setProject().
_services
std::list<DSMService*> nidas::core::DSMServer::_services private
The DSMServices that we've been configured to start.
Referenced by addService(), getServices(), interruptServices(), joinServices(), scheduleServices(), and ~DSMServer().
_site
const Site* nidas::core::DSMServer::_site private
What Site to I serve? Can be NULL if this DSMServer is not for a specific Site, but serves the Project.
Referenced by getSite(), and setSite().
_statusSocketAddr
nidas::util::SocketAddress* nidas::core::DSMServer::_statusSocketAddr private
Referenced by getStatusSocketAddr(), setStatusSocketAddr(), and ~DSMServer().
_xmlFileName
std::string nidas::core::DSMServer::_xmlFileName private
Referenced by getXMLConfigFileName(), and setXMLConfigFileName().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/DSMServer.h
nidas/core/DSMServer.cc