nidas: nidas::core::SampleOutput Class Reference
nidas::core::SampleOutput Class Reference abstract
Interface of an output stream of samples.
#include <SampleOutput.h>
Public Member Functions
virtual ~SampleOutput ()
virtual SampleOutput * getOriginal () const =0
Get pointer to SampleOutput that was cloned.
virtual void setName (const std::string &val)=0
virtual const std::string & getName () const =0
virtual bool isRaw () const =0
virtual void addRequestedSampleTag (SampleTag *tag)=0
Some SampleOutputs don't send out all the Samples that they receive.
virtual std::list< const SampleTag * > getRequestedSampleTags () const =0
virtual void addSourceSampleTag (const SampleTag *tag)=0
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
virtual void addSourceSampleTags (const std::list< const SampleTag * > &tags)=0
virtual std::list< const SampleTag * > getSourceSampleTags () const =0
virtual void requestConnection (SampleConnectionRequester *)=0
Request a connection, of this SampleOutput, but don't wait for it.
virtual int getReconnectDelaySecs () const =0
Derived classes implement this to indicate whether a connection should be requested again if one fails.
virtual void setReconnectDelaySecs (int val)=0
virtual int getFd () const =0
virtual IOChannel * getIOChannel () const =0
virtual size_t write (const void *buf, size_t len)=0
Plain raw write, typically only used to write an initial header.
virtual void close ()=0
virtual void setHeaderSource (HeaderSource *val)=0
virtual void setDSMConfig (const DSMConfig *val)=0
virtual const DSMConfig * getDSMConfig () const =0
virtual void setLatency (float val)=0
virtual float getLatency () const =0
virtual bool receive (const Sample *s)=0
Method called to pass a sample to this client.
virtual void flush ()=0
Ask that this SampleClient send out any buffered Samples that it may be holding.
virtual IOChannelRequester * connected (IOChannel *)=0
virtual void fromDOMElement (const xercesc::DOMElement *)=0
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
virtual SampleOutput * clone (IOChannel *iochannel)=0
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Interface of an output stream of samples.
Constructor & Destructor Documentation
~SampleOutput()
virtual nidas::core::SampleOutput::~SampleOutput () inline virtual
Member Function Documentation
addRequestedSampleTag()
virtual void nidas::core::SampleOutput::addRequestedSampleTag (SampleTag * tag) pure virtual
Some SampleOutputs don't send out all the Samples that they receive.
At configuration time, one can use this method to request the SampleTags that should be output from a SampleOutput. SampleOutput will own the pointer.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::SampleOutputBase, nidas::dynld::raf::CVIOutput, and nidas::dynld::isff::GOESOutput.
addSourceSampleTag()
virtual void nidas::core::SampleOutput::addSourceSampleTag (const SampleTag * tag) pure virtual
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
Users of SampleOutputs should call this method before calling requestConnection().
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::SampleOutputBase, and nidas::dynld::isff::GOESOutput.
addSourceSampleTags()
virtual void nidas::core::SampleOutput::addSourceSampleTags (const std::list< const SampleTag * > & tags) pure virtual
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMEngine::connectOutputs(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), and nidas::dynld::raf::SyncRecordGenerator::connectSource().
clone()
virtual SampleOutput* nidas::core::SampleOutput::clone (IOChannel * iochannel) protected pure virtual
Implemented in nidas::dynld::isff::GOESOutput, nidas::dynld::UDPSampleOutput, nidas::dynld::raf::CVIOutput, nidas::dynld::SampleOutputStream, nidas::dynld::RawSampleOutputStream, and nidas::dynld::AsciiOutput.
Referenced by nidas::core::SampleOutputBase::connected().
close()
virtual void nidas::core::SampleOutput::close () pure virtual
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::UDPSampleOutput, nidas::dynld::SampleOutputStream, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, and nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleIOProcessor::~SampleIOProcessor(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
connected()
virtual IOChannelRequester* nidas::core::IOChannelRequester::connected (IOChannel *) pure virtual inherited
Implemented in nidas::dynld::isff::GOESOutput, nidas::dynld::SampleInputStream, nidas::dynld::UDPSampleOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::SampleOutputStream, nidas::core::SampleOutputBase, nidas::dynld::XMLConfigService, and nidas::dynld::XMLConfigAllService.
Referenced by nidas::core::McSocketUDP::connected(), nidas::core::McSocket::connected(), nidas::core::FileSet::mounted(), nidas::core::FileSet::requestConnection(), nidas::core::UnixIOChannel::requestConnection(), and nidas::core::DatagramSocket::requestConnection().
flush()
virtual void nidas::core::SampleClient::flush () pure virtual inherited
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implemented in nidas::core::SampleThread, nidas::core::Resampler, nidas::dynld::UDPSampleOutput, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::CVIOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, nidas::dynld::AsciiOutput, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, DumpClient, DataStats, SampleDispatcher, and DumpClient.
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::flush(), nidas::dynld::raf::CVIProcessor::flush(), nidas::dynld::SampleProcessor::flush(), nidas::dynld::StatisticsProcessor::flush(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleIOProcessor::~SampleIOProcessor(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
fromDOMElement()
virtual void nidas::core::DOMable::fromDOMElement (const xercesc::DOMElement *) pure virtual inherited
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::dynld::UDPSampleOutput, nidas::dynld::SampleInputStream, nidas::dynld::RawSampleService, nidas::dynld::RawSampleOutputStream, nidas::dynld::RawSampleInputStream, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::CVIProcessor, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::Wind2D, nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::GOESOutput, nidas::dynld::isff::DAUSensor, nidas::core::SerialSensor, nidas::core::SampleOutputBase, nidas::core::SampleIOProcessor, nidas::core::FsMount, nidas::core::FileSet, nidas::core::DSMService, nidas::core::CalFile, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::Arinc_IRS, nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, nidas::core::Linear, nidas::core::VariableConverter, nidas::core::Variable, nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::Site, nidas::core::ServiceCatalog, nidas::core::SensorCatalog, nidas::core::SampleTag, nidas::core::Project, nidas::core::MultipleUDPSockets, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::DSMServer, nidas::core::DSMSensor, nidas::core::DSMConfig, nidas::core::DSMCatalog, nidas::core::DatagramSocket, and nidas::core::CharacterSensor.
Referenced by nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
getDSMConfig()
virtual const DSMConfig* nidas::core::SampleOutput::getDSMConfig () const pure virtual
Implemented in nidas::core::SampleOutputBase.
getFd()
virtual int nidas::core::SampleOutput::getFd () const pure virtual
Implemented in nidas::dynld::psql::PSQLSampleOutput, and nidas::core::SampleOutputBase.
getIOChannel()
virtual IOChannel* nidas::core::SampleOutput::getIOChannel () const pure virtual
Implemented in nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMConfig::findSampleOutputStreamFileSets(), and nidas::core::Project::findServerSampleOutputStreamFileSets().
getLatency()
virtual float nidas::core::SampleOutput::getLatency () const pure virtual
Implemented in nidas::core::SampleOutputBase.
getName()
virtual const std::string& nidas::core::SampleOutput::getName () const pure virtual
Implemented in nidas::dynld::psql::PSQLSampleOutput, and nidas::core::SampleOutputBase.
Referenced by nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::DSMEngine::closeOutputs(), nidas::core::DSMEngine::connectOutputs(), nidas::core::SampleOutputRequestThread::run(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleIOProcessor::~SampleIOProcessor(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getOriginal()
virtual SampleOutput* nidas::core::SampleOutput::getOriginal () const pure virtual
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implemented in nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::DSMEngine::disconnect(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::raf::CVIProcessor::disconnect(), nidas::dynld::raf::SyncRecordGenerator::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::dynld::StatisticsProcessor::disconnect(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
getReconnectDelaySecs()
virtual int nidas::core::SampleOutput::getReconnectDelaySecs () const pure virtual
Derived classes implement this to indicate whether a connection should be requested again if one fails.
@ return: -1 do not resubmit a connection request >=0 number of seconds to wait before submitting a request (0 means ASAP)
Implemented in nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMEngine::disconnect(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::raf::CVIProcessor::disconnect(), nidas::dynld::raf::SyncRecordGenerator::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::dynld::StatisticsProcessor::disconnect(), and nidas::core::SampleOutputRequestThread::run().
getRequestedSampleTags()
virtual std::list<const SampleTag*> nidas::core::SampleOutput::getRequestedSampleTags () const pure virtual
Implemented in nidas::core::SampleOutputBase.
getSourceSampleTags()
virtual std::list<const SampleTag*> nidas::core::SampleOutput::getSourceSampleTags () const pure virtual
Implemented in nidas::core::SampleOutputBase.
isRaw()
virtual bool nidas::core::SampleOutput::isRaw () const pure virtual
Implemented in nidas::dynld::RawSampleOutputStream, nidas::dynld::psql::PSQLSampleOutput, and nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMEngine::closeOutputs(), and nidas::core::DSMEngine::connectOutputs().
receive()
virtual bool nidas::core::SampleClient::receive (const Sample * s) pure virtual inherited
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, DumpClient, DataStats, SampleDispatcher, DumpClient, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, TestClient, nidas::dynld::raf::SyncRecordSource, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, and nidas::dynld::UDPSampleOutput.
requestConnection()
virtual void nidas::core::SampleOutput::requestConnection (SampleConnectionRequester *) pure virtual
Request a connection, of this SampleOutput, but don't wait for it.
The SampleConnectionRequester will be notified via a call back to SampleConnectionRequester::connected(SampleOutput*,SampleOutput*) where the first SampleOutput points to the SampleOutput of the original request, and the second is often a new instance of a SampleOutput with a new IOChannel connection. Or the two pointers may point to the same SampleOutput.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, nidas::dynld::psql::PSQLSampleOutput, and nidas::core::SampleOutputBase.
Referenced by StatsProcess::run(), and nidas::core::SampleOutputRequestThread::run().
setDSMConfig()
virtual void nidas::core::SampleOutput::setDSMConfig (const DSMConfig * val) pure virtual
Implemented in nidas::core::SampleOutputBase.
Referenced by nidas::core::DSMConfig::fromDOMElement().
setHeaderSource()
virtual void nidas::core::SampleOutput::setHeaderSource (HeaderSource * val) pure virtual
Implemented in nidas::core::SampleOutputBase.
setLatency()
virtual void nidas::core::SampleOutput::setLatency (float val) pure virtual
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::dynld::SampleOutputStream, and nidas::core::SampleOutputBase.
setName()
virtual void nidas::core::SampleOutput::setName (const std::string & val) pure virtual
Implemented in nidas::dynld::psql::PSQLSampleOutput, and nidas::core::SampleOutputBase.
setReconnectDelaySecs()
virtual void nidas::core::SampleOutput::setReconnectDelaySecs (int val) pure virtual
Implemented in nidas::core::SampleOutputBase.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write()
virtual size_t nidas::core::SampleOutput::write (const void * buf, size_t len) pure virtual
Plain raw write, typically only used to write an initial header.
Exceptions
nidas::util::IOException
Implemented in nidas::core::SampleOutputBase, and nidas::dynld::isff::GOESOutput.
Referenced by nidas::core::SampleInputHeader::write().
Member Data Documentation
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following file:
nidas/core/SampleOutput.h