nidas: nidas::core::Dictionary Class Reference
nidas::core::Dictionary Class Reference abstract
Interface for a Dictionary class, which can return a string value for a string token name.
#include <Dictionary.h>
Public Member Functions
virtual ~Dictionary ()
virtual bool getTokenValue (const std::string &token, std::string &value) const =0
std::string expandString (const std::string &input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Detailed Description
Interface for a Dictionary class, which can return a string value for a string token name.
Constructor & Destructor Documentation
~Dictionary()
virtual nidas::core::Dictionary::~Dictionary () inline virtual
Member Function Documentation
expandString()
string Dictionary::expandString (const std::string & input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Referenced by nidas::core::DSMConfig::expandString(), nidas::core::DSMSensor::expandString(), nidas::core::Project::expandString(), nidas::core::Site::expandString(), and nidas::core::ParameterT< T >::fromDOMElement().
getTokenValue()
virtual bool nidas::core::Dictionary::getTokenValue (const std::string & token, std::string & value) const pure virtual
Implemented in nidas::core::Site::MyDictionary, nidas::core::Project::MyDictionary, nidas::core::DSMSensor::MyDictionary, and nidas::core::DSMConfig::MyDictionary.
The documentation for this class was generated from the following files:
nidas/core/Dictionary.h
nidas/core/Dictionary.cc