nidas: nidas::core::VariableIterator Class Reference
nidas::core::VariableIterator Class Reference
Class for iterating over the Variables of a Project, Site, DSMConfig, DSMSensor, or SampleTag.
#include <NidsIterators.h>
Public Member Functions
VariableIterator (const Project *)
VariableIterator (const DSMServer *)
VariableIterator (const DSMService *)
VariableIterator (const Site *)
VariableIterator (const DSMConfig *)
VariableIterator (const SampleSource *)
VariableIterator (const SampleTag *)
VariableIterator (const VariableIterator &x)
Excplicit copy constructor to satisfy -Weffc++.
VariableIterator & operator= (const VariableIterator &rhs)
Excplicit assignment operator to satisfy -Weffc++.
bool hasNext ()
const Variable * next ()
Private Attributes
SampleTagIterator _sampleTagIterator
const std::vector< const Variable * > * _variables
std::vector< const Variable * >::const_iterator _variableItr
Detailed Description
Class for iterating over the Variables of a Project, Site, DSMConfig, DSMSensor, or SampleTag.
Constructor & Destructor Documentation
VariableIterator() [1/8]
VariableIterator::VariableIterator (const Project * obj)
VariableIterator() [2/8]
nidas::core::VariableIterator::VariableIterator (const DSMServer *)
VariableIterator() [3/8]
nidas::core::VariableIterator::VariableIterator (const DSMService *)
VariableIterator() [4/8]
VariableIterator::VariableIterator (const Site * obj)
VariableIterator() [5/8]
VariableIterator::VariableIterator (const DSMConfig * obj)
VariableIterator() [6/8]
VariableIterator::VariableIterator (const SampleSource * obj)
VariableIterator() [7/8]
VariableIterator::VariableIterator (const SampleTag * stag)
VariableIterator() [8/8]
nidas::core::VariableIterator::VariableIterator (const VariableIterator & x) inline
Excplicit copy constructor to satisfy -Weffc++.
Member Function Documentation
hasNext()
bool VariableIterator::hasNext ()
References _sampleTagIterator, _variableItr, _variables, nidas::core::SampleTag::getVariables(), nidas::core::SampleTagIterator::hasNext(), and nidas::core::SampleTagIterator::next().
Referenced by nidas::dynld::raf::CVIOutput::addRequestedSampleTag(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::isff::Wind3D::checkSampleTags(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::core::NearestResampler::connect(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::dynld::StatisticsCruncher::createCombinations(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::WxtSensor::init(), PConfig::loadVariables(), DataPrep::matchVariables(), parseAnalog(), parseOther(), DumpClient::setSensors(), PConfig::showAll(), nidas::core::SampleTag::toDOMElement(), and nidas::core::Site::validate().
next()
const Variable* nidas::core::VariableIterator::next () inline
References _variableItr.
Referenced by nidas::dynld::raf::CVIOutput::addRequestedSampleTag(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::isff::Wind3D::checkSampleTags(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::core::NearestResampler::connect(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::StatisticsCruncher::createCombinations(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::WxtSensor::init(), DataPrep::matchVariables(), and DumpClient::setSensors().
operator=()
VariableIterator& nidas::core::VariableIterator::operator= (const VariableIterator & rhs) inline
Excplicit assignment operator to satisfy -Weffc++.
References _sampleTagIterator, _variableItr, and _variables.
Member Data Documentation
_sampleTagIterator
SampleTagIterator nidas::core::VariableIterator::_sampleTagIterator private
Referenced by hasNext(), and operator=().
_variableItr
std::vector<const Variable*>::const_iterator nidas::core::VariableIterator::_variableItr private
Referenced by hasNext(), next(), and operator=().
_variables
const std::vector<const Variable*>* nidas::core::VariableIterator::_variables private
Referenced by hasNext(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc