nidas: nidas::dynld::ParoSci_202BG_Calibration Class Reference
nidas::dynld::ParoSci_202BG_Calibration Class Reference
Support for reading a calibration file for a ParoScientific 202BG sensor.
#include <ParoSci_202BG_Calibration.h>
Public Member Functions
ParoSci_202BG_Calibration ()
void readCalFile (nidas::core::CalFile *cf, dsm_time_t tt)
void setU0 (float val)
void setYs (float v0, float v1, float v2, float v3)
void setCs (float v0, float v1, float v2)
void setDs (float v0, float v1)
void setTs (float v0, float v1, float v2, float v3, float v4)
void setCommonModeCoefs (float v0, float v1, float v2, float v3)
float getU0 () const
double computeTemperature (double usec)
double computePressure (double tper, double pper)
double correctPressure (double pgauge, double pstatic)
Private Attributes
float _U0
float _Y [4]
float _C [3]
float _D [2]
float _T [5]
float _a [2]
float _b
float _P0
Detailed Description
Support for reading a calibration file for a ParoScientific 202BG sensor.
Constructor & Destructor Documentation
ParoSci_202BG_Calibration()
ParoSci_202BG_Calibration::ParoSci_202BG_Calibration ()
References _C, _D, _T, _Y, and nidas::core::floatNAN.
Member Function Documentation
computePressure()
double ParoSci_202BG_Calibration::computePressure (double tper, double pper)
References _C, _D, _T, and nidas::core::Polynomial::eval().
computeTemperature()
double ParoSci_202BG_Calibration::computeTemperature (double usec)
References _Y, and nidas::core::Polynomial::eval().
correctPressure()
double ParoSci_202BG_Calibration::correctPressure (double pgauge, double pstatic)
References _a, _b, and _P0.
getU0()
float nidas::dynld::ParoSci_202BG_Calibration::getU0 () const inline
readCalFile()
void ParoSci_202BG_Calibration::readCalFile (nidas::core::CalFile * cf, dsm_time_t tt)
Exceptions
nidas::util::Exception
References nidas::core::floatNAN, nidas::core::CalFile::getCurrentFileName(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, nidas::core::MBAR_PER_KPA, nidas::core::CalFile::nextTime(), nidas::core::CalFile::readCF(), setCommonModeCoefs(), setCs(), setDs(), setTs(), setU0(), setYs(), nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
setCommonModeCoefs()
void nidas::dynld::ParoSci_202BG_Calibration::setCommonModeCoefs (float v0, float v1, float v2, float v3) inline
Referenced by readCalFile().
setCs()
void nidas::dynld::ParoSci_202BG_Calibration::setCs (float v0, float v1, float v2) inline
Referenced by readCalFile().
setDs()
void nidas::dynld::ParoSci_202BG_Calibration::setDs (float v0, float v1) inline
Referenced by readCalFile().
setTs()
void nidas::dynld::ParoSci_202BG_Calibration::setTs (float v0, float v1, float v2, float v3, float v4) inline
Referenced by readCalFile().
setU0()
void nidas::dynld::ParoSci_202BG_Calibration::setU0 (float val) inline
Referenced by readCalFile().
setYs()
void nidas::dynld::ParoSci_202BG_Calibration::setYs (float v0, float v1, float v2, float v3) inline
Referenced by readCalFile().
Member Data Documentation
_a
float nidas::dynld::ParoSci_202BG_Calibration::_a[2] private
Referenced by correctPressure().
_b
float nidas::dynld::ParoSci_202BG_Calibration::_b private
Referenced by correctPressure().
_C
float nidas::dynld::ParoSci_202BG_Calibration::_C[3] private
Referenced by computePressure(), and ParoSci_202BG_Calibration().
_D
float nidas::dynld::ParoSci_202BG_Calibration::_D[2] private
Referenced by computePressure(), and ParoSci_202BG_Calibration().
_P0
float nidas::dynld::ParoSci_202BG_Calibration::_P0 private
Referenced by correctPressure().
_T
float nidas::dynld::ParoSci_202BG_Calibration::_T[5] private
Referenced by computePressure(), and ParoSci_202BG_Calibration().
_U0
float nidas::dynld::ParoSci_202BG_Calibration::_U0 private
_Y
float nidas::dynld::ParoSci_202BG_Calibration::_Y[4] private
Referenced by computeTemperature(), and ParoSci_202BG_Calibration().
The documentation for this class was generated from the following files:
nidas/dynld/ParoSci_202BG_Calibration.h
nidas/dynld/ParoSci_202BG_Calibration.cc