nidas: nidas::core::XMLParser Class Reference
nidas::core::XMLParser Class Reference
Wrapper class around xerces-c DOMBuilder to parse XML.
#include <XMLParser.h>
Public Member Functions
XMLParser ()
Constructor.
virtual ~XMLParser ()
Nuke the parser.
void setDOMValidation (bool val)
DOMBuilder::setFilter is not yet implemented in xerces c++ 2.6.0 void setFilter(xercesc::DOMBuilderFilter* filter)
void setDOMValidateIfSchema (bool val)
Enable/disable schema validation.
void setDOMNamespaces (bool val)
Enable/disable namespace processing.
void setXercesSchema (bool val)
Enable/disable schema support.
void setXercesSchemaFullChecking (bool val)
Enable/disable full schema constraint checking, including checking which may be time-consuming or memory intensive.
void setDOMDatatypeNormalization (bool val)
Enable/disable datatype normalization.
void setXercesUserAdoptsDOMDocument (bool val)
Control who owns DOMDocument pointer.
void setXercesHandleMultipleImports (bool val)
void setXercesDoXInclude (bool val)
xercesc::DOMDocument * parse (const std::string &xmlFile, bool verbose=true)
xercesc::DOMDocument * parse (xercesc::InputSource &source)
Protected Attributes
xercesc::DOMImplementation * _impl
xercesc::DOMBuilder * _parser
XMLErrorHandler _errorHandler
Private Member Functions
XMLParser (const XMLParser &)
No copying.
XMLParser & operator= (const XMLParser &)
No assignment.
Detailed Description
Wrapper class around xerces-c DOMBuilder to parse XML.
Constructor & Destructor Documentation
XMLParser() [1/2]
XMLParser::XMLParser ()
Constructor.
The default setting for setXercesUserAdoptsDOMDocument(true) is true.
Exceptions
nidas::core::XMLException
References _errorHandler, _impl, _parser, and setXercesUserAdoptsDOMDocument().
~XMLParser()
XMLParser::~XMLParser () virtual
Nuke the parser.
This does a release() (delete) of the associated DOMBuilder.
References _parser.
XMLParser() [2/2]
nidas::core::XMLParser::XMLParser (const XMLParser &) private
No copying.
Member Function Documentation
operator=()
XMLParser& nidas::core::XMLParser::operator= (const XMLParser &) private
No assignment.
parse() [1/2]
xercesc::DOMDocument * XMLParser::parse (const std::string & xmlFile, bool verbose = true)
Exceptions
nidas::core::XMLException
References _errorHandler, _parser, nidas::core::XMLErrorHandler::getXMLException(), NLOG, nidas::core::XMLErrorHandler::resetErrors(), and verbose.
Referenced by PConfig::loadFile(), main(), nidas::core::XMLCachingParser::parse(), nidas::core::ProjectConfigs::parseXML(), nidas::core::Datasets::parseXML(), and PacketDecode::run().
parse() [2/2]
xercesc::DOMDocument * XMLParser::parse (xercesc::InputSource & source)
Exceptions
nidas::core::XMLException
References _errorHandler, _parser, nidas::core::XMLErrorHandler::getXMLException(), and nidas::core::XMLErrorHandler::resetErrors().
setDOMDatatypeNormalization()
void XMLParser::setDOMDatatypeNormalization (bool val)
Enable/disable datatype normalization.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true let the validation process do its datatype normalization that is defined in the used schema language. If false disable datatype normalization. The XML 1.0 attribute value normalization always occurs though.
Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMNamespaces()
void XMLParser::setDOMNamespaces (bool val)
Enable/disable namespace processing.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true perform namespace processing. Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMValidateIfSchema()
void XMLParser::setDOMValidateIfSchema (bool val)
Enable/disable schema validation.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true the parser will validate the document only if a grammar is specified. If false validation is determined by the state of the validation feature, see setDOMValidation().
Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setDOMValidation()
void XMLParser::setDOMValidation (bool val)
DOMBuilder::setFilter is not yet implemented in xerces c++ 2.6.0 void setFilter(xercesc::DOMBuilderFilter* filter)
Enable/disable validation. See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val Boolean value specifying whether to report all validation errors. Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesDoXInclude()
void XMLParser::setXercesDoXInclude (bool val)
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesHandleMultipleImports()
void XMLParser::setXercesHandleMultipleImports (bool val)
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesSchema()
void XMLParser::setXercesSchema (bool val)
Enable/disable schema support.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true enable the parser's schema support. Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesSchemaFullChecking()
void XMLParser::setXercesSchemaFullChecking (bool val)
Enable/disable full schema constraint checking, including checking which may be time-consuming or memory intensive.
Currently, particle unique attribution constraint checking and particle derivation restriction checking are controlled by this option.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true enable schema constraint checking. Default: false.
References _parser.
Referenced by PConfig::loadFile(), main(), and nidas::core::DSMServerApp::parseXMLConfigFile().
setXercesUserAdoptsDOMDocument()
void XMLParser::setXercesUserAdoptsDOMDocument (bool val)
Control who owns DOMDocument pointer.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMBuilderFeatures
Parameters
val If true the caller will adopt the DOMDocument that is returned from the parse method and thus is responsible to call DOMDocument::release() to release the associated memory. The parser will not release it. The ownership is transferred from the parser to the caller. If false the returned DOMDocument from the parse method is owned by the parser and thus will be deleted when the parser is released.
References _parser.
Referenced by XMLParser().
Member Data Documentation
_errorHandler
XMLErrorHandler nidas::core::XMLParser::_errorHandler protected
Referenced by parse(), and XMLParser().
_impl
xercesc::DOMImplementation* nidas::core::XMLParser::_impl protected
Referenced by XMLParser().
_parser
xercesc::DOMBuilder* nidas::core::XMLParser::_parser protected
Referenced by parse(), setDOMDatatypeNormalization(), setDOMNamespaces(), setDOMValidateIfSchema(), setDOMValidation(), setXercesDoXInclude(), setXercesHandleMultipleImports(), setXercesSchema(), setXercesSchemaFullChecking(), setXercesUserAdoptsDOMDocument(), XMLParser(), and ~XMLParser().
The documentation for this class was generated from the following files:
nidas/core/XMLParser.h
nidas/core/XMLParser.cc