nidas: nidas::core::XMLImplementation Class Reference
nidas::core::XMLImplementation Class Reference
#include <XMLParser.h>
Static Public Member Functions
static xercesc::DOMImplementation * getImplementation ()
static void terminate ()
Static Private Attributes
static xercesc::DOMImplementation * _impl = 0
static nidas::util::Mutex _lock
Member Function Documentation
getImplementation()
xercesc::DOMImplementation * XMLImplementation::getImplementation () static
Exceptions
nidas::core::XMLException
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::dynld::UDPSampleOutput::VariableListWorker::run(), nidas::dynld::XMLConfigService::Worker::run(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
terminate()
void XMLImplementation::terminate () static
Referenced by PConfig::main(), main(), nidas::core::DSMEngine::main(), nidas::core::DSMServerApp::main(), nidas::core::Project::parseXMLConfigFile(), nidas::core::DSMEngine::run(), and nidas::dynld::raf::SyncServer::run().
Member Data Documentation
_impl
xercesc::DOMImplementation * XMLImplementation::_impl = 0 static private
_lock
n_u::Mutex XMLImplementation::_lock static private
The documentation for this class was generated from the following files:
nidas/core/XMLParser.h
nidas/core/XMLParser.cc