nidas: nidas/apps/xml_dump.cc File Reference
xml_dump.cc File Reference
#include <nidas/core/XMLParser.h>
#include <nidas/core/Project.h>
#include <nidas/core/Site.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/Variable.h>
#include <nidas/core/CalFile.h>
#include <iostream>
#include <fstream>
Classes
class AutoProject
Functions
void parseAnalog (const DSMConfig *dsm)
void parseOther (const DSMConfig *dsm)
int usage (const char *argv0)
int main (int argc, char **argv)
void sensorTitle (DSMSensor *sensor)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::core::Project::fromDOMElement(), nidas::core::Site::getDSMConfigIterator(), nidas::core::Project::getInstance(), nidas::core::DSMConfig::getLocation(), nidas::core::DSMConfig::getName(), nidas::core::Site::getName(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::XMLParser::parse(), parseAnalog(), parseOther(), nidas::core::XMLParser::setDOMDatatypeNormalization(), nidas::core::XMLParser::setDOMNamespaces(), nidas::core::XMLParser::setDOMValidateIfSchema(), nidas::core::XMLParser::setDOMValidation(), nidas::core::XMLParser::setXercesDoXInclude(), nidas::core::XMLParser::setXercesHandleMultipleImports(), nidas::core::XMLParser::setXercesSchema(), nidas::core::XMLParser::setXercesSchemaFullChecking(), usage(), and nidas::util::Exception::what().
parseAnalog()
void parseAnalog (const DSMConfig * dsm)
References nidas::core::Variable::getA2dChannel(), nidas::core::DSMSensor::getClassName(), nidas::core::Variable::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::Variable::getParameter(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::SampleTag::isProcessed(), and sensorTitle().
Referenced by main().
parseOther()
void parseOther (const DSMConfig * dsm)
References nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDeviceName(), nidas::core::Variable::getName(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::SampleTag::isProcessed(), and sensorTitle().
Referenced by main().
sensorTitle()
void sensorTitle (DSMSensor * sensor)
References nidas::core::DSMSensor::getCalFiles(), nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMId(), nidas::core::CalFile::getFile(), nidas::core::DSMSensor::getParameter(), nidas::core::DSMSensor::getSensorId(), nidas::core::Parameter::getStringValue(), and nidas::core::DSMSensor::getSuffix().
Referenced by parseAnalog(), and parseOther().
usage()
int usage (const char * argv0)
Referenced by main().