nidas: nidas::core::SampleAverager Class Reference
nidas::core::SampleAverager Class Reference
#include <SampleAverager.h>
Public Member Functions
SampleAverager ()
SampleAverager (const std::vector< const Variable * > &vars)
SampleAverager (const std::vector< Variable * > &vars)
virtual ~SampleAverager ()
void setAveragePeriodSecs (float val)
Set average period.
float getAveragePeriodSecs () const
Get average period.
void addVariable (const Variable *var)
void addVariables (const std::vector< const Variable * > &)
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const SampleTag * > getSampleTags () const
Get the output SampleTags.
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of Resampler::flush().
const SampleStats & getSampleStats () const
void connect (SampleSource *source)
Connect the resampler to a SampleSource.
void disconnect (SampleSource *source) throw ()
bool receive (const Sample *s) throw ()
Method called to pass a sample to this client.
Protected Member Functions
void init () throw ()
Private Member Functions
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
SampleAverager (const SampleAverager &)
No copy.
SampleAverager & operator= (const SampleAverager &)
No assignment.
Private Attributes
SampleSourceSupport _source
SampleTag _outSample
int _averagePeriodUsecs
Length of average, in microseconds.
dsm_time_t _endTime
end time of current statistics window.
std::map< Variable *, unsigned int > _outVarIndices
Index of each requested output variable in the output sample.
std::map< dsm_sample_id_t, std::vector< unsigned int > > _inmap
std::map< dsm_sample_id_t, std::vector< unsigned int > > _lenmap
std::map< dsm_sample_id_t, std::vector< unsigned int > > _outmap
unsigned int _ndataValues
double * _sums
int * _cnts
Constructor & Destructor Documentation
SampleAverager() [1/4]
SampleAverager::SampleAverager ()
References _outSample, addSampleTag(), nidas::core::Project::getInstance(), setAveragePeriodSecs(), and nidas::core::SampleTag::setSampleId().
SampleAverager() [2/4]
SampleAverager::SampleAverager (const std::vector< const Variable * > & vars)
References _outSample, addSampleTag(), addVariables(), nidas::core::Project::getInstance(), setAveragePeriodSecs(), and nidas::core::SampleTag::setSampleId().
SampleAverager() [3/4]
SampleAverager::SampleAverager (const std::vector< Variable * > & vars)
References _outSample, addSampleTag(), addVariables(), nidas::core::Project::getInstance(), setAveragePeriodSecs(), and nidas::core::SampleTag::setSampleId().
~SampleAverager()
SampleAverager::~SampleAverager () virtual
References _cnts, and _sums.
SampleAverager() [4/4]
nidas::core::SampleAverager::SampleAverager (const SampleAverager &) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::core::SampleAverager::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleClientForTag()
void nidas::core::SampleAverager::addSampleClientForTag (SampleClient * client, const SampleTag *) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleTag()
void nidas::core::SampleAverager::addSampleTag (const SampleTag * tag) throw () inline private virtual
Add a SampleTag to this SampleSource.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleTag().
Referenced by SampleAverager().
addVariable()
void SampleAverager::addVariable (const Variable * var)
References _ndataValues, _outSample, _outVarIndices, nidas::core::SampleTag::addVariable(), and nidas::core::Variable::getLength().
Referenced by addVariables().
addVariables()
void SampleAverager::addVariables (const std::vector< const Variable * > &)
References addVariable().
Referenced by SampleAverager().
connect()
void SampleAverager::connect (SampleSource * source) virtual
Connect the resampler to a SampleSource.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::Resampler.
References _inmap, _lenmap, _outmap, _outSample, _outVarIndices, nidas::core::SampleSource::addSampleClientForTag(), nidas::core::SampleTag::getDataIndex(), nidas::core::SampleTag::getId(), nidas::core::Variable::getLength(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::SampleSource::getSampleTags(), nidas::core::Variable::getSite(), nidas::core::Variable::getStation(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTag::getVariables(), nidas::core::VariableIterator::hasNext(), init(), nidas::core::VariableIterator::next(), and WLOG.
disconnect()
void SampleAverager::disconnect (SampleSource * source) throw () virtual
Implements nidas::core::Resampler.
flush()
void SampleAverager::flush () throw () virtual
Implementation of Resampler::flush().
Implements nidas::core::Resampler.
References _averagePeriodUsecs, _cnts, _endTime, _ndataValues, _outSample, _source, _sums, nidas::core::SampleSourceSupport::distribute(), nidas::core::floatNAN, fp, nidas::core::SampleT< DataT >::freeReference(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::SampleTag::getId(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
getAveragePeriodSecs()
float nidas::core::SampleAverager::getAveragePeriodSecs () const inline
Get average period.
Returns
average period, in seconds.
References _averagePeriodUsecs, and USECS_PER_SEC.
getClientCount()
int nidas::core::SampleAverager::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getClientCount().
getProcessedSampleSource()
SampleSource* nidas::core::SampleAverager::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _source.
getRawSampleSource()
SampleSource* nidas::core::SampleAverager::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getSampleStats()
const SampleStats& nidas::core::SampleAverager::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::SampleAverager::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::SampleAverager::getSampleTags () const inline virtual
Get the output SampleTags.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::psql::PSQLProcessor::getSampleTags().
init()
void SampleAverager::init () throw () protected
References _cnts, _endTime, _ndataValues, and _sums.
Referenced by connect().
operator=()
SampleAverager& nidas::core::SampleAverager::operator= (const SampleAverager &) private
No assignment.
receive()
bool SampleAverager::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implements nidas::core::SampleClient.
References nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::core::floatNAN, nidas::util::UTime::format(), fp, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), and nidas::util::timeCeiling().
removeSampleClient()
void nidas::core::SampleAverager::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleClientForTag()
void nidas::core::SampleAverager::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleTag()
void nidas::core::SampleAverager::removeSampleTag (const SampleTag *) throw () inline private virtual
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleTag().
setAveragePeriodSecs()
void nidas::core::SampleAverager::setAveragePeriodSecs (float val) inline
Set average period.
Parameters
val average period, in seconds.
References _averagePeriodUsecs, _outSample, nidas::core::SampleTag::setRate(), and USECS_PER_SEC.
Referenced by SampleAverager().
Member Data Documentation
_averagePeriodUsecs
int nidas::core::SampleAverager::_averagePeriodUsecs private
Length of average, in microseconds.
Referenced by flush(), getAveragePeriodSecs(), and setAveragePeriodSecs().
_cnts
int* nidas::core::SampleAverager::_cnts private
Referenced by flush(), init(), and ~SampleAverager().
_endTime
dsm_time_t nidas::core::SampleAverager::_endTime private
end time of current statistics window.
Referenced by flush(), and init().
_inmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::SampleAverager::_inmap private
Referenced by connect().
_lenmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::SampleAverager::_lenmap private
Referenced by connect().
_ndataValues
unsigned int nidas::core::SampleAverager::_ndataValues private
Referenced by addVariable(), flush(), and init().
_outmap
std::map<dsm_sample_id_t,std::vector<unsigned int> > nidas::core::SampleAverager::_outmap private
Referenced by connect().
_outSample
SampleTag nidas::core::SampleAverager::_outSample private
Referenced by addVariable(), connect(), flush(), SampleAverager(), and setAveragePeriodSecs().
_outVarIndices
std::map<Variable*,unsigned int> nidas::core::SampleAverager::_outVarIndices private
Index of each requested output variable in the output sample.
Referenced by addVariable(), and connect().
_source
SampleSourceSupport nidas::core::SampleAverager::_source private
Referenced by addSampleClient(), addSampleClientForTag(), addSampleTag(), flush(), getClientCount(), getProcessedSampleSource(), getSampleStats(), getSampleTagIterator(), getSampleTags(), removeSampleClient(), removeSampleClientForTag(), and removeSampleTag().
_sums
double* nidas::core::SampleAverager::_sums private
Referenced by flush(), init(), and ~SampleAverager().
The documentation for this class was generated from the following files:
nidas/core/SampleAverager.h
nidas/core/SampleAverager.cc