nidas: nidas::core::MessageStreamScanner Class Reference
nidas::core::MessageStreamScanner Class Reference
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
#include <SampleScanner.h>
Public Member Functions
MessageStreamScanner (int bufsize=4096)
void setMessageParameters (unsigned int len, const std::string &val, bool eom)
const std::string & getMessageSeparator () const
Get message separator string.
const std::string getBackslashedMessageSeparator () const
Get message separator with backslash sequences added back.
bool getMessageSeparatorAtEOM () const
unsigned int getMessageLength () const
Returns 0.
void setNullTerminate (bool val)
bool getNullTerminate () const
Should the SampleScanner append a null character, '\0', to the messages.
Sample * nextSample (DSMSensor *sensor)
Extract the next sample from the buffer.
size_t readBuffer (DSMSensor *sensor, bool &exhausted)
size_t readBuffer (DSMSensor *sensor, bool &exhausted, int msecTimeout)
void warnNonIncrTimeTag (const DSMSensor *sensor, dsm_time_t badtt, dsm_time_t cortt, unsigned int nbad)
Issue warning log message about a non-forward time tag.
void warnBackwardsStepTimeTag (const DSMSensor *sensor, dsm_time_t badtt, unsigned int nbad)
virtual void init ()
Initialize the scanner.
void setUsecsPerByte (int val)
int getUsecsPerByte () const
virtual void clearBuffer ()
unsigned int getBytesInBuffer () const
virtual void resetStatistics ()
virtual void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
unsigned int getBadTimeTagCount () const
float getObservedSamplingRate () const
float getObservedDataRate () const
void addNumBytesToStats (size_t val)
void addSampleToStats (unsigned int val)
void incrementBadTimeTags ()
Protected Member Functions
virtual Sample * nextSampleSepBOM (DSMSensor *sensor)
Method to read input and break it into samples where the message separator occurs at the beginning of the message.
virtual Sample * nextSampleSepEOM (DSMSensor *sensor)
Method to read input and break it into samples where the message separator occurs at the end of the message.
Sample * nextSampleByLength (DSMSensor *sensor)
Method to read input and break it into samples strictly by record length.
Sample * requestBiggerSample (unsigned int nc)
If a new sample can be allocated without exceeding MAX_MESSAGE_STREAM_SAMPLE_SIZE then get a new, larger sample, copying the timetag, id and existing data from the current sample, and return null.
Protected Attributes
Sample *(MessageStreamScanner::* _nextSampleFunc)(DSMSensor *)
dsm_time_t _tfirstchar
dsm_time_t _lastBufferTime
dsm_time_t _lastSampleTime
const unsigned int MAX_MESSAGE_STREAM_SAMPLE_SIZE
int _separatorCnt
dsm_time_t _bomtt
int _sampleOverflows
unsigned int _sampleLengthAlloc
Size of samples to allocate.
bool _nullTerminate
int _nsmallSamples
Count of number of consecutive samples smaller than _sampleLengthAlloc.
unsigned int _outSampLengthAlloc
Number of bytes allocated in data portion of current output sample.
bool _stepBackwards
If the system time of a buffer read is earlier than the previous read.
unsigned int _stepBackTimeTag
Number of time tags that were not monotonically increasing, due to backward step changes.
unsigned int _nonIncrTimeTag
Number of time tags that were not monotonically increasing, not because of backward step changes, but instead due to system buffering, where the receipt times of two buffers are closer together than should be possible at the given baud rate.
const unsigned int BUFSIZE
Buffer size for reading from sensor.
char * _buffer
unsigned int _bufhead
unsigned int _buftail
Sample * _osamp
struct dsm_sample _header
unsigned int _outSampRead
unsigned int _outSampToRead
char * _outSampDataPtr
std::string _messageSeparator
int _messageLength
bool _separatorAtEOM
char * _separator
messageSeparator in a C string.
int _separatorLen
Length of messageSeparator.
Private Attributes
std::string _emptyString
time_t _initialTimeSecs
unsigned int _minSampleLength [2]
unsigned int _maxSampleLength [2]
int _currentIndex
int _reportIndex
size_t _nsamples
size_t _nbytes
unsigned int _badTimeTags
float _sampleRateObs
Observed number of samples per second.
float _dataRateObs
int _usecsPerByte
Detailed Description
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
Timetags are applied to the samples based on the time of receipt of each chunk of data, corrected backwards by the computed tranmission time of each byte in the chunk.
See also
setUsecsPerByte().
Constructor & Destructor Documentation
MessageStreamScanner()
MessageStreamScanner::MessageStreamScanner (int bufsize = 4096)
Member Function Documentation
addNumBytesToStats()
void nidas::core::SampleScanner::addNumBytesToStats (size_t val) inline inherited
References nidas::core::SampleScanner::_nbytes.
Referenced by nidas::core::SampleScanner::readBuffer(), and nidas::core::DatagramSampleScanner::readBuffer().
addSampleToStats()
void nidas::core::SampleScanner::addSampleToStats (unsigned int val) inline inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_nsamples.
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
calcStatistics()
void SampleScanner::calcStatistics (unsigned int periodUsec) virtual inherited
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, nidas::core::SampleScanner::_sampleRateObs, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::calcStatistics().
clearBuffer()
void SampleScanner::clearBuffer () virtual inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
Referenced by nidas::core::DSMSensor::clearBuffer().
getBackslashedMessageSeparator()
const string MessageStreamScanner::getBackslashedMessageSeparator () const virtual
Get message separator with backslash sequences added back.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator, and nidas::util::addBackslashSequences().
getBadTimeTagCount()
unsigned int nidas::core::SampleScanner::getBadTimeTagCount () const inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DSMSensor::getBadTimeTagCount().
getBytesInBuffer()
unsigned int nidas::core::SampleScanner::getBytesInBuffer () const inline inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
getMaxSampleLength()
unsigned int nidas::core::SampleScanner::getMaxSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMaxSampleLength().
getMessageLength()
unsigned int nidas::core::MessageStreamScanner::getMessageLength () const inline virtual
Returns 0.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageLength.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and setMessageParameters().
getMessageSeparator()
const std::string& nidas::core::MessageStreamScanner::getMessageSeparator () const inline virtual
Get message separator string.
Any backslash sequences will have been replaced by their intended value.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator.
getMessageSeparatorAtEOM()
bool nidas::core::MessageStreamScanner::getMessageSeparatorAtEOM () const inline virtual
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_separatorAtEOM.
Referenced by setMessageParameters().
getMinSampleLength()
unsigned int nidas::core::SampleScanner::getMinSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMinSampleLength().
getNullTerminate()
bool nidas::core::MessageStreamScanner::getNullTerminate () const inline virtual
Should the SampleScanner append a null character, '\0', to the messages.
Reimplemented from nidas::core::SampleScanner.
References _nullTerminate.
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), requestBiggerSample(), and setMessageParameters().
getObservedDataRate()
float SampleScanner::getObservedDataRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nbytes, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getObservedDataRate().
getObservedSamplingRate()
float SampleScanner::getObservedSamplingRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::DSMSensor::getObservedSamplingRate().
getUsecsPerByte()
int nidas::core::SampleScanner::getUsecsPerByte () const inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and readBuffer().
incrementBadTimeTags()
void nidas::core::SampleScanner::incrementBadTimeTags () inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DriverSampleScanner::nextSample().
init()
void SampleScanner::init () virtual inherited
Initialize the scanner.
Must be called by a user of SampleScanner prior to calling readSamples().
References nidas::core::SampleScanner::resetStatistics().
Referenced by nidas::core::DSMSensor::open().
nextSample()
Sample* nidas::core::MessageStreamScanner::nextSample (DSMSensor * sensor) inline virtual
Extract the next sample from the buffer.
Returns NULL if there are no more samples in the buffer.
Implements nidas::core::SampleScanner.
References _nextSampleFunc.
nextSampleByLength()
Sample * MessageStreamScanner::nextSampleByLength (DSMSensor * sensor) protected
Method to read input and break it into samples strictly by record length.
References nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, _lastSampleTime, _nonIncrTimeTag, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, _separatorCnt, _stepBackTimeTag, _stepBackwards, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), requestBiggerSample(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), warnBackwardsStepTimeTag(), and warnNonIncrTimeTag().
Referenced by setMessageParameters().
nextSampleSepBOM()
Sample * MessageStreamScanner::nextSampleSepBOM (DSMSensor * sensor) protected virtual
Method to read input and break it into samples where the message separator occurs at the beginning of the message.
References _bomtt, nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, _lastSampleTime, _nonIncrTimeTag, _nsmallSamples, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, nidas::core::SampleScanner::_separator, _separatorCnt, nidas::core::SampleScanner::_separatorLen, _stepBackTimeTag, _stepBackwards, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), getNullTerminate(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, requestBiggerSample(), nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), warnBackwardsStepTimeTag(), and warnNonIncrTimeTag().
Referenced by setMessageParameters().
nextSampleSepEOM()
Sample * MessageStreamScanner::nextSampleSepEOM (DSMSensor * sensor) protected virtual
Method to read input and break it into samples where the message separator occurs at the end of the message.
References nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, _lastSampleTime, _nonIncrTimeTag, _nsmallSamples, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, nidas::core::SampleScanner::_separator, _separatorCnt, nidas::core::SampleScanner::_separatorLen, _stepBackTimeTag, _stepBackwards, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), getNullTerminate(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, requestBiggerSample(), nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), warnBackwardsStepTimeTag(), and warnNonIncrTimeTag().
Referenced by setMessageParameters().
readBuffer() [1/2]
size_t MessageStreamScanner::readBuffer (DSMSensor * sensor, bool & exhausted) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleScanner.
References _lastBufferTime, _stepBackwards, _tfirstchar, nidas::util::getSystemTime(), nidas::core::SampleScanner::getUsecsPerByte(), and nidas::core::SampleScanner::readBuffer().
readBuffer() [2/2]
size_t MessageStreamScanner::readBuffer (DSMSensor * sensor, bool & exhausted, int msecTimeout) virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::SampleScanner.
References _lastBufferTime, _stepBackwards, _tfirstchar, nidas::util::getSystemTime(), nidas::core::SampleScanner::getUsecsPerByte(), and nidas::core::SampleScanner::readBuffer().
requestBiggerSample()
Sample * MessageStreamScanner::requestBiggerSample (unsigned int nc) protected
If a new sample can be allocated without exceeding MAX_MESSAGE_STREAM_SAMPLE_SIZE then get a new, larger sample, copying the timetag, id and existing data from the current sample, and return null.
The data members _osamp, and _outSampDataPtr are updated to point to the new sample. Otherwise, since we've reached the MAX limit, more data will not be added to the sample, so return a pointer to the existing max'd out sample, which should then be returned as the value of the nextSample() method.
References nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleOverflows, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::freeReference(), nidas::core::Sample::getAllocByteLength(), nidas::core::Sample::getId(), getNullTerminate(), nidas::core::Sample::getTimeTag(), nidas::core::SampleT< DataT >::getVoidDataPtr(), nidas::core::Sample::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
resetStatistics()
void SampleScanner::resetStatistics () virtual inherited
References nidas::core::SampleScanner::_badTimeTags, nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::SampleScanner::init(), and nidas::core::SampleScanner::SampleScanner().
setMessageParameters()
void MessageStreamScanner::setMessageParameters (unsigned int len, const std::string & val, bool eom) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageLength, nidas::core::SampleScanner::_messageSeparator, _nextSampleFunc, _sampleLengthAlloc, nidas::core::SampleScanner::_separator, nidas::core::SampleScanner::_separatorAtEOM, nidas::core::SampleScanner::_separatorLen, getMessageLength(), getMessageSeparatorAtEOM(), getNullTerminate(), len, MAX_MESSAGE_STREAM_SAMPLE_SIZE, nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), nidas::util::replaceBackslashSequences(), and setNullTerminate().
Referenced by nidas::dynld::GPS_NMEA_Serial::buildSampleScanner().
setNullTerminate()
void nidas::core::MessageStreamScanner::setNullTerminate (bool val) inline
References _nullTerminate.
Referenced by nidas::core::CharacterSensor::buildSampleScanner(), nidas::dynld::GPS_NMEA_Serial::buildSampleScanner(), and setMessageParameters().
setUsecsPerByte()
void nidas::core::SampleScanner::setUsecsPerByte (int val) inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nidas::core::SerialSensor::buildSampleScanner(), and nidas::dynld::GPS_NMEA_Serial::buildSampleScanner().
warnBackwardsStepTimeTag()
void MessageStreamScanner::warnBackwardsStepTimeTag (const DSMSensor * sensor, dsm_time_t badtt, unsigned int nbad)
References nidas::util::UTime::format(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::getSensorId(), and WLOG.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
warnNonIncrTimeTag()
void MessageStreamScanner::warnNonIncrTimeTag (const DSMSensor * sensor, dsm_time_t badtt, dsm_time_t cortt, unsigned int nbad)
Issue warning log message about a non-forward time tag.
References nidas::util::UTime::format(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::getSensorId(), USECS_PER_SEC, and WLOG.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
Member Data Documentation
_badTimeTags
unsigned int nidas::core::SampleScanner::_badTimeTags private inherited
Referenced by nidas::core::SampleScanner::getBadTimeTagCount(), nidas::core::SampleScanner::incrementBadTimeTags(), and nidas::core::SampleScanner::resetStatistics().
_bomtt
dsm_time_t nidas::core::MessageStreamScanner::_bomtt protected
Referenced by nextSampleSepBOM().
_buffer
char* nidas::core::SampleScanner::_buffer protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), nidas::core::SampleScanner::readBuffer(), nidas::core::DatagramSampleScanner::readBuffer(), and nidas::core::SampleScanner::~SampleScanner().
_bufhead
unsigned int nidas::core::SampleScanner::_bufhead protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), nidas::core::SampleScanner::readBuffer(), and nidas::core::DatagramSampleScanner::readBuffer().
_buftail
unsigned int nidas::core::SampleScanner::_buftail protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), nidas::core::SampleScanner::readBuffer(), and nidas::core::DatagramSampleScanner::readBuffer().
_currentIndex
int nidas::core::SampleScanner::_currentIndex private inherited
Referenced by nidas::core::SampleScanner::addSampleToStats(), nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getObservedDataRate(), nidas::core::SampleScanner::getObservedSamplingRate(), and nidas::core::SampleScanner::resetStatistics().
_dataRateObs
float nidas::core::SampleScanner::_dataRateObs private inherited
Referenced by nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getObservedDataRate(), and nidas::core::SampleScanner::resetStatistics().
_emptyString
std::string nidas::core::SampleScanner::_emptyString private inherited
Referenced by nidas::core::SampleScanner::getBackslashedMessageSeparator(), and nidas::core::SampleScanner::getMessageSeparator().
_header
struct dsm_sample nidas::core::SampleScanner::_header protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
_initialTimeSecs
time_t nidas::core::SampleScanner::_initialTimeSecs private inherited
Referenced by nidas::core::SampleScanner::getObservedDataRate(), nidas::core::SampleScanner::getObservedSamplingRate(), and nidas::core::SampleScanner::resetStatistics().
_lastBufferTime
dsm_time_t nidas::core::MessageStreamScanner::_lastBufferTime protected
Referenced by readBuffer().
_lastSampleTime
dsm_time_t nidas::core::MessageStreamScanner::_lastSampleTime protected
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
_maxSampleLength
unsigned int nidas::core::SampleScanner::_maxSampleLength[2] private inherited
Referenced by nidas::core::SampleScanner::addSampleToStats(), nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getMaxSampleLength(), nidas::core::SampleScanner::getMinSampleLength(), and nidas::core::SampleScanner::resetStatistics().
_messageLength
int nidas::core::SampleScanner::_messageLength protected inherited
Referenced by nidas::core::MessageSampleScanner::getMessageLength(), getMessageLength(), and setMessageParameters().
_messageSeparator
std::string nidas::core::SampleScanner::_messageSeparator protected inherited
Referenced by nidas::core::MessageSampleScanner::getBackslashedMessageSeparator(), getBackslashedMessageSeparator(), nidas::core::MessageSampleScanner::getMessageSeparator(), getMessageSeparator(), nidas::core::MessageSampleScanner::setMessageParameters(), and setMessageParameters().
_minSampleLength
unsigned int nidas::core::SampleScanner::_minSampleLength[2] private inherited
Referenced by nidas::core::SampleScanner::addSampleToStats(), nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getMinSampleLength(), and nidas::core::SampleScanner::resetStatistics().
_nbytes
size_t nidas::core::SampleScanner::_nbytes private inherited
Referenced by nidas::core::SampleScanner::addNumBytesToStats(), nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getObservedDataRate(), and nidas::core::SampleScanner::resetStatistics().
_nextSampleFunc
Sample*(MessageStreamScanner::* nidas::core::MessageStreamScanner::_nextSampleFunc) (DSMSensor *) protected
Referenced by nextSample(), and setMessageParameters().
_nonIncrTimeTag
unsigned int nidas::core::MessageStreamScanner::_nonIncrTimeTag protected
Number of time tags that were not monotonically increasing, not because of backward step changes, but instead due to system buffering, where the receipt times of two buffers are closer together than should be possible at the given baud rate.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
_nsamples
size_t nidas::core::SampleScanner::_nsamples private inherited
Referenced by nidas::core::SampleScanner::addSampleToStats(), nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getObservedSamplingRate(), and nidas::core::SampleScanner::resetStatistics().
_nsmallSamples
int nidas::core::MessageStreamScanner::_nsmallSamples protected
Count of number of consecutive samples smaller than _sampleLengthAlloc.
Referenced by nextSampleSepBOM(), and nextSampleSepEOM().
_nullTerminate
bool nidas::core::MessageStreamScanner::_nullTerminate protected
Referenced by getNullTerminate(), and setNullTerminate().
_osamp
Sample* nidas::core::SampleScanner::_osamp protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), requestBiggerSample(), and nidas::core::SampleScanner::~SampleScanner().
_outSampDataPtr
char* nidas::core::SampleScanner::_outSampDataPtr protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
_outSampLengthAlloc
unsigned int nidas::core::MessageStreamScanner::_outSampLengthAlloc protected
Number of bytes allocated in data portion of current output sample.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
_outSampRead
unsigned int nidas::core::SampleScanner::_outSampRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
_outSampToRead
unsigned int nidas::core::SampleScanner::_outSampToRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
_reportIndex
int nidas::core::SampleScanner::_reportIndex private inherited
Referenced by nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getMaxSampleLength(), nidas::core::SampleScanner::getMinSampleLength(), nidas::core::SampleScanner::getObservedDataRate(), nidas::core::SampleScanner::getObservedSamplingRate(), and nidas::core::SampleScanner::resetStatistics().
_sampleLengthAlloc
unsigned int nidas::core::MessageStreamScanner::_sampleLengthAlloc protected
Size of samples to allocate.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and setMessageParameters().
_sampleOverflows
int nidas::core::MessageStreamScanner::_sampleOverflows protected
Referenced by requestBiggerSample().
_sampleRateObs
float nidas::core::SampleScanner::_sampleRateObs private inherited
Observed number of samples per second.
Referenced by nidas::core::SampleScanner::calcStatistics(), nidas::core::SampleScanner::getObservedSamplingRate(), and nidas::core::SampleScanner::resetStatistics().
_separator
char* nidas::core::SampleScanner::_separator protected inherited
messageSeparator in a C string.
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), setMessageParameters(), and nidas::core::SampleScanner::~SampleScanner().
_separatorAtEOM
bool nidas::core::SampleScanner::_separatorAtEOM protected inherited
Referenced by nidas::core::MessageSampleScanner::getMessageSeparatorAtEOM(), getMessageSeparatorAtEOM(), nidas::core::MessageSampleScanner::setMessageParameters(), and setMessageParameters().
_separatorCnt
int nidas::core::MessageStreamScanner::_separatorCnt protected
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
_separatorLen
int nidas::core::SampleScanner::_separatorLen protected inherited
Length of messageSeparator.
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), nidas::core::MessageSampleScanner::setMessageParameters(), and setMessageParameters().
_stepBackTimeTag
unsigned int nidas::core::MessageStreamScanner::_stepBackTimeTag protected
Number of time tags that were not monotonically increasing, due to backward step changes.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
_stepBackwards
bool nidas::core::MessageStreamScanner::_stepBackwards protected
If the system time of a buffer read is earlier than the previous read.
This should only happen due to a step change of the system clock.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and readBuffer().
_tfirstchar
dsm_time_t nidas::core::MessageStreamScanner::_tfirstchar protected
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and readBuffer().
_usecsPerByte
int nidas::core::SampleScanner::_usecsPerByte private inherited
Referenced by nidas::core::SampleScanner::getUsecsPerByte(), and nidas::core::SampleScanner::setUsecsPerByte().
BUFSIZE
const unsigned int nidas::core::SampleScanner::BUFSIZE protected inherited
Buffer size for reading from sensor.
Referenced by nidas::core::SampleScanner::readBuffer(), and nidas::core::DatagramSampleScanner::readBuffer().
MAX_MESSAGE_STREAM_SAMPLE_SIZE
const unsigned int nidas::core::MessageStreamScanner::MAX_MESSAGE_STREAM_SAMPLE_SIZE protected
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), requestBiggerSample(), and setMessageParameters().
The documentation for this class was generated from the following files:
nidas/core/SampleScanner.h
nidas/core/SampleScanner.cc