nidas: DataPrep Class Reference
DataPrep Class Reference
Public Member Functions
DataPrep ()
~DataPrep ()
int parseRunstring (int argc, char **argv)
void parseNcServerSpec (const std::string &spec)
int run () throw ()
int usage ()
map< double, vector< const Variable * > > matchVariables (const Project &, set< const DSMConfig * > &activeDsms, set< DSMSensor * > &activeSensors)
Static Public Member Functions
static int main (int argc, char **argv)
Static Public Attributes
static const int defaultNCInterval = 1
static const int defaultNCLength = 86400
static const float defaultNCFillValue = 1.e37
static const int defaultNCTimeout = 60
static const int defaultNCBatchPeriod = 300
Private Attributes
NidasApp _app
string _xmlFileName
list< string > _dataFileNames
float _sorterLength
DumpClient::format_t _format
map< double, vector< Variable * > > _reqVarsByRate
map< Variable *, string > _sites
n_u::UTime _startTime
n_u::UTime _endTime
std::string _configName
bool _middleTimeTags
bool _dosOut
bool _doHeader
bool _clipping
int _asciiPrecision
string _ncserver
string _ncdir
string _ncfile
int _ncinterval
int _nclength
string _nccdl
float _ncfill
int _nctimeout
int _ncbatchperiod
list< Resampler * > _resamplers
string _dsmName
string _datasetName
BadSampleFilterArg _FilterArg
NidasAppArg DataVariables
NidasAppArg DataRate
NidasAppArg DatasetName
NidasAppArg ConfigsName
NidasAppArg DSMName
NidasAppArg DumpASCII
NidasAppArg DumpBINARY
NidasAppArg DOSOutput
NidasAppArg Clipping
NidasAppArg SorterLength
NidasAppArg Precision
NidasAppArg NoHeader
NidasAppArg NetcdfOutput
NidasAppArg HeapSize
Static Private Attributes
static const int DEFAULT_PORT = 30000
static const char * _isffDatasetsXML
static const char * _isfsDatasetsXML
Constructor & Destructor Documentation
DataPrep()
DataPrep::DataPrep ()
~DataPrep()
DataPrep::~DataPrep ()
References _reqVarsByRate, and _resamplers.
Member Function Documentation
main()
int DataPrep::main (int argc, char ** argv) static
References parseRunstring(), run(), and setupSignals().
Referenced by main().
matchVariables()
map< double, vector< const Variable * > > DataPrep::matchVariables (const Project & project, set< const DSMConfig * > & activeDsms, set< DSMSensor * > & activeSensors)
References _app, _reqVarsByRate, nidas::core::Variable::closeMatch(), nidas::core::Project::getDSMConfigIterator(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::NidasApp::getProcessName(), nidas::core::DSMConfig::getSensors(), nidas::core::Variable::getSite(), nidas::core::Variable::getStation(), nidas::core::DSMSensor::getVariableIterator(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::DSMConfigIterator::next(), nidas::core::VariableIterator::next(), rate, and VLOG.
Referenced by run().
parseNcServerSpec()
void DataPrep::parseNcServerSpec (const std::string & spec)
References _ncbatchperiod, _nccdl, _ncdir, _ncfile, _ncfill, _ncinterval, _nclength, _ncserver, and _nctimeout.
Referenced by parseRunstring().
parseRunstring()
int DataPrep::parseRunstring (int argc, char ** argv)
References _app, _asciiPrecision, _clipping, _configName, _dataFileNames, _datasetName, _doHeader, _dosOut, _dsmName, _endTime, _FilterArg, _format, _middleTimeTags, _reqVarsByRate, _sites, _sorterLength, _startTime, _xmlFileName, nidas::core::NidasAppInputFilesArg::allowFiles, nidas::core::NidasAppInputFilesArg::allowSockets, nidas::core::NidasAppArg::asBool(), DumpClient::ASCII, nidas::core::NidasAppArg::asFloat(), nidas::core::NidasAppArg::asInt(), DumpClient::BINARY1, Clipping, ConfigsName, nidas::core::NidasApp::dataFileNames(), DataRate, DatasetName, DataVariables, DEFAULT_PORT, defaultNCFillValue, defaultNCInterval, defaultNCTimeout, DOSOutput, DSMName, DumpASCII, DumpBINARY, nidas::core::NidasApp::enableArguments(), nidas::core::NidasApp::EndTime, nidas::core::NidasApp::getEndTime(), nidas::core::NidasAppArg::getFlag(), nidas::core::NidasApp::getStartTime(), nidas::core::NidasAppArg::getValue(), HeapSize, nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::InputFiles, nidas::core::NidasApp::loggingArgs(), NetcdfOutput, NoHeader, nidas::core::NidasApp::parseInputs(), parseNcServerSpec(), nidas::core::NidasApp::parseNext(), Precision, rate, nidas::core::NidasAppInputFilesArg::setDefaultInput(), nidas::core::NidasAppArg::setFlags(), nidas::core::Variable::setName(), nidas::core::NidasAppArg::setUsageString(), nidas::core::NidasApp::socketAddress(), SorterLength, nidas::core::NidasApp::startArgs(), nidas::core::NidasApp::StartTime, nidas::util::UTime::toUsecs(), nidas::core::NidasApp::unparsedArgs(), usage(), USECS_PER_DAY, nidas::core::NidasApp::Version, nidas::core::NidasApp::XmlHeaderFile, and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
run()
int DataPrep::run () throw ()
References _app, _asciiPrecision, _clipping, _configName, _dataFileNames, _datasetName, _doHeader, _dosOut, _dsmName, _endTime, _FilterArg, _format, _middleTimeTags, _ncbatchperiod, _nccdl, _ncdir, _ncfile, _ncfill, _ncinterval, _nclength, _ncserver, _nctimeout, _reqVarsByRate, _resamplers, _sites, _sorterLength, _startTime, _xmlFileName, nidas::util::LogContext::active(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::core::SampleSource::addSampleTag(), nidas::core::NidasAppArg::asInt(), nidas::core::FileSet::clone(), nidas::dynld::SampleInputStream::close(), nidas::core::SamplePipeline::connect(), nidas::core::SamplePipeline::disconnect(), DLOG, nidas::util::Process::expandEnvVars(), nidas::core::Project::findSampleOutputStreamFileSets(), nidas::core::Project::findServerSampleOutputStreamFileSets(), DumpClient::finished(), nidas::core::SamplePipeline::flush(), nidas::util::UTime::format(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfig::getBeginTime(), nidas::core::ProjectConfigs::getConfig(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::NidasApp::getConfigsXML(), nidas::core::NidasApp::getDataset(), nidas::core::ProjectConfig::getEndTime(), nidas::core::FileSet::getFileSet(), nidas::core::BadSampleFilterArg::getFilter(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::Variable::getName(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleSource::getSampleTags(), nidas::core::Variable::getStation(), nidas::core::ProjectConfig::getXMLName(), nidas::core::SampleTagIterator::hasNext(), HeapSize, ILOG, nidas::core::DSMSensor::init(), nidas::core::ProjectConfig::initProject(), nidas::core::SamplePipeline::interrupt(), nidas::core::NidasApp::interrupted(), nidas::core::SamplePipeline::join(), LOG_VERBOSE, matchVariables(), nidas::core::SampleTagIterator::next(), nidas::core::ProjectConfigs::parseXML(), nidas::core::parseXMLConfigFile(), PLOG, DumpClient::printHeader(), rate, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSamples(), nidas::dynld::SampleInputStream::search(), nidas::dynld::SampleInputStream::setBadSampleFilter(), nidas::core::Project::setConfigName(), nidas::core::Project::setDataset(), nidas::core::BadSampleFilter::setDefaultTimeRange(), DumpClient::setDOS(), DumpClient::setEndTime(), nidas::core::FileSet::setEndTime(), nidas::core::NearestResamplerAtRate::setFillGaps(), nidas::core::NearestResamplerAtRate::setMiddleTimeTags(), nidas::core::Variable::setName(), nidas::core::SamplePipeline::setProcHeapMax(), nidas::core::SamplePipeline::setProcLateSampleCacheSize(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::NearestResamplerAtRate::setRate(), nidas::core::SampleTag::setRate(), nidas::core::SamplePipeline::setRawHeapMax(), nidas::core::SamplePipeline::setRawLateSampleCacheSize(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), nidas::core::Variable::setSite(), DumpClient::setStartTime(), nidas::core::FileSet::setStartTime(), nidas::core::NidasApp::socketAddress(), nidas::util::UTime::toUsecs(), USECS_PER_SEC, VLOG, nidas::util::Exception::what(), and WLOG.
Referenced by main().
usage()
int DataPrep::usage ()
References _app, DEFAULT_PORT, nidas::core::NidasApp::getProcessName(), and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
_app
NidasApp DataPrep::_app private
Referenced by matchVariables(), parseRunstring(), run(), and usage().
_asciiPrecision
int DataPrep::_asciiPrecision private
Referenced by parseRunstring(), and run().
_clipping
bool DataPrep::_clipping private
Referenced by parseRunstring(), and run().
_configName
std::string DataPrep::_configName private
Referenced by parseRunstring(), and run().
_dataFileNames
list<string> DataPrep::_dataFileNames private
Referenced by parseRunstring(), and run().
_datasetName
string DataPrep::_datasetName private
Referenced by parseRunstring(), and run().
_doHeader
bool DataPrep::_doHeader private
Referenced by parseRunstring(), and run().
_dosOut
bool DataPrep::_dosOut private
Referenced by parseRunstring(), and run().
_dsmName
string DataPrep::_dsmName private
Referenced by parseRunstring(), and run().
_endTime
n_u::UTime DataPrep::_endTime private
Referenced by parseRunstring(), and run().
_FilterArg
BadSampleFilterArg DataPrep::_FilterArg private
Referenced by parseRunstring(), and run().
_format
DumpClient::format_t DataPrep::_format private
Referenced by parseRunstring(), and run().
_isffDatasetsXML
const char* DataPrep::_isffDatasetsXML static private
_isfsDatasetsXML
const char* DataPrep::_isfsDatasetsXML static private
_middleTimeTags
bool DataPrep::_middleTimeTags private
Referenced by parseRunstring(), and run().
_ncbatchperiod
int DataPrep::_ncbatchperiod private
Referenced by parseNcServerSpec(), and run().
_nccdl
string DataPrep::_nccdl private
Referenced by parseNcServerSpec(), and run().
_ncdir
string DataPrep::_ncdir private
Referenced by parseNcServerSpec(), and run().
_ncfile
string DataPrep::_ncfile private
Referenced by parseNcServerSpec(), and run().
_ncfill
float DataPrep::_ncfill private
Referenced by parseNcServerSpec(), and run().
_ncinterval
int DataPrep::_ncinterval private
Referenced by parseNcServerSpec(), and run().
_nclength
int DataPrep::_nclength private
Referenced by parseNcServerSpec(), and run().
_ncserver
string DataPrep::_ncserver private
Referenced by parseNcServerSpec(), and run().
_nctimeout
int DataPrep::_nctimeout private
Referenced by parseNcServerSpec(), and run().
_reqVarsByRate
map<double, vector<Variable*> > DataPrep::_reqVarsByRate private
Referenced by matchVariables(), parseRunstring(), run(), and ~DataPrep().
_resamplers
list<Resampler*> DataPrep::_resamplers private
Referenced by run(), and ~DataPrep().
_sites
map<Variable*, string> DataPrep::_sites private
Referenced by parseRunstring(), and run().
_sorterLength
float DataPrep::_sorterLength private
Referenced by parseRunstring(), and run().
_startTime
n_u::UTime DataPrep::_startTime private
Referenced by parseRunstring(), and run().
_xmlFileName
string DataPrep::_xmlFileName private
Referenced by parseRunstring(), and run().
Clipping
NidasAppArg DataPrep::Clipping private
Referenced by parseRunstring().
ConfigsName
NidasAppArg DataPrep::ConfigsName private
Referenced by parseRunstring().
DataRate
NidasAppArg DataPrep::DataRate private
Referenced by parseRunstring().
DatasetName
NidasAppArg DataPrep::DatasetName private
Referenced by parseRunstring().
DataVariables
NidasAppArg DataPrep::DataVariables private
Referenced by parseRunstring().
DEFAULT_PORT
const int DataPrep::DEFAULT_PORT = 30000 static private
Referenced by parseRunstring(), and usage().
defaultNCBatchPeriod
const int DataPrep::defaultNCBatchPeriod = 300 static
defaultNCFillValue
const float DataPrep::defaultNCFillValue = 1.e37 static
Referenced by parseRunstring().
defaultNCInterval
const int DataPrep::defaultNCInterval = 1 static
Referenced by parseRunstring().
defaultNCLength
const int DataPrep::defaultNCLength = 86400 static
defaultNCTimeout
const int DataPrep::defaultNCTimeout = 60 static
Referenced by parseRunstring().
DOSOutput
NidasAppArg DataPrep::DOSOutput private
Referenced by parseRunstring().
DSMName
NidasAppArg DataPrep::DSMName private
Referenced by parseRunstring().
DumpASCII
NidasAppArg DataPrep::DumpASCII private
Referenced by parseRunstring().
DumpBINARY
NidasAppArg DataPrep::DumpBINARY private
Referenced by parseRunstring().
HeapSize
NidasAppArg DataPrep::HeapSize private
Referenced by parseRunstring(), and run().
NetcdfOutput
NidasAppArg DataPrep::NetcdfOutput private
Referenced by parseRunstring().
NoHeader
NidasAppArg DataPrep::NoHeader private
Referenced by parseRunstring().
Precision
NidasAppArg DataPrep::Precision private
Referenced by parseRunstring().
SorterLength
NidasAppArg DataPrep::SorterLength private
Referenced by parseRunstring().
The documentation for this class was generated from the following file:
nidas/apps/isff/prep.cc