nidas: DataDump Class Reference
DataDump Class Reference
Public Member Functions
DataDump ()
int parseRunstring (int argc, char **argv)
int run () throw ()
int usage (const char *argv0)
Static Public Member Functions
static int main (int argc, char **argv)
Private Attributes
string xmlFileName
DumpClient::format_t format
float warntime
NidasApp app
NidasAppArg WarnTime
NidasAppArg NoDeltaT
NidasAppArg NoLen
NidasAppArg FormatTimeISO
NidasAppArg CSV
BadSampleFilterArg FilterArg
Static Private Attributes
static const int DEFAULT_PORT = 30000
Constructor & Destructor Documentation
DataDump()
DataDump::DataDump ()
References app, nidas::core::NidasApp::setApplicationInstance(), and nidas::core::NidasApp::setupSignals().
Member Function Documentation
main()
int DataDump::main (int argc, char ** argv) static
References parseRunstring(), run(), and nidas::util::Exception::what().
Referenced by main().
parseRunstring()
int DataDump::parseRunstring (int argc, char ** argv)
References nidas::core::NidasAppInputFilesArg::allowFiles, nidas::core::NidasAppInputFilesArg::allowSockets, nidas::core::NidasApp::allowUnrecognized(), app, nidas::core::NidasAppArgv::argc, nidas::core::NidasAppArgv::argv, DumpClient::ASCII, DumpClient::ASCII_7, nidas::core::NidasAppArg::asFloat(), CSV, DEFAULT_PORT, nidas::core::NidasApp::enableArguments(), nidas::core::NidasApp::EndTime, FilterArg, DumpClient::FLOAT, format, nidas::core::NidasApp::FormatHexId, nidas::core::NidasApp::FormatSampleId, FormatTimeISO, nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), DumpClient::HEX_FMT, nidas::core::NidasApp::InputFiles, DumpClient::INT32, DumpClient::IRIG, nidas::core::NidasApp::loggingArgs(), DumpClient::NAKED, NoDeltaT, NoLen, nidas::core::SampleMatcher::numRanges(), nidas::core::NidasApp::parseArgs(), nidas::core::NidasApp::parseInputs(), nidas::core::NidasApp::ProcessData, nidas::core::NidasApp::sampleMatcher(), nidas::core::NidasApp::SampleRanges, nidas::core::NidasAppInputFilesArg::setDefaultInput(), nidas::core::NidasApp::setIdFormat(), DumpClient::SIGNED_SHORT, nidas::core::NidasApp::StartTime, nidas::core::NidasAppArgv::unparsedArgs(), DumpClient::UNSIGNED_SHORT, usage(), nidas::core::NidasApp::Version, warntime, WarnTime, and nidas::core::NidasApp::XmlHeaderFile.
Referenced by main().
run()
int DataDump::run () throw ()
References nidas::dynld::SampleInputStream::addSampleClient(), nidas::core::SampleSource::addSampleClient(), nidas::dynld::SampleInputStream::addSampleTag(), app, nidas::core::NidasAppArg::asBool(), nidas::dynld::SampleInputStream::close(), nidas::core::FileSet::connect(), nidas::core::SamplePipeline::connect(), CSV, nidas::core::NidasApp::dataFileNames(), nidas::core::SamplePipeline::disconnect(), nidas::util::Process::expandEnvVars(), FilterArg, nidas::core::SamplePipeline::flush(), format, FormatTimeISO, nidas::core::SampleInputHeader::getConfigName(), nidas::core::NidasApp::getEndTime(), nidas::core::FileSet::getFileSet(), nidas::core::BadSampleFilterArg::getFilter(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::SamplePipeline::getRawSampleSource(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMConfig::getSensors(), nidas::core::NidasApp::getStartTime(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::DSMSensor::init(), nidas::core::SamplePipeline::interrupt(), nidas::core::NidasApp::interrupted(), ISOFORMAT, nidas::core::SamplePipeline::join(), DumpClient::NAKED, nidas::core::DSMConfigIterator::next(), NoDeltaT, NoLen, nidas::core::parseXMLConfigFile(), DumpClient::printHeader(), nidas::core::NidasApp::processData(), nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSamples(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::core::SampleSource::removeSampleClient(), nidas::core::NidasApp::sampleMatcher(), nidas::dynld::SampleInputStream::setBadSampleFilter(), DumpClient::setCSV(), nidas::core::BadSampleFilter::setDefaultTimeRange(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), DumpClient::setSensors(), DumpClient::setShowDeltaT(), DumpClient::setShowLen(), DumpClient::setTimeFormat(), DumpClient::setWarningTime(), nidas::core::NidasApp::socketAddress(), warntime, nidas::util::Exception::what(), xmlFileName, and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
usage()
int DataDump::usage (const char * argv0)
References app, and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Member Data Documentation
app
NidasApp DataDump::app private
Referenced by DataDump(), parseRunstring(), run(), and usage().
CSV
NidasAppArg DataDump::CSV private
Referenced by parseRunstring(), and run().
DEFAULT_PORT
const int DataDump::DEFAULT_PORT = 30000 static private
Referenced by parseRunstring().
FilterArg
BadSampleFilterArg DataDump::FilterArg private
Referenced by parseRunstring(), and run().
format
DumpClient::format_t DataDump::format private
Referenced by parseRunstring(), and run().
FormatTimeISO
NidasAppArg DataDump::FormatTimeISO private
Referenced by parseRunstring(), and run().
NoDeltaT
NidasAppArg DataDump::NoDeltaT private
Referenced by parseRunstring(), and run().
NoLen
NidasAppArg DataDump::NoLen private
Referenced by parseRunstring(), and run().
warntime
float DataDump::warntime private
Referenced by parseRunstring(), and run().
WarnTime
NidasAppArg DataDump::WarnTime private
Referenced by parseRunstring().
xmlFileName
string DataDump::xmlFileName private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/data_dump.cc