nidas: nidas/dynld/raf/SyncRecordSource.cc File Reference
SyncRecordSource.cc File Reference
#include "SyncRecordSource.h"
#include "Aircraft.h"
#include <nidas/core/SampleInput.h>
#include <nidas/core/Project.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/Variable.h>
#include <nidas/core/CalFile.h>
#include <nidas/util/UTime.h>
#include <nidas/util/Logger.h>
#include <nidas/core/Version.h>
#include <nidas/core/SampleTracer.h>
#include <iomanip>
#include <cmath>
#include <algorithm>
#include <set>
Functions
std::string format_time (dsm_time_t tt, const std::string &fmt="%Y %m %d %H:%M:%S.%3f")
template<typename ST >
void copy_variables_to_record (const Sample *samp, double *dataPtr, int recSize, const vector< size_t > &varSRIndex, const vector< size_t > &varLen, int timeIndex)
Function Documentation
copy_variables_to_record()
template<typename ST > void copy_variables_to_record (const Sample * samp, double * dataPtr, int recSize, const vector< size_t > & varSRIndex, const vector< size_t > & varLen, int timeIndex)
References DLOG, nidas::core::DOUBLE_ST, fp, nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataLength(), and nidas::core::Sample::getType().
format_time()
std::string format_time (dsm_time_t tt, const std::string & fmt = "%Y %m %d %H:%M:%S.%3f") inline
References nidas::util::UTime::format().
Referenced by nidas::dynld::raf::SyncRecordSource::checkTime(), nidas::dynld::raf::SyncRecordSource::sendSyncRecord(), and nidas::dynld::raf::SyncRecordSource::slog().