nidas: nidas::util::SocketAddress Class Reference
nidas::util::SocketAddress Class Reference abstract
An interface for a socket address.
#include <SocketAddress.h>
Public Member Functions
virtual SocketAddress * clone () const =0
Virtual constructor.
virtual ~SocketAddress ()
virtual int getFamily () const =0
Get the family of this SocketAddress, one of the values from /usr/include/sys/socket.h: AF_UNIX, AF_INET, AF_INET6, etc.
virtual int getPort () const =0
return the port number of this address, or -1 if there is no associated port number, e.g.
virtual struct sockaddr * getSockAddrPtr ()=0
Provide non-const pointer to struct sockaddr_in.
virtual const struct sockaddr * getConstSockAddrPtr () const =0
virtual socklen_t getSockAddrLen () const =0
Return the length of the struct sockaddr_XX for this address family.
virtual std::string toString () const =0
Java style toString.
virtual std::string toAddressString () const =0
Java style toString, but no DNS lookup.
Detailed Description
An interface for a socket address.
Constructor & Destructor Documentation
~SocketAddress()
virtual nidas::util::SocketAddress::~SocketAddress () inline virtual
Member Function Documentation
clone()
virtual SocketAddress* nidas::util::SocketAddress::clone () const pure virtual
Virtual constructor.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::DatagramPacketBase::operator=(), nidas::util::SocketImpl::operator=(), nidas::core::DSMServerStat::run(), nidas::core::DSMConfig::setDerivedDataSocketAddr(), nidas::core::Socket::setRemoteSocketAddress(), nidas::core::DatagramSocket::setSocketAddress(), nidas::util::DatagramPacketBase::setSocketAddress(), nidas::core::DSMConfig::setStatusSocketAddr(), nidas::core::DSMServer::setStatusSocketAddr(), and nidas::util::SocketImpl::SocketImpl().
getConstSockAddrPtr()
virtual const struct sockaddr* nidas::util::SocketAddress::getConstSockAddrPtr () const pure virtual
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::addConnection(), nidas::util::SocketImpl::bind(), nidas::core::DatagramSocket::connect(), nidas::core::Socket::connect(), nidas::util::SocketImpl::connect(), nidas::util::DatagramPacketBase::getConstSockAddrPtr(), nidas::core::Socket::getRemoteInet4Address(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::removeConnection(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::sendto().
getFamily()
virtual int nidas::util::SocketAddress::getFamily () const pure virtual
Get the family of this SocketAddress, one of the values from /usr/include/sys/socket.h: AF_UNIX, AF_INET, AF_INET6, etc.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::addConnection(), nidas::core::DatagramSocket::connect(), nidas::core::Socket::connect(), nidas::core::Socket::getRemoteInet4Address(), nidas::util::UnixSocketAddress::operator<(), nidas::util::UnixSocketAddress::operator==(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::removeConnection(), nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
getPort()
virtual int nidas::util::SocketAddress::getPort () const pure virtual
return the port number of this address, or -1 if there is no associated port number, e.g.
AF_UNIX.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::SocketImpl::bind(), nidas::util::SocketImpl::getLocalPort(), nidas::util::SocketImpl::getRemotePort(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), and nidas::core::DSMServerApp::startStatusThread().
getSockAddrLen()
virtual socklen_t nidas::util::SocketAddress::getSockAddrLen () const pure virtual
Return the length of the struct sockaddr_XX for this address family.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::SocketImpl::bind(), nidas::util::SocketImpl::connect(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::SocketImpl::recvfrom(), and nidas::util::SocketImpl::sendto().
getSockAddrPtr()
virtual struct sockaddr* nidas::util::SocketAddress::getSockAddrPtr () pure virtual
Provide non-const pointer to struct sockaddr_in.
This is needed for recvfrom methods. recvfrom updates the struct sockaddr, so we can't cache the other portions of the address.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::DatagramPacketBase::getSockAddrPtr(), and nidas::util::SocketImpl::recvfrom().
toAddressString()
virtual std::string nidas::util::SocketAddress::toAddressString () const pure virtual
Java style toString, but no DNS lookup.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::SocketImpl::accept(), nidas::util::SocketImpl::bind(), nidas::core::Socket::connect(), nidas::util::SocketImpl::connect(), nidas::util::SocketImpl::getBroadcastEnable(), nidas::util::SocketImpl::getInQueueSize(), nidas::util::SocketImpl::getInterface(), nidas::util::SocketImpl::getKeepAlive(), nidas::util::SocketImpl::getKeepAliveIdleSecs(), nidas::util::SocketImpl::getMulticastLoop(), nidas::core::RemoteSerialListener::getName(), nidas::util::SocketImpl::getOutQueueSize(), nidas::util::SocketImpl::getReceiveBufferSize(), nidas::util::SocketImpl::getSendBufferSize(), nidas::util::SocketImpl::getTcpNoDelay(), nidas::util::SocketImpl::getTimeToLive(), nidas::core::MultipleUDPSockets::handleChangedSockets(), nidas::util::SocketImpl::isNonBlocking(), nidas::util::SocketImpl::listen(), nidas::util::SocketImpl::receive(), nidas::util::SocketImpl::recv(), nidas::util::SocketImpl::recvfrom(), nidas::core::RemoteSerialConnection::RemoteSerialConnection(), nidas::core::DerivedDataReader::run(), nidas::core::ServerSocket::ConnectionThread::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::util::McSocketListener::run(), nidas::util::SocketImpl::send(), nidas::util::SocketImpl::sendall(), nidas::util::SocketImpl::sendto(), nidas::util::SocketImpl::setBroadcastEnable(), nidas::util::SocketImpl::setInterface(), nidas::util::SocketImpl::setKeepAlive(), nidas::util::SocketImpl::setKeepAliveIdleSecs(), nidas::util::SocketImpl::setMulticastLoop(), nidas::util::SocketImpl::setNonBlocking(), nidas::util::SocketImpl::setPktInfo(), nidas::util::SocketImpl::setReceiveBufferSize(), nidas::util::SocketImpl::setSendBufferSize(), nidas::core::RemoteSerialConnection::setSensor(), nidas::util::SocketImpl::setTcpNoDelay(), and nidas::util::SocketImpl::setTimeToLive().
toString()
virtual std::string nidas::util::SocketAddress::toString () const pure virtual
Java style toString.
Implemented in nidas::util::UnixSocketAddress, and nidas::util::Inet4SocketAddress.
Referenced by nidas::util::ServerSocket::close(), nidas::util::SocketImpl::getLocalAddr(), nidas::util::SocketImpl::getRemoteAddr(), PacketReader::logBadPacket(), PacketReader::loop(), main(), WriterThread::run(), ServerThread::run(), RemoteSerial::run(), StatsProcess::run(), nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
The documentation for this class was generated from the following file:
nidas/util/SocketAddress.h