nidas: nidas::core::RemoteSerialListener Class Reference
nidas::core::RemoteSerialListener Class Reference
#include <RemoteSerialListener.h>
Public Member Functions
RemoteSerialListener (unsigned short port, SensorHandler *)
Open a ServerSocket for listening on a given port.
~RemoteSerialListener ()
bool handlePollEvents (uint32_t events) throw ()
void close ()
int getFd () const
const std::string getName () const
Private Member Functions
RemoteSerialListener (const RemoteSerialListener &)
RemoteSerialListener & operator= (const RemoteSerialListener &)
Private Attributes
nidas::util::ServerSocket _socket
SensorHandler * _handler
Constructor & Destructor Documentation
RemoteSerialListener() [1/2]
RemoteSerialListener::RemoteSerialListener (unsigned short port, SensorHandler * handler)
Open a ServerSocket for listening on a given port.
Exceptions
nidas::util::IOException
References _handler, _socket, nidas::core::SensorHandler::getEpollFd(), and nidas::util::ServerSocket::getFd().
~RemoteSerialListener()
RemoteSerialListener::~RemoteSerialListener ()
References close(), PLOG, and nidas::util::Exception::what().
RemoteSerialListener() [2/2]
nidas::core::RemoteSerialListener::RemoteSerialListener (const RemoteSerialListener &) private
Member Function Documentation
close()
void RemoteSerialListener::close ()
Exceptions
nidas::util::IOException
References _handler, _socket, nidas::util::ServerSocket::close(), nidas::core::SensorHandler::getEpollFd(), and nidas::util::ServerSocket::getFd().
Referenced by nidas::core::SensorHandler::run(), and ~RemoteSerialListener().
getFd()
int nidas::core::RemoteSerialListener::getFd () const inline virtual
Implements nidas::core::Polled.
References _socket, and nidas::util::ServerSocket::getFd().
Referenced by nidas::core::SensorHandler::handlePollingChange().
getName()
const std::string nidas::core::RemoteSerialListener::getName () const inline
References _socket, nidas::util::ServerSocket::getLocalSocketAddress(), and nidas::util::SocketAddress::toAddressString().
handlePollEvents()
bool RemoteSerialListener::handlePollEvents (uint32_t events) throw () virtual
Returns
: true: read consumed all available data, false otherwise. This return value is required for edge-triggered polling with epoll, since a read event won't be re-triggered on a file descriptor until all available data is read.
Implements nidas::core::Polled.
References N_POLLERR, N_POLLHUP, N_POLLIN, N_POLLRDHUP, PLOG, and nidas::util::Exception::what().
operator=()
RemoteSerialListener& nidas::core::RemoteSerialListener::operator= (const RemoteSerialListener &) private
Member Data Documentation
_handler
SensorHandler* nidas::core::RemoteSerialListener::_handler private
Referenced by close(), and RemoteSerialListener().
_socket
nidas::util::ServerSocket nidas::core::RemoteSerialListener::_socket private
Referenced by close(), getFd(), getName(), and RemoteSerialListener().
The documentation for this class was generated from the following files:
nidas/core/RemoteSerialListener.h
nidas/core/RemoteSerialListener.cc