nidas: nidas::util::DatagramPacketT< DataT > Class Template Reference
nidas::util::DatagramPacketT< DataT > Class Template Reference
A DatagramPacket with a specific structure of data.
#include <DatagramPacket.h>
Public Member Functions
DatagramPacketT (DataT *buf, int n)
Create a datagram packet from a pointer to some data.
DatagramPacketT (DataT *buf, int n, const Inet4Address &add, int port)
Create a DatagramPacket for sending.
DatagramPacketT (DataT *buf, int n, const SocketAddress &add)
DatagramPacketT (const DatagramPacketT &x)
Copy constructor.
DatagramPacketT & operator= (const DatagramPacketT &rhs)
Assignment operator.
virtual void * getDataVoidPtr ()
Get the pointer to the data portion of the packet.
virtual const void * getConstDataVoidPtr () const
DataT * getData ()
void setData (DataT *val)
Set the pointer to the data portion of the packet.
SocketAddress & getSocketAddress () const
void setSocketAddress (const SocketAddress &val)
struct sockaddr * getSockAddrPtr ()
const struct sockaddr * getConstSockAddrPtr () const
int getSockAddrLen () const
virtual void setLength (int val)
Set the value for the current number of bytes in data.
virtual int getLength () const
Get the value for the current number of bytes in data.
void setMaxLength (int val)
Set the allocated length in bytes of the data.
int getMaxLength () const
Return the allocated length in bytes of the data.
Protected Attributes
DataT * data
int maxlength
allocated length in bytes of contents.
int length
length of datagram that was read or will be sent.
SocketAddress * addr
The destination address for a send, or the remote senders address after a receive.
Detailed Description
template<class DataT>
class nidas::util::DatagramPacketT< DataT >
A DatagramPacket with a specific structure of data.
DatagramPacketT doesn not own the pointer to the data.
This class provides (default) copy constructors and assignment operators. The data pointer of the new copies will point to the same data as the original. The user is responsible for making sure that pointer is valid and the space deallocated when finished.
Constructor & Destructor Documentation
DatagramPacketT() [1/4]
template<class DataT > nidas::util::DatagramPacketT< DataT >::DatagramPacketT (DataT * buf, int n) inline
Create a datagram packet from a pointer to some data.
The DatagramPacketT does not own the pointer to the data, and does not delete it in its destructor.
DatagramPacketT() [2/4]
template<class DataT > nidas::util::DatagramPacketT< DataT >::DatagramPacketT (DataT * buf, int n, const Inet4Address & add, int port) inline
Create a DatagramPacket for sending.
Parameters
buf pointer to allocated space for contents. Pointer is owned by caller, not by the DatagramPacket. The DatagramPacket destructor does not delete it in its destructor.
n number of buffers of type DataT in the packet. @add Inet4Address to send packet to. @port port number to send packet to.
DatagramPacketT() [3/4]
template<class DataT > nidas::util::DatagramPacketT< DataT >::DatagramPacketT (DataT * buf, int n, const SocketAddress & add) inline
DatagramPacketT() [4/4]
template<class DataT > nidas::util::DatagramPacketT< DataT >::DatagramPacketT (const DatagramPacketT< DataT > & x) inline
Copy constructor.
The data pointer of the new copy points to the same data as the original. The user is responsible for making sure the pointer is valid and the space deallocated when finished.
Member Function Documentation
getConstDataVoidPtr()
template<class DataT > virtual const void* nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr () const inline virtual
Implements nidas::util::DatagramPacketBase.
References nidas::util::DatagramPacketT< DataT >::data.
Referenced by PacketReader::checkPacket(), and PacketReader::logBadPacket().
getConstSockAddrPtr()
const struct sockaddr* nidas::util::DatagramPacketBase::getConstSockAddrPtr () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getConstSockAddrPtr().
Referenced by nidas::util::SocketImpl::send().
getData()
template<class DataT > DataT* nidas::util::DatagramPacketT< DataT >::getData () inline
References nidas::util::DatagramPacketT< DataT >::data.
Referenced by WriterThread::run(), and PacketReader::~PacketReader().
getDataVoidPtr()
template<class DataT > virtual void* nidas::util::DatagramPacketT< DataT >::getDataVoidPtr () inline virtual
Get the pointer to the data portion of the packet.
Implements nidas::util::DatagramPacketBase.
References nidas::util::DatagramPacketT< DataT >::data.
getLength()
virtual int nidas::util::DatagramPacketBase::getLength () const inline virtual inherited
Get the value for the current number of bytes in data.
Either the number of bytes read in a received packet, or the number of bytes to send().
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket(), PacketReader::logBadPacket(), PacketReader::loop(), WriterThread::run(), nidas::core::DerivedDataReader::run(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
getMaxLength()
int nidas::util::DatagramPacketBase::getMaxLength () const inline inherited
Return the allocated length in bytes of the data.
References nidas::util::DatagramPacketBase::maxlength.
Referenced by PacketReader::loop(), and nidas::util::SocketImpl::receive().
getSockAddrLen()
int nidas::util::DatagramPacketBase::getSockAddrLen () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrLen().
Referenced by nidas::util::SocketImpl::receive(), and nidas::util::SocketImpl::send().
getSockAddrPtr()
struct sockaddr* nidas::util::DatagramPacketBase::getSockAddrPtr () inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrPtr().
Referenced by nidas::util::SocketImpl::receive().
getSocketAddress()
SocketAddress& nidas::util::DatagramPacketBase::getSocketAddress () const inline inherited
References nidas::util::DatagramPacketBase::addr.
Referenced by PacketReader::logBadPacket(), PacketReader::loop(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
operator=()
template<class DataT > DatagramPacketT& nidas::util::DatagramPacketT< DataT >::operator= (const DatagramPacketT< DataT > & rhs) inline
Assignment operator.
The data pointer of the new copy points to the same data as the right hand side. The user is responsible for making sure old pointer is freed and the new pointer is valid and the space deallocated when finished.
References nidas::util::DatagramPacketT< DataT >::data.
setData()
template<class DataT > void nidas::util::DatagramPacketT< DataT >::setData (DataT * val) inline
Set the pointer to the data portion of the packet.
/param val Pointer to an allocated section of memory. This pointer is owned by the caller, it is not deleted by the DatagramPacket destructor.
References nidas::util::DatagramPacketT< DataT >::data.
setLength()
virtual void nidas::util::DatagramPacketBase::setLength (int val) inline virtual inherited
Set the value for the current number of bytes in data.
/param val Number of bytes, must be <= max length.
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket(), and nidas::util::SocketImpl::receive().
setMaxLength()
void nidas::util::DatagramPacketBase::setMaxLength (int val) inline inherited
Set the allocated length in bytes of the data.
/param val Number of bytes allocated in data.
References nidas::util::DatagramPacketBase::maxlength.
setSocketAddress()
void nidas::util::DatagramPacketBase::setSocketAddress (const SocketAddress & val) inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::clone().
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
Member Data Documentation
addr
SocketAddress* nidas::util::DatagramPacketBase::addr protected inherited
The destination address for a send, or the remote senders address after a receive.
Referenced by nidas::util::DatagramPacketBase::getConstSockAddrPtr(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSockAddrPtr(), nidas::util::DatagramPacketBase::getSocketAddress(), nidas::util::DatagramPacketBase::operator=(), nidas::util::DatagramPacketBase::setSocketAddress(), and nidas::util::DatagramPacketBase::~DatagramPacketBase().
data
template<class DataT > DataT* nidas::util::DatagramPacketT< DataT >::data protected
Referenced by nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr(), nidas::util::DatagramPacketT< DataT >::getData(), nidas::util::DatagramPacketT< DataT >::getDataVoidPtr(), nidas::util::DatagramPacketT< DataT >::operator=(), and nidas::util::DatagramPacketT< DataT >::setData().
length
int nidas::util::DatagramPacketBase::length protected inherited
length of datagram that was read or will be sent.
Must be <= maxlength.
Referenced by nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setLength().
maxlength
int nidas::util::DatagramPacketBase::maxlength protected inherited
allocated length in bytes of contents.
Referenced by nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setMaxLength().
The documentation for this class was generated from the following file:
nidas/util/DatagramPacket.h