nidas: nidas::dynld::isff::SE_GOESXmtr Class Reference
nidas::dynld::isff::SE_GOESXmtr Class Reference abstract
An IOChannel implementation for a Signal Engineering GOES transmitter.
#include <SE_GOESXmtr.h>
Classes
struct SE_Codes
struct selfTest
Public Member Functions
SE_GOESXmtr ()
Constructor.
SE_GOESXmtr (const SE_GOESXmtr &)
Copy constructor.
~SE_GOESXmtr ()
Destructor.
SE_GOESXmtr * clone () const
Clone invokes default copy constructor.
void setRFBaud (long val) throw (nidas::util::InvalidParameterException)
Set the RF baud rate.
int getRFBaud () const
void init () throw (nidas::util::IOException)
Initialize tranmitter.
int getModel () const
Return the model number of the transmitter.
void setModel (int val)
int getMaxRFBaud () const
Get the maximum RF baud rate supported by the transmitter.
virtual bool isNewFile () const
void transmitData (const nidas::util::UTime &sendTime, int configid, const Sample *) throw (nidas::util::IOException)
Queue a sample for writing to a GOES transmitter.
void transmitDataSE110 (const nidas::util::UTime &sendTime, int configid, const Sample *) throw (nidas::util::IOException)
Queue a sample for writing to a GOES transmitter.
void transmitDataSE120 (const nidas::util::UTime &sendTime, int configid, const Sample *) throw (nidas::util::IOException)
void close () throw (nidas::util::IOException)
size_t send (const std::string &msg) throw (nidas::util::IOException)
Sent a message to the GOES transmitter.
size_t send (char c) throw (nidas::util::IOException)
A one-byte message, containing only the type.
std::string recv () throw (nidas::util::IOException)
Receive a message from the transmitter.
void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
void encodeClock (const nidas::util::UTime &ut, char *out, bool fractsecs)
nidas::util::UTime decodeClock (const char *in)
void wakeup () throw (nidas::util::IOException)
Raise RTS to wake up transmitter.
void tosleep () throw (nidas::util::IOException)
Lower RTS to put transmitter to sleep.
void query () throw (nidas::util::IOException)
Query the GOES Transmitter.
int detectModel () throw (nidas::util::IOException)
bool testTransmitSE120 () throw (nidas::util::IOException)
void cancelTransmit (const nidas::util::UTime &at) throw (nidas::util::IOException)
int checkStatus () throw (nidas::util::IOException)
Queries the transmitter for status information.
void printStatus () throw ()
Request that transmitter status be printed to an output stream.
void printStatus (std::ostream &) throw ()
void setXmtrId () throw (nidas::util::IOException)
unsigned long getXmtrId () throw (nidas::util::IOException)
void setXmtrClock () throw (nidas::util::IOException)
nidas::util::UTime getXmtrClock () throw (nidas::util::IOException)
int getXmtrClockDelay (int nchar) const
Get the transmission delay of the transmitter clock.
unsigned long checkId () throw (nidas::util::IOException)
int checkClock () throw (nidas::util::IOException)
Check transmitter clock, and correct it if necessary.
void transmitDataSE110 () throw (nidas::util::IOException)
void reset () throw (nidas::util::IOException)
void doSelfTest () throw (nidas::util::IOException)
int getSelfTestResults () throw (nidas::util::IOException)
Fetch self test results.
void checkResponse (char ptype, const std::string &resp) throw (nidas::util::IOException)
Check response string.
void checkACKResponse (char ptype, const std::string &resp, char seqnum) throw (nidas::util::IOException)
Check response to SE110 Transmit Data packet.
void getBatteryVoltages (float &current, float &before, float &during) throw (nidas::util::IOException)
Send Get Status command to SE model 1200 to query the battery voltates.
std::string getSelfTestStatusString ()
const std::string & getName () const
void setName (const std::string &val)
void setId (unsigned long val)
unsigned long getId () const
void setChannel (int val)
int getChannel () const
void setXmitInterval (long val)
Set the transmission interval.
int getXmitInterval () const
void setXmitOffset (long val)
Set the transmission offset.
int getXmitOffset () const
void requestConnection (IOChannelRequester *rqstr) throw (nidas::util::IOException)
Request a connection.
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
void setNonBlocking (bool val __attribute__((unused))) throw (nidas::util::IOException)
virtual void setNonBlocking (bool val)=0
bool isNonBlocking () const throw (nidas::util::IOException)
virtual void open () throw (nidas::util::IOException)
int getFd () const
void setStatusFile (const std::string &val)
const std::string & getStatusFile () const
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static std::string fix (const std::string &msg)
Fix a string for transmission to a SE GOES transmitter.
static std::string unfix (const std::string &msg)
Unfix a string that was read from a SE GOES transmitter, looking for.
static char crc (const std::string &msg)
Compute a CRC for the message.
static std::string codeString (char pktType)
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Static Public Attributes
static const char SOH = '\x1'
Byte at beginning of each message sent to or received from transmitter.
static const char EOT = '\x4'
Byte at end of each message sent to or received from transmitter.
static const std::string SOH_STR = string(1,SOH)
static const char PKT_GET_ID = '\x10'
Get the transmitter's id.
static const char PKT_SET_ID = '\x11'
Sets Transmitter id in either ram or eeprom.
static const char PKT_SET_TIME = '\x13'
Load Transmitter time-of-day.
static const char PKT_GET_TIME = '\x14'
Get Transmitter time-of-day.
static const char PKT_XMT_DATA = '\x15'
Transmit data, SE110 only.
static const char PKT_CANCEL_XMT = '\x16'
Cancel transmission.
static const char PKT_GET_XMT_QUE = '\x17'
static const char PKT_QUERY = '\x18'
static const char PKT_SET_GLOBALS = '\x1b'
SE110.
static const char PKT_GET_GLOBALS = '\x1c'
SE110.
static const char PKT_DISPLAY_VERSION = '\x1d'
Display version information, SE120, SE1200.
static const char PKT_XMT_DATA_SE120 = '\x1e'
Transmit, SE120, SE1200.
static const char PKT_POLL_ENABLE = 0x38
static const char PKT_POLL_DATA_GET = 0x39
static const char PKT_POLL_DATA_SET = 0x3a
static const char PKT_GET_SE1200_STATUS = '\x74'
SE1200 Only, grabs status info.
static const char PKT_RESET_XMTR = '\x76'
static const char PKT_SELFTEST_DISPL = '\x77'
static const char PKT_SELFTEST_START = '\x78'
static const char PKT_SEND_FIXED_CHAN = '\x7a'
static const char PKT_SOFTWARE_LOAD = '\x7c'
SE120, SE1200.
static const char PKT_ACKNOWLEDGE = '\x80'
static const char PKT_ERR_RESPONSE = '\xf0'
Xmtr detected an error in msg it rcvd.
static struct SE_Codes cmdCodes []
static const char PKT_STATUS_OK = 0
static const char PKT_STATUS_ILLEGAL_REQUEST = 0x01
static const char PKT_STATUS_ITEM_NOT_FOUND = 0x03
static const char PKT_STATUS_INVALID_DATE_TIME = 0x04
static const char PKT_STATUS_TRANSMIT_OVERLAP = 0x05
static const char PKT_STATUS_INVALID_CHANNEL = 0x06
static const char PKT_STATUS_INVALID_TRANSMIT_INTERVAL = 0x07
static const char PKT_STATUS_EEPROM_NOT_UPDATED = 0x08
static const char PKT_STATUS_INVALID_REPEAT_COUNT = 0x09
static const char PKT_STATUS_CLOCK_NOT_LOADED = 0x0a
static const char PKT_STATUS_CRC_ERROR_ON_LOAD = 0x0b
static const char * statusCodeStrings []
static const char ERR_TOOLONG = 0x01
static const char ERR_TOOSHORT = 0x02
static const char ERR_CRC = 0x03
static const char ERR_BADTYPE = 0x04
static const char ERR_BADLEN = 0x05
static const char ERR_MEMORY = 0x06
static const char ERR_SEQUENCE = 0x07
static const char ERR_TIMEOUT = 0x08
static const char * errorCodeStrings []
static struct nidas::dynld::isff::SE_GOESXmtr::selfTest selfTestCodes [2][10]
Protected Attributes
nidas::util::SerialPort _port
Private Member Functions
size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Read a message, up to the EOT, from the serial port.
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Write a message to the serial port.
size_t write (const struct iovec *iov, int iovcnt) throw (nidas::util::IOException)
Physical write method which must be implemented in derived classes.
SE_GOESXmtr & operator= (const SE_GOESXmtr &)
No assignment.
Private Attributes
int _model
int _clockDiffMsecs
Most recent value for GOES clock difference: GOES clock - system clock.
nidas::util::UTime _transmitQueueTime
nidas::util::UTime _transmitAtTime
nidas::util::UTime _transmitSampleTime
std::string _lastXmitStatus
std::string _softwareBuildDate
short _selfTestStatus
int _maxRFBaud
bool _gpsInstalled
size_t _xmitNbytes
unsigned long _activeId
Actual id read from transmitter.
int _rfBaud
unsigned long _id
int _channel
int _xmitInterval
int _xmitOffset
std::string _statusFile
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static const nidas::util::EndianConverter * _fromBig
static XMLCh * namespaceURI = 0
Detailed Description
An IOChannel implementation for a Signal Engineering GOES transmitter.
Constructor & Destructor Documentation
SE_GOESXmtr() [1/2]
SE_GOESXmtr::SE_GOESXmtr ()
Constructor.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::Termios::NOFLOWCONTROL, nidas::util::Termios::NONE, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setFlowControl(), nidas::util::Termios::setLocal(), nidas::util::Termios::setParity(), nidas::util::Termios::setRaw(), nidas::util::Termios::setRawLength(), nidas::util::Termios::setRawTimeout(), nidas::util::Termios::setStopBits(), and nidas::util::SerialPort::termios().
SE_GOESXmtr() [2/2]
SE_GOESXmtr::SE_GOESXmtr (const SE_GOESXmtr & x)
Copy constructor.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::Termios::NOFLOWCONTROL, nidas::util::Termios::NONE, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setFlowControl(), nidas::util::Termios::setLocal(), nidas::util::Termios::setParity(), nidas::util::Termios::setRaw(), nidas::util::Termios::setRawLength(), nidas::util::Termios::setRawTimeout(), nidas::util::Termios::setStopBits(), and nidas::util::SerialPort::termios().
~SE_GOESXmtr()
SE_GOESXmtr::~SE_GOESXmtr ()
Destructor.
Member Function Documentation
cancelTransmit()
void SE_GOESXmtr::cancelTransmit (const nidas::util::UTime & at) throw (nidas::util::IOException)
References nidas::dynld::isff::GOESException::getStatus(), PLOG, and nidas::util::Exception::what().
Referenced by testTransmitSE120().
checkACKResponse()
void SE_GOESXmtr::checkACKResponse (char ptype, const std::string & resp, char seqnum) throw (nidas::util::IOException)
Check response to SE110 Transmit Data packet.
If status is not OK, put the transmitter toSleep(), and throw IOException. toSleep() is not done if an exception is not thrown.
checkClock()
int SE_GOESXmtr::checkClock () throw (nidas::util::IOException) virtual
Check transmitter clock, and correct it if necessary.
Returns
transmitter clock minus system clock, in milliseconds.
Implements nidas::dynld::isff::GOESXmtr.
References _clockDiffMsecs, _gpsInstalled, nidas::dynld::isff::GOESXmtr::getName(), nidas::dynld::isff::GOESException::getStatus(), getXmtrClock(), getXmtrClockDelay(), PKT_STATUS_CLOCK_NOT_LOADED, setXmtrClock(), USECS_PER_MSEC, USECS_PER_SEC, and WLOG.
Referenced by detectModel(), and init().
checkId()
unsigned long SE_GOESXmtr::checkId () throw (nidas::util::IOException) virtual
Implements nidas::dynld::isff::GOESXmtr.
References _activeId, nidas::dynld::isff::GOESXmtr::getId(), nidas::dynld::isff::GOESXmtr::getName(), getXmtrId(), setXmtrId(), and WLOG.
checkResponse()
void SE_GOESXmtr::checkResponse (char ptype, const std::string & resp) throw (nidas::util::IOException)
Check response string.
If status is not OK, put the transmitter toSleep(), and throw IOException. toSleep() is not done if an exception is not thrown.
Referenced by checkStatus(), doSelfTest(), getSelfTestResults(), getXmtrClock(), getXmtrId(), query(), reset(), setXmtrClock(), setXmtrId(), and testTransmitSE120().
checkStatus()
int SE_GOESXmtr::checkStatus () throw (nidas::util::IOException)
Queries the transmitter for status information.
Returns a preliminary guess at the model number, which may be wrong. Use detectModel() for a more complete check of the model number.
References _softwareBuildDate, checkResponse(), ERR_BADTYPE, nidas::dynld::isff::GOESXmtr::getName(), getSelfTestResults(), nidas::dynld::isff::GOESException::getStatus(), ILOG, PKT_DISPLAY_VERSION, recv(), send(), and wakeup().
Referenced by detectModel().
clone()
SE_GOESXmtr* nidas::dynld::isff::SE_GOESXmtr::clone () const inline virtual
Clone invokes default copy constructor.
Implements nidas::core::IOChannel.
close()
void nidas::dynld::isff::SE_GOESXmtr::close () throw (nidas::util::IOException) inline virtual
Exceptions
nidas::util::IOException
Reimplemented from nidas::dynld::isff::GOESXmtr.
codeString()
string SE_GOESXmtr::codeString (char pktType) static
connect()
IOChannel * GOESXmtr::connect () throw (nidas::util::IOException) virtual inherited
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Exceptions
nidas::util::IOException
nidas::util::UnknownHostException
Implements nidas::core::IOChannel.
References nidas::dynld::isff::GOESXmtr::open().
crc()
char SE_GOESXmtr::crc (const std::string & msg) static
Compute a CRC for the message.
Referenced by recv().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
decodeClock()
n_u::UTime SE_GOESXmtr::decodeClock (const char * in)
References nidas::util::UTime::format(), getModel(), nidas::dynld::isff::GOESXmtr::getName(), ILOG, USECS_PER_MSEC, and WLOG.
Referenced by getXmtrClock().
detectModel()
int SE_GOESXmtr::detectModel () throw (nidas::util::IOException)
References checkClock(), checkStatus(), getMaxRFBaud(), nidas::dynld::isff::GOESXmtr::getName(), getRFBaud(), ILOG, setModel(), setRFBaud(), testTransmitSE120(), and nidas::util::Exception::toString().
Referenced by init().
doSelfTest()
void SE_GOESXmtr::doSelfTest () throw (nidas::util::IOException)
References checkResponse(), nidas::dynld::isff::GOESXmtr::getName(), ILOG, PKT_SELFTEST_START, recv(), send(), setModel(), tosleep(), and wakeup().
Referenced by main().
encodeClock()
void SE_GOESXmtr::encodeClock (const nidas::util::UTime & ut, char * out, bool fractsecs)
References getModel(), nidas::util::UTime::toTm(), and USECS_PER_SEC.
Referenced by setXmtrClock(), and testTransmitSE120().
fix()
string SE_GOESXmtr::fix (const std::string & msg) static
Fix a string for transmission to a SE GOES transmitter.
SOH character is changed to "#" followed by ~SOH (one's complement) EOT character is changed to "#" followed by ~EOT (one's complement)
character is changed to "#" followed by ~# (one's complement)
flush()
void nidas::dynld::isff::SE_GOESXmtr::flush () throw (nidas::util::IOException) inline virtual
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented from nidas::dynld::isff::GOESXmtr.
fromDOMElement()
void GOESXmtr::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Termios::EVEN, nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), nidas::util::Termios::NONE, nidas::util::Termios::ODD, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setParity(), and nidas::util::Termios::setStopBits().
getBatteryVoltages()
void SE_GOESXmtr::getBatteryVoltages (float & current, float & before, float & during) throw (nidas::util::IOException)
Send Get Status command to SE model 1200 to query the battery voltates.
Parameters
current battery voltage, voltage before last transmission, voltage during last transmission.
References nidas::core::floatNAN.
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getChannel()
int nidas::dynld::isff::GOESXmtr::getChannel () const inline inherited
Referenced by nidas::dynld::isff::SimGOESXmtr::printStatus(), and testTransmitSE120().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::dynld::isff::GOESXmtr::getFd () const inline virtual inherited
Implements nidas::core::IOChannel.
getId()
unsigned long nidas::dynld::isff::GOESXmtr::getId () const inline inherited
Referenced by checkId(), and setXmtrId().
getMaxRFBaud()
int nidas::dynld::isff::SE_GOESXmtr::getMaxRFBaud () const inline
Get the maximum RF baud rate supported by the transmitter.
This value is set by the checkStatus() method, which is called by detectModel(), init(), and transmitData().
Referenced by detectModel().
getModel()
int nidas::dynld::isff::SE_GOESXmtr::getModel () const inline
Return the model number of the transmitter.
Returns
: 0=unknown, 100, 110, 120, or 1200.
Referenced by decodeClock(), encodeClock(), and getSelfTestStatusString().
getName()
const std::string& nidas::dynld::isff::GOESXmtr::getName () const inline virtual inherited
Implements nidas::core::IOChannel.
Referenced by checkClock(), checkId(), checkStatus(), decodeClock(), detectModel(), doSelfTest(), getSelfTestResults(), recv(), reset(), testTransmitSE120(), tosleep(), and wakeup().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getRFBaud()
int nidas::dynld::isff::SE_GOESXmtr::getRFBaud () const inline virtual
Implements nidas::dynld::isff::GOESXmtr.
Referenced by detectModel().
getSelfTestResults()
int SE_GOESXmtr::getSelfTestResults () throw (nidas::util::IOException)
Fetch self test results.
Returns
model number. This model number may be incorrect, because a model 110 will be reported as a 120. One must do a test transmission to determine that it is actually a 110.
References _gpsInstalled, _maxRFBaud, _selfTestStatus, checkResponse(), nidas::dynld::isff::GOESXmtr::getName(), PKT_SELFTEST_DISPL, recv(), send(), tosleep(), and WLOG.
Referenced by checkStatus().
getSelfTestStatusString()
string SE_GOESXmtr::getSelfTestStatusString ()
References _gpsInstalled, _selfTestStatus, getModel(), selfTestCodes, and nidas::dynld::isff::SE_GOESXmtr::selfTest::text.
getStatusFile()
const std::string& nidas::dynld::isff::GOESXmtr::getStatusFile () const inline inherited
Referenced by printStatus().
getXmitInterval()
int nidas::dynld::isff::GOESXmtr::getXmitInterval () const inline inherited
Referenced by nidas::dynld::isff::GOESOutput::getXmitInterval(), nidas::dynld::isff::SimGOESXmtr::printStatus(), and testTransmitSE120().
getXmitOffset()
int nidas::dynld::isff::GOESXmtr::getXmitOffset () const inline inherited
Referenced by nidas::dynld::isff::GOESOutput::getXmitOffset(), nidas::dynld::isff::SimGOESXmtr::printStatus(), and testTransmitSE120().
getXmtrClock()
n_u::UTime SE_GOESXmtr::getXmtrClock () throw (nidas::util::IOException)
References checkResponse(), decodeClock(), PKT_GET_TIME, recv(), send(), tosleep(), and wakeup().
Referenced by checkClock().
getXmtrClockDelay()
int SE_GOESXmtr::getXmtrClockDelay (int nchar) const
Get the transmission delay of the transmitter clock.
Parameters
nchar Number of characters sent to set the clock, or number of characters received when getting the clock.
Returns
The number of microseconds that the receipt of a transmitter clock value was delayed due to serial transmission. This value is typically 14 * 10 * 10^6 / 9600 = 14583. The clock packet is 14 bytes long, assume 10 transmitted bits per byte, at 9600 baud.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::Termios::getBaudRate(), nidas::util::SerialPort::getTermios(), and USECS_PER_SEC.
Referenced by checkClock(), and setXmtrClock().
getXmtrId()
unsigned long SE_GOESXmtr::getXmtrId () throw (nidas::util::IOException)
References _activeId, checkResponse(), PKT_GET_ID, recv(), send(), tosleep(), and wakeup().
Referenced by checkId().
init()
void SE_GOESXmtr::init () throw (nidas::util::IOException) virtual
Initialize tranmitter.
Implements nidas::dynld::isff::GOESXmtr.
References _lastXmitStatus, checkClock(), detectModel(), query(), setXmtrId(), and nidas::util::Exception::what().
Referenced by main().
isNewFile()
virtual bool nidas::dynld::isff::SE_GOESXmtr::isNewFile () const inline virtual
isNewInput()
virtual bool nidas::core::IOChannel::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented in nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::core::IOStream::read(), and nidas::core::IOStream::readUntil().
isNonBlocking()
bool nidas::dynld::isff::GOESXmtr::isNonBlocking () const throw (nidas::util::IOException) inline virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
open()
void GOESXmtr::open () throw (nidas::util::IOException) virtual inherited
Reimplemented in nidas::dynld::isff::SimGOESXmtr.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::SerialPort::flushBoth(), and nidas::util::SerialPort::open().
Referenced by nidas::dynld::isff::GOESXmtr::connect(), and main().
operator=()
SE_GOESXmtr& nidas::dynld::isff::SE_GOESXmtr::operator= (const SE_GOESXmtr &) private
No assignment.
printStatus() [1/2]
void SE_GOESXmtr::printStatus () throw () virtual
Request that transmitter status be printed to an output stream.
Implements nidas::dynld::isff::GOESXmtr.
References nidas::dynld::isff::GOESXmtr::getStatusFile(), and PLOG.
Referenced by main().
printStatus() [2/2]
void SE_GOESXmtr::printStatus (std::ostream & ost) throw ()
References nidas::util::Exception::what(), and WLOG.
query()
void SE_GOESXmtr::query () throw (nidas::util::IOException)
Query the GOES Transmitter.
Returns
false: not responding or not ready. true: A-OK.
References checkResponse(), PKT_QUERY, recv(), send(), tosleep(), and wakeup().
Referenced by init().
read()
size_t SE_GOESXmtr::read (void * buf, size_t len) throw (nidas::util::IOException) private virtual
Read a message, up to the EOT, from the serial port.
Implements nidas::core::IOChannel.
References len.
Referenced by recv().
recv()
string SE_GOESXmtr::recv () throw (nidas::util::IOException)
Receive a message from the transmitter.
IOException is thrown if the message does not match specs:
Is not enclosed in SOH,EOT.
the length does not match what was read.
The CRC check fails.
Returns
The unfix'd contents of the message, without the SOH, length, CRC or the EOT.
References crc(), EOT, nidas::dynld::isff::GOESXmtr::getName(), len, read(), SOH, and unfix().
Referenced by checkStatus(), doSelfTest(), getSelfTestResults(), getXmtrClock(), getXmtrId(), query(), reset(), setXmtrClock(), setXmtrId(), and testTransmitSE120().
requestConnection()
void GOESXmtr::requestConnection (IOChannelRequester * rqstr) throw (nidas::util::IOException) virtual inherited
Request a connection.
Implements nidas::core::IOChannel.
reset()
void SE_GOESXmtr::reset () throw (nidas::util::IOException) virtual
Implements nidas::dynld::isff::GOESXmtr.
References checkResponse(), nidas::dynld::isff::GOESXmtr::getName(), ILOG, PKT_RESET_XMTR, PKT_SELFTEST_START, recv(), send(), setModel(), tosleep(), and wakeup().
send() [1/2]
size_t SE_GOESXmtr::send (char c) throw (nidas::util::IOException)
A one-byte message, containing only the type.
send() [2/2]
size_t SE_GOESXmtr::send (const std::string & msg) throw (nidas::util::IOException)
Sent a message to the GOES transmitter.
Parameters
msg The basic message, without the leading SOH, or length, or the trailing CRC or EOT.
References crc.
Referenced by checkStatus(), doSelfTest(), getSelfTestResults(), getXmtrClock(), getXmtrId(), query(), reset(), setXmtrClock(), setXmtrId(), and testTransmitSE120().
setChannel()
void nidas::dynld::isff::GOESXmtr::setChannel (int val) inline inherited
Referenced by main().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setId()
void nidas::dynld::isff::GOESXmtr::setId (unsigned long val) inline inherited
Referenced by main().
setModel()
void nidas::dynld::isff::SE_GOESXmtr::setModel (int val) inline
Referenced by detectModel(), doSelfTest(), and reset().
setName()
void nidas::dynld::isff::GOESXmtr::setName (const std::string & val) inline virtual inherited
Implements nidas::core::IOChannel.
Referenced by main().
setNonBlocking() [1/2]
void nidas::dynld::isff::GOESXmtr::setNonBlocking (bool val __attribute__(unused)) throw (nidas::util::IOException) inline inherited
setNonBlocking() [2/2]
virtual void nidas::core::IOChannel::setNonBlocking (bool val) pure virtual inherited
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setNonBlocking().
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setRFBaud()
void SE_GOESXmtr::setRFBaud (long val) throw (nidas::util::InvalidParameterException) virtual
Set the RF baud rate.
Parameters
val RF baud, in bits/sec.
Implements nidas::dynld::isff::GOESXmtr.
Referenced by detectModel().
setStatusFile()
void nidas::dynld::isff::GOESXmtr::setStatusFile (const std::string & val) inline inherited
setXmitInterval()
void nidas::dynld::isff::GOESXmtr::setXmitInterval (long val) inline inherited
Set the transmission interval.
Parameters
val Interval, in seconds.
setXmitOffset()
void nidas::dynld::isff::GOESXmtr::setXmitOffset (long val) inline inherited
Set the transmission offset.
Parameters
val Offset, in seconds.
setXmtrClock()
void SE_GOESXmtr::setXmtrClock () throw (nidas::util::IOException)
References checkResponse(), encodeClock(), getXmtrClockDelay(), PKT_SET_TIME, recv(), send(), tosleep(), and wakeup().
Referenced by checkClock().
setXmtrId()
void SE_GOESXmtr::setXmtrId () throw (nidas::util::IOException)
References _activeId, checkResponse(), nidas::dynld::isff::GOESXmtr::getId(), PKT_SET_ID, recv(), send(), tosleep(), and wakeup().
Referenced by checkId(), and init().
testTransmitSE120()
bool SE_GOESXmtr::testTransmitSE120 () throw (nidas::util::IOException)
References cancelTransmit(), checkResponse(), encodeClock(), ERR_BADTYPE, nidas::util::UTime::format(), nidas::dynld::isff::GOESXmtr::getChannel(), nidas::dynld::isff::GOESXmtr::getName(), nidas::dynld::isff::GOESException::getStatus(), nidas::dynld::isff::GOESXmtr::getXmitInterval(), nidas::dynld::isff::GOESXmtr::getXmitOffset(), PKT_XMT_DATA_SE120, recv(), send(), tosleep(), nidas::util::UTime::toUsecs(), USECS_PER_SEC, wakeup(), nidas::util::Exception::what(), and WLOG.
Referenced by detectModel().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
tosleep()
void SE_GOESXmtr::tosleep () throw (nidas::util::IOException)
Lower RTS to put transmitter to sleep.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::SerialPort::clearModemBits(), nidas::util::SerialPort::getModemStatus(), nidas::dynld::isff::GOESXmtr::getName(), and NSECS_PER_SEC.
Referenced by doSelfTest(), getSelfTestResults(), getXmtrClock(), getXmtrId(), query(), reset(), setXmtrClock(), setXmtrId(), and testTransmitSE120().
transmitData()
void SE_GOESXmtr::transmitData (const nidas::util::UTime & sendTime, int configid, const Sample * samp) throw (nidas::util::IOException) virtual
Queue a sample for writing to a GOES transmitter.
Implements nidas::dynld::isff::GOESXmtr.
References nidas::dynld::isff::GOESException::getStatus(), PLOG, and nidas::util::Exception::what().
transmitDataSE110() [1/2]
void nidas::dynld::isff::SE_GOESXmtr::transmitDataSE110 () throw (nidas::util::IOException)
transmitDataSE110() [2/2]
void SE_GOESXmtr::transmitDataSE110 (const nidas::util::UTime & sendTime, int configid, const Sample * samp) throw (nidas::util::IOException)
Queue a sample for writing to a GOES transmitter.
References nidas::dynld::isff::GOES::float_encode_4x6(), nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), and nidas::core::SampleT< DataT >::getDataLength().
transmitDataSE120()
void SE_GOESXmtr::transmitDataSE120 (const nidas::util::UTime & sendTime, int configid, const Sample * samp) throw (nidas::util::IOException)
References nidas::dynld::isff::GOES::float_encode_4x6(), nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), and nidas::core::SampleT< DataT >::getDataLength().
unfix()
string SE_GOESXmtr::unfix (const std::string & msg) static
Unfix a string that was read from a SE GOES transmitter, looking for.
'#c'
where c is any character, and replacing the two characters with the one's complement of c.
Referenced by recv().
wakeup()
void SE_GOESXmtr::wakeup () throw (nidas::util::IOException)
Raise RTS to wake up transmitter.
References nidas::dynld::isff::GOESXmtr::_port, nidas::util::SerialPort::clearModemBits(), nidas::util::SerialPort::getModemStatus(), nidas::dynld::isff::GOESXmtr::getName(), NSECS_PER_SEC, and nidas::util::SerialPort::setModemBits().
Referenced by checkStatus(), doSelfTest(), getXmtrClock(), getXmtrId(), query(), reset(), setXmtrClock(), setXmtrId(), and testTransmitSE120().
write() [1/2]
size_t SE_GOESXmtr::write (const struct iovec * iov, int iovcnt) throw (nidas::util::IOException) private virtual
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
write() [2/2]
size_t SE_GOESXmtr::write (const void * buf, size_t len) throw (nidas::util::IOException) private virtual
Write a message to the serial port.
The message must have already been formatted for a SE GOES tranmitter: leading SOH, length, message, CRC, EOT, and the length,message and CRC portion must have been fixed with the fix() method.
Implements nidas::core::IOChannel.
References len.
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_activeId
unsigned long nidas::dynld::isff::SE_GOESXmtr::_activeId private
Actual id read from transmitter.
Referenced by checkId(), getXmtrId(), and setXmtrId().
_channel
int nidas::dynld::isff::GOESXmtr::_channel private inherited
_clockDiffMsecs
int nidas::dynld::isff::SE_GOESXmtr::_clockDiffMsecs private
Most recent value for GOES clock difference: GOES clock - system clock.
Referenced by checkClock().
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_fromBig
const n_u::EndianConverter * SE_GOESXmtr::_fromBig static private
Initial value:
=
        n_u::EndianConverter::getConverter(n_u::EndianConverter::EC_BIG_ENDIAN)
_gpsInstalled
bool nidas::dynld::isff::SE_GOESXmtr::_gpsInstalled private
Referenced by checkClock(), getSelfTestResults(), and getSelfTestStatusString().
_id
unsigned long nidas::dynld::isff::GOESXmtr::_id private inherited
_lastXmitStatus
std::string nidas::dynld::isff::SE_GOESXmtr::_lastXmitStatus private
Referenced by init().
_maxRFBaud
int nidas::dynld::isff::SE_GOESXmtr::_maxRFBaud private
Referenced by getSelfTestResults().
_model
int nidas::dynld::isff::SE_GOESXmtr::_model private
_port
nidas::util::SerialPort nidas::dynld::isff::GOESXmtr::_port protected inherited
Referenced by getXmtrClockDelay(), nidas::dynld::isff::GOESXmtr::open(), nidas::dynld::isff::SimGOESXmtr::printStatus(), SE_GOESXmtr(), tosleep(), and wakeup().
_rfBaud
int nidas::dynld::isff::SE_GOESXmtr::_rfBaud private
_selfTestStatus
short nidas::dynld::isff::SE_GOESXmtr::_selfTestStatus private
Referenced by getSelfTestResults(), and getSelfTestStatusString().
_softwareBuildDate
std::string nidas::dynld::isff::SE_GOESXmtr::_softwareBuildDate private
Referenced by checkStatus().
_statusFile
std::string nidas::dynld::isff::GOESXmtr::_statusFile private inherited
_transmitAtTime
nidas::util::UTime nidas::dynld::isff::SE_GOESXmtr::_transmitAtTime private
_transmitQueueTime
nidas::util::UTime nidas::dynld::isff::SE_GOESXmtr::_transmitQueueTime private
_transmitSampleTime
nidas::util::UTime nidas::dynld::isff::SE_GOESXmtr::_transmitSampleTime private
_xmitInterval
int nidas::dynld::isff::GOESXmtr::_xmitInterval private inherited
_xmitNbytes
size_t nidas::dynld::isff::SE_GOESXmtr::_xmitNbytes private
_xmitOffset
int nidas::dynld::isff::GOESXmtr::_xmitOffset private inherited
cmdCodes
struct SE_Codes nidas::dynld::isff::SE_GOESXmtr::cmdCodes[] static
EOT
const char nidas::dynld::isff::SE_GOESXmtr::EOT = '\x4' static
Byte at end of each message sent to or received from transmitter.
Referenced by recv().
ERR_BADLEN
const char nidas::dynld::isff::SE_GOESXmtr::ERR_BADLEN = 0x05 static
ERR_BADTYPE
const char nidas::dynld::isff::SE_GOESXmtr::ERR_BADTYPE = 0x04 static
Referenced by checkStatus(), and testTransmitSE120().
ERR_CRC
const char nidas::dynld::isff::SE_GOESXmtr::ERR_CRC = 0x03 static
ERR_MEMORY
const char nidas::dynld::isff::SE_GOESXmtr::ERR_MEMORY = 0x06 static
ERR_SEQUENCE
const char nidas::dynld::isff::SE_GOESXmtr::ERR_SEQUENCE = 0x07 static
ERR_TIMEOUT
const char nidas::dynld::isff::SE_GOESXmtr::ERR_TIMEOUT = 0x08 static
ERR_TOOLONG
const char nidas::dynld::isff::SE_GOESXmtr::ERR_TOOLONG = 0x01 static
ERR_TOOSHORT
const char nidas::dynld::isff::SE_GOESXmtr::ERR_TOOSHORT = 0x02 static
errorCodeStrings
const char * SE_GOESXmtr::errorCodeStrings static
Initial value:
= {
    "Packet OK",
    "Received Packet Too Long",
    "Received Packet Too Short",
    "Received Packet Checksum Error",
    "Invalid Type Code",
    "Length Field mismatch",
    "Unable to Allocate Memory",
    "Invalid Sequence Number",
    "Command Timeout for multi-packet Command",
}
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
PKT_ACKNOWLEDGE
const char nidas::dynld::isff::SE_GOESXmtr::PKT_ACKNOWLEDGE = '\x80' static
PKT_CANCEL_XMT
const char nidas::dynld::isff::SE_GOESXmtr::PKT_CANCEL_XMT = '\x16' static
Cancel transmission.
PKT_DISPLAY_VERSION
const char nidas::dynld::isff::SE_GOESXmtr::PKT_DISPLAY_VERSION = '\x1d' static
Display version information, SE120, SE1200.
Referenced by checkStatus().
PKT_ERR_RESPONSE
const char nidas::dynld::isff::SE_GOESXmtr::PKT_ERR_RESPONSE = '\xf0' static
Xmtr detected an error in msg it rcvd.
PKT_GET_GLOBALS
const char nidas::dynld::isff::SE_GOESXmtr::PKT_GET_GLOBALS = '\x1c' static
SE110.
PKT_GET_ID
const char nidas::dynld::isff::SE_GOESXmtr::PKT_GET_ID = '\x10' static
Get the transmitter's id.
Referenced by getXmtrId().
PKT_GET_SE1200_STATUS
const char nidas::dynld::isff::SE_GOESXmtr::PKT_GET_SE1200_STATUS = '\x74' static
SE1200 Only, grabs status info.
PKT_GET_TIME
const char nidas::dynld::isff::SE_GOESXmtr::PKT_GET_TIME = '\x14' static
Get Transmitter time-of-day.
Referenced by getXmtrClock().
PKT_GET_XMT_QUE
const char nidas::dynld::isff::SE_GOESXmtr::PKT_GET_XMT_QUE = '\x17' static
PKT_POLL_DATA_GET
const char nidas::dynld::isff::SE_GOESXmtr::PKT_POLL_DATA_GET = 0x39 static
PKT_POLL_DATA_SET
const char nidas::dynld::isff::SE_GOESXmtr::PKT_POLL_DATA_SET = 0x3a static
PKT_POLL_ENABLE
const char nidas::dynld::isff::SE_GOESXmtr::PKT_POLL_ENABLE = 0x38 static
PKT_QUERY
const char nidas::dynld::isff::SE_GOESXmtr::PKT_QUERY = '\x18' static
Referenced by query().
PKT_RESET_XMTR
const char nidas::dynld::isff::SE_GOESXmtr::PKT_RESET_XMTR = '\x76' static
Referenced by reset().
PKT_SELFTEST_DISPL
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SELFTEST_DISPL = '\x77' static
Referenced by getSelfTestResults().
PKT_SELFTEST_START
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SELFTEST_START = '\x78' static
Referenced by doSelfTest(), and reset().
PKT_SEND_FIXED_CHAN
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SEND_FIXED_CHAN = '\x7a' static
PKT_SET_GLOBALS
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SET_GLOBALS = '\x1b' static
SE110.
PKT_SET_ID
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SET_ID = '\x11' static
Sets Transmitter id in either ram or eeprom.
Referenced by setXmtrId().
PKT_SET_TIME
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SET_TIME = '\x13' static
Load Transmitter time-of-day.
Referenced by setXmtrClock().
PKT_SOFTWARE_LOAD
const char nidas::dynld::isff::SE_GOESXmtr::PKT_SOFTWARE_LOAD = '\x7c' static
SE120, SE1200.
PKT_STATUS_CLOCK_NOT_LOADED
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_CLOCK_NOT_LOADED = 0x0a static
Referenced by checkClock().
PKT_STATUS_CRC_ERROR_ON_LOAD
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_CRC_ERROR_ON_LOAD = 0x0b static
PKT_STATUS_EEPROM_NOT_UPDATED
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_EEPROM_NOT_UPDATED = 0x08 static
PKT_STATUS_ILLEGAL_REQUEST
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_ILLEGAL_REQUEST = 0x01 static
PKT_STATUS_INVALID_CHANNEL
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_INVALID_CHANNEL = 0x06 static
PKT_STATUS_INVALID_DATE_TIME
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_INVALID_DATE_TIME = 0x04 static
PKT_STATUS_INVALID_REPEAT_COUNT
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_INVALID_REPEAT_COUNT = 0x09 static
PKT_STATUS_INVALID_TRANSMIT_INTERVAL
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_INVALID_TRANSMIT_INTERVAL = 0x07 static
PKT_STATUS_ITEM_NOT_FOUND
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_ITEM_NOT_FOUND = 0x03 static
PKT_STATUS_OK
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_OK = 0 static
PKT_STATUS_TRANSMIT_OVERLAP
const char nidas::dynld::isff::SE_GOESXmtr::PKT_STATUS_TRANSMIT_OVERLAP = 0x05 static
PKT_XMT_DATA
const char nidas::dynld::isff::SE_GOESXmtr::PKT_XMT_DATA = '\x15' static
Transmit data, SE110 only.
PKT_XMT_DATA_SE120
const char nidas::dynld::isff::SE_GOESXmtr::PKT_XMT_DATA_SE120 = '\x1e' static
Transmit, SE120, SE1200.
Referenced by testTransmitSE120().
selfTestCodes
SE_GOESXmtr::selfTest SE_GOESXmtr::selfTestCodes static
Initial value:
= {
    {
        {0x0001,"Ext RAM Test Failure"},
        {0x0002,"Ext RAM PageTest Failure"},
        {0x0004,"Battery Voltage < 10.5 Volts"},
        {0x0008,"EEPROM1 Program CRC Test Failure"},
        {0x0100,"RF Supply Voltage Failure"},
        {0x0200,"RF PLL Lock Failure"},
        {0x0000,""},
        {0x0000,""},
        {0x0000,""},
        {0x0000,""},
    },
    {
        {0x0004,"Battery Voltage < 10.0 Volts"},
        {0x0008,"Software Boot Code Flash CRC Error"},
        {0x0010,"RS232 Software Flash CRC Error"},
        {0x0020,"Temperature Sensor Test Failure"},
        {0x0040,"TCX0 DAC Test Failure"},
        {0x0100,"HSB Software Flash CRC Error"},
        {0x0200,"RF PLL Lock Failure"},
        {0x0400,"TOD Interrrupt Test Failure"},
        {0x0800,"Modulation Interrupt Test Failure"},
        {0x1000,"Manufacturing Data Flash CRC Error"},
    },
}
Referenced by getSelfTestStatusString().
SOH
const char nidas::dynld::isff::SE_GOESXmtr::SOH = '\x1' static
Byte at beginning of each message sent to or received from transmitter.
Referenced by recv().
SOH_STR
const std::string SE_GOESXmtr::SOH_STR = string(1,SOH) static
statusCodeStrings
const char * SE_GOESXmtr::statusCodeStrings static
Initial value:
= {
    "Packet transmission OK",
    "Illegal request",
    "Unknown status",
    "Item not found",
    "Invalid data or time",
    "Transmission time overlap",
    "Invalid channel",
    "Invalid transmit interval",
    "EEPROM not updated",
    "Invalid repeat count",
    "Clock not loaded",
    "CRC error on load",
}
The documentation for this class was generated from the following files:
nidas/dynld/isff/SE_GOESXmtr.h
nidas/dynld/isff/SE_GOESXmtr.cc