nidas: nidas::core::SerialSensor::Prompter Class Reference
nidas::core::SerialSensor::Prompter Class Reference
Public Member Functions
Prompter (SerialSensor *sensor)
~Prompter ()
void setPrompt (const std::string &val)
const std::string getPrompt () const
void setPromptPeriodMsec (const int)
int getPromptPeriodMsec () const
void setPromptOffsetMsec (const int)
int getPromptOffsetMsec () const
void looperNotify () throw ()
Method called by Looper in order to send a prompt.
Private Member Functions
Prompter (const Prompter &)
copy not necessary
Prompter & operator= (const Prompter &)
assignment not necessary
Private Attributes
SerialSensor * _sensor
char * _prompt
int _promptLen
int _promptPeriodMsec
int _promptOffsetMsec
Constructor & Destructor Documentation
Prompter() [1/2]
nidas::core::SerialSensor::Prompter::Prompter (SerialSensor * sensor) inline
~Prompter()
SerialSensor::Prompter::~Prompter ()
References _prompt.
Prompter() [2/2]
nidas::core::SerialSensor::Prompter::Prompter (const Prompter &) private
copy not necessary
Member Function Documentation
getPrompt()
const std::string nidas::core::SerialSensor::Prompter::getPrompt () const inline
References _prompt.
getPromptOffsetMsec()
int nidas::core::SerialSensor::Prompter::getPromptOffsetMsec () const inline
References _promptOffsetMsec.
Referenced by nidas::core::SerialSensor::startPrompting().
getPromptPeriodMsec()
int nidas::core::SerialSensor::Prompter::getPromptPeriodMsec () const inline
References _promptPeriodMsec.
Referenced by nidas::core::SerialSensor::startPrompting().
looperNotify()
void SerialSensor::Prompter::looperNotify () throw () virtual
Method called by Looper in order to send a prompt.
Implements nidas::core::LooperClient.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
operator=()
Prompter& nidas::core::SerialSensor::Prompter::operator= (const Prompter &) private
assignment not necessary
setPrompt()
void SerialSensor::Prompter::setPrompt (const std::string & val)
Referenced by nidas::core::SerialSensor::initPrompting().
setPromptOffsetMsec()
void SerialSensor::Prompter::setPromptOffsetMsec (const int val)
Referenced by nidas::core::SerialSensor::initPrompting().
setPromptPeriodMsec()
void SerialSensor::Prompter::setPromptPeriodMsec (const int val)
Referenced by nidas::core::SerialSensor::initPrompting().
Member Data Documentation
_prompt
char* nidas::core::SerialSensor::Prompter::_prompt private
Referenced by getPrompt(), and ~Prompter().
_promptLen
int nidas::core::SerialSensor::Prompter::_promptLen private
_promptOffsetMsec
int nidas::core::SerialSensor::Prompter::_promptOffsetMsec private
Referenced by getPromptOffsetMsec().
_promptPeriodMsec
int nidas::core::SerialSensor::Prompter::_promptPeriodMsec private
Referenced by getPromptPeriodMsec().
_sensor
SerialSensor* nidas::core::SerialSensor::Prompter::_sensor private
The documentation for this class was generated from the following files:
nidas/core/SerialSensor.h
nidas/core/SerialSensor.cc