nidas: nidas/apps/ck_xml.cc File Reference
ck_xml.cc File Reference
#include <nidas/core/XMLParser.h>
#include <nidas/core/Project.h>
#include <nidas/core/Site.h>
#include <nidas/core/DSMConfig.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/SampleTag.h>
#include <nidas/core/Variable.h>
#include <nidas/core/VariableConverter.h>
#include <nidas/core/CalFile.h>
#include <nidas/core/NidasApp.h>
#include <nidas/core/Socket.h>
#include <nidas/core/SocketAddrs.h>
#include <nidas/core/XMLException.h>
#include <nidas/dynld/RawSampleInputStream.h>
#include <nidas/core/requestXMLConfig.h>
#include <iostream>
#include <iomanip>
#include <list>
#include <unistd.h>
#include <stdlib.h>
Classes
class PConfig
Typedefs
typedef std::map< std::string, const Variable * > variable_map_t
Functions
int main (int argc, char **argv)
Typedef Documentation
variable_map_t
typedef std::map<std::string, const Variable*> variable_map_t
Function Documentation
main()
int main (int argc, char ** argv)
References PConfig::main(), PConfig::parseRunstring(), nidas::core::NidasApp::setApplicationInstance(), and nidas::util::Exception::what().