nidas: DatasetsApp Class Reference
DatasetsApp Class Reference
Public Types
enum tasks { NUTTIN_TO_DO , LIST_DATASET_NAMES , SHOW_BASH_ENV , SHOW_CSH_ENV }
Public Member Functions
DatasetsApp ()
int parseRunstring (int argc, char **argv)
int run ()
void listDatasetNames ()
void showEnv ()
Static Public Member Functions
static int usage (const char *argv0)
Private Attributes
string _xmlFile
XML file containing datasets.
enum tasks _task
What to do, per runstring arguments.
string _datasetName
Name of dataset.
Datasets _datasets
Member Enumeration Documentation
tasks
enum DatasetsApp::tasks
Enumerator
NUTTIN_TO_DO
LIST_DATASET_NAMES
SHOW_BASH_ENV
SHOW_CSH_ENV
Constructor & Destructor Documentation
DatasetsApp()
DatasetsApp::DatasetsApp ()
Member Function Documentation
listDatasetNames()
void DatasetsApp::listDatasetNames ()
References _datasets, nidas::core::Datasets::getDatasets(), and nidas::core::Dataset::getName().
Referenced by run().
parseRunstring()
int DatasetsApp::parseRunstring (int argc, char ** argv)
References _datasetName, _task, _xmlFile, LIST_DATASET_NAMES, NUTTIN_TO_DO, SHOW_BASH_ENV, SHOW_CSH_ENV, and usage().
Referenced by main().
run()
int DatasetsApp::run ()
References _datasets, _task, _xmlFile, LIST_DATASET_NAMES, listDatasetNames(), nidas::core::Datasets::parseXML(), SHOW_BASH_ENV, SHOW_CSH_ENV, showEnv(), and nidas::util::Exception::what().
Referenced by main().
showEnv()
void DatasetsApp::showEnv ()
References _datasetName, _datasets, _task, nidas::core::Datasets::getDataset(), nidas::core::Dataset::getEnvironmentVariables(), nidas::core::Dataset::getName(), SHOW_BASH_ENV, and SHOW_CSH_ENV.
Referenced by run().
usage()
int DatasetsApp::usage (const char * argv0) static
Referenced by parseRunstring().
Member Data Documentation
_datasetName
string DatasetsApp::_datasetName private
Name of dataset.
Referenced by parseRunstring(), and showEnv().
_datasets
Datasets DatasetsApp::_datasets private
Referenced by listDatasetNames(), run(), and showEnv().
_task
enum tasks DatasetsApp::_task private
What to do, per runstring arguments.
Referenced by parseRunstring(), run(), and showEnv().
_xmlFile
string DatasetsApp::_xmlFile private
XML file containing datasets.
Referenced by parseRunstring(), and run().
The documentation for this class was generated from the following file:
nidas/apps/isff/datasets.cc