nidas: nidas/apps/lidar_vel.cc File Reference
lidar_vel.cc File Reference
#include <unistd.h>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cmath>
Macros
#define MAX_BUFFER 512
Functions
static int parse_args (int argc, char **argv)
static void usage (FILE *out)
static int process_file (char *path)
static void compute_freq (int nsamples, double *spec, double *mean_freq, double *spec_width)
int main (int argc, char **argv)
Variables
static int debug = 0
static int verbose = 0
static char * filepath = NULL
static double nyq_freq_mhz = 100
static double noise_mag = 1.0e6
Macro Definition Documentation
MAX_BUFFER
#define MAX_BUFFER 512
Function Documentation
compute_freq()
static void compute_freq (int nsamples, double * spec, double * mean_freq, double * spec_width) static
References debug, MAX_BUFFER, noise_mag, and nyq_freq_mhz.
Referenced by process_file().
main()
int main (int argc, char ** argv)
References filepath, parse_args(), process_file(), and usage().
parse_args()
static int parse_args (int argc, char ** argv) static
References debug, filepath, noise_mag, nyq_freq_mhz, usage(), and verbose.
Referenced by main().
process_file()
static int process_file (char * path) static
References compute_freq(), debug, fclose(), MAX_BUFFER, noise_mag, nyq_freq_mhz, and verbose.
Referenced by main().
usage()
static void usage (FILE * out) static
Referenced by main(), and parse_args().
Variable Documentation
debug
int debug = 0 static
Referenced by compute_freq(), main(), parse_args(), and process_file().
filepath
char* filepath = NULL static
Referenced by main(), and parse_args().
noise_mag
double noise_mag = 1.0e6 static
Referenced by compute_freq(), parse_args(), and process_file().
nyq_freq_mhz
double nyq_freq_mhz = 100 static
Referenced by compute_freq(), parse_args(), and process_file().
verbose
int verbose = 0 static
Referenced by nidas::core::XMLParser::parse(), parse_args(), nidas::core::Datasets::parseXML(), and process_file().