nidas: nidas::core Namespace Reference
nidas::core Namespace Reference
The essential core classes of nidas.
Classes
class AdaptiveDespiker
Adaptive forecaster for despiking of time-series data.
class AsciiSscanf
Class providing sscanf functionality for parsing ASCII data.
class BadSampleFilter
Implement rules for filtering bad samples.
class BadSampleFilterArg
BadSampleFilterArg is a NidasAppArg for configuring a BadSampleFilter with filter rules pased to the –filter option.
class CalFile
A class for reading ASCII files containing a time series of calibration data.
class CharacterSensor
Implementation of support for a sensor which generates character output.
class ChronyStatusNode
Object with a printChronyStatus() method which can be called from a DSMServer.
class ConnectionInfo
Extra information associated with an IOChannel concerning the connection.
class SampleConnectionRequester
Interface for an object that requests connections SampleOutputs.
class DatagramSocket
Implementation of an IOChannel, over a DatagramSocket.
class Dataset
A Dataset is a named collection of parameters, that are used in data processing.
class Datasets
A collection of Datasets.
class DerivedDataClient
Interface of a DerivedDataClient of the DerivedDataReader.
class DerivedDataReader
This class will read, parse and make available the parameters in the onboard real-time broadcast of data.
class Dictionary
Interface for a Dictionary class, which can return a string value for a string token name.
class DOMable
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
class DOMObjectFactory
Class that supports creating instances of DOMable objects from a string containing the class name of the object to be created.
class DSMCatalog
A catalog of DSM DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
class DSMConfig
Class that should include all that is configurable about a DSM.
class DSMEngine
Application for running the NIDAS data acquistion process.
class DSMEngineIntf
A thread that provides XML-based Remote Procedure Calls to web interfaces from the DSMEngine.
class DSMSensor
DSMSensor provides the basic support for reading, processing and distributing samples from a sensor attached to a DSM.
class DSMServer
A provider of services to a DSM.
class DSMServerApp
class DSMServerIntf
A thread that provides XML-based Remote Procedure Calls to web interfaces from the DSMServer.
class GetDsmList
gets a list of DSMs and their locations from the configuration
class GetAdsFileName
gets the name of the current .ads file
class DSMService
Base class for a service, as built from a <service> XML tag.
class DynamicLoader
Class providing dynamic loader functionality of system functions dlopen() and dlsym() to look up symbols.
class FileSet
Implementation of an IOChannel using an nidas::util::FileSet.
class FsMount
Filesystem mounter/unmounter.
class FsMountWorkerThread
Filesystem mounter/unmounter.
class HeaderSource
An interface for sending a SampleHeader to a SampleOutput.
class IOChannelRequester
Interface for an object that requests connections to Inputs or Outputs.
class IOChannel
A channel for Input or Output of data.
class IODevice
An interface to an IO device.
class IOStream
A base class for buffering data.
class Looper
Looper is a Thread that periodically loops, calling the LooperClient::looperNotify() method of LooperClients at the requested intervals.
class LooperClient
Interface of a client of Looper.
class McSocket
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::Socket> to establish a TCP connection.
class McSocketUDP
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::DatagramSocket> to establish a pair of communicating UDP sockets.
class MultipleUDPSockets
class NearestResampler
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
class NearestResamplerAtRate
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
class NidasAppException
The NidasApp class throws a NidasAppException when command-line options do not parse.
class NidasAppArg
A NidasAppArg is command-line argument which can be handled by NidasApp.
class NidasAppInputFilesArg
Extend NidasAppArg so the default input specifier and port can be customized, which in turn updates the usage string.
class NidasApp
NidasApp handles common options for NIDAS applications.
struct NidasAppArgv
Convert vector<string> args to dynamically allocated (argc, argv) pair which will be freed when the instance is destroyed.
class SiteIterator
Class for iterating over the Sites of a Project, or the Sites served by a DSMServer.
class DSMServerIterator
Class for iterating over the DSMServers of a Project.
class DSMServiceIterator
Class for iterating over the DSMServices of a DSMServer.
class DSMConfigIterator
Class for iterating over the DSMConfigs of a Project or Site.
class ProcessorIterator
Class for iterating over the Processors of a DSMServer or DSMConfig.
class SensorIterator
Class for iterating over the DSMSensors of a Project, Site, or DSMConfig.
class SampleTagIterator
Class for iterating over the SampleTags of a Project, Site, DSMConfig, or a SampleSource.
class VariableIterator
Class for iterating over the Variables of a Project, Site, DSMConfig, DSMSensor, or SampleTag.
class Parameter
class ParameterT
A typed Parameter, with data of type T.
class ParameterNameTypeComparator
Functor class for Parameter, doing an equality check of parameter name and type.
class Polled
Interface for objects with a file descriptor, providing a virtual method to be called when system calls such as select, poll, or epoll indicate an event is pending on the file descriptor.
class Project
class ProjectConfig
class ProjectConfigTimeComparator
Sample time tag comparator.
class ProjectConfigs
class Prompt
Class to contain prompt information - string and rate.
class RemoteSerialConnection
class RemoteSerialListener
class Resampler
Interface for a resampler, simply a SampleClient and a SampleSource.
class SampleHeader
The gcc buildin atomic operations are not supported on arm, and one must use -march=i686 for them to work on 32 bit x86.
class Sample
Interface to a data sample.
class SampleT
A typed Sample, with data of type DataT.
struct sample_type_traits_base
struct sample_type_traits
struct sample_type_traits< char >
struct sample_type_traits< unsigned char >
struct sample_type_traits< unsigned short >
struct sample_type_traits< short >
struct sample_type_traits< unsigned int >
struct sample_type_traits< int >
struct sample_type_traits< float >
struct sample_type_traits< double >
struct sample_type_traits< long long >
struct sample_type_traits< void >
class SampleArchiver
class SampleAverager
class SampleBuffer
A SampleClient that buffers its received samples, using a pair of STL vectors, and then sends the buffered samples onto its SampleClients.
class SampleClient
Pure virtual interface of a client of Samples.
class SampleClientList
A list of SampleClients.
class SampleClock
SampleClock adds date information to sample time tags.
class SampleInput
Interface of an input SampleSource.
class SampleInputHeader
class SampleIOProcessor
Interface of a processor of samples.
class SampleLengthException
class SampleMatcher
Match samples according to DSM and Sample ID ranges, and configure the ranges with criteria in text format.
class SampleOutput
Interface of an output stream of samples.
class SampleOutputBase
Implementation of portions of SampleOutput.
class SampleOutputRequestThread
Interface of an output stream of samples.
class SampleParseException
class SamplePipeline
SamplePipeline sorts samples that are coming from one or more inputs.
class SamplePoolInterface
class SamplePools
class SamplePool
A pool of Samples.
class SampleScanner
A scanner of sample data.
class DriverSampleScanner
A SampleScanner for reading samples that have been pre-formatted by a device driver - they already have a header consisting of a timetag, and a data length.
class MessageSampleScanner
A DriverSampleScanner which supports the set/get of message separation parameters.
class MessageStreamScanner
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
class DatagramSampleScanner
class SampleSorter
A SampleClient that sorts its received samples, using an STL multiset, and then sends the sorted samples onto its SampleClients.
class SampleSource
Pure virtual interface for a source of Samples.
class SampleSourceSupport
A source of samples.
class SampleStats
A source of samples.
class SampleTag
Class describing a group of variables that are sampled and handled together.
class SampleThread
Interface for a Thread for buffering samples.
class SampleTracer
SampleTracer uses a Logger to log messages about samples as they are encountered in the code.
class SensorCatalog
A catalog of sensor DOMElements, implemented with std::map, containing sensor DOMElements, keyed by the ID attributes.
class SensorHandler
SensorHandler implements a DSMSensor event loop.
class SensorOpener
Thread which opens DSMSensors.
class SerialPortIODevice
A serial port.
class SerialSensor
Support for a sensor that is sending packets on a TCP socket, a UDP socket, a Bluetooth RF Comm socket, or a good old RS232/422/485 serial port.
class ServerSocketIODevice
An IODevice supporting a TCP or UNIX server socket.
class ServiceCatalog
A catalog of dsm DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
class Site
A measurement site.
class Socket
Implementation of an IOChannel, over a Socket.
class ServerSocket
Implementation of an IOChannel, over a ServerSocket.
class SocketIODevice
A IODevice providing support for UDP and TCP sockets.
class SampleTimetagComparator
Sample time tag comparator.
class SampleHeaderComparator
Timetag and Id comparator of pointers to Samples: if two timetags are the same, then compare Ids, and if they're equal, compare data length.
class FullSampleComparator
Comparator of pointers to Samples, does the same checks as SampleHeaderComparator, but in addition, if two samples compare as equal, then compares their data.
class StatusHandler
This class implements handling routines for the SAX2 parser.
class StatusListener
thread that listens to multicast messages from all of the DSMs.
class GetClocks
gets a list of current clock times for each broadcasting DSM.
class GetStatus
gets a list of current status reports for each broadcasting DSM.
class StatusThread
A thread that runs periodically checking and multicasting the status of a DSMEngine.
class DSMEngineStat
Thread which provides status in XML form from a dsm on a datagram socket, to be read by the status_listener.
class DSMServerStat
Thread which provides status from a dsm_server on a datagram socket.
class TCPSocketIODevice
An IODevice consisting of a TCP socket.
class TimetagAdjuster
Adjust time tags of fixed delta-T time series to correct for irregular latency in the assignments of the time tags at acquisition time.
class UDPSocketIODevice
An IODevice consisting of an UDP socket.
class UnixIOChannel
Simple implementation of an IOChannel, over an opened file descriptor.
class UnixIODevice
A basic Unix I/O device, such as a named pipe, or a watched file.
class Variable
Class describing a sampled variable.
class CalFileHandler
This is the interface for handling CalFile records as they are read by a VariableConverter.
class VariableConverter
class Linear
Why isn't this a sublcass of Polynomial which sets MAX_NUM_COEFFS to 2?
class Polynomial
class CalFileHandlerFunction
A template subclass which implements the CalFileHandler interface by calling a function object.
class VariableIndex
A VariableIndex associates a Variable pointer with it's index into it's SampleTag.
class Version
Class of static member functions providing version strings.
class XDOMElement
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
class XDOMAttr
Class providing convienence methods to access the string attributes of a DOMAttr.
class XMLConfigInput
class XMLConfigWriterFilter
class XMLConfigWriter
An XMLWriter which writes the NIDAS XML configuration.
class XMLException
Exception which can be built from an xerces::XMLException, xercesc::SAXException, or xercesc::DOMException.
class XMLFdBinInputStream
Implemenation of xercesc::BinInputStream, which reads from a unix file descriptor.
class XMLFdFormatTarget
Extension of xercesc::XMLFormatTarget support writing XML to an open device (socket for example).
class XMLFdInputSource
Implemenation of xercesc::InputSource, that returns an XMLFdBinInputStream for reading from a Unix file descriptor - i.e.
class XMLImplementation
class XMLErrorHandler
class XMLParser
Wrapper class around xerces-c DOMBuilder to parse XML.
class XMLCachingParser
Derived class of XMLParser that keeps its DOMDocuments when parsing an XML disk file, and returns the cached DOMDocument if the file hasn't changed.
class XmlRpcThread
A thread that provides XML-based Remote Procedure Calls to web interfaces.
class XMLStringConverter
Class providing conversions between string and XMLCh* using the Xerces-c transcode and release methods.
class XMLWriter
Wrapper class around xerces-c DOMWriter to write XML.
Typedefs
typedef std::vector< NidasAppArg * > nidas_app_arglist_t
Lists of arguments can be manipulated together by putting them into this container type.
typedef std::vector< std::string > ArgVector
Convenience typedef for handling the command-line argv as a vector of strings.
typedef long long dsm_time_t
Posix time in microseconds, the number of non-leap microseconds since 1970 Jan 1 00:00 UTC.
typedef unsigned int dsm_sample_id_t
typedef enum nidas::core::sampleType sampleType
typedef std::multiset< const Sample *, SampleTimetagComparator > SortedSampleSet
A multiset for storing samples sorted by timetag.
typedef std::set< const Sample *, SampleHeaderComparator > SortedSampleSet2
A set for storing samples sorted by the timetag, id and data length.
typedef std::set< const Sample *, FullSampleComparator > SortedSampleSet3
Enumerations
enum McSocketRequest {
XML_CONFIG = 0 , RAW_SAMPLE , UDP_PROCESSED_SAMPLE_FEED , XML_ALL_CONFIG ,
UNKNOWN_REQUEST
}
enum sampleType {
CHAR_ST , UCHAR_ST , SHORT_ST , USHORT_ST ,
INT32_ST , UINT32_ST , FLOAT_ST , DOUBLE_ST ,
INT64_ST , UNKNOWN_ST
}
Functions
std::ostream & operator<< (std::ostream &out, const BadSampleFilter &bsf)
Stream the current rules for BadSampleFilter bsf to out.
void printChronyHeader (std::ostream &ostr) throw ()
void printChronyTrailer (std::ostream &ostr) throw ()
std::string expectArg (const ArgVector &args, int i)
nidas_app_arglist_t operator| (nidas_app_arglist_t arglist1, nidas_app_arglist_t arglist2)
Combine two arglists into a single arglist without any duplicates.
Parameter::parType getParamType (std::string)
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
Parameter::parType getParamType (float)
Parameter::parType getParamType (int)
Parameter::parType getParamType (bool)
xercesc::DOMDocument * requestXMLConfig (bool all, const n_u::Inet4SocketAddress &mcastAddr, sigset_t *signalMask=(sigset_t *) 0)
Request the XML configuration via a McSocket request to a given multicast socket address.
Sample * getSample (sampleType type, unsigned int len)
A convienence method for getting a sample of an enumerated type from a pool.
template<class T >
SampleT< T > * getSample (unsigned int len)
A convenience function for getting a typed sample from a pool.
unsigned int maxValue (unsigned short)
maxValue is an overloaded function returning the maximum value of its integer argument.
unsigned int maxValue (short)
unsigned int maxValue (int)
unsigned int maxValue (unsigned int)
template<typename T >
sampleType getSampleType (T *)
template<class F >
CalFileHandler * makeCalFileHandler (F _fo)
Helper function to deduce the function object type and return a new instance of the CalFileHandlerFunction type which calls it.
xercesc::DOMDocument * parseXMLConfigFile (const std::string &xmlFileName)
Utility function which creates a temporary XMLParser, sets the options we typically want and parses the XML into a DOMDocument.
std::ostream & operator<< (std::ostream &target, const XMLStringConverter &toDump)
std::ostream & operator<< (std::ostream &out, const nidas::core::SampleHeader &header)
std::ostream & operator<< (std::ostream &out, const nidas::core::Sample &samp)
Variables
bool chronyZebra = false
const double MS_PER_KNOT = 1852.0 / 3600.0
const float MBAR_PER_PSI = 68.9476
const float MBAR_PER_KPA = 10.0
const float KELVIN_AT_0C = 273.15
const float STANDARD_ATMOSPHERE = 1013.25
const float floatNAN = nanf("")
Value of a float NAN for general use.
const double doubleNAN = nan("")
Detailed Description
The essential core classes of nidas.
Typedef Documentation
ArgVector
typedef std::vector<std::string> nidas::core::ArgVector
Convenience typedef for handling the command-line argv as a vector of strings.
dsm_sample_id_t
typedef unsigned int nidas::core::dsm_sample_id_t
dsm_time_t
typedef long long nidas::core::dsm_time_t
Posix time in microseconds, the number of non-leap microseconds since 1970 Jan 1 00:00 UTC.
nidas_app_arglist_t
typedef std::vector<NidasAppArg*> nidas::core::nidas_app_arglist_t
Lists of arguments can be manipulated together by putting them into this container type.
The container can be generated using operator|().
sampleType
typedef enum nidas::core::sampleType nidas::core::sampleType
SortedSampleSet
typedef std::multiset<const Sample*,SampleTimetagComparator> nidas::core::SortedSampleSet
A multiset for storing samples sorted by timetag.
It is a multiset rather than a set because it is OK to have samples with the same timetag.
SortedSampleSet2
typedef std::set<const Sample*,SampleHeaderComparator> nidas::core::SortedSampleSet2
A set for storing samples sorted by the timetag, id and data length.
Duplicate samples which compare as equal (!(x<y) & !(y<x)) to another are not inserted. This is used for merging archives containing duplicate samples. Note that we're not comparing the data in the sample. Also note: you must check the return of insert(const Sample*) to know whether a sample was inserted. If a sample wasn't inserted you likely want to do a Sample::freeReference() on it.
SortedSampleSet3
typedef std::set<const Sample*,FullSampleComparator> nidas::core::SortedSampleSet3
Enumeration Type Documentation
McSocketRequest
enum nidas::core::McSocketRequest
Enumerator
XML_CONFIG
Request for a TCP feed of the configuration in XML.
RAW_SAMPLE
Request for a TCP feed of raw samples.
UDP_PROCESSED_SAMPLE_FEED
Request for feed of processed samples on a UDP socket, and a listing of variables on a TCP socket.
XML_ALL_CONFIG
Request for a TCP feed of the entire configuration in XML.
UNKNOWN_REQUEST
sampleType
enum nidas::core::sampleType
Enumerator
CHAR_ST
UCHAR_ST
SHORT_ST
USHORT_ST
INT32_ST
UINT32_ST
FLOAT_ST
DOUBLE_ST
INT64_ST
UNKNOWN_ST
Function Documentation
expectArg()
std::string nidas::core::expectArg (const ArgVector & args, int i) inline
Referenced by nidas::core::BadSampleFilterArg::parse(), and nidas::core::NidasAppArg::parse().
getParamType() [1/4]
Parameter::parType nidas::core::getParamType (bool) inline
getParamType() [2/4]
Parameter::parType nidas::core::getParamType (float) inline
References nidas::core::Parameter::FLOAT_PARAM.
getParamType() [3/4]
Parameter::parType nidas::core::getParamType (int) inline
References nidas::core::Parameter::INT_PARAM.
getParamType() [4/4]
Parameter::parType nidas::core::getParamType (std::string) inline
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
References nidas::core::Parameter::STRING_PARAM.
getSample() [1/2]
Sample * nidas::core::getSample (sampleType type, unsigned int len)
A convienence method for getting a sample of an enumerated type from a pool.
Returns NULL if type is unknown or len is out of range.
References CHAR_ST, DOUBLE_ST, FLOAT_ST, INT32_ST, INT64_ST, len, SHORT_ST, UCHAR_ST, UINT32_ST, UNKNOWN_ST, and USHORT_ST.
Referenced by nidas::core::SamplePool< SampleType >::getSample(), and nidas::dynld::SampleInputStream::sampleFromHeader().
getSample() [2/2]
template<class T > SampleT<T>* nidas::core::getSample (unsigned int len)
A convenience function for getting a typed sample from a pool.
References nidas::core::SamplePool< SampleType >::getSample(), and len.
getSampleType()
template<typename T > sampleType nidas::core::getSampleType (T *) inline
Referenced by nidas::core::SampleT< DataT >::getType().
makeCalFileHandler()
template<class F > CalFileHandler* nidas::core::makeCalFileHandler (F _fo)
Helper function to deduce the function object type and return a new instance of the CalFileHandlerFunction type which calls it.
For example, this code creates a new instance of CalFileHandler which calls the handleRawT() method of the NCAR_TRH sensor class:
makeCalFileHandler(std::bind1st(std::mem_fun(&NCAR_TRH::handleRawT), this));
Where handleRawT has a signature like this:
bool handleRawT(nidas::core::CalFile* cf);
Referenced by nidas::dynld::isff::NCAR_TRH::NCAR_TRH().
maxValue() [1/4]
unsigned int nidas::core::maxValue (int) inline
maxValue() [2/4]
unsigned int nidas::core::maxValue (short) inline
maxValue() [3/4]
unsigned int nidas::core::maxValue (unsigned int) inline
maxValue() [4/4]
unsigned int nidas::core::maxValue (unsigned short) inline
maxValue is an overloaded function returning the maximum value of its integer argument.
Referenced by nidas::core::SampleHeader::getMaxDataLength().
operator<<() [1/4]
std::ostream & nidas::core::operator<< (std::ostream & out, const BadSampleFilter & bsf)
Stream the current rules for BadSampleFilter bsf to out.
References nidas::core::BadSampleFilter::filterBadSamples(), nidas::util::UTime::format(), nidas::core::BadSampleFilter::maxDsmId(), nidas::core::BadSampleFilter::maxSampleLength(), nidas::core::BadSampleFilter::maxSampleTime(), nidas::core::BadSampleFilter::minDsmId(), nidas::core::BadSampleFilter::minSampleLength(), nidas::core::BadSampleFilter::minSampleTime(), nidas::core::BadSampleFilter::sampleTypeLimit(), nidas::core::BadSampleFilter::skipNidasHeader(), nidas::util::UTime::toUsecs(), and UNKNOWN_ST.
operator<<() [2/4]
std::ostream& nidas::core::operator<< (std::ostream & out, const nidas::core::Sample & samp)
References nidas::core::Sample::getHeaderPtr().
operator<<() [3/4]
std::ostream& nidas::core::operator<< (std::ostream & out, const nidas::core::SampleHeader & header)
References ftime(), GET_DSM_ID, GET_SPS_ID, nidas::core::SampleHeader::getDataByteLength(), nidas::core::SampleHeader::getId(), nidas::core::SampleHeader::getTimeTag(), and nidas::core::SampleHeader::getType().
operator<<() [4/4]
std::ostream& nidas::core::operator<< (std::ostream & target, const XMLStringConverter & toDump) inline
operator|()
nidas_app_arglist_t nidas::core::operator| (nidas_app_arglist_t arglist1, nidas_app_arglist_t arglist2)
Combine two arglists into a single arglist without any duplicates.
Order is preserved, with all arguments in the the second arglist succeeding the args in the first arglist.
parseXMLConfigFile()
xercesc::DOMDocument * nidas::core::parseXMLConfigFile (const std::string & xmlFileName)
Utility function which creates a temporary XMLParser, sets the options we typically want and parses the XML into a DOMDocument.
Exceptions
nidas::core::XMLException
Referenced by nidas::core::ProjectConfig::initProject(), StatsProcess::listOutputSamples(), nidas::core::Project::parseXMLConfigFile(), ARLIngest::prepareHeaderIds(), DataDump::run(), DataStats::run(), DmdA2dCk::run(), DataPrep::run(), ExtractFast2D::run(), ExtractDMT::run(), StatsProcess::run(), and nidas::core::DSMEngine::run().
printChronyHeader()
void nidas::core::printChronyHeader (std::ostream & ostr) throw ()
References chronyZebra.
Referenced by nidas::core::DSMServerStat::run().
printChronyTrailer()
void nidas::core::printChronyTrailer (std::ostream & ostr) throw ()
Referenced by nidas::core::DSMServerStat::run().
requestXMLConfig()
xercesc::DOMDocument * nidas::core::requestXMLConfig (bool all, const n_u::Inet4SocketAddress & mcastAddr, sigset_t * signalMask = (sigset_t*)0)
Request the XML configuration via a McSocket request to a given multicast socket address.
Parameters
all If true, request the entire project XML, otherwise just the XML which corresponds to the address of the calling DSM.
Exceptions
nidas::util::Exception
References nidas::util::McSocket< SocketT >::close(), nidas::util::McSocket< SocketT >::connect(), DLOG, PLOG, nidas::util::McSocket< SocketT >::setInet4McastSocketAddress(), nidas::util::McSocket< SocketT >::setRequestType(), nidas::util::Inet4SocketAddress::toString(), nidas::util::Exception::what(), and XML_ALL_CONFIG.
Referenced by PConfig::loadRemoteXML(), and nidas::core::DSMEngine::run().
Variable Documentation
chronyZebra
bool nidas::core::chronyZebra = false extern
Referenced by printChronyHeader().
doubleNAN
const double nidas::core::doubleNAN = nan("") extern
Referenced by nidas::dynld::raf::SyncRecordSource::allocateRecord(), nidas::dynld::GPS_Novatel_Serial::parseBESTPOS(), nidas::dynld::GPS_Novatel_Serial::parseBESTVEL(), nidas::dynld::GPS_NMEA_Serial::parseGGA(), nidas::dynld::GPS_NMEA_Serial::parseHDT(), nidas::dynld::GPS_NMEA_Serial::parseRMC(), nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), nidas::dynld::raf::IRS_HW_YG1854::processLabel(), and nidas::dynld::raf::LSZ_HW_EB7032239::processLabel().
floatNAN
const float nidas::core::floatNAN = nanf("") extern
Value of a float NAN for general use.
Referenced by nidas::dynld::DSC_FreqCounter::calculatePeriodUsec(), SampleCounter::computeRate(), nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::isff::RebsLinear::convert(), nidas::core::Variable::convert(), nidas::dynld::ParoSci_202BG_P::createPressureSample(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::NearestResampler::flush(), nidas::core::SampleAverager::flush(), nidas::dynld::raf::IRIGSensor::get100HzBacklog(), nidas::dynld::isff::SE_GOESXmtr::getBatteryVoltages(), nidas::core::CalFile::getFields(), nidas::dynld::A2DSensor::getIntercept(), nidas::core::Parameter::getNumericValue(), nidas::dynld::ParoSci_202BG_T::getPeriodUsec(), nidas::core::SamplePool< SampleType >::getSample(), nidas::dynld::A2DSensor::getSlope(), nidas::dynld::isff::NCAR_TRH::ifanFilter(), nidas::dynld::ParoSci_202BG_Calibration::ParoSci_202BG_Calibration(), nidas::dynld::GPS_Novatel_Serial::parseBESTPOS(), nidas::dynld::isff::PacketParser::parseData(), nidas::core::DerivedDataReader::parseIWGADTS(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::Wind2D::process(), nidas::dynld::isff::Wind3D::process(), nidas::dynld::DSC_FreqCounter::process(), nidas::dynld::ParoSci_202BG_T::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::raf::IRIGSensor::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::raf::DSMMesaSensor::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::VCSEL_Serial::process(), nidas::dynld::raf::Watlow::process(), nidas::dynld::raf::TwoD64_USB_v3::processSOR(), nidas::dynld::ParoSci_202BG_Calibration::readCalFile(), nidas::dynld::isff::Wind3D::readOffsetsAnglesCalFile(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::core::Linear::reset(), nidas::core::Polynomial::reset(), nidas::dynld::isff::CS_Krypton::reset(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::PHIPS_UDP::scanValue(), nidas::core::NearestResamplerAtRate::sendSample(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), nidas::dynld::isff::ATIK_Sonic::transducerShadowCorrection(), nidas::core::DSMSensor::trimUnparsed(), nidas::dynld::isff::WisardMote::TsoilData::TsoilData(), nidas::dynld::isff::WisardMote::unpack100thSec(), nidas::dynld::isff::WisardMote::unpack10thSec(), nidas::dynld::isff::WisardMote::unpackAccumSec(), nidas::dynld::isff::WisardMote::unpackCNR2(), nidas::dynld::isff::WisardMote::unpackGsoil(), nidas::dynld::isff::WisardMote::unpackInt16(), nidas::dynld::isff::WisardMote::unpackInt32(), nidas::dynld::isff::WisardMote::unpackNR01(), nidas::dynld::isff::WisardMote::unpackPicTime(), nidas::dynld::isff::WisardMote::unpackPicTimeFields(), nidas::dynld::isff::WisardMote::unpackPower(), nidas::dynld::isff::WisardMote::unpackQsoil(), nidas::dynld::isff::WisardMote::unpackRlw(), nidas::dynld::isff::WisardMote::unpackRlwKZ(), nidas::dynld::isff::WisardMote::unpackRnet(), nidas::dynld::isff::WisardMote::unpackRsw(), nidas::dynld::isff::WisardMote::unpackRsw2(), nidas::dynld::isff::WisardMote::unpackStatus(), nidas::dynld::isff::WisardMote::unpackTP01(), nidas::dynld::isff::WisardMote::unpackTRH(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::WisardMote::unpackUint16(), nidas::dynld::isff::WisardMote::unpackUint32(), nidas::dynld::isff::WisardMote::unpackXbee(), and nidas::core::Variable::Variable().
KELVIN_AT_0C
const float nidas::core::KELVIN_AT_0C = 273.15
Referenced by nidas::dynld::raf::AlicatSDI::computeFlow(), nidas::dynld::isff::ATIK_Sonic::process(), and nidas::dynld::isff::CSAT3_Sonic::process().
MBAR_PER_KPA
const float nidas::core::MBAR_PER_KPA = 10.0
Referenced by nidas::dynld::ParoSci_202BG_Calibration::readCalFile().
MBAR_PER_PSI
const float nidas::core::MBAR_PER_PSI = 68.9476
MS_PER_KNOT
const double nidas::core::MS_PER_KNOT = 1852.0 / 3600.0
Referenced by nidas::dynld::GPS_NMEA_Serial::parseRMC().
STANDARD_ATMOSPHERE
const float nidas::core::STANDARD_ATMOSPHERE = 1013.25
Referenced by nidas::dynld::raf::AlicatSDI::computeFlow().