nidas: nidas::dynld::RawSampleService Class Reference
nidas::dynld::RawSampleService Class Reference
A RawSampleService reads raw Samples from a socket connection and sends the samples to one or more SampleIOProcessors.
#include <RawSampleService.h>
Classes
class Worker
Worker thread that is run when a SampleInputConnection is established.
Public Member Functions
RawSampleService ()
~RawSampleService ()
void connect (nidas::core::SampleInput *) throw ()
void disconnect (nidas::core::SampleInput *) throw ()
void schedule (bool optionalProcessing)
void interrupt () throw ()
void fromDOMElement (const xercesc::DOMElement *node)
void printClock (std::ostream &ostr) throw ()
void printStatus (std::ostream &ostr, float deltat) throw ()
float getRawSorterLength () const
Get the length of the SampleSorter of raw Samples, in seconds.
void setRawSorterLength (float val)
Set the length of the SampleSorter of raw Samples, in seconds.
float getProcSorterLength () const
Get the length of the SampleSorter of processed Samples, in seconds.
void setProcSorterLength (float val)
Set the length of the SampleSorter of processed Samples, in seconds.
size_t getRawHeapMax () const
Get the size of in bytes of the raw SampleSorter.
void setRawHeapMax (size_t val)
Set the size of in bytes of the raw SampleSorter.
size_t getProcHeapMax () const
Get the size of in bytes of the processed SampleSorter.
void setProcHeapMax (size_t val)
Set the size of in bytes of the processed SampleSorter.
unsigned int getRawLateSampleCacheSize () const
Get the size of the late sample cache in the raw sample sorter.
void setRawLateSampleCacheSize (unsigned int val)
Cache this number of samples with potentially anomalous, late time tags in the raw sample sorter.
unsigned int getProcLateSampleCacheSize () const
Get the size of the late sample cache in the processed sample sorter.
void setProcLateSampleCacheSize (unsigned int val)
Cache this number of samples with potentially anomalous, late time tags in the processed sample sorter.
const std::string & getName () const
virtual void setDSMServer (DSMServer *val)
virtual DSMServer * getDSMServer () const
virtual void addProcessor (SampleIOProcessor *proc)
Add a processor to this RawSampleService.
virtual const std::list< SampleIOProcessor * > & getProcessors () const
const std::list< SampleInput * > & getInputs () const
ProcessorIterator getProcessorIterator () const
virtual int checkSubThreads () throw ()
virtual void cancel () throw ()
virtual int join () throw ()
nidas::util::Thread::SchedPolicy getSchedPolicy () const
int getSchedPriority () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void addSubThread (nidas::util::Thread *) throw ()
Protected Attributes
std::string _name
DSMServer * _server
std::set< nidas::util::Thread * > _subThreads
nidas::util::Mutex _subThreadMutex
std::list< SampleInput * > _inputs
std::list< SampleIOProcessor * > _processors
std::list< IOChannel * > _ochans
nidas::util::Thread::SchedPolicy _threadPolicy
int _threadPriority
Private Member Functions
RawSampleService (const RawSampleService &)
Copying not supported.
RawSampleService & operator= (const RawSampleService &)
Assignment not supported.
Private Attributes
nidas::core::SamplePipeline * _pipeline
std::map< nidas::core::SampleInput *, Worker * > _workers
Keep track of the Worker for each SampleInput.
std::map< nidas::core::SampleInput *, const nidas::core::DSMConfig * > _dsms
nidas::util::Mutex _workerMutex
std::map< void *, size_t > _nsampsLast
Saved between calls to printStatus in order to compute data rates.
std::map< void *, long long > _nbytesLast
Saved between calls to printStatus in order to compute sample rates.
float _rawSorterLength
float _procSorterLength
size_t _rawHeapMax
size_t _procHeapMax
unsigned int _rawLateSampleCacheSize
unsigned int _procLateSampleCacheSize
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
A RawSampleService reads raw Samples from a socket connection and sends the samples to one or more SampleIOProcessors.
Constructor & Destructor Documentation
RawSampleService() [1/2]
RawSampleService::RawSampleService ()
~RawSampleService()
RawSampleService::~RawSampleService ()
References nidas::core::DSMService::join().
RawSampleService() [2/2]
nidas::dynld::RawSampleService::RawSampleService (const RawSampleService &) private
Copying not supported.
Member Function Documentation
addProcessor()
virtual void nidas::core::DSMService::addProcessor (SampleIOProcessor * proc) inline virtual inherited
Add a processor to this RawSampleService.
This is done at configuration (XML) time.
References nidas::core::DSMService::_processors.
Referenced by nidas::core::DSMService::fromDOMElement().
addSubThread()
void DSMService::addSubThread (nidas::util::Thread * thd) throw () protected inherited
cancel()
void DSMService::cancel () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Thread::cancel(), nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
checkSubThreads()
int DSMService::checkSubThreads () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
connect()
void RawSampleService::connect (nidas::core::SampleInput * input) throw () virtual
Implements nidas::core::DSMService.
References nidas::core::DSMSensor::addSampleTag(), nidas::core::Project::getInstance(), nidas::util::Logger::getInstance(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::Project::getSensorIterator(), nidas::core::SensorIterator::hasNext(), nidas::util::Logger::log(), LOG_INFO, LOG_WARNING, nidas::core::SensorIterator::next(), nidas::util::Thread::setThreadScheduler(), nidas::util::Thread::start(), nidas::util::Exception::what(), and WLOG.
disconnect()
void RawSampleService::disconnect (nidas::core::SampleInput * input) throw ()
References nidas::util::Logger::getInstance(), nidas::dynld::RawSampleService::Worker::interrupt(), nidas::util::Logger::log(), LOG_ERR, LOG_INFO, and WLOG.
fromDOMElement()
void RawSampleService::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented from nidas::core::DSMService.
References nidas::core::DSMService::_inputs, nidas::core::SampleSource::addSampleTag(), nidas::core::DSMService::fromDOMElement(), nidas::core::DSMService::getDSMServer(), nidas::core::DSMService::getName(), nidas::core::XDOMAttr::getName(), nidas::core::SampleInput::getName(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMServer::getSensorIterator(), nidas::core::XDOMAttr::getValue(), nidas::core::SensorIterator::hasNext(), nidas::core::SensorIterator::next(), setProcHeapMax(), setProcLateSampleCacheSize(), setProcSorterLength(), setRawHeapMax(), setRawLateSampleCacheSize(), and setRawSorterLength().
getClassName()
const string DSMService::getClassName (const xercesc::DOMElement * node, const Project * project) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::ServiceCatalog::find(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::Project::getServiceCatalog().
Referenced by nidas::core::DSMServer::fromDOMElement().
getDSMServer()
virtual DSMServer* nidas::core::DSMService::getDSMServer () const inline virtual inherited
References nidas::core::DSMService::_server.
Referenced by nidas::core::DSMService::fromDOMElement(), and fromDOMElement().
getInputs()
const std::list<SampleInput*>& nidas::core::DSMService::getInputs () const inline inherited
References nidas::core::DSMService::_inputs.
getName()
const std::string& nidas::core::DSMService::getName () const inline inherited
References nidas::core::DSMService::_name.
Referenced by nidas::core::DSMService::fromDOMElement(), fromDOMElement(), nidas::core::DSMServer::joinServices(), and nidas::core::DSMServer::~DSMServer().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getProcessorIterator()
ProcessorIterator DSMService::getProcessorIterator () const inherited
Referenced by printStatus().
getProcessors()
virtual const std::list<SampleIOProcessor*>& nidas::core::DSMService::getProcessors () const inline virtual inherited
References nidas::core::DSMService::_processors.
Referenced by nidas::core::ProcessorIterator::hasNext().
getProcHeapMax()
size_t nidas::dynld::RawSampleService::getProcHeapMax () const inline
Get the size of in bytes of the processed SampleSorter.
If the size of the sorter exceeds this value then samples will be discarded.
References _procHeapMax.
getProcLateSampleCacheSize()
unsigned int nidas::dynld::RawSampleService::getProcLateSampleCacheSize () const inline
Get the size of the late sample cache in the processed sample sorter.
See SampleSorter::getLateSampleCacheSize(). Default: 0.
References _procLateSampleCacheSize.
getProcSorterLength()
float nidas::dynld::RawSampleService::getProcSorterLength () const inline
Get the length of the SampleSorter of processed Samples, in seconds.
References _procSorterLength.
getRawHeapMax()
size_t nidas::dynld::RawSampleService::getRawHeapMax () const inline
Get the size of in bytes of the raw SampleSorter.
If the size of the sorter exceeds this value then samples will be discarded.
References _rawHeapMax.
getRawLateSampleCacheSize()
unsigned int nidas::dynld::RawSampleService::getRawLateSampleCacheSize () const inline
Get the size of the late sample cache in the raw sample sorter.
See SampleSorter::getLateSampleCacheSize(). Default: 0.
References _rawLateSampleCacheSize.
getRawSorterLength()
float nidas::dynld::RawSampleService::getRawSorterLength () const inline
Get the length of the SampleSorter of raw Samples, in seconds.
References _rawSorterLength.
getSchedPolicy()
nidas::util::Thread::SchedPolicy nidas::core::DSMService::getSchedPolicy () const inline inherited
References nidas::core::DSMService::_threadPolicy.
getSchedPriority()
int nidas::core::DSMService::getSchedPriority () const inline inherited
References nidas::core::DSMService::_threadPriority.
interrupt()
void RawSampleService::interrupt () throw () virtual
Reimplemented from nidas::core::DSMService.
References nidas::core::SampleIOProcessor::disconnectSource(), and nidas::core::DSMService::interrupt().
join()
int DSMService::join () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, nidas::util::Thread::RUN_OK, and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::joinServices(), and ~RawSampleService().
operator=()
RawSampleService& nidas::dynld::RawSampleService::operator= (const RawSampleService &) private
Assignment not supported.
printClock()
void RawSampleService::printClock (std::ostream & ostr) throw () virtual
Reimplemented from nidas::core::DSMService.
References _pipeline, nidas::util::UTime::format(), nidas::core::SampleStats::getLastTimeTag(), nidas::core::SamplePipeline::getRawSampleSource(), and nidas::core::SampleSource::getSampleStats().
Referenced by printStatus().
printStatus()
void RawSampleService::printStatus (std::ostream & ostr, float deltat) throw () virtual
Reimplemented from nidas::core::DSMService.
References _dsms, _nbytesLast, _nsampsLast, _pipeline, _workerMutex, nidas::util::UTime::format(), nidas::core::SampleStats::getLastTimeTag(), nidas::core::DSMConfig::getName(), nidas::core::SampleStats::getNumBytes(), nidas::core::SamplePipeline::getNumDiscardedProcSamples(), nidas::core::SamplePipeline::getNumDiscardedRawSamples(), nidas::core::SamplePipeline::getNumFutureProcSamples(), nidas::core::SamplePipeline::getNumFutureRawSamples(), nidas::core::SampleStats::getNumSamples(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::DSMService::getProcessorIterator(), nidas::core::SamplePipeline::getRawSampleSource(), nidas::core::SampleSource::getSampleStats(), nidas::core::SamplePipeline::getSorterNumProcBytes(), nidas::core::SamplePipeline::getSorterNumProcBytesMax(), nidas::core::SamplePipeline::getSorterNumProcSamples(), nidas::core::SamplePipeline::getSorterNumRawBytes(), nidas::core::SamplePipeline::getSorterNumRawBytesMax(), nidas::core::SamplePipeline::getSorterNumRawSamples(), nidas::core::ProcessorIterator::hasNext(), nidas::util::Mutex::lock(), nidas::core::ProcessorIterator::next(), printClock(), nidas::core::SampleIOProcessor::printStatus(), and nidas::util::Mutex::unlock().
schedule()
void RawSampleService::schedule (bool optionalProcessing) virtual
Exceptions
nidas::util::Exception
Implements nidas::core::DSMService.
References nidas::core::SampleIOProcessor::connectSource(), nidas::util::Logger::getInstance(), nidas::core::SampleIOProcessor::getName(), nidas::core::DSMSensor::getProcessedSampleSource(), nidas::core::DSMSensor::getRawSampleSource(), nidas::core::SampleSource::getSampleTags(), nidas::core::DSMServer::getSensorIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleIOProcessor::init(), nidas::core::SampleIOProcessor::isOptional(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SensorIterator::next(), nidas::core::SampleInput::requestConnection(), nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
setDSMServer()
void DSMService::setDSMServer (DSMServer * val) virtual inherited
References nidas::core::DSMService::_server.
Referenced by nidas::core::DSMServer::fromDOMElement().
setProcHeapMax()
void nidas::dynld::RawSampleService::setProcHeapMax (size_t val) inline
Set the size of in bytes of the processed SampleSorter.
If the size of the sorter exceeds this value then samples will be discarded.
References _procHeapMax.
Referenced by fromDOMElement().
setProcLateSampleCacheSize()
void nidas::dynld::RawSampleService::setProcLateSampleCacheSize (unsigned int val) inline
Cache this number of samples with potentially anomalous, late time tags in the processed sample sorter.
See SampleSorter::setLateSampleCacheSize(val).
References _procLateSampleCacheSize.
Referenced by fromDOMElement().
setProcSorterLength()
void nidas::dynld::RawSampleService::setProcSorterLength (float val) inline
Set the length of the SampleSorter of processed Samples, in seconds.
References _procSorterLength.
Referenced by fromDOMElement().
setRawHeapMax()
void nidas::dynld::RawSampleService::setRawHeapMax (size_t val) inline
Set the size of in bytes of the raw SampleSorter.
If the size of the sorter exceeds this value then samples will be discarded.
References _rawHeapMax.
Referenced by fromDOMElement().
setRawLateSampleCacheSize()
void nidas::dynld::RawSampleService::setRawLateSampleCacheSize (unsigned int val) inline
Cache this number of samples with potentially anomalous, late time tags in the raw sample sorter.
See SampleSorter::setLateSampleCacheSize(val).
References _rawLateSampleCacheSize.
Referenced by fromDOMElement().
setRawSorterLength()
void nidas::dynld::RawSampleService::setRawSorterLength (float val) inline
Set the length of the SampleSorter of raw Samples, in seconds.
References _rawSorterLength.
Referenced by fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_dsms
std::map<nidas::core::SampleInput*,const nidas::core::DSMConfig*> nidas::dynld::RawSampleService::_dsms private
Referenced by printStatus().
_inputs
std::list<SampleInput*> nidas::core::DSMService::_inputs protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), fromDOMElement(), nidas::core::DSMService::getInputs(), and nidas::core::DSMService::~DSMService().
_name
std::string nidas::core::DSMService::_name protected inherited
Referenced by nidas::core::DSMService::getName().
_nbytesLast
std::map<void*,long long> nidas::dynld::RawSampleService::_nbytesLast private
Saved between calls to printStatus in order to compute sample rates.
Referenced by printStatus().
_nsampsLast
std::map<void*,size_t> nidas::dynld::RawSampleService::_nsampsLast private
Saved between calls to printStatus in order to compute data rates.
Referenced by printStatus().
_ochans
std::list<IOChannel*> nidas::core::DSMService::_ochans protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::~DSMService().
_pipeline
nidas::core::SamplePipeline* nidas::dynld::RawSampleService::_pipeline private
Referenced by printClock(), and printStatus().
_processors
std::list<SampleIOProcessor*> nidas::core::DSMService::_processors protected inherited
Referenced by nidas::core::DSMService::addProcessor(), nidas::core::DSMService::getProcessors(), and nidas::core::DSMService::~DSMService().
_procHeapMax
size_t nidas::dynld::RawSampleService::_procHeapMax private
Referenced by getProcHeapMax(), and setProcHeapMax().
_procLateSampleCacheSize
unsigned int nidas::dynld::RawSampleService::_procLateSampleCacheSize private
Referenced by getProcLateSampleCacheSize(), and setProcLateSampleCacheSize().
_procSorterLength
float nidas::dynld::RawSampleService::_procSorterLength private
Referenced by getProcSorterLength(), and setProcSorterLength().
_rawHeapMax
size_t nidas::dynld::RawSampleService::_rawHeapMax private
Referenced by getRawHeapMax(), and setRawHeapMax().
_rawLateSampleCacheSize
unsigned int nidas::dynld::RawSampleService::_rawLateSampleCacheSize private
Referenced by getRawLateSampleCacheSize(), and setRawLateSampleCacheSize().
_rawSorterLength
float nidas::dynld::RawSampleService::_rawSorterLength private
Referenced by getRawSorterLength(), and setRawSorterLength().
_server
DSMServer* nidas::core::DSMService::_server protected inherited
Referenced by nidas::core::DSMService::getDSMServer(), and nidas::core::DSMService::setDSMServer().
_subThreadMutex
nidas::util::Mutex nidas::core::DSMService::_subThreadMutex protected inherited
Referenced by nidas::core::DSMService::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::DSMService::interrupt(), and nidas::core::DSMService::join().
_subThreads
std::set<nidas::util::Thread*> nidas::core::DSMService::_subThreads protected inherited
Referenced by nidas::core::DSMService::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::DSMService::interrupt(), and nidas::core::DSMService::join().
_threadPolicy
nidas::util::Thread::SchedPolicy nidas::core::DSMService::_threadPolicy protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::getSchedPolicy().
_threadPriority
int nidas::core::DSMService::_threadPriority protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::getSchedPriority().
_workerMutex
nidas::util::Mutex nidas::dynld::RawSampleService::_workerMutex private
Referenced by printStatus().
_workers
std::map<nidas::core::SampleInput*,Worker*> nidas::dynld::RawSampleService::_workers private
Keep track of the Worker for each SampleInput.
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/RawSampleService.h
nidas/dynld/RawSampleService.cc