nidas: nidas::dynld::isff::MOSMote::MOS_TimeSyncer Class Reference
nidas::dynld::isff::MOSMote::MOS_TimeSyncer Class Reference
Public Member Functions
MOS_TimeSyncer (MOSMote *mote)
void looperNotify () throw ()
LooperClient virtual method.
Private Member Functions
MOS_TimeSyncer (const MOS_TimeSyncer &)
MOS_TimeSyncer & operator= (const MOS_TimeSyncer &)
Private Attributes
MOSMote * _mote
Constructor & Destructor Documentation
MOS_TimeSyncer() [1/2]
nidas::dynld::isff::MOSMote::MOS_TimeSyncer::MOS_TimeSyncer (MOSMote * mote) inline
MOS_TimeSyncer() [2/2]
nidas::dynld::isff::MOSMote::MOS_TimeSyncer::MOS_TimeSyncer (const MOS_TimeSyncer &) private
Member Function Documentation
looperNotify()
void MOSMote::MOS_TimeSyncer::looperNotify () throw () virtual
LooperClient virtual method.
Implements nidas::core::LooperClient.
References nidas::util::Logger::getInstance(), nidas::util::getSystemTime(), nidas::util::Logger::log(), LOG_INFO, LOG_WARNING, MSECS_PER_SEC, USECS_PER_MSEC, and nidas::util::Exception::what().
operator=()
MOS_TimeSyncer& nidas::dynld::isff::MOSMote::MOS_TimeSyncer::operator= (const MOS_TimeSyncer &) private
Member Data Documentation
_mote
MOSMote* nidas::dynld::isff::MOSMote::MOS_TimeSyncer::_mote private
The documentation for this class was generated from the following files:
nidas/dynld/isff/MOSMote.h
nidas/dynld/isff/MOSMote.cc