nidas: nidas::core::SampleTagIterator Class Reference
nidas::core::SampleTagIterator Class Reference
Class for iterating over the SampleTags of a Project, Site, DSMConfig, or a SampleSource.
#include <NidsIterators.h>
Public Member Functions
SampleTagIterator (const SampleTagIterator &x)
Copy constructor.
SampleTagIterator & operator= (const SampleTagIterator &x)
SampleTagIterator (const Project *)
SampleTagIterator (const DSMServer *)
SampleTagIterator (const DSMService *)
SampleTagIterator (const Site *)
SampleTagIterator (const DSMConfig *)
SampleTagIterator (const SampleSource *)
SampleTagIterator ()
bool hasNext ()
const SampleTag * next ()
Private Attributes
SensorIterator _sensorIterator
ProcessorIterator _processorIterator
std::list< const SampleTag * > _stags
std::list< const SampleTag * >::const_iterator _sampleTagItr
Detailed Description
Class for iterating over the SampleTags of a Project, Site, DSMConfig, or a SampleSource.
Constructor & Destructor Documentation
SampleTagIterator() [1/8]
nidas::core::SampleTagIterator::SampleTagIterator (const SampleTagIterator & x) inline
Copy constructor.
SampleTagIterator() [2/8]
SampleTagIterator::SampleTagIterator (const Project * obj)
SampleTagIterator() [3/8]
SampleTagIterator::SampleTagIterator (const DSMServer * obj)
SampleTagIterator() [4/8]
nidas::core::SampleTagIterator::SampleTagIterator (const DSMService *)
SampleTagIterator() [5/8]
SampleTagIterator::SampleTagIterator (const Site * obj)
SampleTagIterator() [6/8]
SampleTagIterator::SampleTagIterator (const DSMConfig * obj)
SampleTagIterator() [7/8]
SampleTagIterator::SampleTagIterator (const SampleSource * obj)
SampleTagIterator() [8/8]
SampleTagIterator::SampleTagIterator ()
Member Function Documentation
hasNext()
bool SampleTagIterator::hasNext ()
References _processorIterator, _sampleTagItr, _sensorIterator, _stags, nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::DSMSensor::getSampleTags(), nidas::core::ProcessorIterator::hasNext(), nidas::core::SensorIterator::hasNext(), nidas::core::ProcessorIterator::next(), and nidas::core::SensorIterator::next().
Referenced by nidas::dynld::StatisticsCruncher::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), DataStats::createCounters(), nidas::core::SamplePipeline::disconnect(), nidas::core::CharacterSensor::doesAsciiSscanfs(), nidas::core::Site::findSensor(), nidas::dynld::raf::DSMMesaSensor::fromDOMElement(), nidas::core::Project::getUniqueSampleId(), nidas::core::VariableIterator::hasNext(), nidas::dynld::raf::A2DBoardTempSensor::init(), nidas::dynld::WxtSensor::init(), PConfig::loadVariables(), parseAnalog(), parseOther(), DataPrep::run(), StatsProcess::run(), SampleDispatcher::SampleDispatcher(), DumpClient::setSensors(), PConfig::showAll(), and nidas::core::DSMSensor::toDOMParent().
next()
const SampleTag* nidas::core::SampleTagIterator::next () inline
References _sampleTagItr.
Referenced by nidas::dynld::StatisticsCruncher::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), DataStats::createCounters(), nidas::core::SamplePipeline::disconnect(), nidas::core::Site::findSensor(), nidas::core::Project::getUniqueSampleId(), nidas::core::VariableIterator::hasNext(), DataPrep::run(), StatsProcess::run(), SampleDispatcher::SampleDispatcher(), and DumpClient::setSensors().
operator=()
SampleTagIterator& nidas::core::SampleTagIterator::operator= (const SampleTagIterator & x) inline
References _sampleTagItr, _sensorIterator, and _stags.
Member Data Documentation
_processorIterator
ProcessorIterator nidas::core::SampleTagIterator::_processorIterator private
Referenced by hasNext().
_sampleTagItr
std::list<const SampleTag*>::const_iterator nidas::core::SampleTagIterator::_sampleTagItr private
Referenced by hasNext(), next(), and operator=().
_sensorIterator
SensorIterator nidas::core::SampleTagIterator::_sensorIterator private
Referenced by hasNext(), and operator=().
_stags
std::list<const SampleTag*> nidas::core::SampleTagIterator::_stags private
Referenced by hasNext(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc