nidas: nidas::core::IOChannelRequester Class Reference
nidas::core::IOChannelRequester Class Reference abstract
Interface for an object that requests connections to Inputs or Outputs.
#include <IOChannel.h>
Public Member Functions
virtual ~IOChannelRequester ()
virtual IOChannelRequester * connected (IOChannel *)=0
Detailed Description
Interface for an object that requests connections to Inputs or Outputs.
Constructor & Destructor Documentation
~IOChannelRequester()
virtual nidas::core::IOChannelRequester::~IOChannelRequester () inline virtual
Member Function Documentation
connected()
virtual IOChannelRequester* nidas::core::IOChannelRequester::connected (IOChannel *) pure virtual
Implemented in nidas::dynld::isff::GOESOutput, nidas::dynld::SampleInputStream, nidas::dynld::UDPSampleOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::SampleOutputStream, nidas::core::SampleOutputBase, nidas::dynld::XMLConfigService, and nidas::dynld::XMLConfigAllService.
Referenced by nidas::core::McSocketUDP::connected(), nidas::core::McSocket::connected(), nidas::core::FileSet::mounted(), nidas::core::FileSet::requestConnection(), nidas::core::UnixIOChannel::requestConnection(), and nidas::core::DatagramSocket::requestConnection().
The documentation for this class was generated from the following file:
nidas/core/IOChannel.h