nidas: nidas::core::SocketIODevice Class Reference
nidas::core::SocketIODevice Class Reference abstract
A IODevice providing support for UDP and TCP sockets.
#include <SocketIODevice.h>
Public Member Functions
SocketIODevice ()
Create a SocketIODevice.
~SocketIODevice ()
void open (int flags)
Prepare to open the socket.
void ioctl (int, void *, size_t)
virtual void setName (const std::string &val)
Set the device name to be opened for this sensor.
virtual const std::string & getName () const
virtual int getReadFd () const =0
The file descriptor used when reading from this sensor.
virtual int getWriteFd () const =0
The file descriptor used when writing to this sensor.
virtual size_t read (void *buf, size_t len)=0
Read from the sensor.
virtual size_t read (void *buf, size_t len, int msecTimeout)=0
Read from the sensor with a millisecond timeout.
virtual size_t getBytesAvailable () const
Return how many bytes are available to read on this IODevice.
virtual size_t write (const void *buf, size_t len)=0
Write to the sensor.
virtual void close ()=0
Close the device.
Static Public Member Functions
static void parseAddress (const std::string &name, int &addrtype, std::string &hostname, int &port, std::string &bindaddr)
Parse the getName() string to extract a socket type, destination address and optional port number.
Protected Attributes
int _addrtype
The type of the destination address, AF_INET or AF_UNIX.
std::string _desthost
Destination host name from sensor name.
int _port
Port number that is parsed from sensor name.
nidas::util::auto_ptr< nidas::util::SocketAddress > _sockAddr
The destination socket address.
std::string _bindAddr
The local bind socket address.
Private Attributes
std::string _devname
Whether to reopen this sensor on an IOException.
Detailed Description
A IODevice providing support for UDP and TCP sockets.
Constructor & Destructor Documentation
SocketIODevice()
SocketIODevice::SocketIODevice ()
Create a SocketIODevice.
No IO operations are performed in the constructor, hence no IOExceptions.
~SocketIODevice()
SocketIODevice::~SocketIODevice ()
Member Function Documentation
close()
virtual void nidas::core::IODevice::close () pure virtual inherited
Close the device.
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, and nidas::core::ServerSocketIODevice.
Referenced by nidas::core::DSMSensor::close().
getBytesAvailable()
virtual size_t nidas::core::IODevice::getBytesAvailable () const inline virtual inherited
Return how many bytes are available to read on this IODevice.
This method is only useful when ioctl FIONREAD is supported on this this IODevice, as for example with a UDP socket. It is not available, and not necessary, on most other devices, like serial ports, TCP sockets, or devices with nidas driver module support, in which case it will return an nidas::util::IOException. It is an optimization for use with UDP sockets, where after select determines that data is available on the socket file descriptor, a read will only read one datagram, even if there are more than one packet available, which would not be optimal if a sensor generated many small packets. Rather than returning back to select, we check if there are more datagrams to read. This is not necessary on other types of IODevices, where it is just a matter of using a big enough buffer to get all (or most) available data after a select.
According to man udp(7), FIONREAD will return 0 if the size of the next packet is 0. So, if select/poll indicate there is data available, one read at least should be done, just in case a sensor sends a datagram of length 0, otherwise it will never be consumed.
Exceptions
nidas::util::IOException
References err, nidas::core::IODevice::getName(), nidas::core::IODevice::getReadFd(), and nidas::core::IODevice::ioctl().
Referenced by nidas::core::DSMSensor::getBytesAvailable().
getName()
virtual const std::string& nidas::core::IODevice::getName () const inline virtual inherited
References nidas::core::IODevice::_devname.
Referenced by nidas::core::SerialPortIODevice::applyTermios(), nidas::core::ServerSocketIODevice::close(), nidas::core::TCPSocketIODevice::close(), nidas::core::UDPSocketIODevice::close(), nidas::core::UnixIODevice::close(), nidas::core::IODevice::getBytesAvailable(), nidas::core::UnixIODevice::ioctl(), nidas::core::ServerSocketIODevice::ioctl(), ioctl(), nidas::core::ServerSocketIODevice::open(), open(), nidas::core::UnixIODevice::open(), nidas::core::UnixIODevice::read(), and nidas::core::UnixIODevice::write().
getReadFd()
virtual int nidas::core::IODevice::getReadFd () const pure virtual inherited
The file descriptor used when reading from this sensor.
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, and nidas::core::ServerSocketIODevice.
Referenced by nidas::core::IODevice::getBytesAvailable(), and nidas::core::DSMSensor::getReadFd().
getWriteFd()
virtual int nidas::core::IODevice::getWriteFd () const pure virtual inherited
The file descriptor used when writing to this sensor.
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, and nidas::core::ServerSocketIODevice.
Referenced by nidas::core::DSMSensor::getWriteFd().
ioctl()
void nidas::core::SocketIODevice::ioctl (int , void * , size_t) inline virtual
Implements nidas::core::IODevice.
References nidas::core::IODevice::getName().
open()
void SocketIODevice::open (int flags) virtual
Prepare to open the socket.
This actually just parses the address from the device name, and doesn't actually do a socket connection or bind. See parseAddress(). The connect or bind must be done in the TCPSocketIODevice or UDPSocketIODevice open method. If the name contains a IP hostname and the IP address of that host is not available, then an InvalidParameterException is thrown.
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
Implements nidas::core::IODevice.
Reimplemented in nidas::core::UDPSocketIODevice, and nidas::core::TCPSocketIODevice.
References _addrtype, _bindAddr, _desthost, _port, _sockAddr, nidas::util::Inet4Address::getByName(), nidas::core::IODevice::getName(), parseAddress(), and nidas::util::Exception::what().
Referenced by nidas::core::TCPSocketIODevice::open(), and nidas::core::UDPSocketIODevice::open().
parseAddress()
void SocketIODevice::parseAddress (const std::string & name, int & addrtype, std::string & hostname, int & port, std::string & bindaddr) static
Parse the getName() string to extract a socket type, destination address and optional port number.
The syntax of the set/getName() string is: ("inet" | "sock" | "unix" | "blue" | "btspp") ':' address [:port] "inet" or "sock" indicate a TCP or UDP connection for use by derived classes implementing a TCP or UDP socket. The address field should then be a hostname which can be resolved to an IP address, or an IP address in dot notation. A port number is required for TCP/UDP socket connection. "unix" indicates a Unix socket connection, where address is the path name of the unix socket, for process to process communications. The port value is not used by unix sockets.
Exceptions
nidas::util::ParseException
References port.
Referenced by nidas::core::ServerSocketIODevice::open(), open(), and nidas::dynld::raf::PSI9116_Sensor::open().
read() [1/2]
virtual size_t nidas::core::IODevice::read (void * buf, size_t len) pure virtual inherited
Read from the sensor.
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, and nidas::core::ServerSocketIODevice.
Referenced by nidas::core::DSMSensor::read().
read() [2/2]
virtual size_t nidas::core::IODevice::read (void * buf, size_t len, int msecTimeout) pure virtual inherited
Read from the sensor with a millisecond timeout.
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, and nidas::core::ServerSocketIODevice.
setName()
virtual void nidas::core::IODevice::setName (const std::string & val) inline virtual inherited
Set the device name to be opened for this sensor.
References nidas::core::IODevice::_devname.
Referenced by nidas::core::DSMSensor::open(), and nidas::core::UnixIODevice::UnixIODevice().
write()
virtual size_t nidas::core::IODevice::write (const void * buf, size_t len) pure virtual inherited
Write to the sensor.
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIODevice, nidas::core::UDPSocketIODevice, nidas::core::TCPSocketIODevice, nidas::core::ServerSocketIODevice, and nidas::core::SerialPortIODevice.
Referenced by nidas::core::DSMSensor::write().
Member Data Documentation
_addrtype
int nidas::core::SocketIODevice::_addrtype protected
The type of the destination address, AF_INET or AF_UNIX.
Referenced by open().
_bindAddr
std::string nidas::core::SocketIODevice::_bindAddr protected
The local bind socket address.
Referenced by open().
_desthost
std::string nidas::core::SocketIODevice::_desthost protected
Destination host name from sensor name.
Referenced by open().
_devname
std::string nidas::core::IODevice::_devname private inherited
Whether to reopen this sensor on an IOException.
Referenced by nidas::core::IODevice::getName(), and nidas::core::IODevice::setName().
_port
int nidas::core::SocketIODevice::_port protected
Port number that is parsed from sensor name.
For a server socket this is the local port number to listen on. For a remote connection socket this is the remote port number.
Referenced by open().
_sockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::SocketIODevice::_sockAddr protected
The destination socket address.
Referenced by open(), nidas::core::TCPSocketIODevice::open(), and nidas::core::UDPSocketIODevice::open().
The documentation for this class was generated from the following files:
nidas/core/SocketIODevice.h
nidas/core/SocketIODevice.cc