nidas: TestMesa Class Reference
TestMesa Class Reference abstract
Public Member Functions
IODevice * buildIODevice () throw (n_u::IOException)
Factory method for an IODevice for this DSMSensor.
SampleScanner * buildSampleScanner ()
Factory method for a SampleScanner for this DSMSensor.
void setDSMConfig (const DSMConfig *val)
Set the DSMConfig for this sensor.
const DSMConfig * getDSMConfig () const
What DSMConfig am I associated with?
const Site * getSite () const
What Site am I associated with?
virtual void setDeviceName (const std::string &val)
Set the name of the system device that the sensor is connected to.
virtual const std::string & getDeviceName () const
Fetch the name of the system device that the sensor is connected to.
virtual void setClassName (const std::string &val)
Set the class name.
virtual const std::string & getClassName () const
Fetch the class name.
virtual void setCatalogName (const std::string &val)
Set the name of the catalog entry for this sensor.
virtual const std::string & getCatalogName () const
Fetch the name of the catalog entry for this sensor.
const std::string & getDSMName () const
Fetch the DSM name.
virtual std::string getName () const
Return a name that should fully identify this sensor.
const std::string & getLocation () const
Location string.
void setLocation (const std::string &val)
const std::string & getSuffix () const
Sensor suffix, which is added to variable names.
void setSuffix (const std::string &val)
int getStation () const
void setStation (int val)
void setHeight (const std::string &val)
Set sensor height above ground via a string which is added to variable names.
void setHeight (float val)
Set sensor height above ground.
const std::string & getHeightString () const
Get sensor height above ground in a string.
float getHeight () const
Get sensor height above ground.
void setDepth (const std::string &val)
Set sensor depth below ground via a string which is added to variable names.
void setDepth (float val)
Set sensor depth below ground.
const std::string & getDepthString () const
Get sensor depth below ground in a string.
float getDepth () const
Get sensor depth below ground.
const std::string & getFullSuffix () const
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $HEIGHT.
const Dictionary & getDictionary () const
SampleSource * getRawSampleSource ()
Implementation of SampleSource::getRawSampleSource().
SampleSource * getProcessedSampleSource ()
Implementation of SampleSource::getProcessedSampleSource().
const SampleTag * getRawSampleTag () const
Convenience function to get my one-and-only raw SampleTag().
virtual void addSampleTag (SampleTag *val)
Add a SampleTag to this sensor.
virtual void removeSampleTag (SampleTag *val)
Remove val from the list of SampleTags, and delete it.
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
std::list< SampleTag * > & getSampleTags ()
Non-const method to get a list of non-const pointers to SampleTags.
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush ()
Implementation of SampleClient::flush().
void distributeRaw (const Sample *s)
Distribute a raw sample which has been read from my file descriptor in real time.
const SampleStats & getSampleStats () const
virtual int getReadFd () const
virtual int getWriteFd () const
virtual bool reopenOnIOException () const
Whether to reopen this sensor on an IOException.
void setId (dsm_sample_id_t val)
Set the various levels of the sensor identification.
void setSensorId (unsigned int val)
void setDSMId (unsigned int val)
dsm_sample_id_t getId () const
Get the various levels of the samples identification.
unsigned int getDSMId () const
unsigned int getSensorId () const
virtual void setLatency (float val)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
virtual float getLatency () const
virtual void setTimeoutMsecs (int val)
Set the sensor timeout value in milliseconds.
virtual int getTimeoutMsecs () const
int getTimeoutCount () const
void incrementTimeoutCount ()
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setIODevice (IODevice *val)
Set the IODevice for this sensor.
void setSampleScanner (SampleScanner *val)
Set the SampleScanner for this sensor.
virtual void validate ()
validate() is called once on a DSMSensor after it has been configured, but before open() or init() are called.
virtual void open (int flags)
Open the device.
virtual void init ()
Initialize the DSMSensor.
virtual int getDefaultMode () const
How do I want to be opened.
virtual void setDefaultMode (int val)
virtual size_t getBytesAvailable () const
How many bytes are available to read on this sensor.
virtual size_t read (void *buf, size_t len)
Read from the device (duh).
virtual size_t read (void *buf, size_t len, int msecTimeout)
Read from the device with a timeout.
virtual size_t write (const void *buf, size_t len)
Write to the device (duh).
virtual void ioctl (int request, void *buf, size_t len)
Perform an ioctl on the device.
virtual void close ()
close my associated device.
virtual bool readSamples ()
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
virtual Sample * nextSample ()
Extract the next sample from the buffer.
virtual Sample * readSample ()
Return the next sample.
bool receive (const Sample *s)
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
virtual bool process (const Sample *, std::list< const Sample * > &result)=0
Apply further necessary processing to a raw sample from this DSMSensor.
void printStatusHeader (std::ostream &ostr)
virtual void printStatus (std::ostream &)
void printStatusTrailer (std::ostream &ostr)
void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
float getObservedSamplingRate () const
float getObservedDataRate () const
size_t getBadTimeTagCount () const
VariableIterator getVariableIterator () const
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
virtual void setTypeName (const std::string &val)
Set the type name of this sensor, e.g.
virtual const std::string & getTypeName (void) const
Get the type name of this sensor.
bool getDuplicateIdOK () const
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
void setDuplicateIdOK (bool val)
Set the duplicate ID attribute of this DSMSensor.
virtual bool getApplyVariableConversions () const
virtual void setApplyVariableConversions (bool val)
virtual int getDriverTimeTagUsecs () const
virtual void setDriverTimeTagUsecs (int val)
void addCalFile (CalFile *val)
Add a calibration file for this DSMSensor.
const std::map< std::string, CalFile * > & getCalFiles ()
Return the collection of CalFiles, mapped by name.
CalFile * getCalFile (const std::string &name)
Return a CalFile by its getName().
void removeCalFiles ()
Remove all CalFiles.
virtual void executeXmlRpc (XmlRpc::XmlRpcValue &, XmlRpc::XmlRpcValue &)
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
virtual const std::list< SampleTag * > & getNonConstSampleTags ()
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
bool allowOpen ()
bool readBuffer ()
Read into my SampleScanner's buffer.
bool readBuffer (int msecTimeout)
Read into my SampleScanner's buffer.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *project)
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
static void deleteLooper ()
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void clearBuffer ()
Clear the internal buffer.
IODevice * getIODevice () const
SampleScanner * getSampleScanner () const
void setFullSuffix (const std::string &val)
virtual int getLagUsecs () const
Return the sampling lag for this sensor in microseconds.
virtual double getLagSecs () const
Return the sampling lag for this sensor in seconds.
virtual void setLagSecs (double val)
Set the sampling lag for this sensor in seconds.
void applyConversions (SampleTag *stag, SampleT< float > *outs, float *results=0)
Perform variable conversions for the variables in stag whose values and sample time have been set in outs.
void trimUnparsed (SampleTag *stag, SampleT< float > *outs, int nparsed)
Fill with floatNAN all the values past nparsed values in output sample outs, and trim the length of the sample to match the length of the variables in SampleTag stag.
VariableIndex findVariableIndex (const std::string &vprefix)
Search all the sample tags for a variable whose name starts with the given prefix, and return it's index in the list of variables in the sample tag.
Static Protected Member Functions
static Looper * getLooper ()
Fetch a pointer to a static instance of a Looper thread.
Protected Attributes
bool _openable
Whether this sensor is allowed to be opened.
Private Member Functions
void addSampleTag (const SampleTag *val)
DSMSensor does provide public support for SampleSource::addSampleTag(const SampleTag* val).
void removeSampleTag (const SampleTag *val)
DSMSensor does not provide public support for SampleSource::removeSampleTag(const SampleTag* val)
Private Attributes
std::string _devname
nidas::core::DSMSensor::MyDictionary _dictionary
IODevice * _iodev
int _defaultMode
std::string _className
Class name attribute of this sensor.
std::string _catalogName
std::string _suffix
Sensor suffix, which is added to variable names.
std::string _heightString
std::string _depthString
float _height
std::string _fullSuffix
Concatenation of sensor suffix, and the height or depth string.
std::string _location
SampleScanner * _scanner
const DSMConfig * _dsm
dsm_sample_id_t _id
Id of this sensor.
SampleTag _rawSampleTag
std::list< SampleTag * > _sampleTags
SampleSourceSupport _rawSource
SampleSourceSupport _source
float _latency
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
std::map< std::string, CalFile * > _calFiles
std::string _typeName
int _timeoutMsecs
bool _duplicateIdOK
bool _applyVariableConversions
int _driverTimeTagUsecs
int _nTimeouts
int _lag
int _station
Static Private Attributes
static bool zebra = false
static Looper * _looper = 0
static nidas::util::Mutex _looperMutex
static XMLCh * namespaceURI = 0
Member Function Documentation
addCalFile()
void DSMSensor::addCalFile (CalFile * val) inherited
Add a calibration file for this DSMSensor.
After this method is finished, DSMSensor will own the pointer, and will delete it in the DSMSensor destructor.
References nidas::core::DSMSensor::_calFiles, and nidas::core::CalFile::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
addParameter()
void DSMSensor::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::DSMSensor::_constParameters, nidas::core::DSMSensor::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
addSampleClient()
void nidas::core::DSMSensor::addSampleClient (SampleClient * c) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by nidas::core::SamplePipeline::addSampleClient(), and nidas::core::SamplePipeline::addSampleClientForTag().
addSampleClientForTag()
void nidas::core::DSMSensor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
Referenced by nidas::core::SamplePipeline::addSampleClientForTag().
addSampleTag() [1/2]
void DSMSensor::addSampleTag (const SampleTag * val) private virtual inherited
DSMSensor does provide public support for SampleSource::addSampleTag(const SampleTag* val).
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleSource.
addSampleTag() [2/2]
void DSMSensor::addSampleTag (SampleTag * val) virtual inherited
Add a SampleTag to this sensor.
DSMSensor will own the SampleTag. Throw an exception the DSMSensor cannot support the sample (bad rate, wrong number of variables, etc). Note that a SampleTag may be changed after it has been added. addSampleTag() is called when a sensor is initialized from the sensor catalog. The SampleTag may be modified later if it is overridden in the actual sensor entry. For this reason, it is wise to wait to scan the SampleTags of a DSMSensor in the validate(), init() or open() methods, which are invoked after fromDOMElement.
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::isff::DAUSensor, nidas::dynld::iss::WICORSensor, and nidas::dynld::iss::TiltSensor.
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_source, nidas::core::SampleSourceSupport::addSampleTag(), GET_DSM_ID, GET_SHORT_ID, nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::DSMSensor::getName(), nidas::util::Logger::log(), LOG_WARNING, and nidas::core::SampleTag::setDSMSensor().
Referenced by nidas::dynld::iss::TiltSensor::addSampleTag(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::DAUSensor::addSampleTag(), nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::fromDOMElement(), and main().
allowOpen()
bool nidas::core::DSMSensor::allowOpen () inline inherited
References nidas::core::DSMSensor::_openable.
Referenced by nidas::core::DSMConfig::addSensor().
applyConversions()
void DSMSensor::applyConversions (SampleTag * stag, SampleT< float > * outs, float * results = 0) protected inherited
Perform variable conversions for the variables in stag whose values and sample time have been set in outs.
This method can be used by subclasses to apply any variable conversions associated with the variables in the given SampleTag, using a general algorithm which loops over each value in each variable. The min/max value limits of a variable are applied also, so if a variable value is converted but lies outside the min/max range, the value is set to floatNAN. Typically this can be the last step applied to the output sample of a sensor's process() method, and note that the sample time must already be set in the output sample outs, since that time will be used to look up conversions in calibration files.
If results is non-null, then the converted values are written into results instead of overwriting the values in outs. This is used when one variable's results may be used to filter other variables without replacing the one variable's results. An example is the Ifan variable in the TRH WisardMote. results must point to enough memory to hold all of the values in outs, including for any Variables with multiple values (getLength() > 1).
See Variable::convert().
References nidas::core::Variable::convert(), fp, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::getTimeTag(), and nidas::core::SampleTag::getVariables().
Referenced by nidas::dynld::iss::WICORSensor::process(), and nidas::core::CharacterSensor::process().
buildIODevice()
IODevice* TestMesa::buildIODevice () throw (n_u::IOException) inline virtual
Factory method for an IODevice for this DSMSensor.
Must be implemented by derived classes.
Exceptions
nidas::util::IOException
Implements nidas::core::DSMSensor.
buildSampleScanner()
SampleScanner* TestMesa::buildSampleScanner () inline virtual
Factory method for a SampleScanner for this DSMSensor.
Must be implemented by derived classes.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DSMSensor.
calcStatistics()
void nidas::core::DSMSensor::calcStatistics (unsigned int periodUsec) inline inherited
Update the sensor sampling statistics.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::calcStatistics().
Referenced by nidas::core::SensorHandler::calcStatistics().
clearBuffer()
void nidas::core::DSMSensor::clearBuffer () inline protected inherited
Clear the internal buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::clearBuffer().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), and nidas::dynld::isff::CSAT3_Sonic::sendRateCommand().
close()
void DSMSensor::close () virtual inherited
close my associated device.
Exceptions
nidas::util::IOException;
Reimplemented in nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::VCSEL2_Serial, nidas::dynld::raf::UDPArincSensor, nidas::dynld::raf::TwoD_USB, nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::PIP_Serial, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::AlicatSDI, nidas::dynld::raf::A2DBoardTempSensor, nidas::dynld::isff::MOSMote, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_Event, nidas::dynld::DSC_A2DSensor, nidas::dynld::A2DSensor, and nidas::core::SerialSensor.
References nidas::core::DSMSensor::_iodev, nidas::core::IODevice::close(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getTimeoutCount(), and NLOG.
Referenced by nidas::core::SerialSensor::close(), nidas::dynld::A2DSensor::close(), nidas::dynld::DSC_Event::close(), nidas::dynld::DSC_PulseCounter::close(), nidas::dynld::raf::DSMAnalogSensor::close(), nidas::dynld::raf::DSMArincSensor::close(), nidas::dynld::raf::IRIGSensor::close(), nidas::dynld::raf::PIP_Serial::close(), nidas::dynld::raf::TwoD_USB::close(), nidas::dynld::raf::UDPArincSensor::close(), nidas::core::SensorHandler::run(), and nidas::core::SensorOpener::run().
deleteLooper()
void DSMSensor::deleteLooper () static inherited
References nidas::core::DSMSensor::_looper, and nidas::core::DSMSensor::_looperMutex.
Referenced by nidas::core::DSMEngine::main().
distributeRaw()
void nidas::core::DSMSensor::distributeRaw (const Sample * s) inline inherited
Distribute a raw sample which has been read from my file descriptor in real time.
References nidas::core::DSMSensor::_rawSource, and nidas::core::SampleSourceSupport::distribute().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
executeXmlRpc()
virtual void nidas::core::DSMSensor::executeXmlRpc (XmlRpc::XmlRpcValue & , XmlRpc::XmlRpcValue &) inline virtual inherited
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
The default base class method does nothing.
Reimplemented in nidas::dynld::raf::PSI9116_Sensor, and nidas::dynld::raf::DSMAnalogSensor.
Referenced by nidas::core::DSMEngineIntf::SensorAction::execute().
expandString()
std::string nidas::core::DSMSensor::expandString (const std::string & input) const inline inherited
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References nidas::core::DSMSensor::_dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::CalFile::open().
findVariableIndex()
VariableIndex DSMSensor::findVariableIndex (const std::string & vprefix) protected inherited
Search all the sample tags for a variable whose name starts with the given prefix, and return it's index in the list of variables in the sample tag.
If no such variable is found, return -1.
References nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTags(), and nidas::core::SampleTag::getVariables().
flush()
void nidas::core::DSMSensor::flush () inline virtual inherited
Implementation of SampleClient::flush().
This is where a DSMSensor's process() method could send out any buffered results that might be ready.
Implements nidas::core::SampleClient.
Referenced by nidas::dynld::psql::PSQLProcessor::disconnect().
fromDOMElement()
void DSMSensor::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::LamsSensor, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::Wind2D, nidas::dynld::isff::DAUSensor, nidas::core::SerialSensor, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::DSMArincSensor, and nidas::dynld::raf::Arinc_IRS.
References nidas::core::DSMSensor::_dictionary, nidas::core::DSMSensor::_rawSampleTag, nidas::core::DSMSensor::_rawSource, nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::addCalFile(), nidas::core::DSMSensor::addParameter(), nidas::core::SampleSourceSupport::addSampleTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::Parameter::createParameter(), nidas::core::DSMSensor::expandString(), nidas::core::SensorCatalog::find(), nidas::core::Parameter::FLOAT_PARAM, nidas::core::SampleTag::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMSensor::getApplyVariableConversions(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDefaultMode(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::SampleTag::getDSMId(), nidas::core::DSMSensor::getFullSuffix(), nidas::core::DSMSensor::getId(), nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::Parameter::getLength(), nidas::core::DSMSensor::getName(), nidas::core::Parameter::getName(), nidas::core::Variable::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMConfig::getProject(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTags(), nidas::core::Project::getSensorCatalog(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::getSite(), nidas::core::SampleTag::getSpSId(), nidas::core::DSMSensor::getStation(), nidas::core::DSMSensor::getSuffix(), nidas::core::Parameter::getType(), nidas::core::XDOMAttr::getValue(), nidas::core::DSMSensor::getVariableIterator(), nidas::core::VariableIterator::hasNext(), nidas::core::Parameter::INT_PARAM, nidas::util::Logger::log(), LOG_WARNING, MSECS_PER_SEC, nidas::core::VariableIterator::next(), nidas::core::DSMSensor::setApplyVariableConversions(), nidas::core::DSMSensor::setCatalogName(), nidas::core::DSMSensor::setClassName(), nidas::core::DSMSensor::setDefaultMode(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setDeviceName(), nidas::core::SampleTag::setDSMConfig(), nidas::core::SampleTag::setDSMId(), nidas::core::CalFile::setDSMSensor(), nidas::core::SampleTag::setDSMSensor(), nidas::core::DSMSensor::setDuplicateIdOK(), nidas::core::DSMSensor::setHeight(), nidas::core::DSMSensor::setLagSecs(), nidas::core::DSMSensor::setLatency(), nidas::core::DSMSensor::setLocation(), nidas::core::SampleTag::setRate(), nidas::core::SampleTag::setSampleId(), nidas::core::DSMSensor::setSensorId(), nidas::core::SampleTag::setSensorId(), nidas::core::DSMSensor::setStation(), nidas::core::SampleTag::setStation(), nidas::core::DSMSensor::setSuffix(), nidas::core::SampleTag::setSuffix(), nidas::core::DSMSensor::setTimeoutMsecs(), nidas::core::DSMSensor::setTypeName(), and nidas::util::Exception::what().
Referenced by nidas::core::CharacterSensor::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), and nidas::core::DSMConfig::sensorFromDOMElement().
getApplyVariableConversions()
virtual bool nidas::core::DSMSensor::getApplyVariableConversions () const inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), and nidas::dynld::raf::SppSerial::validate().
getBadTimeTagCount()
size_t nidas::core::DSMSensor::getBadTimeTagCount () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getBadTimeTagCount().
Referenced by nidas::core::DSMSensor::printStatus().
getBytesAvailable()
virtual size_t nidas::core::DSMSensor::getBytesAvailable () const inline virtual inherited
How many bytes are available to read on this sensor.
See also
IODevice::getBytesAvailable().
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getBytesAvailable().
Referenced by nidas::core::DatagramSampleScanner::readBuffer().
getCalFile()
CalFile * DSMSensor::getCalFile (const std::string & name) inherited
Return a CalFile by its getName().
Will return NULL if not found.
References nidas::core::DSMSensor::_calFiles.
getCalFiles()
const std::map<std::string,CalFile*>& nidas::core::DSMSensor::getCalFiles () inline inherited
Return the collection of CalFiles, mapped by name.
References nidas::core::DSMSensor::_calFiles.
Referenced by sensorTitle(), and PConfig::showCalFiles().
getCatalogName()
virtual const std::string& nidas::core::DSMSensor::getCatalogName () const inline virtual inherited
Fetch the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by SampleCounter::collectMetadata(), ExtractFast2D::countParticles(), SampleToDatabase::defaultMeasurementName(), parseOther(), nidas::core::DSMSensor::printStatus(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), and PConfig::showCalFiles().
getClassName() [1/2]
virtual const std::string& nidas::core::DSMSensor::getClassName () const inline virtual inherited
Fetch the class name.
References nidas::core::DSMSensor::_className.
Referenced by SampleCounter::collectMetadata(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getClassName(), parseAnalog(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), PConfig::showAll(), PConfig::showCalFiles(), PConfig::showSensorClasses(), and nidas::dynld::raf::UDPArincSensor::~UDPArincSensor().
getClassName() [2/2]
const string DSMSensor::getClassName (const xercesc::DOMElement * node, const Project * project) static inherited
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::Project::expandString(), nidas::core::SensorCatalog::find(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMSensor::getClassName(), and nidas::core::Project::getSensorCatalog().
getClientCount()
int nidas::core::DSMSensor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getClientCount().
getDefaultMode()
virtual int nidas::core::DSMSensor::getDefaultMode () const inline virtual inherited
How do I want to be opened.
The user can ignore it if they want to.
Returns
one of O_RDONLY, O_WRONLY or O_RDWR.
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::SensorOpener::run().
getDepth()
float nidas::core::DSMSensor::getDepth () const inline inherited
Get sensor depth below ground.
Returns
Depth of sensor below ground, in meters.
References nidas::core::DSMSensor::_height.
getDepthString()
const std::string& nidas::core::DSMSensor::getDepthString () const inline inherited
Get sensor depth below ground in a string.
Returns
Depth of sensor below ground, e.g. "5cm".
References nidas::core::DSMSensor::_depthString.
Referenced by SampleCounter::collectMetadata().
getDeviceName()
virtual const std::string& nidas::core::DSMSensor::getDeviceName () const inline virtual inherited
Fetch the name of the system device that the sensor is connected to.
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::SensorHandler::add(), nidas::core::CharacterSensor::buildIODevice(), nidas::core::SerialSensor::buildIODevice(), nidas::core::CharacterSensor::buildSampleScanner(), nidas::core::DSMSensor::close(), SampleCounter::collectMetadata(), DataStats::createCounters(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::open(), nidas::core::SerialSensor::open(), nidas::dynld::raf::UDPArincSensor::open(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), DmdA2dCk::run(), nidas::core::CharacterSensor::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), PConfig::showCalFiles(), and nidas::core::DSMSensor::validate().
getDictionary()
const Dictionary& nidas::core::DSMSensor::getDictionary () const inline inherited
References nidas::core::DSMSensor::_dictionary.
Referenced by nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::VariableConverter::fromDOMElement().
getDriverTimeTagUsecs()
virtual int nidas::core::DSMSensor::getDriverTimeTagUsecs () const inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::core::DriverSampleScanner::nextSample().
getDSMConfig()
const DSMConfig* nidas::core::DSMSensor::getDSMConfig () const inline inherited
What DSMConfig am I associated with?
References nidas::core::DSMSensor::_dsm.
Referenced by SampleCounter::collectMetadata(), DataStats::createCounters(), nidas::core::DSMSensor::fromDOMElement(), SampleCounter::generateStreamId(), nidas::core::VariableConverter::getDSMConfig(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), nidas::core::SampleTag::setDSMSensor(), and nidas::core::DSMSensor::validate().
getDSMId()
unsigned int nidas::core::DSMSensor::getDSMId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_DSM_ID.
Referenced by nidas::core::Site::findSensor(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::core::SampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), sensorTitle(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::Site::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), and nidas::core::MessageStreamScanner::warnNonIncrTimeTag().
getDSMName()
const std::string & DSMSensor::getDSMName () const inherited
Fetch the DSM name.
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getName().
Referenced by nidas::core::DSMSensor::getName().
getDuplicateIdOK()
bool nidas::core::DSMSensor::getDuplicateIdOK () const inline inherited
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
That other sensor must also agree that dupicateIdOK are OK. This can be useful if one may not be certain of the device name, e.g. /dev/ttyUSB*, that the system will assign to a sensor may use, but there are identifiers in the data returned that allow one to sort things out. In general, getDuplicateID is false.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getFullSuffix()
const std::string& nidas::core::DSMSensor::getFullSuffix () const inline inherited
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
The full sensor suffix are words 2 and 3 in the dot-separated name: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::fromDOMElement().
getHeight()
float nidas::core::DSMSensor::getHeight () const inline inherited
Get sensor height above ground.
Returns
Height of sensor above ground, in meters. Nan if unknown.
References nidas::core::DSMSensor::_height.
getHeightString()
const std::string& nidas::core::DSMSensor::getHeightString () const inline inherited
Get sensor height above ground in a string.
Returns
Height of sensor above ground, e.g. "15m".
References nidas::core::DSMSensor::_heightString.
Referenced by SampleCounter::collectMetadata(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), ARLIngest::prepareHeaderIds(), SampleToDatabase::SampleToDatabase(), and PConfig::showCalFiles().
getId()
dsm_sample_id_t nidas::core::DSMSensor::getId () const inline inherited
Get the various levels of the samples identification.
A sample tag ID is a 32-bit value comprised of four parts: 6-bit sample type id(not used by DSMSensor), a 10-bit DSM id, 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and GET_FULL_ID.
Referenced by DataStats::createCounters(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::TimetagAdjuster::log(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::dynld::raf::DSMArincSensor::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), nidas::dynld::raf::SPP300_Serial::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::DSMArincSensor::processAlta(), nidas::core::SampleTag::SampleTag(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getIODevice()
IODevice* nidas::core::DSMSensor::getIODevice () const inline protected inherited
References nidas::core::DSMSensor::_iodev.
getLagSecs()
virtual double nidas::core::DSMSensor::getLagSecs () const inline protected virtual inherited
Return the sampling lag for this sensor in seconds.
See getLagUsecs().
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
getLagUsecs()
virtual int nidas::core::DSMSensor::getLagUsecs () const inline protected virtual inherited
Return the sampling lag for this sensor in microseconds.
A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. Derived classes can use this method in their process method to correct for inherent, constant, sampling lags of a sensor. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
<sensor>
    <parameter name="lag" type = "float" value="0.186"/>
</sensor>
The DSMSensor::fromDOM() method parses this parameter and sets the value of the lag.
References nidas::core::DSMSensor::_lag.
Referenced by nidas::core::CharacterSensor::adjustTimeTag(), and nidas::dynld::raf::UHSAS_Serial::process().
getLatency()
virtual float nidas::core::DSMSensor::getLatency () const inline virtual inherited
References nidas::core::DSMSensor::_latency.
getLocation()
const std::string & DSMSensor::getLocation () const inherited
Location string.
A DSMConfig also has a Location. If the location has not been set for this DSMSensor, then the location of the DSMConfig will be returned.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMSensor::_location, and nidas::core::DSMConfig::getLocation().
Referenced by SampleCounter::collectMetadata(), and nidas::core::DSMSensor::printStatusHeader().
getLooper()
Looper * DSMSensor::getLooper () static protected inherited
Fetch a pointer to a static instance of a Looper thread.
Use this Looper for periodic callbacks, as for prompting, in support of a DSMSensor.
References nidas::core::DSMSensor::_looper, nidas::core::DSMSensor::_looperMutex, nidas::util::Logger::getInstance(), nidas::util::Thread::getPolicyString(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::setThreadScheduler(), and nidas::util::Exception::what().
Referenced by nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
getMaxSampleLength()
unsigned int nidas::core::DSMSensor::getMaxSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMaxSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
getMinSampleLength()
unsigned int nidas::core::DSMSensor::getMinSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMinSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
getName()
virtual std::string nidas::core::DSMSensor::getName () const inline virtual inherited
Return a name that should fully identify this sensor.
This name could be used in informative messages. The returned name has this format: dsmName:deviceName.
References nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::getDSMName().
Referenced by nidas::core::SensorHandler::add(), nidas::core::SamplePipeline::addSampleClient(), nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::SerialSensor::buildSampleScanner(), nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::Arinc_IRS::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::core::SensorHandler::PolledDSMSensor::getName(), nidas::core::SensorHandler::incrementFullBufferReads(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::core::TimetagAdjuster::log(), nidas::core::SerialSensor::open(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::AlicatSDI::open(), nidas::dynld::raf::PIP_Serial::open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::UHSAS_Serial::open(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::core::DSMSensor::printStatusHeader(), nidas::dynld::raf::UDPArincSensor::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::SampleScanner::readBuffer(), nidas::core::DatagramSampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), nidas::core::SensorOpener::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::PIP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), nidas::dynld::raf::TwoD_USB::sendTrueAirspeed(), nidas::core::DSMConfig::sensorFromDOMElement(), nidas::dynld::A2DSensor::setA2DParameters(), nidas::dynld::A2DSensor::setConversionCorrection(), nidas::core::CharacterSensor::setMessageParameters(), nidas::core::RemoteSerialConnection::setSensor(), PConfig::showAll(), nidas::core::CharacterSensor::startPrompting(), nidas::core::CharacterSensor::stopPrompting(), nidas::dynld::isff::CSAT3_Sonic::terminalMode(), nidas::core::CharacterSensor::validate(), nidas::core::DSMSensor::validate(), nidas::core::Site::validate(), nidas::dynld::A2DSensor::validate(), nidas::dynld::raf::AlicatSDI::validate(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::PIP_Serial::validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), nidas::dynld::raf::UDPArincSensor::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::CharacterSensor::validateSscanfs(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), nidas::core::MessageStreamScanner::warnNonIncrTimeTag(), nidas::dynld::WxtSensor::wxtValidateSscanfs(), and nidas::dynld::raf::UHSAS_Serial::~UHSAS_Serial().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getNonConstSampleTags()
virtual const std::list<SampleTag*>& nidas::core::DSMSensor::getNonConstSampleTags () inline virtual inherited
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
References nidas::core::DSMSensor::_sampleTags.
getObservedDataRate()
float nidas::core::DSMSensor::getObservedDataRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedDataRate().
Referenced by nidas::core::DSMSensor::printStatus().
getObservedSamplingRate()
float nidas::core::DSMSensor::getObservedSamplingRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedSamplingRate().
Referenced by nidas::core::DSMSensor::printStatus().
getParameter()
const Parameter * DSMSensor::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::DSMSensor::_parameters.
Referenced by nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::dynld::raf::UHSAS_Serial::open(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), nidas::dynld::raf::AlicatSDI::validate(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::PIP_Serial::validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::raf::UDPArincSensor::validate().
getParameters()
const std::list<const Parameter*>& nidas::core::DSMSensor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::DSMSensor::_constParameters.
Referenced by nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), and nidas::dynld::A2DSensor::validate().
getProcessedSampleSource()
SampleSource* nidas::core::DSMSensor::getProcessedSampleSource () inline virtual inherited
Implementation of SampleSource::getProcessedSampleSource().
Return the SampleSource for processed samples from this DSMSensor.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::RawSampleService::schedule().
getRawSampleSource()
SampleSource* nidas::core::DSMSensor::getRawSampleSource () inline virtual inherited
Implementation of SampleSource::getRawSampleSource().
Return the SampleSource for raw samples from this DSMSensor. A DSMSensor is only a SampleSource of raw samples when running in real-time, not during post-processing.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_rawSource.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::dynld::RawSampleService::schedule(), and nidas::core::RemoteSerialConnection::setSensor().
getRawSampleTag()
const SampleTag* nidas::core::DSMSensor::getRawSampleTag () const inline inherited
Convenience function to get my one-and-only raw SampleTag().
Equivalent to: getRawSampleSource()->getSampleTags()->front()
References nidas::core::DSMSensor::_rawSampleTag.
Referenced by nidas::core::SamplePipeline::addSampleClient(), nidas::core::SamplePipeline::addSampleClientForTag(), nidas::dynld::RawSampleService::connect(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::dynld::raf::SyncServer::initSensors(), nidas::core::SamplePipeline::removeSampleClient(), nidas::core::SamplePipeline::removeSampleClientForTag(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
getReadFd()
virtual int nidas::core::DSMSensor::getReadFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getReadFd().
Referenced by nidas::core::SensorHandler::PolledDSMSensor::getFd(), nidas::core::SerialSensor::open(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), and nidas::core::SampleScanner::readBuffer().
getSampleScanner()
SampleScanner* nidas::core::DSMSensor::getSampleScanner () const inline protected inherited
References nidas::core::DSMSensor::_scanner.
Referenced by nidas::core::CharacterSensor::getNullTerminated(), and nidas::core::CharacterSensor::setMessageParameters().
getSampleStats()
const SampleStats& nidas::core::DSMSensor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::DSMSensor::getSampleTagIterator () const inline virtual inherited
Implements nidas::core::SampleSource.
Referenced by nidas::core::SamplePipeline::connect(), DataStats::createCounters(), nidas::core::SamplePipeline::disconnect(), nidas::core::CharacterSensor::doesAsciiSscanfs(), nidas::core::Site::findSensor(), nidas::dynld::WxtSensor::init(), PConfig::loadVariables(), parseAnalog(), parseOther(), DataPrep::run(), StatsProcess::run(), SampleDispatcher::SampleDispatcher(), DumpClient::setSensors(), PConfig::showAll(), and nidas::core::DSMSensor::toDOMParent().
getSampleTags() [1/2]
std::list<SampleTag*>& nidas::core::DSMSensor::getSampleTags () inline inherited
Non-const method to get a list of non-const pointers to SampleTags.
References nidas::core::DSMSensor::_sampleTags.
getSampleTags() [2/2]
std::list<const SampleTag*> nidas::core::DSMSensor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::iss::WICORSensor::addSampleTag(), nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::DSMSensor::findVariableIndex(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), PConfig::showCalFiles(), nidas::core::CharacterSensor::validate(), nidas::dynld::A2DSensor::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
getSensorId()
unsigned int nidas::core::DSMSensor::getSensorId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_SPS_ID.
Referenced by SampleToDatabase::defaultMeasurementName(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::CSAT3_Sonic::open(), ARLIngest::prepareHeaderIds(), nidas::core::SampleScanner::readBuffer(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::DSMArincSensor::registerWithUDPArincSensor(), sensorTitle(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::DSMSensor::validate(), nidas::core::Site::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::MessageStreamScanner::warnBackwardsStepTimeTag(), and nidas::core::MessageStreamScanner::warnNonIncrTimeTag().
getSite()
const Site * DSMSensor::getSite () const inherited
What Site am I associated with?
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getSite().
Referenced by SampleCounter::collectMetadata(), and nidas::core::DSMSensor::fromDOMElement().
getStation()
int nidas::core::DSMSensor::getStation () const inline inherited
References nidas::core::DSMSensor::_station.
Referenced by nidas::core::DSMSensor::fromDOMElement().
getSuffix()
const std::string& nidas::core::DSMSensor::getSuffix () const inline inherited
Sensor suffix, which is added to variable names.
It is only necessary to have a sensor suffix to make variable names unique. For example, if there are multiple sensors at the same height, with common variable names, then one can use a sensor suffix to make unique names. The sensor suffix is the second dot-separated word in a variable name, where only the first word is required: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_suffix.
Referenced by ExtractFast2D::countParticles(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), ExtractFast2D::run(), ExtractDMT::run(), sensorTitle(), nidas::core::DSMSensor::setDepth(), and nidas::core::DSMSensor::setHeight().
getTimeoutCount()
int nidas::core::DSMSensor::getTimeoutCount () const inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::DSMSensor::close().
getTimeoutMsecs()
virtual int nidas::core::DSMSensor::getTimeoutMsecs () const inline virtual inherited
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs(), and nidas::core::RemoteSerialConnection::setSensor().
getTokenValue()
bool nidas::core::DSMSensor::getTokenValue (const std::string & token, std::string & value) const inline inherited
Implement a lookup for tokens that I know about, like $HEIGHT.
For other tokens, call getDSMConfig()->getTokenValue(token,value);
References nidas::core::DSMSensor::_dictionary, and nidas::core::DSMSensor::MyDictionary::getTokenValue().
getTypeName()
virtual const std::string& nidas::core::DSMSensor::getTypeName (void) const inline virtual inherited
Get the type name of this sensor.
References nidas::core::DSMSensor::_typeName.
getVariableIterator()
VariableIterator DSMSensor::getVariableIterator () const inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), DataPrep::matchVariables(), and nidas::core::Site::validate().
getWriteFd()
virtual int nidas::core::DSMSensor::getWriteFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getWriteFd().
Referenced by main(), and nidas::core::SerialSensor::open().
incrementTimeoutCount()
void nidas::core::DSMSensor::incrementTimeoutCount () inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::SensorOpener::run().
init()
void DSMSensor::init () virtual inherited
Initialize the DSMSensor.
This method is called on a DSMSensor after it is fully configured, and before the process method is called. This is where a DSMSensor should do any required initialization of anything that is used by the process() method. If processed samples are not requested from this DSMSensor, then NIDAS apps typically do not call init().
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::WxtSensor, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::TwoD_USB, nidas::dynld::raf::SidsNetSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::A2DBoardTempSensor, nidas::dynld::raf::A2D_Serial, nidas::dynld::ParoSci_202BG_T, nidas::dynld::ParoSci_202BG_P, nidas::dynld::isff::DAUSensor, nidas::dynld::IEEE_Float, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_Event, nidas::dynld::A2DSensor, and nidas::core::CharacterSensor.
Referenced by nidas::core::DSMEngine::connectProcessors(), nidas::core::CharacterSensor::init(), nidas::dynld::A2DSensor::init(), nidas::dynld::DSC_Event::init(), nidas::dynld::DSC_FreqCounter::init(), nidas::dynld::DSC_PulseCounter::init(), nidas::dynld::raf::A2DBoardTempSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::core::DSMConfig::initSensors(), nidas::dynld::raf::SyncServer::initSensors(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
ioctl()
virtual void nidas::core::DSMSensor::ioctl (int request, void * buf, size_t len) inline virtual inherited
Perform an ioctl on the device.
request is an integer value which must be supported by the device. Normally this is a value from a header file for the device.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, nidas::core::IODevice::ioctl(), and len.
Referenced by nidas::dynld::raf::IRIGSensor::checkClock(), nidas::dynld::raf::IRIGSensor::getIRIGTime(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::raf::TwoD_USB::open(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::dynld::raf::TwoD_USB::sendTrueAirspeed(), and nidas::dynld::raf::IRIGSensor::setIRIGTime().
nextSample()
virtual Sample* nidas::core::DSMSensor::nextSample () inline virtual inherited
Extract the next sample from the buffer.
Returns a null pointer if there are no samples left in the buffer.
Reimplemented in nidas::dynld::raf::UDPArincSensor, and nidas::dynld::raf::A2D_Serial.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::nextSample().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::raf::A2D_Serial::nextSample(), nidas::dynld::raf::UDPArincSensor::nextSample(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::DSMSensor::readSample(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
open()
void DSMSensor::open (int flags) virtual inherited
Open the device.
flags are a combination of O_RDONLY, O_WRONLY.
Exceptions
nidas::util::IOException,nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::VCSEL2_Serial, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::UDPArincSensor, nidas::dynld::raf::TwoD_USB, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::PIP_Serial, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::CVI_LV_Input, nidas::dynld::raf::AlicatSDI, nidas::dynld::raf::A2DBoardTempSensor, nidas::dynld::raf::A2D_Serial, nidas::dynld::isff::MOSMote, nidas::dynld::isff::CSI_IRGA_Sonic, nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::IR104_Relays, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_Event, nidas::dynld::DSC_A2DSensor, nidas::dynld::A2DSensor, nidas::core::SerialSensor, and nidas::core::CharacterSensor.
References nidas::core::DSMSensor::_iodev, nidas::core::DSMSensor::_scanner, nidas::core::DSMSensor::buildIODevice(), nidas::core::DSMSensor::buildSampleScanner(), nidas::core::DSMSensor::getDeviceName(), nidas::core::SampleScanner::init(), NLOG, nidas::core::IODevice::open(), and nidas::core::IODevice::setName().
Referenced by nidas::core::CharacterSensor::open(), nidas::dynld::A2DSensor::open(), nidas::dynld::DSC_Event::open(), nidas::dynld::DSC_FreqCounter::open(), nidas::dynld::DSC_PulseCounter::open(), nidas::dynld::IR104_Relays::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::raf::IRIGSensor::open(), nidas::dynld::raf::TwoD_USB::open(), and nidas::core::SensorOpener::run().
printStatus()
void DSMSensor::printStatus (std::ostream & ostr) virtual inherited
Reimplemented in nidas::dynld::raf::UDPArincSensor, nidas::dynld::raf::TwoD_USB, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::A2D_Serial, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_Event, nidas::dynld::DSC_A2DSensor, and nidas::core::SerialSensor.
References nidas::core::DSMSensor::getBadTimeTagCount(), nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getMaxSampleLength(), nidas::core::DSMSensor::getMinSampleLength(), nidas::core::DSMSensor::getObservedDataRate(), nidas::core::DSMSensor::getObservedSamplingRate(), and nidas::core::DSMSensor::zebra.
Referenced by nidas::core::SerialSensor::printStatus(), nidas::dynld::DSC_A2DSensor::printStatus(), nidas::dynld::DSC_Event::printStatus(), nidas::dynld::DSC_FreqCounter::printStatus(), nidas::dynld::DSC_PulseCounter::printStatus(), nidas::dynld::raf::DSMAnalogSensor::printStatus(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::dynld::raf::IRIGSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::dynld::raf::UDPArincSensor::printStatus(), and nidas::core::DSMEngineStat::run().
printStatusHeader()
void DSMSensor::printStatusHeader (std::ostream & ostr) inherited
References nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::zebra.
Referenced by nidas::core::DSMEngineStat::run().
printStatusTrailer()
void DSMSensor::printStatusTrailer (std::ostream & ostr) inherited
Referenced by nidas::core::DSMEngineStat::run().
process()
virtual bool nidas::core::DSMSensor::process (const Sample * , std::list< const Sample * > & result) pure virtual inherited
Apply further necessary processing to a raw sample from this DSMSensor.
Return the resultant sample(s) in result. The default implementation of process() simply puts the input Sample into result.
Implemented in nidas::dynld::WxtSensor, nidas::dynld::TSI_CPC3772, nidas::dynld::raf::Watlow, nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::UDPArincSensor, nidas::dynld::raf::TwoD_House, nidas::dynld::raf::TwoD64_USB, nidas::dynld::raf::TwoD32_USB, nidas::dynld::raf::SPP300_Serial, nidas::dynld::raf::SPP200_Serial, nidas::dynld::raf::SPP100_Serial, nidas::dynld::raf::SidsNetSensor, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::PIP_Serial, nidas::dynld::raf::PIP_Image, nidas::dynld::raf::PHIPS_UDP, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::LamsNetSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::CVI_LV_Input, nidas::dynld::raf::CDP_Serial, nidas::dynld::raf::BCPD_Serial, nidas::dynld::raf::A2D_Serial, nidas::dynld::isff::MOSMote, nidas::dynld::isff::DAUSensor, nidas::dynld::isff::CSI_IRGA_Sonic, nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::IEEE_Float, nidas::dynld::GPS_Novatel_Serial, nidas::dynld::GPS_NMEA_Serial, nidas::dynld::raf::IRIGSensor, nidas::dynld::isff::WisardMote, nidas::dynld::A2DSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::A2DBoardTempSensor, nidas::dynld::ParoSci_202BG_T, nidas::dynld::ParoSci_202BG_P, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_Event, and nidas::core::CharacterSensor.
Referenced by nidas::core::DSMSensor::receive().
read() [1/2]
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len) inline virtual inherited
Read from the device (duh).
Behaves like the read(2) system call, without a file descriptor argument, and with an IOException.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
Referenced by main(), nidas::core::SampleScanner::readBuffer(), nidas::core::DatagramSampleScanner::readBuffer(), and nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck().
read() [2/2]
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len, int msecTimeout) inline virtual inherited
Read from the device with a timeout.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
readBuffer() [1/2]
bool nidas::core::DSMSensor::readBuffer () inline inherited
Read into my SampleScanner's buffer.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::core::DSMSensor::readSample(), nidas::core::DSMSensor::readSamples(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
readBuffer() [2/2]
bool nidas::core::DSMSensor::readBuffer (int msecTimeout) inline inherited
Read into my SampleScanner's buffer.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
readSample()
Sample * DSMSensor::readSample () virtual inherited
Return the next sample.
Buffer(s) will be read if necessary.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
Referenced by DmdA2dCk::run().
readSamples()
bool DSMSensor::readSamples () virtual inherited
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
This method is called by SensorHander, when select/poll indicates that data is available on the file descriptor returned by getReadFd(). This is a convienence method which does a readBuffer() to read available data from the DSMSensor into a buffer, and then repeatedly calls nextSample() to extract all samples out of that buffer.
Exceptions
nidas::util::IOException;
References nidas::core::DSMSensor::_rawSource, nidas::core::SampleSourceSupport::distribute(), DLOG, nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getName(), nidas::core::Project::getName(), nidas::core::DSMConfig::getProject(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
Referenced by DmdA2dCk::run().
receive()
bool DSMSensor::receive (const Sample * s) virtual inherited
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
In real-time operations, a DSMSensor can be added as a raw SampleClient of itself, using addRawSampleClient(). In post-processing, a DSMSensor typically receives samples with its own sample id from a SampleSorter. receive() then applies further processing via the process() method.
Implements nidas::core::SampleClient.
References nidas::core::DSMSensor::_source, nidas::core::SampleSourceSupport::distribute(), and nidas::core::DSMSensor::process().
removeCalFiles()
void DSMSensor::removeCalFiles () inherited
Remove all CalFiles.
References nidas::core::DSMSensor::_calFiles.
Referenced by nidas::core::DSMSensor::~DSMSensor().
removeSampleClient()
void nidas::core::DSMSensor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by nidas::core::SamplePipeline::removeSampleClient(), and nidas::core::SamplePipeline::removeSampleClientForTag().
removeSampleClientForTag()
void nidas::core::DSMSensor::removeSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
Referenced by nidas::core::SamplePipeline::removeSampleClientForTag().
removeSampleTag() [1/2]
void DSMSensor::removeSampleTag (const SampleTag * val) private virtual inherited
DSMSensor does not provide public support for SampleSource::removeSampleTag(const SampleTag* val)
Exceptions
Implements nidas::core::SampleSource.
removeSampleTag() [2/2]
void DSMSensor::removeSampleTag (SampleTag * val) virtual inherited
Remove val from the list of SampleTags, and delete it.
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleTag().
reopenOnIOException()
virtual bool nidas::core::DSMSensor::reopenOnIOException () const inline virtual inherited
Whether to reopen this sensor on an IOException.
The base method returns true. Over-ride if a reopen should not be attempted.
setApplyVariableConversions()
virtual void nidas::core::DSMSensor::setApplyVariableConversions (bool val) inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setCatalogName()
virtual void nidas::core::DSMSensor::setCatalogName (const std::string & val) inline virtual inherited
Set the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setClassName()
virtual void nidas::core::DSMSensor::setClassName (const std::string & val) inline virtual inherited
Set the class name.
In the usual usage this method is not used, and getClassName() is over-ridden in a derived class to return a constant string.
References nidas::core::DSMSensor::_className.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setDefaultMode()
virtual void nidas::core::DSMSensor::setDefaultMode (int val) inline virtual inherited
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SerialSensor::SerialSensor(), and nidas::dynld::raf::TwoD_USB::TwoD_USB().
setDepth() [1/2]
void DSMSensor::setDepth (const std::string & val) inherited
Set sensor depth below ground via a string which is added to variable names.
Parameters
val String containing sensor below and units in meters (m) or centimeters(cm), e.g. "5cm". This depth string is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setDepth() [2/2]
void DSMSensor::setDepth (float val) inherited
Set sensor depth below ground.
Parameters
val depth below ground, in meters. The depth is converted to centimeters and is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
setDeviceName()
virtual void nidas::core::DSMSensor::setDeviceName (const std::string & val) inline virtual inherited
Set the name of the system device that the sensor is connected to.
Parameters
val Name of device, e.g. "/dev/xxx0".
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and main().
setDriverTimeTagUsecs()
virtual void nidas::core::DSMSensor::setDriverTimeTagUsecs (int val) inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::dynld::raf::DSMArincSensor::buildIODevice(), and nidas::dynld::raf::IRIGSensor::buildSampleScanner().
setDSMConfig()
void DSMSensor::setDSMConfig (const DSMConfig * val) inherited
Set the DSMConfig for this sensor.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMConfig::getId(), and nidas::core::DSMSensor::setDSMId().
Referenced by nidas::core::DSMConfig::sensorFromDOMElement(), and nidas::core::SensorHandler::~SensorHandler().
setDSMId()
void nidas::core::DSMSensor::setDSMId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_DSM_ID.
Referenced by nidas::core::DSMSensor::setDSMConfig().
setDuplicateIdOK()
void nidas::core::DSMSensor::setDuplicateIdOK (bool val) inline inherited
Set the duplicate ID attribute of this DSMSensor.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setFullSuffix()
void nidas::core::DSMSensor::setFullSuffix (const std::string & val) inline protected inherited
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
setHeight() [1/2]
void DSMSensor::setHeight (const std::string & val) inherited
Set sensor height above ground via a string which is added to variable names.
Parameters
val String containing sensor height and units in meters (m) or centimeters(cm), e.g. "15m". This height string is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setHeight() [2/2]
void DSMSensor::setHeight (float val) inherited
Set sensor height above ground.
Parameters
val height above ground, in meters. The height is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
setId()
void nidas::core::DSMSensor::setId (dsm_sample_id_t val) inline inherited
Set the various levels of the sensor identification.
A sensor ID is a 32-bit value comprised of four parts: 6-bit sample type id (not used by DSMSensor), 10-bit DSM id, and 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and SET_FULL_ID.
setIODevice()
void nidas::core::DSMSensor::setIODevice (IODevice * val) inline inherited
Set the IODevice for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_iodev.
setLagSecs()
virtual void nidas::core::DSMSensor::setLagSecs (double val) inline protected virtual inherited
Set the sampling lag for this sensor in seconds.
This lag should then used to correct the timetags of the processed samples in the process() method of derived classes. Note that this lag is not used to alter the timetags of the raw samples. Raw samples are saved with the un-altered timetag that was determined at the moment they were sampled.
The lag is stored as a signed integer of microseconds, so lags should be between += 2147 seconds. No warning or exception is given if the value exceeds that limit. If your lag is greater than that I suggest you junk your sensor! A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
<parameter name="lag" type = "float" value="0.186"/>
The DSMSensor::fromDOM() method parses this parameter and calls this method to set the lag. process() methods in derived classes must apply this lag value. The DSMSensor base class does not adjust time tags of processed samples.
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setLatency()
virtual void nidas::core::DSMSensor::setLatency (float val) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the driver for a 1/10 sec, then send the data to user space. Generally it should be set before doing a sensor open().
Parameters
val Latency, in seconds.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DSMSensor::_latency.
Referenced by nidas::dynld::A2DSensor::A2DSensor(), nidas::core::DSMSensor::fromDOMElement(), and nidas::dynld::A2DSensor::validate().
setLocation()
void nidas::core::DSMSensor::setLocation (const std::string & val) inline inherited
References nidas::core::DSMSensor::_location.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setSampleScanner()
void nidas::core::DSMSensor::setSampleScanner (SampleScanner * val) inline inherited
Set the SampleScanner for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_scanner.
setSensorId()
void nidas::core::DSMSensor::setSensorId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_SPS_ID.
Referenced by nidas::core::DSMSensor::fromDOMElement().
setStation()
void DSMSensor::setStation (int val) inherited
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_station, and nidas::core::SampleTag::setStation().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setSuffix()
void DSMSensor::setSuffix (const std::string & val) inherited
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::_suffix, and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
setTimeoutMsecs()
virtual void nidas::core::DSMSensor::setTimeoutMsecs (int val) inline virtual inherited
Set the sensor timeout value in milliseconds.
A value of 0 means no timeout (e.g. infinite). If no data is received for this period, then the sensor is closed, and re-opened. For efficiency reasons, the system may not actually detect a sensor timeout of less than 1 second, so setting it to less than 1000 milliseconds will likely not reduce the time before a sensor timeout is detected.
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::RemoteSerialConnection::doEscCmds(), and nidas::core::DSMSensor::fromDOMElement().
setTypeName()
virtual void nidas::core::DSMSensor::setTypeName (const std::string & val) inline virtual inherited
Set the type name of this sensor, e.g.
: "ACME Model 99 Mach7 Particle Disambiguator". This is meant for descriptive purposes only, and is not meant to change the behavior of a sensor object.
References nidas::core::DSMSensor::_typeName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DSMSensor::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Exceptions
xercesc::DOMException;
Reimplemented from nidas::core::DOMable.
Referenced by nidas::core::DSMSensor::toDOMParent().
toDOMParent()
xercesc::DOMElement * DSMSensor::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Exceptions
xercesc::DOMException
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::DSMSensor::toDOMElement(), and nidas::core::SampleTag::toDOMParent().
Referenced by nidas::core::DSMConfig::toDOMElement().
trimUnparsed()
void DSMSensor::trimUnparsed (SampleTag * stag, SampleT< float > * outs, int nparsed) protected inherited
Fill with floatNAN all the values past nparsed values in output sample outs, and trim the length of the sample to match the length of the variables in SampleTag stag.
process() methods which support partial scans of messages can use this to finalize an output sample according to the SampleTag that was matched with it and the number of values parsed.
References nidas::core::floatNAN, fp, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Variable::getLength(), nidas::core::SampleTag::getVariables(), and nidas::core::SampleT< DataT >::setDataLength().
Referenced by nidas::dynld::iss::WICORSensor::process().
validate()
void DSMSensor::validate () virtual inherited
validate() is called once on a DSMSensor after it has been configured, but before open() or init() are called.
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::TSI_CPC3772, nidas::dynld::raf::UDPArincSensor, nidas::dynld::raf::TwoD64_USB_v3, nidas::dynld::raf::SppSerial, nidas::dynld::raf::SPP300_Serial, nidas::dynld::raf::SPP200_Serial, nidas::dynld::raf::SPP100_Serial, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::raf::PIP_Serial, nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::raf::CDP_Serial, nidas::dynld::raf::BCPD_Serial, nidas::dynld::raf::AlicatSDI, nidas::dynld::raf::A2D_Serial, nidas::dynld::isff::WisardMote, nidas::dynld::isff::Wind3D, nidas::dynld::isff::Wind2D, nidas::dynld::isff::NCAR_TRH, nidas::dynld::isff::Licor7500, nidas::dynld::isff::CU_Coldwire, nidas::dynld::isff::CSI_CRX_Binary, nidas::dynld::IEEE_Float, nidas::dynld::GPS_Novatel_Serial, nidas::dynld::GPS_NMEA_Serial, nidas::dynld::DSC_PulseCounter, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_A2DSensor, nidas::dynld::A2DSensor, and nidas::core::CharacterSensor.
References nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::getSensorId().
Referenced by nidas::core::CharacterSensor::validate(), nidas::core::DSMConfig::validate(), nidas::dynld::A2DSensor::validate(), nidas::dynld::DSC_FreqCounter::validate(), and nidas::dynld::DSC_PulseCounter::validate().
write()
virtual size_t nidas::core::DSMSensor::write (const void * buf, size_t len) inline virtual inherited
Write to the device (duh).
Behaves like write(2) system call, without a file descriptor argument, and with an IOException.
Exceptions
nidas::util::IOException
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::write().
Referenced by nidas::dynld::isff::CSAT3_Sonic::dataMode(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::dynld::raf::AlicatSDI::open(), nidas::dynld::isff::CSAT3_Sonic::querySonic(), nidas::dynld::raf::AlicatSDI::sendFlow(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::core::CharacterSensor::sendInitString(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::dynld::isff::CSAT3_Sonic::sendRateCommand(), and nidas::dynld::isff::CSAT3_Sonic::terminalMode().
Member Data Documentation
_applyVariableConversions
bool nidas::core::DSMSensor::_applyVariableConversions private inherited
Referenced by nidas::core::DSMSensor::getApplyVariableConversions(), and nidas::core::DSMSensor::setApplyVariableConversions().
_calFiles
std::map<std::string,CalFile*> nidas::core::DSMSensor::_calFiles private inherited
Referenced by nidas::core::DSMSensor::addCalFile(), nidas::core::DSMSensor::getCalFile(), nidas::core::DSMSensor::getCalFiles(), and nidas::core::DSMSensor::removeCalFiles().
_catalogName
std::string nidas::core::DSMSensor::_catalogName private inherited
Referenced by nidas::core::DSMSensor::getCatalogName(), and nidas::core::DSMSensor::setCatalogName().
_className
std::string nidas::core::DSMSensor::_className private inherited
Class name attribute of this sensor.
Only used here for informative messages.
Referenced by nidas::core::DSMSensor::getClassName(), and nidas::core::DSMSensor::setClassName().
_constParameters
std::list<const Parameter*> nidas::core::DSMSensor::_constParameters private inherited
List of const pointers to Parameters for providing via getParameters().
Referenced by nidas::core::DSMSensor::addParameter(), and nidas::core::DSMSensor::getParameters().
_defaultMode
int nidas::core::DSMSensor::_defaultMode private inherited
Referenced by nidas::core::DSMSensor::getDefaultMode(), and nidas::core::DSMSensor::setDefaultMode().
_depthString
std::string nidas::core::DSMSensor::_depthString private inherited
Referenced by nidas::core::DSMSensor::getDepthString(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
_devname
std::string nidas::core::DSMSensor::_devname private inherited
Referenced by nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::setDeviceName().
_dictionary
nidas::core::DSMSensor::MyDictionary nidas::core::DSMSensor::_dictionary private inherited
Referenced by nidas::core::DSMSensor::expandString(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getDictionary(), and nidas::core::DSMSensor::getTokenValue().
_driverTimeTagUsecs
int nidas::core::DSMSensor::_driverTimeTagUsecs private inherited
Referenced by nidas::core::DSMSensor::getDriverTimeTagUsecs(), and nidas::core::DSMSensor::setDriverTimeTagUsecs().
_dsm
const DSMConfig* nidas::core::DSMSensor::_dsm private inherited
Referenced by nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMName(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getSite(), and nidas::core::DSMSensor::setDSMConfig().
_duplicateIdOK
bool nidas::core::DSMSensor::_duplicateIdOK private inherited
Referenced by nidas::core::DSMSensor::getDuplicateIdOK(), and nidas::core::DSMSensor::setDuplicateIdOK().
_fullSuffix
std::string nidas::core::DSMSensor::_fullSuffix private inherited
Concatenation of sensor suffix, and the height or depth string.
Referenced by nidas::core::DSMSensor::getFullSuffix(), and nidas::core::DSMSensor::setFullSuffix().
_height
float nidas::core::DSMSensor::_height private inherited
Referenced by nidas::core::DSMSensor::getDepth(), nidas::core::DSMSensor::getHeight(), nidas::core::DSMSensor::setDepth(), and nidas::core::DSMSensor::setHeight().
_heightString
std::string nidas::core::DSMSensor::_heightString private inherited
Referenced by nidas::core::DSMSensor::getHeightString(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
_id
dsm_sample_id_t nidas::core::DSMSensor::_id private inherited
Id of this sensor.
Raw samples from this sensor will have this id.
Referenced by nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getId(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::setDSMId(), nidas::core::DSMSensor::setId(), and nidas::core::DSMSensor::setSensorId().
_iodev
IODevice* nidas::core::DSMSensor::_iodev private inherited
Referenced by nidas::core::DSMSensor::close(), nidas::core::DSMSensor::getBytesAvailable(), nidas::core::DSMSensor::getIODevice(), nidas::core::DSMSensor::getReadFd(), nidas::core::DSMSensor::getWriteFd(), nidas::core::DSMSensor::ioctl(), nidas::core::DSMSensor::open(), nidas::core::DSMSensor::read(), nidas::core::DSMSensor::setIODevice(), nidas::core::DSMSensor::write(), and nidas::core::DSMSensor::~DSMSensor().
_lag
int nidas::core::DSMSensor::_lag private inherited
Referenced by nidas::core::DSMSensor::getLagSecs(), nidas::core::DSMSensor::getLagUsecs(), and nidas::core::DSMSensor::setLagSecs().
_latency
float nidas::core::DSMSensor::_latency private inherited
Referenced by nidas::core::DSMSensor::getLatency(), and nidas::core::DSMSensor::setLatency().
_location
std::string nidas::core::DSMSensor::_location private inherited
Referenced by nidas::core::DSMSensor::getLocation(), and nidas::core::DSMSensor::setLocation().
_looper
Looper * DSMSensor::_looper = 0 static private inherited
Referenced by nidas::core::DSMSensor::deleteLooper(), and nidas::core::DSMSensor::getLooper().
_looperMutex
n_u::Mutex DSMSensor::_looperMutex static private inherited
Referenced by nidas::core::DSMSensor::deleteLooper(), and nidas::core::DSMSensor::getLooper().
_nTimeouts
int nidas::core::DSMSensor::_nTimeouts private inherited
Referenced by nidas::core::DSMSensor::getTimeoutCount(), and nidas::core::DSMSensor::incrementTimeoutCount().
_openable
bool nidas::core::DSMSensor::_openable protected inherited
Whether this sensor is allowed to be opened.
Most cases the answer is yes/true. But certain sensors should not be opened due to implementation. e.g. DSMArincSensor when used in conjunction with the UDPArincSensor for then Alta ENET appliance.
The fallout from setting this to false is that the sensor will not be added to SensorHandler.
Referenced by nidas::core::DSMSensor::allowOpen(), and nidas::dynld::raf::DSMArincSensor::fromDOMElement().
_parameters
std::map<std::string,Parameter*> nidas::core::DSMSensor::_parameters private inherited
Map of parameters by name.
Referenced by nidas::core::DSMSensor::addParameter(), nidas::core::DSMSensor::getParameter(), and nidas::core::DSMSensor::~DSMSensor().
_rawSampleTag
SampleTag nidas::core::DSMSensor::_rawSampleTag private inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::DSMSensor::getRawSampleTag().
_rawSource
SampleSourceSupport nidas::core::DSMSensor::_rawSource private inherited
Referenced by nidas::core::DSMSensor::distributeRaw(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getRawSampleSource(), and nidas::core::DSMSensor::readSamples().
_sampleTags
std::list<SampleTag*> nidas::core::DSMSensor::_sampleTags private inherited
Referenced by nidas::core::DSMSensor::addSampleTag(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getNonConstSampleTags(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMSensor::removeSampleTag(), nidas::core::DSMSensor::setStation(), and nidas::core::DSMSensor::~DSMSensor().
_scanner
SampleScanner* nidas::core::DSMSensor::_scanner private inherited
Referenced by nidas::core::DSMSensor::calcStatistics(), nidas::core::DSMSensor::clearBuffer(), nidas::core::DSMSensor::getBadTimeTagCount(), nidas::core::DSMSensor::getMaxSampleLength(), nidas::core::DSMSensor::getMinSampleLength(), nidas::core::DSMSensor::getObservedDataRate(), nidas::core::DSMSensor::getObservedSamplingRate(), nidas::core::DSMSensor::getSampleScanner(), nidas::core::DSMSensor::nextSample(), nidas::core::DSMSensor::open(), nidas::core::DSMSensor::readBuffer(), nidas::core::DSMSensor::setSampleScanner(), and nidas::core::DSMSensor::~DSMSensor().
_source
SampleSourceSupport nidas::core::DSMSensor::_source private inherited
Referenced by nidas::core::DSMSensor::addSampleClient(), nidas::core::DSMSensor::addSampleClientForTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::DSMSensor::getClientCount(), nidas::core::DSMSensor::getSampleStats(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMSensor::receive(), nidas::core::DSMSensor::removeSampleClient(), nidas::core::DSMSensor::removeSampleClientForTag(), and nidas::core::DSMSensor::removeSampleTag().
_station
int nidas::core::DSMSensor::_station private inherited
Referenced by nidas::core::DSMSensor::getStation(), and nidas::core::DSMSensor::setStation().
_suffix
std::string nidas::core::DSMSensor::_suffix private inherited
Sensor suffix, which is added to variable names.
Referenced by nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setSuffix().
_timeoutMsecs
int nidas::core::DSMSensor::_timeoutMsecs private inherited
Referenced by nidas::core::DSMSensor::getTimeoutMsecs(), and nidas::core::DSMSensor::setTimeoutMsecs().
_typeName
std::string nidas::core::DSMSensor::_typeName private inherited
Referenced by nidas::core::DSMSensor::getTypeName(), and nidas::core::DSMSensor::setTypeName().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
zebra
bool DSMSensor::zebra = false static private inherited
Referenced by nidas::core::DSMSensor::printStatus(), and nidas::core::DSMSensor::printStatusHeader().
The documentation for this class was generated from the following file:
nidas/apps/raf/ck_mesa.cc