nidas: nidas/apps/ublox.cc File Reference
ublox.cc File Reference
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <linux/i2c-dev.h>
#include <cstdlib>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <ctype.h>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <map>
#include <vector>
#include <nidas/util/IOException.h>
Classes
class ublox_pkt
class ublox
Macros
#define MSECS_PER_SEC (1000)
#define USECS_PER_SEC (1000 * 1000)
#define WRITE_RDWR
Enumerations
enum NMEA_ID {
GGA , GLL , GSA , GSV ,
RMC , VTG , GRS , GST ,
ZDA , GBS , DTM , GPQ =0x40 ,
TXT =0x41
}
Ubox IDs for standard NMEA messages.
enum reset_type { HOTSTART , WARMSTART , COLDSTART = 0xffff }
Functions
short len_swab (const char *cp)
int main (int argc, char **argv)
Macro Definition Documentation
MSECS_PER_SEC
#define MSECS_PER_SEC (1000)
USECS_PER_SEC
#define USECS_PER_SEC (1000 * 1000)
WRITE_RDWR
#define WRITE_RDWR
Enumeration Type Documentation
NMEA_ID
enum NMEA_ID
Ubox IDs for standard NMEA messages.
Enumerator
GGA
GLL
GSA
GSV
RMC
VTG
GRS
GST
ZDA
GBS
DTM
GPQ
TXT
reset_type
enum reset_type
Enumerator
HOTSTART
WARMSTART
COLDSTART
Function Documentation
len_swab()
short len_swab (const char * cp)
Referenced by ublox::read_rdwr().
main()
int main (int argc, char ** argv)
References ublox::parseRunstring(), and ublox::run().