nidas: nidas::util::Multisync Class Reference
nidas::util::Multisync Class Reference
#include <ThreadSupport.h>
Public Member Functions
Multisync (int n)
void sync ()
void sync (std::string &msg)
void init ()
Private Attributes
Cond _co
int _n
int _count
int debug
Constructor & Destructor Documentation
Multisync()
Multisync::Multisync (int n)
References debug.
Member Function Documentation
init()
void Multisync::init ()
References _count.
sync() [1/2]
void Multisync::sync ()
References _co, _count, _n, nidas::util::Cond::broadcast(), debug, and nidas::util::Cond::wait().
sync() [2/2]
void Multisync::sync (std::string & msg)
References _co, _count, _n, nidas::util::Cond::broadcast(), debug, and nidas::util::Cond::wait().
Member Data Documentation
_co
Cond nidas::util::Multisync::_co private
Referenced by sync().
_count
int nidas::util::Multisync::_count private
Referenced by init(), and sync().
_n
int nidas::util::Multisync::_n private
Referenced by sync().
debug
int nidas::util::Multisync::debug private
Referenced by Multisync(), and sync().
The documentation for this class was generated from the following files:
nidas/util/ThreadSupport.h
nidas/util/ThreadSupport.cc