nidas: nidas/dynld/SampleInputStream.cc File Reference
SampleInputStream.cc File Reference
#include <nidas/core/Project.h>
#include "SampleInputStream.h"
#include <nidas/core/DSMSensor.h>
#include <nidas/core/DSMService.h>
#include <nidas/core/IOChannel.h>
#include <nidas/core/IOStream.h>
#include <nidas/util/Socket.h>
#include <byteswap.h>
#include <nidas/util/Logger.h>
#include <iomanip>
Namespaces
nidas
Root namespace for the NCAR In-Situ Data Acquisition Software.
nidas::util
General utility classes. nidas::util contains classes of general utility, like Socket, Thread, etc. The classes use only the standard Unix system libraries and libstdc++, and have no dependency on other external packages such as an XML parser, or a logging package.
nidas::dynld
The dynamically loadable classes of nidas. The nidas::dynld namespace and any sub namespaces, like nidas::dynld::raf, are for dynamically loadable classes, and any support classes that are only referenced by classes in nidas::dynld. Objects in nidas::dynld are created by nidas::core::DOMObjectFactory, using nidas::core::DynamicLoader, typically from a class="XXXXX" attribute in an XML file.
nidas::core
The essential core classes of nidas.
Macros
#define CNAME ("") << getName() << ": "
Functions
std::string ftime (dsm_time_t tt)
std::ostream & operator<< (std::ostream &out, const BlockStats &bs)
std::ostream & nidas::core::operator<< (std::ostream &out, const nidas::core::SampleHeader &header)
std::ostream & nidas::core::operator<< (std::ostream &out, const nidas::core::Sample &samp)
Macro Definition Documentation
CNAME
#define CNAME ("") << getName() << ": "
Function Documentation
ftime()
std::string ftime (dsm_time_t tt) inline
References nidas::util::UTime::format().
Referenced by nidas::util::FileSet::createFile(), nidas::util::FileSet::matchFiles(), operator<<(), nidas::core::operator<<(), and nidas::dynld::SampleInputStream::sampleFromHeader().
operator<<()
std::ostream& operator<< (std::ostream & out, const BlockStats & bs)
References nidas::dynld::BlockStats::block_start, nidas::dynld::BlockStats::blockEnd(), nidas::dynld::BlockStats::end_time, ftime(), nidas::dynld::BlockStats::good, nidas::dynld::BlockStats::last_good_sample_size, nidas::dynld::BlockStats::nbytes, nidas::dynld::BlockStats::nsamples, and nidas::dynld::BlockStats::start_time.