nidas: nidas::core::SampleClientList Class Reference
nidas::core::SampleClientList Class Reference
A list of SampleClients.
#include <SampleClientList.h>
Public Member Functions
SampleClientList ()
SampleClientList (const SampleClientList &cl)
Public copy constructor.
virtual ~SampleClientList ()
SampleClientList & operator= (const SampleClientList &cl)
Public assignment operator.
virtual void add (SampleClient *)
Add a SampleClient to this list.
virtual void remove (SampleClient *)
Remove a SampleClient from this SampleSource.
virtual bool empty () const
Are there any clients?
virtual void removeAll ()
Big cleanup.
void lock () const throw ()
Lock this list.
void unlock () const throw ()
Unlock this list.
std::list< SampleClient * >::const_iterator begin () throw ()
get a const_iterator pointing to first element.
std::list< SampleClient * >::const_iterator end () throw ()
get a const_iterator pointing to one-past-last element.
Private Attributes
nidas::util::Mutex _clistLock
mutex to prevent simultaneous access to clients list
std::list< SampleClient * > _clients
My current clients.
Detailed Description
A list of SampleClients.
This class is typically used by SampleSources to maintain their client lists.
Constructor & Destructor Documentation
SampleClientList() [1/2]
nidas::core::SampleClientList::SampleClientList () inline
SampleClientList() [2/2]
SampleClientList::SampleClientList (const SampleClientList & cl)
Public copy constructor.
To support multithreading, this first locks the SampleClientList argument.
References _clients, lock(), and unlock().
~SampleClientList()
virtual nidas::core::SampleClientList::~SampleClientList () inline virtual
Member Function Documentation
add()
void SampleClientList::add (SampleClient * client) virtual
Add a SampleClient to this list.
The pointer to the SampleClient must remain valid, until after it is removed. A nidas::util::Mutex exclusion lock is used to avoid simultaneous access.
References _clients, lock(), and unlock().
Referenced by nidas::core::SampleSourceSupport::addSampleClientForTag().
begin()
std::list<SampleClient*>::const_iterator nidas::core::SampleClientList::begin () throw () inline
get a const_iterator pointing to first element.
Does not lock!
References _clients.
Referenced by nidas::core::SampleSourceSupport::distribute().
empty()
bool SampleClientList::empty () const virtual
Are there any clients?
References _clients, lock(), and unlock().
end()
std::list<SampleClient*>::const_iterator nidas::core::SampleClientList::end () throw () inline
get a const_iterator pointing to one-past-last element.
Does not lock!
References _clients.
Referenced by nidas::core::SampleSourceSupport::distribute().
lock()
void nidas::core::SampleClientList::lock () const throw () inline
Lock this list.
References _clistLock, and nidas::util::Mutex::lock().
Referenced by add(), empty(), operator=(), remove(), removeAll(), and SampleClientList().
operator=()
SampleClientList & SampleClientList::operator= (const SampleClientList & cl)
Public assignment operator.
To support multithreading, this first locks the SampleClientList argument.
References _clients, lock(), and unlock().
remove()
void SampleClientList::remove (SampleClient * client) virtual
Remove a SampleClient from this SampleSource.
A nidas::util::Mutex exclusion lock is used to avoid simultaneous access.
References _clients, lock(), and unlock().
removeAll()
void SampleClientList::removeAll () virtual
Big cleanup.
A nidas::util::Mutex exclusion lock is used to avoid simultaneous access.
References _clients, lock(), and unlock().
Referenced by nidas::core::SampleSourceSupport::removeAllSampleClients().
unlock()
void nidas::core::SampleClientList::unlock () const throw () inline
Unlock this list.
References _clistLock, and nidas::util::Mutex::unlock().
Referenced by add(), empty(), operator=(), remove(), removeAll(), and SampleClientList().
Member Data Documentation
_clients
std::list<SampleClient*> nidas::core::SampleClientList::_clients private
My current clients.
Referenced by add(), begin(), empty(), end(), operator=(), remove(), removeAll(), and SampleClientList().
_clistLock
nidas::util::Mutex nidas::core::SampleClientList::_clistLock mutable private
mutex to prevent simultaneous access to clients list
Referenced by lock(), and unlock().
The documentation for this class was generated from the following files:
nidas/core/SampleClientList.h
nidas/core/SampleClientList.cc