nidas: nidas::core::TimetagAdjuster Class Reference
nidas::core::TimetagAdjuster Class Reference
Adjust time tags of fixed delta-T time series to correct for irregular latency in the assignments of the time tags at acquisition time.
#include <TimetagAdjuster.h>
Public Member Functions
TimetagAdjuster (dsm_sample_id_t id, double rate)
Constructor.
dsm_time_t adjust (dsm_time_t tt)
Adjust a time tag.
void log (int level, const DSMSensor *sensor, bool octalLable=false)
Log various statistics of the TimetagAdjuster, used by sensors classes on shutdown.
void slog (SampleTracer &stracer, const std::string &msg, dsm_time_t tt, long long toff, int tdiff, int tdiffUncorr)
Log message for a traced sample.
void slog (SampleTracer &stracer, const std::string &msg, dsm_time_t tt)
Log message for a traced sample.
float getRate () const
Return the configured sample rate, as passed to constructor.
float getMaxResultDt () const
Return the maximum dt in the adjusted time tags.
float getMinResultDt () const
Return the minimum dt in the adjusted time tags.
double getDtAvg () const
Return the current average input delta-T so far.
float getDtMin () const
Return the minimum calculated delta-T so far.
float getDtMax () const
Return the maximum calculated delta-T so far.
float getAdjMax () const
Return the maximum adjustment to the measured time tags.
float getAdjMin () const
Return the minimum adjustment to the measured time tags.
float getMaxGap () const
Maximum data gap in the non-adjusted, raw, time tags, in seconds.
unsigned int getNumPoints () const
Total number of time tags processed.
unsigned int getNumBackwards () const
How many backwards input time tags have been encountered, typically zero.
Static Public Attributes
static const int BIG_GAP_SECONDS = 10
Private Attributes
dsm_time_t _tt0
Result time tags will have a integral number of delta-Ts from this base time.
dsm_time_t _tlast
Previous time tag.
dsm_time_t _ttnDt0
dsm_time_t _ttAdjLast
long long _maxGap
double _dtUsecCorrSum
Sum for average of dt.
dsm_sample_id_t _id
ID of samples that are adjusted, used in log messages.
unsigned int _dtUsec
Expected delta-T in microseconds, 1/rate.
unsigned int _dtUsecCorr
Corrected delta-T in microseconds.
unsigned int _nDt
Current number of delta-Ts from tt0.
unsigned int _npts
Minimum number of points to compute minimum time difference.
int _tdiffminUsec
Minimum diffence between actual time tags and expected, over _npts.
int _dtUsecCorrMin
Minimum averaged dt so far.
unsigned int _dtUsecCorrMax
Maximum averaged dt so far.
unsigned int _nCorrSum
unsigned int _nBack
int _tadjMinUsec
unsigned int _tadjMaxUsec
unsigned int _ntotalPts
int _dtResultMin
int _dtResultMax
int _tdiffLast
unsigned int _nNegTdiff
unsigned int _nBigTdiff
int _nworsen
int _nimprove
unsigned int _nSamp5Min
Number of samples in 5 minutes, used for running average.
Detailed Description
Adjust time tags of fixed delta-T time series to correct for irregular latency in the assignments of the time tags at acquisition time.
See nidas/doc/timetags.md for a discussion of the algorithm.
Constructor & Destructor Documentation
TimetagAdjuster()
TimetagAdjuster::TimetagAdjuster (dsm_sample_id_t id, double rate)
Constructor.
Parameters
rate Sample rate in Hz, sec^-1.
Member Function Documentation
adjust()
dsm_time_t TimetagAdjuster::adjust (dsm_time_t tt)
Adjust a time tag.
Parameters
tt NIDAS time tag to be adjusted.
Returns
Adjusted time tag.
References _dtResultMax, _dtResultMin, _dtUsec, _dtUsecCorr, _dtUsecCorrMax, _dtUsecCorrMin, _dtUsecCorrSum, _id, _maxGap, _nBack, _nBigTdiff, _nCorrSum, _nDt, _nimprove, _nNegTdiff, _npts, _nSamp5Min, _ntotalPts, _nworsen, _tadjMaxUsec, _tadjMinUsec, _tdiffLast, _tdiffminUsec, _tlast, _tt0, _ttAdjLast, _ttnDt0, BIG_GAP_SECONDS, DLOG, GET_DSM_ID, GET_SPS_ID, LOG_VERBOSE, slog(), and USECS_PER_SEC.
Referenced by nidas::core::CharacterSensor::adjustTimeTag(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::raf::DSMArincSensor::process(), and nidas::dynld::isff::CSAT3_Sonic::process().
getAdjMax()
float nidas::core::TimetagAdjuster::getAdjMax () const inline
Return the maximum adjustment to the measured time tags.
References _tadjMaxUsec, and USECS_PER_SEC.
Referenced by log().
getAdjMin()
float nidas::core::TimetagAdjuster::getAdjMin () const inline
Return the minimum adjustment to the measured time tags.
References _tadjMinUsec, and USECS_PER_SEC.
getDtAvg()
double nidas::core::TimetagAdjuster::getDtAvg () const inline
Return the current average input delta-T so far.
1.0 / getDtAvg() is the observed sample rate.
References _dtUsecCorrSum, _nCorrSum, and USECS_PER_SEC.
Referenced by log().
getDtMax()
float nidas::core::TimetagAdjuster::getDtMax () const inline
Return the maximum calculated delta-T so far.
References _dtUsecCorrMax, and USECS_PER_SEC.
Referenced by log().
getDtMin()
float nidas::core::TimetagAdjuster::getDtMin () const inline
Return the minimum calculated delta-T so far.
The observed delta-T of the input raw time tags is averaged to get a better estimate of the actual dt , because it will not typically be exactly the inverse of the configured rate.
References _dtUsecCorrMin, and USECS_PER_SEC.
Referenced by log().
getMaxGap()
float nidas::core::TimetagAdjuster::getMaxGap () const inline
Maximum data gap in the non-adjusted, raw, time tags, in seconds.
References _maxGap, and USECS_PER_SEC.
Referenced by log().
getMaxResultDt()
float nidas::core::TimetagAdjuster::getMaxResultDt () const inline
Return the maximum dt in the adjusted time tags.
This is the maximum difference between successive, adjusted time tags.
References _dtResultMax, and USECS_PER_SEC.
Referenced by log().
getMinResultDt()
float nidas::core::TimetagAdjuster::getMinResultDt () const inline
Return the minimum dt in the adjusted time tags.
References _dtResultMin, and USECS_PER_SEC.
Referenced by log().
getNumBackwards()
unsigned int nidas::core::TimetagAdjuster::getNumBackwards () const inline
How many backwards input time tags have been encountered, typically zero.
References _nBack.
getNumPoints()
unsigned int nidas::core::TimetagAdjuster::getNumPoints () const inline
Total number of time tags processed.
References _ntotalPts.
Referenced by log().
getRate()
float nidas::core::TimetagAdjuster::getRate () const inline
Return the configured sample rate, as passed to constructor.
References _dtUsec, and USECS_PER_SEC.
Referenced by log().
log()
void TimetagAdjuster::log (int level, const DSMSensor * sensor, bool octalLable = false)
Log various statistics of the TimetagAdjuster, used by sensors classes on shutdown.
References _id, _nBigTdiff, _nNegTdiff, GET_DSM_ID, GET_SPS_ID, getAdjMax(), getDtAvg(), getDtMax(), getDtMin(), nidas::core::DSMSensor::getId(), nidas::util::Logger::getInstance(), getMaxGap(), getMaxResultDt(), getMinResultDt(), nidas::core::DSMSensor::getName(), getNumPoints(), getRate(), and nidas::util::Logger::log().
Referenced by nidas::dynld::isff::ATIK_Sonic::~ATIK_Sonic(), nidas::core::CharacterSensor::~CharacterSensor(), nidas::dynld::isff::CSAT3_Sonic::~CSAT3_Sonic(), and nidas::dynld::raf::DSMArincSensor::~DSMArincSensor().
slog() [1/2]
void nidas::core::TimetagAdjuster::slog (SampleTracer & stracer, const std::string & msg, dsm_time_t tt)
Log message for a traced sample.
Used for lower-rate messages every _npts.
slog() [2/2]
void nidas::core::TimetagAdjuster::slog (SampleTracer & stracer, const std::string & msg, dsm_time_t tt, long long toff, int tdiff, int tdiffUncorr)
Log message for a traced sample.
Used for high-rate messages containing each time tag and tdiff.
Referenced by adjust().
Member Data Documentation
_dtResultMax
int nidas::core::TimetagAdjuster::_dtResultMax private
Referenced by adjust(), and getMaxResultDt().
_dtResultMin
int nidas::core::TimetagAdjuster::_dtResultMin private
Referenced by adjust(), and getMinResultDt().
_dtUsec
unsigned int nidas::core::TimetagAdjuster::_dtUsec private
Expected delta-T in microseconds, 1/rate.
Referenced by adjust(), and getRate().
_dtUsecCorr
unsigned int nidas::core::TimetagAdjuster::_dtUsecCorr private
Corrected delta-T in microseconds.
Referenced by adjust().
_dtUsecCorrMax
unsigned int nidas::core::TimetagAdjuster::_dtUsecCorrMax private
Maximum averaged dt so far.
Referenced by adjust(), and getDtMax().
_dtUsecCorrMin
int nidas::core::TimetagAdjuster::_dtUsecCorrMin private
Minimum averaged dt so far.
Referenced by adjust(), and getDtMin().
_dtUsecCorrSum
double nidas::core::TimetagAdjuster::_dtUsecCorrSum private
Sum for average of dt.
Referenced by adjust(), and getDtAvg().
_id
dsm_sample_id_t nidas::core::TimetagAdjuster::_id private
ID of samples that are adjusted, used in log messages.
Referenced by adjust(), and log().
_maxGap
long long nidas::core::TimetagAdjuster::_maxGap private
Referenced by adjust(), and getMaxGap().
_nBack
unsigned int nidas::core::TimetagAdjuster::_nBack private
Referenced by adjust(), and getNumBackwards().
_nBigTdiff
unsigned int nidas::core::TimetagAdjuster::_nBigTdiff private
Referenced by adjust(), and log().
_nCorrSum
unsigned int nidas::core::TimetagAdjuster::_nCorrSum private
Referenced by adjust(), and getDtAvg().
_nDt
unsigned int nidas::core::TimetagAdjuster::_nDt private
Current number of delta-Ts from tt0.
Referenced by adjust().
_nimprove
int nidas::core::TimetagAdjuster::_nimprove private
Referenced by adjust().
_nNegTdiff
unsigned int nidas::core::TimetagAdjuster::_nNegTdiff private
Referenced by adjust(), and log().
_npts
unsigned int nidas::core::TimetagAdjuster::_npts private
Minimum number of points to compute minimum time difference.
Referenced by adjust().
_nSamp5Min
unsigned int nidas::core::TimetagAdjuster::_nSamp5Min private
Number of samples in 5 minutes, used for running average.
Referenced by adjust().
_ntotalPts
unsigned int nidas::core::TimetagAdjuster::_ntotalPts private
Referenced by adjust(), and getNumPoints().
_nworsen
int nidas::core::TimetagAdjuster::_nworsen private
Referenced by adjust().
_tadjMaxUsec
unsigned int nidas::core::TimetagAdjuster::_tadjMaxUsec private
Referenced by adjust(), and getAdjMax().
_tadjMinUsec
int nidas::core::TimetagAdjuster::_tadjMinUsec private
Referenced by adjust(), and getAdjMin().
_tdiffLast
int nidas::core::TimetagAdjuster::_tdiffLast private
Referenced by adjust().
_tdiffminUsec
int nidas::core::TimetagAdjuster::_tdiffminUsec private
Minimum diffence between actual time tags and expected, over _npts.
Referenced by adjust().
_tlast
dsm_time_t nidas::core::TimetagAdjuster::_tlast private
Previous time tag.
Referenced by adjust().
_tt0
dsm_time_t nidas::core::TimetagAdjuster::_tt0 private
Result time tags will have a integral number of delta-Ts from this base time.
This base time is slowly adjusted by computing the minimum difference between the result time tags and the input time tags.
Referenced by adjust().
_ttAdjLast
dsm_time_t nidas::core::TimetagAdjuster::_ttAdjLast private
Referenced by adjust().
_ttnDt0
dsm_time_t nidas::core::TimetagAdjuster::_ttnDt0 private
Referenced by adjust().
BIG_GAP_SECONDS
const int nidas::core::TimetagAdjuster::BIG_GAP_SECONDS = 10 static
Referenced by adjust().
The documentation for this class was generated from the following files:
nidas/core/TimetagAdjuster.h
nidas/core/TimetagAdjuster.cc