nidas: nidas::core::ConnectionInfo Class Reference
nidas::core::ConnectionInfo Class Reference
Extra information associated with an IOChannel concerning the connection.
#include <ConnectionInfo.h>
Public Member Functions
ConnectionInfo ()
ConnectionInfo (const nidas::util::Inet4SocketAddress &remote, const nidas::util::Inet4Address &dest, const nidas::util::Inet4NetworkInterface iface)
nidas::util::Inet4SocketAddress getRemoteSocketAddress () const
The remote address of connection.
void setRemoteSocketAddress (const nidas::util::Inet4SocketAddress &val)
const nidas::util::Inet4Address & getDestinationAddress () const
The destination address of the packet.
void setDestinationAddress (const nidas::util::Inet4Address &val)
const nidas::util::Inet4NetworkInterface & getInterface () const
The interface that the packet was received on.
void setInterface (const nidas::util::Inet4NetworkInterface &val)
Private Attributes
nidas::util::Inet4SocketAddress _remotesaddr
nidas::util::Inet4Address _destAddr
nidas::util::Inet4NetworkInterface _iface
Detailed Description
Extra information associated with an IOChannel concerning the connection.
Constructor & Destructor Documentation
ConnectionInfo() [1/2]
nidas::core::ConnectionInfo::ConnectionInfo () inline
ConnectionInfo() [2/2]
nidas::core::ConnectionInfo::ConnectionInfo (const nidas::util::Inet4SocketAddress & remote, const nidas::util::Inet4Address & dest, const nidas::util::Inet4NetworkInterface iface) inline
Member Function Documentation
getDestinationAddress()
const nidas::util::Inet4Address& nidas::core::ConnectionInfo::getDestinationAddress () const inline
The destination address of the packet.
For a received unicast packet it will be the address of the local interface. Or the destination address could be a multicast address or a broadcast address.
References _destAddr.
Referenced by nidas::core::MultipleUDPSockets::addClient(), and nidas::dynld::UDPSampleOutput::ConnectionMonitor::addDestination().
getInterface()
const nidas::util::Inet4NetworkInterface& nidas::core::ConnectionInfo::getInterface () const inline
The interface that the packet was received on.
References _iface.
Referenced by nidas::core::MultipleUDPSockets::addClient().
getRemoteSocketAddress()
nidas::util::Inet4SocketAddress nidas::core::ConnectionInfo::getRemoteSocketAddress () const inline
The remote address of connection.
References _remotesaddr.
Referenced by nidas::core::MultipleUDPSockets::addClient(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::addDestination(), and nidas::dynld::SampleInputStream::setIOChannel().
setDestinationAddress()
void nidas::core::ConnectionInfo::setDestinationAddress (const nidas::util::Inet4Address & val) inline
References _destAddr.
setInterface()
void nidas::core::ConnectionInfo::setInterface (const nidas::util::Inet4NetworkInterface & val) inline
References _iface.
setRemoteSocketAddress()
void nidas::core::ConnectionInfo::setRemoteSocketAddress (const nidas::util::Inet4SocketAddress & val) inline
References _remotesaddr.
Member Data Documentation
_destAddr
nidas::util::Inet4Address nidas::core::ConnectionInfo::_destAddr private
Referenced by getDestinationAddress(), and setDestinationAddress().
_iface
nidas::util::Inet4NetworkInterface nidas::core::ConnectionInfo::_iface private
Referenced by getInterface(), and setInterface().
_remotesaddr
nidas::util::Inet4SocketAddress nidas::core::ConnectionInfo::_remotesaddr private
Referenced by getRemoteSocketAddress(), and setRemoteSocketAddress().
The documentation for this class was generated from the following file:
nidas/core/ConnectionInfo.h