nidas: ARLIngest Class Reference
ARLIngest Class Reference
Public Member Functions
ARLIngest ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
int usage (const char *argv0)
usage emits a generic usage message to std::cout
void sendHeader (dsm_time_t thead, SampleOutput *out)
sendHeader does something I still dont understand
void printHeader ()
printHeader dumps out header information (for debugging)
Static Public Member Functions
static int main (int argc, char **argv) throw ()
main is the entry point for the ARLIngest class.
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Private Member Functions
bool arl_ingest_one (SampleOutputStream &, string) throw ()
arl_ingest_one ingests a single file by the passed filename and writes the re-encoded data into the passed SampleOutputStream
void writeLine (SampleOutputStream &, string &, n_u::UTime)
writeLine writes a single sample line to the passed output stream applying the needed offset UTime
void prepareHeaderIds (string xmlfilename, string dsmName, string height)
prepareHeaderIds parses the xml files pointed to by xmlfilename and using the passed dsm name and height, modifies dsmid and spsid to the proper values.
Private Attributes
list< string > inputFileNames
string outputFileName
int outputFileLength
int dsmid
int spsid
double leapSeconds
SampleInputHeader header
NidasApp _app
Constructor & Destructor Documentation
ARLIngest()
ARLIngest::ARLIngest () inline
Member Function Documentation
arl_ingest_one()
bool ARLIngest::arl_ingest_one (SampleOutputStream & sout, string filename) throw () private
arl_ingest_one ingests a single file by the passed filename and writes the re-encoded data into the passed SampleOutputStream
References nidas::util::UTime::parse(), and nidas::util::UTime::toDoubleSecs().
main()
int ARLIngest::main (int argc, char ** argv) throw () static
main is the entry point for the ARLIngest class.
argc and argv are taken from the normal places.
References parseRunstring(), run(), and nidas::core::NidasApp::setupSignals().
Referenced by main().
parseRunstring()
int ARLIngest::parseRunstring (int argc, char ** argv) throw ()
References nidas::core::NidasAppInputFilesArg::allowFiles, nidas::core::NidasAppInputFilesArg::allowSockets, nidas::core::NidasApp::allowUnrecognized(), nidas::core::NidasAppArgv::argc, nidas::core::NidasAppArgv::argv, nidas::core::NidasApp::enableArguments(), nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), nidas::core::NidasApp::InputFiles, nidas::core::NidasApp::loggingArgs(), nidas::core::NidasApp::outputFileLength(), nidas::core::NidasApp::outputFileName(), nidas::core::NidasApp::OutputFiles, nidas::core::NidasApp::parseArgs(), usage(), nidas::core::NidasApp::Version, nidas::core::NidasApp::XmlHeaderFile, and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
prepareHeaderIds()
void ARLIngest::prepareHeaderIds (string xmlfilename, string dsmName, string height) private
prepareHeaderIds parses the xml files pointed to by xmlfilename and using the passed dsm name and height, modifies dsmid and spsid to the proper values.
It throws exceptions on file IO errors, or when no configuration match is found. Additionally, it loads proper values into the stored header which is attached to samples when sendHeader is called
References nidas::util::Process::expandEnvVars(), nidas::core::Version::getArchiveVersion(), nidas::core::DSMSensor::getHeightString(), nidas::core::DSMConfig::getId(), nidas::core::Project::getInstance(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::Version::getSoftwareVersion(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::SensorIterator::hasNext(), nidas::core::DSMConfigIterator::next(), nidas::core::SensorIterator::next(), and nidas::core::parseXMLConfigFile().
printHeader()
void ARLIngest::printHeader ()
printHeader dumps out header information (for debugging)
run()
int ARLIngest::run () throw ()
References nidas::dynld::SampleOutputStream::close(), nidas::dynld::SampleOutputStream::flush(), nidas::core::FileSet::setFileLengthSecs(), nidas::core::FileSet::setFileName(), nidas::core::SampleOutputBase::setHeaderSource(), and nidas::util::Exception::what().
Referenced by main().
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
sendHeader()
void ARLIngest::sendHeader (dsm_time_t thead, SampleOutput * out) virtual
sendHeader does something I still dont understand
Implements nidas::core::HeaderSource.
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
usage()
int ARLIngest::usage (const char * argv0)
usage emits a generic usage message to std::cout
writeLine()
void ARLIngest::writeLine (SampleOutputStream & sout, string & line, n_u::UTime time) private
writeLine writes a single sample line to the passed output stream applying the needed offset UTime
References nidas::core::SampleT< DataT >::getDataPtr(), nidas::dynld::SampleOutputStream::receive(), nidas::core::Sample::setDSMId(), nidas::core::Sample::setSpSId(), nidas::core::Sample::setTimeTag(), and nidas::util::UTime::toUsecs().
Member Data Documentation
_app
NidasApp ARLIngest::_app private
dsmid
int ARLIngest::dsmid private
header
SampleInputHeader ARLIngest::header private
inputFileNames
list<string> ARLIngest::inputFileNames private
leapSeconds
double ARLIngest::leapSeconds private
outputFileLength
int ARLIngest::outputFileLength private
outputFileName
string ARLIngest::outputFileName private
spsid
int ARLIngest::spsid private
The documentation for this class was generated from the following file:
nidas/apps/arl-ingest.cc