nidas: nidas::dynld::DSC_AnalogOut Class Reference
nidas::dynld::DSC_AnalogOut Class Reference
Support for the D2A device on a Diamond DMMAT card.
#include <DSC_AnalogOut.h>
Public Member Functions
DSC_AnalogOut ()
~DSC_AnalogOut ()
void setDeviceName (const std::string &val)
const std::string & getDeviceName () const
const std::string & getName () const
int getFd () const
void open ()
Open the D2A.
void close ()
Close the D2A.
int getNumOutputs () const
Return number of VOUT pins on this device.
float getMinVoltage (int i) const
Return the minimum setable voltage of an output.
float getMaxVoltage (int i) const
Return the maximum setable voltage of an output.
void setVoltage (int which, float val)
Set a voltage on an output.
void setVoltages (const std::vector< int > &which, const std::vector< float > &val)
Set one or more outputs.
Private Attributes
std::string _devName
int _fd
The file descriptor of this device.
int _noutputs
How many VOUT pins are on this device?
struct DMMAT_D2A_Conversion _conv
Linear parameters for converting a voltage to an integer count, which is sent to the device.
Detailed Description
Support for the D2A device on a Diamond DMMAT card.
Constructor & Destructor Documentation
DSC_AnalogOut()
DSC_AnalogOut::DSC_AnalogOut ()
~DSC_AnalogOut()
DSC_AnalogOut::~DSC_AnalogOut ()
References _fd, and close().
Member Function Documentation
close()
void DSC_AnalogOut::close ()
Close the D2A.
Exceptions
nidas::util::IOException
References _fd.
Referenced by DmdA2dCk::run(), and ~DSC_AnalogOut().
getDeviceName()
const std::string& nidas::dynld::DSC_AnalogOut::getDeviceName () const inline
References _devName.
getFd()
int nidas::dynld::DSC_AnalogOut::getFd () const inline
References _fd.
getMaxVoltage()
float DSC_AnalogOut::getMaxVoltage (int i) const
Return the maximum setable voltage of an output.
References _conv, _noutputs, and DMMAT_D2A_Conversion::vmax.
Referenced by main(), and DmdA2dCk::run().
getMinVoltage()
float DSC_AnalogOut::getMinVoltage (int i) const
Return the minimum setable voltage of an output.
References _conv, _noutputs, and DMMAT_D2A_Conversion::vmin.
Referenced by main(), and DmdA2dCk::run().
getName()
const std::string& nidas::dynld::DSC_AnalogOut::getName () const inline
References _devName.
Referenced by setVoltages().
getNumOutputs()
int nidas::dynld::DSC_AnalogOut::getNumOutputs () const inline
Return number of VOUT pins on this device.
Value will be 0 if the device has not been opened, or -1 if the open failed.
References _noutputs.
Referenced by main(), and DmdA2dCk::run().
open()
void DSC_AnalogOut::open ()
Open the D2A.
Exceptions
nidas::util::IOException
References _conv, _devName, _fd, _noutputs, DMMAT_D2A_GET_CONVERSION, and DMMAT_D2A_GET_NOUTPUTS.
Referenced by main(), and DmdA2dCk::run().
setDeviceName()
void nidas::dynld::DSC_AnalogOut::setDeviceName (const std::string & val) inline
References _devName.
Referenced by main(), and DmdA2dCk::run().
setVoltage()
void DSC_AnalogOut::setVoltage (int which, float val)
Set a voltage on an output.
Parameters
which Which VOUT pin, numbered from 0.
val Desired voltage value. If val is outside the known limit of the D2A, the request will be changed to the corresponding limit value. Throws nidas::util::InvalidParameterException if "which" is out of range.
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
References setVoltages().
Referenced by DmdA2dCk::run().
setVoltages()
void DSC_AnalogOut::setVoltages (const std::vector< int > & which, const std::vector< float > & val)
Set one or more outputs.
Parameters
which Vector of VOUT pin numbers, numbered from 0.
val Desired voltage values. If a val is outside the known limit of the D2A, the request will be changed to the corresponding limit value. Throws nidas::util::InvalidParameterException if "which" is out of range.
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
References _conv, _devName, _fd, _noutputs, DMMAT_D2A_Outputs::active, DMMAT_D2A_Conversion::cmax, DMMAT_D2A_Conversion::cmin, DMMAT_D2A_Outputs::counts, DMMAT_D2A_SET, getName(), DMMAT_D2A_Outputs::nout, DMMAT_D2A_Conversion::vmax, and DMMAT_D2A_Conversion::vmin.
Referenced by main(), and setVoltage().
Member Data Documentation
_conv
struct DMMAT_D2A_Conversion nidas::dynld::DSC_AnalogOut::_conv private
Linear parameters for converting a voltage to an integer count, which is sent to the device.
Referenced by getMaxVoltage(), getMinVoltage(), open(), and setVoltages().
_devName
std::string nidas::dynld::DSC_AnalogOut::_devName private
Referenced by getDeviceName(), getName(), open(), setDeviceName(), and setVoltages().
_fd
int nidas::dynld::DSC_AnalogOut::_fd private
The file descriptor of this device.
Referenced by close(), getFd(), open(), setVoltages(), and ~DSC_AnalogOut().
_noutputs
int nidas::dynld::DSC_AnalogOut::_noutputs private
How many VOUT pins are on this device?
Referenced by getMaxVoltage(), getMinVoltage(), getNumOutputs(), open(), and setVoltages().
The documentation for this class was generated from the following files:
nidas/dynld/DSC_AnalogOut.h
nidas/dynld/DSC_AnalogOut.cc