nidas: nidas::core::UDPSocketIODevice Class Reference
nidas::core::UDPSocketIODevice Class Reference
An IODevice consisting of an UDP socket.
#include <UDPSocketIODevice.h>
Public Member Functions
UDPSocketIODevice ()
Create a UDPSocketIODevice.
~UDPSocketIODevice ()
void open (int flags)
Open the socket, which does a socket bind to the remote address which is parsed from the contents of getName().
int getReadFd () const
The file descriptor used when reading from this SocketIODevice.
int getWriteFd () const
The file descriptor used when writing to this device.
size_t read (void *buf, size_t len)
Read from the device.
size_t read (void *buf, size_t len, int msecTimeout)
Read from the device with a timeout in milliseconds.
size_t write (const void *buf, size_t len)
Write to the device.
void close ()
close the device.
void ioctl (int, void *, size_t)
virtual void setName (const std::string &val)
Set the device name to be opened for this sensor.
virtual const std::string & getName () const
virtual size_t getBytesAvailable () const
Return how many bytes are available to read on this IODevice.
Static Public Member Functions
static void parseAddress (const std::string &name, int &addrtype, std::string &hostname, int &port, std::string &bindaddr)
Parse the getName() string to extract a socket type, destination address and optional port number.
Protected Member Functions
UDPSocketIODevice (const UDPSocketIODevice &)
No copy.
UDPSocketIODevice & operator= (const UDPSocketIODevice &)
No assignment.
Protected Attributes
nidas::util::DatagramSocket * _socket
The datagramsocket.
int _addrtype
The type of the destination address, AF_INET or AF_UNIX.
std::string _desthost
Destination host name from sensor name.
int _port
Port number that is parsed from sensor name.
nidas::util::auto_ptr< nidas::util::SocketAddress > _sockAddr
The destination socket address.
std::string _bindAddr
The local bind socket address.
Private Attributes
std::string _devname
Whether to reopen this sensor on an IOException.
Detailed Description
An IODevice consisting of an UDP socket.
Constructor & Destructor Documentation
UDPSocketIODevice() [1/2]
UDPSocketIODevice::UDPSocketIODevice ()
Create a UDPSocketIODevice.
No IO operations are performed in the constructor, hence no IOExceptions.
~UDPSocketIODevice()
UDPSocketIODevice::~UDPSocketIODevice ()
References close().
UDPSocketIODevice() [2/2]
nidas::core::UDPSocketIODevice::UDPSocketIODevice (const UDPSocketIODevice &) protected
No copy.
Member Function Documentation
close()
void UDPSocketIODevice::close () virtual
close the device.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, nidas::util::DatagramSocket::close(), nidas::util::DatagramSocket::getFd(), nidas::util::Logger::getInstance(), nidas::core::IODevice::getName(), nidas::util::Logger::log(), and LOG_INFO.
Referenced by ~UDPSocketIODevice().
getBytesAvailable()
virtual size_t nidas::core::IODevice::getBytesAvailable () const inline virtual inherited
Return how many bytes are available to read on this IODevice.
This method is only useful when ioctl FIONREAD is supported on this this IODevice, as for example with a UDP socket. It is not available, and not necessary, on most other devices, like serial ports, TCP sockets, or devices with nidas driver module support, in which case it will return an nidas::util::IOException. It is an optimization for use with UDP sockets, where after select determines that data is available on the socket file descriptor, a read will only read one datagram, even if there are more than one packet available, which would not be optimal if a sensor generated many small packets. Rather than returning back to select, we check if there are more datagrams to read. This is not necessary on other types of IODevices, where it is just a matter of using a big enough buffer to get all (or most) available data after a select.
According to man udp(7), FIONREAD will return 0 if the size of the next packet is 0. So, if select/poll indicate there is data available, one read at least should be done, just in case a sensor sends a datagram of length 0, otherwise it will never be consumed.
Exceptions
nidas::util::IOException
References err, nidas::core::IODevice::getName(), nidas::core::IODevice::getReadFd(), and nidas::core::IODevice::ioctl().
Referenced by nidas::core::DSMSensor::getBytesAvailable().
getName()
virtual const std::string& nidas::core::IODevice::getName () const inline virtual inherited
References nidas::core::IODevice::_devname.
Referenced by nidas::core::SerialPortIODevice::applyTermios(), nidas::core::ServerSocketIODevice::close(), nidas::core::TCPSocketIODevice::close(), close(), nidas::core::UnixIODevice::close(), nidas::core::IODevice::getBytesAvailable(), nidas::core::UnixIODevice::ioctl(), nidas::core::ServerSocketIODevice::ioctl(), nidas::core::SocketIODevice::ioctl(), nidas::core::ServerSocketIODevice::open(), nidas::core::SocketIODevice::open(), nidas::core::UnixIODevice::open(), nidas::core::UnixIODevice::read(), and nidas::core::UnixIODevice::write().
getReadFd()
int nidas::core::UDPSocketIODevice::getReadFd () const inline virtual
The file descriptor used when reading from this SocketIODevice.
Implements nidas::core::IODevice.
References _socket, and nidas::util::DatagramSocket::getFd().
getWriteFd()
int nidas::core::UDPSocketIODevice::getWriteFd () const inline virtual
The file descriptor used when writing to this device.
Implements nidas::core::IODevice.
References _socket, and nidas::util::DatagramSocket::getFd().
ioctl()
void nidas::core::SocketIODevice::ioctl (int , void * , size_t) inline virtual inherited
Implements nidas::core::IODevice.
References nidas::core::IODevice::getName().
open()
void UDPSocketIODevice::open (int flags) virtual
Open the socket, which does a socket bind to the remote address which is parsed from the contents of getName().
See SocketIODevice::open() and SocketIODevice::parseAddress().
Exceptions
nidas::util::IOException
nidas::util::InvalidParameterException
Reimplemented from nidas::core::SocketIODevice.
References nidas::core::SocketIODevice::_sockAddr, _socket, nidas::util::DatagramSocket::bind(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::util::Inet4Address::isMultiCastAddress(), nidas::util::MulticastSocket::joinGroup(), nidas::core::SocketIODevice::open(), and nidas::util::DatagramSocket::setBroadcastEnable().
operator=()
UDPSocketIODevice& nidas::core::UDPSocketIODevice::operator= (const UDPSocketIODevice &) protected
No assignment.
parseAddress()
void SocketIODevice::parseAddress (const std::string & name, int & addrtype, std::string & hostname, int & port, std::string & bindaddr) static inherited
Parse the getName() string to extract a socket type, destination address and optional port number.
The syntax of the set/getName() string is: ("inet" | "sock" | "unix" | "blue" | "btspp") ':' address [:port] "inet" or "sock" indicate a TCP or UDP connection for use by derived classes implementing a TCP or UDP socket. The address field should then be a hostname which can be resolved to an IP address, or an IP address in dot notation. A port number is required for TCP/UDP socket connection. "unix" indicates a Unix socket connection, where address is the path name of the unix socket, for process to process communications. The port value is not used by unix sockets.
Exceptions
nidas::util::ParseException
References port.
Referenced by nidas::core::ServerSocketIODevice::open(), nidas::core::SocketIODevice::open(), and nidas::dynld::raf::PSI9116_Sensor::open().
read() [1/2]
size_t nidas::core::UDPSocketIODevice::read (void * buf, size_t len) inline virtual
Read from the device.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::DatagramSocket::recv().
read() [2/2]
size_t UDPSocketIODevice::read (void * buf, size_t len, int msecTimeout) virtual
Read from the device with a timeout in milliseconds.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, nidas::util::DatagramSocket::recv(), and nidas::util::DatagramSocket::setTimeout().
setName()
virtual void nidas::core::IODevice::setName (const std::string & val) inline virtual inherited
Set the device name to be opened for this sensor.
References nidas::core::IODevice::_devname.
Referenced by nidas::core::DSMSensor::open(), and nidas::core::UnixIODevice::UnixIODevice().
write()
size_t nidas::core::UDPSocketIODevice::write (const void * buf, size_t len) inline virtual
Write to the device.
Exceptions
nidas::util::IOException
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::DatagramSocket::send().
Member Data Documentation
_addrtype
int nidas::core::SocketIODevice::_addrtype protected inherited
The type of the destination address, AF_INET or AF_UNIX.
Referenced by nidas::core::SocketIODevice::open().
_bindAddr
std::string nidas::core::SocketIODevice::_bindAddr protected inherited
The local bind socket address.
Referenced by nidas::core::SocketIODevice::open().
_desthost
std::string nidas::core::SocketIODevice::_desthost protected inherited
Destination host name from sensor name.
Referenced by nidas::core::SocketIODevice::open().
_devname
std::string nidas::core::IODevice::_devname private inherited
Whether to reopen this sensor on an IOException.
Referenced by nidas::core::IODevice::getName(), and nidas::core::IODevice::setName().
_port
int nidas::core::SocketIODevice::_port protected inherited
Port number that is parsed from sensor name.
For a server socket this is the local port number to listen on. For a remote connection socket this is the remote port number.
Referenced by nidas::core::SocketIODevice::open().
_sockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::SocketIODevice::_sockAddr protected inherited
The destination socket address.
Referenced by nidas::core::SocketIODevice::open(), nidas::core::TCPSocketIODevice::open(), and open().
_socket
nidas::util::DatagramSocket* nidas::core::UDPSocketIODevice::_socket protected
The datagramsocket.
This isn't in an auto_ptr because one must close the socket prior to deleting it. The nidas::util::Socket destructor does not close the file descriptor.
Referenced by close(), getReadFd(), getWriteFd(), open(), read(), and write().
The documentation for this class was generated from the following files:
nidas/core/UDPSocketIODevice.h
nidas/core/UDPSocketIODevice.cc