nidas: nidas/apps/set_pcmcom8.c File Reference
set_pcmcom8.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <nidas/linux/serial/pcmcom8.h>
Functions
int printConfig (int fd, const char *devname)
int setConfig (int fd, const char *devname, int port0Addr, const int *irqs)
int getNumBoards (int fd, const char *devname)
int getISABaseAddr (int fd, const char *devname, unsigned long *baseaddr)
void usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
getISABaseAddr()
int getISABaseAddr (int fd, const char * devname, unsigned long * baseaddr)
References fd, and PCMCOM8_IOCGISABASE.
Referenced by main().
getNumBoards()
int getNumBoards (int fd, const char * devname)
References fd, and PCMCOM8_IOCGNBOARD.
Referenced by main().
main()
int main (int argc, char ** argv)
References fd, getISABaseAddr(), getNumBoards(), irqs, printConfig(), setConfig(), and usage().
printConfig()
int printConfig (int fd, const char * devname)
References fd, pcmcom8_serial_port::ioport, pcmcom8_serial_port::irq, PCMCOM8_IOCGEEPORTCONFIG, PCMCOM8_IOCGPORTCONFIG, pcmcom8_config::ports, and printf().
Referenced by main().
setConfig()
int setConfig (int fd, const char * devname, int port0Addr, const int * irqs)
References pcmcom8_serial_port::enable, fd, pcmcom8_serial_port::ioport, pcmcom8_serial_port::irq, irqs, PCMCOM8_IOCEECONFIGLOAD, PCMCOM8_IOCPORTENABLE, PCMCOM8_IOCSEEPORTCONFIG, PCMCOM8_IOCSPORTCONFIG, pcmcom8_config::ports, and printf().
Referenced by main().
usage()
void usage (const char * argv0)
Referenced by main().