nidas: nidas::core::DSMConfigIterator Class Reference
nidas::core::DSMConfigIterator Class Reference
Class for iterating over the DSMConfigs of a Project or Site.
#include <NidsIterators.h>
Public Member Functions
DSMConfigIterator (const Project *)
DSMConfigIterator (const Site *)
DSMConfigIterator ()
bool hasNext ()
const DSMConfig * next ()
Private Attributes
SiteIterator _siteIterator
const std::list< const DSMConfig * > * _dsms
std::list< const DSMConfig * >::const_iterator _dsmItr
Detailed Description
Class for iterating over the DSMConfigs of a Project or Site.
Constructor & Destructor Documentation
DSMConfigIterator() [1/3]
DSMConfigIterator::DSMConfigIterator (const Project * obj)
DSMConfigIterator() [2/3]
DSMConfigIterator::DSMConfigIterator (const Site * site)
DSMConfigIterator() [3/3]
DSMConfigIterator::DSMConfigIterator ()
Member Function Documentation
hasNext()
bool DSMConfigIterator::hasNext ()
References _dsmItr, _dsms, _siteIterator, nidas::core::Site::getDSMConfigs(), nidas::core::SiteIterator::hasNext(), and nidas::core::SiteIterator::next().
Referenced by nidas::dynld::UDPSampleOutput::connected(), nidas::core::GetDsmList::execute(), nidas::core::Project::findSampleOutputStreamFileSets(), PConfig::getHostNames(), nidas::core::ProcessorIterator::hasNext(), nidas::core::SensorIterator::hasNext(), PConfig::loadVariables(), main(), DataPrep::matchVariables(), ARLIngest::prepareHeaderIds(), DataDump::run(), DataStats::run(), DmdA2dCk::run(), ExtractFast2D::run(), ExtractDMT::run(), PConfig::showAll(), and nidas::core::Site::toDOMElement().
next()
const DSMConfig* nidas::core::DSMConfigIterator::next () inline
References _dsmItr.
Referenced by nidas::dynld::UDPSampleOutput::connected(), nidas::core::GetDsmList::execute(), nidas::core::ProcessorIterator::hasNext(), nidas::core::SensorIterator::hasNext(), DataPrep::matchVariables(), ARLIngest::prepareHeaderIds(), DataDump::run(), DataStats::run(), DmdA2dCk::run(), ExtractFast2D::run(), and ExtractDMT::run().
Member Data Documentation
_dsmItr
std::list<const DSMConfig*>::const_iterator nidas::core::DSMConfigIterator::_dsmItr private
Referenced by hasNext(), and next().
_dsms
const std::list<const DSMConfig*>* nidas::core::DSMConfigIterator::_dsms private
Referenced by hasNext().
_siteIterator
SiteIterator nidas::core::DSMConfigIterator::_siteIterator private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc