nidas: nidas/apps/nidsmerge.cc File Reference
nidsmerge.cc File Reference
#include <nidas/core/FileSet.h>
#include <nidas/core/Bzip2FileSet.h>
#include <nidas/dynld/SampleInputStream.h>
#include <nidas/dynld/SampleOutputStream.h>
#include <nidas/core/SortedSampleSet.h>
#include <nidas/core/HeaderSource.h>
#include <nidas/util/UTime.h>
#include <nidas/util/EOFException.h>
#include <nidas/core/NidasApp.h>
#include <nidas/core/BadSampleFilter.h>
#include <nidas/util/Logger.h>
#include <unistd.h>
#include <csignal>
#include <climits>
#include <iomanip>
Classes
class NidsMerge
Functions
int main (int argc, char **argv)
void check_fileset (list< string > &filenames, bool &requiretimes)
std::string tformat (dsm_time_t dt)
Function Documentation
check_fileset()
void check_fileset (list< string > & filenames, bool & requiretimes)
Referenced by NidsMerge::parseRunstring().
main()
int main (int argc, char ** argv)
References NidsMerge::main().
tformat()
std::string tformat (dsm_time_t dt) inline
References nidas::util::UTime::format().
Referenced by NidsMerge::flushSorter(), and NidsMerge::run().