nidas: nidas::dynld::raf Namespace Reference
nidas::dynld::raf Namespace Reference
Classes
class A2D_Serial
A2D Serial Sensor.
class A2DBoardTempSensor
The I2C temperature sensor on the ADS3 A2D board.
class ADC_HW_EB7022597
ARINC ADC label processor.
class Aircraft
Aircraft is a sub-class of a measurement Site.
class AlicatSDI
Alicat Flow Controller, used for the SDI.
class Arinc_IRS
An Inertial Reference Sensor (IRS) connected to an ARINC port.
class BCPD_Serial
A class for reading PMS1D probes with the DMT interface conversion.
class CDP_Serial
A class for reading PMS1D probes with the DMT interface conversion.
class CVI_LV_Input
Support for reading the output from the LabView process on the CVI PC.
class CVIOutput
class CVIProcessor
Processor to support Counter-flow Virtual Impactor.
class DSMAnalogSensor
A sensor connected to the DSM A2D.
class SortByRateThenLabel
This is sorts a list of Sample tags by rate (highest first) then by label.
class DSMArincSensor
A sensor connected to an ARINC port.
class DSMMesaSensor
Sensors connected to the Mesa AnythingIO card.
struct PADS_rec
struct P2d_rec
class Probe
class Extract2D
class GPS_HW_HG2021GB02
ARINC IRS label processor.
class IRIGSensor
Sensor class for controlling and recieving data from an IRIG clock.
class IRS_HW_HG2001GD
ARINC IRS label processor.
class IRS_HW_YG1854
ARINC IRS label processor.
class LamsNetSensor
Sensor class supporting the NCAR/EOL Laser Air Motion Sensor (LAMS 3-beam) via Ethernet UDP connection.
class LamsSensor
Sensor class supporting the NCAR/EOL Laser Air Motion Sensor (LAMS) via a DSM.
class LSZ_HW_EB7032239
ARINC LSZ label processor.
class PHIPS_UDP
PHIPS - HALO UDP Sensor.
class PIP_Image
Sensor class to receive PIP images.
class PIP_Serial
A class for reading DMT PIP/CIP probe histogram data.
class PPT_Serial
Honeywell PTT Pressure Transducer Serial Sensor.
class PSI9116_Sensor
Support for sampling a PSI 9116 pressure scanner from EsterLine Pressure Systems.
class SidsNetSensor
Sensor class supporting the NCAR/EOL SID2H modifications via Ethernet UDP connection.
class SPP100_Serial
A class for reading PMS1D probes with the DMT interface conversion.
class SPP200_Serial
A class for reading PMS1D probes with the DMT interface conversion.
class SPP300_Serial
A class for reading PMS1D probes with the DMT interface conversion.
class SppSerial
Base class for many DMT Probes, including SPP100, SPP200, SPP300 and the CDP.
class SyncRecordGenerator
class SyncRecHeaderException
class SyncRecordReader
SyncRecordReader handles sync samples and provides an interface to access Variables and read sync record data.
class SyncRecordSource
class SyncInfo
Parameters needed for each sample to assemble and write a sync record.
class SyncRecordVariable
A Variable associated with a SyncRecord.
struct StopSignal
class SyncServer
class TwoD32_USB
Sensor class for the standard PMS2D probes where the data signals are converted to USB by a converter box.
class TwoD64_USB
Class for the USB Fast-2DC.
class TwoD64_USB_v3
Class for the USB Fast-2DC.
class TwoD_House
A class for reading and parsing the PMS2D Housekeeping (from the old interface, not the new Fast 2DC).
class TwoD_USB
Base class for PMS 2D particle probes on a USB interface.
class UDPArincSensor
ARINC over UDP, data received from the Alta ARINC to Ethernet appliance.
class UDPSocketSensor
nidas::dynld::raf::UPDSocketSensor is the same as a nidas::dynld::UDPSocketSensor, but kept around for legacy reasons - it's in quite a few XMLs.
class UHSAS_Serial
A class for reading the UHSAS probe.
class VCSEL2_Serial
VCSEL2 Serial Sensor.
class VCSEL_Serial
VCSEL Serial Sensor.
class Watlow
Sensor class supporting the NCAR/ACOM Watlow CLS208 Instrument.
Typedefs
typedef struct PADS_rec PADS_rec
typedef struct P2d_rec P2d_rec
typedef unsigned char DMT_UShort[2]
DMT 2-byte ints are packed with byte order 01, where byte 0 is the low-order byte.
typedef unsigned char DMT_ULong[4]
DMT 4-byte ints are packed with byte order 2301, where byte 0 is the low-order byte.
Functions
unsigned short UnpackDMT_UShort (DMT_UShort dmtval)
void PackDMT_UShort (DMT_UShort dmtval, unsigned short val)
unsigned long UnpackDMT_ULong (DMT_ULong dmtval)
void PackDMT_ULong (DMT_ULong dmtval, unsigned long val)
template<typename T , typename V >
void stream_histogram (T &out, V *sizedist, unsigned int nbins)
Variables
const float INHG_MBAR = 33.8639
const float NM_MTR = 1.0 / 1852.0
const float FT_MTR = 0.3048
const float G_MPS2 = 9.7959
const float KTS_MS = 0.514791
const float FPM_MPS = 0.00508
const float RAD_DEG = 180.0 / 3.14159265358979
Typedef Documentation
DMT_ULong
typedef unsigned char nidas::dynld::raf::DMT_ULong[4]
DMT 4-byte ints are packed with byte order 2301, where byte 0 is the low-order byte.
DMT_ULong is an opaque 4-byte value (just a 4-byte unsigned char array) in DMT order.
UnpackDMT_ULong unpacks a DMT_ULong as a local unsigned long.
PackDMT_ULong packs a local unsigned long into a DMT_ULong.
DMT_UShort
typedef unsigned char nidas::dynld::raf::DMT_UShort[2]
DMT 2-byte ints are packed with byte order 01, where byte 0 is the low-order byte.
DMT_UShort is an opaque 2-byte value (just a 2-byte unsigned char array) in DMT order.
UnpackDMT_UShort unpacks a DMT_UShort as a local unsigned short.
PackDMT_UShort packs a local unsigned short into a DMT_UShort.
P2d_rec
typedef struct P2d_rec nidas::dynld::raf::P2d_rec
PADS_rec
typedef struct PADS_rec nidas::dynld::raf::PADS_rec
Function Documentation
PackDMT_ULong()
void nidas::dynld::raf::PackDMT_ULong (DMT_ULong dmtval, unsigned long val) inline
Referenced by nidas::dynld::raf::PIP_Serial::derivedDataNotify().
PackDMT_UShort()
void nidas::dynld::raf::PackDMT_UShort (DMT_UShort dmtval, unsigned short val) inline
Referenced by nidas::dynld::raf::PIP_Serial::derivedDataNotify(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::PIP_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP300_Serial::sendInitString(), and nidas::dynld::raf::PIP_Serial::sendTimePacket().
stream_histogram()
template<typename T , typename V > void nidas::dynld::raf::stream_histogram (T & out, V * sizedist, unsigned int nbins) inline
Referenced by nidas::dynld::raf::TwoD_USB::countParticle(), and nidas::dynld::raf::TwoD64_USB::process().
UnpackDMT_ULong()
unsigned long nidas::dynld::raf::UnpackDMT_ULong (DMT_ULong dmtval) inline
Referenced by nidas::dynld::raf::BCPD_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), and nidas::dynld::raf::SPP300_Serial::process().
UnpackDMT_UShort()
unsigned short nidas::dynld::raf::UnpackDMT_UShort (DMT_UShort dmtval) inline
Referenced by nidas::dynld::raf::PIP_Serial::appendDataAndFindGood(), nidas::dynld::raf::SppSerial::appendDataAndFindGood(), nidas::dynld::raf::BCPD_Serial::process(), nidas::dynld::raf::CDP_Serial::process(), nidas::dynld::raf::PIP_Serial::process(), nidas::dynld::raf::SPP100_Serial::process(), nidas::dynld::raf::SPP200_Serial::process(), and nidas::dynld::raf::SPP300_Serial::process().
Variable Documentation
FPM_MPS
const float nidas::dynld::raf::FPM_MPS = 0.00508
Referenced by nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::IRS_HW_YG1854::processLabel().
FT_MTR
const float nidas::dynld::raf::FT_MTR = 0.3048
Referenced by nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::IRS_HW_YG1854::processLabel().
G_MPS2
const float nidas::dynld::raf::G_MPS2 = 9.7959
Referenced by nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::IRS_HW_YG1854::processLabel().
INHG_MBAR
const float nidas::dynld::raf::INHG_MBAR = 33.8639
Referenced by nidas::dynld::raf::ADC_HW_EB7022597::processLabel().
KTS_MS
const float nidas::dynld::raf::KTS_MS = 0.514791
Referenced by nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::IRS_HW_YG1854::processLabel().
NM_MTR
const float nidas::dynld::raf::NM_MTR = 1.0 / 1852.0
Referenced by nidas::dynld::raf::IRS_HW_HG2001GD::processLabel().
RAD_DEG
const float nidas::dynld::raf::RAD_DEG = 180.0 / 3.14159265358979
Referenced by nidas::dynld::raf::IRS_HW_HG2001GD::processLabel().