nidas: nidas::util::McSocketDatagram Class Reference
nidas::util::McSocketDatagram Class Reference
Datagram that is multicast by a host when it wants a service.
#include <McSocket.h>
Public Member Functions
McSocketDatagram (int requestType=-1)
McSocketDatagram (const McSocketDatagram &x)
Copy constructor.
McSocketDatagram & operator= (const McSocketDatagram &rhs)
Assignment operator.
int getMagic () const
void setMagic (int val)
int getRequestType () const
void setRequestType (int val)
int getRequesterListenPort () const
What port is the requester listening on for the connection back?
void setRequesterListenPort (int val)
int getSocketType () const
What socket type does the requester want to establish? SOCK_STREAM or SOCK_DGRAM.
void setSocketType (int val)
virtual void * getDataVoidPtr ()
Get the pointer to the data portion of the packet.
virtual const void * getConstDataVoidPtr () const
McSocketData * getData ()
void setData (McSocketData *val)
Set the pointer to the data portion of the packet.
SocketAddress & getSocketAddress () const
void setSocketAddress (const SocketAddress &val)
struct sockaddr * getSockAddrPtr ()
const struct sockaddr * getConstSockAddrPtr () const
int getSockAddrLen () const
virtual void setLength (int val)
Set the value for the current number of bytes in data.
virtual int getLength () const
Get the value for the current number of bytes in data.
void setMaxLength (int val)
Set the allocated length in bytes of the data.
int getMaxLength () const
Return the allocated length in bytes of the data.
Static Public Attributes
static const int magicVal = 0x01234567
Magic value that should be found at the beginning of all received McSocketDatagrams.
Protected Attributes
struct McSocketData mcdata
McSocketData * data
int maxlength
allocated length in bytes of contents.
int length
length of datagram that was read or will be sent.
SocketAddress * addr
The destination address for a send, or the remote senders address after a receive.
Detailed Description
Datagram that is multicast by a host when it wants a service.
A McSocketDatagram contains the address of the sending host, a port number that the sending host is listening on, the type of connection required (SOCK_STREAM or SOCK_DGRAM), and the type of the service requested.
Constructor & Destructor Documentation
McSocketDatagram() [1/2]
McSocketDatagram::McSocketDatagram (int requestType = -1)
References setRequestType().
McSocketDatagram() [2/2]
McSocketDatagram::McSocketDatagram (const McSocketDatagram & x)
Copy constructor.
References nidas::util::DatagramPacketT< McSocketData >::data, and mcdata.
Member Function Documentation
getConstDataVoidPtr()
virtual const void* nidas::util::DatagramPacketT< McSocketData >::getConstDataVoidPtr () const inline virtual inherited
Implements nidas::util::DatagramPacketBase.
getConstSockAddrPtr()
const struct sockaddr* nidas::util::DatagramPacketBase::getConstSockAddrPtr () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getConstSockAddrPtr().
Referenced by nidas::util::SocketImpl::send().
getData()
McSocketData * nidas::util::DatagramPacketT< McSocketData >::getData () inline inherited
getDataVoidPtr()
virtual void* nidas::util::DatagramPacketT< McSocketData >::getDataVoidPtr () inline virtual inherited
Get the pointer to the data portion of the packet.
Implements nidas::util::DatagramPacketBase.
getLength()
virtual int nidas::util::DatagramPacketBase::getLength () const inline virtual inherited
Get the value for the current number of bytes in data.
Either the number of bytes read in a received packet, or the number of bytes to send().
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket(), PacketReader::logBadPacket(), PacketReader::loop(), WriterThread::run(), nidas::core::DerivedDataReader::run(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
getMagic()
int nidas::util::McSocketDatagram::getMagic () const inline
References nidas::util::McSocketData::magic, and mcdata.
Referenced by nidas::util::McSocketListener::run().
getMaxLength()
int nidas::util::DatagramPacketBase::getMaxLength () const inline inherited
Return the allocated length in bytes of the data.
References nidas::util::DatagramPacketBase::maxlength.
Referenced by PacketReader::loop(), and nidas::util::SocketImpl::receive().
getRequesterListenPort()
int nidas::util::McSocketDatagram::getRequesterListenPort () const inline
What port is the requester listening on for the connection back?
References nidas::util::McSocketData::_listenPort, and mcdata.
Referenced by nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
getRequestType()
int nidas::util::McSocketDatagram::getRequestType () const inline
References nidas::util::McSocketData::_requestType, and mcdata.
Referenced by nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
getSockAddrLen()
int nidas::util::DatagramPacketBase::getSockAddrLen () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrLen().
Referenced by nidas::util::SocketImpl::receive(), and nidas::util::SocketImpl::send().
getSockAddrPtr()
struct sockaddr* nidas::util::DatagramPacketBase::getSockAddrPtr () inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrPtr().
Referenced by nidas::util::SocketImpl::receive().
getSocketAddress()
SocketAddress& nidas::util::DatagramPacketBase::getSocketAddress () const inline inherited
References nidas::util::DatagramPacketBase::addr.
Referenced by PacketReader::logBadPacket(), PacketReader::loop(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), and nidas::util::SocketImpl::send().
getSocketType()
int nidas::util::McSocketDatagram::getSocketType () const inline
What socket type does the requester want to establish? SOCK_STREAM or SOCK_DGRAM.
References nidas::util::McSocketData::_socketType, and mcdata.
Referenced by nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
operator=()
McSocketDatagram & McSocketDatagram::operator= (const McSocketDatagram & rhs)
Assignment operator.
References nidas::util::DatagramPacketT< McSocketData >::data, and mcdata.
setData()
void nidas::util::DatagramPacketT< McSocketData >::setData (McSocketData * val) inline inherited
Set the pointer to the data portion of the packet.
/param val Pointer to an allocated section of memory. This pointer is owned by the caller, it is not deleted by the DatagramPacket destructor.
setLength()
virtual void nidas::util::DatagramPacketBase::setLength (int val) inline virtual inherited
Set the value for the current number of bytes in data.
/param val Number of bytes, must be <= max length.
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket(), and nidas::util::SocketImpl::receive().
setMagic()
void nidas::util::McSocketDatagram::setMagic (int val) inline
References nidas::util::McSocketData::magic, and mcdata.
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
setMaxLength()
void nidas::util::DatagramPacketBase::setMaxLength (int val) inline inherited
Set the allocated length in bytes of the data.
/param val Number of bytes allocated in data.
References nidas::util::DatagramPacketBase::maxlength.
setRequesterListenPort()
void nidas::util::McSocketDatagram::setRequesterListenPort (int val) inline
References nidas::util::McSocketData::_listenPort, and mcdata.
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
setRequestType()
void nidas::util::McSocketDatagram::setRequestType (int val) inline
References nidas::util::McSocketData::_requestType, and mcdata.
Referenced by McSocketDatagram(), and nidas::util::McSocketMulticaster< SocketTT >::run().
setSocketAddress()
void nidas::util::DatagramPacketBase::setSocketAddress (const SocketAddress & val) inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::clone().
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
setSocketType()
void nidas::util::McSocketDatagram::setSocketType (int val) inline
References nidas::util::McSocketData::_socketType, and mcdata.
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
Member Data Documentation
addr
SocketAddress* nidas::util::DatagramPacketBase::addr protected inherited
The destination address for a send, or the remote senders address after a receive.
Referenced by nidas::util::DatagramPacketBase::getConstSockAddrPtr(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSockAddrPtr(), nidas::util::DatagramPacketBase::getSocketAddress(), nidas::util::DatagramPacketBase::operator=(), nidas::util::DatagramPacketBase::setSocketAddress(), and nidas::util::DatagramPacketBase::~DatagramPacketBase().
data
McSocketData * nidas::util::DatagramPacketT< McSocketData >::data protected inherited
length
int nidas::util::DatagramPacketBase::length protected inherited
length of datagram that was read or will be sent.
Must be <= maxlength.
Referenced by nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setLength().
magicVal
const int McSocketDatagram::magicVal = 0x01234567 static
Magic value that should be found at the beginning of all received McSocketDatagrams.
Referenced by nidas::util::McSocketListener::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
maxlength
int nidas::util::DatagramPacketBase::maxlength protected inherited
allocated length in bytes of contents.
Referenced by nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setMaxLength().
mcdata
struct McSocketData nidas::util::McSocketDatagram::mcdata protected
Referenced by getMagic(), getRequesterListenPort(), getRequestType(), getSocketType(), McSocketDatagram(), operator=(), setMagic(), setRequesterListenPort(), setRequestType(), and setSocketType().
The documentation for this class was generated from the following files:
nidas/util/McSocket.h
nidas/util/McSocket.cc