nidas: nidas::core::SensorIterator Class Reference
nidas::core::SensorIterator Class Reference
Class for iterating over the DSMSensors of a Project, Site, or DSMConfig.
#include <NidsIterators.h>
Public Member Functions
SensorIterator (const Project *)
SensorIterator (const Site *)
SensorIterator (const DSMConfig *)
SensorIterator ()
bool hasNext ()
DSMSensor * next ()
Private Attributes
DSMConfigIterator _dsmIterator
const std::list< DSMSensor * > * _sensors
std::list< DSMSensor * >::const_iterator _sensorItr
Detailed Description
Class for iterating over the DSMSensors of a Project, Site, or DSMConfig.
Constructor & Destructor Documentation
SensorIterator() [1/4]
SensorIterator::SensorIterator (const Project * obj)
SensorIterator() [2/4]
SensorIterator::SensorIterator (const Site * obj)
SensorIterator() [3/4]
SensorIterator::SensorIterator (const DSMConfig * obj)
SensorIterator() [4/4]
SensorIterator::SensorIterator ()
Member Function Documentation
hasNext()
bool SensorIterator::hasNext ()
References _dsmIterator, _sensorItr, _sensors, nidas::core::DSMConfig::getSensors(), nidas::core::DSMConfigIterator::hasNext(), and nidas::core::DSMConfigIterator::next().
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMEngine::connectProcessors(), nidas::core::Site::findSensor(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::dynld::raf::SyncServer::initSensors(), PConfig::loadVariables(), parseAnalog(), parseOther(), ARLIngest::prepareHeaderIds(), StatsProcess::run(), nidas::core::DSMServerStat::run(), nidas::dynld::RawSampleService::schedule(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromProject(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::DSMConfig::toDOMElement(), nidas::core::DSMConfig::validate(), and nidas::core::Site::validate().
next()
DSMSensor* nidas::core::SensorIterator::next () inline
References _sensorItr.
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMEngine::connectProcessors(), nidas::core::Site::findSensor(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::dynld::raf::SyncServer::initSensors(), ARLIngest::prepareHeaderIds(), StatsProcess::run(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::raf::SyncRecordSource::selectVariablesFromProject().
Member Data Documentation
_dsmIterator
DSMConfigIterator nidas::core::SensorIterator::_dsmIterator private
Referenced by hasNext().
_sensorItr
std::list<DSMSensor*>::const_iterator nidas::core::SensorIterator::_sensorItr private
Referenced by hasNext(), and next().
_sensors
const std::list<DSMSensor*>* nidas::core::SensorIterator::_sensors private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc