nidas: nidas::core::SiteIterator Class Reference
nidas::core::SiteIterator Class Reference
Class for iterating over the Sites of a Project, or the Sites served by a DSMServer.
#include <NidsIterators.h>
Public Member Functions
SiteIterator (const Project *)
SiteIterator ()
bool hasNext ()
Site * next ()
Private Attributes
const std::list< Site * > * _sites
std::list< Site * >::const_iterator _siteItr
Detailed Description
Class for iterating over the Sites of a Project, or the Sites served by a DSMServer.
Constructor & Destructor Documentation
SiteIterator() [1/2]
SiteIterator::SiteIterator (const Project * obj)
SiteIterator() [2/2]
SiteIterator::SiteIterator ()
Member Function Documentation
hasNext()
bool SiteIterator::hasNext ()
References _siteItr, and _sites.
Referenced by nidas::dynld::UDPSampleOutput::connected(), nidas::core::Project::findDSM(), nidas::core::Project::findSensor(), PConfig::getHostNames(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::core::DSMServerIterator::hasNext(), nidas::core::DSMConfigIterator::hasNext(), PConfig::loadVariables(), PConfig::showAll(), PConfig::showCalFiles(), and nidas::core::Project::toDOMElement().
next()
Site* nidas::core::SiteIterator::next () inline
References _siteItr.
Referenced by nidas::dynld::UDPSampleOutput::connected(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::core::DSMServerIterator::hasNext(), and nidas::core::DSMConfigIterator::hasNext().
Member Data Documentation
_siteItr
std::list<Site*>::const_iterator nidas::core::SiteIterator::_siteItr private
Referenced by hasNext(), and next().
_sites
const std::list<Site*>* nidas::core::SiteIterator::_sites private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc