nidas: nidas::dynld::raf::SyncRecordGenerator Class Reference
nidas::dynld::raf::SyncRecordGenerator Class Reference
#include <SyncRecordGenerator.h>
Public Member Functions
SyncRecordGenerator ()
Constructor.
virtual ~SyncRecordGenerator ()
void connectSource (SampleSource *source) override
Implementation of SampleIOProcessor::connectSource(SampleSource*).
void disconnectSource (SampleSource *source) throw ()
Implementation of SampleIOProcessor::disconnectSource(SampleSource*).
void connect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::connect(SampleOutput*).
void disconnect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
void sendHeader (dsm_time_t thead, SampleOutput *output)
Method called to write a header to an SampleOutput.
void init (dsm_time_t sampleTime) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of SampleSource::flush().
const SampleStats & getSampleStats () const
void printStatus (std::ostream &, float deltat, int &) throw ()
SyncRecordSource * getSyncRecordSource ()
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addRequestedSampleTag (SampleTag *tag)
Add a request for a SampleTag from this SampleIOProcessor.
virtual std::list< const SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node)
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Protected Member Functions
void scanSensors (const std::list< DSMSensor * > &sensors)
void allocateRecord (dsm_time_t timetag)
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
SyncRecordGenerator (const SyncRecordGenerator &)
No copying.
SyncRecordGenerator & operator= (const SyncRecordGenerator &)
No assignment.
Private Attributes
nidas::util::Mutex _connectionMutex
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
SyncRecordSource _syncRecSource
size_t _numInputSampsLast
size_t _numOutputSampsLast
long long _numInputBytesLast
long long _numOutputBytesLast
std::string _name
dsm_sample_id_t _id
std::list< const SampleTag * > _constRequestedTags
std::list< SampleOutput * > _origOutputs
bool _optional
const DSMService * _service
What service am I a part of?
const DSMConfig * _dsm
Or, what DSM am I a part of?
std::list< Parameter * > _parameters
std::list< const Parameter * > _constParameters
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
SyncRecordGenerator() [1/2]
SyncRecordGenerator::SyncRecordGenerator ()
Constructor.
References nidas::core::SampleIOProcessor::setName().
~SyncRecordGenerator()
SyncRecordGenerator::~SyncRecordGenerator () virtual
References _connectedOutputs, _connectionMutex, _syncRecSource, nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, nidas::dynld::raf::SyncRecordSource::removeSampleClient(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
SyncRecordGenerator() [2/2]
nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator (const SyncRecordGenerator &) private
No copying.
Member Function Documentation
addOutput()
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
addParameter()
void SampleIOProcessor::addParameter (Parameter * val) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
Exceptions
nidas::util::InvalidParameterException
References nidas::core::SampleIOProcessor::_constParameters, and nidas::core::SampleIOProcessor::_parameters.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
addRequestedSampleTag()
void SampleIOProcessor::addRequestedSampleTag (SampleTag * tag) virtual inherited
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::StatisticsProcessor, and nidas::dynld::raf::CVIProcessor.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::raf::CVIProcessor::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), and nidas::core::SampleIOProcessor::fromDOMElement().
addSampleClient()
void SyncRecordGenerator::addSampleClient (SampleClient * client) throw () virtual
Implementation of SampleSource::addSampleClient().
Reimplemented from nidas::core::SampleIOProcessor.
References DLOG.
Referenced by nidas::dynld::raf::SyncServer::init().
addSampleClientForTag()
void nidas::dynld::raf::SyncRecordGenerator::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Reimplemented from nidas::core::SampleIOProcessor.
addSampleTag()
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::StatisticsProcessor::connectSource().
allocateRecord()
void nidas::dynld::raf::SyncRecordGenerator::allocateRecord (dsm_time_t timetag) protected
connect()
void SyncRecordGenerator::connect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::connect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
References ILOG.
Referenced by nidas::dynld::raf::SyncServer::init().
connectSource()
void SyncRecordGenerator::connectSource (SampleSource * source) override virtual
Implementation of SampleIOProcessor::connectSource(SampleSource*).
Implements nidas::core::SampleIOProcessor.
References _connectedSources, _connectionMutex, _syncRecSource, nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), nidas::dynld::raf::SyncRecordSource::connect(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::core::SampleIOProcessor::getOutputs(), and nidas::dynld::raf::SyncRecordSource::getSampleTags().
Referenced by nidas::dynld::raf::SyncServer::init().
disconnect()
void SyncRecordGenerator::disconnect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), ILOG, nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Referenced by nidas::dynld::raf::SyncServer::stop().
disconnectSource()
void SyncRecordGenerator::disconnectSource (SampleSource * source) throw () virtual
Implementation of SampleIOProcessor::disconnectSource(SampleSource*).
Implements nidas::core::SampleIOProcessor.
Referenced by nidas::dynld::raf::SyncServer::stop().
flush()
void nidas::dynld::raf::SyncRecordGenerator::flush () throw () inline virtual
Implementation of SampleSource::flush().
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::raf::SyncServer::stop().
fromDOMElement()
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::SampleIOProcessor::_origOutputs, nidas::core::SampleIOProcessor::addOutput(), nidas::core::SampleIOProcessor::addParameter(), nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::SampleTag::fromDOMElement(), nidas::core::DOMable::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::SampleIOProcessor::getId(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleTag::getSampleId(), nidas::core::XDOMAttr::getValue(), nidas::core::SampleIOProcessor::setOptional(), nidas::core::SampleIOProcessor::setSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), and nidas::dynld::raf::CVIProcessor::fromDOMElement().
getClientCount()
int nidas::dynld::raf::SyncRecordGenerator::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Reimplemented from nidas::core::SampleIOProcessor.
getDSMConfig()
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
getId()
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
getName()
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getOutputs()
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::SampleArchiver::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), connectSource(), nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
getParameters()
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
getProcessedSampleSource()
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
getRawSampleSource()
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
getRequestedSampleTags()
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
getSampleId()
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
getSampleStats()
const SampleStats& nidas::dynld::raf::SyncRecordGenerator::getSampleStats () const inline virtual
Reimplemented from nidas::core::SampleIOProcessor.
getSampleTagIterator()
SampleTagIterator nidas::dynld::raf::SyncRecordGenerator::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Reimplemented from nidas::core::SampleIOProcessor.
getSampleTags()
std::list<const SampleTag*> nidas::dynld::raf::SyncRecordGenerator::getSampleTags () const inline virtual
Implementation of SampleSource::getSampleTags().
Reimplemented from nidas::core::SampleIOProcessor.
getService()
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
getSyncRecordSource()
SyncRecordSource* nidas::dynld::raf::SyncRecordGenerator::getSyncRecordSource () inline
init()
void SyncRecordGenerator::init (dsm_time_t sampleTime) throw () virtual
Reimplemented from nidas::core::SampleIOProcessor.
References DLOG.
Referenced by nidas::dynld::raf::SyncServer::init().
isOptional()
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
operator=()
SyncRecordGenerator& nidas::dynld::raf::SyncRecordGenerator::operator= (const SyncRecordGenerator &) private
No assignment.
printStatus()
void SyncRecordGenerator::printStatus (std::ostream & , float deltat, int &) throw () virtual
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::util::UTime::format(), nidas::core::SampleStats::getLastTimeTag(), nidas::core::SampleStats::getNumBytes(), nidas::core::SampleStats::getNumSamples(), and nidas::core::SampleSource::getSampleStats().
removeRequestedSampleTag()
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
removeSampleClient()
void nidas::dynld::raf::SyncRecordGenerator::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Reimplemented from nidas::core::SampleIOProcessor.
Referenced by nidas::dynld::raf::SyncServer::stop().
removeSampleClientForTag()
void nidas::dynld::raf::SyncRecordGenerator::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Reimplemented from nidas::core::SampleIOProcessor.
removeSampleTag()
void SampleIOProcessor::removeSampleTag (const SampleTag *) throw () virtual inherited
Exceptions
Implements nidas::core::SampleSource.
scanSensors()
void nidas::dynld::raf::SyncRecordGenerator::scanSensors (const std::list< DSMSensor * > & sensors) protected
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and sendHeader().
sendHeader()
void SyncRecordGenerator::sendHeader (dsm_time_t thead, SampleOutput * output) virtual
Method called to write a header to an SampleOutput.
Exceptions
nidas::util::IOException
Implements nidas::core::HeaderSource.
References _syncRecSource, DLOG, nidas::core::HeaderSource::sendDefaultHeader(), and nidas::dynld::raf::SyncRecordSource::sendSyncHeader().
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
setDSMConfig()
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
setName()
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and SyncRecordGenerator().
setOptional()
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
setSampleId()
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement().
setService()
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_connectedOutputs
std::set<SampleOutput*> nidas::dynld::raf::SyncRecordGenerator::_connectedOutputs private
Referenced by ~SyncRecordGenerator().
_connectedSources
std::set<SampleSource*> nidas::dynld::raf::SyncRecordGenerator::_connectedSources private
Referenced by connectSource().
_connectionMutex
nidas::util::Mutex nidas::dynld::raf::SyncRecordGenerator::_connectionMutex private
Referenced by connectSource(), and ~SyncRecordGenerator().
_constParameters
std::list<const Parameter*> nidas::core::SampleIOProcessor::_constParameters private inherited
Referenced by nidas::core::SampleIOProcessor::addParameter(), and nidas::core::SampleIOProcessor::getParameters().
_constRequestedTags
std::list<const SampleTag*> nidas::core::SampleIOProcessor::_constRequestedTags private inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), and nidas::core::SampleIOProcessor::removeRequestedSampleTag().
_dsm
const DSMConfig* nidas::core::SampleIOProcessor::_dsm private inherited
Or, what DSM am I a part of?
Referenced by nidas::core::SampleIOProcessor::getDSMConfig(), and nidas::core::SampleIOProcessor::setDSMConfig().
_id
dsm_sample_id_t nidas::core::SampleIOProcessor::_id private inherited
Referenced by nidas::core::SampleIOProcessor::getId(), nidas::core::SampleIOProcessor::getSampleId(), and nidas::core::SampleIOProcessor::setSampleId().
_name
std::string nidas::core::SampleIOProcessor::_name private inherited
Referenced by nidas::core::SampleIOProcessor::getName(), and nidas::core::SampleIOProcessor::setName().
_numInputBytesLast
long long nidas::dynld::raf::SyncRecordGenerator::_numInputBytesLast private
_numInputSampsLast
size_t nidas::dynld::raf::SyncRecordGenerator::_numInputSampsLast private
_numOutputBytesLast
long long nidas::dynld::raf::SyncRecordGenerator::_numOutputBytesLast private
_numOutputSampsLast
size_t nidas::dynld::raf::SyncRecordGenerator::_numOutputSampsLast private
_optional
bool nidas::core::SampleIOProcessor::_optional private inherited
Referenced by nidas::core::SampleIOProcessor::isOptional(), and nidas::core::SampleIOProcessor::setOptional().
_origOutputs
std::list<SampleOutput*> nidas::core::SampleIOProcessor::_origOutputs private inherited
Referenced by nidas::core::SampleIOProcessor::addOutput(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleIOProcessor::getOutputs(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_parameters
std::list<Parameter*> nidas::core::SampleIOProcessor::_parameters private inherited
Referenced by nidas::core::SampleIOProcessor::addParameter(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_requestedTags
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
_service
const DSMService* nidas::core::SampleIOProcessor::_service private inherited
What service am I a part of?
Referenced by nidas::core::SampleIOProcessor::getService(), and nidas::core::SampleIOProcessor::setService().
_source
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
_syncRecSource
SyncRecordSource nidas::dynld::raf::SyncRecordGenerator::_syncRecSource private
Referenced by connectSource(), sendHeader(), and ~SyncRecordGenerator().
_tagsMutex
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/raf/SyncRecordGenerator.h
nidas/dynld/raf/SyncRecordGenerator.cc