nidas: nidas::dynld::XMLConfigAllService Class Reference
nidas::dynld::XMLConfigAllService Class Reference
#include <XMLConfigAllService.h>
Public Member Functions
XMLConfigAllService ()
nidas::core::IOChannelRequester * connected (IOChannel *) throw ()
nidas::core::McSocketRequest getRequestType () const
void interrupt () throw ()
void connect (SampleInput *) throw ()
void disconnect (SampleInput *) throw ()
void schedule (bool optionalProcessing)
schedule this service to run.
const std::string & getName () const
virtual void setDSMServer (DSMServer *val)
virtual DSMServer * getDSMServer () const
virtual void addProcessor (SampleIOProcessor *proc)
Add a processor to this RawSampleService.
virtual const std::list< SampleIOProcessor * > & getProcessors () const
const std::list< SampleInput * > & getInputs () const
ProcessorIterator getProcessorIterator () const
virtual int checkSubThreads () throw ()
virtual void cancel () throw ()
virtual int join () throw ()
void fromDOMElement (const xercesc::DOMElement *node)
nidas::util::Thread::SchedPolicy getSchedPolicy () const
int getSchedPriority () const
virtual void printClock (std::ostream &) throw ()
virtual void printStatus (std::ostream &, float) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void addSubThread (nidas::util::Thread *) throw ()
Protected Attributes
std::string _name
DSMServer * _server
std::set< nidas::util::Thread * > _subThreads
nidas::util::Mutex _subThreadMutex
std::list< SampleInput * > _inputs
std::list< SampleIOProcessor * > _processors
std::list< IOChannel * > _ochans
nidas::util::Thread::SchedPolicy _threadPolicy
int _threadPriority
Private Member Functions
XMLConfigAllService (const XMLConfigService &)
Copying not supported.
XMLConfigAllService & operator= (const XMLConfigService &)
Assignment not supported.
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
XMLConfigAllService() [1/2]
XMLConfigAllService::XMLConfigAllService ()
XMLConfigAllService() [2/2]
nidas::dynld::XMLConfigAllService::XMLConfigAllService (const XMLConfigService &) private
Copying not supported.
Member Function Documentation
addProcessor()
virtual void nidas::core::DSMService::addProcessor (SampleIOProcessor * proc) inline virtual inherited
Add a processor to this RawSampleService.
This is done at configuration (XML) time.
References nidas::core::DSMService::_processors.
Referenced by nidas::core::DSMService::fromDOMElement().
addSubThread()
void DSMService::addSubThread (nidas::util::Thread * thd) throw () protected inherited
cancel()
void DSMService::cancel () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Thread::cancel(), nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
checkSubThreads()
int DSMService::checkSubThreads () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
connect()
void nidas::dynld::XMLConfigService::connect (SampleInput *) throw () inline virtual inherited
Implements nidas::core::DSMService.
connected()
IOChannelRequester * XMLConfigAllService::connected (IOChannel * iochan) throw () virtual
Implements nidas::core::IOChannelRequester.
References nidas::util::Thread::start().
disconnect()
void nidas::dynld::XMLConfigService::disconnect (SampleInput *) throw () inline inherited
fromDOMElement()
void DSMService::fromDOMElement (const xercesc::DOMElement * node) virtual inherited
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::RawSampleService.
References nidas::core::DSMService::_inputs, nidas::core::DSMService::_ochans, nidas::core::DSMService::_threadPolicy, nidas::core::DSMService::_threadPriority, nidas::core::DSMService::addProcessor(), nidas::core::IOChannel::createIOChannel(), nidas::core::DOMObjectFactory::createObject(), nidas::core::ServiceCatalog::find(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMService::getDSMServer(), nidas::util::Logger::getInstance(), nidas::core::DSMService::getName(), nidas::core::Project::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::DSMServer::getProject(), nidas::core::Project::getServiceCatalog(), nidas::core::XDOMAttr::getValue(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_RR, nidas::core::SampleIOProcessor::setService(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::fromDOMElement(), and nidas::dynld::RawSampleService::fromDOMElement().
getClassName()
const string DSMService::getClassName (const xercesc::DOMElement * node, const Project * project) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::ServiceCatalog::find(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::Project::getServiceCatalog().
Referenced by nidas::core::DSMServer::fromDOMElement().
getDSMServer()
virtual DSMServer* nidas::core::DSMService::getDSMServer () const inline virtual inherited
References nidas::core::DSMService::_server.
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::dynld::RawSampleService::fromDOMElement().
getInputs()
const std::list<SampleInput*>& nidas::core::DSMService::getInputs () const inline inherited
References nidas::core::DSMService::_inputs.
getName()
const std::string& nidas::core::DSMService::getName () const inline inherited
References nidas::core::DSMService::_name.
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::DSMServer::joinServices(), and nidas::core::DSMServer::~DSMServer().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getProcessorIterator()
ProcessorIterator DSMService::getProcessorIterator () const inherited
Referenced by nidas::dynld::RawSampleService::printStatus().
getProcessors()
virtual const std::list<SampleIOProcessor*>& nidas::core::DSMService::getProcessors () const inline virtual inherited
References nidas::core::DSMService::_processors.
Referenced by nidas::core::ProcessorIterator::hasNext().
getRequestType()
nidas::core::McSocketRequest nidas::dynld::XMLConfigAllService::getRequestType () const inline virtual
Reimplemented from nidas::dynld::XMLConfigService.
References nidas::core::XML_ALL_CONFIG.
getSchedPolicy()
nidas::util::Thread::SchedPolicy nidas::core::DSMService::getSchedPolicy () const inline inherited
References nidas::core::DSMService::_threadPolicy.
getSchedPriority()
int nidas::core::DSMService::getSchedPriority () const inline inherited
References nidas::core::DSMService::_threadPriority.
interrupt()
void XMLConfigService::interrupt () throw () virtual inherited
Reimplemented from nidas::core::DSMService.
References nidas::core::IOChannel::close(), and nidas::core::DSMService::interrupt().
join()
int DSMService::join () throw () virtual inherited
References nidas::core::DSMService::_subThreadMutex, nidas::core::DSMService::_subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, nidas::util::Thread::RUN_OK, and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::joinServices(), and nidas::dynld::RawSampleService::~RawSampleService().
operator=()
XMLConfigAllService& nidas::dynld::XMLConfigAllService::operator= (const XMLConfigService &) private
Assignment not supported.
printClock()
virtual void nidas::core::DSMService::printClock (std::ostream &) throw () inline virtual inherited
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
printStatus()
virtual void nidas::core::DSMService::printStatus (std::ostream & , float) throw () inline virtual inherited
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
schedule()
void XMLConfigService::schedule (bool optionalProcessing) virtual inherited
schedule this service to run.
Exceptions
nidas::util::Exception
Implements nidas::core::DSMService.
References nidas::core::IOChannel::requestConnection(), and nidas::core::IOChannel::setRequestType().
setDSMServer()
void DSMService::setDSMServer (DSMServer * val) virtual inherited
References nidas::core::DSMService::_server.
Referenced by nidas::core::DSMServer::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
_inputs
std::list<SampleInput*> nidas::core::DSMService::_inputs protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::DSMService::getInputs(), and nidas::core::DSMService::~DSMService().
_name
std::string nidas::core::DSMService::_name protected inherited
Referenced by nidas::core::DSMService::getName().
_ochans
std::list<IOChannel*> nidas::core::DSMService::_ochans protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::~DSMService().
_processors
std::list<SampleIOProcessor*> nidas::core::DSMService::_processors protected inherited
Referenced by nidas::core::DSMService::addProcessor(), nidas::core::DSMService::getProcessors(), and nidas::core::DSMService::~DSMService().
_server
DSMServer* nidas::core::DSMService::_server protected inherited
Referenced by nidas::core::DSMService::getDSMServer(), and nidas::core::DSMService::setDSMServer().
_subThreadMutex
nidas::util::Mutex nidas::core::DSMService::_subThreadMutex protected inherited
Referenced by nidas::core::DSMService::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::DSMService::interrupt(), and nidas::core::DSMService::join().
_subThreads
std::set<nidas::util::Thread*> nidas::core::DSMService::_subThreads protected inherited
Referenced by nidas::core::DSMService::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::DSMService::interrupt(), and nidas::core::DSMService::join().
_threadPolicy
nidas::util::Thread::SchedPolicy nidas::core::DSMService::_threadPolicy protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::getSchedPolicy().
_threadPriority
int nidas::core::DSMService::_threadPriority protected inherited
Referenced by nidas::core::DSMService::fromDOMElement(), and nidas::core::DSMService::getSchedPriority().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/XMLConfigAllService.h
nidas/dynld/XMLConfigAllService.cc