nidas: nidas::core::SensorHandler::NotifyPipe Class Reference
nidas::core::SensorHandler::NotifyPipe Class Reference
Public Member Functions
NotifyPipe (SensorHandler *handler)
~NotifyPipe ()
bool handlePollEvents (uint32_t events)
void close ()
void notify ()
Used in public methods of SensorHandler which are called from other threads to notify the SensorHandler that the collection of polled objects has changed.
int getFd () const
Private Member Functions
NotifyPipe (const NotifyPipe &)
NotifyPipe & operator= (const NotifyPipe &)
Private Attributes
int _fds [2]
SensorHandler * _handler
Constructor & Destructor Documentation
NotifyPipe() [1/2]
SensorHandler::NotifyPipe::NotifyPipe (SensorHandler * handler)
References _fds, _handler, and nidas::core::SensorHandler::getEpollFd().
~NotifyPipe()
SensorHandler::NotifyPipe::~NotifyPipe ()
References PLOG, and nidas::util::Exception::what().
NotifyPipe() [2/2]
nidas::core::SensorHandler::NotifyPipe::NotifyPipe (const NotifyPipe &) private
Member Function Documentation
close()
void SensorHandler::NotifyPipe::close ()
Referenced by nidas::core::SensorHandler::run().
getFd()
int nidas::core::SensorHandler::NotifyPipe::getFd () const inline virtual
Implements nidas::core::Polled.
References _fds.
Referenced by nidas::core::SensorHandler::handlePollingChange().
handlePollEvents()
bool SensorHandler::NotifyPipe::handlePollEvents (uint32_t events) virtual
Returns
: true: read consumed all available data, false otherwise. This return value is required for edge-triggered polling with epoll, since a read event won't be re-triggered on a file descriptor until all available data is read.
Implements nidas::core::Polled.
References N_POLLERR, N_POLLHUP, N_POLLIN, N_POLLRDHUP, PLOG, and nidas::util::Exception::what().
notify()
void SensorHandler::NotifyPipe::notify ()
Used in public methods of SensorHandler which are called from other threads to notify the SensorHandler that the collection of polled objects has changed.
References nidas::util::Exception::what(), and WLOG.
Referenced by nidas::core::SensorHandler::interrupt(), nidas::core::SensorHandler::scheduleAdd(), nidas::core::SensorHandler::scheduleClose(), nidas::core::SensorHandler::scheduleReopen(), and nidas::core::SensorHandler::sensorIsOpen().
operator=()
NotifyPipe& nidas::core::SensorHandler::NotifyPipe::operator= (const NotifyPipe &) private
Member Data Documentation
_fds
int nidas::core::SensorHandler::NotifyPipe::_fds[2] private
Referenced by getFd(), and NotifyPipe().
_handler
SensorHandler* nidas::core::SensorHandler::NotifyPipe::_handler private
Referenced by NotifyPipe().
The documentation for this class was generated from the following files:
nidas/core/SensorHandler.h
nidas/core/SensorHandler.cc