nidas: nidas::core::DOMable Class Reference
nidas::core::DOMable Class Reference abstract
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
#include <DOMable.h>
Public Member Functions
virtual ~DOMable ()
Virtual destructor.
virtual void fromDOMElement (const xercesc::DOMElement *)=0
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
Constructor & Destructor Documentation
~DOMable()
virtual nidas::core::DOMable::~DOMable () inline virtual
Virtual destructor.
Member Function Documentation
fromDOMElement()
virtual void nidas::core::DOMable::fromDOMElement (const xercesc::DOMElement *) pure virtual
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::dynld::UDPSampleOutput, nidas::dynld::SampleInputStream, nidas::dynld::RawSampleService, nidas::dynld::RawSampleOutputStream, nidas::dynld::RawSampleInputStream, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::CVIProcessor, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::Wind2D, nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::GOESOutput, nidas::dynld::isff::DAUSensor, nidas::core::SerialSensor, nidas::core::SampleOutputBase, nidas::core::SampleIOProcessor, nidas::core::FsMount, nidas::core::FileSet, nidas::core::DSMService, nidas::core::CalFile, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::Arinc_IRS, nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, nidas::core::Linear, nidas::core::VariableConverter, nidas::core::Variable, nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::Site, nidas::core::ServiceCatalog, nidas::core::SensorCatalog, nidas::core::SampleTag, nidas::core::Project, nidas::core::MultipleUDPSockets, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::DSMServer, nidas::core::DSMSensor, nidas::core::DSMConfig, nidas::core::DSMCatalog, nidas::core::DatagramSocket, and nidas::core::CharacterSensor.
Referenced by nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static
References namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private
Referenced by getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/DOMable.h
nidas/core/DOMable.cc