nidas: nidas::core::Project::MyDictionary Class Reference
nidas::core::Project::MyDictionary Class Reference
Public Member Functions
MyDictionary (Project *project)
MyDictionary (const MyDictionary &x)
MyDictionary & operator= (const MyDictionary &rhs)
bool getTokenValue (const std::string &token, std::string &value) const
std::string expandString (const std::string &input) const
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Private Attributes
Project * _project
Constructor & Destructor Documentation
MyDictionary() [1/2]
nidas::core::Project::MyDictionary::MyDictionary (Project * project) inline
MyDictionary() [2/2]
nidas::core::Project::MyDictionary::MyDictionary (const MyDictionary & x) inline
Member Function Documentation
expandString()
string Dictionary::expandString (const std::string & input) const inherited
Utility function that scans a string for tokens like ${XXXX}, or $XXX followed by any characters from ".$/", and replaces them with what is returned by the virtual method getTokenValue(token,value).
Referenced by nidas::core::DSMConfig::expandString(), nidas::core::DSMSensor::expandString(), nidas::core::Project::expandString(), nidas::core::Site::expandString(), and nidas::core::ParameterT< T >::fromDOMElement().
getTokenValue()
bool Project::MyDictionary::getTokenValue (const std::string & token, std::string & value) const virtual
Implements nidas::core::Dictionary.
References _project, nidas::util::Process::getEnvVar(), nidas::core::Project::getName(), and nidas::core::Project::getSystemName().
Referenced by nidas::core::Project::getTokenValue().
operator=()
MyDictionary& nidas::core::Project::MyDictionary::operator= (const MyDictionary & rhs) inline
References _project.
Member Data Documentation
_project
Project* nidas::core::Project::MyDictionary::_project private
Referenced by getTokenValue(), and operator=().
The documentation for this class was generated from the following files:
nidas/core/Project.h
nidas/core/Project.cc