nidas: nidas::core::GetAdsFileName Class Reference
nidas::core::GetAdsFileName Class Reference
gets the name of the current .ads file
#include <DSMServerIntf.h>
Public Member Functions
GetAdsFileName (XmlRpcServer *s, DSMServerIntf *intf)
void execute (XmlRpcValue &params, XmlRpcValue &result)
std::string help ()
Private Member Functions
GetAdsFileName (const GetAdsFileName &)
No copying.
GetAdsFileName & operator= (const GetAdsFileName &)
No assignment.
Private Attributes
DSMServerIntf * _serverIntf
Detailed Description
gets the name of the current .ads file
Constructor & Destructor Documentation
GetAdsFileName() [1/2]
nidas::core::GetAdsFileName::GetAdsFileName (XmlRpcServer * s, DSMServerIntf * intf) inline
GetAdsFileName() [2/2]
nidas::core::GetAdsFileName::GetAdsFileName (const GetAdsFileName &) private
No copying.
Member Function Documentation
execute()
void GetAdsFileName::execute (XmlRpcValue & params, XmlRpcValue & result)
References nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::core::FileSet::getCurrentName(), nidas::util::Logger::getInstance(), nidas::core::DSMServer::getProject(), nidas::util::Logger::log(), and LOG_ERR.
help()
std::string nidas::core::GetAdsFileName::help () inline
operator=()
GetAdsFileName& nidas::core::GetAdsFileName::operator= (const GetAdsFileName &) private
No assignment.
Member Data Documentation
_serverIntf
DSMServerIntf* nidas::core::GetAdsFileName::_serverIntf private
The documentation for this class was generated from the following files:
nidas/core/DSMServerIntf.h
nidas/core/DSMServerIntf.cc