nidas: nidas::util::LoggerPrivate Class Reference
nidas::util::LoggerPrivate Class Reference
Static Public Member Functions
static bool get_active_flag (LogScheme &scheme, LogContext *lc, bool &matched)
static void reconfig (LogScheme &scheme, log_points_v::iterator firstpoint)
Static Public Attributes
static const int DEFAULT_LOGLEVEL = LOGGER_NOTICE
Member Function Documentation
get_active_flag()
static bool nidas::util::LoggerPrivate::get_active_flag (LogScheme & scheme, LogContext * lc, bool & matched) inline static
References nidas::util::LogContext::_file, nidas::util::LogContext::_function, nidas::util::LogContext::_level, nidas::util::LogContext::_line, DEBUG_LOGGER, and nidas::util::LogScheme::log_configs.
Referenced by nidas::util::LogContext::LogContext().
reconfig()
static void nidas::util::LoggerPrivate::reconfig (LogScheme & scheme, log_points_v::iterator firstpoint) inline static
References DEBUG_LOGGER, nidas::util::LogScheme::getName(), nidas::util::LogScheme::getShowFieldsString(), nidas::util::LogScheme::log_configs, log_points, and stream_backtrace().
Referenced by nidas::util::Logger::setScheme(), and nidas::util::Logger::updateScheme().
Member Data Documentation
DEFAULT_LOGLEVEL
const int nidas::util::LoggerPrivate::DEFAULT_LOGLEVEL = LOGGER_NOTICE static
Referenced by nidas::util::LogScheme::logLevel().
The documentation for this class was generated from the following file:
nidas/util/Logger.cc