nidas: nidas::core::XMLConfigWriter Class Reference
nidas::core::XMLConfigWriter Class Reference
An XMLWriter which writes the NIDAS XML configuration.
#include <XMLConfigWriter.h>
Public Member Functions
XMLConfigWriter ()
XMLConfigWriter (const DSMConfig *dsm)
~XMLConfigWriter ()
void setDiscardDefaultContent (bool val)
Discard default content.
void setEntities (bool val)
Control writing of entities.
void setCanonicalForm (bool val)
Canonicalize the output.
void setPrettyPrint (bool val)
Format pretty-print.
void setNormalizeCharacters (bool val)
Normalize characters.
void setSplitCDATASections (bool val)
Split CDATA sections.
void setValidation (bool val)
Validation.
void setWhitespaceInElement (bool val)
Whitespace in element content.
void setXMLDeclaration (bool val)
Include xml declaration.
void setFilter (xercesc::DOMWriterFilter *filter)
virtual void write (xercesc::DOMDocument *doc, const std::string &fileName)
virtual void writeNode (xercesc::XMLFormatTarget *const dest, const xercesc::DOMNode &node)
Private Member Functions
XMLConfigWriter (const XMLConfigWriter &)
No copying.
XMLConfigWriter & operator= (const XMLConfigWriter &)
No assignment.
Private Attributes
XMLConfigWriterFilter * _filter
xercesc::DOMImplementation * _impl
xercesc::DOMWriter * _writer
XMLErrorHandler _errorHandler
Detailed Description
An XMLWriter which writes the NIDAS XML configuration.
Constructor & Destructor Documentation
XMLConfigWriter() [1/3]
XMLConfigWriter::XMLConfigWriter ()
References nidas::core::XMLWriter::setFilter().
XMLConfigWriter() [2/3]
XMLConfigWriter::XMLConfigWriter (const DSMConfig * dsm)
References _filter, and nidas::core::XMLWriter::setFilter().
~XMLConfigWriter()
XMLConfigWriter::~XMLConfigWriter ()
References _filter, and nidas::core::XMLWriter::setFilter().
XMLConfigWriter() [3/3]
nidas::core::XMLConfigWriter::XMLConfigWriter (const XMLConfigWriter &) private
No copying.
Member Function Documentation
operator=()
XMLConfigWriter& nidas::core::XMLConfigWriter::operator= (const XMLConfigWriter &) private
No assignment.
setCanonicalForm()
void XMLWriter::setCanonicalForm (bool val) inherited
Canonicalize the output.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: is not supported in Xerces-c. Default: false.
References nidas::core::XMLWriter::_writer.
setDiscardDefaultContent()
void XMLWriter::setDiscardDefaultContent (bool val) inherited
Discard default content.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val Boolean value specifying whether to discard default values of attributes and content. Default: true.
References nidas::core::XMLWriter::_writer.
setEntities()
void XMLWriter::setEntities (bool val) inherited
Control writing of entities.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: entity references are serialized as
* &entityName;
. If false, entity references are expanded. Default: true.
References nidas::core::XMLWriter::_writer.
setFilter()
void XMLWriter::setFilter (xercesc::DOMWriterFilter * filter) inherited
Referenced by XMLConfigWriter(), and ~XMLConfigWriter().
setNormalizeCharacters()
void XMLWriter::setNormalizeCharacters (bool val) inherited
Normalize characters.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true is not supported by Xerces-c. Default: false.
References nidas::core::XMLWriter::_writer.
setPrettyPrint()
void XMLWriter::setPrettyPrint (bool val) inherited
Format pretty-print.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: add whitespace to produce an indented form. Default: false.
References nidas::core::XMLWriter::_writer.
Referenced by nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
setSplitCDATASections()
void XMLWriter::setSplitCDATASections (bool val) inherited
Split CDATA sections.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: split CDATA sections containing ']]>' or unrepresentable characters in the output encoding. false: signal an errror. Default: true.
References nidas::core::XMLWriter::_writer.
setValidation()
void XMLWriter::setValidation (bool val) inherited
Validation.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val false: do not report validation errors. true: not supported by Xerces-c. Default: false.
References nidas::core::XMLWriter::_writer.
setWhitespaceInElement()
void XMLWriter::setWhitespaceInElement (bool val) inherited
Whitespace in element content.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: include text nodes that can be considered ignorable whitespace in the DOM tree. false: not supported by Xerces-c. Default: true.
References nidas::core::XMLWriter::_writer.
setXMLDeclaration()
void nidas::core::XMLWriter::setXMLDeclaration (bool val) inherited
Include xml declaration.
See /link http://xml.apache.org/xerces-c/program-dom.html#DOMWriterFeatures
Parameters
val true: include xml declaration. Default: true.
write()
void XMLWriter::write (xercesc::DOMDocument * doc, const std::string & fileName) virtual inherited
Exceptions
nidas::core::XMLException,nidas::util::IOException
References nidas::core::XMLWriter::_impl, and nidas::core::XMLWriter::writeNode().
Referenced by nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
writeNode()
void XMLWriter::writeNode (xercesc::XMLFormatTarget *const dest, const xercesc::DOMNode & node) virtual inherited
Exceptions
nidas::core::XMLException
nidas::util::IOException
Referenced by nidas::dynld::UDPSampleOutput::VariableListWorker::run(), and nidas::core::XMLWriter::write().
Member Data Documentation
_errorHandler
XMLErrorHandler nidas::core::XMLWriter::_errorHandler private inherited
Referenced by nidas::core::XMLWriter::XMLWriter().
_filter
XMLConfigWriterFilter* nidas::core::XMLConfigWriter::_filter private
Referenced by XMLConfigWriter(), and ~XMLConfigWriter().
_impl
xercesc::DOMImplementation* nidas::core::XMLWriter::_impl private inherited
Referenced by nidas::core::XMLWriter::write().
_writer
xercesc::DOMWriter* nidas::core::XMLWriter::_writer private inherited
Referenced by nidas::core::XMLWriter::setCanonicalForm(), nidas::core::XMLWriter::setDiscardDefaultContent(), nidas::core::XMLWriter::setEntities(), nidas::core::XMLWriter::setNormalizeCharacters(), nidas::core::XMLWriter::setPrettyPrint(), nidas::core::XMLWriter::setSplitCDATASections(), nidas::core::XMLWriter::setValidation(), nidas::core::XMLWriter::setWhitespaceInElement(), nidas::core::XMLWriter::XMLWriter(), and nidas::core::XMLWriter::~XMLWriter().
The documentation for this class was generated from the following files:
nidas/core/XMLConfigWriter.h
nidas/core/XMLConfigWriter.cc