nidas: nidas/apps/serial_loopback_test.c File Reference
serial_loopback_test.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>
#include <sys/time.h>
Macros
#define SERIAL_DEV_DEFAULT "/dev/ttyS0"
#define SEND_INTERVAL_MS_DEFAULT 100
#define DURATION_S_DEFAULT 1
#define BAUDRATE_DEFAULT 115200
#define TX_WORD_MAX_LEN 42
#define TX_WORD_DEF_LEN 26
#define RX_BUFF_MAX_LEN 50
#define SAMPLE_CNTR_LEN 100
#define RX_STATUS_LINECOMPLETE 1
#define RX_STATUS_RECEIVING 0
#define RX_STATUS_ERROR_BADWORD -1
#define RX_STATUS_ERROR_NONEWLINE -2
#define RX_STATUS_ERROR_READ -3
Functions
int set_interface_attribs (int fd, int speed, int parity)
void print_app_usage (void)
int main (int argc, char **argv)
Macro Definition Documentation
BAUDRATE_DEFAULT
#define BAUDRATE_DEFAULT 115200
DURATION_S_DEFAULT
#define DURATION_S_DEFAULT 1
RX_BUFF_MAX_LEN
#define RX_BUFF_MAX_LEN 50
RX_STATUS_ERROR_BADWORD
#define RX_STATUS_ERROR_BADWORD -1
RX_STATUS_ERROR_NONEWLINE
#define RX_STATUS_ERROR_NONEWLINE -2
RX_STATUS_ERROR_READ
#define RX_STATUS_ERROR_READ -3
RX_STATUS_LINECOMPLETE
#define RX_STATUS_LINECOMPLETE 1
RX_STATUS_RECEIVING
#define RX_STATUS_RECEIVING 0
SAMPLE_CNTR_LEN
#define SAMPLE_CNTR_LEN 100
SEND_INTERVAL_MS_DEFAULT
#define SEND_INTERVAL_MS_DEFAULT 100
SERIAL_DEV_DEFAULT
#define SERIAL_DEV_DEFAULT "/dev/ttyS0"
TX_WORD_DEF_LEN
#define TX_WORD_DEF_LEN 26
TX_WORD_MAX_LEN
#define TX_WORD_MAX_LEN 42
Function Documentation
main()
int main (int argc, char ** argv)
References BAUDRATE_DEFAULT, DURATION_S_DEFAULT, print_app_usage(), printf(), RX_BUFF_MAX_LEN, RX_STATUS_ERROR_BADWORD, RX_STATUS_ERROR_NONEWLINE, RX_STATUS_ERROR_READ, RX_STATUS_LINECOMPLETE, RX_STATUS_RECEIVING, SAMPLE_CNTR_LEN, SEND_INTERVAL_MS_DEFAULT, SERIAL_DEV_DEFAULT, set_interface_attribs(), TX_WORD_DEF_LEN, and TX_WORD_MAX_LEN.
print_app_usage()
void print_app_usage (void)
References BAUDRATE_DEFAULT, DURATION_S_DEFAULT, printf(), SEND_INTERVAL_MS_DEFAULT, SERIAL_DEV_DEFAULT, and TX_WORD_MAX_LEN.
Referenced by main().
set_interface_attribs()
int set_interface_attribs (int fd, int speed, int parity)
References fd, and printf().
Referenced by main().