nidas: nidas::core::ProcessorIterator Class Reference
nidas::core::ProcessorIterator Class Reference
Class for iterating over the Processors of a DSMServer or DSMConfig.
#include <NidsIterators.h>
Public Member Functions
ProcessorIterator (const Project *)
ProcessorIterator (const Site *)
ProcessorIterator (const DSMServer *)
ProcessorIterator (const DSMService *)
ProcessorIterator (const DSMConfig *)
ProcessorIterator ()
bool hasNext ()
SampleIOProcessor * next ()
Private Attributes
DSMServiceIterator _serviceIterator
DSMConfigIterator _dsmIterator
const std::list< SampleIOProcessor * > * _processors
std::list< SampleIOProcessor * >::const_iterator _procItr
Detailed Description
Class for iterating over the Processors of a DSMServer or DSMConfig.
Constructor & Destructor Documentation
ProcessorIterator() [1/6]
ProcessorIterator::ProcessorIterator (const Project * obj)
ProcessorIterator() [2/6]
ProcessorIterator::ProcessorIterator (const Site * obj)
ProcessorIterator() [3/6]
ProcessorIterator::ProcessorIterator (const DSMServer * obj)
ProcessorIterator() [4/6]
ProcessorIterator::ProcessorIterator (const DSMService * obj)
ProcessorIterator() [5/6]
ProcessorIterator::ProcessorIterator (const DSMConfig * obj)
ProcessorIterator() [6/6]
ProcessorIterator::ProcessorIterator ()
Member Function Documentation
hasNext()
bool ProcessorIterator::hasNext ()
References _dsmIterator, _processors, _procItr, _serviceIterator, nidas::core::DSMConfig::getProcessors(), nidas::core::DSMService::getProcessors(), nidas::core::DSMServiceIterator::hasNext(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::DSMServiceIterator::next(), and nidas::core::DSMConfigIterator::next().
Referenced by nidas::core::DSMEngine::connectProcessors(), nidas::core::DSMEngine::disconnectProcessors(), nidas::core::Project::findServerSampleOutputStreamFileSets(), StatsProcess::getStatisticsProcessor(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::core::SampleTagIterator::hasNext(), and nidas::dynld::RawSampleService::printStatus().
next()
SampleIOProcessor* nidas::core::ProcessorIterator::next () inline
References _procItr.
Referenced by nidas::core::DSMEngine::connectProcessors(), nidas::core::DSMEngine::disconnectProcessors(), nidas::core::Project::findServerSampleOutputStreamFileSets(), StatsProcess::getStatisticsProcessor(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::core::SampleTagIterator::hasNext(), and nidas::dynld::RawSampleService::printStatus().
Member Data Documentation
_dsmIterator
DSMConfigIterator nidas::core::ProcessorIterator::_dsmIterator private
Referenced by hasNext().
_processors
const std::list<SampleIOProcessor*>* nidas::core::ProcessorIterator::_processors private
Referenced by hasNext().
_procItr
std::list<SampleIOProcessor*>::const_iterator nidas::core::ProcessorIterator::_procItr private
Referenced by hasNext(), and next().
_serviceIterator
DSMServiceIterator nidas::core::ProcessorIterator::_serviceIterator private
Referenced by hasNext().
The documentation for this class was generated from the following files:
nidas/core/NidsIterators.h
nidas/core/NidsIterators.cc