nidas: nidas::core::GetDsmList Class Reference
nidas::core::GetDsmList Class Reference
gets a list of DSMs and their locations from the configuration
#include <DSMServerIntf.h>
Public Member Functions
GetDsmList (XmlRpcServer *s, DSMServerIntf *intf)
void execute (XmlRpcValue &params, XmlRpcValue &result)
std::string help ()
Private Member Functions
GetDsmList (const GetDsmList &)
No copying.
GetDsmList & operator= (const GetDsmList &)
No assignment.
Private Attributes
DSMServerIntf * _serverIntf
Detailed Description
gets a list of DSMs and their locations from the configuration
Constructor & Destructor Documentation
GetDsmList() [1/2]
nidas::core::GetDsmList::GetDsmList (XmlRpcServer * s, DSMServerIntf * intf) inline
GetDsmList() [2/2]
nidas::core::GetDsmList::GetDsmList (const GetDsmList &) private
No copying.
Member Function Documentation
execute()
void GetDsmList::execute (XmlRpcValue & params, XmlRpcValue & result)
References nidas::core::Project::getDSMConfigIterator(), nidas::core::DSMConfig::getLocation(), nidas::core::DSMConfig::getName(), nidas::core::DSMServer::getProject(), nidas::core::DSMConfigIterator::hasNext(), and nidas::core::DSMConfigIterator::next().
help()
std::string nidas::core::GetDsmList::help () inline
operator=()
GetDsmList& nidas::core::GetDsmList::operator= (const GetDsmList &) private
No assignment.
Member Data Documentation
_serverIntf
DSMServerIntf* nidas::core::GetDsmList::_serverIntf private
The documentation for this class was generated from the following files:
nidas/core/DSMServerIntf.h
nidas/core/DSMServerIntf.cc