nidas: TeeI2C Class Reference
TeeI2C Class Reference
Public Member Functions
TeeI2C ()
~TeeI2C ()
int parseRunstring (int argc, char **argv)
int run () throw ()
void i2c_byte_reads () throw (n_u::IOException)
void i2c_block_reads () throw (n_u::IOException)
void writeptys (const unsigned char *buf, int len) throw (n_u::IOException)
void setFIFOPriority (int val)
int usage ()
Private Attributes
string progname
string _i2cname
unsigned int _i2caddr
int _i2cfd
vector< string > _ptynames
vector< int > _ptyfds
bool asDaemon
int priority
sigset_t _signalMask
fd_set _writefdset
int _maxwfd
NidasApp _app
NidasAppArg Priority
NidasAppArg Foreground
NidasAppArg KeepMSB
NidasAppArg BlockingWrites
Constructor & Destructor Documentation
TeeI2C()
TeeI2C::TeeI2C ()
~TeeI2C()
TeeI2C::~TeeI2C ()
References _i2cfd, _ptyfds, and _ptynames.
Member Function Documentation
i2c_block_reads()
void TeeI2C::i2c_block_reads () throw (n_u::IOException)
References _i2cfd, _i2cname, and writeptys().
i2c_byte_reads()
void TeeI2C::i2c_byte_reads () throw (n_u::IOException)
References _i2cfd, _i2cname, nidas::util::addBackslashSequences(), nidas::core::NidasAppArg::asBool(), KeepMSB, len, NLOG, VLOG, and writeptys().
Referenced by run().
parseRunstring()
int TeeI2C::parseRunstring (int argc, char ** argv)
References _app, _i2caddr, _i2cname, _ptynames, nidas::core::NidasAppArg::asBool(), asDaemon, nidas::core::NidasAppArg::asInt(), BlockingWrites, nidas::core::NidasApp::enableArguments(), Foreground, nidas::core::NidasApp::Help, nidas::core::NidasApp::helpRequested(), KeepMSB, nidas::core::NidasApp::loggingArgs(), nidas::core::NidasApp::parseArgs(), priority, Priority, nidas::core::NidasAppArg::specified(), usage(), and nidas::core::NidasApp::Version.
Referenced by main().
run()
int TeeI2C::run () throw ()
References _i2caddr, _i2cfd, _i2cname, _maxwfd, _ptyfds, _ptynames, _writefdset, nidas::util::Termios::apply(), asDaemon, nidas::util::Logger::createInstance(), nidas::util::SerialPort::createPtyLink(), fd, nidas::util::Logger::getInstance(), nidas::util::Logger::getScheme(), i2c_byte_reads(), interrupted, MSECS_PER_SEC, PLOG, priority, progname, setFIFOPriority(), nidas::util::Termios::setRaw(), nidas::util::Logger::setScheme(), USECS_PER_SEC, nidas::util::Exception::what(), and WLOG.
Referenced by main().
setFIFOPriority()
void TeeI2C::setFIFOPriority (int val)
References progname, nidas::util::Exception::what(), and WLOG.
Referenced by run().
usage()
int TeeI2C::usage ()
References _app, nidas::core::NidasApp::getName(), and nidas::core::NidasApp::usage().
Referenced by parseRunstring().
writeptys()
void TeeI2C::writeptys (const unsigned char * buf, int len) throw (n_u::IOException)
References len, NLOG, NSECS_PER_SEC, VLOG, and WLOG.
Referenced by i2c_block_reads(), and i2c_byte_reads().
Member Data Documentation
_app
NidasApp TeeI2C::_app private
Referenced by parseRunstring(), and usage().
_i2caddr
unsigned int TeeI2C::_i2caddr private
Referenced by parseRunstring(), and run().
_i2cfd
int TeeI2C::_i2cfd private
Referenced by i2c_block_reads(), i2c_byte_reads(), run(), and ~TeeI2C().
_i2cname
string TeeI2C::_i2cname private
Referenced by i2c_block_reads(), i2c_byte_reads(), parseRunstring(), and run().
_maxwfd
int TeeI2C::_maxwfd private
Referenced by run().
_ptyfds
vector<int> TeeI2C::_ptyfds private
Referenced by run(), and ~TeeI2C().
_ptynames
vector<string> TeeI2C::_ptynames private
Referenced by parseRunstring(), run(), and ~TeeI2C().
_signalMask
sigset_t TeeI2C::_signalMask private
_writefdset
fd_set TeeI2C::_writefdset private
Referenced by run().
asDaemon
bool TeeI2C::asDaemon private
Referenced by parseRunstring(), and run().
BlockingWrites
NidasAppArg TeeI2C::BlockingWrites private
Referenced by parseRunstring().
Foreground
NidasAppArg TeeI2C::Foreground private
Referenced by parseRunstring().
KeepMSB
NidasAppArg TeeI2C::KeepMSB private
Referenced by i2c_byte_reads(), and parseRunstring().
priority
int TeeI2C::priority private
Referenced by parseRunstring(), and run().
Priority
NidasAppArg TeeI2C::Priority private
Referenced by parseRunstring().
progname
string TeeI2C::progname private
Referenced by run(), and setFIFOPriority().
The documentation for this class was generated from the following file:
nidas/apps/tee_i2c.cc