nidas: nidas/dynld/string_token.h File Reference
string_token.h File Reference
#include <string>
#include <vector>
Functions
std::string & trim (std::string &s)
void string_token (std::vector< std::string > &substrings, const std::string &text, const std::string &delims=",")
Split a string up into a vector of substrings delimited by commas.
Function Documentation
string_token()
void string_token (std::vector< std::string > & substrings, const std::string & text, const std::string & delims = ",")
Split a string up into a vector of substrings delimited by commas.
References len, and trim().
Referenced by nidas::dynld::WxtSensor::init(), main(), and nidas::dynld::WxtSensor::scanSample().
trim()
std::string& trim (std::string & s)
Referenced by string_token().