nidas: nidas::core::SampleClient Class Reference
nidas::core::SampleClient Class Reference abstract
Pure virtual interface of a client of Samples.
#include <SampleClient.h>
Public Member Functions
virtual ~SampleClient ()
virtual bool receive (const Sample *s)=0
Method called to pass a sample to this client.
virtual void flush ()=0
Ask that this SampleClient send out any buffered Samples that it may be holding.
Detailed Description
Pure virtual interface of a client of Samples.
Constructor & Destructor Documentation
~SampleClient()
virtual nidas::core::SampleClient::~SampleClient () inline virtual
Member Function Documentation
flush()
virtual void nidas::core::SampleClient::flush () pure virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Exceptions
Implemented in nidas::core::SampleThread, nidas::core::Resampler, nidas::dynld::UDPSampleOutput, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::CVIOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, nidas::dynld::AsciiOutput, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, DumpClient, DataStats, SampleDispatcher, and DumpClient.
Referenced by nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::flush(), nidas::dynld::raf::CVIProcessor::flush(), nidas::dynld::SampleProcessor::flush(), nidas::dynld::StatisticsProcessor::flush(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleIOProcessor::~SampleIOProcessor(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
receive()
virtual bool nidas::core::SampleClient::receive (const Sample * s) pure virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, DumpClient, DataStats, SampleDispatcher, DumpClient, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, TestClient, nidas::dynld::raf::SyncRecordSource, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, and nidas::dynld::UDPSampleOutput.
The documentation for this class was generated from the following file:
nidas/core/SampleClient.h