nidas: nidas/apps/utime.cc File Reference
utime.cc File Reference
#include <nidas/util/UTime.h>
#include <iostream>
#include <cstring>
Functions
int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::UTime::parse(), nidas::util::setDefaultFormat(), nidas::util::UTime::setUTC(), nidas::util::UTime::toUsecs(), usage(), and USECS_PER_SEC.
usage()
int usage (const char * argv0)
Referenced by main().