nidas: nidas::core::SamplePools Class Reference
nidas::core::SamplePools Class Reference
#include <SamplePool.h>
Public Member Functions
std::list< SamplePoolInterface * > getPools () const
Get a copy of the current list of SamplePools.
void addPool (SamplePoolInterface *pool)
void removePool (SamplePoolInterface *pool)
Static Public Member Functions
static SamplePools * getInstance ()
static void deleteInstance ()
Private Member Functions
SamplePools ()
~SamplePools ()
Private Attributes
nidas::util::Mutex _poolsLock
std::list< SamplePoolInterface * > _pools
Static Private Attributes
static SamplePools * _instance = 0
static nidas::util::Mutex _instanceLock = n_u::Mutex()
Constructor & Destructor Documentation
SamplePools()
nidas::core::SamplePools::SamplePools () inline private
~SamplePools()
SamplePools::~SamplePools () private
Member Function Documentation
addPool()
void SamplePools::addPool (SamplePoolInterface * pool)
Referenced by nidas::core::SamplePool< SampleType >::getInstance().
deleteInstance()
void SamplePools::deleteInstance () static
Referenced by nidas::core::DSMEngine::~DSMEngine(), and nidas::core::DSMServerApp::~DSMServerApp().
getInstance()
SamplePools * SamplePools::getInstance () static
Referenced by nidas::core::SamplePool< SampleType >::getInstance(), nidas::core::SensorHandler::run(), and nidas::core::SamplePool< SampleType >::~SamplePool().
getPools()
list< SamplePoolInterface * > SamplePools::getPools () const
Get a copy of the current list of SamplePools.
In the general case a SamplePool could be deleted after this list was copied, and the pointer to that SamplePool would be invalid. However, in practice, these SamplePools stay around until the process is finished, so there shouldn't be a problem.
Referenced by nidas::core::SensorHandler::run().
removePool()
void SamplePools::removePool (SamplePoolInterface * pool)
Referenced by nidas::core::SamplePool< SampleType >::~SamplePool().
Member Data Documentation
_instance
SamplePools * SamplePools::_instance = 0 static private
_instanceLock
n_u::Mutex SamplePools::_instanceLock = n_u::Mutex() static private
_pools
std::list<SamplePoolInterface*> nidas::core::SamplePools::_pools private
_poolsLock
nidas::util::Mutex nidas::core::SamplePools::_poolsLock mutable private
The documentation for this class was generated from the following files:
nidas/core/SamplePool.h
nidas/core/SamplePool.cc