nidas: nidas::core::SampleSourceSupport Class Reference
nidas::core::SampleSourceSupport Class Reference
A source of samples.
#include <SampleSourceSupport.h>
Public Member Functions
SampleSourceSupport (bool raw)
SampleSourceSupport (const SampleSourceSupport &x)
Copy OK.
virtual ~SampleSourceSupport ()
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
What SampleTags am I a SampleSource for?
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *c, const SampleTag *) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *c, const SampleTag *) throw ()
Add a SampleClient to this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void removeAllSampleClients () throw ()
Big cleanup.
void distribute (const Sample *s) throw ()
Distribute a sample to my clients, calling the receive() method of each client, passing the const pointer to the Sample.
void distribute (const std::list< const Sample * > &samps) throw ()
Distribute a list of samples to my clients.
void flush () throw ()
This implementation of SampleSource::flush() does nothing.
const SampleStats & getSampleStats () const
void setKeepStats (bool val)
bool getKeepStats () const
Private Member Functions
SampleSourceSupport & operator= (const SampleSourceSupport &x)
No assignment.
Private Attributes
nidas::util::Mutex _tagsMutex
std::list< const SampleTag * > _sampleTags
SampleClientList _clients
Current clients of all samples.
std::map< dsm_sample_id_t, SampleClientList > _clientsBySampleId
Current clients of specific samples.
std::set< SampleClient * > _clientSet
nidas::util::Mutex _clientMapLock
SampleStats _stats
bool _raw
bool _keepStats
Detailed Description
A source of samples.
A SampleSource maintains a list of SampleClients. When a SampleSource has a Sample ready, it will call the receive method of all its SampleClients. SampleClients register/unregister with a SampleSource via the addSampleClient/removeSampleClient methods.
Constructor & Destructor Documentation
SampleSourceSupport() [1/2]
SampleSourceSupport::SampleSourceSupport (bool raw)
SampleSourceSupport() [2/2]
SampleSourceSupport::SampleSourceSupport (const SampleSourceSupport & x)
Copy OK.
A shallow copy, the SampleTags are copied to the new instance, but the SampleClients are not.
~SampleSourceSupport()
virtual nidas::core::SampleSourceSupport::~SampleSourceSupport () inline virtual
Member Function Documentation
addSampleClient()
void SampleSourceSupport::addSampleClient (SampleClient * c) throw () virtual
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::SampleInputStream::addSampleClient(), nidas::core::DSMSensor::addSampleClient(), nidas::core::NearestResampler::addSampleClient(), nidas::core::NearestResamplerAtRate::addSampleClient(), nidas::core::SampleAverager::addSampleClient(), nidas::core::SampleBuffer::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleSorter::addSampleClient(), nidas::core::NearestResampler::addSampleClientForTag(), nidas::core::NearestResamplerAtRate::addSampleClientForTag(), and nidas::core::SampleAverager::addSampleClientForTag().
addSampleClientForTag()
void SampleSourceSupport::addSampleClientForTag (SampleClient * c, const SampleTag * tag) throw () virtual
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::SampleClientList::add().
Referenced by nidas::dynld::SampleInputStream::addSampleClientForTag(), nidas::core::DSMSensor::addSampleClientForTag(), nidas::core::SampleBuffer::addSampleClientForTag(), nidas::core::SampleIOProcessor::addSampleClientForTag(), and nidas::core::SampleSorter::addSampleClientForTag().
addSampleTag()
void SampleSourceSupport::addSampleTag (const SampleTag *) throw () virtual
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::SampleInputStream::addSampleTag(), nidas::core::NearestResampler::addSampleTag(), nidas::core::NearestResamplerAtRate::addSampleTag(), nidas::core::SampleAverager::addSampleTag(), nidas::core::SampleBuffer::addSampleTag(), nidas::core::SampleSorter::addSampleTag(), nidas::dynld::raf::SyncRecordSource::addSampleTag(), nidas::core::DSMSensor::addSampleTag(), and nidas::core::DSMSensor::fromDOMElement().
distribute() [1/2]
void SampleSourceSupport::distribute (const Sample * s) throw ()
Distribute a sample to my clients, calling the receive() method of each client, passing the const pointer to the Sample.
Does a s->freeReference() on the sample when done, which means you should assume that the pointer to the Sample is invalid after the call to distribute(), unless the owner has done an additional holdReference(). If so, it is very bad form to make any changes to Sample after the distribute() - the clients may get a half-changed Sample.
References nidas::core::SampleClientList::begin(), and nidas::core::SampleClientList::end().
Referenced by nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::SampleInputStream::distribute(), nidas::core::DSMSensor::distributeRaw(), nidas::core::NearestResampler::flush(), nidas::core::SampleAverager::flush(), nidas::dynld::SampleInputStream::flush(), nidas::core::DSMSensor::readSamples(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::SampleInputStream::readSamples(), nidas::core::DSMSensor::receive(), nidas::core::SampleBuffer::run(), nidas::core::SampleSorter::run(), nidas::dynld::raf::SyncRecordSource::sendSyncHeader(), and nidas::dynld::raf::SyncRecordSource::sendSyncRecord().
distribute() [2/2]
void SampleSourceSupport::distribute (const std::list< const Sample * > & samps) throw ()
Distribute a list of samples to my clients.
Calls receive() method of each client, passing the pointer to the Sample. Does a s->freeReference() on each sample in the list.
flush()
void nidas::core::SampleSourceSupport::flush () throw () inline virtual
This implementation of SampleSource::flush() does nothing.
Implements nidas::core::SampleSource.
getClientCount()
int SampleSourceSupport::getClientCount () const throw () virtual
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References _clientSet.
Referenced by nidas::dynld::SampleInputStream::flush(), nidas::core::DSMSensor::getClientCount(), nidas::core::NearestResampler::getClientCount(), nidas::core::NearestResamplerAtRate::getClientCount(), nidas::core::SampleAverager::getClientCount(), nidas::core::SampleBuffer::getClientCount(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleSorter::getClientCount(), and nidas::dynld::SampleInputStream::getClientCount().
getKeepStats()
bool nidas::core::SampleSourceSupport::getKeepStats () const inline
References _keepStats.
Referenced by nidas::core::SampleBuffer::getKeepStats(), and nidas::core::SampleSorter::getKeepStats().
getProcessedSampleSource()
SampleSource* nidas::core::SampleSourceSupport::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _raw.
Referenced by nidas::core::SampleBuffer::getProcessedSampleSource(), nidas::core::SampleSorter::getProcessedSampleSource(), and nidas::dynld::SampleInputStream::getProcessedSampleSource().
getRawSampleSource()
SampleSource* nidas::core::SampleSourceSupport::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References _raw.
Referenced by nidas::core::SampleSorter::flush(), nidas::core::SampleBuffer::getRawSampleSource(), nidas::core::SampleSorter::getRawSampleSource(), nidas::dynld::SampleInputStream::getRawSampleSource(), nidas::core::SampleBuffer::run(), and nidas::core::SampleSorter::run().
getSampleStats()
const SampleStats& nidas::core::SampleSourceSupport::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _stats.
Referenced by nidas::core::DSMSensor::getSampleStats(), nidas::core::NearestResampler::getSampleStats(), nidas::core::NearestResamplerAtRate::getSampleStats(), nidas::core::SampleAverager::getSampleStats(), nidas::core::SampleBuffer::getSampleStats(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleSorter::getSampleStats(), and nidas::dynld::SampleInputStream::getSampleStats().
getSampleTagIterator()
SampleTagIterator SampleSourceSupport::getSampleTagIterator () const virtual
Implements nidas::core::SampleSource.
Referenced by nidas::core::NearestResampler::getSampleTagIterator(), nidas::core::NearestResamplerAtRate::getSampleTagIterator(), nidas::core::SampleAverager::getSampleTagIterator(), nidas::core::SampleBuffer::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleSorter::getSampleTagIterator(), and nidas::dynld::SampleInputStream::getSampleTagIterator().
getSampleTags()
list< const SampleTag * > SampleSourceSupport::getSampleTags () const virtual
What SampleTags am I a SampleSource for?
Implements nidas::core::SampleSource.
References _sampleTags, and _tagsMutex.
Referenced by nidas::core::DSMSensor::getSampleTags(), nidas::core::NearestResampler::getSampleTags(), nidas::core::NearestResamplerAtRate::getSampleTags(), nidas::core::SampleAverager::getSampleTags(), nidas::core::SampleBuffer::getSampleTags(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleSorter::getSampleTags(), and nidas::dynld::SampleInputStream::getSampleTags().
operator=()
SampleSourceSupport& nidas::core::SampleSourceSupport::operator= (const SampleSourceSupport & x) private
No assignment.
removeAllSampleClients()
void nidas::core::SampleSourceSupport::removeAllSampleClients () throw () inline
Big cleanup.
References _clientMapLock, _clients, _clientSet, nidas::util::Mutex::lock(), nidas::core::SampleClientList::removeAll(), and nidas::util::Mutex::unlock().
removeSampleClient()
void SampleSourceSupport::removeSampleClient (SampleClient * c) throw () virtual
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::SampleInputStream::removeSampleClient(), nidas::core::DSMSensor::removeSampleClient(), nidas::core::NearestResampler::removeSampleClient(), nidas::core::NearestResamplerAtRate::removeSampleClient(), nidas::core::SampleAverager::removeSampleClient(), nidas::core::SampleBuffer::removeSampleClient(), nidas::core::SampleIOProcessor::removeSampleClient(), nidas::core::SampleSorter::removeSampleClient(), nidas::core::NearestResampler::removeSampleClientForTag(), nidas::core::NearestResamplerAtRate::removeSampleClientForTag(), and nidas::core::SampleAverager::removeSampleClientForTag().
removeSampleClientForTag()
void SampleSourceSupport::removeSampleClientForTag (SampleClient * c, const SampleTag * tag) throw () virtual
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::SampleInputStream::removeSampleClientForTag(), nidas::core::DSMSensor::removeSampleClientForTag(), nidas::core::SampleBuffer::removeSampleClientForTag(), nidas::core::SampleIOProcessor::removeSampleClientForTag(), and nidas::core::SampleSorter::removeSampleClientForTag().
removeSampleTag()
void SampleSourceSupport::removeSampleTag (const SampleTag *) throw () virtual
Exceptions
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::SampleInputStream::removeSampleTag(), nidas::core::NearestResampler::removeSampleTag(), nidas::core::NearestResamplerAtRate::removeSampleTag(), nidas::core::SampleAverager::removeSampleTag(), nidas::core::SampleBuffer::removeSampleTag(), nidas::core::SampleSorter::removeSampleTag(), and nidas::core::DSMSensor::removeSampleTag().
setKeepStats()
void nidas::core::SampleSourceSupport::setKeepStats (bool val) inline
References _keepStats.
Referenced by nidas::core::SampleBuffer::setKeepStats(), nidas::core::SampleSorter::setKeepStats(), and nidas::dynld::SampleInputStream::setKeepStats().
Member Data Documentation
_clientMapLock
nidas::util::Mutex nidas::core::SampleSourceSupport::_clientMapLock private
Referenced by removeAllSampleClients().
_clients
SampleClientList nidas::core::SampleSourceSupport::_clients private
Current clients of all samples.
Referenced by removeAllSampleClients().
_clientsBySampleId
std::map<dsm_sample_id_t,SampleClientList> nidas::core::SampleSourceSupport::_clientsBySampleId private
Current clients of specific samples.
_clientSet
std::set<SampleClient*> nidas::core::SampleSourceSupport::_clientSet private
Referenced by getClientCount(), and removeAllSampleClients().
_keepStats
bool nidas::core::SampleSourceSupport::_keepStats private
Referenced by getKeepStats(), and setKeepStats().
_raw
bool nidas::core::SampleSourceSupport::_raw private
Referenced by getProcessedSampleSource(), and getRawSampleSource().
_sampleTags
std::list<const SampleTag*> nidas::core::SampleSourceSupport::_sampleTags private
Referenced by getSampleTags().
_stats
SampleStats nidas::core::SampleSourceSupport::_stats private
Referenced by getSampleStats().
_tagsMutex
nidas::util::Mutex nidas::core::SampleSourceSupport::_tagsMutex mutable private
Referenced by getSampleTags().
The documentation for this class was generated from the following files:
nidas/core/SampleSourceSupport.h
nidas/core/SampleSourceSupport.cc