nidas: ExtractFast2D Class Reference
ExtractFast2D Class Reference
Public Member Functions
ExtractFast2D ()
int run () throw ()
virtual int parseRunstring (int argc, char **argv) throw ()
virtual int usage (const char *argv0)
void sendHeader (dsm_time_t, SampleOutput *out)
Static Public Member Functions
static int main (int argc, char **argv) throw ()
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Protected Member Functions
void setTimeStamp (P2d_rec &record, Sample *samp)
Decode Sample time tag and place into outgoing record.
void setTimeStamp (PADS_rec &record, Sample *samp)
Protected Attributes
bool outputHeader
bool outputDiodeCount
Whether to output diode count histogram.
bool outputParticleCount
Whether to output particle count histogram.
bool copyAllRecords
Copy 100% of 2D records from source file to output file, no filtering.
string xmlFileName
list< string > inputFileNames
string outputFileName
int outputFileLength
SampleInputHeader header
set< dsm_sample_id_t > includeIds
set< dsm_sample_id_t > excludeIds
map< dsm_sample_id_t, dsm_sample_id_t > newids
size_t minNumberParticlesRequired
Static Protected Attributes
static bool interrupted = false
Private Member Functions
size_t countParticles (Probe *probe, const unsigned char *record)
Count number of particles in a record, also report miss-aligned data.
size_t computeDiodeCount (Probe *probe, const unsigned char *record)
Sum occluded diodes along the flight path.
Constructor & Destructor Documentation
ExtractFast2D()
ExtractFast2D::ExtractFast2D () inline
Member Function Documentation
computeDiodeCount()
size_t ExtractFast2D::computeDiodeCount (Probe * probe, const unsigned char * record) private virtual
Sum occluded diodes along the flight path.
This increments for the whole flight. Help find stuck bits.
Returns
the number of diodes that had positives in the record.
Implements nidas::dynld::raf::Extract2D.
References nidas::dynld::raf::Probe::diodeCount, Fast2DsyncStr, FastOverloadSync, nidas::dynld::raf::Probe::nDiodes, and P2D_DATA.
countParticles()
size_t ExtractFast2D::countParticles (Probe * probe, const unsigned char * record) private virtual
Count number of particles in a record, also report miss-aligned data.
Implements nidas::dynld::raf::Extract2D.
References nidas::dynld::raf::P2d_rec::data, Fast2DsyncStr, FastOverloadSync, nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getSuffix(), nidas::dynld::raf::P2d_rec::hour, nidas::dynld::raf::Probe::inDOF, nidas::dynld::raf::P2d_rec::minute, nidas::dynld::raf::P2d_rec::msec, nidas::dynld::raf::Probe::nDiodes, nidas::dynld::raf::Probe::particleCount, nidas::dynld::raf::Probe::recordCount, nidas::dynld::raf::P2d_rec::second, nidas::dynld::raf::Probe::sensor, and nidas::dynld::raf::Probe::totalParticles.
main()
int ExtractFast2D::main (int argc, char ** argv) throw () static
References nidas::dynld::raf::Extract2D::parseRunstring(), run(), and setupSignals().
Referenced by main().
parseRunstring()
int Extract2D::parseRunstring (int argc, char ** argv) throw () virtual inherited
Reimplemented in ExtractDMT.
References usage().
Referenced by main().
run()
int ExtractFast2D::run () throw () virtual
Implements nidas::dynld::raf::Extract2D.
References bigEndian, nidas::dynld::raf::Probe::clockFreq, nidas::dynld::raf::P2d_rec::data, nidas::dynld::raf::Probe::diodeCount, _Tap2D_v2::div10, nidas::util::Process::expandEnvVars(), FILE_VERSION, nidas::core::Sample::freeReference(), nidas::core::Project::fromDOMElement(), nidas::core::DSMSensor::getCatalogName(), nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), nidas::core::Project::getDSMConfigIterator(), nidas::core::FileSet::getFileSet(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::Project::getInstance(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMSensor::getParameter(), nidas::core::DSMConfig::getSensors(), nidas::core::Parameter::getStringValue(), nidas::core::DSMSensor::getSuffix(), nidas::core::DSMConfigIterator::hasNext(), nidas::dynld::raf::Probe::hasOverloadCount, nidas::dynld::raf::P2d_rec::id, nidas::dynld::raf::Probe::id, nidas::dynld::raf::Probe::inDOF, nidas::util::EndianConverter::int32Value(), interrupted, nidas::dynld::raf::Probe::nDiodes, nidas::core::DSMConfigIterator::next(), _Tap2D_v2::ntap, nidas::dynld::raf::P2d_rec::overld, overLoadSync, P2D_DATA, nidas::core::parseXMLConfigFile(), nidas::dynld::raf::Probe::particleCount, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSample(), nidas::dynld::raf::Probe::recordCount, nidas::dynld::raf::Probe::rejectRecordCount, nidas::dynld::raf::Probe::rejectTooFewDiodesCount, nidas::dynld::raf::Probe::rejectTooFewParticleCount, nidas::dynld::raf::Probe::resolution, nidas::dynld::raf::Probe::resolutionM, nidas::dynld::raf::Probe::sensor, nidas::dynld::raf::Probe::serialNumber, nidas::dynld::raf::P2d_rec::tas, nidas::dynld::raf::Probe::totalParticles, TWOD_IMG_TYPE, TWOD_IMGv2_TYPE, TWOD_IMGv3_TYPE, nidas::dynld::raf::Probe::waveLength, and nidas::util::Exception::what().
Referenced by main().
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
sendHeader()
void Extract2D::sendHeader (dsm_time_t , SampleOutput * out) virtual inherited
Exceptions
nidas::util::IOException
Implements nidas::core::HeaderSource.
References nidas::dynld::raf::Extract2D::header, and nidas::core::SampleInputHeader::write().
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
setTimeStamp() [1/2]
void Extract2D::setTimeStamp (P2d_rec & record, Sample * samp) protected inherited
Decode Sample time tag and place into outgoing record.
References nidas::dynld::raf::P2d_rec::day, nidas::core::Sample::getTimeTag(), nidas::dynld::raf::P2d_rec::hour, nidas::dynld::raf::P2d_rec::minute, nidas::dynld::raf::P2d_rec::month, nidas::dynld::raf::P2d_rec::msec, nidas::dynld::raf::P2d_rec::second, nidas::util::UTime::toTm(), and nidas::dynld::raf::P2d_rec::year.
setTimeStamp() [2/2]
void Extract2D::setTimeStamp (PADS_rec & record, Sample * samp) protected inherited
References nidas::dynld::raf::PADS_rec::day, nidas::core::Sample::getTimeTag(), nidas::dynld::raf::PADS_rec::hour, nidas::dynld::raf::PADS_rec::minute, nidas::dynld::raf::PADS_rec::month, nidas::dynld::raf::PADS_rec::msec, nidas::dynld::raf::PADS_rec::second, nidas::util::UTime::toTm(), and nidas::dynld::raf::PADS_rec::year.
setupSignals()
void Extract2D::setupSignals () static inherited
References sigAction().
sigAction()
void Extract2D::sigAction (int sig, siginfo_t * siginfo, void *) static inherited
References interrupted.
usage()
int Extract2D::usage (const char * argv0) virtual inherited
Reimplemented in ExtractDMT.
Member Data Documentation
copyAllRecords
bool nidas::dynld::raf::Extract2D::copyAllRecords protected inherited
Copy 100% of 2D records from source file to output file, no filtering.
excludeIds
set<dsm_sample_id_t> nidas::dynld::raf::Extract2D::excludeIds protected inherited
header
SampleInputHeader nidas::dynld::raf::Extract2D::header protected inherited
Referenced by nidas::dynld::raf::Extract2D::sendHeader().
includeIds
set<dsm_sample_id_t> nidas::dynld::raf::Extract2D::includeIds protected inherited
inputFileNames
list<string> nidas::dynld::raf::Extract2D::inputFileNames protected inherited
interrupted
bool Extract2D::interrupted = false static protected inherited
minNumberParticlesRequired
size_t nidas::dynld::raf::Extract2D::minNumberParticlesRequired protected inherited
newids
map<dsm_sample_id_t,dsm_sample_id_t> nidas::dynld::raf::Extract2D::newids protected inherited
outputDiodeCount
bool nidas::dynld::raf::Extract2D::outputDiodeCount protected inherited
Whether to output diode count histogram.
outputFileLength
int nidas::dynld::raf::Extract2D::outputFileLength protected inherited
outputFileName
string nidas::dynld::raf::Extract2D::outputFileName protected inherited
outputHeader
bool nidas::dynld::raf::Extract2D::outputHeader protected inherited
outputParticleCount
bool nidas::dynld::raf::Extract2D::outputParticleCount protected inherited
Whether to output particle count histogram.
xmlFileName
string nidas::dynld::raf::Extract2D::xmlFileName protected inherited
The documentation for this class was generated from the following file:
nidas/apps/raf/extract2d.cc