nidas: nidas::core::VariableConverter Class Reference
nidas::core::VariableConverter Class Reference abstract
#include <VariableConverter.h>
Public Member Functions
VariableConverter ()
VariableConverter (const VariableConverter &x)
Copy constructor.
VariableConverter & operator= (const VariableConverter &x)
Assignment.
virtual ~VariableConverter ()
virtual VariableConverter * clone () const =0
virtual void readCalFile (dsm_time_t) throw ()
Before a VariableConverter can be used for a conversion, the converter's CalFile, if it exists, needs to be advanced to the right record for the current sample time.
void setCalFileHandler (CalFileHandler *)
Set the instance of CalFileHandler which will be called and given first option to handle new CalFile records.
virtual double convert (dsm_time_t, double v)=0
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
virtual void reset ()=0
Reset the converter to invalid or default settings, such as after an error occurs parsing a CalFile.
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
virtual std::string toString () const =0
Generate a string description of this VariableConverter.
virtual void fromString (const std::string &)
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void fromDOMElement (const xercesc::DOMElement *)
void setCalFile (CalFile *)
CalFile * getCalFile ()
const CalFile * getCalFile () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
virtual void parseFields (CalFile *cf)=0
Parse the fields in the current CalFile record for the particular settings and coefficients needed by this converter.
void abortCalFile (const std::string &what)
Protected Attributes
CalFile * _calFile
CalFileHandler * _handler
Private Attributes
std::string _units
std::map< std::string, Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
const Variable * _variable
Static Private Attributes
static XMLCh * namespaceURI = 0
Constructor & Destructor Documentation
VariableConverter() [1/2]
VariableConverter::VariableConverter ()
VariableConverter() [2/2]
VariableConverter::VariableConverter (const VariableConverter & x)
Copy constructor.
References _calFile, addParameter(), nidas::core::Parameter::clone(), and getParameters().
~VariableConverter()
VariableConverter::~VariableConverter () virtual
References _calFile, and _constParameters.
Member Function Documentation
abortCalFile()
void VariableConverter::abortCalFile (const std::string & what) protected
References _calFile, nidas::core::CalFile::getCurrentFileName(), reset(), and WLOG.
addParameter()
void VariableConverter::addParameter (Parameter * val)
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References _constParameters, _parameters, and nidas::core::Parameter::getName().
Referenced by fromDOMElement(), operator=(), and VariableConverter().
clone()
virtual VariableConverter* nidas::core::VariableConverter::clone () const pure virtual
Implemented in nidas::dynld::isff::RebsLinear, nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
Referenced by nidas::core::Variable::operator=(), and nidas::core::Variable::Variable().
convert()
virtual double nidas::core::VariableConverter::convert (dsm_time_t , double v) pure virtual
Implemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
Referenced by nidas::core::Variable::convert(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::isff::DAUSensor::process(), and nidas::dynld::raf::Watlow::process().
createFromString()
VariableConverter * VariableConverter::createFromString (const std::string & str) static
Exceptions
nidas::util::InvalidParameterException
References fromString().
createVariableConverter()
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
fromDOMElement()
void VariableConverter::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
References addParameter(), nidas::core::Parameter::createParameter(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMSensor::getDictionary(), getDSMSensor(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::XDOMAttr::getValue(), setCalFile(), nidas::core::CalFile::setDSMSensor(), and setUnits().
Referenced by nidas::core::Variable::fromDOMElement(), nidas::core::Linear::fromDOMElement(), nidas::core::Polynomial::fromDOMElement(), and nidas::dynld::isff::CS_Krypton::fromDOMElement().
fromString()
virtual void nidas::core::VariableConverter::fromString (const std::string &) inline virtual
Exceptions
nidas::util::InvalidParameterException
Reimplemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
Referenced by createFromString().
getCalFile() [1/2]
CalFile* nidas::core::VariableConverter::getCalFile () inline
References _calFile.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::core::SampleTag::fromDOMElement(), and PConfig::showCalFiles().
getCalFile() [2/2]
const CalFile* nidas::core::VariableConverter::getCalFile () const inline
References _calFile.
getDSMConfig()
const DSMConfig * VariableConverter::getDSMConfig () const
References nidas::core::DSMSensor::getDSMConfig(), and getDSMSensor().
getDSMSensor()
const DSMSensor * VariableConverter::getDSMSensor () const
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and getVariable().
Referenced by fromDOMElement(), and getDSMConfig().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getParameter()
const Parameter * VariableConverter::getParameter (const std::string & name) const
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References _parameters.
getParameters()
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline
Get list of parameters.
References _constParameters.
Referenced by operator=(), and VariableConverter().
getUnits()
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual
References _units.
Referenced by nidas::dynld::psql::PSQLSampleOutput::addVariable(), nidas::dynld::raf::SyncRecordSource::createHeader(), DumpClient::printHeader(), SampleToDatabase::SampleToDatabase(), nidas::core::Variable::toDOMElement(), nidas::core::Linear::toString(), and nidas::core::Polynomial::toString().
getVariable()
const Variable* nidas::core::VariableConverter::getVariable () const inline
References _variable.
Referenced by getDSMSensor().
operator=()
VariableConverter & VariableConverter::operator= (const VariableConverter & x)
Assignment.
References _calFile, _handler, _units, _variable, addParameter(), nidas::core::Parameter::clone(), and getParameters().
parseFields()
virtual void nidas::core::VariableConverter::parseFields (CalFile * cf) protected pure virtual
Parse the fields in the current CalFile record for the particular settings and coefficients needed by this converter.
Implemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
readCalFile()
void VariableConverter::readCalFile (dsm_time_t t) throw () virtual
Before a VariableConverter can be used for a conversion, the converter's CalFile, if it exists, needs to be advanced to the right record for the current sample time.
As records are read, this method calls parseFields() so the VariableConverter subclass can extract the particular information it needs from the CalFile fields, typically coefficients.
For sensors which need to extend the kind of conversions which can be specified by a CalFile, there is a callback function available. See setCalFileHandler().
References DLOG, nidas::util::UTime::format(), and nidas::util::Exception::what().
Referenced by nidas::core::Linear::convert(), nidas::core::Polynomial::convert(), nidas::dynld::isff::NCAR_TRH::convertVariable(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
reset()
virtual void nidas::core::VariableConverter::reset () pure virtual
Reset the converter to invalid or default settings, such as after an error occurs parsing a CalFile.
Implemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
Referenced by abortCalFile().
setCalFile()
void VariableConverter::setCalFile (CalFile * val)
References _calFile.
Referenced by fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
setCalFileHandler()
void VariableConverter::setCalFileHandler (CalFileHandler * cfh)
Set the instance of CalFileHandler which will be called and given first option to handle new CalFile records.
Pass null to disable the callbacks.
References _handler.
Referenced by nidas::dynld::isff::NCAR_TRH::validate().
setUnits()
void nidas::core::VariableConverter::setUnits (const std::string & val) inline
References _units.
Referenced by nidas::core::Variable::fromDOMElement(), fromDOMElement(), nidas::core::Linear::fromString(), nidas::core::Polynomial::fromString(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
setVariable()
void nidas::core::VariableConverter::setVariable (const Variable * val) inline
References _variable.
Referenced by nidas::core::Variable::fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
toString()
virtual std::string nidas::core::VariableConverter::toString () const pure virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implemented in nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, and nidas::core::Linear.
Member Data Documentation
_calFile
CalFile* nidas::core::VariableConverter::_calFile protected
Referenced by abortCalFile(), getCalFile(), operator=(), nidas::core::Polynomial::parseFields(), setCalFile(), VariableConverter(), and ~VariableConverter().
_constParameters
std::list<const Parameter*> nidas::core::VariableConverter::_constParameters private
List of const pointers to Parameters for providing via getParameters().
Referenced by addParameter(), getParameters(), and ~VariableConverter().
_handler
CalFileHandler* nidas::core::VariableConverter::_handler protected
Referenced by operator=(), and setCalFileHandler().
_parameters
std::map<std::string,Parameter*> nidas::core::VariableConverter::_parameters private
Map of parameters by name.
Referenced by addParameter(), and getParameter().
_units
std::string nidas::core::VariableConverter::_units private
Referenced by getUnits(), operator=(), and setUnits().
_variable
const Variable* nidas::core::VariableConverter::_variable private
Referenced by getVariable(), operator=(), and setVariable().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/VariableConverter.h
nidas/core/VariableConverter.cc