nidas: nidas/apps/ir104.cc File Reference
ir104.cc File Reference
#include <iostream>
#include <iomanip>
#include <nidas/util/Logger.h>
#include <nidas/dynld/IR104_Relays.h>
Functions
static int usage (const char *argv0)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References nidas::util::LogScheme::addConfig(), nidas::util::LogScheme::clearConfigs(), nidas::util::BitArray::getBit(), nidas::util::BitArray::getBits(), nidas::util::Logger::getInstance(), nidas::dynld::IR104_Relays::getNumOutputs(), nidas::dynld::IR104_Relays::getOutputs(), nidas::util::Logger::getScheme(), nidas::util::LogConfig::level, nidas::util::LOGGER_WARNING, nidas::dynld::IR104_Relays::open(), nidas::util::BitArray::setBit(), nidas::util::BitArray::setBits(), nidas::core::DSMSensor::setDeviceName(), nidas::dynld::IR104_Relays::setOutputs(), nidas::util::Logger::setScheme(), and usage().
usage()
static int usage (const char * argv0) static
Referenced by main().