nidas: nidas::core::HeaderSource Class Reference
nidas::core::HeaderSource Class Reference abstract
An interface for sending a SampleHeader to a SampleOutput.
#include <HeaderSource.h>
Public Member Functions
virtual ~HeaderSource ()
virtual void sendHeader (dsm_time_t, SampleOutput *output)=0
Method called to write a header to an SampleOutput.
Static Public Member Functions
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Detailed Description
An interface for sending a SampleHeader to a SampleOutput.
Constructor & Destructor Documentation
~HeaderSource()
virtual nidas::core::HeaderSource::~HeaderSource () inline virtual
Member Function Documentation
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
sendHeader()
virtual void nidas::core::HeaderSource::sendHeader (dsm_time_t , SampleOutput * output) pure virtual
Method called to write a header to an SampleOutput.
Derived classes implement as they see fit.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::raf::Extract2D, SensorExtract, nidas::dynld::raf::SyncRecordGenerator, NidsMerge, and ARLIngest.
Referenced by nidas::core::SampleOutputBase::createNextFile().
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
The documentation for this class was generated from the following files:
nidas/core/HeaderSource.h
nidas/core/HeaderSource.cc