nidas: nidas/apps/sync_server.cc File Reference
sync_server.cc File Reference
#include <nidas/dynld/raf/SyncServer.h>
#include <nidas/core/NidasApp.h>
#include <nidas/util/Logger.h>
#include <nidas/core/Project.h>
#include <unistd.h>
#include <getopt.h>
#include <iostream>
#include <sstream>
Functions
int usage (const std::string &argv0)
int parseRunstring (SyncServer &sync, ArgVector &args)
void interrupt_sync_server (int)
void setupSignals (SyncServer &sync)
int main (int argc, char **argv)
Variables
SyncServer * signal_target = 0
Function Documentation
interrupt_sync_server()
void interrupt_sync_server (int)
References nidas::dynld::raf::SyncServer::interrupt(), and signal_target.
Referenced by setupSignals().
main()
int main (int argc, char ** argv)
References nidas::core::Project::destroyInstance(), nidas::core::NidasApp::enableArguments(), nidas::core::NidasApp::Help, nidas::dynld::raf::SyncServer::init(), nidas::core::NidasApp::LogConfig, nidas::core::NidasApp::loggingArgs(), parseRunstring(), nidas::core::NidasApp::requireLongFlag(), nidas::dynld::raf::SyncServer::run(), nidas::core::NidasApp::setApplicationInstance(), setupSignals(), nidas::core::XMLImplementation::terminate(), nidas::util::Exception::what(), and nidas::core::NidasApp::XmlHeaderFile.
parseRunstring()
int parseRunstring (SyncServer & sync, ArgVector & args)
References nidas::core::NidasApp::allowUnrecognized(), nidas::util::Logger::getScheme(), nidas::core::NidasApp::parseArgs(), port, nidas::dynld::raf::SyncServer::resetAddress(), nidas::dynld::raf::SyncServer::setDataFileNames(), nidas::dynld::raf::SyncServer::setRawSorterLengthSeconds(), nidas::util::Logger::setScheme(), nidas::dynld::raf::SyncServer::setSorterLengthSeconds(), nidas::dynld::raf::SyncServer::setXMLFileName(), usage(), and nidas::core::NidasApp::xmlHeaderFile().
Referenced by main().
setupSignals()
void setupSignals (SyncServer & sync)
References interrupt_sync_server(), and signal_target.
Referenced by main().
usage()
int usage (const std::string & argv0)
References nidas::core::NidasApp::usage().
Referenced by parseRunstring().
Variable Documentation
signal_target
SyncServer* signal_target = 0
Referenced by interrupt_sync_server(), and setupSignals().