nidas: nidas::dynld::isff::GOESXmtr Class Reference
nidas::dynld::isff::GOESXmtr Class Reference abstract
Support for a GOES transmitter, implemented as an IOChannel.
#include <GOESXmtr.h>
Public Member Functions
GOESXmtr ()
Constructor.
GOESXmtr (const GOESXmtr &)
Copy constructor.
virtual ~GOESXmtr ()
Destructor.
const std::string & getName () const
void setName (const std::string &val)
void setId (unsigned long val)
unsigned long getId () const
void setChannel (int val)
int getChannel () const
void setXmitInterval (long val)
Set the transmission interval.
int getXmitInterval () const
void setXmitOffset (long val)
Set the transmission offset.
int getXmitOffset () const
virtual void setRFBaud (long val)=0 throw (nidas::util::InvalidParameterException)
Set the RF baud rate.
virtual int getRFBaud () const =0
void requestConnection (IOChannelRequester *rqstr) throw (nidas::util::IOException)
Request a connection.
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
void setNonBlocking (bool val __attribute__((unused))) throw (nidas::util::IOException)
bool isNonBlocking () const throw (nidas::util::IOException)
virtual void open () throw (nidas::util::IOException)
virtual void init ()=0 throw (nidas::util::IOException)
Initialize tranmitter.
virtual void transmitData (const nidas::util::UTime &at, int configid, const Sample *)=0 throw (nidas::util::IOException)
Queue a sample for writing to a GOES transmitter.
virtual unsigned long checkId ()=0 throw (nidas::util::IOException)
virtual int checkClock ()=0 throw (nidas::util::IOException)
Check transmitter clock, and correct it if necessary.
virtual void reset ()=0 throw (nidas::util::IOException)
virtual void printStatus ()=0 throw ()
Request that transmitter status be printed to an output stream.
void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
void close () throw (nidas::util::IOException)
int getFd () const
void setStatusFile (const std::string &val)
const std::string & getStatusFile () const
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual IOChannel * clone () const =0
Derived classes must provide clone.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual int getReconnectDelaySecs () const
virtual void setNonBlocking (bool val)=0
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const
Return suggested buffer length.
virtual size_t read (void *buf, size_t len)=0
Physical read method which must be implemented in derived classes.
virtual size_t write (const void *buf, size_t len)=0
Physical write method which must be implemented in derived classes.
virtual size_t write (const struct iovec *iov, int iovcnt)=0
Physical write method which must be implemented in derived classes.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Protected Attributes
nidas::util::SerialPort _port
Private Attributes
unsigned long _id
int _channel
int _xmitInterval
int _xmitOffset
std::string _statusFile
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Support for a GOES transmitter, implemented as an IOChannel.
Constructor & Destructor Documentation
GOESXmtr() [1/2]
GOESXmtr::GOESXmtr ()
Constructor.
GOESXmtr() [2/2]
GOESXmtr::GOESXmtr (const GOESXmtr & x)
Copy constructor.
~GOESXmtr()
GOESXmtr::~GOESXmtr () virtual
Destructor.
Member Function Documentation
checkClock()
virtual int nidas::dynld::isff::GOESXmtr::checkClock () throw (nidas::util::IOException) pure virtual
Check transmitter clock, and correct it if necessary.
Returns
transmitter clock minus system clock, in milliseconds.
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
checkId()
virtual unsigned long nidas::dynld::isff::GOESXmtr::checkId () throw (nidas::util::IOException) pure virtual
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
clone()
virtual IOChannel* nidas::core::IOChannel::clone () const pure virtual inherited
Derived classes must provide clone.
Implemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SimGOESXmtr, nidas::dynld::isff::SE_GOESXmtr, nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::MultipleUDPSockets, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
close()
void nidas::dynld::isff::GOESXmtr::close () throw (nidas::util::IOException) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
Reimplemented in nidas::dynld::isff::SE_GOESXmtr.
connect()
IOChannel * GOESXmtr::connect () throw (nidas::util::IOException) virtual
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Exceptions
nidas::util::IOException
nidas::util::UnknownHostException
Implements nidas::core::IOChannel.
References open().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
void nidas::dynld::isff::GOESXmtr::flush () throw (nidas::util::IOException) inline virtual
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented from nidas::core::IOChannel.
Reimplemented in nidas::dynld::isff::SE_GOESXmtr.
fromDOMElement()
void GOESXmtr::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Termios::EVEN, nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), nidas::util::Termios::NONE, nidas::util::Termios::ODD, nidas::util::Termios::setBaudRate(), nidas::util::Termios::setDataBits(), nidas::util::Termios::setParity(), and nidas::util::Termios::setStopBits().
getBufferSize()
virtual size_t nidas::core::IOChannel::getBufferSize () const inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::MultipleUDPSockets, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
getChannel()
int nidas::dynld::isff::GOESXmtr::getChannel () const inline
Referenced by nidas::dynld::isff::SimGOESXmtr::printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::dynld::isff::GOESXmtr::getFd () const inline virtual
Implements nidas::core::IOChannel.
getId()
unsigned long nidas::dynld::isff::GOESXmtr::getId () const inline
Referenced by nidas::dynld::isff::SE_GOESXmtr::checkId(), and nidas::dynld::isff::SE_GOESXmtr::setXmtrId().
getName()
const std::string& nidas::dynld::isff::GOESXmtr::getName () const inline virtual
Implements nidas::core::IOChannel.
Referenced by nidas::dynld::isff::SE_GOESXmtr::checkClock(), nidas::dynld::isff::SE_GOESXmtr::checkId(), nidas::dynld::isff::SE_GOESXmtr::checkStatus(), nidas::dynld::isff::SE_GOESXmtr::decodeClock(), nidas::dynld::isff::SE_GOESXmtr::detectModel(), nidas::dynld::isff::SE_GOESXmtr::doSelfTest(), nidas::dynld::isff::SE_GOESXmtr::getSelfTestResults(), nidas::dynld::isff::SE_GOESXmtr::recv(), nidas::dynld::isff::SE_GOESXmtr::reset(), nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120(), nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getRFBaud()
virtual int nidas::dynld::isff::GOESXmtr::getRFBaud () const pure virtual
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
getStatusFile()
const std::string& nidas::dynld::isff::GOESXmtr::getStatusFile () const inline
Referenced by nidas::dynld::isff::SE_GOESXmtr::printStatus().
getXmitInterval()
int nidas::dynld::isff::GOESXmtr::getXmitInterval () const inline
Referenced by nidas::dynld::isff::GOESOutput::getXmitInterval(), nidas::dynld::isff::SimGOESXmtr::printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
getXmitOffset()
int nidas::dynld::isff::GOESXmtr::getXmitOffset () const inline
Referenced by nidas::dynld::isff::GOESOutput::getXmitOffset(), nidas::dynld::isff::SimGOESXmtr::printStatus(), and nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120().
init()
virtual void nidas::dynld::isff::GOESXmtr::init () throw (nidas::util::IOException) pure virtual
Initialize tranmitter.
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
Referenced by nidas::dynld::isff::GOESOutput::run().
isNewInput()
virtual bool nidas::core::IOChannel::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented in nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::core::IOStream::read(), and nidas::core::IOStream::readUntil().
isNonBlocking()
bool nidas::dynld::isff::GOESXmtr::isNonBlocking () const throw (nidas::util::IOException) inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
open()
void GOESXmtr::open () throw (nidas::util::IOException) virtual
Reimplemented in nidas::dynld::isff::SimGOESXmtr.
References _port, nidas::util::SerialPort::flushBoth(), and nidas::util::SerialPort::open().
Referenced by connect(), and main().
printStatus()
virtual void nidas::dynld::isff::GOESXmtr::printStatus () throw () pure virtual
Request that transmitter status be printed to an output stream.
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
Referenced by nidas::dynld::isff::GOESOutput::run().
read()
virtual size_t nidas::core::IOChannel::read (void * buf, size_t len) pure virtual inherited
Physical read method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::FileSet, nidas::core::DatagramSocket, nidas::dynld::isff::SimGOESXmtr, nidas::core::ServerSocket, nidas::core::MultipleUDPSockets, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::core::IOStream::read().
requestConnection()
void GOESXmtr::requestConnection (IOChannelRequester * rqstr) throw (nidas::util::IOException) virtual
Request a connection.
Implements nidas::core::IOChannel.
reset()
virtual void nidas::dynld::isff::GOESXmtr::reset () throw (nidas::util::IOException) pure virtual
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
Referenced by nidas::dynld::isff::GOESOutput::run().
setChannel()
void nidas::dynld::isff::GOESXmtr::setChannel (int val) inline
Referenced by main().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setId()
void nidas::dynld::isff::GOESXmtr::setId (unsigned long val) inline
Referenced by main().
setName()
void nidas::dynld::isff::GOESXmtr::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
Referenced by main().
setNonBlocking() [1/2]
void nidas::dynld::isff::GOESXmtr::setNonBlocking (bool val __attribute__(unused)) throw (nidas::util::IOException) inline
setNonBlocking() [2/2]
virtual void nidas::core::IOChannel::setNonBlocking (bool val) pure virtual inherited
Exceptions
nidas::util::IOException
Implemented in nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::FileSet, and nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setNonBlocking().
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setRFBaud()
virtual void nidas::dynld::isff::GOESXmtr::setRFBaud (long val) throw (nidas::util::InvalidParameterException) pure virtual
Set the RF baud rate.
Parameters
val RF baud, in bits/sec.
Implemented in nidas::dynld::isff::SimGOESXmtr, and nidas::dynld::isff::SE_GOESXmtr.
setStatusFile()
void nidas::dynld::isff::GOESXmtr::setStatusFile (const std::string & val) inline
setXmitInterval()
void nidas::dynld::isff::GOESXmtr::setXmitInterval (long val) inline
Set the transmission interval.
Parameters
val Interval, in seconds.
setXmitOffset()
void nidas::dynld::isff::GOESXmtr::setXmitOffset (long val) inline
Set the transmission offset.
Parameters
val Offset, in seconds.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
transmitData()
virtual void nidas::dynld::isff::GOESXmtr::transmitData (const nidas::util::UTime & at, int configid, const Sample *) throw (nidas::util::IOException) pure virtual
Queue a sample for writing to a GOES transmitter.
Implemented in nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::SimGOESXmtr.
Referenced by nidas::dynld::isff::GOESOutput::run().
write() [1/2]
virtual size_t nidas::core::IOChannel::write (const struct iovec * iov, int iovcnt) pure virtual inherited
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::isff::SE_GOESXmtr, nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::MultipleUDPSockets, nidas::core::FileSet, nidas::core::DatagramSocket, nidas::dynld::isff::SimGOESXmtr, nidas::core::ServerSocket, nidas::core::McSocketUDP, and nidas::core::McSocket.
write() [2/2]
virtual size_t nidas::core::IOChannel::write (const void * buf, size_t len) pure virtual inherited
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, nidas::core::UnixIOChannel, nidas::core::Socket, nidas::core::MultipleUDPSockets, nidas::core::FileSet, nidas::core::DatagramSocket, nidas::dynld::isff::SimGOESXmtr, nidas::core::ServerSocket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::core::IOStream::flush(), nidas::dynld::AsciiOutput::printHeader(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::UDPSampleOutput::write(), nidas::core::IOStream::write(), and nidas::core::SampleOutputBase::write().
writeNidasHeader()
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
_channel
int nidas::dynld::isff::GOESXmtr::_channel private
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_id
unsigned long nidas::dynld::isff::GOESXmtr::_id private
_port
nidas::util::SerialPort nidas::dynld::isff::GOESXmtr::_port protected
Referenced by nidas::dynld::isff::SE_GOESXmtr::getXmtrClockDelay(), open(), nidas::dynld::isff::SimGOESXmtr::printStatus(), nidas::dynld::isff::SE_GOESXmtr::SE_GOESXmtr(), nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
_statusFile
std::string nidas::dynld::isff::GOESXmtr::_statusFile private
_xmitInterval
int nidas::dynld::isff::GOESXmtr::_xmitInterval private
_xmitOffset
int nidas::dynld::isff::GOESXmtr::_xmitOffset private
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/dynld/isff/GOESXmtr.h
nidas/dynld/isff/GOESXmtr.cc