nidas: nidas::core::XDOMAttr Class Reference
nidas::core::XDOMAttr Class Reference
Class providing convienence methods to access the string attributes of a DOMAttr.
#include <XDOM.h>
Public Member Functions
XDOMAttr (const xercesc::DOMAttr *a)
const std::string & getName () const
const std::string & getValue () const
Protected Attributes
const xercesc::DOMAttr * _attr
std::string _name
std::string _value
Private Member Functions
XDOMAttr (const XDOMAttr &)
No copying.
XDOMAttr & operator= (const XDOMAttr &)
No assignment.
Detailed Description
Class providing convienence methods to access the string attributes of a DOMAttr.
Constructor & Destructor Documentation
XDOMAttr() [1/2]
nidas::core::XDOMAttr::XDOMAttr (const xercesc::DOMAttr * a) inline
XDOMAttr() [2/2]
nidas::core::XDOMAttr::XDOMAttr (const XDOMAttr &) private
No copying.
Member Function Documentation
getName()
const std::string& nidas::core::XDOMAttr::getName () const inline
References _name.
Referenced by nidas::core::Parameter::createParameter(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DatagramSocket::fromDOMElement(), nidas::core::Dataset::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::McSocket::fromDOMElement(), nidas::core::McSocketUDP::fromDOMElement(), nidas::core::MultipleUDPSockets::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::Socket::fromDOMElement(), nidas::core::ServerSocket::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::Linear::fromDOMElement(), nidas::core::Polynomial::fromDOMElement(), nidas::dynld::psql::PSQLChannel::fromDOMElement(), nidas::dynld::raf::Arinc_IRS::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::ParameterT< T >::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::FileSet::fromDOMElement(), nidas::core::FsMount::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::dynld::isff::GOESXmtr::fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::dynld::SampleInputStream::fromDOMElement(), and LogSchemeFromDOMElement().
getValue()
const std::string& nidas::core::XDOMAttr::getValue () const inline
References _value.
Referenced by nidas::core::Parameter::createParameter(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DatagramSocket::fromDOMElement(), nidas::core::Dataset::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::McSocket::fromDOMElement(), nidas::core::McSocketUDP::fromDOMElement(), nidas::core::MultipleUDPSockets::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::Socket::fromDOMElement(), nidas::core::ServerSocket::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::Linear::fromDOMElement(), nidas::core::Polynomial::fromDOMElement(), nidas::dynld::psql::PSQLChannel::fromDOMElement(), nidas::dynld::raf::Arinc_IRS::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::ParameterT< T >::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::FileSet::fromDOMElement(), nidas::core::FsMount::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::dynld::isff::GOESXmtr::fromDOMElement(), nidas::dynld::RawSampleService::fromDOMElement(), and LogSchemeFromDOMElement().
operator=()
XDOMAttr& nidas::core::XDOMAttr::operator= (const XDOMAttr &) private
No assignment.
Member Data Documentation
_attr
const xercesc::DOMAttr* nidas::core::XDOMAttr::_attr protected
_name
std::string nidas::core::XDOMAttr::_name protected
Referenced by getName().
_value
std::string nidas::core::XDOMAttr::_value protected
Referenced by getValue().
The documentation for this class was generated from the following file:
nidas/core/XDOM.h