nidas: nidas::core::SampleInput Class Reference
nidas::core::SampleInput Class Reference abstract
Interface of an input SampleSource.
#include <SampleInput.h>
Public Member Functions
virtual ~SampleInput ()
virtual std::string getName () const =0
virtual void setKeepStats (bool val)=0
virtual const DSMConfig * getDSMConfig () const =0
virtual void requestConnection (DSMService *)=0
virtual SampleInput * getOriginal () const =0
virtual bool readSamples ()=0
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients.
virtual Sample * readSample ()=0
Blocking read of the next sample from the buffer.
virtual void close ()=0
virtual void setNonBlocking (bool val)=0
virtual bool isNonBlocking () const =0
virtual int getFd () const =0
virtual SampleSource * getRawSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual SampleSource * getProcessedSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addSampleTag (const SampleTag *)=0
Add a SampleTag to this SampleSource.
virtual void removeSampleTag (const SampleTag *)=0
virtual std::list< const SampleTag * > getSampleTags () const =0
What SampleTags am I a SampleSource for?
virtual SampleTagIterator getSampleTagIterator () const =0
virtual void addSampleClient (SampleClient *c)=0
Add a SampleClient of all Samples to this SampleSource.
virtual void removeSampleClient (SampleClient *c)=0
Remove a SampleClient from this SampleSource.
virtual void addSampleClientForTag (SampleClient *c, const SampleTag *)=0
Add a SampleClient to this SampleSource.
virtual void removeSampleClientForTag (SampleClient *c, const SampleTag *)=0
Remove a SampleClient for a given SampleTag from this SampleSource.
virtual int getClientCount () const =0
How many SampleClients are currently in my list.
virtual void flush ()=0
Request that this SampleSource flush it's samples.
virtual const SampleStats & getSampleStats () const =0
virtual IOChannelRequester * connected (IOChannel *)=0
virtual void fromDOMElement (const xercesc::DOMElement *)=0
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Interface of an input SampleSource.
Typically a SampleInput is reading serialized samples from a socket or file, and then sending them on.
Constructor & Destructor Documentation
~SampleInput()
virtual nidas::core::SampleInput::~SampleInput () inline virtual
Member Function Documentation
addSampleClient()
virtual void nidas::core::SampleSource::addSampleClient (SampleClient * c) pure virtual inherited
Add a SampleClient of all Samples to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::AsciiOutput::connect(), nidas::core::SampleArchiver::connect(), nidas::dynld::SampleProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), DataDump::run(), DataStats::run(), and nidas::core::RemoteSerialConnection::setSensor().
addSampleClientForTag()
virtual void nidas::core::SampleSource::addSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::raf::CVIProcessor::attachLVInput(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), and nidas::core::NearestResampler::connect().
addSampleTag()
virtual void nidas::core::SampleSource::addSampleTag (const SampleTag *) pure virtual inherited
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::addSampleTag(), nidas::dynld::RawSampleService::fromDOMElement(), DataPrep::run(), and StatsProcess::run().
close()
virtual void nidas::core::SampleInput::close () pure virtual
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream, and nidas::dynld::isff::PacketInputStream.
Referenced by nidas::core::DSMService::~DSMService().
connected()
virtual IOChannelRequester* nidas::core::IOChannelRequester::connected (IOChannel *) pure virtual inherited
Implemented in nidas::dynld::isff::GOESOutput, nidas::dynld::SampleInputStream, nidas::dynld::UDPSampleOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::SampleOutputStream, nidas::core::SampleOutputBase, nidas::dynld::XMLConfigService, and nidas::dynld::XMLConfigAllService.
Referenced by nidas::core::McSocketUDP::connected(), nidas::core::McSocket::connected(), nidas::core::FileSet::mounted(), nidas::core::FileSet::requestConnection(), nidas::core::UnixIOChannel::requestConnection(), and nidas::core::DatagramSocket::requestConnection().
flush()
virtual void nidas::core::SampleSource::flush () pure virtual inherited
Request that this SampleSource flush it's samples.
One must think about whether to call flush() on SampleClients of this SampleSource. A SampleClient may have multiple SampleSources and a flush() of it when one SampleSource() is done may not be what is wanted.
Exceptions
Implemented in nidas::core::SampleThread, nidas::core::Resampler, nidas::dynld::StatisticsProcessor, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleProcessor, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::raf::CVIProcessor, nidas::dynld::isff::PacketInputStream, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::SampleArchiver, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::DSMEngine::disconnectProcessors().
fromDOMElement()
virtual void nidas::core::DOMable::fromDOMElement (const xercesc::DOMElement *) pure virtual inherited
Initialize myself from a xercesc::DOMElement.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::dynld::UDPSampleOutput, nidas::dynld::SampleInputStream, nidas::dynld::RawSampleService, nidas::dynld::RawSampleOutputStream, nidas::dynld::RawSampleInputStream, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::CVIProcessor, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::Wind2D, nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::GOESOutput, nidas::dynld::isff::DAUSensor, nidas::core::SerialSensor, nidas::core::SampleOutputBase, nidas::core::SampleIOProcessor, nidas::core::FsMount, nidas::core::FileSet, nidas::core::DSMService, nidas::core::CalFile, nidas::dynld::raf::IRIGSensor, nidas::dynld::raf::DSMMesaSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::Arinc_IRS, nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::CS_Krypton, nidas::core::Polynomial, nidas::core::Linear, nidas::core::VariableConverter, nidas::core::Variable, nidas::core::UnixIOChannel, nidas::core::ServerSocket, nidas::core::Socket, nidas::core::Site, nidas::core::ServiceCatalog, nidas::core::SensorCatalog, nidas::core::SampleTag, nidas::core::Project, nidas::core::MultipleUDPSockets, nidas::core::McSocketUDP, nidas::core::McSocket, nidas::core::DSMServer, nidas::core::DSMSensor, nidas::core::DSMConfig, nidas::core::DSMCatalog, nidas::core::DatagramSocket, and nidas::core::CharacterSensor.
Referenced by nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
getClientCount()
virtual int nidas::core::SampleSource::getClientCount () const pure virtual inherited
How many SampleClients are currently in my list.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getClientCount().
getDSMConfig()
virtual const DSMConfig* nidas::core::SampleInput::getDSMConfig () const pure virtual
Implemented in nidas::dynld::SampleInputStream.
getFd()
virtual int nidas::core::SampleInput::getFd () const pure virtual
Implemented in nidas::dynld::SampleInputStream.
getName()
virtual std::string nidas::core::SampleInput::getName () const pure virtual
Implemented in nidas::dynld::SampleInputStream, and nidas::dynld::isff::PacketInputStream.
Referenced by nidas::dynld::RawSampleService::fromDOMElement().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getOriginal()
virtual SampleInput* nidas::core::SampleInput::getOriginal () const pure virtual
Implemented in nidas::dynld::SampleInputStream.
getProcessedSampleSource()
virtual SampleSource* nidas::core::SampleSource::getProcessedSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SampleArchiver::connectSource(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), and nidas::core::SampleArchiver::disconnectSource().
getRawSampleSource()
virtual SampleSource* nidas::core::SampleSource::getRawSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SampleArchiver::disconnectSource().
getSampleStats()
virtual const SampleStats& nidas::core::SampleSource::getSampleStats () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getSampleStats(), nidas::dynld::RawSampleService::printClock(), nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
getSampleTagIterator()
virtual SampleTagIterator nidas::core::SampleSource::getSampleTagIterator () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SamplePipeline::getSampleTagIterator().
getSampleTags()
virtual std::list<const SampleTag*> nidas::core::SampleSource::getSampleTags () const pure virtual inherited
What SampleTags am I a SampleSource for?
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::psql::PSQLProcessor, nidas::dynld::isff::PacketInputStream, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), nidas::core::NearestResampler::connect(), nidas::core::DSMEngine::connectOutputs(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::SamplePipeline::getSampleTags(), DataPrep::run(), and nidas::dynld::RawSampleService::schedule().
isNonBlocking()
virtual bool nidas::core::SampleInput::isNonBlocking () const pure virtual
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream.
readSample()
virtual Sample* nidas::core::SampleInput::readSample () pure virtual
Blocking read of the next sample from the buffer.
The caller must call freeReference on the sample when they're done with it.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream, and nidas::dynld::isff::PacketInputStream.
readSamples()
virtual bool nidas::core::SampleInput::readSamples () pure virtual
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients.
This will perform only one physical read of the underlying device and so is appropriate to use when a select() has determined that there is data availabe on our file descriptor.
Returns
false: no data available for physical read, likely the result of doing a non-blocking read on an empty file descriptor. true: physical read did not necessarily consume all available data.
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream, and nidas::dynld::isff::PacketInputStream.
removeSampleClient()
virtual void nidas::core::SampleSource::removeSampleClient (SampleClient * c) pure virtual inherited
Remove a SampleClient from this SampleSource.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::core::SamplePipeline::disconnect(), DataDump::run(), DataStats::run(), nidas::core::SampleArchiver::~SampleArchiver(), and nidas::dynld::SampleProcessor::~SampleProcessor().
removeSampleClientForTag()
virtual void nidas::core::SampleSource::removeSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
removeSampleTag()
virtual void nidas::core::SampleSource::removeSampleTag (const SampleTag *) pure virtual inherited
Exceptions
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::removeSampleTag().
requestConnection()
virtual void nidas::core::SampleInput::requestConnection (DSMService *) pure virtual
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::RawSampleService::schedule().
setKeepStats()
virtual void nidas::core::SampleInput::setKeepStats (bool val) pure virtual
Implemented in nidas::dynld::SampleInputStream.
setNonBlocking()
virtual void nidas::core::SampleInput::setNonBlocking (bool val) pure virtual
Exceptions
nidas::util::IOException
Implemented in nidas::dynld::SampleInputStream.
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Member Data Documentation
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following file:
nidas/core/SampleInput.h