nidas: nidas::dynld::isff::PacketInfo Class Reference
nidas::dynld::isff::PacketInfo Class Reference abstract
#include <Packets.h>
Public Member Functions
virtual ~PacketInfo ()
virtual const char * header () const =0
virtual bool scan (const char *)=0
virtual std::ostream & print (std::ostream &) const =0
virtual float getSignalStrength () const =0
virtual float getFreqOffset () const =0
virtual int getChannel () const =0
virtual int getStatusInt () const =0
virtual int getLength () const =0
Constructor & Destructor Documentation
~PacketInfo()
virtual nidas::dynld::isff::PacketInfo::~PacketInfo () inline virtual
Member Function Documentation
getChannel()
virtual int nidas::dynld::isff::PacketInfo::getChannel () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getFreqOffset()
virtual float nidas::dynld::isff::PacketInfo::getFreqOffset () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getLength()
virtual int nidas::dynld::isff::PacketInfo::getLength () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
getSignalStrength()
virtual float nidas::dynld::isff::PacketInfo::getSignalStrength () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
getStatusInt()
virtual int nidas::dynld::isff::PacketInfo::getStatusInt () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
Referenced by nidas::dynld::isff::PacketInputStream::readSamples().
header()
virtual const char* nidas::dynld::isff::PacketInfo::header () const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
print()
virtual std::ostream& nidas::dynld::isff::PacketInfo::print (std::ostream &) const pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
Referenced by nidas::dynld::isff::operator<<().
scan()
virtual bool nidas::dynld::isff::PacketInfo::scan (const char *) pure virtual
Implemented in nidas::dynld::isff::SutronPacketInfo, and nidas::dynld::isff::NESDISPacketInfo.
The documentation for this class was generated from the following file:
nidas/dynld/isff/Packets.h