nidas: nidas::util::SerialPort Class Reference
nidas::util::SerialPort Class Reference
#include <SerialPort.h>
Public Member Functions
SerialPort ()
SerialPort (const SerialPort &)
Copy constructor.
SerialPort (const std::string &name)
Constructor, given a device name.
SerialPort (const std::string &name, int fd)
For serial port that is already open (stdin for example).
virtual ~SerialPort ()
close the file descriptor if is is open.
Termios & termios ()
Writable reference to the SerialPort's Termios.
const Termios & getTermios () const
Readonly reference to Termios.
void applyTermios ()
Apply the Termios settings to an opened serial port.
const std::string & getName () const
Get device name of the SerialPort.
void setName (const std::string &val)
Set device name of the SerialPort.
virtual int open (int mode=O_RDONLY)
open the serial port.
void close ()
close the file descriptor.
int getFd () const
int getModemStatus ()
Get the current state of the modem bits.
void setModemStatus (int val)
Set the current state of the modem bits.
void clearModemBits (int val)
Clear the indicated modem bits.
void setModemBits (int val)
Set the indicated modem bits.
bool getCarrierDetect ()
void setBlocking (bool val)
bool getBlocking ()
void drain ()
Do a tcdrain() system call on the device.
void flushInput ()
Do a tcflush() system call on the device.
void flushOutput ()
Do a tcflush() system call on the device.
void flushBoth ()
int timeoutOrEOF () const
virtual int readUntil (char *buf, int len, char term)
Read bytes until either the term character is read, or len-1 number of characters have been read.
virtual int readLine (char *buf, int len)
Do a readUntil with a newline terminator.
virtual int read (char *buf, int len)
virtual char readchar ()
Do a buffered read and return character read.
virtual int write (const void *buf, int len)
Static Public Member Functions
static std::string modemFlagsToString (int modem)
static int createPtyLink (const std::string &linkname)
Static utility that creates a pseudo-terminal, returning the file descriptor of the master side and creating a symbolic link with the given name to the slave side.
Private Types
enum state { OK , TIMEOUT_OR_EOF }
Private Member Functions
SerialPort & operator= (const SerialPort &)
No assignment.
Private Attributes
Termios _termios
int _fd
std::string _name
enum nidas::util::SerialPort::state _state
char * _savep
char * _savebuf
int _savelen
int _savealloc
bool _blocking
Member Enumeration Documentation
state
enum nidas::util::SerialPort::state private
Enumerator
OK
TIMEOUT_OR_EOF
Constructor & Destructor Documentation
SerialPort() [1/4]
SerialPort::SerialPort ()
SerialPort() [2/4]
SerialPort::SerialPort (const SerialPort & x)
Copy constructor.
The attributes of the port are copied, but if the original is opened, the copy will not be opened.
SerialPort() [3/4]
SerialPort::SerialPort (const std::string & name)
Constructor, given a device name.
The device is NOT opened, mainly just to avoid throwing an exception in the constructor. Perhaps that should be changed.
SerialPort() [4/4]
SerialPort::SerialPort (const std::string & name, int fd)
For serial port that is already open (stdin for example).
References getBlocking().
~SerialPort()
SerialPort::~SerialPort () virtual
close the file descriptor if is is open.
References _savebuf, and close().
Member Function Documentation
applyTermios()
void SerialPort::applyTermios ()
Apply the Termios settings to an opened serial port.
References _fd, _name, _termios, and nidas::util::Termios::apply().
Referenced by SensorSimApp::main().
clearModemBits()
void SerialPort::clearModemBits (int val)
Clear the indicated modem bits.
References _fd, and _name.
Referenced by nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
close()
void SerialPort::close ()
close the file descriptor.
References _fd, getName(), and ILOG.
Referenced by SensorSimApp::main(), Garmin::run(), GPS_SetClock::run(), and ~SerialPort().
createPtyLink()
int SerialPort::createPtyLink (const std::string & linkname) static
Static utility that creates a pseudo-terminal, returning the file descriptor of the master side and creating a symbolic link with the given name to the slave side.
Parameters
linkname Name of symbolic link to be created that links to the slave side of the pseudo-terminal. If a symbolic link already exists with that name it will be removed and re-created. If linkname already exists and it isn't a symbolic link, an error will be returned.
Returns
The file descriptor of the master side of the pseudo-terminal.
Note: the symbolic link should be deleted when the file descriptor to the master pseudo-terminal is closed. Otherwise, because of the way the system recycles pseudo-terminal devices, the link may at some time point to a different pseudo-terminal, probably created by a different process, like sshd. Opening and reading/writing to the symbolic link would then effect the other process, if the open was permitted.
References fd, and open().
Referenced by SensorSimApp::main(), TeeI2C::run(), and TeeTTy::run().
drain()
void SerialPort::drain ()
Do a tcdrain() system call on the device.
According to the tcdrain man page, it "waits until all output written to the object referred to by fd has been transmitted".
References _fd, and _name.
Referenced by SensorSimApp::main().
flushBoth()
void SerialPort::flushBoth ()
References _fd, and _name.
Referenced by nidas::dynld::isff::GOESXmtr::open(), and openPort().
flushInput()
void SerialPort::flushInput ()
Do a tcflush() system call on the device.
According to the tcflush man page, it "discards data received but not read".
References _fd, and _name.
flushOutput()
void SerialPort::flushOutput ()
Do a tcflush() system call on the device.
According to the tcflush man page, it "discards data written to the object referred to by fd but not transmitted".
References _fd, and _name.
getBlocking()
bool SerialPort::getBlocking ()
References _blocking, _fd, and _name.
Referenced by SerialPort().
getCarrierDetect()
bool SerialPort::getCarrierDetect ()
References getModemStatus().
getFd()
int nidas::util::SerialPort::getFd () const inline
References _fd.
Referenced by GPS_SetClock::run(), Csat3Sim::run(), Receiver::run(), and TeeTTy::run().
getModemStatus()
int SerialPort::getModemStatus ()
Get the current state of the modem bits.
Do "man tty_ioctl" from Linux for more information. These macros are useful for checking/setting the value of of individual bits:
TIOCM_LE        DSR (data set ready/line enable)
TIOCM_DTR       DTR (data terminal ready)
TIOCM_RTS       RTS (request to send)
TIOCM_ST        Secondary TXD (transmit)
TIOCM_SR        Secondary RXD (receive)
TIOCM_CTS       CTS (clear to send)
TIOCM_CAR       DCD (data carrier detect)
TIOCM_CD         see TIOCM_CAR
TIOCM_RNG       RNG (ring)
TIOCM_RI         see TIOCM_RNG
TIOCM_DSR       DSR (data set ready)
References _fd, and _name.
Referenced by getCarrierDetect(), openPort(), ModemLineSetter::run(), ModemLineMonitor::run(), nidas::dynld::isff::SE_GOESXmtr::tosleep(), and nidas::dynld::isff::SE_GOESXmtr::wakeup().
getName()
const std::string& nidas::util::SerialPort::getName () const inline
Get device name of the SerialPort.
References _name.
Referenced by close(), open(), nidas::dynld::isff::SimGOESXmtr::printStatus(), Garmin::readMessage(), GPS_SetClock::run(), Csat3Sim::run(), and TeeTTy::run().
getTermios()
const Termios& nidas::util::SerialPort::getTermios () const inline
Readonly reference to Termios.
References _termios.
Referenced by nidas::dynld::isff::SE_GOESXmtr::getXmtrClockDelay().
modemFlagsToString()
string SerialPort::modemFlagsToString (int modem) static
Referenced by openPort(), ModemLineSetter::run(), and ModemLineMonitor::run().
open()
int SerialPort::open (int mode = O_RDONLY) virtual
open the serial port.
The current Termios settings are also applied to the port.
References _blocking, _fd, _name, _termios, nidas::util::Termios::apply(), getName(), ILOG, and setBlocking().
Referenced by createPtyLink(), SensorSimApp::main(), nidas::dynld::isff::GOESXmtr::open(), openPort(), Garmin::run(), GPS_SetClock::run(), and TeeTTy::run().
operator=()
SerialPort& nidas::util::SerialPort::operator= (const SerialPort &) private
No assignment.
read()
int SerialPort::read (char * buf, int len) virtual
References _fd, _name, _state, len, OK, and TIMEOUT_OR_EOF.
Referenced by readchar(), readUntil(), Csat3Sim::run(), Receiver::run(), and TeeTTy::run().
readchar()
char SerialPort::readchar () virtual
Do a buffered read and return character read.
If '\0' is read, then do a check of timeoutOrEOF() to see if the basic read returned 0.
References _savealloc, _savebuf, _savelen, _savep, and read().
readLine()
int SerialPort::readLine (char * buf, int len) virtual
Do a readUntil with a newline terminator.
References len, and readUntil().
Referenced by GPS_SetClock::run().
readUntil()
int SerialPort::readUntil (char * buf, int len, char term) virtual
Read bytes until either the term character is read, or len-1 number of characters have been read.
buf will be null terminated.
References _savealloc, _savebuf, _savelen, _savep, len, and read().
Referenced by readLine(), and Garmin::readMessage().
setBlocking()
void SerialPort::setBlocking (bool val)
References _blocking, _fd, and _name.
Referenced by open(), and openPort().
setModemBits()
void SerialPort::setModemBits (int val)
Set the indicated modem bits.
References _fd, and _name.
Referenced by nidas::dynld::isff::SE_GOESXmtr::wakeup().
setModemStatus()
void SerialPort::setModemStatus (int val)
Set the current state of the modem bits.
References _fd, and _name.
Referenced by ModemLineSetter::run().
setName()
void nidas::util::SerialPort::setName (const std::string & val) inline
Set device name of the SerialPort.
References _name.
Referenced by openPort(), and Garmin::run().
termios()
Termios& nidas::util::SerialPort::termios () inline
Writable reference to the SerialPort's Termios.
If the SerialPort is open, the user should call applyTermios() for any modifications to take effect.
References _termios.
Referenced by SensorSimApp::main(), openPort(), Garmin::run(), GPS_SetClock::run(), TeeTTy::run(), and nidas::dynld::isff::SE_GOESXmtr::SE_GOESXmtr().
timeoutOrEOF()
int nidas::util::SerialPort::timeoutOrEOF () const inline
References _state, and TIMEOUT_OR_EOF.
write()
int SerialPort::write (const void * buf, int len) virtual
References _blocking, _fd, _name, and len.
Referenced by Garmin::disableAllMessages(), Garmin::disablePPS(), Garmin::enableAllMessages(), Garmin::enablePPS(), Sender::flush(), Garmin::readInit(), Csat3Sim::run(), TeeTTy::run(), Receiver::scanBuffer(), Csat3Sim::sendMessage(), and Garmin::setBaudRateOption().
Member Data Documentation
_blocking
bool nidas::util::SerialPort::_blocking private
Referenced by getBlocking(), open(), setBlocking(), and write().
_fd
int nidas::util::SerialPort::_fd private
Referenced by applyTermios(), clearModemBits(), close(), drain(), flushBoth(), flushInput(), flushOutput(), getBlocking(), getFd(), getModemStatus(), open(), read(), setBlocking(), setModemBits(), setModemStatus(), and write().
_name
std::string nidas::util::SerialPort::_name private
Referenced by applyTermios(), clearModemBits(), drain(), flushBoth(), flushInput(), flushOutput(), getBlocking(), getModemStatus(), getName(), open(), read(), setBlocking(), setModemBits(), setModemStatus(), setName(), and write().
_savealloc
int nidas::util::SerialPort::_savealloc private
Referenced by readchar(), and readUntil().
_savebuf
char* nidas::util::SerialPort::_savebuf private
Referenced by readchar(), readUntil(), and ~SerialPort().
_savelen
int nidas::util::SerialPort::_savelen private
Referenced by readchar(), and readUntil().
_savep
char* nidas::util::SerialPort::_savep private
Referenced by readchar(), and readUntil().
_state
enum nidas::util::SerialPort::state nidas::util::SerialPort::_state private
Referenced by read(), and timeoutOrEOF().
_termios
Termios nidas::util::SerialPort::_termios private
Referenced by applyTermios(), getTermios(), open(), and termios().
The documentation for this class was generated from the following files:
nidas/util/SerialPort.h
nidas/util/SerialPort.cc