nidas: nidas/apps/dmd_mmat_test.cc File Reference
dmd_mmat_test.cc File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <math.h>
#include <signal.h>
#include <string.h>
#include <iostream>
#include <sstream>
#include <vector>
#include <string>
#include <nidas/linux/diamond/dmd_mmat.h>
#include <nidas/util/IOException.h>
#include <unistd.h>
#include <getopt.h>
Classes
struct waveout
class DMD_MMAT_test
Functions
void sigAction (int sig, siginfo_t *, void *)
void setupSignals ()
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References DMD_MMAT_test::parseRunstring(), DMD_MMAT_test::run(), setupSignals(), and nidas::util::Exception::what().
setupSignals()
void setupSignals ()
References sigAction().
Referenced by DataPrep::main(), MergeVerifier::main(), ExtractFast2D::main(), ExtractDMT::main(), SensorExtract::main(), and main().
sigAction()
void sigAction (int sig, siginfo_t * , void *)
Referenced by nidas::core::NidasApp::addSignal(), setupSignals(), and nidas::dynld::raf::Extract2D::setupSignals().