nidas: nidas::core::SampleBuffer Class Reference
nidas::core::SampleBuffer Class Reference
A SampleClient that buffers its received samples, using a pair of STL vectors, and then sends the buffered samples onto its SampleClients.
#include <SampleBuffer.h>
Public Types
enum runStatus { RUN_CANCELED = -1 , RUN_OK = 0 , NOT_RUNNING = 1 , RUN_EXCEPTION = 2 }
Values that can be returned by run method.
enum SchedPolicy { NU_THREAD_OTHER =SCHED_OTHER , NU_THREAD_FIFO =SCHED_FIFO , NU_THREAD_RR =SCHED_RR }
Public Member Functions
SampleBuffer (const std::string &name, bool raw)
Constructor.
virtual ~SampleBuffer ()
void setKeepStats (bool val)
bool getKeepStats () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
void addSampleTag (const SampleTag *tag) throw ()
How to tell this SampleBuffer what sample tags it will be sorting.
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
void flush () throw ()
flush all samples from buffer, distributing them to SampleClients.
void interrupt ()
Interrupt this thread.
bool receive (const Sample *s) throw ()
Insert a sample in the buffer, where it is then passed on to SampleClients.
size_t size () const
Current number of samples in the buffer.
void setLengthSecs (float)
float getLengthSecs () const
void setHeapMax (size_t val)
Set the maximum amount of heap memory to use for sorting samples.
size_t getHeapMax () const
size_t getHeapSize () const
Get the current amount of heap being used for sorting.
void setHeapBlock (bool val)
bool getHeapBlock () const
size_t getNumDiscardedSamples () const
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
size_t getNumFutureSamples () const
Number of samples discarded because their timetags were in the future.
void setRealTime (bool val)
Is this sorter running in real-time? If so then we can screen for bad time-tags by checking against the system clock, which is trusted.
bool getRealTime () const
void setLateSampleCacheSize (unsigned int)
unsigned int getLateSampleCacheSize () const
virtual void start ()
Start the thread running, meaning execute the run method in a separate thread.
virtual int join ()
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
virtual void kill (int sig)
Send a signal to this thread.
virtual void cancel ()
Cancel this thread.
virtual bool isInterrupted () const
Return true when this thread has been interrupted.
virtual bool isRunning () const
Is this thread running?
virtual bool isJoined () const
Has this thread been joined?
virtual bool isDetached () const
Is this a detached thread.
bool isCancelEnabled () const
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
bool isCancelDeferred () const
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
const std::string & getName () const throw ()
Return the name of this thread.
const std::string & getFullName () throw ()
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
bool setRealTimeRoundRobinPriority (int val)
bool setRealTimeFIFOPriority (int val)
bool setNonRealTimePriority ()
void setThreadScheduler (enum SchedPolicy policy, int priority)
void blockSignal (int)
Block a signal in this thread.
void unblockSignal (int)
Install a signal handler and unblock the signal.
Static Public Member Functions
static Thread * currentThread ()
Return the thread object for the current thread.
static pthread_t currentThreadId ()
static Thread * lookupThread (pthread_t id)
static const std::string & currentName ()
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
static std::string getPolicyString (int policy)
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
static int test (int argc, char **argv)
a test method.
Protected Member Functions
void setCancelEnabled (bool val)
Set the cancel state for this thread - false means cancel requests are ignored.
void setCancelDeferred (bool val)
Set the cancel type for this thread.
pthread_t getId () const
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Private Member Functions
int run ()
Thread run function.
void heapDecrement (size_t bytes)
Utility function to decrement the heap size after writing one or more samples.
size_t sizeNoLock () const
bool emptyNoLock () const
SampleBuffer (const SampleBuffer &)
No copy.
SampleBuffer & operator= (const SampleBuffer &)
No assignment.
virtual void signalHandler (int, siginfo_t *)
Signal handler function for this thread.
virtual int pRun ()
void setThreadSchedulerNolock (enum SchedPolicy policy, int priority)
void makeFullName ()
void registerThread ()
Register this current thread with a static registry of threads by id.
void unregisterThread ()
void unsetId ()
Static Private Member Functions
static void * thr_run (void *me)
static void * thr_run_detached (void *me)
static void thr_cleanup (void *me)
static void thr_cleanup_delete (void *me)
static void thr_add_sig (int sig)
static void sigAction (int sig, siginfo_t *si, void *vptr)
Private Attributes
std::vector< const Sample * > _sampleBufs [2]
std::vector< const Sample * > * _inserterBuf
std::vector< const Sample * > * _consumerBuf
SampleSourceSupport _source
nidas::util::Cond _sampleBufCond
nidas::util::Cond _flushCond
size_t _heapMax
Limit on the maximum size of memory to use while buffering samples.
size_t _heapSize
Current heap size, in bytes.
bool _heapBlock
_heapBlock controls what happens when the number of bytes in _samples exceeds _heapMax.
nidas::util::Cond _heapCond
size_t _discardedSamples
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
size_t _realTimeFutureSamples
Number of samples discarded because getRealTime() is true and the samples have timetags later than the system clock.
int _discardWarningCount
How often to log warnings about discardedSamples.
bool _doFlush
bool _flushed
bool _realTime
Is this sorter running in real-time? If so then we can screen for bad time-tags by checking against the system clock, which is trusted.
Mutex _mutex
Mutex for accessing _id.
std::string _name
std::string _fullname
pthread_t _id
bool _running
bool _interrupted
bool _cancel_enabled
bool _cancel_deferred
pthread_attr_t _thread_attr
Exception * _exception
Exception thrown by run method.
bool _detached
sigset_t _blockedSignals
sigset_t _unblockedSignals
Static Private Attributes
static std::string unknownName = std::string("unknown")
Detailed Description
A SampleClient that buffers its received samples, using a pair of STL vectors, and then sends the buffered samples onto its SampleClients.
Member Enumeration Documentation
runStatus
enum nidas::util::Thread::runStatus inherited
Values that can be returned by run method.
User can define other values greater than RUN_EXCEPTION. These values are then returned by int join(). Note that PTHREAD_CANCELLED is -1
Enumerator
RUN_CANCELED
RUN_OK
NOT_RUNNING
RUN_EXCEPTION
SchedPolicy
enum nidas::util::Thread::SchedPolicy inherited
Enumerator
NU_THREAD_OTHER
NU_THREAD_FIFO
NU_THREAD_RR
Constructor & Destructor Documentation
SampleBuffer() [1/2]
SampleBuffer::SampleBuffer (const std::string & name, bool raw)
Constructor.
References _consumerBuf, _inserterBuf, and _sampleBufs.
~SampleBuffer()
SampleBuffer::~SampleBuffer () virtual
References nidas::util::Logger::getInstance(), interrupt(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
SampleBuffer() [2/2]
nidas::core::SampleBuffer::SampleBuffer (const SampleBuffer &) private
No copy.
Member Function Documentation
addSampleClient()
void nidas::core::SampleBuffer::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
addSampleClientForTag()
void nidas::core::SampleBuffer::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
addSampleTag()
void nidas::core::SampleBuffer::addSampleTag (const SampleTag * tag) throw () inline virtual
How to tell this SampleBuffer what sample tags it will be sorting.
SampleClients can then query it.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::addSampleTag().
amInterrupted()
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::Looper::run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
blockSignal()
void Thread::blockSignal (int sig) inherited
Block a signal in this thread.
This method is usually called before this Thread has started. If this Thread is currently running, then this method is only effective if called from this Thread, i.e. from its own run() method.
Because SIGINT, SIGTERM and SIGHUP are typically caught in the main thread, they are blocked by default in a Thread. Call unblockSignal(sig) if you want to catch them in a Thread.
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::ConnectionMonitor(), nidas::core::ServerSocket::ConnectionThread::ConnectionThread(), nidas::core::DerivedDataReader::DerivedDataReader(), nidas::util::McSocketListener::McSocketListener(), nidas::util::McSocketMulticaster< SocketTT >::McSocketMulticaster(), nidas::core::SensorHandler::SensorHandler(), nidas::core::SensorOpener::SensorOpener(), nidas::util::Thread::test(), nidas::dynld::RawSampleService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
cancel()
void Thread::cancel () virtual inherited
Cancel this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::DSMService::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DerivedDataReader::deleteInstance(), and nidas::core::DSMEngine::joinDataThreads().
currentName()
static const std::string& nidas::util::Thread::currentName () inline static inherited
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
References nidas::util::Thread::currentThread(), nidas::util::Thread::getName(), and nidas::util::Thread::unknownName.
Referenced by nidas::util::Logger::msg_locked().
currentThread()
Thread * Thread::currentThread () static inherited
Return the thread object for the current thread.
Returns null if not found.
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::currentName(), and nidas::util::Thread::unblockSignal().
currentThreadId()
pthread_t Thread::currentThreadId () static inherited
Referenced by nidas::core::Looper::removeClient().
emptyNoLock()
bool SampleBuffer::emptyNoLock () const private
References _consumerBuf, and _inserterBuf.
Referenced by run().
flush()
void SampleBuffer::flush () throw () virtual
flush all samples from buffer, distributing them to SampleClients.
Implements nidas::core::SampleThread.
getClientCount()
int nidas::core::SampleBuffer::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getClientCount().
getFullName()
const std::string & Thread::getFullName () throw () inherited
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
References nidas::util::Thread::_fullname.
Referenced by nidas::util::Thread::pRun(), nidas::util::Thread::test(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
getHeapBlock()
bool nidas::core::SampleBuffer::getHeapBlock () const inline virtual
Implements nidas::core::SampleThread.
References _heapBlock.
getHeapMax()
size_t nidas::core::SampleBuffer::getHeapMax () const inline virtual
Implements nidas::core::SampleThread.
References _heapMax.
getHeapSize()
size_t nidas::core::SampleBuffer::getHeapSize () const inline virtual
Get the current amount of heap being used for sorting.
Implements nidas::core::SampleThread.
References _heapSize.
getId()
pthread_t nidas::util::Thread::getId () const inline protected inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Referenced by nidas::util::Thread::isJoined(), nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::core::Looper::removeClient().
getKeepStats()
bool nidas::core::SampleBuffer::getKeepStats () const inline virtual
Implements nidas::core::SampleThread.
References _source, and nidas::core::SampleSourceSupport::getKeepStats().
getLateSampleCacheSize()
unsigned int nidas::core::SampleBuffer::getLateSampleCacheSize () const inline virtual
Implements nidas::core::SampleThread.
getLengthSecs()
float nidas::core::SampleBuffer::getLengthSecs () const inline virtual
Implements nidas::core::SampleThread.
getName()
const std::string & Thread::getName () const throw () inherited
Return the name of this thread.
References nidas::util::Thread::_name.
Referenced by nidas::core::DSMService::cancel(), nidas::util::Thread::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), nidas::core::SensorHandler::PolledDSMSensor::close(), nidas::util::Thread::currentName(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SampleSorter::heapDecrement(), nidas::core::DSMService::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleSorter::run(), nidas::util::ThreadJoiner::run(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::sigAction(), nidas::util::Thread::start(), nidas::util::Thread::test(), nidas::util::LogContext::threadName(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
getNumDiscardedSamples()
size_t nidas::core::SampleBuffer::getNumDiscardedSamples () const inline virtual
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
Implements nidas::core::SampleThread.
References _discardedSamples.
getNumFutureSamples()
size_t nidas::core::SampleBuffer::getNumFutureSamples () const inline virtual
Number of samples discarded because their timetags were in the future.
Implements nidas::core::SampleThread.
References _realTimeFutureSamples.
getPolicyString()
string Thread::getPolicyString (int policy) static inherited
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
References nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::NU_THREAD_RR.
Referenced by nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::makeFullName().
getProcessedSampleSource()
SampleSource* nidas::core::SampleBuffer::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getProcessedSampleSource().
getRawSampleSource()
SampleSource* nidas::core::SampleBuffer::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getRawSampleSource().
getRealTime()
bool nidas::core::SampleBuffer::getRealTime () const inline virtual
Implements nidas::core::SampleThread.
References _realTime.
getSampleStats()
const SampleStats& nidas::core::SampleBuffer::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleStats().
getSampleTagIterator()
SampleTagIterator nidas::core::SampleBuffer::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
getSampleTags()
std::list<const SampleTag*> nidas::core::SampleBuffer::getSampleTags () const inline virtual
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::getSampleTags().
heapDecrement()
void SampleBuffer::heapDecrement (size_t bytes) private
Utility function to decrement the heap size after writing one or more samples.
If the heapSize has has shrunk below heapMax then signal any threads waiting on heapCond.
References _heapBlock, _heapCond, _heapMax, _heapSize, nidas::util::Cond::lock(), nidas::util::Cond::signal(), and nidas::util::Cond::unlock().
Referenced by run().
interrupt()
void SampleBuffer::interrupt () virtual
Interrupt this thread.
This sets a boolean which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted. This is a "soft" request to terminate the thread.
What follows is a discussion of when to use cancel(), kill(), or interrupt() to terminate a thread.
If you can consistently check the state of isInterrupted() in the run method, and return if it is true, at a time interval which is an acceptable amount of time to wait for the thread to terminate, then using interrupt() should work well.
If the run method does I/O, then things are usually a bit more complicated.
If all I/O is guaranteed to finish quickly, which is a rare situation, or is done with a timeout, such as using select/poll with a timeout before every read/write, then one could still use interrupt() as above, and the thread will terminate within the timeout period.
If the thread does blocking I/O operations, and the I/O might block for a period of time longer than you're willing to wait for the thread to terminate, then you need to use kill(sig) or cancel().
If a signal is sent to the thread with kill(sig) while the thread is blocking on an I/O operation, the I/O will immediately return with an errno of EINTR, and one could then return from the run method, after any necessary cleanup.
However there is a possibility that the signal could be missed. In order to make sure you receive a signal, you must block it, so that any received signals are held as pending, and then atomically unblock it with pselect/ppoll/epoll_pwait before performing the I/O operation.
If you do not use I/O timeouts, or kill(sig) with pselect/ppoll/epoll_pwait, or other tricks such as writing to a pipe that is watched with select/poll in the run method, then using cancel() is the only way to guarantee that your thread will terminate in an acceptable amount of time.
All NIDAS Threads support deferred cancelation. Immediate asynchronous cancellation is not fully supported (and is very hard to get right). Deferred cancelation means that cancellation is delayed until the thread next calls a system function that is a cancellation point. At that point the thread run method will simply terminate without any return value from the system function, and then execute any cleanup methods that may have been registered with pthread_cleanup_push.
A list of cancellation points is provided in the pthreads(7) man page. Cancellation points are typically I/O operations, waits or sleeps.
This immediate thread termination can be a problem if there is a possibility that your objects could be left in a bad state, such as with a mutex locked, though it isn't generally a good practice to hold mutexes during a time-consuming I/O operation, wait or sleep.
One should check the run method to see if the state of the objects is OK if execution stops at any of the cancellation points. Note that logging a message, or writing to cerr is a cancellation point. Typically there is error/exception handling associated with an I/O operation. Ensuring the state is OK upon a cancellation is similar to preparation for a fatal I/O error that requires a return of the run method. One can use setCancelEnabled() to defer cancellation.
One can use pthread_cleanup_push and pthread_cleanup_pop to register cleanup routines that are called when a thread is cancelled if special handling is required.
Reimplemented from nidas::util::Thread.
References _sampleBufCond, nidas::util::Cond::lock(), nidas::util::Cond::signal(), and nidas::util::Cond::unlock().
Referenced by ~SampleBuffer().
isCancelDeferred()
bool Thread::isCancelDeferred () const inherited
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
References nidas::util::Thread::_cancel_deferred.
isCancelEnabled()
bool Thread::isCancelEnabled () const inherited
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
References nidas::util::Thread::_cancel_enabled.
isDetached()
virtual bool nidas::util::Thread::isDetached () const inline virtual inherited
Is this a detached thread.
References nidas::util::Thread::_detached.
isInterrupted()
virtual bool nidas::util::Thread::isInterrupted () const inline virtual inherited
Return true when this thread has been interrupted.
Implements nidas::util::Runnable.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::core::SampleSorter::flush(), nidas::dynld::raf::SyncServer::read(), ServerThread::run(), Sender::run(), ModemLineSetter::run(), ModemLineMonitor::run(), nidas::core::DerivedDataReader::run(), nidas::core::FsMountWorkerThread::run(), run(), nidas::core::SampleOutputRequestThread::run(), nidas::core::SampleSorter::run(), nidas::core::SensorHandler::run(), nidas::core::SensorOpener::run(), nidas::core::StatusListener::run(), nidas::core::DSMEngineStat::run(), nidas::util::McSocketListener::run(), and nidas::dynld::raf::SyncServer::stop().
isJoined()
virtual bool nidas::util::Thread::isJoined () const inline virtual inherited
Has this thread been joined?
References nidas::util::Thread::getId().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::SensorHandler::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::util::Thread::test(), ~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
isRunning()
virtual bool nidas::util::Thread::isRunning () const inline virtual inherited
Is this thread running?
References nidas::util::Thread::_mutex, and nidas::util::Thread::_running.
Referenced by nidas::util::Thread::blockSignal(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::DSMService::interrupt(), nidas::core::SamplePipeline::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::Looper::removeClient(), nidas::core::ServerSocket::requestConnection(), nidas::core::SensorHandler::run(), nidas::core::Looper::setupClientMaps(), nidas::util::Thread::test(), nidas::util::Thread::unblockSignal(), ~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::util::Thread::~Thread(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
join()
int Thread::join () virtual inherited
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
The return value is the int return value of the run method, or PTHREAD_CANCELED (-1). If the run method threw an Exception, it will be caught and then re-thrown by join.
Exceptions
Exception
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_exception, nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), nidas::util::Thread::getId(), nidas::util::Thread::getName(), nidas::util::Thread::RUN_EXCEPTION, and nidas::util::Thread::RUN_OK.
Referenced by nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocketListener::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::core::SensorHandler::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::core::DSMEngine::killXmlRpcThread(), nidas::core::DSMServerApp::killXmlRpcThread(), main(), nidas::core::Looper::removeClient(), nidas::util::ThreadJoiner::run(), ~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
kill()
void Thread::kill (int sig) virtual inherited
Send a signal to this thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::interrupt(), nidas::core::SensorHandler::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::XmlRpcThread::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), main(), nidas::core::SensorHandler::scheduleAdd(), nidas::core::SensorHandler::scheduleClose(), nidas::core::SensorHandler::scheduleReopen(), and nidas::core::SensorHandler::sensorIsOpen().
lookupThread()
Thread * Thread::lookupThread (pthread_t id) static inherited
Referenced by nidas::util::LogContext::threadName().
makeFullName()
void Thread::makeFullName () private inherited
References nidas::util::Thread::_cancel_deferred, nidas::util::Thread::_cancel_enabled, nidas::util::Thread::_detached, nidas::util::Thread::_fullname, nidas::util::Thread::_id, nidas::util::Thread::_name, and nidas::util::Thread::getPolicyString().
Referenced by nidas::util::Thread::start().
operator=()
SampleBuffer& nidas::core::SampleBuffer::operator= (const SampleBuffer &) private
No assignment.
pRun()
int Thread::pRun () private virtual inherited
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_exception, nidas::util::Thread::_mutex, nidas::util::Thread::_unblockedSignals, nidas::util::Exception::clone(), nidas::util::Thread::getFullName(), nidas::util::Thread::getId(), ILOG, nidas::util::Mutex::lock(), nidas::util::Mutex::ptr(), nidas::util::Runnable::run(), and nidas::util::Thread::RUN_EXCEPTION.
Referenced by nidas::util::Thread::thr_run(), and nidas::util::Thread::thr_run_detached().
receive()
bool SampleBuffer::receive (const Sample * s) throw () virtual
Insert a sample in the buffer, where it is then passed on to SampleClients.
Depending on how SampleBuffer is compiled, the buffer length may actually be 1 sample, meaning the sample is immediately passed onto the clients. In this case, this method uses a lock to force thread exclusion so that the SampleClient::receive() methods of downstream clients don't have to worry about being reentrant. If the buffer length is greater than one, then a separate thread is created which calls the SampleClient::receive() methods. Since only one thread is distributing the samples, the clients again don't have to worry about having re-entrant receive() methods.
Implements nidas::core::SampleClient.
registerThread()
void Thread::registerThread () private inherited
Register this current thread with a static registry of threads by id.
Thread::registerThread (new Thread ("Main"));
Referenced by nidas::util::Thread::start().
removeSampleClient()
void nidas::core::SampleBuffer::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
removeSampleClientForTag()
void nidas::core::SampleBuffer::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
removeSampleTag()
void nidas::core::SampleBuffer::removeSampleTag (const SampleTag *) throw () inline virtual
Exceptions
Implements nidas::core::SampleSource.
References _source, and nidas::core::SampleSourceSupport::removeSampleTag().
run()
int SampleBuffer::run () private virtual
Thread run function.
Thread function.
Implements nidas::util::Runnable.
References _consumerBuf, _doFlush, _flushCond, _flushed, _inserterBuf, _sampleBufCond, _sampleBufs, _source, nidas::util::Cond::broadcast(), nidas::core::SampleSourceSupport::distribute(), emptyNoLock(), nidas::core::Sample::freeReference(), nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getHeaderLength(), nidas::core::SampleSourceSupport::getRawSampleSource(), heapDecrement(), nidas::util::Thread::isInterrupted(), nidas::util::Cond::lock(), NSECS_PER_SEC, nidas::util::Thread::RUN_OK, sizeNoLock(), nidas::util::Cond::unlock(), nidas::util::Cond::wait(), and WLOG.
setCancelDeferred()
void Thread::setCancelDeferred (bool val) protected inherited
Set the cancel type for this thread.
true means cancel requests are deferred until the next cancellation point. false means they occur instantly. This is protected, it should be called only from a thread's own run method. See the pthreads(7) man page for a list of the cancellation points.
Note: non-deferred canceling is difficult to get right. It has not been tested with this class, and is not recommended.
References nidas::util::Thread::_cancel_deferred.
setCancelEnabled()
void Thread::setCancelEnabled (bool val) protected inherited
Set the cancel state for this thread - false means cancel requests are ignored.
See pthread_setcancelstate. This is protected, it should be called only from a thread's own run method.
References nidas::util::Thread::_cancel_enabled.
setHeapBlock()
void nidas::core::SampleBuffer::setHeapBlock (bool val) inline virtual
Parameters
val If true, and heapSize exceeds heapMax, then wait for heapSize to be less then heapMax, which will block any SampleSources that are inserting samples into this sorter. If false, then discard any samples that are received while heapSize exceeds heapMax.
Implements nidas::core::SampleThread.
References _heapBlock.
setHeapMax()
void nidas::core::SampleBuffer::setHeapMax (size_t val) inline virtual
Set the maximum amount of heap memory to use for sorting samples.
Parameters
val Maximum size of heap in bytes.
Implements nidas::core::SampleThread.
References _heapMax.
setKeepStats()
void nidas::core::SampleBuffer::setKeepStats (bool val) inline virtual
Implements nidas::core::SampleThread.
References _source, and nidas::core::SampleSourceSupport::setKeepStats().
setLateSampleCacheSize()
void nidas::core::SampleBuffer::setLateSampleCacheSize (unsigned int) inline virtual
Implements nidas::core::SampleThread.
setLengthSecs()
void nidas::core::SampleBuffer::setLengthSecs (float) inline virtual
Implements nidas::core::SampleThread.
setNonRealTimePriority()
bool Thread::setNonRealTimePriority () inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::setThreadScheduler().
setRealTime()
void nidas::core::SampleBuffer::setRealTime (bool val) inline virtual
Is this sorter running in real-time? If so then we can screen for bad time-tags by checking against the system clock, which is trusted.
Implements nidas::core::SampleThread.
References _realTime.
setRealTimeFIFOPriority()
bool Thread::setRealTimeFIFOPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_FIFO, and nidas::util::Thread::setThreadScheduler().
Referenced by nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
setRealTimeRoundRobinPriority()
bool Thread::setRealTimeRoundRobinPriority (int val) inherited
Exceptions
Exception
References nidas::util::Thread::NU_THREAD_RR, and nidas::util::Thread::setThreadScheduler().
setThreadScheduler()
void Thread::setThreadScheduler (enum SchedPolicy policy, int priority) inherited
Exceptions
Exception
References nidas::util::Thread::_mutex, and nidas::util::Thread::setThreadSchedulerNolock().
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::getLooper(), nidas::util::Thread::setNonRealTimePriority(), nidas::util::Thread::setRealTimeFIFOPriority(), and nidas::util::Thread::setRealTimeRoundRobinPriority().
setThreadSchedulerNolock()
void Thread::setThreadSchedulerNolock (enum SchedPolicy policy, int priority) private inherited
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::util::Thread::setThreadScheduler(), and nidas::util::Thread::start().
sigAction()
void Thread::sigAction (int sig, siginfo_t * si, void * vptr) static private inherited
References DLOG, nidas::util::Thread::getName(), and nidas::util::Thread::signalHandler().
Referenced by nidas::util::Thread::thr_add_sig().
signalHandler()
virtual void nidas::util::Thread::signalHandler (int , siginfo_t *) inline private virtual inherited
Signal handler function for this thread.
The default handler just sets _interrupt to true, so that amInterrupted() or isInterrupted() will return true. Derived classes can override this method for custom signal handling. However, derived classes are limited in what they can do in their signal handler. Specifically, from the pthread_cond_signal man page:
"It is not safe to use the pthread_cond_signal() function in a signal handler that is invoked asynchronously."
Therefore do not call Cond::signal() from a signal handler.
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_interrupted.
Referenced by nidas::util::Thread::sigAction().
size()
size_t SampleBuffer::size () const virtual
Current number of samples in the buffer.
This method does hold a lock to force exclusive access to the sample container. However, if double buffering is used, a lock is not held on the buffer of samples currently being sent on to clients. Therefore this is only an instantaneous check and should't be used by methods in this class when exclusive access is required.
Implements nidas::core::SampleThread.
References _sampleBufCond, and sizeNoLock().
sizeNoLock()
size_t SampleBuffer::sizeNoLock () const private
References _consumerBuf, and _inserterBuf.
Referenced by run(), and size().
start()
void Thread::start () virtual inherited
Start the thread running, meaning execute the run method in a separate thread.
Exceptions
Exception
References nidas::util::Thread::_id, nidas::util::Thread::_interrupted, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), nidas::util::Thread::getName(), nidas::util::Thread::makeFullName(), nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::registerThread(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::thr_run(), nidas::util::Thread::thr_run_detached(), and WLOG.
Referenced by nidas::util::McSocketListener::accept(), nidas::dynld::RawSampleService::connect(), nidas::dynld::XMLConfigAllService::connected(), nidas::dynld::XMLConfigService::connected(), nidas::core::DerivedDataReader::createInstance(), nidas::dynld::raf::SyncServer::getTimeWindow(), nidas::util::McSocket< SocketT >::joinMulticaster(), main(), nidas::core::FsMount::mount(), nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), nidas::core::SamplePipeline::rawinit(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), ServerThread::run(), PSI::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerApp::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::SensorHandler::run(), nidas::core::Socket::ConnectionThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::dynld::raf::SyncServer::setTimeWindow(), nidas::core::Looper::setupClientMaps(), nidas::core::DSMServerApp::startStatusThread(), nidas::core::DSMEngine::startXmlRpcThread(), and nidas::core::DSMServerApp::startXmlRpcThread().
test()
int Thread::test (int argc, char ** argv) static inherited
a test method.
References nidas::util::Runnable::amInterrupted(), nidas::util::Thread::blockSignal(), nidas::util::Thread::getFullName(), nidas::util::Thread::getName(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Runnable::run(), nidas::util::Thread::Thread(), and nidas::util::Exception::what().
testCancel()
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
thr_add_sig()
void Thread::thr_add_sig (int sig) static private inherited
References nidas::util::Thread::sigAction().
Referenced by nidas::util::Thread::blockSignal(), and nidas::util::Thread::unblockSignal().
thr_cleanup()
void Thread::thr_cleanup (void * me) static private inherited
References nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), ILOG, and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run().
thr_cleanup_delete()
void Thread::thr_cleanup_delete (void * me) static private inherited
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::getFullName(), nidas::util::Mutex::lock(), nidas::util::Mutex::unlock(), and nidas::util::Thread::unregisterThread().
Referenced by nidas::util::Thread::thr_run_detached().
thr_run()
void * Thread::thr_run (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup().
Referenced by nidas::util::Thread::start().
thr_run_detached()
void * Thread::thr_run_detached (void * me) static private inherited
References nidas::util::Thread::pRun(), and nidas::util::Thread::thr_cleanup_delete().
Referenced by nidas::util::Thread::start().
unblockSignal()
void Thread::unblockSignal (int sig) inherited
Install a signal handler and unblock the signal.
The signal handler will log a message about the receipt of the signal at severity LOG_INFO using the nidas::util::Logger. Then, if the signal handler is being invoked from a registered Thread, the virtual method signalHandler() for that Thread will be called.
The signal handler is installed with the sigaction() system call, and will be the action for the given signal in all threads, including the main() thread. If other threads do not wish to take action on a given signal, they should call blockSignal(sig). Or they can define their own signalHandler() method.
After installing the signal handler, the signal is added to those that are unblocked for the thread, or if the Thread is not yet running, the signal will be unblocked in the thread once it runs.
As with blockSignal(), this method is typically called on this Thread before it has started. If this Thread has started, then the signal will only be unblocked if the method is called from this Thread, i.e. from its own run() method.
To install a signal handler, and then block the signal so that it is held as pending until it is later unblocked, typically with pselect(), or sigwaitinfo(), do:
void Thread::run()
{
    // get the existing signal mask
    sigset_t sigmask;
    pthread_sigmask(SIG_BLOCK,NULL,&sigmask);
    // remove SIGUSR1 from the mask passed to pselect
    sigdelset(&sigmask,SIGUSR1);
    for (;;) {
        pselect(nfd,&readfds,0,0,0,&sigmask);
        ...
    }
}
...
thread.unblockSignal(SIGUSR1);
thread.blockSignal(SIGUSR1);
thread.start();
...
try {
    if (thread.isRunning()) {
        thread.kill(SIGUSR1);
        thread.join()
    }
}
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::core::DerivedDataReader::DerivedDataReader(), nidas::core::FsMountWorkerThread::FsMountWorkerThread(), nidas::core::StatusListener::StatusListener(), nidas::core::StatusThread::StatusThread(), nidas::dynld::XMLConfigService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
unregisterThread()
void Thread::unregisterThread () private inherited
Referenced by nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
unsetId()
void nidas::util::Thread::unsetId () inline private inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Member Data Documentation
_blockedSignals
sigset_t nidas::util::Thread::_blockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
_cancel_deferred
bool nidas::util::Thread::_cancel_deferred private inherited
Referenced by nidas::util::Thread::isCancelDeferred(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelDeferred().
_cancel_enabled
bool nidas::util::Thread::_cancel_enabled private inherited
Referenced by nidas::util::Thread::isCancelEnabled(), nidas::util::Thread::makeFullName(), and nidas::util::Thread::setCancelEnabled().
_consumerBuf
std::vector<const Sample*>* nidas::core::SampleBuffer::_consumerBuf private
Referenced by emptyNoLock(), run(), SampleBuffer(), and sizeNoLock().
_detached
bool nidas::util::Thread::_detached private inherited
Referenced by nidas::util::Thread::isDetached(), nidas::util::Thread::makeFullName(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_discardedSamples
size_t nidas::core::SampleBuffer::_discardedSamples private
Number of samples discarded because of _heapSize > _heapMax and heapBlock == true.
Referenced by getNumDiscardedSamples().
_discardWarningCount
int nidas::core::SampleBuffer::_discardWarningCount private
How often to log warnings about discardedSamples.
_doFlush
bool nidas::core::SampleBuffer::_doFlush private
Referenced by run().
_exception
Exception* nidas::util::Thread::_exception private inherited
Exception thrown by run method.
Referenced by nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::util::Thread::~Thread().
_flushCond
nidas::util::Cond nidas::core::SampleBuffer::_flushCond private
Referenced by run().
_flushed
bool nidas::core::SampleBuffer::_flushed private
Referenced by run().
_fullname
std::string nidas::util::Thread::_fullname private inherited
Referenced by nidas::util::Thread::getFullName(), and nidas::util::Thread::makeFullName().
_heapBlock
bool nidas::core::SampleBuffer::_heapBlock private
_heapBlock controls what happens when the number of bytes in _samples exceeds _heapMax.
If _heapBlock is true and _heapSize exceeds _heapMax, then any threads which are calling SampleSorter::receive to insert a sample to this sorter will block on _heapCond until sample consumers have reduced _heapSize to less than _heapMax. If _heapBlock is false and _heapSize exceeds _heapMax then samples are discarded until _heapSize is less than _heapMax.
Referenced by getHeapBlock(), heapDecrement(), and setHeapBlock().
_heapCond
nidas::util::Cond nidas::core::SampleBuffer::_heapCond private
Referenced by heapDecrement().
_heapMax
size_t nidas::core::SampleBuffer::_heapMax private
Limit on the maximum size of memory to use while buffering samples.
Referenced by getHeapMax(), heapDecrement(), and setHeapMax().
_heapSize
size_t nidas::core::SampleBuffer::_heapSize private
Current heap size, in bytes.
Referenced by getHeapSize(), and heapDecrement().
_id
pthread_t nidas::util::Thread::_id private inherited
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::makeFullName(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_inserterBuf
std::vector<const Sample*>* nidas::core::SampleBuffer::_inserterBuf private
Referenced by emptyNoLock(), run(), SampleBuffer(), and sizeNoLock().
_interrupted
bool nidas::util::Thread::_interrupted private inherited
Referenced by nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::signalHandler(), and nidas::util::Thread::start().
_mutex
Mutex nidas::util::Thread::_mutex mutable private inherited
Mutex for accessing _id.
Referenced by nidas::util::Thread::cancel(), nidas::util::Thread::getId(), nidas::util::Thread::interrupt(), nidas::util::Thread::isInterrupted(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Thread::pRun(), nidas::util::Thread::setThreadScheduler(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), nidas::util::Thread::thr_cleanup_delete(), and nidas::util::Thread::unsetId().
_name
std::string nidas::util::Thread::_name private inherited
Referenced by nidas::util::Thread::getName(), and nidas::util::Thread::makeFullName().
_realTime
bool nidas::core::SampleBuffer::_realTime private
Is this sorter running in real-time? If so then we can screen for bad time-tags by checking against the system clock, which is trusted.
Referenced by getRealTime(), and setRealTime().
_realTimeFutureSamples
size_t nidas::core::SampleBuffer::_realTimeFutureSamples private
Number of samples discarded because getRealTime() is true and the samples have timetags later than the system clock.
Referenced by getNumFutureSamples().
_running
bool nidas::util::Thread::_running private inherited
Referenced by nidas::util::Thread::isRunning(), nidas::util::Thread::start(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
_sampleBufCond
nidas::util::Cond nidas::core::SampleBuffer::_sampleBufCond mutable private
Referenced by interrupt(), run(), and size().
_sampleBufs
std::vector<const Sample*> nidas::core::SampleBuffer::_sampleBufs[2] private
Referenced by run(), and SampleBuffer().
_source
SampleSourceSupport nidas::core::SampleBuffer::_source private
Referenced by addSampleClient(), addSampleClientForTag(), addSampleTag(), getClientCount(), getKeepStats(), getProcessedSampleSource(), getRawSampleSource(), getSampleStats(), getSampleTagIterator(), getSampleTags(), removeSampleClient(), removeSampleClientForTag(), removeSampleTag(), run(), and setKeepStats().
_thread_attr
pthread_attr_t nidas::util::Thread::_thread_attr private inherited
Referenced by nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::util::Thread::Thread(), and nidas::util::Thread::~Thread().
_unblockedSignals
sigset_t nidas::util::Thread::_unblockedSignals private inherited
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::pRun(), nidas::util::Thread::Thread(), and nidas::util::Thread::unblockSignal().
unknownName
std::string Thread::unknownName = std::string("unknown") static private inherited
Referenced by nidas::util::Thread::currentName().
The documentation for this class was generated from the following files:
nidas/core/SampleBuffer.h
nidas/core/SampleBuffer.cc