nidas: nidas::core::DatagramSocket Class Reference
nidas::core::DatagramSocket Class Reference
Implementation of an IOChannel, over a DatagramSocket.
#include <DatagramSocket.h>
Public Member Functions
DatagramSocket ()
Constructor.
DatagramSocket (const DatagramSocket &x)
Copy constructor.
DatagramSocket & operator= (const DatagramSocket &rhs)
DatagramSocket (nidas::util::DatagramSocket *sock)
~DatagramSocket ()
DatagramSocket * clone () const
Derived classes must provide clone.
void requestConnection (IOChannelRequester *service)
IOChannel * connect ()
bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
std::list< nidas::util::Inet4NetworkInterface > getInterfaces () const
void setNonBlocking (bool val)
Do setNonBlocking(val) on underlying socket.
bool isNonBlocking () const
Return isNonBlocking() of underlying socket.
size_t getBufferSize () const throw ()
Return suggested buffer length.
size_t read (void *buf, size_t len)
Do the actual hardware read.
size_t write (const void *buf, size_t len)
Do the actual hardware write.
size_t write (const struct iovec *iov, int iovcnt)
Do the actual hardware write.
void close ()
int getFd () const
const std::string & getName () const
void setName (const std::string &val)
const std::string & getUnixPath () const
Get the unix path name.
void setUnixPath (const std::string &unixPath)
Set the pathname for the unix socket connection.
void setSocketAddress (const nidas::util::SocketAddress &val)
Set address for this socket.
const nidas::util::SocketAddress & getSocketAddress ()
void setHostPort (const std::string &host, unsigned short port)
Set the hostname and port of the remote connection.
void setPort (unsigned short port)
Set the the local port number.
const std::string & getHost () const
Get the name of the remote host.
unsigned short getPort () const
void fromDOMElement (const xercesc::DOMElement *)
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual void flush ()
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node)
static const XMLCh * getNamespaceURI ()
Private Attributes
nidas::util::auto_ptr< nidas::util::SocketAddress > _sockAddr
std::string _host
unsigned short _port
std::string _unixPath
nidas::util::DatagramSocket * _nusocket
std::string _name
IOChannelRequester * _iochanRequester
bool _nonBlocking
const DSMConfig * _dsm
ConnectionInfo _conInfo
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Implementation of an IOChannel, over a DatagramSocket.
Constructor & Destructor Documentation
DatagramSocket() [1/3]
DatagramSocket::DatagramSocket ()
Constructor.
References setName().
Referenced by clone().
DatagramSocket() [2/3]
DatagramSocket::DatagramSocket (const DatagramSocket & x)
Copy constructor.
References _sockAddr, and setName().
DatagramSocket() [3/3]
DatagramSocket::DatagramSocket (nidas::util::DatagramSocket * sock)
~DatagramSocket()
DatagramSocket::~DatagramSocket ()
References _nusocket, close(), getName(), nidas::util::Exception::what(), and WLOG.
Member Function Documentation
clone()
DatagramSocket * DatagramSocket::clone () const virtual
Derived classes must provide clone.
Implements nidas::core::IOChannel.
References DatagramSocket().
close()
void nidas::core::DatagramSocket::close () inline virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::DatagramSocket::close().
Referenced by ~DatagramSocket().
connect()
IOChannel * DatagramSocket::connect () virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, nidas::util::DatagramSocket::bind(), nidas::util::DatagramSocket::connect(), nidas::util::SocketAddress::getConstSockAddrPtr(), nidas::util::SocketAddress::getFamily(), nidas::util::Inet4SocketAddress::getInet4Address(), getName(), getSocketAddress(), isNonBlocking(), nidas::util::DatagramSocket::setNonBlocking(), and nidas::util::Exception::what().
Referenced by requestConnection().
createFile()
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Exceptions
nidas::util::IOException
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile(), and nidas::core::SampleOutputBase::createNextFile().
createIOChannel()
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) static inherited
Exceptions
nidas::util::InvalidParameterException
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
flush()
virtual void nidas::core::IOChannel::flush () inline virtual inherited
Default flush implementation does nothing.
Exceptions
nidas::util::IOException
Reimplemented in nidas::dynld::psql::PSQLChannel, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::isff::GOESXmtr.
Referenced by nidas::core::IOStream::flush().
fromDOMElement()
void DatagramSocket::fromDOMElement (const xercesc::DOMElement * node) virtual
Exceptions
nidas::util::InvalidParameterException
Implements nidas::core::DOMable.
References nidas::util::Process::expandEnvVars(), nidas::util::Inet4Address::getByName(), getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMAttr::getValue(), port, setHostPort(), setNonBlocking(), setUnixPath(), nidas::util::Exception::what(), and WLOG.
getBufferSize()
size_t DatagramSocket::getBufferSize () const throw () virtual
Return suggested buffer length.
Reimplemented from nidas::core::IOChannel.
References _nusocket, and nidas::util::DatagramSocket::getReceiveBufferSize().
getConnectionInfo()
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
getDSMConfig()
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
getFd()
int nidas::core::DatagramSocket::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::DatagramSocket::getFd().
getHost()
const std::string& nidas::core::DatagramSocket::getHost () const inline
Get the name of the remote host.
References _host.
getInterfaces()
std::list<nidas::util::Inet4NetworkInterface> nidas::core::DatagramSocket::getInterfaces () const inline
Exceptions
nidas::util::IOException
References _nusocket, and nidas::util::DatagramSocket::getInterfaces().
getName()
const std::string& nidas::core::DatagramSocket::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by connect(), fromDOMElement(), and ~DatagramSocket().
getNamespaceURI()
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::ServerSocket::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
getPort()
unsigned short nidas::core::DatagramSocket::getPort () const inline
References _port.
getReconnectDelaySecs()
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
getRequestType()
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement().
getSocketAddress()
const n_u::SocketAddress & DatagramSocket::getSocketAddress ()
Exceptions
nidas::util::UnknownHostException
References _host, _port, _sockAddr, _unixPath, nidas::util::Inet4Address::getByName(), getUnixPath(), setName(), and setSocketAddress().
Referenced by connect().
getUnixPath()
const std::string& nidas::core::DatagramSocket::getUnixPath () const inline
Get the unix path name.
References _unixPath.
Referenced by getSocketAddress().
isNewInput()
bool nidas::core::DatagramSocket::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
isNonBlocking()
bool nidas::core::DatagramSocket::isNonBlocking () const inline virtual
Return isNonBlocking() of underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking, _nusocket, and nidas::util::DatagramSocket::isNonBlocking().
Referenced by connect().
operator=()
DatagramSocket & DatagramSocket::operator= (const DatagramSocket & rhs)
References _host, _iochanRequester, _name, _nonBlocking, _nusocket, _port, _sockAddr, _unixPath, and setName().
read()
size_t nidas::core::DatagramSocket::read (void * buf, size_t len) inline virtual
Do the actual hardware read.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, len, and nidas::util::DatagramSocket::recv().
requestConnection()
void DatagramSocket::requestConnection (IOChannelRequester * service) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _iochanRequester, connect(), and nidas::core::IOChannelRequester::connected().
setConnectionInfo()
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
References nidas::core::IOChannel::_conInfo.
Referenced by nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocketUDP::connected(), nidas::core::MultipleUDPSockets::connected(), and nidas::core::McSocket::connected().
setDSMConfig()
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
References nidas::core::IOChannel::_dsm.
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
setHostPort()
void DatagramSocket::setHostPort (const std::string & host, unsigned short port)
Set the hostname and port of the remote connection.
This method does not try to do a DNS host lookup. The DNS lookup will be done at connect time.
References _host, _port, and port.
Referenced by fromDOMElement().
setName()
void nidas::core::DatagramSocket::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by DatagramSocket(), getSocketAddress(), and operator=().
setNonBlocking()
void nidas::core::DatagramSocket::setNonBlocking (bool val) inline virtual
Do setNonBlocking(val) on underlying socket.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nonBlocking, _nusocket, and nidas::util::DatagramSocket::setNonBlocking().
Referenced by nidas::core::MultipleUDPSockets::connect(), nidas::core::MultipleUDPSockets::connected(), and fromDOMElement().
setPort()
void nidas::core::DatagramSocket::setPort (unsigned short port)
Set the the local port number.
setRequestType()
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::RawSampleInputStream::fromDOMElement(), nidas::dynld::RawSampleOutputStream::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), and nidas::dynld::XMLConfigService::schedule().
setSocketAddress()
void DatagramSocket::setSocketAddress (const nidas::util::SocketAddress & val)
Set address for this socket.
If address is INADDR_ANY or an address of a local interface, then a bind will be done to that address. If the address is a remote host, then a connect will be done, which sets the default sendto address.
References _sockAddr, and nidas::util::SocketAddress::clone().
Referenced by getSocketAddress().
setUnixPath()
void DatagramSocket::setUnixPath (const std::string & unixPath)
Set the pathname for the unix socket connection.
References _unixPath.
Referenced by fromDOMElement().
toDOMElement()
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const virtual inherited
Add my content into a DOMElement.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
Referenced by nidas::core::ServerSocket::toDOMParent().
toDOMParent()
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const virtual inherited
Create a DOMElement and append it to the parent.
Exceptions
xercesc::DOMException
Reimplemented in nidas::core::Variable, nidas::core::ServerSocket, nidas::core::Site, nidas::core::SampleTag, nidas::core::Project, nidas::core::DSMSensor, and nidas::core::DSMConfig.
write() [1/2]
size_t nidas::core::DatagramSocket::write (const struct iovec * iov, int iovcnt) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, and nidas::util::DatagramSocket::send().
write() [2/2]
size_t nidas::core::DatagramSocket::write (const void * buf, size_t len) inline virtual
Do the actual hardware write.
Exceptions
nidas::util::IOException
Implements nidas::core::IOChannel.
References _nusocket, len, and nidas::util::DatagramSocket::send().
writeNidasHeader()
bool nidas::core::DatagramSocket::writeNidasHeader () const inline virtual
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented from nidas::core::IOChannel.
Member Data Documentation
_conInfo
ConnectionInfo nidas::core::IOChannel::_conInfo private inherited
Referenced by nidas::core::IOChannel::getConnectionInfo(), and nidas::core::IOChannel::setConnectionInfo().
_dsm
const DSMConfig* nidas::core::IOChannel::_dsm private inherited
Referenced by nidas::core::IOChannel::getDSMConfig(), nidas::core::IOChannel::operator=(), and nidas::core::IOChannel::setDSMConfig().
_host
std::string nidas::core::DatagramSocket::_host private
Referenced by getHost(), getSocketAddress(), operator=(), and setHostPort().
_iochanRequester
IOChannelRequester* nidas::core::DatagramSocket::_iochanRequester private
Referenced by operator=(), and requestConnection().
_name
std::string nidas::core::DatagramSocket::_name private
Referenced by getName(), operator=(), and setName().
_nonBlocking
bool nidas::core::DatagramSocket::_nonBlocking private
Referenced by isNonBlocking(), operator=(), and setNonBlocking().
_nusocket
nidas::util::DatagramSocket* nidas::core::DatagramSocket::_nusocket private
Referenced by close(), connect(), getBufferSize(), getFd(), getInterfaces(), isNonBlocking(), operator=(), read(), setNonBlocking(), write(), and ~DatagramSocket().
_port
unsigned short nidas::core::DatagramSocket::_port private
Referenced by getPort(), getSocketAddress(), operator=(), and setHostPort().
_sockAddr
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::DatagramSocket::_sockAddr private
Referenced by DatagramSocket(), getSocketAddress(), operator=(), and setSocketAddress().
_unixPath
std::string nidas::core::DatagramSocket::_unixPath private
Referenced by getSocketAddress(), getUnixPath(), operator=(), and setUnixPath().
namespaceURI
XMLCh * DOMable::namespaceURI = 0 static private inherited
Referenced by nidas::core::DOMable::getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/DatagramSocket.h
nidas/core/DatagramSocket.cc