nidas: nidas::dynld::raf::Extract2D Class Reference
nidas::dynld::raf::Extract2D Class Reference abstract
#include <Extract2D.h>
Public Member Functions
Extract2D ()
virtual int parseRunstring (int argc, char **argv) throw ()
virtual int usage (const char *argv0)
virtual int run ()=0 throw ()
void sendHeader (dsm_time_t, SampleOutput *out)
Static Public Member Functions
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output)
Protected Member Functions
virtual size_t countParticles (Probe *probe, const unsigned char *record)=0
Count number of particles in a record, also report miss-aligned data.
virtual size_t computeDiodeCount (Probe *probe, const unsigned char *record)=0
Sum occluded diodes along the flight path.
void setTimeStamp (P2d_rec &record, Sample *samp)
Decode Sample time tag and place into outgoing record.
void setTimeStamp (PADS_rec &record, Sample *samp)
Protected Attributes
bool outputHeader
bool outputDiodeCount
Whether to output diode count histogram.
bool outputParticleCount
Whether to output particle count histogram.
bool copyAllRecords
Copy 100% of 2D records from source file to output file, no filtering.
string xmlFileName
list< string > inputFileNames
string outputFileName
int outputFileLength
SampleInputHeader header
set< dsm_sample_id_t > includeIds
set< dsm_sample_id_t > excludeIds
map< dsm_sample_id_t, dsm_sample_id_t > newids
size_t minNumberParticlesRequired
Static Protected Attributes
static bool interrupted = false
Constructor & Destructor Documentation
Extract2D()
Extract2D::Extract2D ()
Member Function Documentation
computeDiodeCount()
virtual size_t nidas::dynld::raf::Extract2D::computeDiodeCount (Probe * probe, const unsigned char * record) protected pure virtual
Sum occluded diodes along the flight path.
This increments for the whole flight. Help find stuck bits.
Returns
the number of diodes that had positives in the record.
Implemented in ExtractDMT, and ExtractFast2D.
countParticles()
virtual size_t nidas::dynld::raf::Extract2D::countParticles (Probe * probe, const unsigned char * record) protected pure virtual
Count number of particles in a record, also report miss-aligned data.
Implemented in ExtractDMT, and ExtractFast2D.
parseRunstring()
int Extract2D::parseRunstring (int argc, char ** argv) throw () virtual
Reimplemented in ExtractDMT.
References usage().
Referenced by ExtractFast2D::main().
run()
virtual int nidas::dynld::raf::Extract2D::run () throw () pure virtual
Implemented in ExtractDMT, and ExtractFast2D.
sendDefaultHeader()
void HeaderSource::sendDefaultHeader (SampleOutput * output) static inherited
Exceptions
nidas::util::IOException
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
sendHeader()
void Extract2D::sendHeader (dsm_time_t , SampleOutput * out) virtual
Exceptions
nidas::util::IOException
Implements nidas::core::HeaderSource.
References header, and nidas::core::SampleInputHeader::write().
setDefaults()
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
setTimeStamp() [1/2]
void Extract2D::setTimeStamp (P2d_rec & record, Sample * samp) protected
Decode Sample time tag and place into outgoing record.
References nidas::dynld::raf::P2d_rec::day, nidas::core::Sample::getTimeTag(), nidas::dynld::raf::P2d_rec::hour, nidas::dynld::raf::P2d_rec::minute, nidas::dynld::raf::P2d_rec::month, nidas::dynld::raf::P2d_rec::msec, nidas::dynld::raf::P2d_rec::second, nidas::util::UTime::toTm(), and nidas::dynld::raf::P2d_rec::year.
setTimeStamp() [2/2]
void Extract2D::setTimeStamp (PADS_rec & record, Sample * samp) protected
References nidas::dynld::raf::PADS_rec::day, nidas::core::Sample::getTimeTag(), nidas::dynld::raf::PADS_rec::hour, nidas::dynld::raf::PADS_rec::minute, nidas::dynld::raf::PADS_rec::month, nidas::dynld::raf::PADS_rec::msec, nidas::dynld::raf::PADS_rec::second, nidas::util::UTime::toTm(), and nidas::dynld::raf::PADS_rec::year.
setupSignals()
void Extract2D::setupSignals () static
References sigAction().
sigAction()
void Extract2D::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
usage()
int Extract2D::usage (const char * argv0) virtual
Reimplemented in ExtractDMT.
Member Data Documentation
copyAllRecords
bool nidas::dynld::raf::Extract2D::copyAllRecords protected
Copy 100% of 2D records from source file to output file, no filtering.
excludeIds
set<dsm_sample_id_t> nidas::dynld::raf::Extract2D::excludeIds protected
header
SampleInputHeader nidas::dynld::raf::Extract2D::header protected
Referenced by sendHeader().
includeIds
set<dsm_sample_id_t> nidas::dynld::raf::Extract2D::includeIds protected
inputFileNames
list<string> nidas::dynld::raf::Extract2D::inputFileNames protected
interrupted
bool Extract2D::interrupted = false static protected
minNumberParticlesRequired
size_t nidas::dynld::raf::Extract2D::minNumberParticlesRequired protected
newids
map<dsm_sample_id_t,dsm_sample_id_t> nidas::dynld::raf::Extract2D::newids protected
outputDiodeCount
bool nidas::dynld::raf::Extract2D::outputDiodeCount protected
Whether to output diode count histogram.
outputFileLength
int nidas::dynld::raf::Extract2D::outputFileLength protected
outputFileName
string nidas::dynld::raf::Extract2D::outputFileName protected
outputHeader
bool nidas::dynld::raf::Extract2D::outputHeader protected
outputParticleCount
bool nidas::dynld::raf::Extract2D::outputParticleCount protected
Whether to output particle count histogram.
xmlFileName
string nidas::dynld::raf::Extract2D::xmlFileName protected
The documentation for this class was generated from the following files:
nidas/dynld/raf/Extract2D.h
nidas/dynld/raf/Extract2D.cc