nidas: nidas::core::DSMEngineIntf::DSMAction Class Reference
nidas::core::DSMEngineIntf::DSMAction Class Reference
Send a command to a DSMEngine.
Public Member Functions
DSMAction (XmlRpc::XmlRpcServer *s)
void execute (XmlRpc::XmlRpcValue &params, XmlRpc::XmlRpcValue &result) throw ()
std::string help ()
Detailed Description
Send a command to a DSMEngine.
Expects one string parameter named "action", containing a value of "start", "stop", "restart", "quit", "reboot", or "shutdown".
Constructor & Destructor Documentation
DSMAction()
nidas::core::DSMEngineIntf::DSMAction::DSMAction (XmlRpc::XmlRpcServer * s) inline
Member Function Documentation
execute()
void DSMEngineIntf::DSMAction::execute (XmlRpc::XmlRpcValue & params, XmlRpc::XmlRpcValue & result) throw ()
References nidas::core::DSMEngine::getInstance(), PLOG, nidas::core::DSMEngine::quit(), nidas::core::DSMEngine::reboot(), nidas::core::DSMEngine::restart(), nidas::core::DSMEngine::shutdown(), nidas::core::DSMEngine::start(), and nidas::core::DSMEngine::stop().
help()
std::string nidas::core::DSMEngineIntf::DSMAction::help () inline
The documentation for this class was generated from the following files:
nidas/core/DSMEngineIntf.h
nidas/core/DSMEngineIntf.cc