nidas: nidas::core::SampleInputHeader Class Reference
nidas::core::SampleInputHeader Class Reference
#include <SampleInputHeader.h>
Classes
struct headerField
Public Member Functions
SampleInputHeader ()
SampleInputHeader (const SampleInputHeader &)
Copy constructor.
SampleInputHeader & operator= (const SampleInputHeader &)
Assignment operator.
~SampleInputHeader ()
void read (IOStream *iostream)
Read IOStream until the SampleInputHeader has been fully read.
bool parse (IOStream *iostream)
Parse the current contents of the IOStream for the SampleInputHeader.
int getLength () const
Get length in bytes of the header.
std::string toString () const
Render the header in string form.
size_t write (SampleOutput *output) const
size_t write (IOStream *iostream) const
void setArchiveVersion (const std::string &val)
const std::string & getArchiveVersion () const
void setSoftwareVersion (const std::string &val)
const std::string & getSoftwareVersion () const
void setProjectName (const std::string &val)
const std::string & getProjectName () const
void setSystemName (const std::string &val)
const std::string & getSystemName () const
void setConfigName (const std::string &val)
const std::string & getConfigName () const
void setConfigVersion (const std::string &val)
const std::string & getConfigVersion () const
Protected Member Functions
bool parseMagic (IOStream *iostream)
bool parseTag (IOStream *iostream)
bool parseValue (IOStream *iostream)
Private Types
enum parseStage {
PARSE_START , PARSE_MAGIC , PARSE_TAG , PARSE_VALUE ,
PARSE_DONE
}
Private Member Functions
void setDummyString (const std::string &)
const std::string & getDummyString () const
Private Attributes
std::string _archiveVersion
std::string _softwareVersion
std::string _projectName
std::string _systemName
std::string _configName
std::string _configVersion
std::string _dummy
int _minMagicLen
int _imagic
int _endTag
int _tagMatch
int _size
Size in bytes of the header.
char * _buf
char * _headPtr
enum nidas::core::SampleInputHeader::parseStage _stage
Static Private Attributes
static const struct headerField headers []
static const char * magicStrings []
Strings that can occur as the magic value at the beginning of a sample file.
static const int _nmagic = (int)(sizeof(magicStrings) / sizeof(magicStrings[0]))
static const int _ntags = (int)(sizeof(headers)/sizeof(struct headerField))
static const int HEADER_BUF_LEN = 256
Member Enumeration Documentation
parseStage
enum nidas::core::SampleInputHeader::parseStage private
Enumerator
PARSE_START
PARSE_MAGIC
PARSE_TAG
PARSE_VALUE
PARSE_DONE
Constructor & Destructor Documentation
SampleInputHeader() [1/2]
SampleInputHeader::SampleInputHeader ()
References _buf, _endTag, _headPtr, _minMagicLen, _nmagic, _ntags, HEADER_BUF_LEN, headers, and magicStrings.
SampleInputHeader() [2/2]
SampleInputHeader::SampleInputHeader (const SampleInputHeader & x)
Copy constructor.
Should not be used when a header is being parsed.
References _buf, _headPtr, and HEADER_BUF_LEN.
~SampleInputHeader()
SampleInputHeader::~SampleInputHeader ()
References _buf.
Member Function Documentation
getArchiveVersion()
const std::string& nidas::core::SampleInputHeader::getArchiveVersion () const inline
References _archiveVersion.
Referenced by NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), and StatsProcess::run().
getConfigName()
const std::string& nidas::core::SampleInputHeader::getConfigName () const inline
References _configName.
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::raf::SyncServer::openStream(), NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), DataDump::run(), DataStats::run(), DataPrep::run(), and StatsProcess::run().
getConfigVersion()
const std::string& nidas::core::SampleInputHeader::getConfigVersion () const inline
References _configVersion.
Referenced by NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), and StatsProcess::run().
getDummyString()
const std::string& nidas::core::SampleInputHeader::getDummyString () const inline private
References _dummy.
getLength()
int nidas::core::SampleInputHeader::getLength () const inline
Get length in bytes of the header.
References _size.
Referenced by HeaderUtil::run().
getProjectName()
const std::string& nidas::core::SampleInputHeader::getProjectName () const inline
References _projectName.
Referenced by NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), and StatsProcess::run().
getSoftwareVersion()
const std::string& nidas::core::SampleInputHeader::getSoftwareVersion () const inline
References _softwareVersion.
Referenced by NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), and StatsProcess::run().
getSystemName()
const std::string& nidas::core::SampleInputHeader::getSystemName () const inline
References _systemName.
Referenced by NidsMerge::printHeader(), SensorExtract::printHeader(), MergeVerifier::printHeader(), and StatsProcess::run().
operator=()
SampleInputHeader & SampleInputHeader::operator= (const SampleInputHeader & x)
Assignment operator.
Should not be used when a header is being parsed.
References _archiveVersion, _buf, _configName, _configVersion, _endTag, _headPtr, _imagic, _minMagicLen, _projectName, _size, _softwareVersion, _stage, _systemName, and _tagMatch.
parse()
bool SampleInputHeader::parse (IOStream * iostream)
Parse the current contents of the IOStream for the SampleInputHeader.
Returns
true: SampleInputHeader has been fully parsed. false: SampleInputHeader not completely parsed yet, another iostream->read() is necessary.
Exceptions
nidas::util::ParseException
References _size, _stage, PARSE_DONE, PARSE_MAGIC, PARSE_START, PARSE_TAG, PARSE_VALUE, parseMagic(), parseTag(), and parseValue().
Referenced by nidas::dynld::SampleInputStream::parseInputHeader(), and read().
parseMagic()
bool SampleInputHeader::parseMagic (IOStream * iostream) protected
Exceptions
nidas::util::ParseException
References _buf, _headPtr, _imagic, _minMagicLen, _nmagic, _size, _stage, nidas::core::IOStream::backup(), HEADER_BUF_LEN, len, magicStrings, PARSE_START, PARSE_TAG, and nidas::core::IOStream::readBuf().
Referenced by parse().
parseTag()
bool SampleInputHeader::parseTag (IOStream * iostream) protected
Exceptions
nidas::util::ParseException
References _buf, _endTag, _headPtr, _ntags, _size, _stage, _tagMatch, nidas::core::IOStream::backup(), HEADER_BUF_LEN, headers, len, PARSE_DONE, PARSE_START, PARSE_VALUE, and nidas::core::IOStream::readBuf().
Referenced by parse().
parseValue()
bool SampleInputHeader::parseValue (IOStream * iostream) protected
Exceptions
nidas::util::ParseException
References _buf, _endTag, _headPtr, _ntags, _size, _stage, _tagMatch, nidas::core::IOStream::backup(), HEADER_BUF_LEN, headers, PARSE_START, PARSE_TAG, nidas::core::IOStream::readBuf(), and nidas::core::SampleInputHeader::headerField::setFunc.
Referenced by parse().
read()
void SampleInputHeader::read (IOStream * iostream)
Read IOStream until the SampleInputHeader has been fully read.
This will perform one or more iostream->read()s.
Exceptions
nidas::util::IOException
References nidas::core::IOStream::getName(), parse(), nidas::core::IOStream::read(), and nidas::util::Exception::what().
Referenced by HeaderUtil::run().
setArchiveVersion()
void nidas::core::SampleInputHeader::setArchiveVersion (const std::string & val) inline
References _archiveVersion.
Referenced by HeaderUtil::run(), and nidas::core::HeaderSource::setDefaults().
setConfigName()
void nidas::core::SampleInputHeader::setConfigName (const std::string & val) inline
References _configName.
Referenced by HeaderUtil::run(), NidsMerge::sendHeader(), and nidas::core::HeaderSource::setDefaults().
setConfigVersion()
void nidas::core::SampleInputHeader::setConfigVersion (const std::string & val) inline
References _configVersion.
Referenced by HeaderUtil::run(), and nidas::core::HeaderSource::setDefaults().
setDummyString()
void nidas::core::SampleInputHeader::setDummyString (const std::string &) inline private
setProjectName()
void nidas::core::SampleInputHeader::setProjectName (const std::string & val) inline
References _projectName.
Referenced by HeaderUtil::run(), and nidas::core::HeaderSource::setDefaults().
setSoftwareVersion()
void nidas::core::SampleInputHeader::setSoftwareVersion (const std::string & val) inline
References _softwareVersion.
Referenced by HeaderUtil::run(), and nidas::core::HeaderSource::setDefaults().
setSystemName()
void nidas::core::SampleInputHeader::setSystemName (const std::string & val) inline
References _systemName.
Referenced by HeaderUtil::run(), and nidas::core::HeaderSource::setDefaults().
toString()
string SampleInputHeader::toString () const
Render the header in string form.
References _size, nidas::core::SampleInputHeader::headerField::getFunc, headers, len, magicStrings, and nidas::core::SampleInputHeader::headerField::tag.
Referenced by HeaderUtil::printHeader(), HeaderUtil::run(), and write().
write() [1/2]
size_t SampleInputHeader::write (IOStream * iostream) const
Exceptions
nidas::util::IOException
References toString(), and nidas::core::IOStream::write().
write() [2/2]
size_t SampleInputHeader::write (SampleOutput * output) const
Exceptions
nidas::util::IOException
References toString(), and nidas::core::SampleOutput::write().
Referenced by HeaderUtil::run(), nidas::core::HeaderSource::sendDefaultHeader(), NidsMerge::sendHeader(), SensorExtract::sendHeader(), and nidas::dynld::raf::Extract2D::sendHeader().
Member Data Documentation
_archiveVersion
std::string nidas::core::SampleInputHeader::_archiveVersion private
Referenced by getArchiveVersion(), operator=(), and setArchiveVersion().
_buf
char* nidas::core::SampleInputHeader::_buf private
Referenced by operator=(), parseMagic(), parseTag(), parseValue(), SampleInputHeader(), and ~SampleInputHeader().
_configName
std::string nidas::core::SampleInputHeader::_configName private
Referenced by getConfigName(), operator=(), and setConfigName().
_configVersion
std::string nidas::core::SampleInputHeader::_configVersion private
Referenced by getConfigVersion(), operator=(), and setConfigVersion().
_dummy
std::string nidas::core::SampleInputHeader::_dummy private
Referenced by getDummyString().
_endTag
int nidas::core::SampleInputHeader::_endTag private
Referenced by operator=(), parseTag(), parseValue(), and SampleInputHeader().
_headPtr
char* nidas::core::SampleInputHeader::_headPtr private
Referenced by operator=(), parseMagic(), parseTag(), parseValue(), and SampleInputHeader().
_imagic
int nidas::core::SampleInputHeader::_imagic private
Referenced by operator=(), and parseMagic().
_minMagicLen
int nidas::core::SampleInputHeader::_minMagicLen private
Referenced by operator=(), parseMagic(), and SampleInputHeader().
_nmagic
const int SampleInputHeader::_nmagic = (int)(sizeof(magicStrings) / sizeof(magicStrings[0])) static private
Referenced by parseMagic(), and SampleInputHeader().
_ntags
const int SampleInputHeader::_ntags = (int)(sizeof(headers)/sizeof(struct headerField)) static private
Referenced by parseTag(), parseValue(), and SampleInputHeader().
_projectName
std::string nidas::core::SampleInputHeader::_projectName private
Referenced by getProjectName(), operator=(), and setProjectName().
_size
int nidas::core::SampleInputHeader::_size private
Size in bytes of the header.
The value is saved, so that if we update one or more values, then we might be able to re-write the header without exceeding the original size.
Referenced by getLength(), operator=(), parse(), parseMagic(), parseTag(), parseValue(), and toString().
_softwareVersion
std::string nidas::core::SampleInputHeader::_softwareVersion private
Referenced by getSoftwareVersion(), operator=(), and setSoftwareVersion().
_stage
enum nidas::core::SampleInputHeader::parseStage nidas::core::SampleInputHeader::_stage private
Referenced by operator=(), parse(), parseMagic(), parseTag(), and parseValue().
_systemName
std::string nidas::core::SampleInputHeader::_systemName private
Referenced by getSystemName(), operator=(), and setSystemName().
_tagMatch
int nidas::core::SampleInputHeader::_tagMatch private
Referenced by operator=(), parseTag(), and parseValue().
HEADER_BUF_LEN
const int SampleInputHeader::HEADER_BUF_LEN = 256 static private
Referenced by parseMagic(), parseTag(), parseValue(), and SampleInputHeader().
headers
const SampleInputHeader::headerField SampleInputHeader::headers static private
Initial value:
= {
    { "archive version:",16, &SampleInputHeader::setArchiveVersion,
        &SampleInputHeader::getArchiveVersion,false },
    { "software version:",17, &SampleInputHeader::setSoftwareVersion,
        &SampleInputHeader::getSoftwareVersion,false },
    { "project name:",13, &SampleInputHeader::setProjectName,
        &SampleInputHeader::getProjectName,false },
    { "system name:",12, &SampleInputHeader::setSystemName,
        &SampleInputHeader::getSystemName,false },
    { "config name:",12, &SampleInputHeader::setConfigName,
        &SampleInputHeader::getConfigName,false },
    { "config version:",15, &SampleInputHeader::setConfigVersion,
        &SampleInputHeader::getConfigVersion,false },
    { "site name:",10, &SampleInputHeader::setSystemName,
        &SampleInputHeader::getSystemName,true },
    { "observation period name:",24, &SampleInputHeader::setDummyString,
        &SampleInputHeader::getDummyString,true },
    { "xml name:",9, &SampleInputHeader::setDummyString,
        &SampleInputHeader::getDummyString,true },
    { "xml version:",12, &SampleInputHeader::setDummyString,
        &SampleInputHeader::getDummyString,true },
    { "end header\n",11, 0, 0,false },
}
Referenced by parseTag(), parseValue(), SampleInputHeader(), and toString().
magicStrings
const char * SampleInputHeader::magicStrings static private
Initial value:
= {
     "NIDAS (ncar.ucar.edu)\n",
     "NCAR ADS3\n"
}
Strings that can occur as the magic value at the beginning of a sample file.
magicString[0] is the value written to new sample files. The other strings, magicString[1] etc, are historic values that may be found in existing sample files.
Referenced by parseMagic(), SampleInputHeader(), and toString().
The documentation for this class was generated from the following files:
nidas/core/SampleInputHeader.h
nidas/core/SampleInputHeader.cc