nidas: nidas::core::ProjectConfigs Class Reference
nidas::core::ProjectConfigs Class Reference
#include <ProjectConfigs.h>
Public Member Functions
ProjectConfigs ()
~ProjectConfigs ()
const ProjectConfig * getConfig (const nidas::util::UTime &begin) const
const ProjectConfig * getConfig (const std::string &name) const
const std::list< const ProjectConfig * > & getConfigs () const
void addConfigByTime (ProjectConfig *val)
Add a project configuration, inserting it in the list, which should be sorted by time.
void addConfigByName (ProjectConfig *val) throw ()
Add a project configuration, replacing an existing configuration if the name matches, otherwise appending the configuration on the list.
void removeConfig (const ProjectConfig *val)
void parseXML (const std::string &xmlFileName)
void writeXML (const std::string &xmlFileName)
void fromDOMElement (const xercesc::DOMElement *)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent) const
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node) const
Private Attributes
std::string _xmlName
std::list< const ProjectConfig * > _constConfigs
std::list< ProjectConfig * > _configs
Constructor & Destructor Documentation
ProjectConfigs()
ProjectConfigs::ProjectConfigs ()
~ProjectConfigs()
ProjectConfigs::~ProjectConfigs ()
References _configs.
Member Function Documentation
addConfigByName()
void ProjectConfigs::addConfigByName (ProjectConfig * val) throw ()
Add a project configuration, replacing an existing configuration if the name matches, otherwise appending the configuration on the list.
References nidas::core::ProjectConfig::getName().
Referenced by fromDOMElement().
addConfigByTime()
void ProjectConfigs::addConfigByTime (ProjectConfig * val)
Add a project configuration, inserting it in the list, which should be sorted by time.
If the beginning time is equal to the beginning time of an existing project configuration, and the end time is prior to or equal to the beginning time of the next configuration, the existing configuration is replaced. Exceptions are thrown if project configuration times are overlapping.
Exceptions
nidas::util::InvalidParameterException
References _configs, _constConfigs, nidas::core::ProjectConfig::getBeginTime(), and nidas::core::ProjectConfig::getEndTime().
Referenced by ProjConfigIO::addConfigByTime(), and ProjConfigIO::termConfig().
fromDOMElement()
void ProjectConfigs::fromDOMElement (const xercesc::DOMElement * node)
Exceptions
nidas::util::InvalidParameterException
References addConfigByName(), nidas::core::ProjectConfig::fromDOMElement(), and nidas::core::XDOMElement::getNodeName().
Referenced by parseXML().
getConfig() [1/2]
const ProjectConfig * ProjectConfigs::getConfig (const nidas::util::UTime & begin) const
Exceptions
nidas::util::InvalidParameterException
References _constConfigs, _xmlName, nidas::util::UTime::format(), nidas::core::ProjectConfig::getBeginTime(), and nidas::core::ProjectConfig::getEndTime().
Referenced by StatsProcess::listOutputSamples(), DataPrep::run(), StatsProcess::run(), and nidas::core::DSMServerApp::run().
getConfig() [2/2]
const ProjectConfig * ProjectConfigs::getConfig (const std::string & name) const
Exceptions
nidas::util::InvalidParameterException
References _constConfigs, _xmlName, and nidas::core::ProjectConfig::getName().
getConfigs()
const std::list< const ProjectConfig * > & ProjectConfigs::getConfigs () const
References _constConfigs.
Referenced by ProjConfigIO::addConfigByTime(), ProjConfigIO::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), ProjConfigIO::termConfig(), and toDOMElement().
parseXML()
void ProjectConfigs::parseXML (const std::string & xmlFileName)
Exceptions
nidas::core::XMLException
nidas::util::InvalidParameterException
References _xmlName, fromDOMElement(), and nidas::core::XMLParser::parse().
Referenced by StatsProcess::listOutputSamples(), DataPrep::run(), ProjConfigIO::run(), StatsProcess::run(), and nidas::core::DSMServerApp::run().
removeConfig()
void ProjectConfigs::removeConfig (const ProjectConfig * val)
References _configs, and _constConfigs.
Referenced by ProjConfigIO::termConfig().
toDOMElement()
xercesc::DOMElement * ProjectConfigs::toDOMElement (xercesc::DOMElement * node) const
Exceptions
xercesc::DOMException
References getConfigs(), and nidas::core::ProjectConfig::toDOMParent().
Referenced by toDOMParent(), and writeXML().
toDOMParent()
xercesc::DOMElement * ProjectConfigs::toDOMParent (xercesc::DOMElement * parent) const
Exceptions
xercesc::DOMException
References nidas::core::DOMable::getNamespaceURI(), and toDOMElement().
writeXML()
void ProjectConfigs::writeXML (const std::string & xmlFileName)
Exceptions
nidas::core::XMLException
nidas::util::IOException
References fd, nidas::core::XMLImplementation::getImplementation(), nidas::core::DOMable::getNamespaceURI(), nidas::core::XMLWriter::setPrettyPrint(), toDOMElement(), and nidas::core::XMLWriter::write().
Referenced by ProjConfigIO::addConfigByTime(), and ProjConfigIO::termConfig().
Member Data Documentation
_configs
std::list<ProjectConfig*> nidas::core::ProjectConfigs::_configs private
Referenced by addConfigByTime(), removeConfig(), and ~ProjectConfigs().
_constConfigs
std::list<const ProjectConfig*> nidas::core::ProjectConfigs::_constConfigs private
Referenced by addConfigByTime(), getConfig(), getConfigs(), and removeConfig().
_xmlName
std::string nidas::core::ProjectConfigs::_xmlName private
Referenced by getConfig(), and parseXML().
The documentation for this class was generated from the following files:
nidas/core/ProjectConfigs.h
nidas/core/ProjectConfigs.cc