nidas: nidas::core::Resampler Class Reference
nidas::core::Resampler Class Reference abstract
Interface for a resampler, simply a SampleClient and a SampleSource.
#include <Resampler.h>
Public Member Functions
virtual ~Resampler ()
virtual void flush ()=0 throw ()
Both SampleClient and SampleSource have a flush() method.
virtual void connect (SampleSource *source)=0
Connect the resampler to a source.
virtual void disconnect (SampleSource *source)=0 throw ()
virtual bool receive (const Sample *s)=0
Method called to pass a sample to this client.
virtual SampleSource * getRawSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual SampleSource * getProcessedSampleSource ()=0
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addSampleTag (const SampleTag *)=0
Add a SampleTag to this SampleSource.
virtual void removeSampleTag (const SampleTag *)=0
virtual std::list< const SampleTag * > getSampleTags () const =0
What SampleTags am I a SampleSource for?
virtual SampleTagIterator getSampleTagIterator () const =0
virtual void addSampleClient (SampleClient *c)=0
Add a SampleClient of all Samples to this SampleSource.
virtual void removeSampleClient (SampleClient *c)=0
Remove a SampleClient from this SampleSource.
virtual void addSampleClientForTag (SampleClient *c, const SampleTag *)=0
Add a SampleClient to this SampleSource.
virtual void removeSampleClientForTag (SampleClient *c, const SampleTag *)=0
Remove a SampleClient for a given SampleTag from this SampleSource.
virtual int getClientCount () const =0
How many SampleClients are currently in my list.
virtual const SampleStats & getSampleStats () const =0
Detailed Description
Interface for a resampler, simply a SampleClient and a SampleSource.
Constructor & Destructor Documentation
~Resampler()
virtual nidas::core::Resampler::~Resampler () inline virtual
Member Function Documentation
addSampleClient()
virtual void nidas::core::SampleSource::addSampleClient (SampleClient * c) pure virtual inherited
Add a SampleClient of all Samples to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::AsciiOutput::connect(), nidas::core::SampleArchiver::connect(), nidas::dynld::SampleProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), DataDump::run(), DataStats::run(), and nidas::core::RemoteSerialConnection::setSensor().
addSampleClientForTag()
virtual void nidas::core::SampleSource::addSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::raf::CVIProcessor::attachLVInput(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), and nidas::core::NearestResampler::connect().
addSampleTag()
virtual void nidas::core::SampleSource::addSampleTag (const SampleTag *) pure virtual inherited
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::addSampleTag(), nidas::dynld::RawSampleService::fromDOMElement(), DataPrep::run(), and StatsProcess::run().
connect()
virtual void nidas::core::Resampler::connect (SampleSource * source) pure virtual
Connect the resampler to a source.
Exceptions
nidas::util::InvalidParameterException
Implemented in nidas::core::NearestResampler, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, and nidas::core::NearestResamplerAtRate.
disconnect()
virtual void nidas::core::Resampler::disconnect (SampleSource * source) throw () pure virtual
Implemented in nidas::core::NearestResampler, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, and nidas::core::NearestResamplerAtRate.
flush()
virtual void nidas::core::Resampler::flush () throw () pure virtual
Both SampleClient and SampleSource have a flush() method.
Redeclaring it here as pure virtual removes the ambiguity.
Implements nidas::core::SampleClient.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, and nidas::core::NearestResampler.
getClientCount()
virtual int nidas::core::SampleSource::getClientCount () const pure virtual inherited
How many SampleClients are currently in my list.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getClientCount().
getProcessedSampleSource()
virtual SampleSource* nidas::core::SampleSource::getProcessedSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SampleArchiver::connectSource(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), and nidas::core::SampleArchiver::disconnectSource().
getRawSampleSource()
virtual SampleSource* nidas::core::SampleSource::getRawSampleSource () pure virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::connect(), nidas::core::SampleArchiver::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SampleArchiver::disconnectSource().
getSampleStats()
virtual const SampleStats& nidas::core::SampleSource::getSampleStats () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::core::SamplePipeline::getSampleStats(), nidas::dynld::RawSampleService::printClock(), nidas::core::SampleArchiver::printStatus(), nidas::dynld::raf::SyncRecordGenerator::printStatus(), and nidas::dynld::RawSampleService::printStatus().
getSampleTagIterator()
virtual SampleTagIterator nidas::core::SampleSource::getSampleTagIterator () const pure virtual inherited
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::CVIProcessor::connectSource(), nidas::core::SamplePipeline::disconnect(), and nidas::core::SamplePipeline::getSampleTagIterator().
getSampleTags()
virtual std::list<const SampleTag*> nidas::core::SampleSource::getSampleTags () const pure virtual inherited
What SampleTags am I a SampleSource for?
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::SampleInputStream, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::dynld::psql::PSQLProcessor, nidas::dynld::isff::PacketInputStream, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::core::DSMSensor.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::SampleAverager::connect(), nidas::core::NearestResampler::connect(), nidas::core::DSMEngine::connectOutputs(), nidas::core::SampleArchiver::connectSource(), nidas::dynld::SampleProcessor::connectSource(), nidas::dynld::StatisticsProcessor::connectSource(), nidas::core::SamplePipeline::getSampleTags(), DataPrep::run(), and nidas::dynld::RawSampleService::schedule().
receive()
virtual bool nidas::core::SampleClient::receive (const Sample * s) pure virtual inherited
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Exceptions
Implemented in nidas::dynld::raf::CVIOutput, nidas::dynld::AsciiOutput, DumpClient, DataStats, SampleDispatcher, DumpClient, nidas::dynld::StatisticsCruncher, nidas::dynld::SampleOutputStream, nidas::dynld::raf::SyncRecordReader, nidas::dynld::raf::CVIProcessor, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::RemoteSerialConnection, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::DSMSensor, TestClient, nidas::dynld::raf::SyncRecordSource, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::isff::GOESOutput, and nidas::dynld::UDPSampleOutput.
removeSampleClient()
virtual void nidas::core::SampleSource::removeSampleClient (SampleClient * c) pure virtual inherited
Remove a SampleClient from this SampleSource.
Exceptions
Implemented in nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::DSMSensor, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::DSMEngine::closeOutputs(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::SampleProcessor::disconnect(), nidas::core::SamplePipeline::disconnect(), DataDump::run(), DataStats::run(), nidas::core::SampleArchiver::~SampleArchiver(), and nidas::dynld::SampleProcessor::~SampleProcessor().
removeSampleClientForTag()
virtual void nidas::core::SampleSource::removeSampleClientForTag (SampleClient * c, const SampleTag *) pure virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Exceptions
Implemented in nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleSorter, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, nidas::core::SampleSourceSupport, nidas::core::SamplePipeline, and nidas::dynld::SampleInputStream.
removeSampleTag()
virtual void nidas::core::SampleSource::removeSampleTag (const SampleTag *) pure virtual inherited
Exceptions
Implemented in nidas::core::DSMSensor, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordSource, nidas::core::SampleSourceSupport, nidas::core::SampleSorter, nidas::core::SamplePipeline, nidas::core::SampleIOProcessor, nidas::core::SampleBuffer, nidas::core::SampleAverager, nidas::core::NearestResamplerAtRate, nidas::core::NearestResampler, and nidas::dynld::SampleInputStream.
Referenced by nidas::core::SamplePipeline::removeSampleTag().
The documentation for this class was generated from the following file:
nidas/core/Resampler.h